### ISSUE TITLE
Shattered Pixel Dungeon looks ready for Version 1.0

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#100]
Version numbers 0.x gives "beta" feeling, while SPD already looks ready for gaming for a couple of updates.

Or is it "eternal beta"?

**Comment by 00-Evan** [comment]
not eternal beta, but 1.0 won't happen for a little while.

1.0 will basically be when i'm ready to say that I am done making major, core changes to the game.
