### ISSUE TITLE
It is possible to obtain more than 6 dungeon berries

### ISSUE THREAD

**Issue by olekhov** [00-Evan/shattered-pixel-dungeon#1000]
The Natures' Bounty +2 talent reads: 

> The Huntress can find 6 berries hidden in tall grass as she explores the earlier stages of the dungeon

I managed to obtain 10 berries: I had full inventory and left berries unpicked when they appeared.
Lately I revisited early stages of dungeon and picked all left berries. To my surprise, there were 10 of them.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this, the game always drops a total of exactly 4 or 6 berries in my testing.

There were internal code changes for this talent between 1.2.3 and the current 1.3 beta. Did you get some of your berry drops on this run before updating to the beta?

**Comment by 00-Evan** [comment]
That would probably explain it then, it's just a bit of luck on your part as the run was caught between the old and new logic.
