### ISSUE TITLE
Frame Limit on PC

### ISSUE THREAD

**Issue by Danee2108** [00-Evan/shattered-pixel-dungeon#1001]
This is a small issue that happens on the .jar version of the beta, I haven't tried it on the steam version, and it doesn't happen on mobile versions due to the device's frame limit.

When playing, either on fullscreen or windowed mode, frames reach insanely high numbers (which is good) due to the nature of the graphics, but this creates quite noisy GPU coil whine. I looked for a "Limit FPS" option in the game settings menu, but I don't think there is one. The only way to limit FPS I've found is by using the NVIDIA Control Panel.

Is this a planned feature? I have no idea if it would be possible to add it.

Here're (Here are?) a couple of screenshots, thanks for reading:

Unlimited FPS and Coil Whine
![ShatteredPD_UnlimitedFPS](https://user-images.githubusercontent.com/88794940/175983329-0c36a886-5f17-4453-9678-460fa5b53443.png)

Limited FPS, used NVIDIA control panel
![ShatteredPD_LimitedFPS](https://user-images.githubusercontent.com/88794940/175983397-a0de7551-0208-440a-b274-6923c1d6a83e.png)

**Comment by 00-Evan** [comment]
Shattered already enables vSync by default (there's no reason to have it off on a game like this), so something in your graphics driver is forcibly disabling it.
