### ISSUE TITLE
winning a daily run does not record a win

### ISSUE THREAD

**Issue by danastasio** [00-Evan/shattered-pixel-dungeon#1003]
Hello,

I tried out the new daily run feature (which is awesome) and won. However, on my ranking page the most recent game is the game previous to my daily game win. On the daily page of the ranking, the listings are empty.

![Screenshot_20220628-220825_Shattered Pixel Dungeon](https://user-images.githubusercontent.com/23290366/176458841-76e77f15-924d-4c92-8299-2b2b0c658aa2.png)
![Screenshot_20220628-220815_Shattered Pixel Dungeon](https://user-images.githubusercontent.com/23290366/176458847-1f97d648-d5b7-4119-9ebc-aeb5d1398ba8.png)

All of the wins shown are from other wins. The most recent win is not shown.

Version 1.3.0-beta-2.

I used "Let's call it a day" instead of resurfacing.

**Comment by 00-Evan** [comment]
This is a known bug with Google Play Games sync, should be fixed soon.

**Comment by 00-Evan** [comment]
This should now be fixed as of BETA-3
