### ISSUE TITLE
Application freezes when amulet Is recovered

### ISSUE THREAD

**Issue by il-ponz** [00-Evan/shattered-pixel-dungeon#1009]
version 1.3.0 beta 3. Android on redmi note 9 pro.
This happened twice with different classes in daily runs, i'm sharing game data, i hope It can help.
As soon as i recover the amulet and call It a day the screen freezes and i have to close the app. Run Is not saved in hall of fame 
![Screenshot_2022-07-05-16-16-38-685_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/28760264/177344680-aac5b986-3783-49c9-8eaa-d7e4605b513b.jpg)

**Comment by 00-Evan** [comment]
This was just fixed with the release of RC-1
