### ISSUE TITLE
Missing room keys

### ISSUE THREAD

**Issue by kmaris** [00-Evan/shattered-pixel-dungeon#101]
It seems after playing shattered PD that keys for locked rooms are quite often nowhere to be found. It's safe to assume they may spawn behind the locked doors.

Has this behavior been observed by others? I am certain I could always find all room keys for a level in vanilla PD. When I notice this happening I will usually waste the characters entire supply of health and food searching every tile available to verify my suspicions (using the actual 'Search' mode by double tapping the magnifying glass).

**Comment by 00-Evan** [comment]
When this happens, is there a room on the floor above with a broken floor at a well in the darkness?

This is intentional, you need to drop into these rooms from above.

**Comment by kmaris** [comment]
You know, I've dropped down those open floors often and have never put two and two together. Thanks for such a quick response, and fwiw thanks for all the work you've put into this and I prefer shattered over PD.
