### ISSUE TITLE
gotcha! and Outmaneuvered badges 

### ISSUE THREAD

**Issue by aceventura82** [00-Evan/shattered-pixel-dungeon#1010]
I'm on version 1.3.0 beta 2, defeated  the prison boss and cave boss as requested to earn the gotcha! and Outmaneuvered badges, got the badge message in the messages after I beat them, but the badge still grayout in the badge section

**Comment by 00-Evan** [comment]
Were you playing with a custom seed or on a daily run? Those runs are not eligible to unlock badges.

**Comment by aceventura82** [comment]
I did open the custom seed menu but cancel it an didn't add any custom seeds

**Comment by aceventura82** [comment]
Well, I did a android data backup from last stable version and copy it after intall the beta version?
Maybe there is a conflict  there?

**Comment by 00-Evan** [comment]
yeah something like that could easily override the badge unlock.

**Comment by aceventura82** [comment]
Just played a new game an got the badge correclty
