### ISSUE TITLE
希望能够添加存档导入导出功能

### ISSUE THREAD

**Issue by QiongHuapai** [00-Evan/shattered-pixel-dungeon#1013]
我是像素地牢老玩家，从17年开始就一直在玩，破碎是很不错的一个。有个小建议就是希望游戏中能够增加数据导入导出功能。也可以用绑定账号的方式将存档保留，配合即将增加的积分功能，也可以绑定到账号里。

**Comment by 00-Evan** [comment]
Thanks for the suggestion, but I'm afraid I don't have any plans to add any account functionality. Setting up and managing a server would be a lot of work that I could spent working on game content instead.
