### ISSUE TITLE
[Feature Request] Discord Rich Presence Support

### ISSUE THREAD

**Issue by megz15** [00-Evan/shattered-pixel-dungeon#1016]
Hi, first off I'm a big fan, thank you very much for this fork 😊

I want to suggest implementing rich presence so that it's shown on Discord that we're playing the game, maybe along with other details like world seed, hero class, current floor / level / HP and score.

**Comment by 00-Evan** [comment]
I appreciate that a feature like this would be nice to have, but my time as a developer is limited and I would rather spend it working on core game content or feature integrations that are more useful to gameplay (such as Steam achievements or cloud sync).
