### ISSUE TITLE
paralyzed by electricity even after prison guard pulls me out

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1017]
I stepped on shocking trap while two prison guards are in water next to me.  A third person guard pulls me out with his chain.  Even though I'm no longer at the trap, I am paralyzed the full duration of the electricity.  I expected to get out of paralysis before the electricity finished since I was no longer in it.
![Screenshot_20220709-005608](https://user-images.githubusercontent.com/8593007/178092255-6b4b451a-25bc-4016-a3b0-2f2580e4c99a.png)

**Comment by 00-Evan** [comment]
Electricity applies paralysis for its remaining duration regardless how long you're in it. This is so having partial paralysis resistance doesn't make the electricity field harmless.

**Comment by protective1** [comment]
In other cases where I accidentally step on a shocking trap, I often get a chance to act before the electricity ends.  Is this because I resisted paralysis?  In the example above, I got pulled out by the guard as soon as the electricity started, but was not able to move again until the electricity (across the room) ended.  So they're are many cases where the paralysis from being on the electricity does not last as long as it did in the example above (when I got pulled out of the electricity).  Is this just a matter of bad luck on the resist paralysis roll?

**Comment by 00-Evan** [comment]
The trap is designed to frequently damage the player, which gives them a higher chance to resist paralysis. In this case you were removed from the trap and attacked by the guard instead. In both cases though it's just a chance, you can still get stunned for the full duration.
