### ISSUE TITLE
Dried Rose equippable before Ghost quest using scroll of transmutation

### ISSUE THREAD

**Issue by Tiger-Tom** [00-Evan/shattered-pixel-dungeon#1020]
If you use a transmutation scroll on an artifact before completing the Sad Ghost's quest, then you will have an unusable dried rose in your artifacts slot, and additionally it will have the text that is usually only shown when the quest is completed. Perhaps when an artifact is transmuted into a rose before the finishing of that quest, it could drop on the ground or in the inventory?
![Screenshot_20220709-102621](https://user-images.githubusercontent.com/55163690/178126791-1b39b44c-320d-41eb-9d48-0846ef94b0b7.png)

**Comment by 00-Evan** [comment]
I'm fine with this edge case, the rose still can't be used until the player had done the quest, and it can still be unequipped.
