### ISSUE TITLE
attacking with glaive in garden

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1021]
I'm in a garden two spaces away from a succubus while weilding a glaive.  Whenever I click on the succubus to attack, my character moves toward the succubus instead of attacking.  I can see the succubus, so it's not seemingly an invisibility issue.

**Comment by 00-Evan** [comment]
Were you charmed by the succubus? That would prevent attacking.

**Comment by protective1** [comment]
That's a possibility.  The resulting attack from the succubus killed me, so I didn't take a screenshot.

**Comment by protective1** [comment]
I'm assuming I was charmed and just didn't notice.
