### ISSUE TITLE
wand of corrosion not activating burning trap

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1023]
A fly was hovering over a burning trap.  I shot the square with wand of corrosion but trap did not go off as I would have expected.
![Screenshot_20220711-113831](https://user-images.githubusercontent.com/8593007/178302664-6e3ef4b5-24fb-41b0-9cd5-889bbe04000f.png)

**Comment by 00-Evan** [comment]
The corrosion bolt with only trigger a trap if it strikes the floor. As there was an enemy at that position, it struck them instead.
