### ISSUE TITLE
"Master of Many Trades" badge incorrectly shows as partially completed

### ISSUE THREAD

**Issue by ivanpu** [00-Evan/shattered-pixel-dungeon#1025]
Version: 1.3.1 (Android)
As you con see in the screenshot, I don't yet have the "Victory!" badge (correctly), but "Master of Many Trades" says that I did get the amulet with a mage.
![Screenshot_20220712-230321_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/2607888/178586388-bd53cf3b-7306-465d-8c9c-62b5757d9440.jpg)

**Comment by 00-Evan** [comment]
These are recorded as two different variables internally, although they should always both get assigned at the same time. In a case such as this there's not really much to do as there's no indication of why one badge might be unlocked while the other isn't.
