### ISSUE TITLE
bomb exploded after tengu killed

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1026]
I dropped items for safe keeping next to the stairs in tengu's lair before fighting him.  These items disappear when fighting tengu, as expected.  I threw a bomb at tengu during phase 2 of the fight.  He died before the bomb went off.  The lit bomb and all of the items I previously dropped on the floor were warped to the post-tengu room.  The bomb exploded next to my items and I think destroyed some of them.
The issue is that the game should probably let the bomb explode in tengu phase 2 before auto-placing all of the items.

**Comment by 00-Evan** [comment]
fixed in commit 87023151a733fc09fb2cbdf22a034434bef6f856
