### ISSUE TITLE
Thief improvements idea

### ISSUE THREAD

**Issue by przemyslaw-zan** [00-Evan/shattered-pixel-dungeon#1028]
Since recently there was some talk about additional "side" floors with special purposes, I think there is _some room to improve_ (pun not intended) mechanics of thieves.

In the past, unblessed ankh used to just delete items without the ability to gain them back. This was changed, and player now can fight back and reclaim his items. This was great improvement. However, thieves can just steal something from the player, and if the player is busy fighting three skeletons at the time, stolen item is gone forever. I think this is too punishing. Especially with champions challenge, and projecting thief. This guy can steal the item and dissapear within two turns, thats just unfair. Here's my idea:

There should be a way to regain the item. Stolen items, instead of just vanishing, could instead be taken away to a treasure stash of the thieves. This could be either a hidden room somewhere on the floor. or even beforementioned "side" floor - a dedicated thieves den. Player could go in there, and fight back with thieves to regain the items he lost. There could also be some miniboss, eg. King of thieves.

Perhaps to not make the game too easy because of this, thieves could be made more effective, and not run slower when they cary stolen goods.

This also opens up some edge cases, eg. What happens when a thief spawns later than the prison, and there is no thieves den ahead to stash his treasures. Forcing player to go all the way back could be too annoying, so perhaps in those cases, thieves could just not steal? Or maybe steal, but they would just stay on the floor with the stolen item.

**Comment by 00-Evan** [comment]
Thieves actually originally didn't fully run away with items, you could find them later and get your item back. Because of this, the best strategy was to just let thieves run away because you knew you could always get your item back anyway. I specifically made them permanently steal items so that the player would want to chase after and catch up to them.
