### ISSUE TITLE
Ascension route boss

### ISSUE THREAD

**Issue by przemyslaw-zan** [00-Evan/shattered-pixel-dungeon#1029]
Ascension route was great addition in the last patch, greatly appreciated. It gave me an idea: perhaps on the way back, player could fight the real, hidden final boss of the dungeon: the Rat King. He has no purpose in shattered at the moment, so he could act as a final boss of the ascencion route. There is some lore to explore here: perhaps he is the guardian of the evil below, and will do everything in his power to keep the amulet of yendor from reaching the surface, which could have dire consequences? Perhaps he is tougher to fight when player steals his gold after defeating the Goo, because he's angry? Perhaps whether the player wakes him up or not influences the fight in some way? He could be really cool hidden ending of the game, that requires player to take some specific steps to unlock (ascension route + some combination of stealing his gold and waking him up).

It could also be something way simpler, like a cool easter egg, eg. a badge for not stealing from the king and waking him up. Maybe even a badge for giving him (leaving in his room) an item, such as some food?

Just really loose idea, hopefully it inspires you to make something really cool :)

**Comment by 00-Evan** [comment]
I don't intend to add any new bosses at the moment, and if I did add one it wouldn't be rat king. I'm happy with him being more of a light-hearted easter egg character.

There actually already is something rat king can do though, have you tried giving him a crown?

**Comment by przemyslaw-zan** [comment]
Oh right, I knew about the crown thing and did it in the past, just forgot about it :)
