### ISSUE TITLE
Ring of Might reveals itself before it's identified.

### ISSUE THREAD

**Issue by benkorpella** [00-Evan/shattered-pixel-dungeon#1030]
The Ring of Might shows its strength increase in the character stats before it's identified. See 2 images below.

![Screenshot_20220713-204837.png](https://user-images.githubusercontent.com/26315699/178879242-40a63b8c-bb5c-4827-8122-6027abac6161.png)

![Screenshot_20220713-204826.png](https://user-images.githubusercontent.com/26315699/178879465-e91fff2e-f22a-4239-9677-9e4e760b6aad.png)

**Comment by 00-Evan** [comment]
I'm okay with this, lots of items can be indirectly identified by seeing how they affect your stats, ring of might is just the most obvious.
