### ISSUE TITLE
Alternate routes and zones

### ISSUE THREAD

**Issue by BloodRaven0** [00-Evan/shattered-pixel-dungeon#1031]
First off, this is a really big "expansion" on the original Pixel Dungeon concept and content, and is just an idea you could pin to your "Updates in the far future" board.

Similar to how Dead Cells routes work, you could have alternate zones and routes the players could take in a given playthrough. This will add more variety, replayability, choices and content to the game.

The enterances to the new zones could be hidden or unlocked with an item (rewarded by certain quests (un)completed in a certain way) and will be placed after the boss rooms - For example a route could require the rotberry seed that you'd normally give to the wizard. Once a route is chosen, the other route will cave in, blocking the player from exploring both zones, (and getting more scrolls/potions than a run should have).

The new zones could differ from the current ones in a number of ways:
-New aesthetics, music and theme
-New enemies
-Bigger chance for certain seeds, potions, scrolls, enchantments, wands, traps, items etc over others
-New quests
-New bosses at the end of each zone

A few themes I can think off the top of my head:

-Catacombs (alternative to prison) - would have more undead and necromancers, as well as mummies and other undead and wraith-type enemies. Bigger chance for grim-enchanted weapons. End boss is abomination

-Frozen caves (alternative to prison/caves?) - would have abundance of frost effects and maybe young frost elementals, as well as the good ol' ice slide puzzles (special ice tiles that propel you forward until you hit an object or land on a normal tile). Icecap and freezing enchantments are more common here. End boss is yeti

-Crystal caverns (alternative to caves) - could have special crystals (similar to traps) that produce a certain effect when damaged. End boss is crystal golem

-Mushroom kingdom (alternative to dwarf kingdom) - weak friendly mushroom NPCs that are being attacked by big monsters with an appetite for mushrooms. Could give small gifts if you manage to save them. End boss is a giant mushroom-devouring monstrosity (several tiles big) that you have to take down with the help of the mushroom people you saved in the previous floors (the more you save, the easier the fight will be).

I think such an expansion on the original content would serve as an awesome outlet for your creativity in game design, while giving us new and exciting content for our beloved game.

**Comment by 00-Evan** [comment]
I've already already mentioned this in a blog post: https://shatteredpixel.com/blog/shattered-pixel-dungeon-in-2022.html#alternate-paths

It would be nice to work on, but as mentioned it woudl be a massive undertaking, so it isn't currently planned.
