### ISSUE TITLE
No warning using scroll of upgrade on enchanted gear +4 or greater

### ISSUE THREAD

**Issue by dplynx** [00-Evan/shattered-pixel-dungeon#1032]
Although I’m not sure why this is an aspect of gameplay in the first place, I feel like the game generally tries to protect the player from unintentional loss of SoUs and in a similar way am always surprised to lose enchantments without warning (mostly due to forgetting I had an enchantment applied and had intended to make magical infusions from here on). I think a warning for this irreversible loss is in line with the player-friendly design of the UI.

**Comment by 00-Evan** [comment]
Scrolls of upgrade include an explanation of this mechanic in their description.

**Comment by dplynx** [comment]
Sorry for not being more clear. I’m referring to confirmation dialog when attempting to upgrade an enchanted item (are you sure?)

**Comment by 00-Evan** [comment]
I understood what you are referring to, I am saying that such a dialog isn't needed as SoU already include an explanation of this mechanic in their description. In general I don't want to add 'are you sure?' messages unless they're really necessary.

**Comment by dplynx** [comment]
Ok, got you. I’m not sure if there’s a back-out point after you’ve read the scroll and before you’ve selected the target item to where it makes sense anyway.

Still, as a gameplay mechanic, even though I am and have always been fully aware of it, I make the mistake frequently enough, and it feels bad enough, that I wonder about its implementation. Maybe something like “SoUs suppress existing enchantments until arcane catalyst or a magical infusion is later applied” would fulfill the design goal without downsides. I’m sure there are many other approaches. 

In many, many hours of enjoyment, this has been the *only* significant frustration for me. I imagine you have much better developed muscle memory for the gameplay, so I thought I would pass this on (before I became too adept to remember what frustrated me as a new-ish player😅).
