### ISSUE TITLE
Invalid controller axis mappings

### ISSUE THREAD

**Issue by parport0** [00-Evan/shattered-pixel-dungeon#1034]
I am experiencing issues with using gaming controllers on my Samsung Note 10 running Android 12.

In particular, for menu navigation:
when using an Xbox Series X/S controller:
- moving left stick up/down works for up/down
- moving right stick left/right works for left/right

when using Dualshock 4 & Dualsense controllers:
- right stick works as:
  - up -> left
  - left -> up
  - right -> down
  - down -> right

I could fix this issue and submit a pull request. To me, it looks like the ControllerHandler class needs some attention. I have a Nintendo Switch controller and an iOS device that i can whip out to test all possible configurations.

**Comment by 00-Evan** [comment]
I've identified a bunch of issues with gdx-controllers on Android, which is the likely source of this. I've submitted a PR for that here: https://github.com/libgdx/gdx-controllers/pull/23

I unfortunately don't have an Android 12 device currently, or a series X/S controller, but this did fix issues I encountered on several test controllers under Android 11.

**Comment by 00-Evan** [comment]
@parport0 would you be interested in testing a build of Shattered with an attempted fix for these controller issues? Let me know if you play the Google Play or the plain Android version of the game.

**Comment by parport0** [comment]
@00-Evan Sure. I play the Google Play version.

**Comment by 00-Evan** [comment]
Okay, here is a zipped APK that is identical to the current 1.3.2 version on Google Play, but which contains an update to gdx-controllers. Let me know if this helps out any of the issues you're encountering.

[ShatteredPD-v1.3.2-GPlay-CONTROLLERFIX.zip](https://github.com/00-Evan/shattered-pixel-dungeon/files/9263245/ShatteredPD-v1.3.2-GPlay-CONTROLLERFIX.zip)

You should be able to freely switch between this version and the latest Google Play apk on Github, the game will also still be able to update through Google Play when the next update releases.

**Comment by 00-Evan** [comment]
@parport0 sorry to be pushy on this, but it would be really helpful if you tried out the fix I linked above.

**Comment by dseight** [comment]
@parport0 left the country and left all of the controllers for me :) So, I'll answer instead.

I have tested the version with a fix on Pixel 5 with Android 12 and axis behavior seems to be fixed now. Thanks!

There are some other controller-related issues, though. 

- On the Nintendo Pro Controller everything works nice, including the D-pad
- On the Xbox Series X/S controller everything seems to be fine now, except the D-pad:
  - LT opens a menu, RT moves the character
  - The left stick moves the character
  - The right stick moves the cursor
  - X opens quickslot selection
- Dualshock/dualsense controllers have the following behavior:
  - R2 doesn’t move the character, instead, it opens a menu
  - Pressing R2 doesn’t always trigger a menu, it feels like pressed twice: once on half of a trigger (or a little bit further) and the second time on a full trigger
  - Simultaneous pressing R2 and moving the right stick leads to a black screen (infinite zoom out or panning?)
  - D-pad doesn’t work

**Comment by 00-Evan** [comment]
@dseight glad to hear that the functionality is improved for axis input, as that was the major target of the changes. In Shattered buttons can be remapped but the axis are hard-coded.

A few followup questions:
- How exactly does the dpad not work on a Series X/S controller?
- For the dualshock/dualsense controllers, were you only testing with dualsense, or did you also test with an older dualshock (Ps4 controller)? I did note issues on PS5 controllers in my testing similar to what you're getting, but PS4 worked perfectly.

**Comment by dseight** [comment]
> How exactly does the dpad not work on a Series X/S controller?

Oh, sorry, it's my bad. It seems that I was wrong: d-pad works exactly as should (switch enemy, pick an object, and stuff like that). My first thought was that it should move the character — and this is what it does on the Nintendo Pro Controller.

> For the dualshock/dualsense controllers, were you only testing with dualsense, or did you also test with an older dualshock (Ps4 controller)? I did note issues on PS5 controllers in my testing similar to what you're getting, but PS4 worked perfectly.

I've tested both of them (ps4 and ps5 controllers), and both of them behave exactly the same.

**Comment by 00-Evan** [comment]
Glad to hear that everything seems to work correctly on xbox controllers at least. The button mapping errors are unfortunately though, especially given that Android 12 was supposedly fixing the dualshock issues. Interestingly, my PS4 controller works correctly on my phone (Android 11) but does not work for you.

Last question, were you using these controllers via wire or bluetooth?

**Comment by 00-Evan** [comment]
Hmm, will look into this in more detail and see if there is any way for the game to detect this and adjust, though my ability to test is sadly limited to my Android 11 device (android emulators do not work with controller input).

At the very least the axis mappings seem to be fixed, which was the original report in this issue.

**Comment by 00-Evan** [comment]
Fixed in commit 998fb3c67013d88b8a2e3a10e9fadb43e54fd122

also see [this pull request](https://github.com/libgdx/gdx-controllers/pull/23) for the relevant code changes in gdx-controllers
