### ISSUE TITLE
Woolly Bomb Bugs

### ISSUE THREAD

**Issue by gigalh128** [00-Evan/shattered-pixel-dungeon#1035]
If you switch floors (or exit and re-enter) after using the woolly bomb, the sheep will not disappear upon tapping them (so you will have to wait the full 200 turns). This can make for a pretty awkward scenario if you use it by the stairs, since you will be stuck behind the sheep for a long time. I'd recommend making it so that the stone of flock/woolly bomb/flock trap cannot spawn sheep on the stairs. Seed is TYG-YJQ-NQT if you are interested.

Switching floors
https://user-images.githubusercontent.com/90579944/179640346-9e29528b-9e77-4184-9a09-a9f9bf5b3cf0.mp4

Exiting and re-entering
https://user-images.githubusercontent.com/90579944/179641564-7937a486-194e-44df-8bca-06f3258cf04f.mov

**Comment by gigalh128** [comment]
Also somewhat related: you lose your stone of flock even if it spawns 0 sheep. I am guessing that this is a bug considering one of the bug fixes for 1.3 was preventing stones of blink from disappearing if they fail to teleport.

**Comment by 00-Evan** [comment]
I think it makes more sense to evaluate the specific cases where items are preserved. I believe teleportation items are generally preserved when the fail as the player might not intuitively know they won't work. Generally I don't want to preserve items when they're used in ways that fail to have an effect.

**Comment by 00-Evan** [comment]
fixed in commit 571acc76ffad83d852836b6ce4893bdabeac0a40
