### ISSUE TITLE
using chalice doesn't build rage

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1038]
Berserker builds rage from physical damage.  Pricking finger on chalice does not build rage.  Do you consider damage from chalice to be purely magical?

**Comment by protective1** [comment]
Related to this, chalice damage is reduced by armor, but my understanding is that armor doesn't block magical damage.  That seems to imply that chalice damage is physical, not magical.

**Comment by Block-Vader** [comment]
It's a bit wonky. Chalice prick is considered physical damage, but not an attack. Armor does apply, other on hit effects (like rage buildup or glyphs) do not, since these effects require you to be attacked by something.

**Comment by 00-Evan** [comment]
This is correct, using the chalice does not count as being attacked. Unlike most other sources of neutral damage, armor does apply though.

**Comment by 00-Evan** [comment]
The chalice is not physical damage, it is a special type of magic damage that has different effects apply than normal.
