### ISSUE TITLE
Potions of str/might and upgrade/infusion scrolls carried by bandits can still be destroyed by frost and fire respectively

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#104]
Potions of str/might and upgrade/infusion scrolls carried by bandits can still be destroyed by frost and fire while the bandit is carrying them.

I'm pretty sure at least this method of permanently losing upgrade scrolls isn't intended.

**Comment by 00-Evan** [comment]
This is actually already fixed in the 0.4.1 beta

**Comment by tiw-gpidev** [comment]
Ah, okay. I should look at the latest public push then. Thanks!

**Comment by 00-Evan** [comment]
afraid the source for betas aren't public, although that same source is part of the public release shortly after.

I'll mark this as fixed once that fix commit goes public, probably in a couple of days as the beta is almost over.

**Comment by 00-Evan** [comment]
fixed in commit 43f3582e1e03897772122fb8ee101077f5dd09ee
