### ISSUE TITLE
Gladiator combo count issue

### ISSUE THREAD

**Issue by tvcat** [00-Evan/shattered-pixel-dungeon#1040]
Version: 1.3.1

As shown in the screenshot below, the "2 hit combo" counted twice. Is this normal?

![Clipboard01_](https://user-images.githubusercontent.com/119237/180120937-3855e7bc-0f00-4a83-90b6-502031787499.jpg)

**Comment by 00-Evan** [comment]
Are you sure you didn't build up to 2 combo on two separate occasions? The text for getting two combo, then losing it, then building up to 4 combo would look exactly like what you see here.

**Comment by tvcat** [comment]
@00-Evan That must be the case, thanks. I keep thinking it start with 1 hit combo lol.
