### ISSUE TITLE
after win on daily, regular rankings are displayed

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1041]
After winning the daily, the regular rankings pop up.  I would have expected the daily rankings to be open instead.  I know I can open the daily rankings manually, but this was unexpected and made it look like I had just been slain by a mimic, which was actually a few games ago and not the most recent game.

![Screenshot_20220721-151319](https://user-images.githubusercontent.com/8593007/180297466-425dc7da-3212-46d8-9be2-74d09fc7b008.png)
![Screenshot_20220721-151333](https://user-images.githubusercontent.com/8593007/180297458-13aae072-ce90-447d-9782-bcb78c227962.png)

**Comment by 00-Evan** [comment]
I agree that this should be adjusted, in future please don't present design suggestions as bug reports though.

**Comment by 00-Evan** [comment]
added in commit 987350c11e2769f38de45587618ab8f99a347a9a
