### ISSUE TITLE
[Bug] Gateway trap allows interaction from a distance

### ISSUE THREAD

**Issue by przemyslaw-zan** [00-Evan/shattered-pixel-dungeon#1042]
There were hero's remain on the ground. I tried to walk over them. There was hidden gateway under the remains. The trap teleported me away. Button to interact with the remains was still present despite being in a different location. I clicked the button and successfully interacted with the remains.

Seems like gateway trap does not update / check whether it is still possible to interact with an item on the ground.

**Comment by 00-Evan** [comment]
gateway traps also teleport items, so the remains were next to you after teleporting, if they were before the teleport. They probably shouldn't though, as its inconsistent with regular teleportation traps, but that's a separate issue.
