### ISSUE TITLE
Winning screen  cut off

### ISSUE THREAD

**Issue by tvcat** [00-Evan/shattered-pixel-dungeon#1044]
Version: 1.3.1 Windows
Windows display scale: 125%
Screen resolution: 1920x1080
Game fullscreen: No
Game interface scale: 6x

It will show correctly if I change the Windows display scale to 100% (default). So far only the winning screen having this issue.

![Clipboard01__](https://user-images.githubusercontent.com/119237/180383137-b6241fe0-c8c9-4dee-bb4b-7d80d2545088.jpg)

**Comment by 00-Evan** [comment]
I'd suggest using the desktop UI, which will resolve this for now. I'm going to be adjusting the width of this desktop for mobile and desktop landscape users in 1.3.2, which will fix this.

**Comment by 00-Evan** [comment]
fixed in commit 7beeec84f5b3a696fb89285123834443575af0b7
