### ISSUE TITLE
rooted doesn't end while sleeping

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1045]
I used unstable spellbook to cast lullaby.  I ate mystery meat before falling asleep.  Mystery meat caused me to be rooted for five turns.  When I woke up I was still fully rooted.  I expected to be out of root due to the passage of time during lullaby.  Is this behavior expected or a bug?

**Comment by 00-Evan** [comment]
Were you already at full health? Magical sleep ends pretty much instantly if you don't have any HP to recover.

**Comment by protective1** [comment]
No I was not at full health.  I was missing quite a bit, but was also starving, hence the need to eat the food once I realized the spell was lullaby.  I was actually quite shocked that no monsters interrupted the sleep because I was missing so much health.

**Comment by 00-Evan** [comment]
I think I see what's going on here. Rooted from mystery meat actually lasts 10 turns. Your were asleep for 5 turns, which reduced the duration to 5. Because of the way buff fading works, it only starts fading at a pre-set value, which is 5 for rooted.

**Comment by protective1** [comment]
Thanks for figuring it out and explaining.
