### ISSUE TITLE
Tome of Dungeon Mastery readable without picking it up

### ISSUE THREAD

**Issue by verdulo** [00-Evan/shattered-pixel-dungeon#1046]
Minor cosmetic bug: player can read the Tome of Dungeon Mastery and gets notification "The guidebook has advice for you!" even if he hasn't picked it up.

**Comment by 00-Evan** [comment]
I'm fine with this inconsistency. For new players it's better than denying them tutorial tips because they didn't realize they could tap on the book to collect it.
