### ISSUE TITLE
Unsolvable puzzle room

### ISSUE THREAD

**Issue by BradfordC** [00-Evan/shattered-pixel-dungeon#1049]
Reporting the bug in this reddit post:
https://www.reddit.com/r/PixelDungeon/comments/w9fmqy/shattered_lets_play_a_game/

Seed is FHQ-QSZ-FBY

Problem:

On Floor 3, there's three special rooms:

* Locked crystal chest room
* Locked alchemy room with levitation potion
* Levitation puzzle room w/ key reward

There are no levitation potions on the floor, other than the one in the alchemy room. (This has been confirmed by several players.) So, if you unlock the crystal chest room first, there's no way to open/solve the other rooms (without backtracking from later floors). The alchemy room needs the key from the puzzle room, but the puzzle room needs the potion from the alchemy room.

**Comment by 00-Evan** [comment]
This isn't a bug, levelgen can very rarely create these sorts of scenarios and I'm fine with that. It adds just a tiny bit of uncertainty to solution items otherwise always being guaranteed.
