### ISSUE TITLE
Teleported DM-300 with fadeleaf

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1050]
Someone on discord said this is a bug and I should report it. I dunno if that's true or not but here I am. He just sat there spitting exhaust until I managed to do enough damage that he phased up and broke himself a path out. Super annoying as warrior; might have been an easy kill as rogue or huntress though.

![2022-07-27_1920x1080](https://user-images.githubusercontent.com/1139517/181590710-64070319-204e-4bbe-b4a0-eca2ef436502.jpg)

**Comment by 00-Evan** [comment]
That's amusing. It's not an invalid location for DM-300 to be, so I'm fine with it.

**Comment by LeahLuong** [comment]
![Screenshot_20221101-135734](https://user-images.githubusercontent.com/91638992/199346350-e58e1369-9c50-4312-b6dc-7a7d156fbe75.png)

This recently happened to me & it is super annoying. I used phase shift to push him away while supercharged & he ended up in another pylon room; didn't break out before I knocked down the other pylon. Weren't giant succubi fixed so they can't teleport themselves into places they can't normally fit?? Isn't it the same for giant necromancers summoning giant skeletons in hallways?? Seems inconsistent DM-300 can teleport into places too small for him to fit.

**Comment by 00-Evan** [comment]
> ![Screenshot_20221101-135734](https://user-images.githubusercontent.com/91638992/199346350-e58e1369-9c50-4312-b6dc-7a7d156fbe75.png)
> 
> This recently happened to me & it is super annoying. I used phase shift to push him away while supercharged & he ended up in another pylon room; didn't break out before I knocked down the other pylon. Weren't giant succubi fixed so they can't teleport themselves into places they can't normally fit?? Isn't it the same for giant necromancers summoning giant skeletons in hallways?? Seems inconsistent DM-300 can teleport into places too small for him to fit.

You're mixing up 'in a hallway' with 'in a room that can only be accessed via hallways'. That is not an invalid position for a large enemy to be in.

**Comment by LeahLuong** [comment]
The pylon isn't walkable space before its destruction. I don't believe I was confused in saying the space is too small; the pylon rooms are effectively donuts which don't block vision before the pylon is destroyed which, if I'm not mistaken, otherwise count as hallways.

**Comment by 00-Evan** [comment]
> The pylon isn't walkable space before its destruction. I don't believe I was confused in saying the space is too small; the pylon rooms are effectively donuts which don't block vision before the pylon is destroyed which, if I'm not mistaken, otherwise count as hallways.

Pylons are enemies, not terrain. Only terrain is considered when determining what space is valid for large enemies.
