### ISSUE TITLE
More ranking pages

### ISSUE THREAD

**Issue by Zhizhou7** [00-Evan/shattered-pixel-dungeon#1053]
The current ranking page only has space for about 11 played games, meaning most games you complete won't be recorded after you've played a cerntain amount. I wish to have more than one ranking page for games I won. It'd be very nice if I could have the records of games won with a irregular technique but not necessarily with a high score. The ability to delete some records would also be an alternative for me.
Thanks ahead of time for taking this into consideration.

**Comment by 00-Evan** [comment]
I'm afraid I don't have any plans to make the rankings page infinitely long, but if you have purchased the game (or made a supporter purchase on Android) then you would have access to the the hall of heroes, which effectively gives 4 extra rankings pages that you do have some control over.
