### ISSUE TITLE
Cross-platform saves/profiles

### ISSUE THREAD

**Issue by vPubneutral** [00-Evan/shattered-pixel-dungeon#1055]
Was wondering if you were planning on implementation some sort of cross-progression between platforms (ex: syncing badges/rankings from Google Play to Steam.) I'm not sure how difficult this would be, but I think it'd be neat.

Also, and this isn't nearly as important, but maybe there could be a way to detect if someone were a Shattered Supporter on Google Play, and enable those cosmetics on Steam?

**Comment by 00-Evan** [comment]
Unfortunately I don't have any plans to do this.

For pretty obvious reasons, the different platform holders do not have any way to sync progress or share payment status between them, which means I have to implement something like this manually. That leaves two options:
- Implement an account and sync system entirely on my own, which would be an enourmous amount of work and requires expertese that I don't have.
- Allow users to export and import their data via files. This would be very clunky for legitimate users and would make it extremely easy to cheat.
