### ISSUE TITLE
Challenges are not unlocked after winning a game.

### ISSUE THREAD

**Issue by nvlie** [00-Evan/shattered-pixel-dungeon#1056]
I can't unlock the challenges seeded run and daily run after winning a game on steam, and many players I knew are also facing this problem.

**Comment by 00-Evan** [comment]
This is a known bug that will be fixed next update. Unfortunately the victory badge isn't being properly saved in some cases.

To prevent this from happening, either select the 'wait' option when you get the amulet initially (you can immediately re-use it to the end the game), start a new run before closing the game, or view the badges screen before closing the game.

**Comment by 00-Evan** [comment]
Fixed in commit 1df169f533c8affe110f29e40a1cfbcb2f041cff
