### ISSUE TITLE
More audio events

### ISSUE THREAD

**Issue by bhilmers** [00-Evan/shattered-pixel-dungeon#1057]
Enhancement: I would really like to hear a audio events for "demon ripper prepares to leap" and "you sense a deadly presence." These could probably be the same audio cue, perhaps a growl or snarl or other generic monster sound. It would be nice to have one for Yog too, on the turn before firing when the red squares mark the laser path.

**Comment by 00-Evan** [comment]
More audio queues would be nice, but currently there are none planned. I'm not really able to produce sfx to add to the game myself either, I work with someone to add more sfx, and they have been busy with other work lately.
