### ISSUE TITLE
Can we have cheats?

### ISSUE THREAD

**Issue by jistjak** [00-Evan/shattered-pixel-dungeon#1058]
Can you add cheats to the game? Asking for a friend... lol jk. I like cheats. I'm a responsible cheater. I dont use them unless everyone in the same game agrees to let me. Since this is a single player game as far as i know, and i dont know much, I'll be okay with me cheating. I had just unlocked the rest of the cast and havent even switched from default warrior yet. He's at lvl 10 rn i dont wanna start over im in too deep. Literally and figuratively. I found a wand that does random spell effects i wanna keep it. Says it's cursed but i think it's blessed.

Some people just suck at games, not me tho no cap 420 no-scope 360 blaze it mountain duu-ritos cool ranch bruh fo-shizzle ya digg? Nah, i dont suck, but i'm no Baby Ruth at baseball either... I dont follow sports. im not super good at games like i wont win tournaments is all. But im also not bad either, i can probably beat the game without cheats.. eventually. Blah, FOCUS!: ≥-> sorry. Anyway, some are bad at games and would like to casually explore.

sorry for rambling so much, you wont know how much i had to delete cuz i just say the most random things that somehow connect to previous statements.

here's a bulleted list for some reasons:

- bad at games.
- beat the game already and want to mess around.
- want to mess around anyway without beating it already.
- challenge mode cheats make it harder (for maso's... masokists... masochist... idk. People that like pain)
- fun for the creator of cheats (i'll explain this at the bottom*)
- love cheats/ just love the idea of cheating. (it's just fun.. this probably should go in 'people like to mess around' category)
- There's probably more reasons that dont fall into any of these categories. Maybe other people might add reason they can think of.

Here's some cheat ideas
- inf HP
- inf magic
- indestructible items
- inf item/ no item depletion (ie: use a scroll multiple times)
- get any item from list of all items
- modify / customize glyphs and upgrades
- unpermanent death, respawn at top dungeon or something idk.
- big head mode lol

*fun for the creator of cheats. You can let your imagination run wild. Anything goes, no holds barred. Play the game completely upside down? You got it. What happens when an lowly common enemy takes up the entire screen? Only one way to find out. Wanna see how crazy it looks in first person? Super difficult to implement, but sure. Can the hero be a pineapple? Obviously, yeah. Point is, cheats dont all have to be : press B to win/ inf hp/ blah whatever. you can have any wacky idea be part of your game. Like if you got a really good dream and want to implement something from your dream but afraid it wont mesh well cuz it's not "canon" to the gameplay. You can do a [insert dream idea]-MODE cheat and make it happen. Feel free to use any ideas in this post if you want to (no credit needed).

**Comment by 00-Evan** [comment]
Sorry but I have no intention of adding cheats to the game. I closed another request recently asking for game modifiers to reduce difficulty (which is very similar), you can read over my reply to that for my reasoning: https://github.com/00-Evan/shattered-pixel-dungeon/issues/1033#issuecomment-1188213198

**Comment by luffah** [comment]
> Can you add cheats to the game? Asking for a friend...

… a great opportunity to discover java code together … :)
