### ISSUE TITLE
quickslot magical holster strength requirement and quantity text obscures visual item information

### ISSUE THREAD

**Issue by mrsocksman** [00-Evan/shattered-pixel-dungeon#1059]
Visual information such as dart tip colour, differentiating different spear-like objects,  etc

![Screenshot_20220806-213024_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/74167120/183271306-3c747e79-df09-4cbc-be8b-bdc74d09e0e7.png)

**Comment by 00-Evan** [comment]
Thi is only really a problem for tipped darts, as they are virtually identical with the tip cut off. I will likely adjust their sprites a bit in the next update so the tip color reaches a little further down.

**Comment by 00-Evan** [comment]
Fixed in commit 06daf06e8d3f5d7a77f63b879e3cff311d7f135b
