### ISSUE TITLE
Scroll of Terror scares away merchants!

### ISSUE THREAD

**Issue by muleyryan** [00-Evan/shattered-pixel-dungeon#106]
I accidentally opened a scroll of terror on level 11 at Pixel-Mart and the merchant and items vanished. 

Ruined an awesome seed. Bug?

**Comment by 00-Evan** [comment]
This is intended, the shopkeeper is a pacifist by nature and will flee at the first sign of trouble, like a careless adventurer reading dangerous scrolls in their shop =P.
