### ISSUE TITLE
Blooming enchantment adds vegetation on top of demon spawner

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1060]
Let's see if I can figure out how to add screenshots on mobile...

**Comment by rpdelaney** [comment]
![Screenshot_20220806-221657](https://user-images.githubusercontent.com/1139517/183272277-547f0ee8-c4a0-49c3-94fb-6fe92556a893.png)
![Screenshot_20220806-221704](https://user-images.githubusercontent.com/1139517/183272278-b4af0aab-72d2-49c1-b5a1-96f3d2dc226b.png)

**Comment by 00-Evan** [comment]
This does look odd but is correct. vegitation (grass, plants, etc) can appear on top of characters, it just doesn't usually happen for immobile enemies.
