### ISSUE TITLE
Visual: Goo pump animation stays when using Stone of Fear

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1065]
Minor visual glitch: When you use Stone of Fear while Goo is pumping up,  the visual effect is not despawned. 
![Screenshot_2022-08-22-21-46-11-971_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/186006519-252d789d-782a-4151-918a-016c004317e8.jpg)

**Comment by 00-Evan** [comment]
I'm aware of this one and actually already have it fixed in development =)
