### ISSUE TITLE
Balance change: Arcane Resin should be stored in the Wand Holster

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1066]
It's really weird that Arcane ~Catalyst~ Resin goes in the main stash when I have a wand holster. This means I have to do a bit of arithmetic to figure out if I can make enough to upgrade my wand again before converting other wands to ~Catalyst~ Resin, or else I wind up wasting a precious inventory slot that I bought the Holster to save me.

**Comment by 00-Evan** [comment]
Do you mean arcane resin?

**Comment by rpdelaney** [comment]
Yes! Thanks for the correction. The purple thing that I can use to cannibalize wands into upgrades for other wands! Xd

**Comment by 00-Evan** [comment]
Okay that makes more sense.

I understand why this would be a QoL adjustment, but I'd rather not expand containers to include items outside of their intended item groups. Arcane resin isn't a throwing weapon or a wand in any sense. It already feels like a bit of a stretch that catalysts can be stored in containers for potions/scrolls, but they can at least be activated for a potion/scroll effect.

However, liquid metal is already considered a potion for the purposes of fitting in the potion bandolier, so reasonably arcane resin could be considered a spell and be allowed to fit in the scroll holder.

**Comment by 00-Evan** [comment]
Added in commit 749c3a84f9dbebed38b06cde8958409ddbdbdf89
