### ISSUE TITLE
Stuttering/inconsistent frame rate

### ISSUE THREAD

**Issue by cryocore05** [00-Evan/shattered-pixel-dungeon#1067]
gameplay isn't smooth at all!
using 1.3.2 on Xiaomi Redmi note 8 pro.
I tried common solutions like disabling battery saver, closing apps, reinstalling app, etc... none helped.
Frame rate isn't low, animations and Ui are smooth but once I move frame rate becomes very inconsistent & it feels so stuttery

**Comment by 00-Evan** [comment]
It might be easier to diagnose this with a screen recording. When the hero starts moving, game logic is performed (pathfinding, vision calculation, etc.) but that should not be interrupting the game's graphics operations. There is also a 'power saver' setting in the game's menu, which may help.

**Comment by cryocore05** [comment]
I tried using power saver, it still happens, I paid closer attention and understood it most likely occurs when I step in bushes and get vision of dark spots or when I click to pass through doors.
or when I make a turn that expands my vision all of it causes the smoothness to go away

**Comment by 00-Evan** [comment]
Hmm, the game does perform lots of calculations when the fog of war (that's the darkening effect) gets updated, but it shouldn't be significant enough to cause major slowdown or stuttering.

I suspect something in your device's power management may be causing it to not respond properly to these little spikes in processor demand. For instance, your device has 6 efficiency processor cores and 2 performance cores, it may be swapping which processor cores it uses for the game on the fly, which would definitely result in some hitching.

I do hope to improve the fog of war game logic at some point in the future (it's more complex than it needs to be at the moment), but there's nothing I can really do to fix your issue in particular, sorry. It is possible that there is a setting in your device you may be able to change to improve this though, such as a 'game mode' or per-app battery optimization settings.
