### ISSUE TITLE
[Feature request] Seed accessibility 

### ISSUE THREAD

**Issue by 0Karakurt0** [00-Evan/shattered-pixel-dungeon#1068]
As of right now there is no way to copy the seed of the dungeon, other than to retype it yourself.
Therefore I'm asking so that long-press on seed would copy it to the clipboard

**Comment by 00-Evan** [comment]
There is a copy seed button in the the rankings screen. I am planning to make this a bit smoother in the next update, but don't plan to put a copy button in game as you can't start a custom run with the same seed as a run in progress anyway.

**Comment by 0Karakurt0** [comment]
you can't start it, yes, but that doesn't mean that you don't want to share an interesting seed without dying or completing the game
