### ISSUE TITLE
Wrong text on a trap

### ISSUE THREAD

**Issue by Flindgh** [00-Evan/shattered-pixel-dungeon#1069]
See the attached screenshot: the trap description is erroneous.
Game version 1.3.2, on Android.
![Screenshot_20220831-120742](https://user-images.githubusercontent.com/105607585/187782887-00d53f1c-8cf2-4162-a095-83cff47d78d2.jpg)

**Comment by 00-Evan** [comment]
I don't see anything wrong with that description at a glance, what specifically is incorrect about it?

**Comment by Flindgh** [comment]
Oh OK... I thought it was a harmful trap (because red), not a displacing one (usually blue). Sorry for the inconvenience.
And thanks for the game!

**Comment by 00-Evan** [comment]
That is the correct visual for disarming traps. They're sort of a weird mix of a weapon-affecting trap and a teleportation trap, so they get a red color.
