### ISSUE TITLE
Feature Request: Draggable quickbar on touch

### ISSUE THREAD

**Issue by replete** [00-Evan/shattered-pixel-dungeon#1071]
For the thumb tappers, having a right/left aligned quickbar OR (preferably) a draggable vertical quick bar would really improve the gameplay experience, especially for Huntress. Quick bar isn't so quick when its nowhere near your thumb - it's especially RSI-prone on those long screens.

As an aside, this game is really excellent! I was fed up after a few attempts, but the learning curve is really nicely balanced and it became a bit addictive... amazing work!

**Comment by 00-Evan** [comment]
Glad to hear that you're enjoying the game! Sorry, but I don't plan to add a customizable UI to the game, or a setting for quickslots to go on the left or right, as action indicators already go there. There are settings for toolbar layout in the settings menu, but none of them move it away from the bottom of the screen.
