### ISSUE TITLE
stone of intuition ends invisibility

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1072]
I drank unknown invisibility potion.  I used stone of intuition and currently guessed paralysis potion.  For dinner reason, I am now visible.  It seems like this shouldn't end invisibility.  I did not attack, and there are no enemies present which can see me use a wand or scroll (not did I use them).
![Screenshot_20220902-004640](https://user-images.githubusercontent.com/8593007/188064067-a17ae931-bf99-4df2-a4ad-53911b10eaf8.png)
![Screenshot_20220902-011751](https://user-images.githubusercontent.com/8593007/188064147-c3fe932f-9a4e-4ede-8f40-d3fc0f6a280e.png)

**Comment by 00-Evan** [comment]
From Invisibility's description: "Physical attacks and magical effects (such as scrolls and wands) will immediately cancel invisibility." Runestones effects are magical.
