### ISSUE TITLE
Keyboard doesn't work on macOS

### ISSUE THREAD

**Issue by mhmdanas** [00-Evan/shattered-pixel-dungeon#1074]
I compiled the game (version 1.3.2) locally and the produced JAR works just fine, except for the fact that the game doesn't register any keypresses from my keyboard whatsoever. This has nothing to do with the keyboard layout, as the issue also happens with a QWERTY layout.  I also tested with both the laptop keyboard and an external keyboard, and both exhibit the issue. I'm using macOS 12.5.1 on a 2017 MacBook Pro.

Any ideas what the cause is and how to fix this?

**Comment by 00-Evan** [comment]
That is quite odd. I'm using an M1 macbook air, also on 12.5.1, and keyboard input works just fine. Does this also occur using the official release JAR?

**Comment by mhmdanas** [comment]
> That is quite odd. I'm using an M1 macbook air, also on 12.5.1, and keyboard input works just fine.

Might be worth noting that my MacBook is Intel.

>  Does this also occur using the official release JAR?

Yes.

**Comment by 00-Evan** [comment]
Updated my macbook (was on 12.5.0 before) and ran a few more tests but still can't reproduce this. I'm assuming keyboard input just flatly doesn't work, including text input and game key bindings? Can you do anything in the key bindings window?

It sounds like it may be a device specific error.

**Comment by mhmdanas** [comment]
Well, lo and behold, it works now, maybe restarting the machine fixed the issue. Gotta love this kind of issues. Sorry for the bother, and thank you for the help.

>  I'm assuming keyboard input just flatly doesn't work, including text input and game key bindings? Can you do anything in the key bindings window?

Back when it didn't work, yes, no keys on the keyboard did anything in the game, menu, and key bindings window.
