### ISSUE TITLE
Giant skeleton spawned in doorway?

### ISSUE THREAD

**Issue by andreasmjg** [00-Evan/shattered-pixel-dungeon#1076]
Giant hero monster's can't move through doorways. But a Necromancer still spawned a skeleton inside a doorway.

IMO, the Necromancer's spawn is also a giant (shines blue), and so should not fit inside the doorway, and so should not be able to be spawned there. 

![Screenshot_20220909-225251_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/34312687/189471395-efc2ec97-8af8-47cd-846c-4911003d3094.png)

**Comment by 00-Evan** [comment]
Fixed in commit efa0fc367866214d62b2808a261e147633cac97b
