### ISSUE TITLE
Runic Transference doesn't work properly

### ISSUE THREAD

**Issue by WX4300** [00-Evan/shattered-pixel-dungeon#1077]
1. I got the Leather Armor of Stone.
2. I upgraded the Cloth Armor to +1.
3. I upgraded Runic Transference to Lvl 2.
4. I detached the Broken Seal from the Cloth Armor.
5. I affixed it to the Leather Armor of Stone.
6. I detached it from the Leather Armor of Stone.
7. I affixed it to 2 different armors and the Glyph of Stone wasn't transferred.
8. I enchanted a clean armor and the Broken Seal transferred the new glyph (Repulsion) properly.

Runic Transference doesn't work for armors obtained before upgrading this skill to Lvl 2?

**Comment by 00-Evan** [comment]
This is working correctly. The warriors seal cannot be used to take upgrades or glyphs from other armors, it only transfers upgrades/glyphs that are applied to the armor when the seal is attached to it.
