### ISSUE TITLE
Stepping from plant to plant

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#108]
If you step off of an earthroot and onto another earthroot, the related buff (herbal armor) disappears.

**Comment by 00-Evan** [comment]
looks like the buff isn't updating the position that it expects you to be at.

Will fix, thanks

**Comment by 00-Evan** [comment]
fixed in commit 3c1e130b5920622bb4517b466fcd536568ed7ee4
