### ISSUE TITLE
Blast Wave knockback messes with fog of war

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1080]
When you are knocked back by a wand or blast wave (possibly geyser traps as well, but haven't check that out), the tiles at the edge of the old field of view stay lit up as if it is still in your field of view, and stay that way until that tile re-enters your vision, even if you walk away. Any mobs there will still be invisible, just as they normally are when outside the vision range.

![Screenshot_20220917-135533](https://user-images.githubusercontent.com/101913866/190873212-598487a5-e22d-4ffa-904d-3cc84c9dbbe0.jpg)

**Comment by bhilmers** [comment]
Can confirm the buggy redraw, video attached. Simply blasting an adjacent tile produces the effect.

Samsung Galaxy A12
Android 11
SPD v1.3.2 with default display settings


https://user-images.githubusercontent.com/77466683/190879945-679f60af-0067-45ae-82bd-ae0364a0939f.mp4

**Comment by 00-Evan** [comment]
Fixed in commit e288a2efa3a97781bb96b37cb62e962f2b470128
