### ISSUE TITLE
Spellbook Generates Scrolls of Lullaby

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1081]
The book will generate a scroll in the inventory whenever the player uses a Siren's Song from the Spellbook. This appears to be mentioned as fixed in the 1.2 changelog, but it is clearly not fixed.
https://user-images.githubusercontent.com/101913866/190925598-53e2a384-8eef-4307-86e7-cf6703611e09.mp4

**Comment by 00-Evan** [comment]
This is actually already fixed indev based on another report

**Comment by 00-Evan** [comment]
Fixed in commit 94e7ea056148c1c32f07866d0b4683c73895885b
