### ISSUE TITLE
Cancelled uses of Identify and Remove Curse from the Spellbook don't take up any turns

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1082]
When the Spellbook is used, you are forced to use one of the two scrolls that show up, and each time it takes a turn to use. The one exception to this is if you roll Identify or Remove Curse and don't use them, (backing out of the inventory), then it doesn't take up your turn. Because of this, these two are some of the more desirable scrolls to receive, not because their effects are useful, but because you immediately take another turn and enemies don't get to react. Is this intended? It seems like all uses of the spellbook ought to take time, even if the scroll is unused.

**Comment by 00-Evan** [comment]
Fixed in commit 9415a00930aef7d09a2386835bc37dda98aec0bb
