### ISSUE TITLE
Softlock after update to 1.40-beta-1

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1084]
I updated to 1.40-beta-1 and am now softlocked in a Spinner web. The wait button, quick bar and HP bar are not loaded properly. It is not even possible to quit the app anymore.

**Comment by spixi** [comment]
![Screenshot_2022-09-24-09-05-38-475_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/192085191-383788b2-d628-4e48-bd0f-16ee2d47ae1c.jpg)

**Comment by 00-Evan** [comment]
A few things I'd like to know:
- do you currently have four runs in progress?
- If not, how were you able to play a regular run instead of being forced to create a new one?

This is the game's tutorial functionality, but it shouldn't trigger on an existing run.

**Comment by spixi** [comment]
I had only one run in progress. I updated via menu and then continued the run. However I found a workaround. You can start another run and pick up the book. This will enable the UI for all runs again.

**Comment by 00-Evan** [comment]
Yes that's the intended way to complete the tutorial, but you should be forced to start a new run and shouldn't be able to access the runs in progress menu at all. That's what I asked specifically how you were able to do that.

**Comment by spixi** [comment]
@00-Evan I already had a saved run. Then I started the game, updated it via the menu and then continued my run. I was not forced to start a new one.

**Comment by 00-Evan** [comment]
So after updating the game should show you the update message screen, which then forces you to create a new run. Continuing your run wouldn't be possible as you shouldn't be able to access that interface.

If you weren't shown the update message screen then the tutorial wouldn't trigger anyway, as the tutorial being enabled is tied to being shown that screen.

**Comment by spixi** [comment]
The update message screen did not appear after updating the game.

**Comment by spixi** [comment]
Oh, wait, I guess, that I know what happened. The screen indeed appeared and I also looked at the changes, but then quit the app. At the next start the screen did not appear again. I was able to start a regular run, but somehow a tutorial mode flag must have been activated.

**Comment by 00-Evan** [comment]
This has been fixed in BETA-2
