### ISSUE TITLE
UI broken in 1.4 beta

### ISSUE THREAD

**Issue by Nyx019** [00-Evan/shattered-pixel-dungeon#1086]
![Screenshot_20220925-211230](https://user-images.githubusercontent.com/73610161/192162069-a8e61afe-2ef1-4bba-ba21-a66a6062295b.jpg)

Both the toolbar and the menu button don't show up. Character Info and so on are also broken.

**Comment by 00-Evan** [comment]
This is the new guided tutorial, please read the text in the game log and follow the isntructions.

**Comment by Nyx019** [comment]
That's on me of course for not noticing, but I found it frustrating to not be able to go to the menu without entirely closing the game. I think the menu button is as vital as the settings button.
