### ISSUE TITLE
Showcase seeds.

### ISSUE THREAD

**Issue by haltalt** [00-Evan/shattered-pixel-dungeon#1088]
Shattered updates bring in quite a lot of new features. I believe some people who like to keep up with the development of the game and beta testers would like to have an option to specifically come in contact with new changes. The feature I'd like to suggest is **making a couple daily seeds showcase new elements/changes of the game after bigger updates**. It doesn't make the UI more convoluted, and is an elegant solution to the issue I described. However, I understand that a function like this could be regarded low-priority and not being worth the time to implement, or just unnecessary - this was more of a neat idea I had that I think could improve the game.

**Comment by 00-Evan** [comment]
Daily seeds are not hardcoded currently, they are based on the date. Adding in hardcoded seeds would not only be tricky to organize, it would only be able to work on a per-update basis and would require manually sifting through seeds to find runs which feature the item.
