### ISSUE TITLE
Minor graphical glitch with DM-300 and prismatic image

### ISSUE THREAD

**Issue by aaubry** [00-Evan/shattered-pixel-dungeon#1089]
This happened on 1.4 beta. As you can see the prismatic image is rendered on front of DM-300 when it should be behind.

![Screenshot_2022-09-25-20-50-35-24_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/630495/192393782-1d027ec1-42b3-43c1-86cf-e0bdad4bae98.jpg)

**Comment by 00-Evan** [comment]
This is an unfortunate quirk of the way the game renders visuals. It doesn't render characters in any particular order, and while there is some logic to make DM-300 and pylons render later in the order, it isn't guaranteed.
