### ISSUE TITLE
Floors featuring locked doors without a key

### ISSUE THREAD

**Issue by muleyryan** [00-Evan/shattered-pixel-dungeon#109]
Since the update, several times have I encountered locked doors with no key on the floor. I confirmed this with a scroll of magic mapping once or twice.

**Comment by 00-Evan** [comment]
Do those locked rooms have an empty well in them? If so, perhaps you should look for a way to drop down from the floor above.

If that's not the case, please let me know.

**Comment by muleyryan** [comment]
😐
