### ISSUE TITLE
Graphical glitch with summoned scorpio

### ISSUE THREAD

**Issue by aaubry** [00-Evan/shattered-pixel-dungeon#1090]
This happened on 1.4 beta. The sprite of the scorpio was shifted. The amount of shift changed as I attacked it. All enemies were summoned by a trap.

![Screenshot_2022-09-26-19-02-04-57_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/630495/192394363-ec12d2ca-088b-4ef0-bdce-ba1febc33e7a.jpg)

**Comment by 00-Evan** [comment]
This has been fixed in BETA-2
