### ISSUE TITLE
Alchemy UI

### ISSUE THREAD

**Issue by witten** [00-Evan/shattered-pixel-dungeon#1091]
First off, thank you for the awesome game. I can only imagine how much work goes into it. I'm a long-time casual player, but just *today* I had some major revelations about the alchemy UI that I thought I'd share in case it helps inform the UI design. Specifically, when accessing the list of possible alchemical combinations within the alchemy UI:

 * **Energy number confusion:** I had no idea until today the small blue number on each "formula" was the energy cost. I thought it was the number of ingredients needed since it's so close to the ingredients. For instance, under Exotic Scrolls, I thought I needed *six* Scrolls of Upgrade to make one Scroll of Enchantment! In retrospect, I should've realized the blue was the same color as the big "Energy" count down below, but that didn't occur to me. A potential fix would be to move the little energy number to the middle or right of the arrow. Or even being explicit with a little energy icon and a number as one of the ingredients. More horizontal space might help too.
 * **"Grayed out" formulas**: I had no idea until today that the slightly darker formulas were ones I didn't have the components for, and the lighter formulas were the ones for which I did have the prerequisites. That would've been really useful to know! Maybe I just wasn't observant enough? Maybe he difference in darkness/lightness could be greater to make this really clear?
 * **Clicking on formulas**: I had no idea until today that *clicking on* a lit up formula would pre-populate the alchemy UI with those ingredients. That would've saved me a lot of time and clicking back and forth to check ingredients! Not sure how to make this more discoverable though.

In sum, these discoveries make the alchemy feature much easier to use and more _useful_ in the game. I just wish I'd known about them earlier!

Running: v1.3.2 on Android.

**Comment by 00-Evan** [comment]
Things like this are always tricky. I've tried to do things to make the design of that more intuitive but there's only so much to do short of just writing "X means Y" in text.

I can't really think of much else to do here short of having a written description. The blue text, greying out, and yellow highlighting are all there to try and make things more intuitive. Adding more to the blue text area isn't really possible as the UI is already very limited on space in lots of cases, and moving the text or adding the icon along with the text (I did try this at one point) obscures the arrow. The greying out of items is the same 30% opacity greying out that occurs in other situations where an item is absent or not selectable, such as when you've used up every item in a quickslot.

**Comment by witten** [comment]
Okay, totally understood. I just thought you might want to get a sense of things that users (or at least this one user) are getting hung up on, even if it's not actionable at this point. One thing I've seen some games/apps do is to have a mini wizard tutorial the first time you visit a new feature or page. E.g., open alchemy formulas for the first time and it shows you each item, maybe with an arrow or circle: "These are the ingredients for the formula [next ->]", then "This number is the energy cost [next ->]", then "This is the resulting item produced [next ->]", then "Grayed out formulas mean you're missing ingredients [next ->]", then "Click on a formula to populate your alchemy brew! [got it]".

I can see if that's not a road you want to go down, but this *is* one way to quickly convey complex UI from within the UI.

Thanks!

**Comment by 00-Evan** [comment]
The new guided tutorial for Shattered does do that a little, but it tries to mainly just explain the very initial basics of game interaction, encourage the player to read the game log and guidebook, and then stops. I hate it when games have a mini guided tutorial for every interface. I feel like they're sort of the developers saying "we acknowledge our UI isn't intuitive (or assume you're an idiot) and so we're going to waste 30 seconds of your time explaining it to you."

I am always happy to hear feedback though, even if I don't always do things directly based on it. In future you may want to send me an email for things like this instead of creating an issue report: Evan@ShatteredPixel.com
