### ISSUE TITLE
Suggestion: Post beta builds with the github release beta tag

### ISSUE THREAD

**Issue by theofficialgman** [00-Evan/shattered-pixel-dungeon#1092]
The current github BETA tag is marked as a release. github has separate markings for beta releases that should be used in this case.

Also, if you could, please keep the tag, filename, and name of the release with the same capitilization. It makes automation used at pi-apps for automatic update detection work. For example, the release tag is `v1.4.0-beta` but the name of the release is `v1.4.0-BETA` and the filename contains `v1.4.0-BETA`. this can't be checked automatically easily.

**Comment by 00-Evan** [comment]
Whoops, the lack of prerelease tag was actually an oversight on my part for this release. That should be fixed now.
