### ISSUE TITLE
Summoned Guardian counts as statue in Landmarks page

### ISSUE THREAD

**Issue by Dimedime-d** [00-Evan/shattered-pixel-dungeon#1096]
Played on today October 1st daily
<img width="180" alt="Screenshot_20221001-101602" src="https://user-images.githubusercontent.com/73413313/193414276-5deb1e20-ad5d-4f7f-9750-851a62daa246.png">
<img width="180" alt="Screenshot_20221001-101612" src="https://user-images.githubusercontent.com/73413313/193414277-6e75ba33-5a95-49cf-8dc6-4487db3e34db.png">
The depth did not have a special room with a naturally generated animated statue. Corrupting the Guardian kept the landmark note (checked with Mind Vision that that was the only statue)

I saw that sac fires and demon spawners were added to the Landmarks page in the beta, presumably for keeping track of score. The Guardian also counting as a statue raises concerns about them counting against the floor being fully explored for scoring, and the possibility of losing exploration points by tripping a Guardian trap on a depth that would have been considered fully explored.

While I don't have a screenshot, activating a Distortion Trap and summoning a Statue might also have the same effect (appears in landmark page and counts against scoring after levelgen)

**Comment by 00-Evan** [comment]
Will look into this for v1.4.0's full release, should be a fairly easy fix.

**Comment by 00-Evan** [comment]
Fixed in commit 539f1c8ea5e486bfc2cd0f41b2c2f5e7fe95c82b
