### ISSUE TITLE
The chance of Blooming

### ISSUE THREAD

**Issue by F-LTP** [00-Evan/shattered-pixel-dungeon#1099]
I've read the source code.In the Blooming.java line 49 I've found
float procChance = (level+1f)/(level+1f) * procChanceMultiplier(attacker);
Is it enhancement of blooming?I didn't find it in the change history.

**Comment by 00-Evan** [comment]
That looks like some incorrectly committed debug code

**Comment by 00-Evan** [comment]
fixed in commit 9a341e4480dac4ce34bda47064ebd0aa1d81ecae
