### ISSUE TITLE
Quickslot does not update when horn of plenty gains food

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#11]
When the horn of plenty gains more food, it doesn't update the quick slot it's in.  You need a `QuickSlotButton.refresh();` in hornRecharge at the end of the `if (partialCharge >= 36)` block.

**Comment by 00-Evan** [comment]
I'll include this in the next patch.

**Comment by 00-Evan** [comment]
corrected here: 
https://github.com/00-Evan/shattered-pixel-dungeon/commit/9d90a24a95eaed5a7b49b500b91d147de7d95ae7
