### ISSUE TITLE
Tengu arena walls can trap mirror images

### ISSUE THREAD

**Issue by sethoscope** [00-Evan/shattered-pixel-dungeon#110]
In the Tengu's cell, I read a Mirror Image scroll. One mirror image survived the initial encounter. When I reached the end of the maze and my surroundings turned into the arena, the mirror image got a wall drawn on top of him and was trapped in stone. I wasn't able to interact with it. I'd probably call this an acceptable quirk, more interesting than problematic, but I thought I'd post it.

![screenshot](https://cloud.githubusercontent.com/assets/534043/18024855/cd217600-6bc9-11e6-8aba-6764dca8d5c6.png)

**Comment by 00-Evan** [comment]
Interesting, I'm guessing that the sprite stuck around when the mirror image was deleted, as the arena shifting should remove all characters that aren't you or Tengu.

**Comment by 00-Evan** [comment]
fixed in commit 8501abc9cf992ef48401fb9831d2b8b0bd69d8fc
