### ISSUE TITLE
two ethereal chains

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1100]
Started game in 1.3, then upgraded to 1.4.  I found a second ethereal chains.  I believe it came from a group of bone piles.
![Screenshot_20221006-081008](https://user-images.githubusercontent.com/8593007/194309432-a3b85e13-c4a3-4776-9874-ba1648113e84.png)
![Screenshot_20221006-081227](https://user-images.githubusercontent.com/8593007/194309500-29f03839-46e2-466c-abc0-2964034d1ffb.png)
I'm assuming this only occurs when upgrading the game but thought I'd report it nonetheless.

**Comment by 00-Evan** [comment]
This is intended, sort of. Some item generation tables were adjusted behind the scenes which causes this on runs partially played through in v1.3
