### ISSUE TITLE
Status Effects Display Issue

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1101]
Playing on Android in landscape. Since the latest update, it seems like the status effects display beneath the health bar has been limited. This typically comes up in the Yog fight where I pull out all the stops to buff my char. Partway thru, a scorpio will hit me or a ripper will jump on me & the crippled/bleeding debuff won't show on the bar despite affecting my char. It's like the bar only has room for like 7 or 8 effects whereas before the update this wasn't an issue.

**Comment by 00-Evan** [comment]
This is an intended change in v1.4.0, as before the buff bar could go off the screen in cases where enough buffs could be applied. Now instead it matches the length of the hero's health bar. This limit is present even on mobile landscape to not advantage users playing on one orientation.

Buffs still apply to the hero as normal once the bar is full, and can be viewed on the buffs tab of the hero info window.
