### ISSUE TITLE
Lethal Inconsistency

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1102]
Lethal Momentum doesn't trigger on ghouls until the last 1 falls. Other abilities which trigger on killing blow do seem to work on individual ghouls, such as gaining damage for kinetic weapons or corrupting ghouls to fight their brethren. The language used in the descriptions is consistent but their application doesn't seem to be.

Other possible cases that might warrant attention to maintain consistency: gladiator's kill-for-armor ability, warlock's wraith conversions, rogue's Death Mark, assassin's Bounty Hunter, huntress' extension for Nature's Power. I'll try to test these as I get the opportunity & post to this thread when I get the chance.

My suggested fix would be to apply Lethal Momentum's effect to individual ghouls. This would make the talent consistent w/ other, similarly-worded abilities as well as giving the warrior an on-theme place to shine when surrounded by resurrecting undead where other heroes might falter. Slaying a group of almost-dead undead in a single turn would be so satisfying & I think the warrior could use a little buff as he's outshown in pretty much every aspect by the other heroes.

A simpler fix would be editing the description for the talent although I'm uncertain how to word it so that it's differentiated from other triggers-on-kill abilities.

**Comment by 00-Evan** [comment]
Both Kinetic and Corrupting do not trigger 'on-kill' per-se, but rather when damage dealt exceeds an enemy's remaining health. In the case of corrupting this is a compromise because having it truly check whether an enemy is dead or not would also make corrupting that enemy very complicated. For Kinetic things are working properly as intended.

Lethal momentum specifically checks if the enemy is dead, and is working correctly against ghouls.

**Comment by LeahLuong** [comment]
Gladiator's Lethal Defense does proc when slaying ghouls as their brethren look on.

**Comment by 00-Evan** [comment]
I see your point there, it shouldn't proc in that case. I'll look into re-evaluating how that effect triggers to make it more consistent with lethal momentum.

**Comment by LeahLuong** [comment]
Rogue's Deathly Durability procs when slaying ghouls as their brethren look on.

I was unable to determine for sure if Necromancer's Minions & Bounty Hunter do thanks to their probabilistic nature. I did see a ghoul drop its gold before its brother died while using Bounty Hunter but I think they can do that anyway.  I've seen both ghouls drop gold when slain simultaneously by a mage.

**Comment by LeahLuong** [comment]
It appears that a grim weapon triggering & slaying an enemy fails to proc Lethal Momentum. I think this failure can happen even if the triggering blow does enough dmg to push the enemy to 0 HP. Grim proc seems to override Lethal Momentum.

**Comment by LeahLuong** [comment]
Sacrificial altars may need to be included in the consistency pass for on-kill effects as well when you get around to it. Knocking down individual ghouls while their brethren look on count as sacrifices. I believe it may be possible to proc the altar using a single pair of ghouls; just keep knocking down the same ghoul until the prize pops out.
