### ISSUE TITLE
Barkskin OP, plz nrf

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1103]
Warden's Barkskin talent seems too good. Late-game, it's like having a 2nd set of upgraded plate mail on top of your upgraded plate mail that doesn't require Str to use. Armor becomes a non-issue for the huntress once she dons Tengu's mask & it's hard not to choose warden even in Barren Land runs thanks to this 1 talent. There's basically always a patch of grass around &, if there isn't, it's no big to toss down a seed or burn a door. I thought defense was supposed to be the warrior's forte but his Hold Fast can't hold a candle to this warden's talent.

On a side note, potion of earthen armor seems to override the buff gained from the talent when it seems like the 2 things should stack. I typically brew 1 of these for the DK fight but I found that's a detriment there because the talent greatly outshines the potion.

Lastly, I think Nature's Aid (NA) could use an overhaul. I noticed the previous threads here confusing grass for plants & I haven't put a single talent point here once I found this out for myself long ago. "Plants" aren't that common in the early game & the buff from NA is fleeting & miniscule. The trampled plant is likely to be a precious, early-game seed whose effect was likely more than enough to win the fight it was used for. DOT seeds are best used by running away from their victim, thus negating any possible benefit from NA. On average, NA is going to prevent 1 dmg/hit for a handful of turns, likely netting a savings of HP over the course of an entire run that barely cracks double digits. The opportunity cost of not spending your talent points elsewhere is just too high.

I'd like to see NA completely reworked & the warden Barkskin nerfed if not qualitatively altered. Perhaps the talents could be swapped, in a way: have it so NA triggers off grass & the Barkskin only from "plants". This way, the huntress gains a little mid-game survivability from the Rejuvenating Steps synergy w/ the tradeoff of losing the Barkskin brokenness later.

**Comment by 00-Evan** [comment]
Barskin is indeed quite strong, but not to the point where it is deserving of major nerfs. It is possible I may nudge it down in the future, but only slightly.

People have a variety of playstyles and preferences, nature's aid is actually reasonably popular and has a competitive success rate versus the other huntress T1 talents.

If you'd like to make subjective balance suggestions, it's better to email me. This place is more for reporting technical issues or suggesting technical enhancements.
