### ISSUE TITLE
enhanced ring of might not reflecting in displayed strength

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1104]
I have a ring of might +2.  With enhanced rings talent, this becomes +3 after using an artifact.  However, the enhancement is not reflected in the displayed strength.  
![Screenshot_20221008-221301](https://user-images.githubusercontent.com/8593007/194946178-4c51e8ee-cb0a-44bc-9af0-6927374cd089.png)
![Screenshot_20221008-202528](https://user-images.githubusercontent.com/8593007/194946379-cae1801e-bac6-4152-88d0-de88b083c6f6.png)
![Screenshot_20221008-202521](https://user-images.githubusercontent.com/8593007/194946393-b6079055-f77f-4003-91d2-bbcebe055d72.png)

**Comment by 00-Evan** [comment]
This is functioning correctly. The strength system is not affected by temporary upgrades. Weapons/armor don't lose strength requirement, and the ring of might does not provide extra strength.
