### ISSUE TITLE
boots of nature seed drop chance seems to be low

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1105]
I have had sandals/boots of nature since early game. I am now on level 24, and received hardly any seeds from stepping on grass during the game (but plenty of dew).  In games before the recent change to the sandal code, I felt like I got seeds a lot more often with the boots.  Now in v1.4 I'm just barely getting to a point where I can upgrade sandals to +10 on level 24, mostly only because of seed drops from evil eyes.  Is this just an unlucky run or is something wrong with the seed-dropping code?  Thanks!
![Screenshot_20221010-163125](https://user-images.githubusercontent.com/8593007/194947980-4464f4fe-e824-4e4c-9c69-eff16a996ffa.png)

P.S. the new power of sandals is a great enhancement.  Now I have a reason to wear the sandals even when not trampling grass!  (I just have trouble telling the color of the glow, which I've already mentioned in a previous issue.)

**Comment by LeahLuong** [comment]
Drop rates from the footwear were nerfed in the update but I feel your pain. It's tough getting the greaves & settling for the boots or shoes might be the new meta outside of extraordinary runs. W/out Rejuvenating Steps, I now find it hard to justify dedicating an artifact slot for a lesser hourglass or the ability to use mageroyal @ will.

FWIW, I think the activation costs for earthroot, sungrass, & starflower are overcosted.

**Comment by protective1** [comment]
Oh thanks.  Didn't notice before the part in the change log that states that number of dropped seeds was intentionally nerfed.
