### ISSUE TITLE
not trampling when waiting

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1107]
I'm trying to trample the vegetation made by the soiled fist using the "wait" button.  However, contrary to the release notes for 1.4, waiting does not seem to trample the vegetation I'm standing on.
![Screenshot_20221010-212207](https://user-images.githubusercontent.com/8593007/194976636-26a7a6c5-b632-426f-897d-8e83f828a9c8.png)
![Screenshot_20221010-212155](https://user-images.githubusercontent.com/8593007/194976670-d2d87d07-1edb-455b-9109-897f4c74bc0e.png)

**Comment by 00-Evan** [comment]
As the changelog states, you can wait and trample high grass. This does not apply to furrowed grass.

I'll consider adding a case for when the hero is on furrowed grass and not playing the huntress, but for now this is working as intended.
