### ISSUE TITLE
Overlapping Plants

### ISSUE THREAD

**Issue by bhilmers** [00-Evan/shattered-pixel-dungeon#1108]
Using a Wand of Regrowth near existing plants can result in two plants occupying the same tile, which is not possible when planting seeds. Not sure if this is expected behavior.

SPD v1.4.0
Android 12
Samsung Galaxy A12
![Screenshot_20221011-151204](https://user-images.githubusercontent.com/77466683/195198220-353228cd-4184-4af4-9c29-d4286690432b.jpg)
![Screenshot_20221011-151244](https://user-images.githubusercontent.com/77466683/195198232-41d489d4-c41e-4808-8c7a-5cd2cebc3983.jpg)

**Comment by 00-Evan** [comment]
There's only one plant at that tile (the blindweed), the other is a seed, which is an item.

**Comment by bhilmers** [comment]
Ah, I see now, sorry about that.

**Comment by 00-Evan** [comment]
No worries
