### ISSUE TITLE
The upgrade removal.

### ISSUE THREAD

**Issue by Wolfman1234567890** [00-Evan/shattered-pixel-dungeon#1109]
I had spears I upgraded but when I did the mining quest and put them together the upgrades were gone.v1.4.1

**Comment by Wolfman1234567890** [comment]
<img width="230" alt="Screenshot 2022-10-12 at 12 20 38" src="https://user-images.githubusercontent.com/115623699/195303931-08417d15-6166-4058-8773-35d2494d0717.png">
<img width="230" alt="Screenshot 2022-10-12 at 12 20 28" src="https://user-images.githubusercontent.com/115623699/195303962-6bbbb3c4-44ae-49eb-8ee7-2e4ad9d74de9.png">
<img width="230" alt="Screenshot 2022-10-12 at 12 20 17" src="https://user-images.githubusercontent.com/115623699/195303976-80f96d5e-cfd9-42b5-8604-a3c26cd33e60.png">
<img width="230" alt="Screenshot 2022-10-12 at 12 21 58" src="https://user-images.githubusercontent.com/115623699/195304232-226c3e8a-0bac-4f5e-b43c-64ea000173ff.png">

**Comment by Wolfman1234567890** [comment]
I started with v1.4 and upgraded to 1.4.1

**Comment by Wolfman1234567890** [comment]
If an upgrade is +4 and a spear is +20 then the spear should be 11-64 or is it right. I have never ben able put things together because I don't identify them so I don't know if I'm right.

**Comment by npetronio1** [comment]
Hello @Wolfman1234567890, I would like to work on this issue. Could you please assign it to me?

**Comment by Wolfman1234567890** [comment]
I am new so I don't know how to do that can you please help me out.

**Comment by Wolfman1234567890** [comment]
I die to dm-300.

**Comment by Wolfman1234567890** [comment]
The 2 floor down so it would help if the damage was 64.

**Comment by Wolfman1234567890** [comment]
And I think I have another bug the artefacts didn't charge on the 15th floor during the boos fight.

**Comment by 00-Evan** [comment]
The blacksmith's quest does not combine upgrade levels, it sacrifices the weaker item to put one upgrade onto the stronger one.

Regarding artifacts in the boss fight, if you hide and don't attack the boss, then items like wands and artifacts will eventually stop recharging.
