### ISSUE TITLE
Class armor of Stone

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#111]
Class (e.g. Rogue/Mage/etc.) Armor of stone seems to lose its improved minimum value.

Example: Rogue armor converted from Plate armor +6 of Stone gives 8-40 DR instead of 14-40 DR.

**Comment by 00-Evan** [comment]
Which version of the game are you running? This should be fixed in 0.4.1a

**Comment by camlost** [comment]
V0.4.1.  I'll assume it's fixed, then.
