### ISSUE TITLE
Quality of Life for Death

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1110]
Corrupted enemies drop if they're going to when corrupted. Death Marked enemies don't; you need to wait for them to croak to see if they'll roll a drop. Would be a nice QoL improvement if they rolled their drop on hitting 0 HP. Fear the Reaper makes them run away from you so you can sometimes lose track of them if they run around a corner during a hectic battle; I believe this can cause a fully explored depth to become not so if you fail to recover a dropped item.

**Comment by 00-Evan** [comment]
The main difference here is that corrupted enemies become your ally, while death marked enemies are still hostile to you, even in death. Also, any items that are not dropped as part of levelgen do not count against exploration score.

**Comment by LeahLuong** [comment]
Thanks for clearing that up for me.
