### ISSUE TITLE
Demon Spawners & Minions

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1111]
I thought this may've been addressed by the AI updates mentioned in the latest patch notes but apparently not. My recent warlock run was unable to get the Doom Slayer badge because 1 of my wraiths ran off & singlehandedly destroyed a demon spawner. I think it'd be nice if they ignored these until seeing you start to attack 1.

If you choose to address this, consider giving the same treatment to summoned elementals. Much lower chance they'd be able to pull it off w/out dying but you can't control these in the same way wraiths do their own thing.

**Comment by Wolfman1234567890** [comment]
You should be able to get to control theme with the staff by preparing k.

**Comment by 00-Evan** [comment]
Corrupted enemies are intended to be autonomous, it would be annoying a majority of the time if they did not attack spawners before you attack them.

**Comment by Pr0methean** [comment]
Why not change the badge criterion so that kills by autonomous allies count?

**Comment by 00-Evan** [comment]
> Why not change the badge criterion so that kills by autonomous allies count?

You're not thinking of the right badge. Doom Slayer requires the spawners to all still be alive when Yog is killed.

**Comment by Pr0methean** [comment]
ok, so maybe they should have a "shield" against autonomous allies that you can ask an NPC to summon or dismiss.

**Comment by LeahLuong** [comment]
I can think of several reasons why it's more annoying the majority of the time w/ their current behavior:
1) Avoiding the loss of the Doom Slayer badge practically requires you to ignore 1 of the main perks of the warlock: wraiths.
2) If you don't ignore it, you end up having to babysit them or kill them off as they're generated.
3) When a wraith goes after a demon spawner, the dmg causes it to kick out rippers faster than it normally would. These end up leaving as a group once the wraith is dealt w/, leading to a spike in the danger lvl for the player in addition to the loss of the badge.

I neglected to mention in my OP that corrupted enemies (by wand or weapon) have the same behavior pattern & expand this prob to all hero classes.

It's not like demon spawners are difficult to destroy & require the aid of minions to take down. Can you please let me know why you think it would be more annoying if autonomous allies ignored spawners until seeing you attack them??

**Comment by 00-Evan** [comment]
> I can think of several reasons why it's more annoying the majority of the time w/ their current behavior:
> 
>     1. Avoiding the loss of the Doom Slayer badge practically requires you to ignore 1 of the main perks of the warlock: wraiths.
> 
>     2. If you don't ignore it, you end up having to babysit them or kill them off as they're generated.
> 
>     3. When a wraith goes after a demon spawner, the dmg causes it to kick out rippers faster than it normally would. These end up leaving as a group once the wraith is dealt w/, leading to a spike in the danger lvl for the player in addition to the loss of the badge.
> 
> 
> I neglected to mention in my OP that corrupted enemies (by wand or weapon) have the same behavior pattern & expand this prob to all hero classes.
> 
> It's not like demon spawners are difficult to destroy & require the aid of minions to take down. Can you please let me know why you think it would be more annoying if autonomous allies ignored spawners until seeing you attack them??

Because the vast majority of runs are not going for that badge and will want to kill the spawners. The aggravated ripper spawning is also based entirely on taken damage, there's no downside (in terms of total rippers spawned) to having the damage dealt by a distant minion versus yourself directly. A swell of rippers may be a concern, but they will all pick random locations to wander to, and the spawner's death will prevent future rippers from appearing.
