### ISSUE TITLE
Room Exclusions for Mobs??

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1112]
1 thing that's bugged me awhile is how golems will teleport into & trample all the plants in a secret garden before you can do anything about it. It's especially annoying when you could've gotten some extra benefit from footwear. Would it be possible to bar mobs from going into hidden rooms until your hero has?? 1 time, a golem pulled me into the summoning trap room as soon as I opened the door, causing me to trigger all the traps.

A similar issue can occur w/ any mob if you use magic mapping. I'll frequently find the golden bee dead in the demon halls because I tend to save my scrolls for this chapter.

**Comment by 00-Evan** [comment]
Enemies are normally barred from entering locked rooms, but golems are intended to be an exception.

**Comment by LeahLuong** [comment]
Also kinda silly how mobs go into the shopkeeper's store but ignore his presence.
