### ISSUE TITLE
succubus attack charms when zero damage

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1113]
Succubus attack did zero damage but still charmed me.  Is this intentional?  I would not expect it to have an effect if it does zero damage. ![Screenshot_20221013-184625](https://user-images.githubusercontent.com/8593007/195724379-a60286b6-b6f5-4474-b22e-71a43e2753fb.png)
![Screenshot_20221013-184806](https://user-images.githubusercontent.com/8593007/195724509-28ef7477-d896-4d42-b953-d8418f6e2a9f.png)
![Screenshot_20221013-184801](https://user-images.githubusercontent.com/8593007/195724514-de88193a-db7d-43fb-a57d-d4853ecbcb9e.png)

**Comment by 00-Evan** [comment]
Charm is intended to trigger if the attack hits but is fully blocked. 0 damage and missing aren't the same thing.
