### ISSUE TITLE
hourglass, mystery meat, seed of icecap

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1115]
I activated timekeepers hourglass to freeze time.
I threw a seed of icecap on the ground next to a mob.
I threw a mystery meat on the resulting icecap plant.
Time was still frozen.  I threw a second mystery meat on the first.
Time unfroze (I attacked).
Only one of the two mystery meats had become frozen carpacio.
I expected the meats would stack and both become frozen.
![Screenshot_20221014-201333](https://user-images.githubusercontent.com/8593007/195960154-403ebad7-9674-4e02-861f-a2b3e8869632.png)
![Screenshot_20221014-201410](https://user-images.githubusercontent.com/8593007/195960165-42cd73c3-7a62-44de-bd47-1a5ab050f248.png)

**Comment by 00-Evan** [comment]
The reason for this is that most effects resolve instantly when they are triggered, so the freeze on the meat occurs the moment that meat is thrown on the icecap. These effects have no concept of 'time', they just execute logic when they are triggered.

Traps have specific exceptions to this behaviour, their triggered is held back by the time freeze buff itself and all triggered occur the moment the time freeze ends.

I'll consider having plants work the same way, but can't garuntee it as it may cause issues elsewhere.

**Comment by 00-Evan** [comment]
functionality added in commit 49b73a75750a79e9114706264f28e871f74d6918
