### ISSUE TITLE
Door animation when enemy follows player

### ISSUE THREAD

**Issue by Pr0methean** [00-Evan/shattered-pixel-dungeon#1116]
When I step out of a doorway and an enemy steps into it, the sound effect of the door closing and opening plays, but the animation doesn't. It's clear that the door *is* opening and closing from a gameplay perspective, because my next attack gets the ! icon for a surprise attack and is never dodged, and this doesn't happen when another enemy entered the door on the previous turn (evidently enemies don't close the door behind them), but it took me a while to figure out how this worked. Why not blink the door closed for a fraction of a second, after the player leaves the doorway tile and before the enemy enters it?

**Comment by 00-Evan** [comment]
The reason for this is that the game logic for stepping on a location resolves before the visual movement starts. While I do agree that something like this would be nice, it would take significantly more dev work that it would appear to.
