### ISSUE TITLE
Thank You for Boxing My Blandfruit

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1117]
Nothing earthshattering but I found a quirk where dropping an item into a chasm resulted in me finding that item by itself in a chest on the following depth. Made me smile wondering which mob would be so kind.

**Comment by 00-Evan** [comment]
The falling item's random position was on top of another item, and so it was added to that item stack. This is intended and necessary to prevent edge cases where a floor full of items would otherwise crash the game.

**Comment by LeahLuong** [comment]
This is why I said, " . . . finding that item **by itself** in a chest on the following depth." There were no other items in the box besides the blandfruit. I believe levelgen placed it in there as blandfruit is normally only found in gardens or hidden rooms when trampling their respective plant.
