### ISSUE TITLE
Alchemists Toolkit gains charge when loading game

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#1119]
I have an Alchemist's Toolkit equipped on my Gladiator, with no buffs applied, and no rings or enchantments that affect recharging.

The artifact was just equipped (at +0), so had no charge. After loading the game 4 or 5 times, without moving, the toolkit was at 5%.

Version 1.4.0. Ubuntu 20.04. Using snap.

![alchemists-toolkit](https://user-images.githubusercontent.com/5109532/196329146-ecd1acb5-546e-4cf2-a4d9-841dcfbea41a.gif)

**Comment by 00-Evan** [comment]
That's actually the warm up percentage for the toolkit, not its charge. Regardless that shouldn't be happening, will take a look at why that might be happening.

**Comment by 00-Evan** [comment]
fixed in commit 9bc40ebbb49b57840aaf31355e35becf5acaa65e
