### ISSUE TITLE
Infinitely burning flammable tiles

### ISSUE THREAD

**Issue by ListenToTheWhiteNoise** [00-Evan/shattered-pixel-dungeon#112]
The fire lasts forever on a flammable tile when I keep on moving away and walking back on it while it's still burning.

This seems to be an old bug: http://pixeldungeon.wikia.com/wiki/Old_bug#Infinitely_burning_flammable_tiles

I'm playing in v0.4.2-BETA-6.

**Comment by 00-Evan** [comment]
Beta issues are not relevant to the open source, please do not post them here.

**Comment by 00-Evan** [comment]
I will, of course, fix this though, forgot to mention that.

In future please email me with any issues pertaining to betas.
