### ISSUE TITLE
Prismatic Force

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1120]
It seems like the prismatic guards summoned by scroll of prismatic image don't benefit from the hero's use of a ring of force as their primary weapon. I was typically dealing 30-40 dmg w/ a +6 ring while the guard was only managing single digit #'s. Mirror images don't seem to have this problem as they were dealing much more substantial dmg (I saw 1 do 29).

**Comment by 00-Evan** [comment]
Prismatic images copy the player's armor instead of their weapon, and do a set amount of damage (which is fairly low). That's the main tradeoff versus mirror images, which use the player's weapon but are otherwise fragile.

**Comment by Pr0methean** [comment]
Then shouldn't this disadvantage be documented in the description for the Scroll of Prismatic Image?

**Comment by LeahLuong** [comment]
![Screenshot_20221026-150506](https://user-images.githubusercontent.com/91638992/198154751-7637a56d-a317-4edc-aa0c-56b29ef46284.png)

" . . . current weapon _**AND**_ armor."
