### ISSUE TITLE
Lethal Inconsistency, Pt. 2

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1121]
I made the comment below in another thread but I think it may have gone unnoticed & prob deserves its own bug report:

        It appears that a grim weapon triggering & slaying an enemy fails to proc Lethal Momentum. I think this failure can happen even if the triggering blow does enough dmg to push the enemy to 0 HP. Grim proc seems to override Lethal Momentum.

_Originally posted by @LeahLuong in https://github.com/00-Evan/shattered-pixel-dungeon/issues/1102#issuecomment-1279652203_

**Comment by LeahLuong** [comment]
The other issue has to do w/ the interaction betw/ Lethal Momentum & ghouls. This issue has to do w/ the interaction betw/ Lethal Momentun & grim weapons. Did you even read the comment??

**Comment by 00-Evan** [comment]
> The other issue has to do w/ the interaction betw/ Lethal Momentum & ghouls. This issue has to do w/ the interaction betw/ Lethal Momentun & grim weapons. Did you even read the comment??

You have made it abundantly clear that 'on-kill' effects need a consistency pass. There is no need to create a separate issue for each instance of this.
