### ISSUE TITLE
Cursed Disintegration

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1122]
It's possible to test the wand for a curse by standing next to a wall & attempting to fire thru it. If it's cursed, you'll get the "can't self-target" text & nothing happens. The wand will retain its purple background implying you don't know its status but you will . . . you will know . . .

**Comment by 00-Evan** [comment]
This is intended, you aren't supposed to be able to target yourself with cursed wands in any case. I'm fine with this letting players indirectly curse-ID disintegration. You can actually do this due to a very recent fix in v1.4.1
