### ISSUE TITLE
Unreliable Projections

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1125]
Something seems to be up w/ projecting weapons & I believe this issue was introduced by a recent change. @ least, my battlemage's staff of disintegration was doing this:

![Screenshot_20221022-112308](https://user-images.githubusercontent.com/91638992/197369110-064415cb-eef7-4515-ba47-99741a84afbc.png)

![Screenshot_20221022-112354](https://user-images.githubusercontent.com/91638992/197369136-ff2c1a1a-25f1-414b-ae26-256f6ed595c9.png)

![Screenshot_20221022-112427](https://user-images.githubusercontent.com/91638992/197369156-35329c7a-ad68-412b-9dd8-94bd9cc2da1d.png)

![Screenshot_20221022-150818](https://user-images.githubusercontent.com/91638992/197369179-f98ecb06-a52b-4c66-8b5f-5a23a6ffa9a1.png)

As you should be able to tell from the 1st & 4th pics, I'm able to mélée from 3 tiles away. This isn't the case in the 3rd pic even though my position & EQ were the same as in the 1st pic; I moved around some trying to replicate. This issue only arises intermittently & I was unable to tell what was causing it. @ 1st, I thought it might have something to do w/ a ring of haste I was using but I'd changed my EQ by the 4th pic & was no longer using it. Ring of arcana wasn't involved because I never got 1 on this run. Most times, projecting was only targeting up to 2 tiles away but there were several other times in this run where I could reach 3.

I don't recall this being a thing prior to 1.4.1.

**Comment by 00-Evan** [comment]
Are you using the empowered strike talent? In the recent update that talent was changed to boost the power of the battlemage's staff effect, which includes the bonus reach on a disintegration staff.

**Comment by LeahLuong** [comment]
Ah, that must be it. I'd put 3 pts into that talent by the time I'd taken these screen caps.
