### ISSUE TITLE
Imperfect Reflections

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1126]
Mirror images are able to use reach weapons effectively but I don't believe this is the case if they are mirroring a battlemage wielding a staff of disintegration; they'll run right up to enemies before fighting them. I'm also pretty sure mirror images don't account for ring effects. My hero was using a ring of haste & I seemed to be outpacing them.

**Comment by 00-Evan** [comment]
This is intended. Mirror images copy your hero's appearance and weapon, but do not copy class and subclass benefits.
