### ISSUE TITLE
Dodged Attacks Count Against Score

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1131]
![Screenshot_20221026-155535](https://user-images.githubusercontent.com/91638992/198155751-b15b9f12-3d40-4e25-938f-b894acf05a89.png)

I've several perfect scores under my belt & so know what it takes to do that. In this run, the only possible thing that prevented my perfect were 2 dodged warlock bolts in the DK fight. I had all boss badges except DK implying Goo didn't heal or blast me. Tengu wasn't able to trap me. I avoided DM-300's rockfalls. Yog's lasers deduct in chunks of 500 pts.

If score-deducting attacks are dodged or nullified due to invulnerability, then they shouldn't count against your final score.

**Comment by 00-Evan** [comment]
I do admit that the text here is very misleading, but the behavior is intended. I don't want the player to be able to just build their run such that they can max boss score though stats. To avoid those point penalties you must use good positioning.

I can see that Yog-Dzewa isn't following this rule at the moment though, and is only penalizing the player if they are actually damaged by the laser. I'll leave this issue open to track that, and also will see about changing that text.

**Comment by LeahLuong** [comment]
I agree that good positioning works in many cases but the DK fight is sometimes up to luck. I've seen it where a golem has a valid path but still chooses to yoink you into a warlock's firing line. Dodging is the last line of defense & that's a dice roll. So much for "avoidable" dmg.

**Comment by 00-Evan** [comment]
fixed in commit 385fa9791c314691bbc24c28286b0a9357b7b6bf

**Comment by Pr0methean** [comment]
This issue needs a response to @LeahLuong's latest comment.
