### ISSUE TITLE
Anti-magic & Reclaim Trap

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1133]
Placing a trap while under the effect of a scroll of anti-magic tells the player they can't cast spells but also causes the hero to simultaneously attempt moving to the selected location. This may be an issue for other spellstones.

**Comment by 00-Evan** [comment]
This is happening because selecting the item does not cause a targeting prompt to pop up (as the effect was cancelled by antimagic) and so tapping on a target location will be interpreted as a regular move action when no targeting prompt is active.
