### ISSUE TITLE
AI for fist doesn't step around obstacle to attack

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#1134]
![Screenshot_20221027-081053](https://user-images.githubusercontent.com/162737/198215851-0865fc41-c084-4080-9861-a272b8bf5e23.png)

Standing in the position shown in the above screenshot, with a projecting bow, I could shoot the fist repeatedly, and it never moved to attack me.

**Comment by 00-Evan** [comment]
Read the fist's description, it is a large enemy and can't move into enclosed spaces, such as between two skull piles.

**Comment by joshtriplett** [comment]
It could have come around the other way, or moved to where it could shoot me. Something other than sit there and let me kill it slowly without reacting.

**Comment by Pr0methean** [comment]
I think the general issue is that the AI doesn't account for the reach of its melee attack when it's looking for a place it can route to that, while not adjacent to the player, still brings the player into melee range.
