### ISSUE TITLE
Projecting bow can shoot through wall-then-web, but not through web

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#1135]
![Screenshot_20221027-085445](https://user-images.githubusercontent.com/162737/198224441-06410e8f-f424-456d-b660-855aaacbfff4.png)

I have a projecting bow. The enemy was previously standing directly to the right of the web (caught in a second web so it didn't move for a few turns).

Standing in the doorway, such that only the web was in the way, if I tried to shoot the enemy, my shot was blocked by the web.

If I stepped left, to the position shown in the screenshot (but with the enemy still directly to the right of the web), I could shoot through the door *and* the web.

**Comment by 00-Evan** [comment]
Figured this out, it's not to do with the web specifically, but rather an enemy standing in solid terrain. A check that's meant to prevent the player from throwing projectile weapons into walls is also triggering there.

**Comment by joshtriplett** [comment]
@00-Evan Ah, I see. So it's not about the web between the player and the enemy, it's about the web the enemy was caught in?

**Comment by 00-Evan** [comment]
fixed in commit 9ae5836f98cf1c8e0507d7a12e620223891e616e
