### ISSUE TITLE
Meat Off the Bone

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1137]
![Screenshot_20221028-105446](https://user-images.githubusercontent.com/91638992/198738559-8cad19e7-66d0-44cf-8219-75efee6f997c.png)

It's possible to steal mystery meat from cave spinners. The real mystery is how this is done w/out dmg or fatality for the spider. The same can be done for sewer crabs & giant piranha. Perhaps there should be an exclusion for stealing monster body parts while they're still alive; or perhaps a successful steal of this type of item should dmg or kill the victim.

Is it possible to steal their meat & have them drop more on death??

On a side note, this particular spider seemed to be stuck in the corner. The blacksmith's forge had another egress but the spider seemed fixated on the secret door in the corner; I was able to observe it for a few turns using Heightened Senses hoping it would go away. Revealing the secret door using wand of prismatic light caused the spider to hop thru the door where its meat was pilfered.

Further along in this run, I spotted a gnoll shaman in a similar situation: he was in a hallway on the other side of an unrevealed secret door. Using the wand caused the gnoll to start pathing away from the door.

![Screenshot_20221028-112143](https://user-images.githubusercontent.com/91638992/198740468-0da5e9f8-0e02-41e8-9ede-29b811e176c0.png)

After spotting the gnoll, I threw a shuriken @ the non-secret door in prep for shooting a beam of light south to maximize its effect. The revealed door was directly west of the gnoll. The gnoll was in a donut which itself was in an L-shaped hallway, w/ the gnoll @ the elbow of the L. IDK if he was standing there for long & I didn't take time to observe him but if he was moving prior to my spotting him his pathing was to go right up to the secret door & then turn around upon its revelation; I'd have spotted him sooner if he'd been further north in the L. This leads me to believe he was camping the secret door like the spider from before.

**Comment by 00-Evan** [comment]
I do agree that stealing mystery meat from enemies is thematically odd, but this is the item type they are meant to have a chance to drop, and I would rather allow it than limit which items the armband can help you steal.

Regarding secret doors, enemies do not intentionally camp them, but if they were on a level with lots of hidden doors, they might end up idling for some period of time, as several of the locations they might randomly choose to wander to would be inaccessible to them.

**Comment by Pr0methean** [comment]
TIL shurikens make effective doorstops.
