### ISSUE TITLE
FR: Holiday Shutoff Switch

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1138]
Not all peoples &/or cultures celebrate All Hallows' Eve. The same can be said for winter holidays.

On top of that, there's an element of stolen valor for those runs which scraped by thanks to the HP gain from pumpkin pie or the extra wand charges from candy canes. Every edge counts in high challenge runs & these food items are like having extra talent activations that wouldn't otherwise be there were it not for the calendar setting. I have to give any successful run during these times a side eye because of their built-in advantage.

There should be a toggle in the settings to turn off the food items related to the holidays. That, or these items should be reverted to pasties during challenge runs  regardless of the time of year.

**Comment by 00-Evan** [comment]
Both of the holiday items are intended to be very general, specifically to avoid cultural sensitivities. If someone feels offended by a piece of pumpkin pie or a candy cane then I don't really think that's the game's problem.

Additionally, while I do agree that the 10% health boost from the is probably stronger than the wand boost from candy canes, they are ultimately meant to be insignificant. Putting a toggle for them would be unnecessary UI complexity, and would do nothing to stop other players from using them for an advantage.


Over the last ~20 days you have opened 22 issues on this repository, more than every other user combined. Only three of those issues (four if you count lethal inconsistency) were not immediate closed as not planned. Please take more care when opening issues in the future.

**Comment by LeahLuong** [comment]
I think your assessment of my activity in this repo is unfair. Skimming over the last year's threads before I started posting here reveals about the same average response on your part. You're fairly diligent in tagging issues which you address in patches & so it's easy to see about 4-5 make it into dev for every 25 you close as not planned. My batting average by your metric is .182, about par for the course but perhaps not the .250 the major leaguers are able to manage; working on it.

I've also been careful to avoid posting dupes by researching this repo before making any new threads. The issues I've raised can help prevent dupes in the future or remain as discussion points for others in further conversations.

That said, I see the pattern you prefer bug reports to feature requests; you'd prefer the design decisions be left to you & crowdsource the sleuthing of failures in technical implementation. Several of the issues I've raised have been more on the FR side of things & I see I should prob reign that in a bit.

Most every dev has to balance working on new content & polishing the old. I don't mean to come off as spammy & I genuinely like the game. I write here because I want to help the game become even better. I look forward to the release of the duelist & hope my contributions to this repo don't unduly postpone it.

**Comment by 00-Evan** [comment]
Let me put it this way. Every day there's a certain amount of time I spend processing emails, messages, reports, etc. That's an important task, but it's ultimately time that I'm not spending working on the game, so I try to limit it. When a particular person is sending lots of message (regardless of the method), that ends up taking a proportionally large amount of my time versus other messages and risks crowding them out.

I certainely don't mean that reports from you are unwelcome, just please be a bit more considerate of the fact that your messages take time to respond to. From what you've written in your reply, it seems you're already well on your way to doing that.
