### ISSUE TITLE
Status Overflow

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1139]
![Screenshot_20221029-151437](https://user-images.githubusercontent.com/91638992/198856326-4c33887c-26ba-4a0a-8a31-96d7a54a7c75.png)

As you may see, the crippled status for this mob is cut off. I'd examined it because I wanted to see if it was also bleeding after I threw a tomahawk. I still don't know if it was. Can spectral beings bleed?? I think I've inflicted bleed on wraiths but they don't really do it because 1 HP.

This issue is somewhat particular to this mob thanks to its long name but perhaps it's compounded when accounting for translations of other names. Would be nice if the new status effect compression we got in 1.4.2 were applied here. That, or perhaps mob status effects deserve their own dedicated space rather than being appended to the name.

**Comment by Wolfman1234567890** [comment]
Also the icons go out of the info box.

**Comment by Wolfman1234567890** [comment]
<img width="377" alt="Screenshot 2022-10-30 at 18 12 52" src="https://user-images.githubusercontent.com/115623699/198886264-173631d1-1566-4340-82c5-a38ec8d27507.png">

**Comment by 00-Evan** [comment]
fixed in commit 95b2a2208b2af46b68009ddff406a886b2c02f70
