### ISSUE TITLE
Cross-counter kills sometimes freeze game until reloaded from main menu

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#114]
Running up to a monster, triggering a simultaneous attack animation, and hitting it enough to kill it has a roughly 25% chance of stumping the game, forever wondering what happened until you exit to menu and reload the game.

**Comment by 00-Evan** [comment]
I have been getting reports of this bug but wasn't able to reproduce it as nobody was providing any description or reproduction steps.

I've now managed to successfully reproduce it, will fix and include in 0.4.2b, thanks.

**Comment by 00-Evan** [comment]
fixed in commit c6d86f42abcf026478b6b3424b7d46d93ffb24e8
