### ISSUE TITLE
[Bug] Player and NPC overlap

### ISSUE THREAD

**Issue by megz15** [00-Evan/shattered-pixel-dungeon#1142]
I had used a Scroll of Mirror Image before. The Image was at a door when a Crazy Thief behind the door saw me, the Image got attacked and died and I moved towards the door. Somehow the thief and I occupy a single tile now, it doesn't seem intentional.

![Peek 2022-11-02 10-38](https://user-images.githubusercontent.com/56220472/199403186-7fe60ead-6908-4414-bf4a-f674790e0c97.gif)

The Thief also was in its "running" animation state before I turned off fullscreen to capture the gif

**Comment by 00-Evan** [comment]
Thanks for the more detailed report, I'll look into this. I've had this reported once or twice (usually focused around ally swapping) but haven't been able to reproduce it yet.

**Comment by 00-Evan** [comment]
Fixed in commit b8947e78fc062d239bfeaf7505780f79dec4cc6c
