### ISSUE TITLE
Drunken Potion

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1144]
![Screenshot_20221102-162926](https://user-images.githubusercontent.com/91638992/199629798-4fe42876-0620-44ef-b97a-6232c419c543.png)

"Drank" is the past tense of "drink." "Drunk" is its past participle. "Drunk" can be correctly used here if the wording is changed to, " . . . might do when you've drunk it or it's thrown," although the simpler & more efficient solution would be to swap "drank" for "drunk."

Additionally, there should prob be a period following "land" & "who" capitalized. It's arguable a semicolon would do but the statement & question can stand on their own.

**Comment by megz15** [comment]
In passive sentences, usage of past participle is correct. "Who knows what it might do when drunk or thrown (by you/by the player)" is grammatically correct, I believe.

**Comment by LeahLuong** [comment]
@megz15 Good catch w/ observing this verb is being used in passive voice. In that case, it needs the helping verb "be," properly conjugated: " . . . might do when it _**is**_ [could be shortened to "it's"] drunk or thrown."

The 1st part of this run-on sentence was in active voice & then it switches after the comma; further reason it should be split.

**Comment by LeahLuong** [comment]
Here's a helpful link on the subject:

https://www.thesaurus.com/e/grammar/drink-vs-drank-vs-drunk/

**Comment by 00-Evan** [comment]
No grammar nitpicks please.

It's also worth noting that some of the slightly awkward grammar is actually inherited from the original Pixel Dungeon. I've removed most of it at this point (some of it was very clearly incorrect, such as "welcome to the level X of Pixel Dungeon"), but I'd like to preserve a bit of it where reasonable.

**Comment by Pr0methean** [comment]
I would've used the active voice, "when you drink or throw it".
