### ISSUE TITLE
The imp is difficult to see

### ISSUE THREAD

**Issue by ResCXsention** [00-Evan/shattered-pixel-dungeon#1146]
It's not impossible to see him, but it's very easy to pass over him if you're not paying attention or not zoomed in close. Would more contrast be possible, or at the very least, could he be taken off of the red carpet where he blends in far too well?

**Comment by 00-Evan** [comment]
This is the nature of the game's invisibility vfx. It's why there are also things like a print to the game log when the imp first comes into view.

I will eventually rework his quest, and will probably give him his own dedicated room type at that point. In the meantime, I'd prefer to leave it as-is.
