### ISSUE TITLE
Infinite loop when triggering teleport trap with honey pot

### ISSUE THREAD

**Issue by un-logic** [00-Evan/shattered-pixel-dungeon#115]
I've thought it would be funny to trigger teleportating trap with honey pot (unshattered) only concern I had that bee will stay in place of trap and rush to random direction stinging anyone on her way to the pot wherever that is. But, unfortunately, instead game has stuck in a loop.
After restart game loaded successfully, alas not a clue of honey pot anywhere.
Game version is 4.0.2a.

**Comment by 00-Evan** [comment]
I assume you mean game version 0.4.2a

I've just tested this with the latest version (0.4.2b) and this seems to be working properly. Make sure you have the latest update.

**Comment by un-logic** [comment]
It is 0.4.2a, of course - latest available at F-droid repositories ATM, AFAIK.
Well if it's fixed in next release it's fine then I guess.

**Comment by 00-Evan** [comment]
Currently F-Droid is having a little trouble building the latest shattered release, if you care you can follow that here: https://gitlab.com/fdroid/fdroiddata/issues/519
