### ISSUE TITLE
Clicking on item with full inventory will lift it up

### ISSUE THREAD

**Issue by bjoern-tantau** [00-Evan/shattered-pixel-dungeon#1150]
When your inventory is full and you click multiple times on an item on the ground it will lift up every time you click on it, making it look like it is flying.

Just a minor visual bug, but it looks funny. 

https://user-images.githubusercontent.com/8307357/200793113-26aec1e9-7fb5-4041-9654-02ba504d84be.mp4

**Comment by TheYsconator** [comment]
I believe this is a relic from vanilla PD, left as a bit of a gimmick.

**Comment by TheYsconator** [comment]
Ah yes; ref #689
