### ISSUE TITLE
Camouflaged Cripple

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1151]
Getting pulled by prison guards seems inconsistent when wearing armor w/ a camouflage glyph & using Rejuvenating Steps. Here, I was pulled & released partway:

![Screenshot_20221103-194701](https://user-images.githubusercontent.com/91638992/200969549-aa0dd77a-aa4d-42ed-9b97-30ef58cccbe7.png)

![Screenshot_20221103-194738](https://user-images.githubusercontent.com/91638992/200969601-73cedf02-6c90-4c13-a8fc-edbaabfd7be7.png)

Normally, guards are able to complete their pull but lose track once camouflage procs. This happened shortly after the previous image & slightly north:

![Screenshot_20221103-194830](https://user-images.githubusercontent.com/91638992/200969914-3443a62a-4f62-4016-94d5-eb6ae1f900f1.png)

![Screenshot_20221103-194845](https://user-images.githubusercontent.com/91638992/200969999-f85cb068-81be-4314-ba87-358c5bf9b336.png)

Notice the difference in cripple duration?? I was using a ring of furor. It seems the debuff duration is tied to when the guard uses his pull instead of being linked to the turn clock & keying off of a specific # for the player. This may explain why the guard's pull behavior is inconsistent w/ this setup.

Flavorwise, this entire interaction seems weird. How come the guard loses track of you after you engage your Predator cloak when he has his chains wrapped around you?? If I'm not mistaken, this ability is a reference to Mortal Kombat's Scorpion. Shouldn't the guard @ least get an uppercut or jump kick in before you can slip away??

**Comment by 00-Evan** [comment]
The odd duration is due to the player working on partial turns. The duration difference you're seeing here is reflective of the time between the guard's action and your action.

There's a pretty clear event order of pull -> press tile -> become invisible here. Enemies cannot attack you while invisible and I'd prefer not to start adding exceptions to that for the sake of flavor.

Regarding the shorter pull though, that one seems odd but from examining it a moment I think I know what's happening. The guard seems to be in the middle of a movement animation, so he did pull you to an adjacent tile, but then walked one tile south as he lost track of you.

**Comment by LeahLuong** [comment]
IDK if your interpretation of the 1st set of images is correct. Both sets of images were captured just after being pulled. I did notice the lack of question mark in the 1st image (indicating loss of tracking) & this is why I created this post. Normally, mobs will pause a turn after losing tracking w/ a question mark above them. This didn't happen in the 1st case; the guard pulled me partway, camo activated, & the guard remained in position. This is also why I took the image of the status description box @ the same time. Had I paused a turn to clear the question mark, the crippled debuff would be @ 1.84 turns. Are you saying the debuff window should have read 3.84 if I didn't accidentally press the wait button?? In my experience, that crippled debuff lasts 3 ticks. Pretty sure I didn't fat-finger it but anything's possible, I suppose.

**Comment by 00-Evan** [comment]
Yes, actually. The buff is timed so that the duration will read 3 on the player's next turn, but it looks like in that picture you're acting ~0.16 turns after the guard instead of 1, so it would read 3.84

**Comment by LeahLuong** [comment]
This still doesn't explain the shorter pull. It would've taken the guard 2 ticks to move a tile south: 1 paused while questioning, 1 to take the step. The crippled timer should have been @ 1.84 in that case by your reasoning if it started @ 3.84.

In the 2nd set of images, I was pulled from more than 2 tiles away but the behavior seemed typical (AFAIK, guards never pull @ 2 or less distance). I don't think the game usually checks intermediary tile presses when being pulled & this is what makes this case puzzling.

**Comment by Pr0methean** [comment]
Guards do pull at distance 2.

**Comment by LeahLuong** [comment]
@Pr0methean Oop, I think I'm confusing that behavior w/ succubus' teleport. Pretty sure _**they**_ simply walk when you're close enough. Still, kinda peripheral to the discussion here although I appreciate the correction.
