### ISSUE TITLE
Prismatic Vulnerability

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1155]
It seems prismatic guards are dmg'd by scroll of retribution where other allies are not. Others like the sad ghost or mirror images will receive the blindness & weakened debuffs but no dmg. Is this intentional?? If not, it may be worthwhile to check if prismatic guards are prone to other friendly fire effects like chaining lightning or blast wave explosions; I noticed allies tend to be immune to dmg from those.

I'll try to post here again if & when I get a chance to check the other cases.

**Comment by 00-Evan** [comment]
Allies actually aren't immune to retribution at all, it hits everything in your FOV. For mirror images in particular, because they have 1 health, the damage dealt might be getting rounded down to 0 if it is less than 0.5.
