### ISSUE TITLE
Curse of Anti-Entropy Bug (v1.4.3)

### ISSUE THREAD

**Issue by CalebAlex-Ander** [00-Evan/shattered-pixel-dungeon#1156]
Received a leather armor with a curse of anti-entropy; removed the curse using a scroll of upgrade (got the prompt that the SoU removed the curse). The armor was now highlighted as blue (uncursed) yet the description still shows a curse of anti-entropy and functionally still has the curse. Playing as a huntress, vanilla run (no seeds, challenges, dailies, etc.) **v1.4.3**

**Comment by 00-Evan** [comment]
Curses can be 'weakened' by scrolls of upgrade before being entirely removed. In those cases the curse effect stays on the item, but its possible to unequip it. The text changes to reflect this:
"The scroll of upgrade weakens the curse on your item."
"Despite the curse, you are able to unequip this armor."

**Comment by LeahLuong** [comment]
This is a dupe of #750. It should be noted that upgrades _**do**_ have a 1/3 chance to eradicate curses but, failing that, they weaken instead.

**Comment by CalebAlex-Ander** [comment]
Thanks for the response. From a UI perspective, it's not entirely clear, especially considering cursed items are shown with a red background instead of blue. Thanks and good work as always!
