### ISSUE TITLE
EQ Deletion

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1157]
This is related to #477.

I believe attempting to sell an outfitted Dried Rose gives a warning prompt. No such warning prompt is given when using scroll of transmutation on a Dried Rose. This can result in the permanent loss of equipment.

**Comment by Pr0methean** [comment]
IIRC it's also possible to destroy the warrior's seal by giving the affixed armor to the Troll Blacksmith.

**Comment by LeahLuong** [comment]
@00-Evan There's a "no take-backsies" rule when using un-ID'd scrolls. Don't forget to consider that case when transmuting the Dried Rose that way! Should heeding a possible warning prompt result in the loss of the scroll to no effect??

@Pr0methean I smith the seal almost every time I play warrior. I have no recollection of ever losing the seal that way.

**Comment by 00-Evan** [comment]
Plan is to either not allow the scroll to be used on the item at all, or have it drop the equipment after transmute.

**Comment by Pr0methean** [comment]
@LeahLuong I think it only happens if the affixed armor is the same or lower level than the other smithed one. I don't remember the exact conditions though.

**Comment by LeahLuong** [comment]
@Pr0methean That sounds like it could happen. I've noticed a preference for the left slot if the armors are equal. If you test & confirm loss can happen, you should open a separate issue.

**Comment by Pr0methean** [comment]
You're probably in a much better position to do that than I am - so far, I've only obtained the Amulet once, and I often don't even reach Tengu.

**Comment by LeahLuong** [comment]
@Pr0methean I was able to test the seal & it's fine. I put scale armor of flow +2 in the left slot & scale armor of camouflage w/ an upgraded seal (so, +1) in the right. Troll gave me scale armor of flow +3 & the upgraded seal dropped @ my feet. While testing, I realized this situation will practically never come up; you'll always get a better result smithing a +3 & +0 than if you did a +2 & +1. Players will tend to move the seal to the better armor or already be using it anyway.

**Comment by Pr0methean** [comment]
Okay, I'll report if this ever happens again, or Evan can add a telemetry event for "Warrior has no seal and there isn't one on the ground on any level".

**Comment by Wolfman1234567890** [comment]
I got 2 dried rose in SomPD . But I think you can get 2 or more also in SPD.

**Comment by 00-Evan** [comment]
fixed in commit dd5b7592f946ea0ec570409ecbe697a90cdfa8d7
