### ISSUE TITLE
Sad Sad Ghost

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1158]
![Screenshot_20221111-200703](https://user-images.githubusercontent.com/91638992/201495938-8ea10855-d3f5-4b53-978d-5ef22edbfd97.png)

You'd be sad too if you had none of the benefits of a circulatory system but were still prone to being poisoned or bled!

Since the ghost is an inorganic, ethereal being, shouldn't she be immune to those status effects?? She's already unaffected by toxic & corrosive gases. I did notice she takes dmg from fireblasts but seems immune to standing fires. Chaining lightning originating from the hero seems to do her no dmg. I need to do more testing w/ scrolls of retribution & psionic blast but I think the former don't harm her.

**Comment by 00-Evan** [comment]
The ghost is mainly immune to some AOE effects so that it doesn't easily kill itself inside a potion you through, although some of that is leftover from before you could control the ghost's position.

Generally 'poison' and 'bleed' are a bit generic, and this is so those effects work on a majority of characters in the game. If poison and bleed didn't work on undead or non-humanoid characters then they would be completely useless in the metropolis. This is why poison/bleed are only blocked against enemies that are totally metallic, like golems. Loosely organic characters like ghosts or elementals are considered to be organic.

Allies are also immune to chain lightning damage as of 0.8.1

**Comment by Pr0methean** [comment]
I'd take that as a sign to add more living mobs and make the undead ones less common.

**Comment by LeahLuong** [comment]
@00-Evan That logic seems a bit flimsy: "Sad Ghost vulnerabilities are a holdover from an earlier time in the game's development. Most enemies need to have these vulnerabilities to keep these effects relevant. Therefore, the status quo should be maintained."

Also, I'm pretty sure elementals don't bleed. I'll test it when I get the chance but I haven't thrown a tomahawk @ an elemental for a long time & I'm pretty sure there's a reason I stopped since that's 1 of my fav missile weapons, next to bolas.

Furthermore, there are arguments for why corporeal undead can make use of blood or are vulnerable to poison. It's possible to exsanguinate vampires (though they don't currently exist IG) & this is purportedly quite unhealthy for them. The lore makes no mention of any blood rituals & I assumed most of the dwarves kept most of their blood before being taken over. There are many different types of poison &, while nerve poisons are likely ineffective against corporeal undead, necrotic/acidic poisons prob are. That said, ghouls don't seem to be resistant to earthroot when it's injected into them.

The only reason I can think of for incorporeal undead to be afflicted by bleeding or poison is psychosomatic; they think those effects are actually taking place & so the placebo effect takes over.

**Comment by 00-Evan** [comment]
You're misreading my message, most of the ghost's **immunities** are a holdover, not the vulnerabilities. If anything I would prefer to remove some of those immunities now that the ghost can be directed out of gasses.

Elementals are in fact vulnerable to bleeding.

Also, if we want to argue that physical effects should not harm incorporeal undead, then they should be immune to all physical damage. At the end of the day my preference to to have fewer character invulnerabilities.

**Comment by LeahLuong** [comment]
@00-Evan I apologize for the misunderstanding. It prob looks like I was trying to strawman you but that wasn't my intent. I'll try to be more careful in the future when reading your comments.

As for elementals, I guess I'll have to chalk that 1 up to the Mandela effect. Good to know I've reality-hopped to the space-timeline where elementals bleed. I searched the patch notes & couldn't find anything where this interaction was ever changed in the past but I could've sworn they didn't used to bleed.

In my imagination, there's no conflict w/ the ghost being invulnerable to bleed/poison effects but vulnerable to physical dmg. She's obviously got _**some**_ materiality or she couldn't wield her weapon & armor. When sustaining attacks, she begins to lose her ability to interact w/ the physical plane, represented by her HP pool. Lacking a circulatory system, she has no blood to bleed or carry toxins. She also lacks those systems which venoms/poisons can chemically interact w/. Makes perfect sense to me.
