### ISSUE TITLE
Magic Immunity Immunity

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1159]
![Screenshot_20221112-174502](https://user-images.githubusercontent.com/91638992/201545636-b1f86d02-2401-4c57-89f8-79781b87cf71.png)

There are several effects which seemingly escape the purview of the "immune to magic" status. Here's a slew of potion effects:

![Screenshot_20221112-174452](https://user-images.githubusercontent.com/91638992/201545744-cbae9c9a-a0e9-4271-b6f7-62cc847a83b1.png)

![Screenshot_20221112-174603](https://user-images.githubusercontent.com/91638992/201545790-350377ac-661d-4d75-aca2-056be15002a0.png)

![Screenshot_20221112-174647](https://user-images.githubusercontent.com/91638992/201545813-e0aebdf0-41a1-40ee-af55-318ba1c58f34.png)

![Screenshot_20221112-174659](https://user-images.githubusercontent.com/91638992/201545918-fc804ce2-42ce-4b8b-8d59-f0b16b2b8972.png)

![Screenshot_20221112-174735](https://user-images.githubusercontent.com/91638992/201545939-753053ab-7dd6-4254-9232-b05b51393f49.png)

![Screenshot_20221112-174818](https://user-images.githubusercontent.com/91638992/201545949-0a4f9a7e-2bf1-4055-b8b5-c6544709abd6.png)

1 could argue some of these effects are mundane chemistry augmenting the hero's own but that breaks down in the cases of arcane armor & levitation where the descriptions specifically call them out as magical. Potions are derived from magical seeds which are able to spring to full maturity in a few seconds from a stone floor so it's likelier that all potions are magical in nature.

Here's a self-targeted runestone effect:

![Screenshot_20221112-174944](https://user-images.githubusercontent.com/91638992/201546512-2a14b121-319b-41b3-9b6d-d59d74759f59.png)

I threw stone of aggression @ myself. Note the description's magical call-out. I imagine there are other runestone effects which override magic immunity but my scroll's duration ran out & it seems like I was able to collect enough pertinent examples to make a case here.

Is the effect of the Amulet of Rodney magical in nature??

The main reason I decided to open this thread was the discovery that Backup Battery is usable while immune to magic. 1 is prohibited from zapping wands while immune but 1 can still self-target & expend magical wand charges to produce a magical force field using a magical talent. This gets into some murky territory. Are there other talents, magical in nature, which should be prohibited while immune to magic?? Are all talents gained through Tengu's mask & DK's crown magical in nature??

On a side note, 1 is seemingly able to use Backup Battery w/ cursed wands where such use should prob inflict cursed wand effects, or @ least cause the vulnerability debuff for the user w/out any beneficial effect.

**Comment by 00-Evan** [comment]
The main intention is for magical immune to both make the hero impervious to magic harm while also limiting their usable options (no scrolls, wands, rings, artifacts, etc.) I am not interesting in building and maintaining a huge list of every buff effect that could be considered magical, and then expecting the player to remember it.

Broad categories are more reasonable however, I'll look into wand-use edge cases (like backup barrier) and runestone use as possible things to limit.

**Comment by LeahLuong** [comment]
@00-Evan No need for burdensome upkeep if you rule that potions, as a "usable option," are magical in nature & ineffective when consumed while immune to magic. Or, @ least overridden while anti-magic is in effect; they could proc following the effect or have their effect reduced by the percentage of overlap.

The description for magic immunity implies its effect is centered on the hero. Runestones' magic seem centered in the rocks themselves, not the thrower. I think you should still be able to throw them for magical effect but not have those effects rebound on the hero (during anti-magic). The same for spellstones. Other magic items either use the hero as a focus or are projected from the hero while in contact so it makes sense for them to be disrupted.
