### ISSUE TITLE
Unblessed Ankh should suggest Ring of Force when you have no item equipped

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1161]
The unblessed Ankh autosuggests the two items you want to keep. This is usually your equipped weapon and your armor. When you have a Ring of Force, you often use no weapon (or in very rare cases a ranged weapon like Whip or Crossbow). If you have no equipped weapon, but an equipped identified Ring of Force, the item selection dialog should suggest the equipped identified Ring of Force with the highest level instead of an empty slot for the weapon. (There may be also other improvements, like proposing the Rogueʼs Cloak or the Huntressʼ Bow instead of the equipped armor in the Faith is my Armor challenge, however this is more situational, because some glyphs like Camouflage are still pretty good at higher upgrade levels.)

**Comment by LeahLuong** [comment]
I've almost lost a run to this situation & it really sucks. I was no match for the blazing bat that nearly killed me twice until I got my force back. Sad Ghost was carrying my backup weapon so suggesting carrying 1 of those is fruitless if you can't access it for lack of the Dried Rose.
