### ISSUE TITLE
A maths-related error in HornOfPlenty

### ISSUE THREAD

**Issue by 1015561267** [00-Evan/shattered-pixel-dungeon#1163]
\<sections discussing code removed>

I think you intend to make ArtifactRecharge buff to recharge HornOfPlenty one charge every four turns.However you messed absolute value up with relative proportion,then if you have some little partical recharge(like 40)then you can exchange them into real charge in 1:1 rate every turn until it's full,other than 90:1.It's obviously overpowered by BattleMage as it can gain some small partical recharge,trigger ArtifactRecharge buff with talent,then convert them with absurd exchange rate and eat like hell.

\<sections discussing code removed>

**Comment by 00-Evan** [comment]
Thanks for the bug report, but I don't accept code contributions. After skimming over your message I have removed the sections that were discussing code, and have left the part that describes the issue itself.

**Comment by 00-Evan** [comment]
fixed in commit e2e3d11ac9776d49a837de04aa606dece947b71c
