### ISSUE TITLE
Zooming on the Steam version is often unresponsive

### ISSUE THREAD

**Issue by akuza55555** [00-Evan/shattered-pixel-dungeon#1164]
When zooming in or out the game often skips some scrollwheel inputs. Just a minor inconvenience.

Additionally, it would be nice to have a toggleable zoom button on the screen for Windows tablets, as the gesture required for scrolling on my Surface Go 2 is extremely janky in game.

**Comment by akuza55555** [comment]
Just learned that it might be intended that zooming only happens every other input. If that's the case then feel free to close this issue.

**Comment by 00-Evan** [comment]
The reason for this is that the game needs to visually zoom by an integer multiple. Every tick of the scroll wheel increases/decreases the true camera zoom by about 10%, but at lower zoom amounts that means it can take a few scroll wheel moves before the difference becomes visible. e.g. at 1x the 'true zoom' needs to be increased to 1.5 over 5 wheel increments before it gets rounded up to 2x visually. But at a zoom of 5x, a single mouse move would bring it up to 5.5 which rounds to 6x.

The alternative to this, having every wheel move translate to a zoom change, would mean that the camera would zoom in/out way too rapidly at low zoom levels.
