### ISSUE TITLE
Maybe need optimization

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1165]
When I ascension, if I blocked the door with ripper in magical sleep and stayed on the 24th floor long enough, the spawner will summon rippers quickly
![Screenshot_20221117_072943_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/202321920-0b4fb95e-332b-41f2-addb-e231f57cd059.jpg)
As shown in the figure, five rippers were summoned in only six rounds

**Comment by Lyx0527** [comment]
Blocked spawner's room with a sleeping ripper

**Comment by Lyx0527** [comment]
and stay on the 24th floor long enough before ascension

**Comment by Wolfman1234567890** [comment]
Why did not kill the spawner before obtaining the amulet.

**Comment by Lyx0527** [comment]
For the Doom slayer badge and gain more boss score. For achievement and boss score. The game developer encouraged us to do this, isn't it?

**Comment by Lyx0527** [comment]
> Why did not kill the spawner before obtaining the amulet.

For the Doom Slayer bandge and more boss score. Game developers encourage us to challenge this, isn't it?

**Comment by 00-Evan** [comment]
fixed in commit ff84cfd220b529ff05694a38d2c54dbce42c643c
