### ISSUE TITLE
[Idea] Add new Challenge: All mimics

### ISSUE THREAD

**Issue by pflanzenandi** [00-Evan/shattered-pixel-dungeon#1168]
Add a new challenge in which all treasure chests are actual mimics (no visual difference).

- Player has to trigger test each chest most definitely in early to mid game to avoid getting crushed. Maybe give mimics for this challenge even more HP.

**Comment by 00-Evan** [comment]
I do plan on adding new challenges in the future, as hostile champions and badder bosses were both received very well. I'd rather not add a challenge that's so specific to one enemy type though. Making every chest a mimic also somewhat defeats the purpose of mimics, as the player would be always expecting them.
