### ISSUE TITLE
fdroid version still out of date

### ISSUE THREAD

**Issue by woutershep** [00-Evan/shattered-pixel-dungeon#117]
I know about the .so problems but those have been fixed right? Will we fdroid users have to wait till a c release with those fixes or something?

**Comment by 00-Evan** [comment]
See Here: https://gitlab.com/fdroid/fdroiddata/issues/519
and here:  https://gitlab.com/fdroid/fdroiddata/merge_requests/1703

If you have any suggestions to help with these issues i'd welcome it, but right now I'm waiting until a maintainer has the free time to help out.

**Comment by 00-Evan** [comment]
Decided to give up on building the native libs for now, will try again next update and will test using my own fork of f-droid's build server.

F-droid version should update to 0.4.2b shortly after this merge request is accepted: https://gitlab.com/fdroid/fdroiddata/merge_requests/1741

**Comment by 00-Evan** [comment]
F-Droid is now on v0.4.2b, sorry for the holdup.
