### ISSUE TITLE
They may be bugs. And some suggestions

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1170]
1. When hero's armor with +1 seal is transfered to armor B, the armor level of the new hero's armor is equal to the armor B , and 1 level will be reduced if the seal is detached. 
![Screenshot_20221118_133628_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/202651689-5f834530-26e5-4d18-ac40-fa67117f8746.jpg)

2. Ring of Elements will not reduce the splash damage of shock elemental or animated state with shocking weapon，nor will it reduce the sparks damage of exposed wiring at 15th floor.
3. Shock element and shocking enchantment will deal damage to all nearby enemies, but the shopkeeper（and other NPCs） is not anyone's enemy. He will run away due to these splash damage.
4. Barkskin cannot resist the explosion of bombs or double resist explosion of bones.  It can't resist prick damage of chalice, too.    It seems that it appeared in the v0.9.3. 
5. After DM300 is generated, and before it's health bar appears, attacked it by thrown weapon outside its field of vision. DM300 will only approach hero without using skills. 
6. A thrown weapon with the projecting enchantment cannot be thrown on the closed door or spider web after through the wall. 
7. 1.4.3, if the rouge returns to the main menu immediately after using the cloak to remove his cloaked,  using the cloak will not consume the charge after returning to the game in the first turn. 
8. Greaves of nature cannot target spiders in spider webs.
9. Tengu's shocker occasionally shows it will shocks every cells around it，but actually it only shocks four cells. 
![Screenshot_20221117_162158_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/202652025-b511998a-f154-4ff1-bacb-b522717f15d6.jpg)

10. The splash damage of the shock elemental will damage its allies. 
11. If there are multiple unlit bombs in one cell, they will only cause damage once when they are detonated by the flame. 

Next, here are some suggestions and strange things

1. The chalice. Armor and damage reduction（such as tenacity, challange, blessed ankh) are very strange to resist the damage caused by blood loss. And it is too difficult for beginners to calculate the damage of the chalice. It is too frustrating to die of sacrifice. It is also incredible an adventurer prick themslevs to die .It's more reasonable to reserve 1  HP for heroes after prick, and increase the upgrading advance of the chalice subsection. And increase the required HP for each level to balance.
2. When the evil eye dies, the second dewdrop it drops may trigger the trap around the evil eye. Spectral necromancer, caustic slime and DM201 have the same problem.
3. A unit that cannot move will cause the item to trigger a trap when it pushes the item apart. For example, throwing a healing dart at a sentry.
4. Throwing rune stones、potions at enemies over the chasm will fall into the chasm instead of taking effect, but the improvised projectiles won't.
5. It's strange that paralyzed bats and frozen bats can't fall into chasm. Heros can also dodge during paralyzed and frozen.
6. Enemy in amok ignores the chasm as it moves towards its target.
7. Crazy thieves may steal ungraded armor with broken seal from hero's package, and cause warrior to lose his seal .
8. When hero cast aqua blast on themself, they will be push to a trap or chasm, and the hero on fire cannot extinguish the fire in time. Maybe it is reasonable to cast on hero without push.
9. Sometimes the gas sprayed by DM300 will hurt the player immediately. If reset the round counting of poison gas every time when DM300 spray the poison gas, it can be avoid, I think. Similarly, reset the turn count of fire, poison gas, and caustic gas when hero steps on a burning trap, a toxic gas trap,throw a toxic gas potion or casts a spell with corrosion wand, so there will be no situations where stepping on the trap with a haste ring will not be affected、 the caustic gas bolt cannot damage the target.
10. If hero's movement speed is less than 1, stepping on pitfall trap will directly fall.
11. If an enemy is killed by a pitfall trap, its loot and items generated from wealth ring will not fall with it.
12. When hero dodge attacks, automatic movement should be interrupted.
When hero attacked by enemies out of his vision, the automatic pickup of items should be interrupted. 
13. It is too difficult to notice the traps under the objects close to the side wall below.
14. Spiderweb can prevent gas diffusion.
15. The gas diffusion animation is too slow. When gas appears in the field of vision, automatic movement will be stopped, which is more appropriate. 
16. When all fists are dead, Yog can be hit without take damage until he said "your hope is an illusion". It is more reasonable to display "invulnerable".
17. Losing Boss score due to being paralyzed by falling rocks is unreasonable. It is often unavoidable in narrow spaces. When a hero is paralyzed, the score will be deducted for the attack, which is more reasonable,I think. 
The hero is shot by Yog's laser while he stops himself with hourglass, Boss score will be deducted. 
18. The sound effect of parried often sounds like dodged. 
19. When the hero freezes time, he cannot surprise attacks the piranha that could not be seen behind the door. 
20. "Doomed is permanent, its effects only end in death. "
and potion of cleansing.
21. Blazing champion flies are terrible. Heroes have to fight for a long time in a fire filled environment. Perhaps it is more appropriate that the heroes on the water will not be ignited by blazing champions, just like fight against fire elemental. 
22. I can't understand why the wand of transfusion can heal charmed enemies. What is its meaning? 
23. When the Ring of Arcana amplification polarized curse, it is more reasonable to increase its damage and the probability of causing 0 damage at the same time. After all, it's a curse. To blocking enchantment, after the trigger probability exceeds 1, it is more reasonable to increase the number of shields. 
24. When the floor is locked and passive regeneration stops, the warrior's seal can provied shielding.

**Comment by 00-Evan** [comment]
You've mentioned a lot of things here, so my reply to each will be brief:

1. It should not be possible to find negatively levelled equipment, how did you get that plate armor in the first place?
2. I'll look into this
3. this is working correctly
4. I'll look into this
5. this is working correctly
6. this is already fixed in development
7. I'll look into this
8. I'll look into this
9. I'm aware of this one but have not been able to reproduce it
10. this is working correctly
11. this is working correctly

Please further explain point number 1. I will look into fixing 2,4,7, and 8.

I'm afraid if you want to make lots of suggestions it is better to email me. This place is primarily meant for reporting technical issues with the game. I have read your suggestions and most of them describe game mechanics that are intended to work that way.

**Comment by 00-Evan** [comment]
Point 2 is now fixed in development, as one extra note, it seems that ring of elements does in fact already work against pylon damage.

**Comment by Lyx0527** [comment]
> You've mentioned a lot of things here, so my reply to each will be brief:
> 
> 1. It should not be possible to find negatively levelled equipment, how did you get that plate armor in the first place?
> 2. I'll look into this
> 3. this is working correctly
> 4. I'll look into this
> 5. this is working correctly
> 6. this is already fixed in development
> 7. I'll look into this
> 8. I'll look into this
> 9. I'm aware of this one but have not been able to reproduce it
> 10. this is working correctly
> 11. this is working correctly
> 
> Please further explain point number 1. I will look into fixing 2,4,7, and 8.
> 
> I'm afraid if you want to make lots of suggestions it is better to email me. This place is primarily meant for reporting technical issues with the game. I have read your suggestions and most of them describe game mechanics that are intended to work that way.

It seems that because of my poor English, you don't understand what I mean. 
1 hero's armor with +1 seal, transfer, +0 armor, gain +0 hero's armor, detach, -1hero's armor. 
3&10. "dealing extra damage to all nearby enemies"
"they will arc electricity to nearby enemies"
 how about modifying these descriptions if friendly fire and accidental injury are normal,
5  Until the first power pylon is activated, the sniper's attack will not receive any counter attack from DM300. I'm sure it still works in v1.4.3. If this is not a bug, I will continue to use it.
![Screenshot_20221119_074754_bdcb114926dd6276f40884c10794134b](https://user-images.githubusercontent.com/118305192/202826021-eb93f810-456b-45f9-a9b8-5a508a021d56.jpg)

11  In one cell. If the fuse is not ignited, it is reasonable that the bomb will not explode. Why does each fuse ignited bomb will cause damage?

I know it's annoying to give too much advice, but please pay attention to the suggestions  7.14.24, they may also be bugs. 12.13. also often leads to bad game experience
About 12, the vertigo hero always auto move at random may also should be repaired 
9. It often makes players counterintuitive and incomprehensible.

**Comment by 00-Evan** [comment]
I'll look into number 1 then, thanks for the explanation.

I'm afraid that I have a limited amount of time to listen and reply to messages, especially when you consider that I receive many messages each day and try to reply to all of them. If you send me 30+ things at once I will not be able to consider each one, or I would have to ignore messages from everyone else for at least one day, maybe two.

**Comment by 00-Evan** [comment]
fixed over several commits in v2.0.0
