### ISSUE TITLE
Potions freezing log/chat text starts with a lowercase letter

### ISSUE THREAD

**Issue by akuza55555** [00-Evan/shattered-pixel-dungeon#1172]
![image](https://user-images.githubusercontent.com/77411780/202930881-d7992256-47ba-454a-ae65-4f1c6b01d0f8.png)

Not sure if this affects all potions, but it happened with both a potion of frost and a potion of paralytic gas. I was frozen via a cursed wand effect.

**Comment by akuza55555** [comment]
Steam version.

**Comment by 00-Evan** [comment]
fixed in commit 0dd384daeda2eacb5f5dfd4dfbcb97d7116791d2
