### ISSUE TITLE
Hunger/health/wand-charge stopped changing

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#1173]
I was fighting Tengu, in between the first and second arenas, and resting to get health and wand charge back. At some point while resting, everything time-dependent seemed to stop changing: health stopped going up, hunger stopped increasing, wand charge stopped increasing. I tried resting, moving around, and searching, and nothing seemed to change any of those things.

I recorded a video demonstrating; will attach if I can.

https://user-images.githubusercontent.com/162737/202960938-3e926b78-a082-4281-b856-576e6891d799.mp4

**Comment by 00-Evan** [comment]
This is intended, read the description of the locked floor buff next time you're fighting a boss.
