### ISSUE TITLE
Bugs of tipped darts

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1174]
Tipped darts with 2 uses left, throw it on to the ground, throw the same kind of dart into an enemy, pick up the dart on the ground, 
①throw it into the same enemy, kill it, and lose a dart; 
②throw it into another enemy, kill them, pick up all darts, and lose a dart. 
![Screenshot_20221122_103132_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/203214048-b9b549b9-d5ff-4e0e-a8ae-391ae55a234d.jpg)

Tipped darts can produce more liquid metal than darts.

**Comment by Lyx0527** [comment]
It's strange that throwing stones can produce liquid metal.

**Comment by spixi** [comment]
> It's strange that throwing stones can produce liquid metal.

The Throwing Stone also misses the fact that is non-sticky its description (similar to the Throwing Club and the Throwing Hammer). But that is the only reason why it is not strictly worse than the Throwing Knife or the Throwing Spike.
