### ISSUE TITLE
Rankings enum design

### ISSUE THREAD

**Issue by nicholas-carlotti** [00-Evan/shattered-pixel-dungeon#1175]
Hi, I was reviewing some parts of the code as an exercise and i stumbled upon the Rankings enumerator. It looks like the intent here was to realize a singleton pattern, which was done by using a single enumerator constant to access the instance.
Could this enum be changed into a class that strictly implements the pattern?

**Comment by 00-Evan** [comment]
Sorry but I don't accept code contributions. There are several idiosyncrasies in Shattered's code, some of which are my doing and some come from the original Pixel Dungeon. Generally as long as things are working reasonably well I'm not interested in changing the code.
