### ISSUE TITLE
Quirks

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1176]
Embers on the floor of the spanwer's room cannot be seen. 
After the garden is burned, the embers will become grass automatically, but the grass cannot be lit until the player enters the game again. 

The deathgaze will not destroy the bookshelf. 
Evil eyes can resist disintegration beams, but cannot resist deathgaze and disintegration traps. 
When Yog's minions are just summoned, they will not trample emberfungi beside Yog.

**Comment by 00-Evan** [comment]
fixed in commit f473f5144fa1ad9a316b601b0d7bc82d7a32bc6c
