### ISSUE TITLE
Goo explosion error. Explosion persists 

### ISSUE THREAD

**Issue by TrueFMartin** [00-Evan/shattered-pixel-dungeon#1177]
Fighting Goo with an earth elemental guardian. Door closed with goo and elemental on other side, out of visibility. Goo explosion remained visible for many turns until goo became visible again.  Attached video. [Reddit link to goo video ](https://www.reddit.com/r/PixelDungeon/comments/z3rye5/goo_bug_report_video_for_github_error_reporting/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)

**Comment by 00-Evan** [comment]
fixed in commit 406dce63ac50c6a4cc9fdf57e712f6a81ae6952e
