### ISSUE TITLE
Feature Request: Journal Progress export/import

### ISSUE THREAD

**Issue by Mia-Rain** [00-Evan/shattered-pixel-dungeon#1178]
My main idea for this is that the progress in ones Journal could be exported between platforms, such that one would not have to do the tutorial again, and could hero unlock progress, and discovery of items progress. My idea isn't save export/import which would cause a huge problem with cheating but just that one can export/import data to not need to the tutorial again, as personally I've done the tutorial at least 20 times between devices.
This is actually quite easy to do from a PC but for Android you can't manually access the data folder unless you're rooted and I can't imagine it's easier for iOS.

**Comment by 00-Evan** [comment]
Unfortunately there isn't really a way to have any sort of export/import feature that doesn't require a bunch of permissions on mobile platforms. I don't want Shattered to have access to external file read/write, as that opens it up to a bunch of scrutiny from players and Google/Apple.

It's worth noting that the Android version supports Android's backup and restore function, as well as cloud sync via Google Play Games. The iOS version should support iPhone's built-in backup and restore as well (and I may integrate iCloud in the future). The Steam version also support Steam Cloud Saves.
