### ISSUE TITLE
Combo Counter Accuracy

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1180]
The combo counter doesn't seem to display partial turns until combo is lost.

![Screenshot_20221125-134642](https://user-images.githubusercontent.com/91638992/204071380-0513b903-b73b-4fac-9d6d-eee30395c5a7.png)

You can see the turn clock is only partially filled but the turns until combo is lost is a whole number. This is either because the counter is actually counting attacks or it's rounding partial numbers. I believe it's the latter case but the former would warrant changes to the description box or something. The game displays partial turns in pretty much every other case so why not here??

**Comment by 00-Evan** [comment]
Some buffs act every turn, others wait until a specific time before expiring. this results in this mild discrepancy in time display, which I'm fine with.
