### ISSUE TITLE
Antimagic Vulnerability

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1181]
In the process of slaying a sewer crab, my shocking weapon proc'd a couple of times & dmg'd the nearby antimagic champ. Shouldn't those be immune to this magical effect??

![Screenshot_20221125-155726](https://user-images.githubusercontent.com/91638992/204071678-8383ad1a-7166-4629-a8a7-bac893492290.png)

**Comment by 00-Evan** [comment]
Already covered by point 2 in #1170
