### ISSUE TITLE
Warrior's Broken Seal stops transferring any upgrades or runes after using Runic Transference +2

### ISSUE THREAD

**Issue by 4ndyD** [00-Evan/shattered-pixel-dungeon#1183]
Steps to reproduce:
Have some armour with a few upgrades and a rune on it and the Warrior's broken seal affixed.
Learn the Tier 2 talent Runic Transference to level 2.
Detach the broken seal from the armour.
Put it on another set of armour or put it back on the original one.
Detach the broken seal again.
![Screenshot_20221124-081211_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/1424385/204150849-423d4ee2-6969-4cd4-b578-69026ee0c6bf.png)
![Screenshot_20221124-081232_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/1424385/204150852-71ef7fdc-4a5a-4b22-bacf-c3302b1aad17.png)
The broken seal's function of either transferring upgrades or runes entirely stops working / is broken.
Possible intermediate steps to fiddle with that might have triggered this: either upgrade a piece of armour while a rune is removed from it before putting it back, or try using Runic Transference at L1 before using it at L2.

If this is an intended limitation of the Runic Transference upgrade, then this should be communicated to the player, because it can severely hamper being able to acquire some good late-game armour (I rolled a rare magic resistance rune that I now cannot move onto higher-tier armour, and my original broken seal's carried upgrade is also stranded on the same suit of mail).
Occurred in at least v1.3 and was not fixed by updating to v1.4.3

**Comment by Lyx0527** [comment]
The seal cannot rob glyph and upgrades from other armor. It is just to let you use the first upgrade scroll without hesitation

**Comment by 4ndyD** [comment]
You could be on to something there. I remember taking the seal off while upgrading some armour to test whether that would work to preserve its glyph.
I was convinced that I had put an upgrade on the seal early in the run and that it now isn't picking it up anymore after learning the talent, but on further trying to upgrade the scale armour with it on, it is picking up and transferring a new one now, so I could be wrong.
I'll close this for now, assuming I won't be able to reproduce it on the next run.

**Comment by LeahLuong** [comment]
Pretty sure this is a dupe of #1077. Would be nice if the seal were "stickier" but I doubt Evan is going to change it. The seal glows the color of the the glyph it's carrying if it has 1.
