### ISSUE TITLE
DM Silliness

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1185]
![Screenshot_20221127-124216](https://user-images.githubusercontent.com/91638992/204177181-d20a533f-38c7-4e49-8123-2ce10db6f0c7.png)

DM-300 launched its gas attack directly onto me while I was invisible. It also seems capable of using that attack to make shots the hero isn't ordinarily able to, both because of visibility & intervening obstacles. For example, when it's positioned @ a corner, it can shoot far past that corner where, if the hero were in the same position, the corner would both obstruct vision & block the shot @ the corner.

I've also seen DM-201's make likewise impossible shots such as firing thru closed doors & walls when provoked. You'd think dropping a corrosive cloud next to them & running for cover would be a viable strat but you just end up in a world of hurt. So much for giving them a taste of their own medicine.

**Comment by Lyx0527** [comment]
As a Boss, DM300 is too weak. Only various incomprehensible bugs can give me a sense of crisis：)

**Comment by 00-Evan** [comment]
The DM's are capable of aiming shots more effectively than other enemies, this is to make it harder for the player to use corners and hallways to get free attacks while they can't retaliate with gas. Generally if they can see you then they can retaliate.

As for invisibility, enemies will still be hunting their targets for a brief time after they become invisible, which in the case of DM-300 does mean it is still able to use abilities at your approximate location.

**Comment by LeahLuong** [comment]
![Screenshot_20221221-223218](https://user-images.githubusercontent.com/91638992/209212718-9a4f57ee-cedf-4a42-8ed1-976e7b99ad8f.png)

@00-Evan DM-200 was orthogonally lined up w/ the hero (directly south) & fired its gas thru the web. Players are prohibited from doing this as the web normally intercepts shots. Blobs over the webs were destroyed in the following turn but I still had to flee from the expanding gas @ the hero's position.

I'll try to post again when I have a pic of a DM-201 firing directly thru a closed door or wall.
