### ISSUE TITLE
Tengu and glyph of repulsion

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1186]
In the second stage, tengu is often pushed in the wrong direction by glyph of repulsion

https://user-images.githubusercontent.com/118305192/204191531-451abd81-8393-4142-a950-177f3a1f446e.mp4

**Comment by 00-Evan** [comment]
I've decided to adjust repulsion to only trigger on adjacent enemies, so this will be incidentally fixed by that

**Comment by 00-Evan** [comment]
fixed in commit e5026808513b0879c503f33153f2ec7ea0a9b0e3
