### ISSUE TITLE
Do Ring of Force unarmed damage stack with other rings of the same type?

### ISSUE THREAD

**Issue by RealBamboolord** [00-Evan/shattered-pixel-dungeon#1187]
Do Ring of Force unarmed damage stack with other rings of the same type?
Im curious because I want to know if its worth using two of the ring at the same time

**Comment by 00-Evan** [comment]
This isn't really the place to ask gameplay questions, you're better off emailing me.

All rings stack with each other, two rings are equivalent to one ring with their levels combined and an extra +1 added on.
