### ISSUE TITLE
Hold Fast can be preserved via time freezee

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1189]
1 can move during a time freeze & the warrior's Hold Fast bonus is preserved. This contradicts the talent's description. If this is intended behavior, I think the bonus should be preserved when relocated via golem yoink or other means.

**Comment by 00-Evan** [comment]
This is because the buff's expiry triggers when it acts. The same happens with sungrass and earthroot buffs. I am fine with allowing this quirk.

**Comment by LeahLuong** [comment]
I think I understand what you're saying but the bonus persists after the time freeze ends. When a golem yoinks you, Hold Fast lasts a turn & expires. I believe throwing a blink stone, chaining away, teleporting, or being pushed ends the buff immediately. With time freeze, you can vacate the Hold Fast tile entirely & maintain the buff indefinitely. These seem like inconsistent applications of the logic for when the expiry trigger happens.

**Comment by 00-Evan** [comment]
I can get hold fast to travel with you if you activate it while time frozen. I've also thought of a couple of tweaks that would make these buffs less susceptible to this sort of logic, will make those adjustments.

**Comment by 00-Evan** [comment]
fixed in commit 0a4b8949fa5ce6b58e941c9dfc9901bee3a4ce5c
