### ISSUE TITLE
Important objects put on explosive traps

### ISSUE THREAD

**Issue by Ezelty** [00-Evan/shattered-pixel-dungeon#119]
In one game I've played, a potion of levitation was put on an explosive trap. I couldn't step on the trap or throw an object on it without destroying the potion. Without this potion, I was unable to take an important object which would have helped me a lot in the game.
In order to prevent such situations, could you make it impossible that strategical object (potions, keys, artefacts, anything important that would be destroyed by the trap) are put on explosive traps? (or freezing traps for the potions, it destroys them too)
Thank you!

**Comment by 00-Evan** [comment]
This was logic that I probably should have updated in 0.3.1 when I made these trap changes.

will fix, thanks. Specifically potions will not spawn over chilling traps (but may still spawn over frost traps, just as scrolls may spawn over blazing), and no items will spawn atop explosive traps.

**Comment by Ezelty** [comment]
Thanks! The most important thing, in my opinion, is that objects that give access to other objects (such as potions of invisibility, potion of levitation or keys) shouldn't be destroyed without giving the player any mean to avoid it.

**Comment by 00-Evan** [comment]
fixed in commit 4ffd6f9c83c8b6bd1c253f0d1725c3fd9a5178a6
