### ISSUE TITLE
Tile Press Failure

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1191]
![Screenshot_20221209-144915](https://user-images.githubusercontent.com/91638992/206816800-f887e34d-fbc3-4a18-9148-b8be67deabd2.png)

You should be able to see a burning trap below the northern golem. You should also see the corrosive cloud centered on it. I zapped the wand of corrosion @ it & the wand didn't activate the trap as it would've done if the golem weren't there.

**Comment by 00-Evan** [comment]
Wand zaps only press tiles if there is no character there.
