### ISSUE TITLE
Uncanny Dodge, Pt. 2

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1192]
![Screenshot_20221209-153833](https://user-images.githubusercontent.com/91638992/206818080-33c8de13-f170-446e-844c-59b48be88c8a.png)

I used Spectral Blades on all 3 piranha @ once. The northern 1 somehow dodged the attack & remained asleep.

![Screenshot_20221209-153940](https://user-images.githubusercontent.com/91638992/206818154-bb88682e-6ab3-4e35-a992-4b390df96df9.png)

![Screenshot_20221209-153952](https://user-images.githubusercontent.com/91638992/206818181-4ff4c8bf-104c-4391-bfce-6a816f132e64.png)

I did this 2 more times (as you should be able to tell based on the % on my quickslotted armor) & the fish dodged twice more. Flail was my equipped weapon, if that makes a difference, & I also had a +2 ring of accuracy.

On a side note, Swarm Intelligence was 1 of my active challenges but all piranha weren't alerted by a successful attack.

**Comment by Pr0methean** [comment]
Spectral Blades says it's based on your weapon's attack, and flails can't surprise attack.

**Comment by 00-Evan** [comment]
As noted, flails cannot surprise attack.

**Comment by LeahLuong** [comment]
@00-Evan That makes sense but it seemed really strange that the fish made 3 dodges in a row, especially considering the accuracy bonus from the ring. Does that factor in while using Spectral Blades?? I think it should prob stack w/ Spectral Blades' own accuracy buff talent but that didn't seem to be happening based on my experience here & in the rest of this run. If I'm not mistaken, flails have -20% to-hit but I should've been offsetting that by +169% (so, +149%; +119% from ring of accuracy +2, +50% from Projecting Blades, & -20% from flail).

Also, what about Swarm Intelligence not waking up all piranha??
