### ISSUE TITLE
DM-201 stuck in a corner. Won't move, won't attack.

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#1194]
Playing the Daily for 2022-12-04. On level 14, a DM-201 has been generated in the position as per screenshot.

![signal-2022-12-11-205454](https://user-images.githubusercontent.com/46329185/206925840-2e653c07-a901-4d77-ac0a-3c9e3b498f95.png)

The mob neiter moves nor shoots gas. It will only attack when approached.

**Comment by pescepalla** [comment]
Ok. Indeed intended behaviour. But why having a mob you can effectively just ignore 99% of the times?

**Comment by 00-Evan** [comment]
DM-200s, being a large enemy, can be ignored as long as you stay out of their range. DM-201s are meant to push that a bit further, by having an extremely limited ranged but more power to compensate.
