### ISSUE TITLE
DM-300 enemy prioritization is cheesable & DM-300 rockfall has no minimum delay

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1196]
DM-300 can become fixated on heroes' allies he can't reach, e.g., a sad ghost holding position in a narrow hall. The robot will sit there unendingly spewing toxic gas & ignore ranged attacks coming from the hero. Would it be too much to have this boss do a check after launching X gas attacks for no effect, after which it'd go back to wandering?? Sentries are also immune to toxic gas & can be used to cheese in this way. Perhaps heroes' allies should be precluded from DM-300's special attacks??

A tangential issue is that allies targeted by a rockfall can generate an unavoidable paralysis & score deduction. I believe the warning animation plays for only a small fraction of a tick before the attack happens. If your hero's clock isn't sync'd w/ their ally's & they happen to be w/in a couple of tiles, there is a very high likelihood of instant paralysis & loss of score. Of course, there are many different reasons for why the clocks wouldn't be sync'd, especially in this particular fight where it's likely the hero will use a haste potion to get to a pylon.

I have some pics to post here but I'm seemingly unable to because of a low mem warning. Is this on my end or github's??

**Comment by 00-Evan** [comment]
Enemies change targets if they are being attacked by something closer than what they are currently hunting, I will consider adjusting this so 'closer' uses pathfinding logic, such that unreachable enemies are seen as very far away.

Please open separate issues for unrelated bugs. I can see that DM-300's rockfall logic is missing a minimum duration check of 1 turn (such as with Goo's pump up and Yog's laser), which could cause your described behavior to occur when targeting an ally in some cases.

**Comment by LeahLuong** [comment]
![Screenshot_20221216-080141](https://user-images.githubusercontent.com/91638992/208280776-ef25b588-aaa3-4c83-8fbe-45b0db86a802.png)

Sad Ghost was 1 tile west from where she is in the pic; I'd moved her into view for the 'gram. From there, she couldn't see DM-300 but it could see her. When she could see the boss, she'd run over to attack it, ignoring the hold position command a turn after given.

During this run in other encounters, I noticed Sad Ghost had an annoying propensity to ignore move commands when occupied in a fight. Got her killed @ least twice. Is that intended behavior?? I can try to study that more if not.

![Screenshot_20221216-080759](https://user-images.githubusercontent.com/91638992/208280982-1b86bed5-5f05-4caa-9621-10eade944926.png)

Later in that fight, I'd positioned a sentry where it couldn't return DM-300's fire. I've never understood the logic of when corners can be fired around but I've gotten an intuitive sense of it from fighting many deathgazes. Of course, I can bend shots around many corners by manually tapping on the correct tile but mobs seem incapable of bending their shots around certain 6-tile arrangements. Is there any logic to it or is it arbitrary?? It seems like they can't fire north/south in horizontal arrangements but can fire east/west in vertical arrangements. Here, in a vertical arrangement, the entity closer to the corner is able to fire south while the other isn't able to fire north.

**Comment by 00-Evan** [comment]
Ran some tests and looked at your screenshot more carefully, this is working as intended. Enemies automatically try to switch targets when their current one is unreachable. In your first screenshot, both you and the ghost are out of reach of DM-300, so it prefers to keep using abilities (something which the ghost is quite effective against).

**Comment by LeahLuong** [comment]
@00-Evan When you changed the title of this issue, you also split it into 2 separate 1's. I hope you don't forget to fix the minimum duration check for rockfalls . . .
