### ISSUE TITLE
Attacking succubus from out of FOV does not surprise it

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1197]
I have a pic I'd like to post for this topic but can't due to the low mem warning. I don't think anything's changed on my end since posting pics here before. Have I hit some sort of github limit for posting??

Anyway, I'd hit a succubus w/ a blinding dart & created some separation using Ally Warp w/ Sad Ghost. My next 2 darts were dodged by that succubus despite the separation & debuff remaining. The pic shows the succubus' description box w/ active blindness; off to the side, my mage is standing a tile away from the succubus w/ a dart @ her feet.

I have a couple of hypotheses for what's going on here: either Ally Warp is fooling the game into thinking my mage is still adjacent to the succubus, or the succubus' status as a blessed champ is somehow throwing off the to-hit calc. I'm leaning more towards the former but the game did have a full player turn to update my hero's status before the 2nd standard dart missed.

**Comment by LeahLuong** [comment]
![Screenshot_20221216-150621](https://user-images.githubusercontent.com/91638992/208280601-e78ae1d8-6be9-4e2a-b8c4-400a2188918c.png)

It was on my end. I'd enabled a dev option to discard left activities on my phone & this was seemingly blocking my uploads.

**Comment by 00-Evan** [comment]
This is because surprise attacks consider whether an enemy seeds their current target, not whether they see you in particular. I may be able to add some additional checks for this in cases where the hero is entirely out of the enemy's FOV, but it's not really feasible for enemies to track whether they see every other character all the time.

**Comment by 00-Evan** [comment]
fixed in commit a7a0a7e51f10f9a0e970979a8322544f44970acb
