### ISSUE TITLE
Sound effects play on rear speakers

### ISSUE THREAD

**Issue by foresto** [00-Evan/shattered-pixel-dungeon#1199]
On a desktop system with 5.1 surround speakers, the game plays sound effects through the rear speakers, and music through the front.

Having on-screen actions produce sounds behind me is disorienting, and sometimes startling for other people in the room. Is there a way to swap them, or select which speakers to use, or send all sounds to the front?

This is the v1.4.3 desktop build, OpenJDK 11.0.17, on linux.

**Comment by 00-Evan** [comment]
Another user messaged me about this about a year ago, unfortunately this is likely an issue with LibGDX's implementation of openAL, and there's not really anything I can do about it on my end. LibGDX does not expose functionality for specifying which speakers audio comes from.

**Comment by foresto** [comment]
For the record, Slay the Spire (another java game using libGDX and OpenAL) does not have this problem. That might be a useful lead if you ever decide to investigate.

**Comment by 00-Evan** [comment]
Slay the Spire likely uses a much older version of LibGDX, may interface with openAL directly, etc. There are a lot of variables that would not be the same between these games.
