### ISSUE TITLE
Summoned Immunity

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1200]
![Screenshot_20221221-121759](https://user-images.githubusercontent.com/91638992/209039722-90177b8f-2626-4d22-a238-204ab4fda4b6.png)

This may be related to the quirk where fresh mobs can't be surprised. Here, I dropped a corrosive cloud before the monk appeared, while the green particle animation was playing. The monk then gained focus & took a step towards the hero but was unaffected by the blob.

**Comment by 00-Evan** [comment]
This is working correctly, and is due to actor order. In this case the relevant actor order is characters -> gasses -> buffs

So we get: other chars act -> gas acts -> spawner buff acts, summoning monk -> monk acts

**Comment by LeahLuong** [comment]
@00-Evan That's confusing. The monk took its turn by stepping towards the hero & gained a buff. By the actor order you described, the corrosive gas should've taken effect betw/ those 2 things, as it tends to do everywhere else in the game. But because summoning the monk is a "buff" it gets to evade blobs on the turn it's spawned??
