### ISSUE TITLE
Undocumented Statue

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1202]
![Screenshot_20221221-171433](https://user-images.githubusercontent.com/91638992/209040988-318c119d-03c4-4aeb-b955-c8f19847e9a1.png)

I spotted this statue earlier in the run, examined its weapon, & decided to come back for it later. Luckily, I remembered to return when I was stronger despite the journal not noting it. It seems you need to spend more than a full turn w/ vision on it before it gets logged. My hero had no clock-affecting modifiers active when 1st observing the statue nor in the pic above.

I believe the same issue can occur w/ altars. In fact, this issue tends to affect altars more because players learn to recognize the altar room's architecture before laying eyes on the altar itself.

On a side note, it'd be nice if you could steal statues' weapons. I was once lucky enough to have a disarming trap spawn right underneath where a statue was placed; got a chuckle out of defeating the statue by throwing a torch. In the case of armored statues, maybe have a 50/50 on whether stealing takes the weapon or armor.

![Screenshot_20221221-171508](https://user-images.githubusercontent.com/91638992/209042248-f2f51db2-e3d8-4f85-b0d5-b5f83b1c1ab2.png)

**Comment by 00-Evan** [comment]
Not able to reproduce this with normal movespeed, will consider adjustments so that journal notation doesn't rely on characters/effects active while in view.
