### ISSUE TITLE
Ethereal Pickaxe

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1203]
![Screenshot_20221222-213712](https://user-images.githubusercontent.com/91638992/209285377-62ae964e-5daf-40ff-ae70-88778c6f6359.png)

Died to a bat after a ludicrous sequence where I pushed it to 1 or 2 HP like 4 times. On the last time, I was like, "I have 15 HP left! Surely, it won't evade death this time & return a lethal blow. I don't even think it can considering my chain mail!" When prompted to choose my keepers, I switched the pickaxe for my mage's staff.

On resurrecting, I was getting my ass kicked by another bat when I opened my pack to find the pic posted above. Now, I don't die all that frequently &, when I do, I'm usually wearing what I'd choose as my keepers anyway. I don't think this is typical behavior for how the game handles EQ swaps on death but, if it is, I'd suggest changing it so your kept items are the 1's you resurrect w/ equipped. I was able to equip my mage's staff, slay that bat, & recover my lost pack but it was silly I had to find out the reason I was dealing piddly dmg & getting my HP drained by a bat was that I was attempting to wield a pickaxe I no longer had access to. The EQ selection screen conveys the impression that you are, in fact, changing your EQ.

If this happens w/ armors (i.e., switching armors on death results in the selected armor ending up on your back instead of girding your loins), the equip time ends up as a 2nd death sentence when you realize your lack of protection while an enemy is already upon you.

Anyway, Merry Chrimbus. I hope Winter Man leaves you many gifts under your Chrimbus bush.

**Comment by 00-Evan** [comment]
Working as intended, choosing to keep an item does not auto-equip it.

**Comment by Pr0methean** [comment]
It's also worth noting that an armor's minimum damage absorb roll is always the same as its upgrade level. So +0 chainmail can't reduce the probability of a given amount of damage to zero, even though +1 cloth armor can.
