### ISSUE TITLE
Blue fire treasure room, PoLF and PoFr interaction bug

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#1204]
In a treasure room with "blue fire"... Drinking a Potion of Liquid Flame while being adjacent to the blue fire, then drinking Potion of Frost immediately after does not cleanse the blue fire. 

However, simply drinking the Potion of Frost should suffice in any other scenario.

I consider this is not an intentional behavior.

**Comment by LeahLuong** [comment]
I believe this is intended behavior. This once happened to me & I felt jilted but c'est la vie. I stepped up to the fire wall because I didn't know which pot was frost & was going to test them. Hit fire pot 1st & kept drinking. The frost put out the normal fire but not the magical fire underneath.

**Comment by fregkos** [comment]
Yes, exactly the same happened to me and it seemed like there were "two layers of fire" on the same tiles, but the Potion of Frost cleansed one layer instead of all. I don't find it intuitive, I'd expect any fire to be overridden with frost and vice versa. Otherwise I, as a player, should then start thinking of AoE layers for other game mechanics too.

**Comment by 00-Evan** [comment]
This is happening because fire and frost are meant to cancel each other out, so the frost does not persist for an extra moment and cancel out the magical fire. Probably magical fire should just cancel out regular fire, as it doesn't really make sense for them to both exist on the same tile.
