### ISSUE TITLE
Blind Bees

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1205]
Improvised Projectiles blinds bees which emerge from thrown honeypots. It's not like the thrower is intentionally flinging something @ the bee's eyes to blind them so I think there should be an exception for this talent in this case. Throwing honeypots is the generally preferred method of using the bees inside them & having the bees emerge blind seems like a silly & unintentional nerf for users of Improvised Projectiles.

**Comment by LeahLuong** [comment]
On 2nd thought & after posting, I realized I may've fatfingered this. I was setting up a bee @ a pylon before the DM-300 fight & threw the honeypot out of vision. It's possible the honeypot hit the pylon instead of landing next to it. I saw the Improvised Projectiles cooldown pop up after the throw & assumed the bee was blinded.

Feel free to ignore this if you can't reproduce blind bees in testing.

**Comment by LeahLuong** [comment]
Got another chance to test this & I'm unsure if it's happening. The bee approached me & wasn't blinded after throwing the honeypot. It may still get blinded if it doesn't move immediately but that would mean it's likely in combat & doing its job; temp blindness shouldn't really come into play then, even if it does happen.

Then again, players might want their talent off cooldown if this is happening. IDK when I'll get another chance to test this. If you do test it, make sure you stand well back from where the honeypot lands so the bee doesn't immediately aggro on you.

**Comment by 00-Evan** [comment]
Just tested this. Throwing the pot to an empty spot does not blind the bee or set the talent on cooldown. Throwing the pot onto an enemy correctly blinds that enemy while also summoning the bee.
