### ISSUE TITLE
Deathless Fury Vs. Death

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1207]
![Screenshot_20221226-103701](https://user-images.githubusercontent.com/91638992/209581615-b96ed168-6c0c-4b3b-8b6e-d73c3025baea.png)

I had 1 point in the talent & stepped on a storm trap while above 100% rage. My searches here, on reddit, & @ the wiki seem to indicate the talent should've taken priority over the ankh. This makes sense because players have more access to ankhs rather than the talent; the talent becomes superfluous (barely redundant) when an ankh is present, especially considering how 1 loses all rage after an unblessed ankh procs.

I believe this was the 1st & only death on this run (so far). Obviously, the ankh was unblessed.

**Comment by 00-Evan** [comment]
Looks like your armor is missing the warrior's seal. Berserking requires the seal to be equipped.

**Comment by LeahLuong** [comment]
@00-Evan I suppose that makes sense as the ability mightn't know what value shield to give. Still, I think it was misleading the berserking icon appeared if I didn't have the sealed armor on & was unable to berserk; I had a bad feeling about that hallway & would've drank a pot if that weren't showing. Rage encourages players to keep low HP & I figured I was safe awhile longer because berserk seemed ready. The sealed armor was in my pack but I was working on ID'ing a 2nd set for the troll & hadn't put 2 in Armsmaster's Intuition this run as I normally do.
