### ISSUE TITLE
Wands seems to deal more than the stated max damage

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1208]
The stated dmg for magic missile was 3-10 but I saw it do 11 in 1 hit during the Goo fight. Later in that same run, I saw lightning do 21 to a necromancer when its stated max was only 20. I was using the mage's staff in both cases. Both times, this was the 1st dmg taken by that enemy.

![Screenshot_20221226-174103](https://user-images.githubusercontent.com/91638992/209900005-38c71f67-1dfd-419a-b039-bbbd975db427.png)

Here's a pic right after zapping the necro. Lightning was imbued on the mage's staff +2. The necro wasn't in water & the lightning didn't chain.

This isn't something I ordinarily pay attention to because I trust computers to calculate correctly. I just happened to notice the discrepancy because I glanced @ the mage's staff description box for some reason during the Goo fight. Later, 21 seemed like an extraordinary amount of dmg & checking the description box revealed it was so.

**Comment by 00-Evan** [comment]
These are not youtube videos, please use reasonably descriptive titles.

Were you perhaps under the benefits of the empowering meal talent?

**Comment by LeahLuong** [comment]
@00-Evan I'll work on using more descriptive titles. I don't always have a good grasp of what might be going on w/ various issues & would rather err on the side of generality than lead to false conclusions.

It's likely Empowering Meal was @ play in the Goo fight. I usually have the On Diet challenge active & tend to eat just before a boss fight to maximize passive regen. IDK if that was a factor w/ the necro but I think you're prob right even though it's not showing in the pic.

I'll keep an eye out & ask for this issue to be reopened if it comes up in future mage runs.

Quick question: do huntress' Shared Upgrades work w/ darts fired from an upgraded crossbow?? On my last run, I'd invested 3 in that talent & it didn't seem to be performing as well as past runs where the talent seemed to synergize strongly w/ an upgraded Ring of Sharpshooting. I've been able to get 100+ dmg sniper shots using a +8 ring but my +10 crossbow in this  last run was only able to clear 50 dmg a couple of times (that is, the sniper shot following the firing of a dart).

**Comment by 00-Evan** [comment]
Shared upgrades does not apply to the crossbow or the ring of sharpshooting, neither affect the actual upgrade levels of thrown weapons. Sharpshoting felt like it was doing something with the talent because it also boosts the base damage of the bow.
