### ISSUE TITLE
Mob enters shop upon death shopkeep dissappears

### ISSUE THREAD

**Issue by 133794m3r** [00-Evan/shattered-pixel-dungeon#121]
I don't think mobs should be allowed to just randomly wander into th eshop an dthen block the entrance I don't know how it's code atm but having a mob block the entrance and force you to give up the shop keeps items or run around taking damage and try to buy stuff you need until you kill it.

I happened upon this by chance thinking nothing of it, but then the mob died the shopkeep left, and the mob didn't even drop an item for me.

I should also say I was a good ways into the shop and I didn't get the "mob seen" notification until it was in the doorway.

**Comment by 00-Evan** [comment]
Was this mob a skeleton? The shopkeeper is not scared away by nearby combat, only by taking damage or being affected by a debuff.

Sounds to me like a skeleton exploded near the shopkeeper and that's what caused him to run.

**Comment by 133794m3r** [comment]
It may have been, I got sidetracked after reporting it and meant to post a screenshot. Do skeletons explode? And if they do what damage do they do wen they do it? I think it might've as it was on the second shop I think or maybe the first I think it's the first on so it'd have to be a skeleton I guess or a thief thing.which I don't belive it was. I guess it was a skeleton.

I have accidenetly burn the shopkeeper up though after buying what I wanted at tha ttime b/c I get glyph of brimstone a ton of the time an just drink liquid fire potions to use a temp healing ones.

**Comment by 00-Evan** [comment]
This sounds like it's working as intended then.

Skeletons damage all characters near them when they die, so the shopkeeper was hit and scared off.
