### ISSUE TITLE
Suggestion: always open to backpack when preferred container is not present

### ISSUE THREAD

**Issue by inkhsutesou** [00-Evan/shattered-pixel-dungeon#1210]
No reason to open anywhere else, causing needless player interaction

**Comment by 00-Evan** [comment]
Liquid metal actually already prefers to open the magical holster (if it is present) instead of the base inventory.

**Comment by inkhsutesou** [comment]
When the magical holster is not yet attained can it please open the main inventory where thrown weapons will be instead of the potions band ?

**Comment by 00-Evan** [comment]
I see, will consider that.

**Comment by inkhsutesou** [comment]
🙇🙇🙇

**Comment by 00-Evan** [comment]
fixed in commit 24883323f991baac3cac057dfcac2a11ea1b4251
