### ISSUE TITLE
Wielded Drop Time Is Counterintuitive

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1211]
Currently, dropping a wielded weapon takes 2 full turns. Presumably 1 to place it in the pack & 1 to drop it from there. I'd argue it should be a free action. IRL, I can simply open my hands as I reach for something else, allowing that which was in my hands to be taken by gravity. Wielding a new weapon should, of course, still take a turn.

Right now, the use case for this proposed change is fairly narrow. The only practical scenario I can think of is when you're maining a ring of force but want to test an un-ID'd weapon to see if you have enough Str to wield it. If you discover you don't have the Str, you could switch back to your fists immediately instead of having to spend a turn or 2 putting the weapon away.

I believe this may change w/ the introduction of the duelist. It may be the new hero can gain benefits by carrying a backup weapon or 2 to make use of their specific abilities. Players who attempt to cut the corner of wield time by dropping their current weapon would actually be penalized for attempting to implement a clever solution; they'd have been better off carefully placing the item in their pack during the heat of combat before pulling out a different 1. Instead, if this feature request is implemented, the instantly-dropped weapon could be picked up after combat's over & players wouldn't lose turns taking the time to properly sheathe their weapons mid-combat.

IDK how the timing works w/ throwing wielded weapons but perhaps that deserves a look as well. Throwing a wielded weapon presumes some wind-up & gauging so prob should take a turn but not 2. Would be neat if certain thrown weapons (i.e., spears, great swords, perhaps glaives) had application beyond Improvised Projectiles. There is also the issue of how certain actions which are currently free prob should take time (i.e, alchemy, liquid metal) but that's beyond the scope of this post.

If I'm wrong about the duelist gaining benefit from backups, I can understand how this prob isn't worth implementing. The ring of force edge case rarely comes up & a single lost turn or 2 isn't usually enough to wreck a run.

**Comment by 00-Evan** [comment]
I'm not interested in opening up the micro-optimization of dropping and equipping a weapon instead of swapping which weapon is equipped.

The Duelist will have a talent and subclass mechanic to allow for the rapid swapping of weapons.
