### ISSUE TITLE
Elemental Blast should tell the player if they do not possess their staff

### ISSUE THREAD

**Issue by ResCXsention** [00-Evan/shattered-pixel-dungeon#1212]
Apparently, attempting to use Elemental Blast as a mage without a staff (e.g. after using an ankh) simply closes the menu silently with nothing happening, even if it has enough charge. I think the armour should note the fact that the ability has no source in order to avoid confusion about why the ability isn't working.

**Comment by 00-Evan** [comment]
fixed in commit c9bb2421f5df8f7f26f1716398c950aafeebf6ea
