### ISSUE TITLE
DM-300 game frozen 

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#1213]
![Screenshot_2023-01-17-23-10-10-76_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/212973290-4b69405e-0dfc-4ada-b5a6-ed4a4befe3e8.jpg)
Well while battling DM-300 I used 2 scrolls of mirror image and I was equipped with ring of haste. The game came to an infinite turn loop when DM-300 was making the rocks fall on my mirror image.

**Comment by 00-Evan** [comment]
Was this an actual infinite turn loop (as in, DM-300 was constantly dropping new rocks) or a freeze, where DM-300 completed its action but no further actions could occur?

**Comment by Mellotic** [comment]
When DM-300 used the turn to rocks to fall then game freezed

**Comment by 00-Evan** [comment]
Okay, also where is the mirror image in this screenshot? Did it walk outside of your field of view?

**Comment by Mellotic** [comment]
Yes it did and I think that caused it cus it was targeting my image and while me having ring of haste this caused it.

**Comment by Mellotic** [comment]
I restarted the game and yes it was targeting my image

**Comment by Mellotic** [comment]
Just to add my ring of haste is 3+

**Comment by 00-Evan** [comment]
This may be occurring because of a lack of minimum turn delay on the rock fall ability, which is also causing a separate quirk that was reported to me a few weeks ago. The fix for that error should also incidentally fix this.
