### ISSUE TITLE
Double firewall from Tengu

### ISSUE THREAD

**Issue by Diomos** [00-Evan/shattered-pixel-dungeon#1214]
v1.4.3 and previous
**Steps to replicate:**
Attack Tengu with enchanted chilling weapon and slowing him down OR use wand of frost OR attack with high damage attack before he can drop bomb or create next fire wave.

**Problem**
Tengu creates "double wall" (experience triple once), meaning it take two tiles thick instead of normal one.

It looks like Tengu wants to "keep up". Not sure if this is intentional, but I don't think so. It's basically punishing player for using specific attacks.

**Comment by 00-Evan** [comment]
this is intended. In these cases only the last tile of the wall actually ignites each turn, making it possible to evade still.

**Comment by Diomos** [comment]
Thank you for the reply. Good to know. Yet I was trying to avoid "both" tiles anyway, so to me as player it was confusing :D

**Comment by protective1** [comment]
Hi @00-Evan - which tile is the "last" tile of the wall?  Is it visibly different?

**Comment by 00-Evan** [comment]
@protective1 the wall is moving in a direction, only the layer that is furthest from the direction the wall is moving will ignite each turn
