### ISSUE TITLE
Suggestion: Allow renaming of all items

### ISSUE THREAD

**Issue by inkhsutesou** [00-Evan/shattered-pixel-dungeon#1217]
I would like to do this to place my guesses on scrolls and potions.  I write information about my predictions on equipment whether they are possibly cursed or where an item came from

If I believe a potion is healing or levitation I'd like to write my prediction down before swallowing it.

**Comment by 00-Evan** [comment]
I would like to allow players to add custom notes in the future for something like this, but I'd rather not let the player rename stackable consumable items. It just creates too many problems when it comes to name persistance. e.g. are you renaming that specific potion or healing, or all potions of healing?

**Comment by Pr0methean** [comment]
I think I speak for most players when I say renaming a potion or scroll would apply to all identical items, and only until they were identified.

**Comment by inkhsutesou** [comment]
Rename a stackable consumable, as to rename an individual potion would require more work in separating stacks.
However, the ability to keep notes on an unidentified potion or scroll is very valuable.  Especially as valuable as keeping notes on where a weapon or armor came from.

Perhaps another interface that allows a player to keep a prediction of the scroll or potion like the way the stone of intuition works ?  it keeps the icon of what the player believes it to be.  although i think renaming would be less work or renaming UNTIL it is identified ?

**Comment by Mokura** [comment]
I think it'd work like nethack - "a stack of X unidentified potions named Y"
