### ISSUE TITLE
Corrupted mobs attack neutral animated statue

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1220]
I didn't want to fight this one because I'm battlemage and it has great gear that I therefore don't want. 

A corrupted golem teleported into the room, attacked the statue, and got smacked down. Now it's coming after me!

A bee is one thing, but I would expect that corrupted mobs would ignore a neutral statue the same as before I recruited them over to my side...

**Comment by 00-Evan** [comment]
This is intended. Only intelligent allies (such as the ghost) ignore passive, sleeping, or wandering enemies. Simpler allies (corruption targets, mirror images, etc.) will attack whatever they find.
