### ISSUE TITLE
Is the Desktop.jar the Full??

### ISSUE THREAD

**Issue by MarshMeadow** [00-Evan/shattered-pixel-dungeon#1222]
Is the GitHub desktop version of the game the full one, why do you have to pay on steam?

**Comment by TheYsconator** [comment]
Gameplay-wise I believe they are the same game. However, with the Steam version you support Evan (the developer), you have the game on Steam (with the associated features of having Achievements listed on your profile etc.), and you get the game in a nice executable package (so you don't have to run the game from the .jar). I believe those are the current differences. I believe I've read that Evan plans on adding some if not all of the 'donator'-features from the Android version to the Steam version as well, but on that I'm not certain.

Anyway; gameplay-wise: Shattered is a free game - in practically all its glory.

**Comment by 00-Evan** [comment]
As mentioned, paying for the Steam version gives various small extras and financially supports me so that I can keep making the game.
