### ISSUE TITLE
Moar datas pleaz

### ISSUE THREAD

**Issue by vernzimm** [00-Evan/shattered-pixel-dungeon#1223]
I would like the option to view log data of damage calculation, and/or additional info about player stats, such as evasion, move speed, attack speed, etc.

I understand it's probably part of the experience to figure things out by context and observation, but it's also frustrating when it's not something you can figure out, now you're dead, who knows when you will have a similar configuration to try a different approach.

Maybe a log after death of last several lines/actions so it is easier to realize what your mistake was?

-----

One additional complaint that I find really frustrating is lack of HP recovery can make a really good run end too soon. I've got dozens of potions, wands, scrolls, good weapon/armor, food, etc, but used all HP stuff, and in later levels it's basically impossible to sleep to heal even if you have lots of food... you get ambushed immediately and end up losing the few HP you had gained.

v1.4.3 on Android 10

**Comment by 00-Evan** [comment]
Offering a full log would also mean recording all of that data and persisting it between save/load. I generally prefer to only show the stats that are required for player decision-making, accuracy and evasion are especially awkward as the stats themselves tell you nothing about actually hit/dodge chance. The game also already has a basic log that does include details such as what killed you.

As for healing, if you are running out it is likely there are things you can to do improve your strategy. Being constantly low on healing likely means that you're going through it much faster than if you were positioning better or better spending scrolls of upgrade.
