### ISSUE TITLE
Bug With Stone of Intuition 

### ISSUE THREAD

**Issue by TheShadowOfHassen** [00-Evan/shattered-pixel-dungeon#1224]
Ok this is going to sound weird but if you click to use a stone of intuition and on the guessing menu close the program it destroys the stone. I don't know if it's because it guesses and is wrong or just destroys it.

I'm running the latest shattered pixel dungeon Flatpak build on Ubuntu 22.04

I love this game and I'm really happy about the lore additions because I love story additions. I can't wait to see what else you add.

**Comment by 00-Evan** [comment]
This is consistent with how other items with inventory selectors behave. If you quit the game with the interface open, it has no opportunity to process that the action was cancelled and return the item.

**Comment by TheShadowOfHassen** [comment]
It is rather unfair behavior, I think, and not what anyone expects.

**Comment by 00-Evan** [comment]
I agree that this is unfortunate, but generally the game isn't expecting to be closed in the middle of an interaction. As I mentioned this affects lots of different things were not designed with this in mind.

**Comment by TheShadowOfHassen** [comment]
I understand that, I just wanted to let you know.

**Comment by Pr0methean** [comment]
If you're restarting regularly because the game is crashing, then the crashes are probably what you should report here.

**Comment by TheShadowOfHassen** [comment]
No the game isn't crashing, but sometimes my computer does, it's an older system and nvidia isn't really supporting the graphic drivers any more
