### ISSUE TITLE
One-off donations to the Shattered Pixel Dungeon

### ISSUE THREAD

**Issue by sokolgeo** [00-Evan/shattered-pixel-dungeon#1225]
Hello!

Apart from patreon link, which is monthly payment, is there a way to make a one-off donation via a PayPal link, please?

Thank you,
George

**Comment by 00-Evan** [comment]
It is entirely possible to make a single payment on the Patreon and then immediately unsubscribe. There's even a yearly option now, so if you were going to make a single payment of about $20 US you'll even get a year of base-tier Patreon benefits.

I would rather encourage people to sign up than offer a one-time payment option.

**Comment by sokolgeo** [comment]
Totally understand the preference for subscription model. The problem with Patreon for one-off payments is that it will charge you on 1st of the new month. Which means for today I shall wait until Feb 28th, get charged by Patreon, and then go through unsubscribe routine. Rather an effort for a simple one-off transaction, isn't it? But its your choice, right?

**Comment by 00-Evan** [comment]
I've actually recently changed that, the Shattered Patreon now charges on signup, and then at the same time next month, or next year if you sign up yearly.
