### ISSUE TITLE
Sacrificial Fire Nearly Impossible on First Floor

### ISSUE THREAD

**Issue by ReallyBasicGames** [00-Evan/shattered-pixel-dungeon#1227]
There have been many games where a sacrifice room appears on the first floor, but I only discover it once most of the enemies are killed. The first floor doesn't spawn any enemies, so this room is nearly impossible to complete. I would suggest checking if this room exists on the current floor and have the dungeon spawn mobs for you to kill until this room is cleared.

**Comment by 00-Evan** [comment]
Sacrificial fire spawns additional enemies in the level when you see it and no enemies are present, specifically so that fire on floor 1 is not impossible if you've cleared the level first.
