### ISSUE TITLE
[Locale][2.0.0 beta 1] Weird interactions between phone and app language when the phone is in French locale.

### ISSUE THREAD

**Issue by yerffff** [00-Evan/shattered-pixel-dungeon#1228]
Hi,
On the latest beta, phone and app language seem to be interfering. With english selected, I still have some bits translated in French.

For example : 
![Screenshot_20230210-095841_Shattered Pixel Dungeon](https://user-images.githubusercontent.com/925989/218048726-773c3a13-9176-4fb0-befe-5d5f118787a9.png)

It happens on most menus and weapons, but seems to be specific with French Language (tested with Deutsch without any problem).

**Comment by 00-Evan** [comment]
I'm aware of this, being fixed in beta-2

**Comment by 00-Evan** [comment]
Fixed in BETA-2
