### ISSUE TITLE
Duelist ability deactivation and item duplication 

### ISSUE THREAD

**Issue by isaac-ped** [00-Evan/shattered-pixel-dungeon#1229]
NB: unsure what led to this.

Suddenly (in the dwarven halls) I was unable to use the duelist's ability on my primary weapon (screenshot 1). The ability counter next to it disappeared.
![Screenshot 1](https://user-images.githubusercontent.com/3009842/218188743-7c8f9d5b-1c33-45f3-b4f9-5c6a1b1e7d6b.png)

When I clicked on the quick-use slot, it asked if I wanted to equip it. I said I wanted to equip to my primary slot and when I did a copy of the item landed on the floor (i had no space in my inventory)

I did this twice more (could only do so after sleeping because i had to wait for the quick-equip timer to count down) and each time a copy landed at my feet.

After several turns the ability icon reappeared. At this point the ability activated when clicked. I tried to pick up the three duplicates (after clearing one spot out of my inventory).
It said that I picked up all three but only one duplicate wound up in the inventory (screenshot 2) 
![screenshot 2](https://user-images.githubusercontent.com/3009842/218189345-4818e9bb-191e-41b3-8573-16b4724ae50e.png)

Not sure if I can get you logs or something else useful for debugging. Can provide more context if needed.

(An aside: thank you for your work on this! I quite enjoy watching your dev process and the iterative nature of building the game)

**Comment by 00-Evan** [comment]
This is already fixed in BETA-2
