### ISSUE TITLE
Sometimes fire burns forever

### ISSUE THREAD

**Issue by bjthinks** [00-Evan/shattered-pixel-dungeon#123]
If I kill an enemy who is on fire, and the enemy drops an item, the fire will continue to burn indefinitely (or until I step on it to pick up the item, at which point I will be on fire instead of the dropped item).

**Comment by 00-Evan** [comment]
This is already fixed indev, will reference commit when source is released for 0.4.3

**Comment by bjthinks** [comment]
Saving and reloading also seems to fix this.

**Comment by OffifialMITX** [comment]
Also you con throw any object that doesn't burn on the fire and after the next round it stops.

**Comment by 00-Evan** [comment]
fixed in commit 4c38f73fdf5fba8355865635b829973716fbe966 along with several other bugs
