### ISSUE TITLE
Several issues with duelist and ring of force

### ISSUE THREAD

**Issue by folkcoder** [00-Evan/shattered-pixel-dungeon#1230]
On `v2.0.0-BETA-1`, my very observant nine-year-old noticed a few issues with the duelist and the Ring of Force.

1. The duelist can seemingly use Brawler's Stance on an unidentified Ring of Force. I'm not sure if this is intentional behavior since no other rings have an active component.

1. If Brawler's Stance is activated and then the Ring of Force is transmuted into a different ring, Brawler's Stance remains activated and cannot be removed.

I did not manage to get any useful screenshots, but let me know if there's any additional information we can provide!

**Comment by 00-Evan** [comment]
1. That's intended, you do not need to identify rings to benefit from them, nor does the Duelist need to identify items to use her weapon abilities
2. This is partly intended, as I didn't want to force the stance off the moment the player unequips the ring, but I can see how this is akward as the buff would never leave. Will consider changing that in beta-3

**Comment by 00-Evan** [comment]
Point 2 is now fixed in BETA-3
