### ISSUE TITLE
champion and crossbow

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1232]
If the primary weapon of the champion is a crossbow, the power of dartst will not be change. If the secondary weapon is a crossbow, darts will deal more damage

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Darts benefit from the crossbow regardless of the slot it is in.

**Comment by Lyx0527** [comment]
@00-Evan Let me explain this bug again. If the primary weapon is +20crossbow，darts will deal only 4-12 damage

**Comment by 00-Evan** [comment]
Judging from the video you sent over email, you neglected to mention that the crossbow is +0 and benefiting from the twin upgrades talent. I am able to reproduce this issue from the video under those circumstances.

https://user-images.githubusercontent.com/2347603/219718625-6bc83970-59f2-4911-ad32-28494b7a2242.png

**Comment by spixi** [comment]
Doing it the other way around works for me. I currently have a Crossbow +9 as secondary weapon.

**Comment by 00-Evan** [comment]
fixed in BETA-6
