### ISSUE TITLE
Duelist bug

### ISSUE THREAD

**Issue by Yuslendo** [00-Evan/shattered-pixel-dungeon#1233]
I'm not sure if this is a bug. Duelist hits the Marsupial Rat from 1 block away. I can give more information about this if wanted.

https://user-images.githubusercontent.com/123311399/219685662-94c07a49-e932-4e05-8efb-c300c7ec3d0b.mp4

**Comment by 00-Evan** [comment]
I'm aware of this one, will be fixed next beta release.

**Comment by 00-Evan** [comment]
fixed in BETA-5
