### ISSUE TITLE
Rare Crash floor restarts!

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#1236]
I was trying to screenshot while fighting DM-300 ( DM-300 was Charged). Game just crashed the moment when I toke a screenshot and after that I rejoined the floor restarted.

**Comment by 00-Evan** [comment]
Usually crashes like this are caused by your device killing the game for some reason, as it doesn't have a chance to save itself (which it normally can do when it gets a crash). Unfortunately there's nothing I can do about errors like this.

**Comment by Mellotic** [comment]
Is Power Pylon consider as any entity like other?

**Comment by Mellotic** [comment]
Another thing when I have herbal effect and Dm-300 Knocks back, I still do own the effect even if I'm moved from the tile.
