### ISSUE TITLE
Pickaxe, rigid skin

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1239]
Why can pierce deal double damage to flies

**Comment by 00-Evan** [comment]
because they have an exoskeleton, like other insects.

**Comment by Lyx0527** [comment]
Let's imagine, the duelist pierce the pickaxe at a large group of flies which with 0 defence, the sharp end of the pickaxe pierced every fly, and break the exoskeleton that is only used to maintain vital signs.
If flies have exoskeleton worth breaking, what about bees with 0 defence？
