### ISSUE TITLE
sad ghost doesn't come

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#124]
I've killed the fetid rat using a fireplant without hitting it. The ghost's message was displayed but it never arrived.

**Comment by 00-Evan** [comment]
This is probably happening because the ghost is inside a hidden room. The ghost (like all other creatures) cannot move through hidden doors.

**Comment by OffifialMITX** [comment]
Well then, even if it's not actually a bug some ghosts are able to go trough doors.

**Comment by 00-Evan** [comment]
ghosts don't have any special rules for terrain interaction. All characters can go through doors, nothing can go through a hidden door until it is discovered by the player (and becomes a normal door)

**Comment by OffifialMITX** [comment]
What if you use ethernal chains and go trough a hidden door? You haven't to discover it then.
