### ISSUE TITLE
Planted seeds are incorrectly triggered near chasms

### ISSUE THREAD

**Issue by joepatricio** [00-Evan/shattered-pixel-dungeon#1244]
Steps to reproduce:
1) Stand within range of a chasm.
2) Plant any seed.
3) Attempt to fall down the chasm. This will prompt the chasm warning, and incorrectly proc the planted seed.

![Screenshot_20230226-034712](https://user-images.githubusercontent.com/75157862/221376694-06a636c8-3b0e-45e2-bef2-34dec3a98d6d.png)
![Screenshot_20230226-034720](https://user-images.githubusercontent.com/75157862/221376700-72e791b7-e5f5-4882-8d27-27ff11a3e9b1.png)
![Screenshot_20230226-034726](https://user-images.githubusercontent.com/75157862/221376701-f658d35e-92f7-49f3-b30e-17ba979a48d4.png)

**Comment by 00-Evan** [comment]
fixed in BETA-6
