### ISSUE TITLE
Bugs of beta

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1245]
1. The spin buff of the flail will be consumed by the attack of the mirror image.
2. When the target of Dm300 dies, releasing the falling rock to the hero immediately will cause the game stuck.
3. It seems that Patient Strike will work for throwing weapons. At least the sound effect does.
4. Shuriken can be thrown instantly after walk and stay.It may be related to Patient Strike.
5. Focused Meal and Weapon Recharging have different descriptions, but Focus wont charge the scondeary weapon.
6. Guard can negating the damage of force cube, but not the damage of red sentry or traps.
7. Pierce will not deal double damage to the exoskeleton of bees

**Comment by 00-Evan** [comment]
I'd like more information about number 2 if possible, the rest of these seem pretty minor

**Comment by 00-Evan** [comment]
1, and 3-7 have been fixed indev. I am not going to attempt a fix on 2 until I have evidence that it actually occurs in Shattered (reporter send an email of the bug occurring in a different Pixel Dungeon version).

**Comment by Lyx0527** [comment]
Turn 1, DM300 kill a mirror image
Turn2, DM300 cause falling rocks because hero stays nearby
It is difficult  to reproduce. And I don't have much time to re-record
The video comes from beta5 with only text changes, for unpleasant jokes
The email will be returned, if I don't hide the version
![1677710448597](https://user-images.githubusercontent.com/118305192/222282980-5180b652-51be-42c8-84ef-2e79cc29f1f2.jpg)

I use it because it can coexist with SPD on my mobile phones. It is convenient for me to conduct more tests
I guess this bug may be related to bugfix 3-4 in beta1

**Comment by 00-Evan** [comment]
I'm able to reproduce the bug with those steps. Will fix for the next beta.

I've edited your comment to remove references to illegal modifications of closed source versions of Shattered.

**Comment by 00-Evan** [comment]
All issues except for 2 are now fixed as of BETA-7

**Comment by 00-Evan** [comment]
All fixed as of BETA-8
