### ISSUE TITLE
Descriptions of unidentified rings

### ISSUE THREAD

**Issue by vladkryv** [00-Evan/shattered-pixel-dungeon#1246]
The description of the rings reveals the type of the ring before it is identified, on the duellist character.

<details>
  <summary>Screenshot</summary>

![Screenshot_20230226-191711](https://user-images.githubusercontent.com/83036866/221425955-c7f5307f-0b93-47b0-a01a-810ae3eaa9f2.png)
</details>

**Comment by 00-Evan** [comment]
Duplicate of #1230
