### ISSUE TITLE
Missing elemental strike descriptions for duelist

### ISSUE THREAD

**Issue by TomaszKrassowski** [00-Evan/shattered-pixel-dungeon#1248]
The description of different enchantment is visible when applying crown to armor.  
But after the crown is applied, the description is no longer visible (last screen).
![Screenshot_2023-02-28-17-54-01-53_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/30243513/221923354-4b0149f7-7385-4d98-8b03-ce5f9f543368.jpg)
![Screenshot_2023-02-28-17-53-50-06_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/30243513/221923361-0b91105a-6af9-4b2d-9e65-e4191643dcdd.jpg)
![Screenshot_2023-02-28-17-54-16-57_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/30243513/221923365-6fde5065-bfb0-45fa-812d-ef66a7b84170.jpg)

**Comment by 00-Evan** [comment]
The full description of elemental strike, including the enchantment effect, is available from the hero info window. Stats tab -> info button -> armor abilities tab.
