### ISSUE TITLE
Duelist second spec - Spellblade (brainstorming ideas)

### ISSUE THREAD

**Issue by BloodRaven0** [00-Evan/shattered-pixel-dungeon#1249]
I don't know what plans you have for the second specialization of the duelist, but here is an idea that you can take inspiration from:

Spellblade - Can imbue wands into her weapon, similar to how the mage imbues them into his staff. Depending on the wand used, it will grant a different enchantment to the weapon (it will replace any enchantment already on the weapon, but will also not get removed by upgrades).
In addition, they will modify or add special effects to the weapon's special ability.

Talents could include swapping imbued wands without losing them (max level would make the swap instant too), weapon specials buffing other non-imbued wands for a few turns (like the wand of magic missile), wands restoring weapon charges, small chance for enemies to drop arcane resin if killed with a weapon ability (so we can upgrade our wands without sacrificing other wands; maybe cap it to 1 per floor?).

An armor ability that could complement this playstyle could make it possible to imbue wands into the armor as well, in order to change its active ability, depending on the wand.

This is all just brainstorming off the top of my head, hope I could inspire you with some of the ideas. Sorry if this is not the right place for ideas and suggestions, if so, please let me know where I should post them in the future.

**Comment by 00-Evan** [comment]
This is not a place to make gameplay suggestions for the game. The second subclass also was just recently implemented into the beta, and I did have some ideas for a 'spellblade' style subclass, but ended up implementing it as the elemental strike ability instead.
