### ISSUE TITLE
Cannot kill vines with elastic bow

### ISSUE THREAD

**Issue by Halifay** [00-Evan/shattered-pixel-dungeon#1251]
I was playing huntress and got elastic enchantment on her bow pretty quickly. During the wandmaker's quest I tried to kill vines with it, but they seemed to regain full hp every elastic proc. Don't remember having any other modifiers. When I gave up trying to kill them with the bow, I switched to whip/projecting weapon and dispatched them easily. It was a hard run so I wasn't able to test it any further, but I don't have any other explanation.

**Comment by 00-Evan** [comment]
rot lashers heal 3hp per turn when their target is not adjacent to them, to make killing them from a distance harder (but still possible). They also block 0-8 damage per attack. The bow in would be outpaced by their armor and healing, but a whip would deal enough to overcome it.

**Comment by Halifay** [comment]
Yep, my bow was augmented for speed at this point. Sorry, it even written on wiki.
