### ISSUE TITLE
bug of staff

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1253]
https://user-images.githubusercontent.com/118305192/222978998-79d66001-2d81-44d4-a6db-eb2a3eaeac32.mp4

**Comment by 00-Evan** [comment]
Please include a description of the issue in the future. This one is fairly simple so I was able to reproduce it. Seems that Duelist weapon ability targeting logic sometimes interferes with the staff's targeting.

**Comment by 00-Evan** [comment]
Fixed in BETA-7
