### ISSUE TITLE
Bugs with the lunge attack of the duelist with the rapier

### ISSUE THREAD

**Issue by TobinLeNain** [00-Evan/shattered-pixel-dungeon#1254]
If you try to use the lunge attack while over void by levitating thanks to a potion, all ennemies will be out of range, even if they are one square away.

Also, if you use the lunge attack when being stuck by cobwebs or roots, it will still trigger and move you but keep the effect on you. I don't know if it's working as intended.

Sorry for my english, it's not my motherlinguage.

**Comment by 00-Evan** [comment]
I've been aware of these for a bit, but it's been a lower priority to fix vs. other beta issues.

**Comment by 00-Evan** [comment]
Fixed as of BETA-8
