### ISSUE TITLE
Feint armor ability costs 0 charge

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1256]
![IMG_20230308_063956](https://user-images.githubusercontent.com/118305192/223570202-b91f5628-b46e-43dd-863d-75759f90a9d9.jpg)

**Comment by ResCXsention** [comment]
To add: Yes, the ability can be spammed every single turn, so it's not just visual.

**Comment by 00-Evan** [comment]
Please take the effort to actually describe the issue in text and write a proper title, even if it seems obvious from an attached screenshot.

**Comment by Lyx0527** [comment]
> Please take the effort to actually describe the issue in text and write a proper title, even if it seems obvious from an attached screenshot

Actually, it is difficult for me to describe the issues in English.It takes me many times more time than you to describe the same problem. Even so, there may be a lot of language errors. I will pay attention

**Comment by 00-Evan** [comment]
If necessary, you can write in your native language and I can use machine translation. Mainly it's important that issues have informative titles so that people do not report the same thing multiple times.

Regardless, this has been fixed in BETA-9
