### ISSUE TITLE
Bug of unstable spellbook

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1258]
https://user-images.githubusercontent.com/118305192/223708761-2ecf1ded-cac2-40dd-9483-2bd14c345ff7.mp4

Click the book and consumables at the same time in the quick slot, release the book first and then the consumables, and the scroll effect will be used once more

**Comment by 00-Evan** [comment]
fixed in commit 7928f41ee3aff29d49d2f08fd76f887df1f14582
