### ISSUE TITLE
Request: toggle automatic stopping

### ISSUE THREAD

**Issue by ResCXsention** [00-Evan/shattered-pixel-dungeon#1260]
Currently, actions get cancelled every time an enemy enters your sight. Although it's a good protective feature,  this is especially annoying when you are trying to move or are just ignoring enemies, and you get stopped every few turns while they pursue you. 

Would it be possible to have an option to be stopped only if you would be attacked?

**Comment by 00-Evan** [comment]
The automatic stopping is sort of necessary, as an enemy entering your FOV can often mean that the path you're going on is invalidated. Letting the hero continue moving in these cases would result in them immediately turning and taking a different path, which likely isn't what you want.

I'd rather not add a bunch of conditional logic to this, such as a toggle to only stop the hero if a new enemy appears and the path is invalidated.
