### ISSUE TITLE
About bright fist

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1263]
Bright fist can resist the damage of lightning wand, but not the prismatic light wand.
ps
The lightning wand is too pitiful, it will be resist by dm100, pylon, shock element, even the fist

**Comment by 00-Evan** [comment]
Electrical enemies resist lightning, which includes the bright fist. Prismatic light is unrelated.

**Comment by Lyx0527** [comment]
> Electrical enemies resist lightning, which includes the bright fist. Prismatic light is unrelated.

![IMG_20230311_000153](https://user-images.githubusercontent.com/118305192/224364729-4ebedb97-361e-4f72-8852-206478e4b90c.jpg)

**Comment by Pr0methean** [comment]
Then the fist's description should probably say something like "pure lightning" instead of "pure light energy".
