### ISSUE TITLE
Farsight not interacting with darkness challenge

### ISSUE THREAD

**Issue by andreasmjg** [00-Evan/shattered-pixel-dungeon#1268]
Hi, it seems like huntress's farsight ability does not impact the Into Darkness challenge. Is this intentional? If it is, it should probably be noted in one of the descriptions.
Thanks!
Andreas 

![Screenshot_20230310-192532_Shattered Pixel Dungeon](https://user-images.githubusercontent.com/34312687/224411980-3048c395-fac5-4f4b-9d93-e076db5bbd1a.png)

![Screenshot_20230310-192522_Shattered Pixel Dungeon](https://user-images.githubusercontent.com/34312687/224412020-59322793-f9bc-4427-9424-7aa9c05cc5d9.png)

**Comment by andreasmjg** [comment]
![Screenshot_20230310-193924_Shattered Pixel Dungeon](https://user-images.githubusercontent.com/34312687/224412213-b83c3811-7a8b-4163-beb3-418de7206311.png)

**Comment by 00-Evan** [comment]
You're on a dark level feeling, which halves vision range. Default vision range for into darkness is 2, so a dark level with that challenge has a vison range of 1. Farsight then adds a +75% boost, increasing it to 1.75, which is rounded down back to 1.
