### ISSUE TITLE
Scroll of Retribution damaging Antimagic champions

### ISSUE THREAD

**Issue by Dimedime-d** [00-Evan/shattered-pixel-dungeon#1269]
Antimagic enemies were made immune to psionic blast scrolls a while back. But they can still be damaged by the weaker Retribution scroll. They should also be immune to Retribution.

I cast retribution from a spellbook and noticed it damaged, weakened, and blinded an antimagic prison guard. Psionic blast would've had no effect, happened in 2.0.0 beta-9.

**Comment by 00-Evan** [comment]
fixed in commit ad4e5ef898945b09b4d7d4c6a3998e67a88d294a
