### ISSUE TITLE
Altar room misaligned 

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1270]
I don't know if this intended, but it looks odd, that the altar room is not aligned correctly.
Seed: ZYS-TKZ-XVM

![Screenshot_2023-03-12-13-56-51-488_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/224546150-4edda0bc-2ca0-4b96-babc-71f1fd467cdf.jpg)

**Comment by 00-Evan** [comment]
This is intended. The altars are offset from the entrance door, and in the case where they spawn near to a wall one statue is skipped.
