### ISSUE TITLE
Throwing Stone description

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1273]
Unlike the Throwing Club and the Throwing Hammer, the description of the Throwing Stone misses to mention that the weapon is non-sticky. However, this is the only reason why it is not strictly worse than the Throwing Knife or the Throwing Spike. For consistency with the other weapons that should be mentioned.

**Comment by 00-Evan** [comment]
fixed in commit 46421c78fc34bafc37447371d31c6b46c92ca1fb
