### ISSUE TITLE
App not installed.

### ISSUE THREAD

**Issue by overtube** [00-Evan/shattered-pixel-dungeon#1274]
The package conflicts with an existing package by the same name 
![6b71e198-55f7-4c6b-bd19-7833faa5d16a](https://user-images.githubusercontent.com/15115920/225211291-7266de44-2391-4004-b862-434e84a8166f.png)

**Comment by 00-Evan** [comment]
Is your previous installation of the game from F-Droid? They are an unofficial distribution of the game which uses its own developer certificate, meaning that you cannot update it interchangeably with the builds I provide here. If you want to switch you will have to uninstall the game first.
