### ISSUE TITLE
no buff displayed for duelist's patient strike

### ISSUE THREAD

**Issue by mmacura311** [00-Evan/shattered-pixel-dungeon#1275]
The patient strike ability does not display any buff icon (as opposed to eg strengthening meal that displays a buff icon after eating something). At this point I'm not even sure that it works, as there is no way to tell.
Also I do not know how long should I wait, eg I see a monster and wait few rounds without a movement, no buff icon. Or is there some other action necessary (eg taking damage first then wait?)
I use SPD 2.0 from google store.

**Comment by mmacura311** [comment]
also when I compare this to other characters, it is less clear rally.
As far as I recall:
warrior's "hold fast" does show a buff when not moving
mage's "shield barrier" does show a buff that shield exists
rogue's "sucker punch" does not show anything. Probably the internal mechanics are different? it is also per-monster and per-hit dependant so makes sense not to have generic buff icon I guess
huntress' Followup Strike it's no buff (isn't it a debuff on the monster?), but Nature's Aid is a buff.

**Comment by 00-Evan** [comment]
I opted to not give this a buff icon for the same reason followup strike has no icon, it's a pretty direct trigger that gets spent immediately (attacking right after the wait action), and giving it an icon would result in a lot of visual noise whenever you wanted to rest for any other purpose, especially later in the game as the talent becomes less relevant.

**Comment by mmacura311** [comment]
understood.
just a follow-up question to be explicit - is it sufficient to wait 1 turn for this to activate?
