### ISSUE TITLE
Duelist does not show levitation animation

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#1277]
This is on android, v2.0.0. Duelist hero did not show levitation particles, mage hero does. I have not done another duelist run yet so I cannot confirm if this was a one-off thing.

![Screenshot_20230314-203544](https://user-images.githubusercontent.com/45757529/226060697-268bad69-3cc8-4230-85f2-5b4647f05fbb.jpg)
![Screenshot_20230317-155826](https://user-images.githubusercontent.com/45757529/226060829-c08bf195-e045-421e-a066-e656eb754a1e.jpg)

**Comment by 00-Evan** [comment]
This isn't tied to the hero class, it's a purely visual error. Will look into this but i've never been able to reproduce it.

**Comment by 00-Evan** [comment]
Was able to find a cause for this, relating to necromancer logic (the skeleton in your FOV tipped me off toward that)

**Comment by wknoben** [comment]
Decent! Glad this was helpful
