### ISSUE TITLE
Metaprogression?

### ISSUE THREAD

**Issue by max2007-69** [00-Evan/shattered-pixel-dungeon#1278]
Hello, I would like to inquire about future plans for the game. Are there any plans to add metaprogression for different classes (warrior, mage, huntress, rogue, duelist)? Personally, I have an idea to implement this idea, to make conditional levels from 0 to 3, where 0 is the initial level, everything matches the class description, as you get levels (for example, for killing bosses) the list of starting items and/or the list of items identified from the start is expanded for the class.

**Comment by 00-Evan** [comment]
I have no plans to add metraprogression beyond cosmetics or the existing tutorial features like really simple character unlocks. Adding real metaprogression would change the genre of the game. Shattered is a Roguelike, not a Roguelite.
