### ISSUE TITLE
Monk does not correctly receive extra energy with ring of force

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#1280]
The duelist monk does not get 150% more energy when she is using a ring of force, with "Unencumbered Spirit +3"

The description here says "She also gains _150% more energy_ if she has no weapon (or ring of force)", but this is not the case.

```
if (hero.buff(RingOfForce.Force.class) == null && points >= 3){
    enGainMulti += 1.50f;
}
```

**Comment by 00-Evan** [comment]
This is intended, you're misreading that description text.

It's: 150% energy if no (weapon or ring of force)
Not: 150% energy if (no weapon) or (ring of force)
