### ISSUE TITLE
Evil eye laser bug

### ISSUE THREAD

**Issue by Diegovica643** [00-Evan/shattered-pixel-dungeon#1282]
I've been having a bug while escaping the laser from the evil eyes. 
Whenever they start charging I try to get out of sight to prevent taking the damage, but every time I start receiving melee damage from an invisible source until I go back to the evil eye, it fries me with the laser and it's not charging the attack anymore.
I've got a screen recording example of the problem but I'm not sure how/if I can upload it here

**Comment by Diegovica643** [comment]
Forgot to mention I'm on the beta branch

**Comment by 00-Evan** [comment]
Update your beta, this has already been fixed with an amended v2.0.1 release.
