### ISSUE TITLE
"a annoying curse" should be "an annoying curse"

### ISSUE THREAD

**Issue by Pr0methean** [00-Evan/shattered-pixel-dungeon#1286]
![Screenshot_20230328-202014](https://user-images.githubusercontent.com/4961925/228602451-21472d40-e697-4b3c-8410-efb7ba3f5c4d.png)

A way to avoid needing logic for "a" and "an" would be to use "a curse of...".

**Comment by 00-Evan** [comment]
I'm fine with small grammatical errors due to variable text like this.
