### ISSUE TITLE
add change log to fdroid

### ISSUE THREAD

**Issue by treakiandroid** [00-Evan/shattered-pixel-dungeon#129]
hi,

first of all thanks a lot for that grate app, its much fun to play, i had only one problem that the german text was to long to be displayed on one ui, but I don't remember anymore...

also somehow the audiofx app from change mod keeps crushing while playing shattered pixeldungeon bit i guess thats not a bug in it here.

but it would be realy grate of you could add a change log page to that fdroid repository.

thanks in advance

**Comment by 00-Evan** [comment]
Shattered does already have a changelog built into the app, is that good enough for you?

You can access it on the bottom right of the main menu.
