### ISSUE TITLE
v2.0.1: sync error, then continued in locked room

### ISSUE THREAD

**Issue by derekdifilippo** [00-Evan/shattered-pixel-dungeon#1292]
Hi Evan

Context:
+ v2.0.1
+ received a sync error from the app (improper shutdown)

Action:
+ continued game

Result:
+ Started in a locked two-chest room.
+ Screenshots attached.

Note that the four other games I have are not exhibiting the same behavior, which makes sense since they've been on ice for a few days.

![Screenshot_20230402-153022](https://user-images.githubusercontent.com/11355157/229382854-fb45b48b-9b6b-41cb-8ae3-6084f5dd2167.png)
![Screenshot_20230402-153047](https://user-images.githubusercontent.com/11355157/229382856-297a2843-08a5-4d89-8e9f-b783697ecdad.png)
![Screenshot_20230402-153326](https://user-images.githubusercontent.com/11355157/229382857-36442595-d86f-49a0-9160-023db5794ac9.png)
![Screenshot_20230402-153830](https://user-images.githubusercontent.com/11355157/229382939-7bd26151-988e-4e6e-bb52-f8a689401b7f.png)

**Comment by 00-Evan** [comment]
As the game states, this occurs when Shattered is killed before it can properly write save data, which can lead to unusual situations. In this case the file containing your hero info was saved correctly but the file containing level state was not. There is nothing the game can do about this as it's up to the device whether things get saved and whether the app gets suddenly terminated.

**Comment by derekdifilippo** [comment]
👍👍
