### ISSUE TITLE
Spirit Bow doesn't appear to actually decrease its strength requirement as it upgrades

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1295]
I was attempting to complete a run with under 10 strength for the first time, and decided to wait until my bow was +3 (at huntress level 15) before equipping a cursed ring of might to bring my strength down to 8 (or 10-2). As the bow is +3, it claims to take 8 strength to use, and yet I've found myself unable to land any sneak attacks at all, which is usually a result of a weapon being too heavy. Perhaps I'm overlooking some other factor, but it seems to me that the bow's requirement isn't actually decreasing like its description implies

https://user-images.githubusercontent.com/101913866/230130005-1df1fa72-db30-4efc-b12a-7c4ae4460357.mp4

**Comment by 00-Evan** [comment]
Looks like this is happening because of some level confusion. The arrows are using their level (always 0) when determining str requirement, instead of the bow's level.
