### ISSUE TITLE
Brawler's stance has no range attack is intended? 

### ISSUE THREAD

**Issue by YouIG** [00-Evan/shattered-pixel-dungeon#1297]
![Screenshot_20230408_113527](https://user-images.githubusercontent.com/97358481/230699737-4938987c-1cb1-4d66-b62e-d22409905763.png)
![Screenshot_20230408_113502](https://user-images.githubusercontent.com/97358481/230699712-bbb5c375-ff64-4a9c-a2ec-68f38227240e.png)
![Screenshot_20230408_113512](https://user-images.githubusercontent.com/97358481/230699728-bd74e21e-4d34-4eab-926b-ca42af566868.png)

When the brawler's stance on, there is no attack button with spear. 

![Screenshot_20230408_113523](https://user-images.githubusercontent.com/97358481/230699731-9e940592-cdd6-4bbe-85e6-791c0dc325e3.png)

But when the brawler's stance off, shows attack button. 

is this intended mechanism?

**Comment by 00-Evan** [comment]
That is intended. With brawler's stance you are attacking with the ring, not the weapon.

**Comment by YouIG** [comment]
I got it. Thank you Evan!
