### ISSUE TITLE
Casting Scroll of Transmutation on an artifact eventually deletes the artifact

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1298]
Ring of Wealth can generate enough scrolls to make this happen.

It is speculated that this is SPD trying to avoid creating duplicate artifacts.

* https://www.reddit.com/r/PixelDungeon/comments/12gg1ho/artifact_just_disappeared/

**Comment by 00-Evan** [comment]
See #1250

Please do not re-post other people's issue reports from different places.

**Comment by rpdelaney** [comment]
> Please do not re-post other people's issue reports from different places.

I wouldn't, and didn't 👍
