### ISSUE TITLE
Story/interaction mode

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#130]
It would be cool if there was a story mode or if the game had more story components. For example if the player could go upstairs from the first floor and see why he even got down. Or if you could really talk to some charackters with preconsteucted answers, you know, maybe something like in Andor's trail (I don't like this game but I had no other examples).  It also would be very cool if you had the option to interact with the bosses. Not maybe the goo but the others. I don't mean that there should be a way to pass them without killing, but this option would make the game more interesting.

**Comment by 00-Evan** [comment]
I agree, and more story is something I want to integrate with the game, but it is something I plan to do gradually.

I'm closing this as it's a none-technical suggestion, but I am planning on implementing more story.

**Comment by OffifialMITX** [comment]
Will there be a forum or a suggestion board so the people can tell their
ideas?

2016-10-19 18:09 GMT+02:00 Evan Debenham <notifications@github.com>:

**Comment by 00-Evan** [comment]
The most active community is the pixel dungeon subreddit. If you want to talk with me directly, you can also email me: Evan@ShatteredPixel.com
