### ISSUE TITLE
Emptyhanded w/ Full Pack & Can't Pick Up Weapon

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1304]
I stepped on a disarming trap & had to pull something out of my backpack & put it on the ground in order to wield my weapon again. Kinda silly when it seems like the hero should be able to simply lean down & grab it w/out having to fuss w/ their bag. Thankfully, no monsters were watching. I raised a similar issue in #1211. If the wielded slot behaved as a pseudo-backpack slot perhaps both issues could be addressed.

I need to look more closely @ it but I think the champ's 2ndary weapon slot may already work this way. Or, hopefully, it doesn't have the same issue since it seems like a repurposed backpack slot.

**Comment by 00-Evan** [comment]
This is intended, you are not able to collect items into equip slots.
