### ISSUE TITLE
Twin Upgrades Reveals Hidden Upgrades

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1305]
![Screenshot_20230414-120327](https://user-images.githubusercontent.com/91638992/232176694-47377035-e5cd-42ce-a57f-65edc3dc0aa2.png)

The hammer is un-ID'd but I can tell it's +2 thanks to Twin Upgrades. The champ's primary & 2ndary weapons are both quickslotted.

The shield is ordinarily +1 but the blue coloration & number change gives it away. Equipping a +1 flail as primary shows the shield @ +1 but w/ normal coloration.

**Comment by SujayDalai02** [comment]
Let's assume you have twin upgrade talent at +3.
![Screenshot_2023-04-15-12-39-48](https://user-images.githubusercontent.com/130607815/232194465-9bfa9be4-7fea-4436-9e02-f64c1da8ccf6.png)
But according to description, there should be at least 1 level difference between the primary and secondary weapon for twin upgrades to be applicable. Which is true when you use hammer+2 as primary and shield+1 as secondary. But if you use both weapons(flail and shield) at +1 level, there's no level difference between them for twin upgrades to balance. So, when you use flail+1, it shows the original upgrade level of shield(which is +1) and when you use hammer +2, it shows the increased level of shield(which is +2, same as hammer balanced by twin upgrades) in blue.

**Comment by 00-Evan** [comment]
I'm fine with allowing this. You still have to risk the item being cursed, and there are already plenty of ways to soft-ID something after equipping it.
