### ISSUE TITLE
Antimagic Mobs Immune to Heavy Blow's Debuffs

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1306]
![Screenshot_20230414-122815](https://user-images.githubusercontent.com/91638992/232177051-38969070-fc1f-4108-afc1-3ea6c649e776.png)

![Screenshot_20230414-122821](https://user-images.githubusercontent.com/91638992/232177066-144cae2b-f319-4d1f-9988-5ba6ad0ce05e.png)

I got the surprise attack Heavy Blow when the golem stepped around the tall grass. I understand the debuffs are ordinarily considered magical (e.g., shaman bolts & wand of corruption) but shouldn't they be mundane in this case??

On a side note, I'm doubting the shield's applying its dmg blocking as a 2ndary weapon. @ +6 (thanks to Twin Upgrades) it should be conferring an extra 0-10 dmg mitigation to attacks but it really doesn't feel like it considering the hits my hero's been taking. Of course, I've no way of determining this for certain but I thought I should mention it. Champ's description says she can dual wield & the shield's blocking comes from wielding it.

**Comment by 00-Evan** [comment]
For the moment this is working as intended, but I do agree that mixing magical debuffs and mundane sources can get confusing quickly. I think there's a good chance that I'm going to charge up the heavy blow effect a bit in v2.1, and will consider options then.

As for your second point, that's intended. You do not get the blocking benefit from shields unless they are your primary.
