### ISSUE TITLE
Patient Strike on Duelist maybe not working?

### ISSUE THREAD

**Issue by SujayDalai02** [00-Evan/shattered-pixel-dungeon#1307]
![Screenshot_2023-04-15-12-34-48](https://user-images.githubusercontent.com/130607815/232195476-e6832b0e-f903-4f58-b379-6faaf3eb67d3.png)
As you can see, I'm using the rapier at strength 11. My tier 1 talent, **Patient Strike**, is at **+2**. That means, if I wait long enough, it should deal damage more than 8 on my normal melee attacks(at least sometimes). But I haven't seen it dealing damage more than 9(maybe 1 more damage from excess strength). I have even waited for like 25-26 turns before attacking. So I think, it maybe not working.

By the way, all of my attacks were on the cave rats, so I should have dealt at least 10 damage(assuming rat have 0-1 damage resistance), but none of my attacks dealt more than 9 damage.

**Comment by 00-Evan** [comment]
Patient strike does not store more damage the longer you wait. After one wait action you'll get an extra 1-2 or 2 damage, that's it. Shattered uses triangular distributions for things like damage rolls, so while hitting 10 damage is definitely possible it would be quite unlikely.
