### ISSUE TITLE
about automatic pathfinding

### ISSUE THREAD

**Issue by crosage** [00-Evan/shattered-pixel-dungeon#1308]
I clicked on the crystal door when I was one block away from the piranha, but the automatic pathfinding let me go in the direction close to the piranha

![029ECA78DE8CEECC53550EA3694AD7D1](https://user-images.githubusercontent.com/90540469/232265988-3657927b-93f3-4e4a-aeb9-f2de6be9d6ed.jpg)

seed：
![FD43028B73871FF230C8AE161CCB8F23](https://user-images.githubusercontent.com/90540469/232266093-7dc6b89f-33a9-4bc9-b891-c38de6f87e8a.jpg)

**Comment by crosage** [comment]
> It's hard to be sure from your screenshot, but it seems like the path to the left is the shortest way to the room with the crystal door, and so that's the path the game decided to take you to get there. You need to be careful with where you move when you're in a piranha room.

maybe a smarter automatic planning of paths? Longer but avoids piranhas.

**Comment by 00-Evan** [comment]
Pathfinding does not make decisions for the player about enemy danger, as it would simply make the system more complex and confusing. It will always take the shorted valid path.
