### ISSUE TITLE
Ranged mobs melee-striking from distance instead of ranged attacks!

### ISSUE THREAD

**Issue by SujayDalai02** [00-Evan/shattered-pixel-dungeon#1309]
I nearly missed it, but sometimes when I'm range-striking ranged mobs with spirit bow or damage-type wands or missile-type weapons(i noticed it on hunter quite a few times but only once using mage), the mob doesn't range-strike, but instead, they melee-strike me from distance...

For example, 
- dm-100 not zapping me
- cave spinners not shooting webs but biting me from distance and poisoning me
- gnoll shamans not debuffing me with magic bolts
- dm-200 and dm-201 not spraying their gas jetsprays at me
- elementals not using their special ranged magic bolt
- dwarf warlock not degrading my items withagic bolts
- evil eye not using laser beam
- scorpio doing nothing, just standing while I kill it

Fix it please. Thank you.

**Comment by 00-Evan** [comment]
Were these enemies projecting champions? As of v2.0.1 projecting champions with ranged attacks will correctly use their longer-ranged melee attack if they can see you but can't hit you with their ranged attack.

**Comment by SujayDalai02** [comment]
No, i wasn't doing any challenges, it was just a normal game.

**Comment by SujayDalai02** [comment]
I first found it when i was playing as hunter... nearly missed it, definitely saw it happen with dm-100.
 Then I went for some new games as mage and hunter to see if I was wrong, but I was right.

**Comment by 00-Evan** [comment]
I see. You are the only person who has reported this, so it should be a fairly specific circumstance. Could you provide me a screenshot of a situation where the bug occurs?

**Comment by 00-Evan** [comment]
I've gotten a video report about this from #1311, so this is definitely happening for evil eyes at least. Any additional reproduction steps would be appreciated though, especially for other enemies.

**Comment by 00-Evan** [comment]
After further inspection, I realize that #1311 is referencing a bug which was already fixed in a later iteration of v2.0.1, so there isn't currently any evidence of this issue occurring.

**Comment by 00-Evan** [comment]
I'm closing this report for no under the assumption that the reports are from versions of 2.0.1 before this fix was applied. Will be happy to re-open if anyone can reproduce the error on v2.0.2 or later.
