### ISSUE TITLE
Disable vibration in the powersafe mode

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#131]
Of course it wouldn't save as much power but it still would be helpful.

**Comment by 00-Evan** [comment]
I'm curious if this actually would save any battery.

I'll look into it, if there's evidence that it does, then sure.

**Comment by 00-Evan** [comment]
I've decided against implementing this.

Power Saver isn't aimed at making as many changes as possible to reduce power usage, just the big important ones. Most phones also have a battery saver mode which turns off vibration anyway.
