### ISSUE TITLE
Certain items that are required sometimes don't generate/ Unidentified brews don't tell you if they're harmless when thrown

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1310]
In a run, I found every potion I could, and I doing the wandmaker quest for the embers. I had tested most of my potions already, and I hadn't identified frost. The only potion in the level that I hadn't identified yet must've been frost right? But when I threw it, it literally did nothing. It didn't even say "the flash shattered and the liquid splashes harmlessly" There was literally no message about the potion being thrown. I did make it into a brew, because I thought it might one-shot the elemental, in which case, this is a problem with the brews, or it was a potion of flash freeze and it just didn't work. Also, in the same run, the last ceremonial candle was in the chasm chest, where you need the potion of levitation to get the chest across the chasm. Not sure if that's a bug, but it's annoying.

**Comment by 00-Evan** [comment]
The embers wandmaker quest does not generate a potion of frost. Using ice against the elemental is very helpful but not required for defeating it.

As for potion throwing did the potion land outside of your FOV? You only get a message about a potion splashing harmlessly if you actually see it happening.

It is intended that candles can spawn as the reward to a challenge room.

**Comment by Howdidibreakit** [comment]
It wasn't out of my fov btw
