### ISSUE TITLE
About necromancer's summon and memory

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1318]
When a necromancer summons, he does not remember the position of the hero he sees. Just like in the video, he does not remember the position where the hero appears at the door

\<video removed>

**Comment by 00-Evan** [comment]
I have edited your report to remove the video, as it was not from Shattered Pixel Dungeon, please do not report issues in other Pixel Dungeon verisons. I was able to reproduce this in Shattered however.

**Comment by 00-Evan** [comment]
Fixed in commit: 8ce54149edc5d8ef8558dd91f515d9a5bb7115a3
