### ISSUE TITLE
Stop sad ghost bosses from spawning in hidden areas.

### ISSUE THREAD

**Issue by 133794m3r** [00-Evan/shattered-pixel-dungeon#132]
I don't know how hard this is to do, but I at least 10-20% of the time have the bosses hidden in some room that's not visible and unless I have a potion of mind vision I have to spend a ton of time searching the whole floor to find it as magic mapping doesn't reveal "hidden" rooms.

**Comment by 00-Evan** [comment]
Magic mapping does reveal hidden rooms, and this interaction is intended.

I do want to make it a bit easier to anticipate where hidden rooms are,  but that wouldn't result in a direct change to sad ghost mechanics.

**Comment by 133794m3r** [comment]
The key here is to stop them from spawning in some place where it's hidde nand thus requires time to try to find it should be a simple test to see if a room is "found" and only spawn there or atleast I'd think it'd have been that way.

**Comment by 00-Evan** [comment]
I understand your point, but don't agree that hidden rooms as they are now should be excluded from enemy spawning, either in a specific or general case.
