### ISSUE TITLE
Champion's weapon swap doesn't change quickslot weapon

### ISSUE THREAD

**Issue by dabramov1** [00-Evan/shattered-pixel-dungeon#1321]
When playing the Champion, using the purple weapon swap button doesn't change the weapon in the quick slot for the duelist's weapon ability. It does change the charges available to match the different weapons, but the icon and the ability do not change. At least, this is the case for the combination of spear and shield. 

![Screenshot_20230420_212836](https://user-images.githubusercontent.com/13987849/233534876-ad860276-e45b-4d82-8802-1fb6d210b6ed.jpg)

![Screenshot_20230420_212906](https://user-images.githubusercontent.com/13987849/233534903-38dfa127-bdd6-4edc-aeb4-29aed273634b.jpg)

**Comment by dabramov1** [comment]
Possibly relevant, I was using a ring of force with "brawler stance" enabled.

**Comment by 00-Evan** [comment]
This is intended. You can use the abilities of both your primary and secondary weapon, so the game expects you to have both quickslotted.

**Comment by dabramov1** [comment]
Why do the charges available change? I.e. if the quick slot is static, the the charges should always reflect the charges available for that weapon. Instead, the charges available for the spear showed on the quick slot icon of the shield.

**Comment by 00-Evan** [comment]
Charges are tied to the slot, not the weapon, so by swapping them you're also swapping which weapon gets the charges in the primary slot.
