### ISSUE TITLE
tengu smoke bomb

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1322]
I used timekeeper's hourglass during Tengu fight.  I walked into a smoke bomb and, seeing the action button for a smoke bomb,  tried to pick it up.  I got a message - "you don't have room to pick up smoke bomb".  However I have one empty slot in my backpack.  An I supposed to be able to pick up the smoke bomb?

**Comment by 00-Evan** [comment]
That is intended, Tengu's bombs cannot be picked up.

**Comment by Pr0methean** [comment]
The error message is misleading.

**Comment by 00-Evan** [comment]
When you attempt to pick it up the game text reads:
```
It's stuck to the ground, you can't move it!
You can't carry: Smoke Bomb
```
How is that misleading?

**Comment by TheYsconator** [comment]
> When you attempt to pick it up the game text reads:
> 
> ```
> It's stuck to the ground, you can't move it!
> You can't carry: Smoke Bomb
> ```
> 
> How is that misleading?

I don't think it is, as is.

As an alternative you can consider "It's stuck to the ground; you can't pick it up!" This has the content of both lines (in just a single line), so people will not miss the line above. However, it's a bit wider, and I don't know if this version causes issues in relation to fitting on the screen.

**Comment by SujayDalai02** [comment]
@TheYsconator I think @00-Evan is right. It might have been misleading if it was only the line "You can't carry : Smoke Bomb". But with both lines being displayed, it totally makes sense.

**Comment by TheYsconator** [comment]
@SujayDalai02

> > How is that misleading?

> I don't think it is, as is.

I don't see why you're trying to convince me; we already agree.

**Comment by SujayDalai02** [comment]
@TheYsconator bro chill, I'm not trying to convince you. I'm just saying that I also agree to it.
