### ISSUE TITLE
Bug of turn and speed enhanced weapon

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1324]
If the turn display is not an integer(as figure), 
![IMG_20230425_064721](https://user-images.githubusercontent.com/118305192/234132905-34e9bdab-36e8-463f-9cd2-5e1f3f3a93fe.jpg)
hero summons wraith , and uses a spear with speed enhanced to attack the wraith, will immediately receiving two attacks. 
If it is an integer, there will be no bugs. 
This may be a rounding or priority bug

**Comment by 00-Evan** [comment]
Fixed in commit: 9cd16948ec093445037bdd04989af3b2f6296b9b
