### ISSUE TITLE
About Ascension, Damage Resistance, and Enchantment

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1325]
I noticed that the interaction between kinetic enchantment and damage resistance has been improved. But there are still unreasonable interactions between other enchantments and damage resistance.
Taking sniper shooting a rat as an example: Grim enchantment will never trigger; Even if the damage is not enough to kill the mouse, the corrupting enchantment will trigger.
In my opinion, directly increasing the health of enemies instead of giving them damage resistance can solve these problems. For example, rats have 80 HP instead of 90% damage resistance. This change can also solve the problem of bats being able to recover all their HP with just one hit.

**Comment by Lyx0527** [comment]
And Slimes are too difficult to defeat

**Comment by 00-Evan** [comment]
Slimes are the exact reason why I don't scale enemy HP up, as otherwise they would become extremely difficult on ascension. Scaling damage down causes fewer problems overall. Will consider the specific interaction of grim, but I'm not planning to change this overall.
