### ISSUE TITLE
Large enemies can still appear in hallways

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#1326]
![Screenshot_20230422_213914.jpg](https://user-images.githubusercontent.com/44932833/234391732-37bf43b7-5a18-4dfc-8864-81eb1e437549.jpg)

I recently encountered a giant skeleton in a hallway. I am not sure what happened, but I think a large necromancer teleported it there.

**Comment by 00-Evan** [comment]
Fixed in commit: aed47bc3a35b145e14ccb205baf1bf9ee07f79ba
