### ISSUE TITLE
Suggestion: Themed chests

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1328]
The fact that all chests are the exact same in every section of the dungeon is kinda bland. You don't have to do any sprite work btw, if you could send me the chest image I could absolutely make the sprites by myself and send them to you. I've had some bad ideas in the past, but this one is pretty good I think.

**Comment by 00-Evan** [comment]
Thanks but I'm not currently looking for any spritework offers. Different chest visuals might be interesting, but I worry that it might be difficult to come up with 5 sprites for each chest type that still clearly communicate what type the chest is.

**Comment by Howdidibreakit** [comment]
I FOUND EM!
![themedchest_0000_Sewer](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/255cafbf-292c-48ad-8601-ed3c24db6dd8)
![themedchest_0001_City](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/06016b7b-de51-46f1-a5bd-f11521b570c6)
![themedchest_0002_Layer-1](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/b7862eef-298a-4844-ac1d-acad7274d30b)
