### ISSUE TITLE
Bug of rest during ascension

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1331]
The green characters will appear repeatedly until the hero returns to the 19th floor.
5, 10, 15 have the same bug

**Comment by Lyx0527** [comment]
![Screenshot_20230428_063613_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/235006329-5414f5ff-bed7-4cf3-a99f-2ed0945096a6.jpg)

**Comment by 00-Evan** [comment]
Fixed in commit: fa828c402ac81e070ef47b3b40d1f621c985346d
