### ISSUE TITLE
Kinetic weapons can conserve damage by killing allies

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1333]
Perhaps changing the description of kinetic enchantment would be more reasonable

**Comment by 00-Evan** [comment]
it is intended that kinetic does not build on allies. I'll change the functionality, not the description.

**Comment by 00-Evan** [comment]
Fixed in commit: 70340c335b79048bf7634127c90332ae12d97e62
