### ISSUE TITLE
Bat Quest - Duelist - Special Attack : Does not become blood-stained

### ISSUE THREAD

**Issue by F0x186c39** [00-Evan/shattered-pixel-dungeon#1334]
**Issue**:
Killing a bat with ~~champion's (~~ duelist ~~)~~ "guaranteed to hit" special attack (pierce) does not transform pickaxe into blood-stained pickaxe.

**Player Expectation**:
Pickaxe to transform upon killing bat.

**Steps to reproduce**:
1. Play as duelist ~~, and choose champion (unknown if champion is a factor)~~
2. Equip pickaxe on primary slot
3. Damage a bat until it is low health, and ensure that weapon has enough charge
4. Kill bat using special attack (pierce)

**Comment by F0x186c39** [comment]
Regular attack checks Boolean `bloodStained`  in `proc` [L143](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/quest/Pickaxe.java#L143)

Suggestion, check for `bloodStained` within `else` block beginning at line [216](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/quest/Pickaxe.java#L217)

**Comment by 00-Evan** [comment]
Thanks for the report, I'll look into this. Please do not make code suggestions.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this, using pierce on a bat correctly applies the blood to the pickaxe.

A couple things to note:
- The blood effect is applied in proc(), which occurs both on regular attacks and the pierce ability (which piggybacks on melee code)
- If the pickaxe has an enchantment, the visuals for that will override the blood visuals.
