### ISSUE TITLE
GreatCrab can be hit by flail's "surprise attack"

### ISSUE THREAD

**Issue by F-LTP** [00-Evan/shattered-pixel-dungeon#1335]
When the GreatCrab chased me through the door/ I got invisibility, I could hit GreatCrab with my flail.
Is it a bug or special design for this?

**Comment by 00-Evan** [comment]
The great crab's blocking effect is tied to whether it can see you, not specifically whether you can surprise attack. Although in most cases these two are equivalent.

**Comment by SujayDalai02** [comment]
@F-LTP um, I think it was a totally normal hit, and NOT a ***surprise attack***.
