### ISSUE TITLE
Dimming quick slot and inventory buttons while player moving can be annoying to eyes

### ISSUE THREAD

**Issue by starwindz** [00-Evan/shattered-pixel-dungeon#1337]
While the player is moving, the quick slot and inventory buttons at the bottom right of the screen become dimmed. This can be kind of flickering, which can be annoying and eye-straining at times. Where is the related source code for this? And could you please keep the slot and buttons from dimming (blurring) while the player is moving?

**Comment by starwindz** [comment]
I understand very well what you are describing. Thank you, But I generally use the keyboard like traditional roguelikes on desktop. If I press the arrow keys of the keyboard quickly, UI such as quick slot or item slot blinks quickly. This is clearly eye-straining to me.

**Comment by 00-Evan** [comment]
I'm not willing to remove the effect entirely, it's quite important for mouse and touch input, but I do agree that it is quite strong currently. The effect could probably be made less pronounced, which would reduce the eye strain effect from the flicker significantly.

**Comment by starwindz** [comment]
can you give some information about how this feature is actually implemented in development version?

**Comment by 00-Evan** [comment]
The button icons now become partly transparent in a similar way to existing buttons and item slots when they become inactive: 
![image](https://user-images.githubusercontent.com/2347603/236367309-657cdac8-b709-4289-b5c8-abc7248ff45d.png)

**Comment by 00-Evan** [comment]
Added in commit: e10189928e20f69a3a388b872a25205c4e630415
