### ISSUE TITLE
Studded gloves more accurate than normal weapons?

### ISSUE THREAD

**Issue by SujayDalai02** [00-Evan/shattered-pixel-dungeon#1338]
I've killed the sewer snake using normal attacks(not surprise strike and without any ring of accuracy) with studded gloves.

So I was wondering if it's more accurate to hit a evasive snake. If it is, there's no mention in the in-game weapon description. If it's not, then please explain how it was possible to hit snake with normal attacks?

And one more question. It says, "It is a very fast weapon". How fast is it compared to normal weapons?

By the way, this occurance is rather rare but I'm sure you can re-create this.

**Comment by 00-Evan** [comment]
Studded gloves have 2x attack speed and standard accuracy. If you want to ask me questions it is better to email me, this is a place to report technical issues with the game.
