### ISSUE TITLE
Improve scroll of psionic blast

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#134]
I think that such a powerfull scroll should be given a special effect like longer animation duration and something like a zoom blur if you know what I mean.

**Comment by 00-Evan** [comment]
Shattered's engine doesn't have the capability for many advanced visual effects.

Furthermore this isn't the place to make none-technical suggestions, please email them to me in future.

**Comment by OffifialMITX** [comment]
Why was this not a te chnical suggestion?

**Comment by 00-Evan** [comment]
it's to do with the visual design of the scroll of psionic blast, which is not a technical element. A technical element might be, for example, a possible concern regarding performance of the visual effect, or a bug regarding the visual effect.

**Comment by OffifialMITX** [comment]
Ok, I got it.
