### ISSUE TITLE
Disintegration traps can kill the hero multiple times

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1340]
![Screenshot_20230427_122724_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/118305192/236097556-bcc76653-b0e9-40cf-a93b-6ad8db541a50.jpg)
I used hourglass to pick up the gold coins on the disintegration traps and wanted to use chains to leave the room. But before chains could pull me out of the room, I was killed by the disintegration trap. 
It shows many times I have been killed by disintegration trap and gain badge of Deadly Misstep. And after resurrection, the game stuck until I reload.

**Comment by Lyx0527** [comment]
https://user-images.githubusercontent.com/118305192/236109854-30b22bb6-58c5-4bb6-9b54-bfb5baa25d3e.mp4

**Comment by 00-Evan** [comment]
Fixed in commit: abf3cd5a0d4bca96eb9d19bb6f1c0bce3fd05c99
