### ISSUE TITLE
When elastic enchantment is applied to different thrown weapons

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1341]
If boomerang flies back and hits the enemy's back, force cube hit the enemy's diagonal rear, the enemy will still be pushed away from the hero, which is counterintuitive.

**Comment by Lyx0527** [comment]
https://user-images.githubusercontent.com/118305192/236130278-f38e9bb7-8982-42a1-87e8-4ccc20cf209a.mp4


https://user-images.githubusercontent.com/118305192/236132412-7650b941-3cb4-4aee-a452-0374514c1206.mp4

**Comment by 00-Evan** [comment]
This is working correctly, the hero is the source for the elastic enchantment.
