### ISSUE TITLE
Scorpios run TOWARDS you when terrified

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1342]
For whatever reason, when you use terrify on a scorpio, it will run towards you, until it gets adjacent, then it runs back a tile. That, or the strange geometry of the map is doing it, since i'm the path of the only way out.
![image](https://user-images.githubusercontent.com/118551559/236289890-5d827cde-f612-4625-ab3b-62f9ba8b3ef1.png)
Sidenote, attacking around like. 
![image](https://user-images.githubusercontent.com/118551559/236290066-60e9be25-f7cd-434d-835e-5b3c515f167f.png)
That kind of geometry with ranged or magic attacks is super jank. When it's vertical like in the picture, it works most of the time, but for whatever reason, when it's horizontal it doesn't work

**Comment by Howdidibreakit** [comment]
ALSO ALSO 
![image](https://user-images.githubusercontent.com/118551559/236290473-14e7f871-2f45-4e53-852c-3d414a3de7f8.png)
He will not move from that spot, and because he has no melee, he just can't hurt me in this position, retreating pathfinding seems to be pretty broken. I'm assuming this also applies to enemies like the gnoll trickster, but since that geometry is impossible to find in the sewers, it never really happens. Fixing the terrify thing should be easy, just add a variable that toggles when the scorpio is terrified that when it's true, then the rule that when the scorpio is adjacent to the tile the hero is on the scorpio has to go back, just doesn't happen.

**Comment by 00-Evan** [comment]
This is a quirk of retreating logic that occurs with specific layouts when the hero is standing on or around the only exit path. It has nothing to do with scorpios in particular.

**Comment by Howdidibreakit** [comment]
Are you gonna fix it? It genuinely did affect my run negatively because the scorpio blocked the way and thus I couldn't let it retreat properly. (and yes, I know it's a quirk with retreating ai and not just scorpios, but i've had ai run past me to get out before, so it's a quirk with the scorpio because it cannot stay next to the hero for more than one turn.

**Comment by 00-Evan** [comment]
It's not a bug. Retreating enemies try to pick a path that's more than just a couple of tiles away. If they are unable to do so then they'll either approach the hero (usually to try and retreat past them) or freeze in place. There are some specific aspects of this I might like to improve but the fundamental idea of retreating enemies being smarter than just looking 1 tile ahead won't change.

**Comment by SujayDalai02** [comment]
@Howdidibreakit I have seen similar behaviour with the rat king. When I wake him up and then block the door, he never move from his position.
