### ISSUE TITLE
Lightning Wand treats water+levitation inconsistently

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1344]
Levitating characters are still subject to certain effects of water. 
Glyph of flow is still effect
Characters will gain more chilled
Damage of the lighting wand will not decay, but it will not spread two distance away

**Comment by Lyx0527** [comment]
By the way, I don't know why ooze traps don't affect levitating characters

**Comment by 00-Evan** [comment]
In general I don't want some of these effects to anti-synergize with levitation, or for flying enemies to resist them. For Ooze and other traps I decided that some of them should only apply to grounded characters, which included ooze traps.

Will look into lightning wand though, at the very least it should be consistent with itself.
