### ISSUE TITLE
Can't make meat pie

### ISSUE THREAD

**Issue by kenanAlhindi97** [00-Evan/shattered-pixel-dungeon#1346]
![Screenshot_20230507-172529](https://user-images.githubusercontent.com/91883997/236687368-403427d9-7f77-4516-bb71-30981568e4ff.jpg)

**Comment by 00-Evan** [comment]
You're using a small ration, which does not work for the recipe.

**Comment by spixi** [comment]
You need a regular Ration, not a small one for a meat pie.

**Comment by kenanAlhindi97** [comment]
whoops my bad.
