### ISSUE TITLE
Mimic is not targetable

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1347]
It is not possible to target a Mimic for the lunge attack.
![Screenshot_2023-05-07-17-58-03-259_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/236688708-434145a2-0cab-4345-bfdb-b30054b65a0a.jpg)

**Comment by 00-Evan** [comment]
Mimics can be attacked with the lunge ability, they just aren't autotargeted when they are hidden.

**Comment by spixi** [comment]
@00-Evan You cannot use the Lunge attack against them. Instead, the Duelist will walk in front of the Mimic and try to open it.

**Comment by 00-Evan** [comment]
Before closing this issue I tested this with and without brawler's stance, in both cases the ability works normally.
