### ISSUE TITLE
Invisibility cloak doesn't provide barrier effect in specific cases

### ISSUE THREAD

**Issue by TadaCZE** [00-Evan/shattered-pixel-dungeon#1349]
If you use the invisibility cloak without the ability necessary to activate the barrier effect, then proceed to purchase said ability, the invisibility cloak starts providing the barrier effect only once you dismiss the invisibility and start using it again.

**Comment by 00-Evan** [comment]
Fixed in commit: e296a6dfe4667bd9f75ce4fbb3cb6483c91f0ab7
