### ISSUE TITLE
Powersave on more new NULL found.

### ISSUE THREAD

**Issue by 133794m3r** [00-Evan/shattered-pixel-dungeon#135]
This was a new one for me, it wasn't on the same one that I had a NULL for the icon of a seed don't know if this si powersave related or not. I will be trying to continue playing in powersave and see if I can get ti again. I had never quit th egame/restarted theapp during this run.
![screenshot_2016-10-20-17-28-31](https://cloud.githubusercontent.com/assets/599849/19622900/747d4c18-9883-11e6-97fd-4626a29c1be3.png)

I think I had just opened the thing or well the ghosts had just spawned after opening the gravestone or destroying ti whatever the comon thing is. I don't remember a text showing up on other runs though after doing that I can't think of it ever hving a text shown until you picked up the corpse dust.

**Comment by 00-Evan** [comment]
I'm aware of the no text found error here, will be fixed shortly. I've closed this as it's exclusively a beta issue and isn't present in the open source yet. It will be fixed shortly though.

**Comment by 133794m3r** [comment]
Wait what, are yuo talking about the error? Or the fix? I am using the f-droid build and have for quite a long while. I am using 0.4.3 from the f-droid  repos signed 47c75 etc. So  Idon'tknow what you're talking about it not being in the open source yet, are you talking about teh fix right?

So the issue is a beta version and where is the beta version I'm on f-droid.

**Comment by 00-Evan** [comment]
whoops, very sorry. I misread my own commit messages =S

Yes this is indeed an issue with the live version, re-opened.

**Comment by 00-Evan** [comment]
fixed in commit 2bb55aa7c15d62e66b6bcd8a9518c161494ada3c
