### ISSUE TITLE
Runic Transference Description (meta)

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#1350]
Importance: <nano

(actors.hero.talent.runic_transference.meta_desc) - Not 100% easy to read or exhaustively describing what really happens.
* Just adding a colon after "when upgrading armor" sounds much clearer?
* No mention that the propability progression is overridden, not shifted -> normally you get glyph loss chances by level: [4->0, 5->10, 6->40, 7->90, 8->100]. With 2 levels of RT, you get [4->0, 5->0, 6->0, 7->0, 8->100], not [7->0, 8->10, 9->40, 10->90, 11->100] as some may suspect... Just meant as food for thought, I'd also tend to leave that to mystery, as I can't come up with succinct wording for it.

**Comment by Pr0methean** [comment]
How about this? "When you upgrade armor to +8 or less, you don't risk losing the glyph on the armor. You still always lose it when upgrading beyond +8."

**Comment by 00-Evan** [comment]
Agreed that the description here is a bit obtuse, will see about rewriting it.

**Comment by 00-Evan** [comment]
Fixed in commit: b8f623b2c28cb8980fd37559dba560ed0a73771c
