### ISSUE TITLE
AntiMagic Glyph description

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#1351]
Another tiny nag where I feel a description doesn't fit """reality""".
* AntiMagic says it's "powerful" and it is rare
* It offers damage reduction for a set of _direct damage_ attacks
* It offers zero protection against DOT or area effects as far as I can see
* It offers zero protection against debuffs - neither proc rate nor duration.
* A level +20 AM armor _feels_ comparably potent at damage reduction than a +5 ring of elements - AM reduces by 20-33 points, RE by 62%, so for an evil eye (average ray damage 40) that would indeed be close.
* But the RE also helps with debuffs, and area effects... So it's far better at five green scrolls than the AM with all scrolls of a run.

All in all, all I'm saying is, with these mechanics the word "powerful" could maybe migrate over to the ring of elements?

**Comment by 00-Evan** [comment]
AntiMagic is balanced based on gameplay data, and it's surprisingly strong for how little magic damage resist it gives you. DOT and Area effects aren't necessarily magic, and regular armor does not protect against non-magical debuffs. Ring of Elements is an entirely different effect. It's also not fair to compare them given that one is its own item and the other is a tag-along on armor that's already worth upgrading.
