### ISSUE TITLE
Dying during fadeleaf transition resetting floor 21?

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1352]
This happened yesterday, and unfortunately I didn't take any screenshots, as I didn't immediately realize I'd need to. From memory,, then:

I was attempting a promising run of scrolless/potionless, and had gotten to floor 21. I currently had an ankh in the inventory, as well as an assortment of seeds (including fadeleaf) and the greaves of nature. After killing the spawner, I made it about halfway through the floor before getting swarmed, and although I managed to shake of my pursuers, I had only a few health left, which due to deferred damage would kill me in two turns. I doubted I would be able to recover my bag if I died on floor 21, so with my last two turns available, I planted a fadeleaf seed (playing as warden, btw), and activated it, which took me back to floor 20 and relative safety right as I died. (I don't think that I activated the fadeleaf through my greaves but it is possible that I did and am misremembering)

Now, as I recall, the vision on floor 20 was not reset. I could be wrong about that, but I think I remember this being the case, which should have immediately alarmed me because it implied that I did not die on that floor. Despite this, my bag was simply at the end of the floor, as if I had died there. I picked it up and thought I had pulled off a really clutch maneuver. I then went back to floor 21.

I immediately noticed that my vision was reset, but for whatever reason didn't think anything of it. What really got my attention is when I went back into one of the rooms and saw a sleeping enemy that I knew I had killed, and then a few turns later I was attacked by a ripper (which to be fair might have been left over from the spawner before, but I considered that unlikely in light of the circumstances). I checked out another room, and the two enemies were once again there sleeping, and then I went to where I'd destroyed the spawner only to find it still there intact. The floor had apparently reset itself.

I'm not sure if this had something to do with the partial turn indicator, or that I might not have picked up any of the floors items (don't remember if I did; definitely didn't use any). I've tried seeing if I could recreate the effect with similar setups on other floors, to no avail, so I am not sure if I screwed something up or if this is a super niche thing exclusive to floor 20-21, but it likely cost me my run (I failed in the last fight when Yog had 5 hp) due to draining my resources, so I am a bit irritated.

**Comment by 00-Evan** [comment]
This sounds like a device storage error, not an error with the game. Shattered saves each floor of the dungeon to its own file, and in the case of loading transitions, reads those files to populate the game world. Something occurred on your device that prevented Shattered from writing data to the files for floors 20 and 21. This is why your map knowledge was not cleared for floor 20, and why floor 21 reverted to before you had entered it. There's nothing the game can really do if the device refuses to update save file contents.
