### ISSUE TITLE
can't swing with reach weapon after champion switching

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1354]
I switched to glaive , which I'm not strong enough to use.  When I press the button to swing, nothing happens.
![Screenshot_20230518-193228](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/e5f5e087-f1d3-47e8-a14d-8c44d8f1d592)
![Screenshot_20230518-193538](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/23ca1b1c-35cd-435d-8d89-63cd52f65893)

**Comment by protective1** [comment]
This may be the same bug.  I can't swing the spear at the golem.
![Screenshot_20230517-004312](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/f7502ff7-3a0d-4376-b9d9-4bf1be4e8c3f)
![Screenshot_20230517-004333](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/d7b68c8c-a1c0-4b35-b288-c3a6bdd9d731)

**Comment by 00-Evan** [comment]
In the first set of screenshots, it does look like the game is correctly identifying that you were able to attack, did tapping on the piranha itself do anything?

In the second set of screenshots you're using brawler's stance, you don't benefit from extra reach when you're not actually attacking with the weapon.

**Comment by protective1** [comment]
Thanks for clarifying the second scenario.

In the first scenario, nothing happened when I clicked the button, and I did not try clicking the piranha directly.  I exited the game and came back in, and then after that the glaive button worked appropriately (took a swing at the piranha).

**Comment by 00-Evan** [comment]
This is an issue with the attack indicator then. This is a known bug where the indicator will very rarely fail to work, but I haven't even been able to reproduce it unfortunately. Closing this for now as there's no action I can currently take on it.
