### ISSUE TITLE
Bug when repeatedly tapping item on the ground with full inventory

### ISSUE THREAD

**Issue by RamiShafikovca** [00-Evan/shattered-pixel-dungeon#1355]
When trying to pick up an item from the ground with a full inventory, the item bounces to indicate that you cannot carry it. However, pressing it repeatedly pushes it further and further upwards, until it exits by the top of the screen. This is only a visual effect, after ending the repeated tapping the item returns to the ground.

**Comment by Sarius997** [comment]
This is fully intentional. See https://github.com/00-Evan/shattered-pixel-dungeon/issues/1150 and the linked issues
