### ISSUE TITLE
Bug of Freerunner

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1356]
In 2.0.2, building momentum turn yellow, freerunning turn purple
And the numbers of buff and skill icons are not always the same. With speedy stealth, wait while invisible, the number of icons will not change 
![Screenshot_20230521_064305_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/e154a619-cc40-4aed-a02b-7cbed4491251)

**Comment by 00-Evan** [comment]
I'm not sure what you mean by "momentum turn yellow, freerunning turn purple" . The color purple is never used by the momentum buff

I am aware of that bug with speedy steath, it's already fixed in v2.1.0-BETA-1

**Comment by Lyx0527** [comment]
In the picture, '动量积蓄'  means 'building momentum'. The icon under the blood bar is yellow, which used to be green.

**Comment by 00-Evan** [comment]
That is intended. as of v2.0.2 information about turns of momentum is displayed in the action indicator, and so having the buff icon change color from white to green is no longer needed.

**Comment by Lyx0527** [comment]
But freerunning and recovering have the same color, which is not intuitive

**Comment by 00-Evan** [comment]
You should have said that then. That's also already fixed in v2.1.0-BETA-1, which should be releasing in another couple of hours or so.
