### ISSUE TITLE
Explanation on ascension

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1357]
It says I can leave the amulet on the 25th floor and return, but in reality, doing so does not end the game

**Comment by Lyx0527** [comment]
![Screenshot_20230521_205234_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/67f049bb-0f15-4550-85b4-c7eb58fcdcbf)

**Comment by 00-Evan** [comment]
I'm not sure what you mean here. It's intended that you cannot end the game by leaving the amulet on floor 25, which should be obvious as the amulet is the point of your quest. You are able to leave it there temporarily if you want to go back to previous floors without starting the challenge though.

**Comment by Pr0methean** [comment]
The wording "ascend without starting this challenge" is confusing - it suggests that leaving the dungeon without the amulet but with no bosses left to guard it is possible, and that taking it out is an optional hard mode.
