### ISSUE TITLE
Buyback menu visual glitch

### ISSUE THREAD

**Issue by a-Mayor-K** [00-Evan/shattered-pixel-dungeon#1365]
Items with long names display in a single line despite being too long.

![IMG_20230523_153333.jpg](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101465375/234894f5-9693-41cf-99a9-60c54cb1a299)

Please tell me if I am doing this wrong.

**Comment by 00-Evan** [comment]
Fixed in BETA-2
