### ISSUE TITLE
Can completely cancel fist attacks by clicking during animation

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1366]
I have no idea how this happened, 
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/2d2db421-331d-44ec-a83c-511943c61009)
But sometimes when the soiled fist is on fire, you can just say "no" to his attacks, and interrupt them, making them do no damage to you because they never happened. Again, no clue how it happened.

**Comment by Howdidibreakit** [comment]
It seems to be unpredictable, and only works when it's on fire. I suspect that because the grass is burning every turn, the fist is regrowing it every turn, and I am also burning, and so is the fist, the game is overwhelmed with actions, since they're all happening at the same exact time. It's probably at the maximum amount of damage calculation it's allowed to do in one frame, so when I prompt the game for my character to attack the fist, it prioritizes that over the fist attacking me. There's simply too much happening at once. I think at least, it's fun for me to try to figure out "What the hell is happening here"

**Comment by Howdidibreakit** [comment]
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/757507b9-8b6c-4e68-9128-c7799dfe01a9)
now i'm more confused. I somehow got the badge from dying?

**Comment by 00-Evan** [comment]
I'm not able to reproduce that error with soiled fist attacks, the game does not accept input for me when the fist's attacking animation plays.

The game checks for the dungeoneer badges every time that you finish a run, also please do not report separate issues in replies to an unrelated one.

**Comment by Howdidibreakit** [comment]
I think it actually might have been a visual bug, where the hit sound and animation doesn't actually play. The damage was probably just unnoticed by me because of my armor. My gear was this.
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/06c2a66a-fe85-445c-88c2-c61eea99221f)
I had death mark but I didn't use it on the guy.
