### ISSUE TITLE
`NO TEXT FOUND!!` for Duelist Using Katana

### ISSUE THREAD

**Issue by dragid10** [00-Evan/shattered-pixel-dungeon#1367]
I transmuted a crossbow into a Katana, and the Duelist special ability says `NO TEXT FOUND!!`
When I select the ability, it still acts normal and lets me use it
![Screenshot_20230523-112707](https://github.com/00-Evan/shattered-pixel-dungeon/assets/4042877/80238b4f-492a-4f66-8035-30c6809a59ab)

**Comment by 00-Evan** [comment]
Fixed in BETA-2
