### ISSUE TITLE
Maybe a bug. Crazy thief in sewers. Hostile champions challenge enabled

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1368]
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/9841288a-6e07-4e90-859a-31a90c5b0f41)
There's no information on the wiki about this, and I've never seen it before. I presume it's caused by the challenge, but the challenge says nothing about this. Also it's V2.0.0

**Comment by 00-Evan** [comment]
This is intended. Enemies from early in the next region can rarely appear at the end of the prior one.
