### ISSUE TITLE
The last sentence of the metamorphosis scroll is redundant

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1373]
You have added each talent to the random pool
![Screenshot_20230524_171738_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/eb2e0222-8355-4221-843d-c8dffe3f5cdd)

**Comment by 00-Evan** [comment]
I'm fine with leaving this in.
