### ISSUE TITLE
Goo regeneration through water will not reduce time

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1375]

**Comment by 00-Evan** [comment]
I"m assuming you mean time until passive regeneration stops? I've double checked and that logic is unchanged in v2.1.0, when Goo heals that removes as much time as damaging it would add.

**Comment by Lyx0527** [comment]
Although I have only heard about it, I trust the feedback giver's understanding of the game. Additionally, I have just tested it and badder boss goo has indeed given me 100+ health. Personally, I would prefer to keep this bug and take advantage of it, because the weakening of regeneration time is not easy to accept, but I still submitted it to you. Please re-examine this issue.
![Screenshot_20230525_060034_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/b06ed20d-a420-47bc-9f31-f833b20e7e6f)
![Screenshot_20230525_060056_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/6091b468-687c-4430-b7c6-24f1c37187d8)
![Screenshot_20230525_060105_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/c0fd5a23-b681-43a5-8461-d09cb0928229)
![Screenshot_20230525_060117_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/1810ea4a-09fe-491c-9892-003e31a7f8c1)

**Comment by Lyx0527** [comment]
![Screenshot_20230525_060236_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/cde1c1ee-7c15-449d-95e2-d2da52aec624)

**Comment by 00-Evan** [comment]
After double checking there is no issue with Goo's logic. There is an unrelated error in how locked floor calculations are working that makes it much more permissive than intended generally, which is what is causing this to occur. Essentially, damaging the boss in any way immediately sets remaining turn to 50, when it should cap it at 50.
