### ISSUE TITLE
About combined lethality

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1377]
Why can't I execute the enemy？
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/53d87406-fba2-4fd6-8b2e-98b5bdd12870

![Screenshot_20230526_122458_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/a8617fea-e64b-4db8-a229-3f586b2a41dd)

**Comment by 00-Evan** [comment]
In what context are you not able to execute an enemy?

**Comment by Lyx0527** [comment]
Can't the video be played?
Using charged shoot, shooting fire element for 30 damage, immediately using the whip ability in close proximity, dealing 26 damage, unable to execute

**Comment by 00-Evan** [comment]
You attached an image to the issue, not a video.

You are performing an action in between using the two abilities. Charged shot counts as being 'used' when the ability is intitially activated.

**Comment by Lyx0527** [comment]
Shouldn't it be considered as a weapon ability to hit enemies with a dart? Just like triggering lethal haste with a dart
