### ISSUE TITLE
Random is not very random

### ISSUE THREAD

**Issue by tomreyn** [00-Evan/shattered-pixel-dungeon#138]
Hi,

thanks to Watabou and Evan for developing this awesome game. I have been playing Shattered Pixel Dungeon for about a year (about 3 or 5 times a week average), and only made it to the end last week (I was almost convinced I would never make - it is tough!).

What puzzles me is that there seem to be repetitive patterns across games. If you play a game and happen to find good items on the first and second level, but die then, chances are very high you will happen to find good items early on on the next game as well. Also, the contrary is true. 

This is not limited to items you find (but most obvious there), but also the same special rooms are more likely to reappear early on on a follow-up game if you loose the first game early.

Since I can't even tell for sure this is related to the game or whether its just the platform: this is on a Galaxy S7, running the (default) Samsung Android distribution which ships with the phone, with all the latest OS updates installed.

Feel free to close this if it turns out to be unreproducible for you. I just thought it would be worth bringing it up.

Thanks again,

Tom

**Comment by 00-Evan** [comment]
all of the games RNG is based on standard java random number generation, there should definitely not be any kind of consistent pattern to the RNG. 

This sounds like the clustering illusion cognitive bias to me: https://en.wikipedia.org/wiki/Clustering_illusion
