### ISSUE TITLE
2.1.0-Beta-3, Taking very high damage from Golem after changing armor enchantment.

### ISSUE THREAD

**Issue by TrueFMartin** [00-Evan/shattered-pixel-dungeon#1380]
I had a character mid-run when the beta update released. Previously had **Plate +3**, Stone enchantment, +3 RoEva, +1 RoEva. After game was updated, returned to game and used stone of enchantment on armor to remove Stone Glyph on armor. Replaced with Glyph of Entanglement. Faced a Golem, not a 'Hostile Champion' version. Received damage of **25, 45, 26**. The 45 seemed too high with my armor. I'm not sure of Golem's current damage roll, but I thought it capped around 40 (wiki says 20-40). That may be possible damage, but it seemed like very high, consecutive damage rolls. Similar to the damage I would receive without armor. I don't know if it had something to do with my character existing pre-update, the rings interacting with Stone Glyph, or if it was some extremely unlucky damage rolls. **Faith is my Armor** is disabled. I wish I was recording. No debuffs active. 
![Screenshot_20230526-220913](https://github.com/00-Evan/shattered-pixel-dungeon/assets/103139765/f927c37d-f540-4487-87ec-0745dbb16636)

**Comment by 00-Evan** [comment]
Golems have a damage range of 25-30, so there would have to be something either boosting the damage it deals or the damage you recieve if you were hit for a 45, but the other numbers are totally possible. Stone glyph would be very strong with your rings of evasion, which might explain why the damage rolls felt so much higher without it.

**Comment by 00-Evan** [comment]
Closing for now as I cannot reproduce nor find any code changes that would result in a golem dealing 45 damage without a clear reason (e.g. champion golem + vulnerable on the player).
