### ISSUE TITLE
Grim weapon can kill goo instantly

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1381]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/a2ea1c1b-26a2-4f53-b3a8-2c226b8857f0

Does this bug still exist in beta3?

**Comment by SujayDalai02** [comment]
@Lyx0527 Holy.... 90+ damage with a +1 grim spirit bow? That's broken...

**Comment by 00-Evan** [comment]
Fixed in v2.1.0-RC-1
