### ISSUE TITLE
purpose to add a new install method

### ISSUE THREAD

**Issue by dimatakoy** [00-Evan/shattered-pixel-dungeon#1383]
Hi, I want to add shattered pixel dungeon to [homebrew](https://brew.sh/). This will allow advanced users to install the game via the terminal command:

```sh
brew install shattered-pixel-dungeon
```

With this method user will get free version of MacOS app
https://github.com/00-Evan/shattered-pixel-dungeon/releases/tag/v2.0.2

Are you okay with adding this method?

**Comment by 00-Evan** [comment]
You're obviously able to make an unofficial distribution of Shattered if you want to, I ask two things:
- please try to ensure it stays updated with the latest (non-beta) release reasonably quickly.
- please clearly state that it is an unofficial distribution, which is not maintained or supported by me.
