### ISSUE TITLE
Bug with transmuting throwables

### ISSUE THREAD

**Issue by Aim226** [00-Evan/shattered-pixel-dungeon#1385]
Transmuting a +6 javelin ended up making it into 3 +1 boomerangs instead of a +6 boomerang/tomahawk, essentially ignoring 3 scrolls of upgrade
![Screenshot_20230529-005626](https://github.com/00-Evan/shattered-pixel-dungeon/assets/134911982/2ec46eeb-3a06-4e03-86d3-8c26abc3881f)

**Comment by 00-Evan** [comment]
Fixed in v2.1.0-RC-1
