### ISSUE TITLE
Follow-up Strike Description

### ISSUE THREAD

**Issue by SujayDalai02** [00-Evan/shattered-pixel-dungeon#1387]
![Screenshot_2023-05-31-11-31-31](https://github.com/00-Evan/shattered-pixel-dungeon/assets/130607815/d3946194-08b8-423f-9b74-b4a3354aed63)
 There's no mention of any kind of time limit for the extra melee damage. But in the details of the buff, it says...
![Screenshot_2023-05-31-11-31-45](https://github.com/00-Evan/shattered-pixel-dungeon/assets/130607815/3ffb8e42-b0c7-4777-b723-affef7326046)

I think the time limit should be specified on the talent page also.

**Comment by Lyx0527** [comment]
In fact, this change is a weakening of the talent. Now it can't work against multiple enemies at the same time, and there is also a time limit, which makes it more difficult for Huntress to deal with swarms than before

**Comment by 00-Evan** [comment]
I'm fine with this. 5 turns and a single target is more than sufficient in almost any case the talent will be used. These changes were mainly made so that the buff would appear more intuitively with its new visual indicator.
