### ISSUE TITLE
Some display issues relating to magical sight

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1388]
If a hero sees enemy by magical effect, their position remains illuminated even after their death. 
![-3821489af775350b](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/5ad2325a-f8aa-46d1-9974-9db7e99b2e57)
But the hero cannot see what exactly happened in that area

**Comment by 00-Evan** [comment]
re: 2nd message: Please do not use evidence from other versions of Pixel Dungeon when reporting issues.

re: 2nd and 3rd message: Please do not append unrelated issues to the same issue report. Make separate issues unless they are clearly related, or you are reporting many (e.g. 10) issues at once. If you are reporting many things at once, please organize them in a list or similar.

re: 3rd message: I'm fine with allowing this. It's a minor visual quirk that's a consequence of action order and would be more difficult to change than it is worth.

To simplify this issue report I have edited your messages and changed the title to reflect the originally reported issue in your first message.

Now, regarding that issue, can you give me more information about this? What 'magical effect' was used to see enemies from a distance?

**Comment by Lyx0527** [comment]
I tried to reproduce this bug, but it failed. I have indeed seen similar bugs, but I did not pay special attention to them.
Sorry for providing incorrect information. According to dictation, this seems to have nothing to do with magical vision. The monk used a blast wave wand to push away the evil eye preparing for death gaze, and then used a dash, but was still attacked.
You can close this issue now, and I will continue to pay attention to it

**Comment by 00-Evan** [comment]
Sure, feel free to comment here or post a new issue if you can reproduce the error again.
