### ISSUE TITLE
FR: Provide more information on how cursed items affect the player

### ISSUE THREAD

**Issue by tomreyn** [00-Evan/shattered-pixel-dungeon#139]
Having played the game for roughly a year, it still remains unclear whether or how cursed items which are not readied, affect the player. My impression is that they still have a negative effect on the player, but less so than if they were readied. This, however, is only based on guessing, since the game does not seem to discuss this anywhere.

Now you could say this is on purpose, and it is part of the (otherwise actually quite entertaining) learning effect / better understanding you grow after playing the game for a good while. But I feel that after a year of playing the game (and having won it), I really should know, and I do not.

**Comment by 00-Evan** [comment]
Curse items have no affect if they aren't worn. The game doesn't do a good job of explaining several things and I hope to improve that in a future update which overhauls the tutorial system.
