### ISSUE TITLE
F-Droid version "Has security vulnerabilities"

### ISSUE THREAD

**Issue by RageGamerBoi** [00-Evan/shattered-pixel-dungeon#1390]
![Screenshot_20230531-154010](https://github.com/00-Evan/shattered-pixel-dungeon/assets/105567407/a5dbb2ea-e5ed-4dc6-9f34-998da692858f)

This is according to Neo Store. I don't know where it gets its vulnerability reports but it's presumably F-Droid's Anti-features list.
I hope you can get this resolved soon :)

**Comment by TheGamer1002** [comment]
+1. Neo Store is REALLY loud about this. I'm getting notifications literally every second.

**Comment by RageGamerBoi** [comment]
> +1. Neo Store is REALLY loud about this. I'm getting notifications literally every second. Might have to back up and uninstall for now.

You can enable the "Ignore reported security vulnerabilities" toggle but be careful to turn it back off once it's fixed.

**Comment by 00-Evan** [comment]
There are no anti-features listed on F-Droid directly: https://f-droid.org/packages/com.shatteredpixel.shatteredpixeldungeon/

Regardless, sorry but I don't provide support for unofficial distributions of the game. If you want to get an APK of the game built directly from the open source then the recommended way is directly via github: https://github.com/00-Evan/shattered-pixel-dungeon/releases

**Comment by RageGamerBoi** [comment]
Oh, I didn't realize that...
Hopefully you can somehow officially support F-Droid in the future ;)
Thanks.

**Comment by 00-Evan** [comment]
> Oh, I didn't realize that... Hopefully you can somehow officially support F-Droid in the future ;) Thanks.

'Fraid not. I previously did and issues like this one, that I can do nothing about other than open an issue report and wait (sometimes for 1-2 weeks), are what caused me to drop it as an official channel to get the game. I just can't officially link to a platform page that may be more than week out of date or contain false information about security issues with the game.

**Comment by RageGamerBoi** [comment]
Makes sense.
I assume https://apt.izzysoft.de/fdroid/ wouldn't work either then.

**Comment by 00-Evan** [comment]
I have no issue with Shattered being available though new unofficial channels, but I don't have any plans to add more official ones right now.

**Comment by Silent-Hunter** [comment]
If I do get the github version, will it notify me when there's a new version? If so I'll just do that.

**Comment by 00-Evan** [comment]
The github version has a built-in update notification that scrapes from github releases whenever it is launched. There are also the usual blog links.

**Comment by ProfessorSniff** [comment]
https://monitor.f-droid.org/anti-feature/KnownVuln

interestingly, `com.shatteredpixel.shatteredpixeldungeon` is listed as an app with a known vulnerability, but not on its app page. Other apps list this as an anti-feature.
