### ISSUE TITLE
F-Droid vulnerability warning

### ISSUE THREAD

**Issue by twann4** [00-Evan/shattered-pixel-dungeon#1391]
F-Droid indicates that the app contains a vulnerability. Unfortunately, I haven't found a way to know which vulnerability that is.

**Screenshots:**
![Screenshot_20230601-002023_F-Droid_1](https://github.com/00-Evan/shattered-pixel-dungeon/assets/121837300/54ab3a71-b716-48bc-bc9e-d11146813b94)

![Screenshot_20230601-002036_F-Droid_1](https://github.com/00-Evan/shattered-pixel-dungeon/assets/121837300/2217585e-ebf6-4ee0-a231-c8039d301a72)

**Comment by kyhou** [comment]
Yep, sadly going to uninstall it, until this is fixed, just to be safe

**Comment by 00-Evan** [comment]
Duplicate of #1390

I do not provide support for unofficial distributions of Shattered, especially when they falsely flag it as having security vulnerabilities. I suggest that you switch to the releases here on github if you want an APK that's built from the open source.

**Comment by kyhou** [comment]
Oh I didn't know, I thought it was official 😅 going to install it again using Obtainium to get it directly from here 👍
