### ISSUE TITLE
Feature request: automatically fill seed pouch/waterskin

### ISSUE THREAD

**Issue by graevy** [00-Evan/shattered-pixel-dungeon#1393]
I'd code it myself but you don't do PRs! This feels like massive QOL, especially on mobile.

You'd obviously have to choose how these pickups interact with game ticks. If they still take a tick to grab, it would have to be disabled when enemies are in sight, I'd guess.

**Comment by 00-Evan** [comment]
Sorry but I don't plan to add auto-pickup features like this.
