### ISSUE TITLE
Why can't I challenge the enemy?

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1396]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/6985d1fd-d021-43d9-9ca8-c20a89d9f29d

Perhaps this is related to language habits? within 5 tiles

**Comment by 00-Evan** [comment]
fixed in commit 52f33c44134a8b097742280ce3070f2f7d1399f2
