### ISSUE TITLE
dealing +50% damage

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1397]
![Screenshot_20230603_050718_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/e231aacb-0303-4708-b7bb-d2c3e2afdfc9)
![Screenshot_20230603_051010_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/1b08415a-5997-4595-9278-8fe492aacef9)

**Comment by 00-Evan** [comment]
fixed in commit e0ca11e307c10b705377dd755deb4f31a0a30842
