### ISSUE TITLE
FR: Provide more information on challenges

### ISSUE THREAD

**Issue by tomreyn** [00-Evan/shattered-pixel-dungeon#140]
Once the game is won, you can choose of challenges to make follow up runs more exciting / a little tougher. Unfortunately, only the challenges' names are provided. It remains unclear what each challenge means, and whether the fact that a challenge is taken alone means that other effects also kick in (such as starting without any food packs). It would be nice to hint on how these work, and what to expect.

**Comment by 00-Evan** [comment]
The current challenge system is pretty bad for a number of reasons, my plan is to completely rework it rather than make improvements to the current system.

The reworked system will feature proper descriptions.

**Comment by Block-Vader** [comment]
I'm from the future. We've had two rounds of challenge improvements and two new challenges were added. Meanwhile complete rework was just moved to stretch goals.
