### ISSUE TITLE
Vampire bat got into an infinite attack loop killing the character

### ISSUE THREAD

**Issue by denis-kralj** [00-Evan/shattered-pixel-dungeon#1400]
The run was on a rogue (assassin) after defeating Yog. On dungeon level 14 I got into combat with 2 bats. I first summoned 2 rats with Ratforcements that died pretty quickly, then Ratmogged one bat while fighting the other. Killed the non transformed bat, in the mean time the transformation ended on the other one. At this point the remaining bat started hitting the character and not really stopping. I couldn't move, hit or use abilities, potions etc.

I had a corrupting great axe, the Ratmog armor, chalice of blood, ring of might and ring of haste. 

The game was created before 2.1 and ended abruptly about 30min ago.

Let me know if other details are needed.  RIP for a pretty good run 😢

**Comment by 00-Evan** [comment]
Seems to be caused an intersection of ratmorify and the ascension challenge

**Comment by 00-Evan** [comment]
fixed in commit c9bed0e0cbc59731ae2e51b16a53115fa9270bb6
