### ISSUE TITLE
If the hero gained chilled, Icy touch cannot be immune to the cold

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1401]
When hero drinks the elixir, chilled should end
Uploading Screenrecording_20230606_183911_com.shatteredpixel.shatteredpixeldungeon.mp4…

**Comment by Lyx0527** [comment]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/2d13620f-94e2-4449-b7eb-ee7b01757fe8

**Comment by 00-Evan** [comment]
fixed in commit 88a80fb289a60840c4adf9b1da2135e01d9c820f
