### ISSUE TITLE
Suggestion: Slight rebalance of warrior to make them more unique

### ISSUE THREAD

**Issue by ludvigng** [00-Evan/shattered-pixel-dungeon#1402]
Hello!

Currently the warriors unique starting ability seems to only be the broken seal, which is very equipment-dependant in its usefulness. Personally I find it very difficult to get a good build going, though I am pretty new to the game all considered so it might just be a skill issue.

However, one thing that I think could be interesting could be to either give the warrior one extra point of strength at the start, or making the strength requirement one less for weapons for the warrior. I think this would fit the role better, since they'd have slightly earlier access to some weapons/equipment compared to the other classes, while still hopefully not being completely broken. Plus with them being a warrior, it could make some sense flavour-wise that they have some experience with weapons already, making them a bit easier to wield as a result.

What do you think?

**Comment by Pr0methean** [comment]
If this is implemented, the tier-3 talent that increases strength should probably be changed to something different.

**Comment by ludvigng** [comment]
> If this is implemented, the tier-3 talent that increases strength should probably be changed to something different.

Good point. I suppose another alternative is to move the tier-3 talent to tier-1 instead and use something like 10% and 14% as talent levels instead. 10% would effectively be a 1 strength increase until 20 base strength, while 14% would be 2 extra strength at base 15, since they're rounded down. This would mean a slight power increase early, while still effectively staving the max potential 2+ strength increase effect until after tengu, just like the current tier-3 talent.

Question then becomes what talent to replace, or transfer from tier-1 to tier-3, instead.

**Comment by 00-Evan** [comment]
The warrior actually used to have 11 strength, along with other various mild hero statistical differences such as the mage getting faster wand recharge, the Rogue having more passive detection, and the Huntress having 15 starting health but healing more from dew.

I've steadily moved away from these differences in favor of having the heroes vary based on gameplay mechanics instead. The Warrior is also already doing quite well overall, including in the early game, and giving him back 11 strength would make him quite overpowered.
