### ISSUE TITLE
The spirit hawk seems unable to attack Scorpio.

### ISSUE THREAD

**Issue by Kesan1984** [00-Evan/shattered-pixel-dungeon#1403]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/135830292/911ecc65-6210-4fa0-b035-19123a1efe03

**Comment by 00-Evan** [comment]
Seems to be caused by the 'move to position' command followed by 'move to attack'. It's not specific to Scorpios.

**Comment by 00-Evan** [comment]
fixed in commit aa8c81237ea1dfefebe48751850d8b8691da81f0
