### ISSUE TITLE
Returning boomerang breaks invisibility

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#1404]
I threw a boomerang at a distant enemy, and then took a step backward. A nearby enemy followed me and stepped where I had been standing. I went invisible using the assassins dagger special on the Duelist. The boomerang returned, hitting the close by enemy, which broke my invis, and I was attacked.

**Comment by Lyx0527** [comment]
Evan insists that the return of the boomerang is also seen as an attack from hero

**Comment by 00-Evan** [comment]
This is intended. Hitting an enemy with a returning boomerang is a ranged attack, which breaks stealth.
