### ISSUE TITLE
Imp design is not colorblind friendly

### ISSUE THREAD

**Issue by danielnoiz08** [00-Evan/shattered-pixel-dungeon#1408]
Love the game, but the imp's color palette makes it difficult to see with my color blindness. Perhaps making the sprite a bit bigger with a contrast border? The movement helps sometimes but I still have missed the imp only to notice it on the Landmarks menu two or three floors later.

**Comment by 00-Evan** [comment]
duplicate of #1146

This is a long-standing issue when the Imp happens to generate on red carpet tiles. I don't plan to change anything relating to him at the moment, but will eventually rework the quest, and in doing so will probably give the Imp a dedicated room where he'll stand out more.

**Comment by Pr0methean** [comment]
Why not just turn him yellow in the meantime?
