### ISSUE TITLE
The shoes of nature cannot target the spiders in the web

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1409]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/0ddeb680-9151-4182-b13f-69686e9641c2

https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/a05d349c-6600-4b42-bf26-141d95a25a9d

**Comment by Lyx0527** [comment]
In addition, Spider web works like a wall in too many aspects.
They can serve as a basis for chain pulling and can block the diffusion of gases.
When it comes to chains, ethereal chains can even ignore the barriers of walls to move heroes, but are powerless against the barriers of the web.

**Comment by 00-Evan** [comment]
This is at least somewhat intended, as spinner webs are meant to be treated as solid terrain like walls. I can look into some specifics of this (e.g. chains should definitely let you go through webs, footwear not working at all when enemy is reachable but just standing in a web), but it's definitely intended that they work like walls in most aspects.

**Comment by 00-Evan** [comment]
Given the 'rooting' nature of the Sandals ability, I've decided to allow it to work on any location within 3 tiles you have vision of, even if it is through solid terrain.

**Comment by 00-Evan** [comment]
fixed in commit 5a70a482aec5414845f23ac62e850b9f76396276
