### ISSUE TITLE
Katanas really don't block

### ISSUE THREAD

**Issue by TheShadowOfHassen** [00-Evan/shattered-pixel-dungeon#1411]
This isn't an bug or anything. However, in real life Katanas are not really good at blocking. In the description of you say the katana has a broad guard but just show a normal katana with an ity-bity guard. People have tried blocking with it and usually they get they hand banged.

A katana is still a cool weapon to have in the game but in real life it isn't a good blocking weapon. I thought seeing that no one else had brought it up I'd let you know.

**Comment by 00-Evan** [comment]
I'm aware of this, the in-game justification is more than the length of the blade lets you keep a bit more distance from enemies. In general I'm not aiming for high realism with Shattered's weapons anyway though.
