### ISSUE TITLE
A very unexpected failure

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1419]
【最搞笑的死法-哔哩哔哩】 https://b23.tv/rkjsJns

**Comment by 00-Evan** [comment]
Please do not report bugs from other versions of Pixel Dungeon

**Comment by Lyx0527** [comment]
You can easily understand what happened in the video

**Comment by 00-Evan** [comment]
I have no way of knowing what game code has or has not been modified. Trying to process reports from other versions of PD that 'might' be applicable to Shattered would generate a tremendous amount of work for me. I can clearly see what the intent of your report is, I can take a quick look at that, but I do not want to encourage reports from other PD versions, regardless of how close to Shattered they claim to me.

**Comment by Lyx0527** [comment]
Okay, I understand. Let me explain in detail.

This video was recorded by Loneless（地牢散人）, and he often communicates with you. He once asked you, if pulling a phantom piranhas into the chasm and falling to death was a bug.

He is a Minecraft fan. He likes to change some of the textures and sound effects of your game to Minecraft. That's all. I have no choice but to use his video. 

Regarding the content of the video, strictly speaking, this is not a bug. The metal shard dropped from DM201 triggered the rockfall trap and caused rouge death. I think this is extremely unpredictable, just like dying from teleportation into a secret summoning room.

I also mentioned this in #1170. You see it as a 'intended game mechanics'. I guess this video may change your perspective. I may restart some issues from #1170 in the future.
