### ISSUE TITLE
No more hero turns after ratmogrify

### ISSUE THREAD

**Issue by carlo-luzi** [00-Evan/shattered-pixel-dungeon#1421]
Hi, I try to report here a hilarious bug that killed my level 30 Warlock.

The bug was triggered after hitting a dwarf monk back to normal from ratmogrify transformation; After my hit, I skipped all my turns, the monk hits me in quick succession endlessly (like Hokuto no Ken!) until I died.

In the process all four of my blessed Ankhs were activated, I had no way of turning away or responding and the turn indicator was spinning at full speed.

When I realized I lost control I took screenshots, here they are

<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/3d392604-de2c-4e83-b78d-6b858f6f6d3d" width=30% height=30%/>
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/7ffb047a-b222-4789-9783-7b7b02eb74c8" width=30% height=30%/>
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/d04aad56-cf6a-49de-acd5-158f3f8d545e" width=30% height=30%/>
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/332bbcbf-d4ac-46c4-86df-0641e65450b9" width=30% height=30%/>
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/a73460a4-039b-4a24-80b8-a67b754ed98f" width=30% height=30%/>
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/611f4b19-f410-4f93-b7bf-e58348b2929c" width=30% height=30%/>

Other possibly useful screenshots:

<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/13215264-00df-4a56-90e5-31e906b4a14a" width=30% height=30%/>
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/12167043/c7d54b5f-f458-4a9f-9d27-220d02c56aa9" width=30% height=30%/>

Other relevant information not evident from the screenshots:
  - Version: 2.1.0
  - Dungeon seed: CNS-HDM-DTP
  - Platform: iOS

Thank you for maintaining this game!

**Comment by 00-Evan** [comment]
This has already been fixed  in v2.1.1 and v2.1.2, please update to the latest release.

**Comment by subruber** [comment]
Hi, something similar happened to me yesterday twice in the same run. I survived the first time but died on the second. I had a L29 Warden.

Game seed: JTF-WXQ-KJV
See the screenshot for my inventory. Note the +5 Ring of Haste (which I guess could be related?)

The first time a ratmogrified Scorpio went back to it's original form and started shooting me repeatedly (I couldn't count, but I lost ~all my HP.

The second time it was a Giant Piranha (I can't remember why on Earth it seemed a good idea to ratmogrify it). Once back to the original form it ate me through two blessed Ankh.

It's possible it also happened with an Evil Eye earlier on but I'm not 100% sure.

![Image](https://github.com/user-attachments/assets/db6c5d71-8ed5-4fa7-8f34-9380c67fab2f)
![Image](https://github.com/user-attachments/assets/0c15dbe7-2eb0-4264-852e-c4efa89d8dee)
![Image](https://github.com/user-attachments/assets/f1016bd2-ce6d-4f08-9b6b-abc0f3445ca8)
