### ISSUE TITLE
Idea of feature: camping

### ISSUE THREAD

**Issue by Gowq** [00-Evan/shattered-pixel-dungeon#1426]
I was  thinking about a new mechanic: a camping feature.  

You would be enable to rest in the camping, to cook, to forge itens etc. This will enable more complex dungeons and more chalenges. If you die with a totem you are reborn in the camping, and could equip the items that you storaged there.

To move a camping must be a complex task, to  discourage  to move to every level. If you die without a camping, even with totem, you lost.  

This will replicate the idea of RPGS of to create a  bonfire and take a time to  recompose. You will need to find a safe space and to create a way to avoid monsters coming in when you are sleeping. Maybe the monster couldn't find you once you are there, but when you are trying to get they could follow you and you not be able to rest or use it.

**Comment by 00-Evan** [comment]
The game essentially already has this with the rest feature (hold down the wait button to rest), and alchemy system. I'm not opposed to expanding resting, but I think a single-use item like a campfire kit would be more appropriate than something this elaborate.
