### ISSUE TITLE
When the magical fire wall was extinguished, the scroll inside the fire wall was burned down

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1427]
![Screenshot_20230621_224116_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/2b481e1e-065b-4e13-b42b-5cd190c7518d)

**Comment by 00-Evan** [comment]
fixed in commit 0d0231f7b5464a95b270079022dd9b3853222186
