### ISSUE TITLE
Fire not burning down undetected doors

### ISSUE THREAD

**Issue by andreasmjg** [00-Evan/shattered-pixel-dungeon#1428]
Just a thought... Fire only seems to affect doors that are detected.

To me this seems unrealistic. OK if some doors are hidden, but why would the fire not burn them down even if they are hidden from view?

**Comment by 00-Evan** [comment]
This is intentional, mainly so that spreading fire is not an effective way to find secrets, accidentally or intentionally. If you want a lore reason, consider that the hidden door is likely placed behind a false wall, that may be made of stone instead of wood.
