### ISSUE TITLE
Miscellaneous changes - minor typo

### ISSUE THREAD

**Issue by IamHakumen** [00-Evan/shattered-pixel-dungeon#1429]
There's a typo in the miscellaneous changes of v2.1.2
![Screenshot_20230627-233524](https://github.com/00-Evan/shattered-pixel-dungeon/assets/137912246/e22e50c5-4560-4b2f-b511-39da24ca46ba)

**Comment by 00-Evan** [comment]
It would be helpful if you actually stated what the typo is. Closing as this is too minor of a textual issue to address directly. it will get changed when the full change log for v2.1.0 gets condensed together with the next update.
