### ISSUE TITLE
Visuals - Interface

### ISSUE THREAD

**Issue by IamHakumen** [00-Evan/shattered-pixel-dungeon#1430]
Using the system font can make this thing happen (the entire text box can't fit on the screen when in landscape mode)
![Screenshot_20230627-225811](https://github.com/00-Evan/shattered-pixel-dungeon/assets/137912246/07c1e6d0-eb75-4e4d-a131-137a74a99291)

**Comment by 00-Evan** [comment]
These text boxes can sometimes push the boundaries of the screen when looked at in specific ways, often with maximum zoom and system font. You can actually read each line though, albeit barely.

When the next update releases I'll condense these into the existing bug fixes under v2.1.0
