### ISSUE TITLE
Request to add achievement reward system and levels

### ISSUE THREAD

**Issue by xuanyu6268** [00-Evan/shattered-pixel-dungeon#1434]
Hello author：
I really enjoy playing this game, but after completing countless levels, if I challenge directly, many attributes will decrease exponentially at once, making it difficult to adapt.

I found the game to be too monotonous. There is no difference between first-time players and players who have passed countless levels. In the daily challenge leaderboard, only their own ranking can be seen. People are more competitive. Can you add achievement system rewards to allow players to gain better attributes at the beginning.

Add levels and adjust values by percentage.

These two functions are not difficult: the achievement system can be quite cumbersome and require you to work hard to change. But the level system only needs to set one parameter, which can be multiplied by the percentage of existing monster data and character weakening status

Thank you.

**Comment by 00-Evan** [comment]
Sorry, but what you're asking for is to turn Shattered Pixel Dungeon into a different game. If there were permanent progression mechanics that make the player stronger, Shattered would be a 'roguelite' and not a proper traditional roguelike. The player's knowledge and skill being the only determining factor between their first run and their hundredth is the entire point.
