### ISSUE TITLE
Brawler Stance description and button always visible

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#1435]
If you equip an unidentified Ring of Force as the Duelist, there is a bug that gives out what the ring actually is. Is this intentional like when you observe the Strength of the hero wearing a Ring of Might?

![Screenshot_2023-06-21-00-18-19-71_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/1816060/6282d1a4-e9a6-4612-aebc-d6c6d3610680)

**Comment by 00-Evan** [comment]
This is intended. You are still able to use the functionality of unidientified equipment, which includes brqwler's stance.
