### ISSUE TITLE
[Visual Glitch] Item flies away when trying to pick it up with full inventory

### ISSUE THREAD

**Issue by megz15** [00-Evan/shattered-pixel-dungeon#1436]
On trying to pick up a scroll with a full inventory after jumping from a partially damaged wooden floor on the previous level, I got this glitch while spamming the key to pick items. I wasn't able to replicate it with a pie after dropping it and picking up the scroll of YNGVI, but I was able to do it with a scroll of BERKANAN, although not every time. It seems the glitch happens randomly with random items.

Again, like my previous issue, this isn't anything game-breaking but I thought I should still report it.

![image](https://i.imgur.com/eoRCzWt.gif)

**Comment by TheYsconator** [comment]
Known and intended. Refs.: #689, #1150 and #1355 (and probably others).

**Comment by megz15** [comment]
Ah, should have checked my bad
tribute to the original pd, that's cool :p

**Comment by megz15** [comment]
Ah, should have checked my bad
tribute to the original pd, that's cool :p
