### ISSUE TITLE
Monk flurry of blows doesn't work with whip? 

### ISSUE THREAD

**Issue by metbic** [00-Evan/shattered-pixel-dungeon#1438]
"the target can't be reached"
Game version 2.1.4
![Screenshot_20230713-215347](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8116828/8ac861e3-eb8f-453c-bb19-51efcc7dbdc7)

**Comment by 00-Evan** [comment]
Flurry of blows attacks with your fists, not your equipped weapon.

**Comment by 00-Evan** [comment]
No worries
