### ISSUE TITLE
Glyph wrongly transferred to broken seal

### ISSUE THREAD

**Issue by aaubry** [00-Evan/shattered-pixel-dungeon#1439]
I had a plate armor enchanted with a glyph of affection, and an unenchanted broken seal attached to it. After beating the dwarf king and using his crown, I noticed that the enchantment became attached to the broken seal instead.
It's not a big deal, but I don't think it is intended.

**Comment by 00-Evan** [comment]
fixed in commit daa7c31490cba704c2461f4b5c0c6505a470ed2e
