### ISSUE TITLE
Feedback for new blacksmith quest

### ISSUE THREAD

**Issue by fgeisser2** [00-Evan/shattered-pixel-dungeon#1440]
I'm not sure, whether there is an official place for feedback to your developer-message, so I'm just opening a new issue.

Things that confused me:
* At first I thought the entrance to the next floor had generated there, because they look very similar
* invisible border of the new sub-floor

But I like the idea in general.

**Comment by 00-Evan** [comment]
For feedback specifically it's usually best to email me: Evan@Shatteredpixel.com

v2.1.4 added both a unique visual for the stairs down to the test area (although it is admittedly similar) and a darkening effect to the borders of the test area. There's also a message that pops up when descending that explains that it's a test area and not the next floor.
