### ISSUE TITLE
There is only 13 Dark gold ore for the blacksmith troll.

### ISSUE THREAD

**Issue by gachikuku** [00-Evan/shattered-pixel-dungeon#1441]
Hello Evan, I dug the whole floor! 
The game generated only 13 ores and Blacksmith asks
for 15.

I play as a Warlock Strength 15, Health 90, Exp 80
seed LJZ-ZSP-PZC

Awesome game keep it up.

Alnoman Kamil

**Comment by 00-Evan** [comment]
The new floor is a tester area and is an extra on top of the regular game currently. You can also mine gold on the regular floors of the dungeon.
