### ISSUE TITLE
Disable drop/throw/unequip for equipped cursed items

### ISSUE THREAD

**Issue by 5225225** [00-Evan/shattered-pixel-dungeon#1443]
Minor quality of life thing, but the user shouldn't be given the option to even try to throw or unequip a cursed item, because it won't do anything. Especially throwing, which asks you to pick a direction and then tells you that you can't.

**Comment by 00-Evan** [comment]
I'd rather allow the player to attempt the action and then show text saying that they're prevented. I guarantee that if I removed the buttons I would get bug reports from players stating that the UI bugged out after they equipped a new weapon.
