### ISSUE TITLE
.desktop file improvement

### ISSUE THREAD

**Issue by MadameMalady** [00-Evan/shattered-pixel-dungeon#1447]
Your game is and has been compatible with both desktops and mobile linux devices.
If you add the following entry to your .desktop for the game, de's that support it will list it in the 'mobile only' section. (Phosh, for example):

X-Purism-FormFactor=Workstation;Mobile;

**Comment by 00-Evan** [comment]
Sorry, but I'm not interested in adding metadata for 3rd party distributions of the game.

**Comment by MadameMalady** [comment]
don't you package the flatpak build of this game? 
Also, this is for *your* release of your game, at risk of sounding mean, do you know what desktop environments are, and or what desktop files are?
what do you think exactly I asked?

flatpak is your release.
secondly, this is data that should be in your file already, thirdly, sorry for trying to help you improve your game -_-
You should really know what you're talking abt before being a rude ass to people.

**Comment by 00-Evan** [comment]
I don't release the game on flatpak actually, that's an unofficial distribution that I'm happy to allow, but have no interest in maintaining. You might consider asking the maintainers of that distribution if that'd like to make the change you're mentioning.

You can find links to official releases here: https://github.com/00-Evan/shattered-pixel-dungeon/releases
