### ISSUE TITLE
Feature request: improvements for e-ink screens 

### ISSUE THREAD

**Issue by mvonweis** [00-Evan/shattered-pixel-dungeon#1448]
E-ink is a perfect match for turn-based games where the board or map changes infrequently, such as Shattered Pixel Dungeon. However, it turns out to be impossible to play Shattered Pixel Dungeon on e-ink Android tablets. The application itself works fine, but the animations and graphics make the display a flickering mess.

1. The animations introduce constant flicker and consume extra battery. There would need to be a way to disable animations at runtime.
2. The graphic tiles become a low-contrast jumble of mid-grey pixels on grayscale screens. There would need to be a separate set of graphics assets with higher contrast and in some cases glyphs or icons. Potions especially would need a glyph-and-name system like scrolls have.

If system hardware can be reliably detected, "e-ink support" could be enabled automatically, otherwise a preference setting is necessary.

I'm aware that e-ink tablets are a niche product, but I still wanted to drop the suggestion here.

**Comment by Jak2k** [comment]
> * As you mention, potion colors in particular would be tricky for this.

Isn't there a small icon at every known potion?

**Comment by mvonweis** [comment]
> > * As you mention, potion colors in particular would be tricky for this.
> 
> Isn't there a small icon at every known potion?

That's right, and it's only for the identified potions.

Some further observations:
- Grass and trampled grass look identical, I can't see any difference at all.
- Unidentified potions are difficult. It's possible to distinguish between light colored potions and dark ones, but that's about it.
- The same goes for unidentified rings.
- The home screen, the character selection screen, all menus etc. are fine.

I have an Onyx Note Air2 Plus which offers several display modes. In slower modes ("normal", "regal"), the updated parts of the screen flicker badly. I forgot to mention that moving the map looks really bad, bordering on nauseating. Also animated tiles like water and fire are flickering badly. There's also the animations when you change levels etc. Using the faster "A2" or "X" modes, you can increase the frame rate of the display so that the animations become bearable, however ghosting becomes a problem after a little while. The best solution, in my opinion, would be to remove the animations or possibly slow them down to something like 1/2 fps.

I'll see if I can do some photos later.

**Comment by mvonweis** [comment]
Here's a video that shows the gameplay on e-ink:
https://www.dropbox.com/scl/fi/7pov79i7g43r6m7iwhvwx/eink-shattered-pixel-dungeon.mp4?rlkey=uvvs4votd32bjr3ex2jqxfzyq&dl=0

The standard mode flickers a lot, causing mild motion sickness after a while. Around the 2:05 mark I'm changing to speed mode, which seems to be fast enough to get rid of the flickering, but it leaves ghost images on the screen that make it difficult to see what's going on. The A2 and X modes have even more ghosting but no discernible effect on the flickering.

**Comment by 00-Evan** [comment]
Closing this as discussion has died down. I do still think this is a neat idea, honestly, but the amount of work it would require makes it completely infeasible to implement.
