### ISSUE TITLE
[Question] Is it intended to have one key but two chests?

### ISSUE THREAD

**Issue by 4164696f73** [00-Evan/shattered-pixel-dungeon#1449]
I have found multiple rooms with [one key and two chests](https://i.imgur.com/KKeSpCu.png) and I have no idea if I'm missing something or if it's a bug. 

In case it might be a spoiler, the maximum depth I've got to was 23 or 24. 

PS: (**SPOILERS!!!**) Please make those dumb scorpions not fire projectiles and move away in one turn...

**Comment by 00-Evan** [comment]
Yes, crystal keys/chests are usually about making a choice between different options, letting you customize the loot that you get a little. You can also examine the chest to get a hint  about what's inside of it.

Scorpios do not fire and move in one turn, you may be taking multiple turns to move toward them though, such as if you are crippled by their ranged attack.
