### ISSUE TITLE
UI improvement: Smooth scrolling

### ISSUE THREAD

**Issue by Akmal02** [00-Evan/shattered-pixel-dungeon#145]
Please add smooth scrolling feature when navigating through maps, like, continue scrolling the maps when user flick across it. I'd like to see this kind of eye-candy feature in it.

**Comment by 00-Evan** [comment]
Levels and scrolling lists in the game are all very small relative to screen space, don't you think this kind of functionality would be more annoying then helpful? Continuing the scrolling would just mean the camera would slide out of bounds.

**Comment by 00-Evan** [comment]
Closing this as no reply has been given, feel free to re-open this issue if you want to continue discussing it.
