### ISSUE TITLE
Sungrass issue

### ISSUE THREAD

**Issue by GyrateBalloon57** [00-Evan/shattered-pixel-dungeon#1450]
Encountered bug with Warden's Sungrass healing.

When the Warden receives the special healing effect from sungrass, they're unable to receive healing from healing potions (presumably until the Sungrass's healing effect wears off... although I didn't live to find out if this is the case)

Not sure if this is also triggered when a player of any class is using the standard Sungrass effect and tries to apply a healing potion. Definitely worth looking into though.

This was on the latest build,  V2.1.4

**Comment by 00-Evan** [comment]
This is intended, warden sungrass triggers the regular healing buff, and multiple sources of the healing buff do not stack. The game will pick the instance which has the most overall healing to give.
