### ISSUE TITLE
Infinite tick passing after resurrection by Ankh

### ISSUE THREAD

**Issue by Rojfos** [00-Evan/shattered-pixel-dungeon#1451]
This place seems like a good place to report a bug. If I've chosen poorly then I'm sorry.

I've played as a champion and then felt through a pitfall trap. I died, but my Ankh resurrected me. It resulted in me being stuck in an infinite tick and i couldn't do anything. Leaving to the main menu and loading the saved game fixed the issue. I know it's not game breaking, but I thought you'd appreciate any bug reports.

A short video with demonstration ---v
https://github.com/00-Evan/shattered-pixel-dungeon/assets/109231474/a7ca2b17-8d62-406f-9ee5-32a118275a32
game version: v2.1.4 (I play on the experimental build using play store)

I don't use github often. So if you need any additional information we don't really have any means of contact. I hope video helps with tracking the issue. Have a nice day Evan.

**Comment by 00-Evan** [comment]
Thanks for the detailed report. Unfortunately I'm not able to reproduce this. Falling through a pitfall trap and reviving to an unblessed ankh does not result in a freeze. It's likely that this is a race condition that may trigger very rarely, or may be device-specific. Unfortunately there's nothing I can do without being able to reproduce the issue.
