### ISSUE TITLE
Water in DM-300 arena gets electrified without adjacent floor trap

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#1452]
I had always assumed that the water in DM-300's arena gets electrified when it's adjacent to a floor trap, but in a recent run a puddle of water turned into a patch of lightning all on its own. This seems inconsistent with lightning trap + water behavior in the rest of the game.

Game version: 2.1.4

![Screenshot_20230806-084552](https://github.com/00-Evan/shattered-pixel-dungeon/assets/45757529/8a4858df-18e1-4835-92ad-643587f032e7)

**Comment by 00-Evan** [comment]
This is intended, the sparks are spawned directly on water and aren't spread from adjacent wire tiles. This is not the same effect as electricity.
