### ISSUE TITLE
[Minor visual] Sprite on Change weapon button is not updated after Scroll of Remove Curse

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1453]
I was playing Champion and had a Pickaxe which Bat blood as primary and an unenchanted +8 Runic Blade as secondary weapon. I returned the pickaxe to the blacksmith and equipped an unidentified Runic Blade in the primary slot. It was cursed, so the change-weapon slot showed a blinking sprite for the cursed pickaxe on the change weapon button. After using a Scroll of Remove Curse, the sprite on the button was not updated. Pressing the button fixed that minor glitch, however. I have not checked whether that also affects Scroll of Update or Transmutation.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Handing in an equipped pickaxe to the blacksmith correctly updates the weapon swap indicator to show no weapon in the secondary slot. It's possible that another in-development change incidentally fixed this.
