### ISSUE TITLE
Runic Slash’s +300 % enchantment power not working for Projecting 

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1454]
The description of Runic Slash claims that it increases the enchantement power by 300 %. However, this does not seem to work for Projecting, as the range is not increased.

**Comment by 00-Evan** [comment]
After a quick test the ability seems to work just fine for me. Runic slash correctly adds 3 additional tiles to the reach of a projecting runic blade when targeting the ability. This makes for 5 tiles of reach total.
