### ISSUE TITLE
Add checksums for every new release

### ISSUE THREAD

**Issue by StackOverflow4096** [00-Evan/shattered-pixel-dungeon#1455]
### Please add checksums
\(clearsigned with *pgp* key/s even better)

It would be nice for people to be able verify what they are downloading is legit

- **BTW:** I had no issues on linux just using the `.jar` by running:
`java -jar ShatteredPD-v2.1.4-Java.jar`

**Comment by 00-Evan** [comment]
I appreciate why this would be handy, but currently whenever I do a release of Shattered I built 10 separate binaries over 2 computers and 1 VM, 2 binaries need to be notarized by Apple, then those binaries are released over 6 platforms. I want to avoid adding even more complexity to this release process.
