### ISSUE TITLE
Top margin on Xiaomi Mix 4

### ISSUE THREAD

**Issue by drizt** [00-Evan/shattered-pixel-dungeon#1456]
Mix 4 has invisible front camera. So game can use whole display without margin for front camera hole. See screenshot. Area marked with brown color can be removed. 
![Screenshot_2023-08-09-15-32-29-759_com shatteredpixel shatteredpixeldungeon-edit](https://github.com/00-Evan/shattered-pixel-dungeon/assets/534665/22d782c9-8948-4be4-89af-8135b9f965c1)

You can point me where this mrgin placed in code and I will try to rebuild SPD for myself with required changes. 

Thanks for good game.

**Comment by 00-Evan** [comment]
Unfortunately currently there is no way to determine the difference between a regular hole-punch camera and an under-display camera in Android. Shattered doesn't know what it is, so it assumes it should not render over it and leaves the area empty. It's up to the device to report whether a particular area is safe to render in or not.
