### ISSUE TITLE
Unblessed ankh not giving the Player turn priority

### ISSUE THREAD

**Issue by RealFFF000** [00-Evan/shattered-pixel-dungeon#1458]
I had a +12 ring of arcana and wanted to try it with curse of bulk (stupid I know). I had one blessed and one unblessed ankh in my inventory. After activating the blessed ankh I died without getting any chance to take any action (I think this is intended change introduced the ankh rework)

The problem is however that after activating the normal ankh and teleporting to a random location I was still stuck and died (I didnt respawn in a door or anything)

And yes - I am aware that this bug is almost impossible to accidentaly replicate.

**Comment by 00-Evan** [comment]
Unblessed ankhs are not supposed to give turn priority, that functionality was entirely removed with the ankh rework. If you take an excessively long action, that will be reflected after you are revived.
