### ISSUE TITLE
Some users can get ShatteredPD via homebew now

### ISSUE THREAD

**Issue by dimatakoy** [00-Evan/shattered-pixel-dungeon#1459]
I just added a new way to install game. It may be useful for "advanced" MacOS users.

```sh
brew install shattered-pixel-dungeon
```

I will update the formula as new versions are released. If the user has previously installed the game, they will be able to receive updates through the game. 

Even if I'm a little late with the update, the user will always be able to get the new version :-)

https://github.com/Homebrew/homebrew-cask/pull/152804

**Comment by 00-Evan** [comment]
I'm closing this as it's not an issue, but thanks for letting me know!

I'm of course fine with others making unofficial distributions of Shattered, just please try to keep it updated reasonably quickly, and make it clear that your distribution is unofficial.
