### ISSUE TITLE
Feature pickaxe in the weapons list

### ISSUE THREAD

**Issue by SBasalaev** [00-Evan/shattered-pixel-dungeon#1460]
Since v2.0 pickaxe can be used like any other weapon, upgrades and all. Surely it is worthy to appear in the weapons list.

**Comment by 00-Evan** [comment]
The pickaxe is not intended to be a regular weapon that would appear in the list. It's upgradeable now for people who really want to do that, but it's not supposed to have a place alongside other regular weapons.
