### ISSUE TITLE
mobs not triggering unrevealed traps

### ISSUE THREAD

**Issue by cooltasty** [00-Evan/shattered-pixel-dungeon#1461]
non flying mobs not triggering unrevealed by player traps. also impossible open unrewealed door by trowing item into it. is it intented?

**Comment by Sarius997** [comment]
See https://github.com/00-Evan/shattered-pixel-dungeon/issues/251

Tldr: it is intended

**Comment by 00-Evan** [comment]
They are both intended. Secret doors in particular behave like walls before they are revealed.
