### ISSUE TITLE
Small Request: quickslotted bags show all items of applicable types even if the bags is full

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1463]
Sometimes you run into a situation where one of your bags (usually the seed poach) is filled up, and you end up with a few consumables in your main inventory. Is there a reason why quickslotted bags in such a case couldn't show items that would have been in that bag if there was room for them?

**Comment by 00-Evan** [comment]
quickslotting and tapping on the bag is meant to show that bag's contents. I appreciate why this is inconvenient but I don't think having them show potential additional items makes sense. It's worth noting that you can long-press on the inventory button to get a quick-use window for your entire inventory.
