### ISSUE TITLE
Alchemy guide - result potion icon wrong shape for unidentified potions

### ISSUE THREAD

**Issue by jcttrll** [00-Evan/shattered-pixel-dungeon#1464]
Very minor, but in the alchemy guide to exotic potions, unidentified potions show an outline of the triangular necked flask, rather than an outline of the round flask, in the result column. Identified potions show the round flask, as expected.

![Screenshot_20230822-073123](https://github.com/00-Evan/shattered-pixel-dungeon/assets/6539951/1b5d7e5f-0bc9-4985-bedf-170e05e6345a)

**Comment by 00-Evan** [comment]
This is intentional. Exotic potions are still a type of potion, and so use the potion placeholder sprite. They aren't distinct from regular potions in most cases aside from how they're acquired.

**Comment by jcttrll** [comment]
Ah, OK. Thanks for explaining.
