### ISSUE TITLE
Updating MacOS release to a Universal binary

### ISSUE THREAD

**Issue by Morgon** [00-Evan/shattered-pixel-dungeon#1465]
Hello! I'd love to check out this game (noticed it in a `brew` package manager update), but I don't allow Rosetta or system-wide Java bloatware on my computer.

Would it be possible to update the compiled binary to be Universal so that ARM Macs can natively get in on the fun?

**Comment by 00-Evan** [comment]
I would like to switch to a universal binary at some point in the future, but it is not a priority currently. Shattered has library dependencies that use native code, many of which are still using intel binaries in their latest official release.

I appreciate that having the game run natively would be best, but Shattered is lightweight enough to have no noticeable performance impact when running via Rosetta 2. I also think requiring Rosetta 2 for Shattered is entirely reasonable at this point in time.

Lastly, while you're absolutely welcome to use the brew release, please do note that it is an unofficial release and is not maintained or supported by me.
