### ISSUE TITLE
Shopkeeper buyback feature is clunky - a recommendation

### ISSUE THREAD

**Issue by jagprog5** [00-Evan/shattered-pixel-dungeon#1466]
The shopkeepers dialog options should instead be:

- Sell an item
- Buyback an item
- Talk

That is, buying back a recently sold item should not appear at the top level screen.

Additionally, this new buyback dialog (reached from "Buyback an item") should display 3 slots. These slots should display the same buttons showing the items to buy back that exist in the top level shopkeeper dialog currently. The slots should be disabled and/or empty if there is no recent item to buyback. This hints to the user that only up to the latest 3 sold items can be bought back. Currently there is no indication for this if items haven't yet been sold.

**Comment by 00-Evan** [comment]
Shops will eventually move to an entirely interface-based system, which may more closely resemble what you're suggesting. Until then, I have no plans to make further interface changes.
