### ISSUE TITLE
Glyph of potential interacting with duelist weapon recharging 

### ISSUE THREAD

**Issue by jagprog5** [00-Evan/shattered-pixel-dungeon#1467]
If I closely inspect the wording for weapon recharging: "... when under the effect of wand or artifact recharging buffs."

I get that Glyph of potential doesn't apply a buff status and instead just increments wand charge. But should it be this way? Should it not instead apply a short lasting recharging buf for consistency with other ways that charges are typically granted?

Thanks

**Comment by 00-Evan** [comment]
Yes, that is intended. There are actually a few cases where wand charges are affected directly, instead of via the recharging buff.
