### ISSUE TITLE
scrying and inspection

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#147]
When scrying with the talisman, revealed items, monsters, and tiles cannot be inspected for information.

**Comment by 00-Evan** [comment]
I'm aware of this one, a fix will be included in the next major update.

**Comment by camlost** [comment]
Also affects mind vision.

**Comment by 00-Evan** [comment]
yup, the fix applies to both.

**Comment by 00-Evan** [comment]
fixed in commit 591b96fb811528bb68ebd1e7e3aa146d6211aa74
