### ISSUE TITLE
Fullscreen glitch on Android 13

### ISSUE THREAD

**Issue by gatopeich** [00-Evan/shattered-pixel-dungeon#1470]
Playing Shattered on a Fairphone 3 with Android 13, full screen mode expands the screen visually but not the touch area, so touches hit higher than they should.

This worked fine on Android 11 and I cannot be sure if it is a problem of the Fairphone's port of Android 13... only I have not observed it on other apps.

**Comment by 00-Evan** [comment]
A quick video of this might be helpful. Does this happen with or without power saver on as well, as that setting can sometimes affect UI input.

I'd lean toward this being a fairphone issue, as this hasn't been reported to me from any other users, and Android 13 is a pretty high percentage of the playerbase.

**Comment by 00-Evan** [comment]
Closing this due to lack of reply. If anyone else (including the author) gets this issue and can provide more information I'll be happy to re-open.

**Comment by gatopeich** [comment]
Yeah, likely a Fairphone issue. Thanks anyway!
