### ISSUE TITLE
There is no message when player is killed by a necromancer

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1477]

**Comment by chorby-short** [comment]
I didn't have enough time for a full summary earlier (I was on my way to go somewhere), but basically the necromancer was never given a player death message because it presumably wasn't anticipated that a necromancer would be able to kill the player, as they don't have an 'attack', per se. However, if a player cannot be forced out of the space where the summoning will take place (i.e. they're surrounded by other mobs) and walk onto the summoning tile), they will take the standard damage from blocking a summoning seen elsewhere in the game. This counts as a magical attack by the necromancer itself; thus, when a player is killed, they will endorse the Zapped death badge and will count as being killed by the necromancer (hence how I noticed the lack of "killed by" message). Not sure if this is explicitly intentional, but don't know what alternative there could possibly be for any of this, because it all makes sense with the game's mechanics.

**Comment by Lyx0527** [comment]
Not just necromancers. Dwarf King can also kill players like this. In extremely rare cases, skeletal remains with cursed equipment can kill players.There are no message, too.

**Comment by 00-Evan** [comment]
@chorby-short thanks for the explanation, though in this case I did get your meaning from the title.

> Not just necromancers. Dwarf King can also kill players like this. In extremely rare cases, skeletal remains with cursed equipment can kill players.There are no message, too.

Will add a message for Dwarf King too. For remains, that's not intended to be able to kill you, so there isn't even a rankings entry recorded currently.

**Comment by 00-Evan** [comment]
fixed in commit d5efcdd93da563541854501abf4525bc08534a0d
