### ISSUE TITLE
Resuming move ignores being zapped

### ISSUE THREAD

**Issue by ffxsam** [00-Evan/shattered-pixel-dungeon#1478]
I was moving toward a destination on the map, which was interrupted by losing HP due to hunger. I ate, then tapped the arrow to resume movement, and got zapped several turns by an enemy.

Expected behavior: Getting attacked at all should immediately stop the auto movement.

Version 2.1.4.

**Comment by 00-Evan** [comment]
This is intended. The 'continue moving' indicator is for when you want to keep moving to a destination and ignore other factors. You can always tap pretty much anywhere on the screen to cancel a move.
