### ISSUE TITLE
Prison guards have increased their cripple time by 1 turn

### ISSUE THREAD

**Issue by Aim226** [00-Evan/shattered-pixel-dungeon#1479]
Prior to beta, prison guards inflicted 4 turns of cripple, which immediately went down to 3 on the turn you were pulled in (either that or it was just 3 turns of cripple). However, now the prison guards seem to be inflicting 5 turns of cripple which goes down to 4 immediately after being pulled in (either that or it was 4 turns of cripple). In both of these cases I did not move after being chained, I have no movement speed affecting items and the turnwheel/partial turn indicator is full/empty/not showing (however it's interpreted lol)

This screenshot is showing the 3 turns before the beta (in debug)
![Screenshot_2023 09 12_19 28 38 644](https://github.com/00-Evan/shattered-pixel-dungeon/assets/134911982/505477eb-b288-4823-acb6-be1ce929142a)

These screenshots show the 4 turns during beta
![Screenshot_20230912-193331](https://github.com/00-Evan/shattered-pixel-dungeon/assets/134911982/46edb085-7c3b-45b3-80ca-36f56b90fd33)
![Screenshot_20230912-193346](https://github.com/00-Evan/shattered-pixel-dungeon/assets/134911982/3353db63-cd9f-4a2e-9536-8f05638323c9)
![Screenshot_20230912-193339](https://github.com/00-Evan/shattered-pixel-dungeon/assets/134911982/3beffb49-151d-4d8c-9c5a-83edafbb5da6)

**Comment by 00-Evan** [comment]
This is an intended tack-on change caused by internal code corrections to how pushing/pulling vfx are processed. The cripple was always meant to last for 4 turns, not 3.

Additional, your first screenshot is not from Shattered Pixel Dungeon. Please do not report bugs in other versions of the game, or unofficial distributions of Shattered.

**Comment by Aim226** [comment]
Ok, fair point. However, if it was an unintentional change from v2.2.0 beta that would still be left in the game, then shouldn't the change be noted in the beta changelogs?
