### ISSUE TITLE
Pickaxe drops on heroic remain

### ISSUE THREAD

**Issue by Highseekerz** [00-Evan/shattered-pixel-dungeon#148]
if blacksmith quest is already completed
pickaxe has no "bone=false" code

**Comment by 00-Evan** [comment]
reopening as this has not been fixed in the open source yet. I'll close this and reference the commit once 0.5.0 source releases.

**Comment by 00-Evan** [comment]
fixed in commit 0f79e3a5de24d34959d4aa6d0dd5b6a77d1ca09d
