### ISSUE TITLE
Can't examine fading prismatic image

### ISSUE THREAD

**Issue by ropeFullOfHope** [00-Evan/shattered-pixel-dungeon#1482]
![Screenshot_20230914_000610](https://github.com/00-Evan/shattered-pixel-dungeon/assets/104153774/87941649-09d2-4990-ba28-447ff26800ed)
After my prismatic image has been killed by an eye laser it probably entered a berserking state. It has no AI (it won't attack, won't move and cannot swap places with my character) and inspecting it yields the "You don't know what is there" message. It died a few turns later.

**Comment by 00-Evan** [comment]
There is a mild UI bug here in that the description of the prismatic image should appear, but otherwise this is intended. Prismatic images do not get class benefits like raging, they will fade away when at 0HP unless they are healed.

**Comment by 00-Evan** [comment]
Fixed in BETA-0.5
