### ISSUE TITLE
recycle turn scroll into exotic scroll

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1484]

**Comment by 00-Evan** [comment]
I can see that this is occurring in v2.2.0-BETA-0.4. In future please mention which version of the game you're getting the issue in, or include a screenshot which shows the version number.

**Comment by Lyx0527** [comment]
I will

**Comment by 00-Evan** [comment]
Fixed in BETA-0.5
