### ISSUE TITLE
About Ascension and Traps

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1485]
The lethality of certain traps does not belong to the level of 26 floor.  Disintegration trap, rockfall trap, flashing trap, guardian trap, poison dart trap, gripping trap, all gas trap.

**Comment by 00-Evan** [comment]
This is intended. Traps are tied to their dungeon floor, and so do not suddenly become stronger when ascension starts. Enemies like mimics and statues, that are spawned as part of levelgen, behave the same way.

I can see that geyser traps are incorrectly using the scaling depth value, will fix that. Will also consider allowing traps to scale in the case where they are used by the reclaim trap spell.

**Comment by chorby-short** [comment]
But during ascension, shouldn't traps have a danger level befitting to the late game feel of ascension? It makes it far harder to use them against enemies, and largely nonhazardous for the player. By that same degree, certain potions and enchantments where the damage is dependent on depth suddenly becoming much weaker during ascension is rather annoying— corrosion (the curse) especially comes to mind.

**Comment by 00-Evan** [comment]
@chorby-short potions/enchantments are not tied to level generation, and should behave as if they are on floor 26 during ascension. Corrosion inflicts ooze for example, which does work with the ascension challenge.

**Comment by 00-Evan** [comment]
fixed in commit 5a1d6e5d91ba249c53895592bfb6038afc4a0898
