### ISSUE TITLE
Weird visual bug during goo boss fight

### ISSUE THREAD

**Issue by dragid10** [00-Evan/shattered-pixel-dungeon#1487]
Unfortunately I'm not entirely sure what even triggered this bug. I was just walking around the stage before fighting the goo. I think I pulled my notification shade down and when I came back into the game, it looked like this 
![Screenshot_20230914-122558](https://github.com/00-Evan/shattered-pixel-dungeon/assets/4042877/578fd1bb-dd48-4a03-bbb7-a32b62432066)

I also [captured a screen recording](https://photos.app.goo.gl/oaxa3ea1LCStjKrG8) that is too big to upload

As a side note, having some issue templates for the repo might be beneficial in receiving bugs from users. That way you can direct them to provide all the relevant information you'd need to investigate bugs

**Comment by 00-Evan** [comment]
This is a graphics hiccup that is likely device-specific and impossible to reproduce. Something caused your device to kill some of the textures the game had loaded. This sort of hiccup is very rare and can be solved by going back to the main menu and then returning to the game.

Regarding templates, it'll just turn into more text to sort though. I'm not generally interested in people trying to explain what they think is wrong with the game, a simple screenshot and/or 1 sentence description is generally plenty.
