### ISSUE TITLE
teleporting evil eyes

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#149]
When evil eyes are teleported away,  they still cast their disintegration beam.

**Comment by 00-Evan** [comment]
Eyes should still shoot their beams after teleporting, but it does seem that the beams are hitting the player when they shouldn't be, or are at least not being very clear in where they are coming from.

Will investigate and either bugfix or improve clarity, depending on what's needed.

**Comment by 00-Evan** [comment]
After some testing I've concluded that what's happening here is that the eyes are being teleported to a valid location to shoot you, but the visual effects are not clearly showing that the beam is being shot.

I've adjusted the logic to correct this, so if you teleport an evil eye to a location where it still has a valid shot on you, you'll now see the beam coming up of the darkness towards you when you're hit.

**Comment by 00-Evan** [comment]
clarity improvements were made in commit dc4f3ebfeae95949a3f8ad0c52149df742510f4a
