### ISSUE TITLE
Passive regeneration time of yog is too short

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1491]
Fighting with fists won't even extend the time.
In fact, it is almost unnecessary to impose regeneration restrictions in battles with Yog. No one can procrastinate under the attack of lasers and demons.

**Comment by 00-Evan** [comment]
Fists and Yog itself both give time when damaged. 900 turns total on normal gameplay (500 for yog and 150 for each fist), and 833 with badder bosses (333 for yog and 75 for each fist).

**Comment by Lyx0527** [comment]
> Fists and Yog itself both give time when damaged. 900 turns total on normal gameplay (500 for yog and 150 for each fist), and 833 with badder bosses (333 for yog and 75 for each fist).

Something must be wrong with the fist.I hope you can check it out.
Rejuvenating steps has ineffective more than once in battles with fists.

**Comment by 00-Evan** [comment]
Rejuvenating steps is also tied to EXP gain. You can produce a total of 100 grass per hero level at +1, or 200 at +2

**Comment by Lyx0527** [comment]
> Rejuvenating steps is also tied to EXP gain. You can produce a total of 100 grass per hero level at +1, or 200 at +2

So how do I explain that it can take effect again after I hurt Yog? I didn't drink experience potion

**Comment by 00-Evan** [comment]
> > Rejuvenating steps is also tied to EXP gain. You can produce a total of 100 grass per hero level at +1, or 200 at +2
> 
> So how do I explain that it can take effect again after I hurt Yog? I didn't drink experience potion

In that case it's possible that one of the fists has an error with its damage tracking logic. Is there a particular fist this tends to happen with?

**Comment by Lyx0527** [comment]
> > > Rejuvenating steps is also tied to EXP gain. You can produce a total of 100 grass per hero level at +1, or 200 at +2
> > 
> > 
> > So how do I explain that it can take effect again after I hurt Yog? I didn't drink experience potion
> 
> In that case it's possible that one of the fists has an error with its damage tracking logic. Is there a particular fist this tends to happen with?

I tested it in 2.1.4 mod version. Every fist won't prolong the time. 
I exhausted my time and dealt 150 damage to fist, but there is no regeneration. 
And because of barren land challenge, I couldn't trigger this talent so many times.

**Comment by F-LTP** [comment]
> Fists and Yog itself both give time when damaged. 900 turns total on normal gameplay (500 for yog and 150 for each fist), and 833 with badder bosses (333 for yog and 75 for each fist).
I find the mistake , dmgTaken is wrongly calculated. From YogFist.java.
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/45702488/80112ea5-ede9-43a7-ba6c-3dae930baf8a)

**Comment by 00-Evan** [comment]
@F-LTP sorry but I've edited your message, I don't accept code contributions due to potential issues with copyright and the GPL license. I'll look into this and see what cases cause fists to not trigger regen.

**Comment by 00-Evan** [comment]
fixed in commit 9c7b78fd3e81aab0fbbed23fb26071d0121a2248
