### ISSUE TITLE
Remote Control support

### ISSUE THREAD

**Issue by basxto** [00-Evan/shattered-pixel-dungeon#1495]
It would me interesting to support playing on Android TV and Fire TV with a remote control. With a controller it already works. It would be nice to have that at least in mind when adding gamepad/keyboard support for menus and windows.

According to ~~Google~~Alphabet a remote control has at least 4 directional buttons, select button, back button and home button https://developer.android.com/training/tv/start/controllers

Fire TV should have one less since they don’t allow to intercept home button. https://developer.amazon.com/docs/fire-tv/remote-input.html

They share: `KEYCODE_DPAD_UP`, `KEYCODE_DPAD_DOWN`, `KEYCODE_DPAD_LEFT`, `KEYCODE_DPAD_RIGHT`, `KEYCODE_DPAD_CENTER` and `KEYCODE_BACK`

I hope the names on their sites are correct, I get different ones via `adb shell getevent -lt`

I played a bit arround with the Fire TV remote:

`KEYCODE_DPAD_CENTER`, `KEYCODE_MEDIA_REWIND`, `KEYCODE_MEDIA_PLAY_PAUSE` and `KEYCODE_MEDIA_FAST_FORWARD` don’t do anything and can’t get bound via settings.

`KEYCODE_MENU` opens the inventory, but that can’t be changed since it can’t get bound.

`KEYCODE_BACK` can’t be bound but neither cancels the key bind window.

"select" button of my gamepad also doesn’t work, that should be `KEYCODE_BUTTON_SELECT`

--

Currently the only way to leave a running game with a remote control is the home button, which feels wrong. That becomes relevant when a bluetooth gamepad’s battery gets empty.

**Comment by 00-Evan** [comment]
While this would be nice, 7 buttons simply isn't enough to be able to control the game to any reasonable degree, unless you fancy binding the direction keys to the virtual cursor and the 3 buttons to left/right/middle click, which would be painfully slow. I'd prefer to spend time building better control or keyboard support into the game.

I am surprised that KEYCODE_BACK doesn't quit out of the game though, as that's the same keycode (4) that gets sent by the back navigation button/gesture on a phone. If I had to guess it's because Shattered's game controller library is not built to support remotes.

**Comment by basxto** [comment]
> While this would be nice, 7 buttons simply isn't enough to be able to control the game to any reasonable degree, unless you fancy binding the direction keys to the virtual cursor and the 3 buttons to left/right/middle click, which would be painfully slow.

I had somewhat a further radial menu in mind that allows to get to the two currently implemented radial menus, to enter a virtual cursor mode that could be exited with "back", to open journal/inventory/hero info and actions examine/attack/pickup/wait/rest/special or windows and actions each with their own radial menus reachable from the super menu.

> I am surprised that KEYCODE_BACK doesn't quit out of the game though

It’s the same with ESC key. In a running game it just opens and closes the menu that gets you to settings and main menu, which can’t be used by keyboard/gamepad.

> as that's the same keycode (4) that gets sent by the back navigation button/gesture on a phone

yes, it’s the same behavior on a phone, it opens and closes that menu.
