### ISSUE TITLE
I can directly know the level of the unidentified ring

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1499]
It is +1
![Screenshot_20230920_192049_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/40260a6a-4039-4234-92a2-c42fa21471e4)

**Comment by 00-Evan** [comment]
On consideration I'm fine with allowing this, one of the rings must be IDed.
