### ISSUE TITLE
There are still bugs in the texture of the plenty horn

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1502]
Charge from 5 to 6 and from 7 to 6 is different
![Screenshot_20230920_235604_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/4bdffa92-a65a-406a-a35f-0dd7a157be03)
![Screenshot_20230920_235835_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/28f91a7a-bae5-40af-9812-e91259a817ea)

**Comment by 00-Evan** [comment]
> still

As far as I'm aware this is the first time this has been reported to me. It seems like some of the horn's charge logic is still using numbers from back when it has 20 max charges, instead of 10.

**Comment by Lyx0527** [comment]
In my memory, the texture of horn was fixed once
At that time, the texture of the horn was always the same as the old horn with same charges.

**Comment by 00-Evan** [comment]
fixed in commit ab67766c66e1423f7c414eda1eb1a9751836c7cd
