### ISSUE TITLE
Why does Scorpio attack the Demon Ripper

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1503]
None of them are my allies. They are not dominated by amok or targeted. 
Before the time shown in this video, targeted received by Yog has just ended, I controlled a Scorpio with a siren scroll, it's still alive. 
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/3a245ca4-fd40-469d-949a-a0fab235dabe

**Comment by 00-Evan** [comment]
I'm not certain. Something caused the scorpio to choose that ripper as its target, but without more information about the game state leading up to that point I can't really say why, especially with everything that is going on in that scenario.

**Comment by Lyx0527** [comment]
Today, I saw this bug again. This time, it is still targeted yog that causes the Ripper to be attacked by the Evil Eye

**Comment by Lyx0527** [comment]
@00-Evan I can stably reproduce this bug now. After the targeted duration ends, if yog does not summon fists, all minions will attack the minions who finally hits yog's eye. Scorpions even shoot themselves.This seems to be related to the AI that prevents bees from attacking the eyes unobstructed.

**Comment by 00-Evan** [comment]
I was able to reproduce this based on an email report and have already fixed it indev for 2.4.0
