### ISSUE TITLE
Cannot mine at Level 13

### ISSUE THREAD

**Issue by indicozy** [00-Evan/shattered-pixel-dungeon#1504]
![RDT_20230922_2139151298836996343413801.jpg](https://github.com/00-Evan/shattered-pixel-dungeon/assets/51142471/b84e257c-1945-4abd-a2c4-67b3c048b239)

Hi there!

I cant mine at this level because my pickage was removed by blacksmith. Ive given him 15 gold and he took my pickaxe back.

**Comment by 00-Evan** [comment]
The mining area in v2.1.4 is just meant for testing out the mining mechanic. You don't need to mine gold ore in it, and you don't need to explore it to continue your run.

**Comment by indicozy** [comment]
Yes, there was second ladder at floor 12. Thanks for reply
