### ISSUE TITLE
Duelist food talents stack incorrectly for other classes

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1505]
![Screenshot_20230923-113638](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/d0ddfa09-26f1-4f44-9efd-00a8caa7f83d)

Rather than combining the level/2 + 3 for the first hit and then having a simple +3 for the next two hours, it uses level/2 for all three

**Comment by 00-Evan** [comment]
fixed in commit cd2a70aea3c35e80729c73d0e36ca2a1509d2155
