### ISSUE TITLE
About BGM

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1506]
Using the tooltik resulted in playing incorrect tracks
The third and fifth bosses are all like this, and the fourth boss should also be like this

https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/ac961807-e9b8-4fdb-9a26-cd30738dfb62

Defeating the fifth boss and quickly going downstairs will result in no tracks being played.

Summoning elements outside the room where the ritual site is located will not play intense track, until the element enters the room where the hero is located

How about applying the intense track of Demon Hall to the battle against Demon Spwaners?

**Comment by 00-Evan** [comment]
fixed in BETA-1.0
