### ISSUE TITLE
Key behind barrier, liquid flame behind locked door

### ISSUE THREAD

**Issue by jsera** [00-Evan/shattered-pixel-dungeon#1507]
The key for a locked room was behind a barrier, but the option of liquid flame was in that locked room.

I think there might have been two locked rooms on lv4, and if you opened the right one first, you wouldn't get stuck, but that's a blind 50/50 chance, and not good gameplay.

Dungeon seed:
QTW-TLK-TNQ

Version:
2.1.4

**Comment by 00-Evan** [comment]
This is intended, it can rarely happen and forces alternative solutions to these sorts of puzzles.
