### ISSUE TITLE
Where is my 40th piece of gold

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1508]
![Screenshot_20230930_221326_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/b89f589a-f62d-4677-98c0-ca54f30a4d9e)
![Uploading Screenshot_20230930_221329_6f3fe77889fbecf862f7061166760abf.jpg…]()
![Screenshot_20230930_221401_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/8d6fe692-46b3-470a-b6ea-361c1e35476a)

**Comment by Lyx0527** [comment]
The food consumption caused by excavation is quite unacceptable
![Screenshot_20230930_221329_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/a0d3c873-22e8-43ef-969f-ae0af65c8e40)

**Comment by Lyx0527** [comment]
Digging for gold will not damage the crystal

**Comment by 00-Evan** [comment]
Secret room is in the bottom left, note that little tunnel that seemingly goes nowhere.

Hunger cost is intended

Digging gold not breaking crystals is intended.
