### ISSUE TITLE
notes screen and back button

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#151]
When typing notes in the hall of heroes, the back button should probably close the notes screen.

**Comment by 00-Evan** [comment]
This the back button is disabled here for two reasons:

1. to prevent accidentally closing the window, especially given that people will also tap back to hide the software keyboard.

2. pressing back is ambiguous, does the user want to save the note or not? By forcing them to either hit save or cancel the game can be sure.
