### ISSUE TITLE
Pickaxe not counting as a weapon for the duelist

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#1511]
The duelist has the talent "swift equip" that allows her to quickly equip weapons from either your quickslots or the quick-use menu. But the pickaxe behaves differently compared to other weapons. In the quick-use menu it doesn't show up (unless it's already equipped) and you can't asign it to a quickslot (unless when you equip the pickaxe you already have your equipped weapon asigned to a quickslot)

**Comment by 00-Evan** [comment]
Using quisklots or the quick use menu isn't required for swift equip. The current pickaxe behavior is slightly odd because the item still has existing quickslot behavior from the old caves quest.
