### ISSUE TITLE
Sub floor

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1515]
1. Cash out can be clicked repeatedly. When 0 favor, Cash out should not be available.

https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/f4ed600a-a7a1-41b5-ae8f-619e746f920f

2. Beacon of return. May warping beacon the same. 

https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/3578dda1-2f90-4838-913a-aab6ce8cdb31

3. After the warning of  spire's attack appears, leaving the room where the spire is located will cause the attack to pause. Return to the room and the attack will continue. 

4. The texture of the spire is too large to see anything in the square above it. Even the hero.
![Screenshot_20231004_210400_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/e4374b86-4d4f-4508-b520-8a72ebfb53b4)

**Comment by 00-Evan** [comment]
4 is intended, will investigate others

**Comment by 00-Evan** [comment]
Fixed in v2.2.0-BETA-1.3
