### ISSUE TITLE
Quickslots not always preserved upon picking up bags.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1517]
If a bag containing items is dropped, and then an item type that is present in the bag is picked up and quickslotted, then the quickslot will become empty upon picking up the bag.
![Screenshot_20231005-172626](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/d077ea2b-b6ea-4928-8771-4a3935c349b9)

**Comment by 00-Evan** [comment]
This is an intended result of re-collecting a bag. The item that you have in both the bag and inventory is merged into the bag, and so the item instance you have quickslotted no longer exists.

**Comment by chorby-short** [comment]
But why shouldn't it merge the other way for quickslot purposes? If I have one scroll and add it to a 5,000 stack, why doesn't the five thousand get added to the quickslot, rather than the other way around?

Aside from that, it also doesn't remain consistent when you have more than one quickslot of the same item emptied. Say you have four quickslots. You throw one of a missile stack, drop the holster, grab and quickslot the other missile item, and pick up the holster again. The one quickslot is now emptied, as apparantly was intended? Then quickslot the missiles in another slot, throw all the missiles again, and upon picking them up they will be automatically assigned to the first of the two quickslots registered to that item, regardless of which one was assigned to the holster and which one was assigned to the bag. Isn't that inconsistent at least? It can be a weird effect especially when one of the quickslots is not visible, as seen here: https://www.reddit.com/r/PixelDungeon/comments/16zqwuj/comment/k3g5zb8/?context=3
