### ISSUE TITLE
Time freeze breaks ability cooldown indicator. 

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#1518]
If you use meditate ability when time is frozen, the ability cooldown indicator glitches.
![Screenshot_20231007_163433.jpg](https://github.com/00-Evan/shattered-pixel-dungeon/assets/44932833/be2d62f2-f769-4136-b014-7084fd62b8b0)

**Comment by 00-Evan** [comment]
fixed in commit a768e9d3981421c746f40833a2dd5bc85d9b27df
