### ISSUE TITLE
About armband

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1519]
How about adding a confirmation prompt when stealing goods when the charge of armband isn't enough

**Comment by 00-Evan** [comment]
In general I try to avoid adding more 'are you sure?' style confirmation prompts, as they clutter up the interface. Do you think there's a particularly large number of people who are accidentally hitting the button?

**Comment by Lyx0527** [comment]
In fact, I made this request because when I was watching live broadcasts about SPD, I found that many people mistakenly used stealing instead of purchasing due to negligence. 
I collected opinions from players from the SPD community in China. 
The voting result obtained is: add confirmation prompt: without prompt, it is 9:1
The only person who voted against, his opinion is that this mistake would make the live broadcast more enjoyable.

**Comment by Lyx0527** [comment]
Even without adding new confirmation prompts, I have collected the following viewpoints to instead it.
Changing the position of the steal button away from the purchase button can also greatly avoid accidental click. 
Directly use the steal button on the armband to click on the square where the hero is located to steal goods.

**Comment by 00-Evan** [comment]
Just because players vote for something doesn't mean it is a good idea to add it to the game. I suspect players would also vote in favor of a confirmation prompt when tapping on visible traps.

There's also the issue of consistency. I understand the desire for a conformation prompt here, but there are lots of other cases where the player might mistap when using options on an item, should all of those cases have confirmation prompts as well?

I'll consider this, but please don't use community votes as a basis for game design suggestions.

**Comment by Lyx0527** [comment]
> I suspect players would also vote in favor of a confirmation prompt when tapping on visible traps.

Perhaps you are right. I did initiate a vote, and the result was 8:2. 
But there are still differences between these two issues. Traps are present in every game, but armband not so often. In most games that do not use armband, players do not need to carefully choose the 'purchase method' when buying goods, and can spend money without thinking. But armbands disrupt players' original shopping habits. 'Steal' and 'buy' are so close that I have seen some players use armband with only 1 charge to steal potion bags from stores on the 6th floor.

**Comment by 00-Evan** [comment]
People always bring up the potion confirmation prompt, which is a great example actually. That one was added in the original Pixel Dungeon, and I disagree with it. I would not have added it, but it's too late to remove it now.
