### ISSUE TITLE
Improve armor description

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#152]
If an armor doesn't block any damage it doesn't have much sense to write "blocks 0-0 damage".

What about writing "doesn't block any damage" instead or if it isn't upgrated yet - "blocks up to *x* damage" instead of "0-*x*"?

**Comment by 00-Evan** [comment]
0-0 is accurate, and I'd rather keep the description format consistent between all armor states.
