### ISSUE TITLE
Themed icon support 

### ISSUE THREAD

**Issue by flexagoon** [00-Evan/shattered-pixel-dungeon#1521]
It would be great if the Android version of SPD supported the "themed icon" feature introduced in Android 13

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by Jak2k** [comment]
You could use the arcticons-pack for that.

**Comment by flexagoon** [comment]
@Jak2k I could, but I don't want to use custom icon packs. I shouldn't have to completely change the way my apps look in order to use a basic Android feature.

**Comment by flexagoon** [comment]
@00-Evan Android 13+ is used by 30% of devices at this point, and pretty much every app on my phone except SPD supports themed icons

**Comment by flexagoon** [comment]
> I dont have a single game that supports it. 

@Jak2k I'm not sure about games, since SPD is the only gave I have on my phone. But yeah, games are generally really bad in terms of supporting new Android features.
