### ISSUE TITLE
From beta, triggering glyph of entanglement seems to resist damage completely.

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1523]
Beta 0.2, Armor 0－6, Gnoll Shaman deals 0 damage during Ascension

**Comment by 00-Evan** [comment]
during ascension entanglement's earthroot armor effect would block 15 damage in addition to the 0-6 from your armor. Shamans would deal 12-25 damage in melee range during ascension, making taking 0 damage fairly common.

**Comment by Lyx0527** [comment]
> during ascension entanglement's earthroot armor effect would block 15 damage in addition to the 0-6 from your armor. Shamans would deal 12-25 damage in melee range during ascension, making taking 0 damage fairly common.

Can +0 entanglement cloth armor provide 6 herbal armor without arcana ring？

**Comment by Lyx0527** [comment]
0－4 from round shield

**Comment by Lyx0527** [comment]
It's my fault, I misunderstood the way Herbal Armor takes effect
