### ISSUE TITLE
Not identified item and armor by wearing them

### ISSUE THREAD

**Issue by aloncar** [00-Evan/shattered-pixel-dungeon#1525]
In mid game, when I already had one ring identified by wearing it, second one and new armor was not able to be identified by wearing them (I'm pretty sure). v2.2.0

**Comment by aloncar** [comment]
Hi, is there are debug mode to make it easier to track changes.
I'm pretty sure I have wore it for a long time where I have gain lot's of levels.

**Comment by 00-Evan** [comment]
There is no debug mode unfortunately. Adding such a mode would cheapen the regular game, as players could get whatever items they want anytime in debug mode.
