### ISSUE TITLE
Game thread hang during auto run

### ISSUE THREAD

**Issue by bjthinks** [00-Evan/shattered-pixel-dungeon#153]
I was using auto run to travel, when I stepped into a door and was spotted by a Dwarf Warlock. The game thread hung, with the progress spinner spinning. I used back -> main menu... to resume my game, at which point the Dwarf Warlock was able to attack and everything continued as normal.

![screenshot_20170115-124602](https://cloud.githubusercontent.com/assets/306373/21966670/c10689fa-db2c-11e6-9dfe-63f718d12402.png)

**Comment by 00-Evan** [comment]
Does this happen with any consistency? There isn't much I can do if the issue can't be reproduced.

**Comment by bjthinks** [comment]
This is the only time I've seen it in many hours of play. If this isn't enough to go on, then no worries.

**Comment by pixeled4life** [comment]
This happened to me a couple times: once in vanilla PD and another time in Shattered, I don't know what caused it but the enemy and me were both at a door both times.This is probably not enough to help but it seems too rare to be annoying anyway
