### ISSUE TITLE
Rot Heart gas cloud issues

### ISSUE THREAD

**Issue by voronaam** [00-Evan/shattered-pixel-dungeon#1531]
There are issues with the poisonous cloud in the new room version. In some configuration the cloud never reaches the square right next to the Rot Heart making it trivial to kill it.

![Screenshot_20231025-100631-087](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2351069/491c53fd-2c5b-4dc3-be29-d88ce2c55c38)

**Comment by 00-Evan** [comment]
Previously the rot heart spread a constant 20 units of gas. I reduced that to be dependent on the number of open adjacent cells, with a minimum of 6. Perhaps it needs to be tuned up a bit.

**Comment by 00-Evan** [comment]
Changed in commit 1fca4c4f88205b09a7bafcb522d0472211984b1f
