### ISSUE TITLE
Can't load gdx library

### ISSUE THREAD

**Issue by drizt** [00-Evan/shattered-pixel-dungeon#1532]
After updating to v2.2.0 I can't start app. It shows me sucherror 
![Screenshot_2023-10-26-20-59-31-540_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/534665/6be85530-30b0-45e5-9fe3-14e0f01d0bd2)

How it happens. 
1. Upgrade app from F-Droid
2. Touch app on screen
3. My phone hangs and some time ago rebooted.
4. Touch app again
5. Error on screenshot.

Also now I can't load any page in Fennec (Firefox mobile browser) it shows just blank page. And I can't start my Camera app. It shows just black screen. Before this problem happens with my phone but old version SPD didn't show any error message. Only black screen and I couldn't to find reason. Single way to fix this it do factory reset. I tried to restore TWRP backup of data partition. It's not help me. I still can't start SPD, Camera or Fennec application. If I remove and install apps again no success.

My phone Xiaomi Mix4.
ROM 14.0.6.0 xiaomi.eu
Installed apps:
* Magisk
* De-Bloater v1.0
* F-Droid Privileged Extension 0.2.13
* SSH for Magisk v0.16
* Zygisk - LSPosed
* CustoMIUIzer14 23.10.01
* Killegram 22.03.12
* Mir Pay Security 1.3.4

**Comment by 00-Evan** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/3115
