### ISSUE TITLE
rebalancing for some dungeon dwellers

### ISSUE THREAD

**Issue by indra87g** [00-Evan/shattered-pixel-dungeon#1533]
After playing Shattered Pixel Dungeon several times, I felt that some of the dungeon inhabitants were too difficult to beat. If possible, please rebalance the powers to match the hero's level. Example: If the hero has level 5, then the scout gnoll should have level 5 strength. If the system is like that it might be interesting, like some other RPG themed games

Some games that have a system like this (that I have played):
- Genshin Impact (3D)
- Yet Another Pixel Dungeon ( 2D ) - I didn't know this game had a system like this anymore
- Terraria (2D)
- Epic Conquest I & II ( 3D )

If you read this,
Thank You So Much, Evan :D

I'm not forcing you to add this feature to Shattered PD. I'm just giving my opinion. If you add it, that would be great. but if not, no problem. because you are the game maker. your game your rules :D

OK

**Comment by 00-Evan** [comment]
It is intended that you gain exp as a reward for combat, and that levels gained from that exp help you deal with stronger monsters as the dungeon progresses. Having the game scale to the hero's level would defeat the entire point of levelling, I might as well just remove exp altogether.

**Comment by indra87g** [comment]
ok, thanks for your answer
