### ISSUE TITLE
Finishing the bone ball wand quest kills the red ghost.

### ISSUE THREAD

**Issue by TadaCZE** [00-Evan/shattered-pixel-dungeon#1534]
If a red ghost spawns and the bone ball quest is active at the same time and you finish the quest before using a scroll of remove curse, the red ghost disappears. The completion of the quest should probably only kill the ghosts that are spawned by the bone ball.

**Comment by 00-Evan** [comment]
Fixed in commit cdec9a68bf85d13b34ede72760937e53606b6d04
