### ISSUE TITLE
Uneasy effect from talisman of foresight doesn't work very well when going fast.

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1535]
So when you use the talisman of foresight and have any speed buffs, (ring of haste, swiftness glyph, etc) the uneasy effect sometimes does not apply when it should because it only checks on every full turn. I don't have any screenshots because it's really hard to show, but the way to fix it would be to instead make the check every single time the character does a movement action, at all. I'll get some screenshots in a bit.

**Comment by Howdidibreakit** [comment]
This bug is not exclusive only to going fast, it happens in any instance where you move tiles without spending a full turn and in proximity to a hidden trap. Just entering a new floor of the dungeon and pressing wait will probably show you that it's only when a full turn is spent that it checks.

**Comment by 00-Evan** [comment]
Please do not close the issue as it has not been addressed in a public release yet. I'll close it and tag the relevant commit when v2.3.0 releases.

**Comment by 00-Evan** [comment]
Fixed in commit fae73101aaa70ac5b51ea577a9389809a91fdafe
