### ISSUE TITLE
Able to teleport out from chasm vault before picking up the crystal key.

### ISSUE THREAD

**Issue by ChuiyuWang1** [00-Evan/shattered-pixel-dungeon#1536]
I fell into a chasm vault, the special room that requires to jump from the previous floor. After I examined the skeleton remain, a Tormented spirit appeared. I tried to read my Unstable Spellbook, and a teleportation scroll was activated and I was teleported out from the locked chasm room. Is this considered as a bug?
![微信图片_20231107151005](https://github.com/00-Evan/shattered-pixel-dungeon/assets/51296659/057be665-f675-47d6-a333-95ab10039636)
![微信图片_20231107151010](https://github.com/00-Evan/shattered-pixel-dungeon/assets/51296659/0ffff60f-57b8-4aee-b275-5d193f368ac6)

**Comment by 00-Evan** [comment]
This is intended, you can always jump back into the room from the previous floor.
