### ISSUE TITLE
Crystal Boss and Liquid Nature/Barskin interplay

### ISSUE THREAD

**Issue by voronaam** [00-Evan/shattered-pixel-dungeon#1539]
When the Crystal Boss attacks and creates small crystals over the grass it wipes the grass out completely. I think it should leave the furled grass behind which the Warden can bring back to get the barskin effect.

Basically, if Warden is unlucky with armor early on she relies on drinking potions in the boss fights to create patches of grass on the arena and stepping on it ever so often to refresh the barskin. This does not work in the new arena because after crystals are cleared, the floor under them is bare - no sign of grass ever existing there previously. Which denies Warden the opportunity to refresh the Barskin.

**Comment by 00-Evan** [comment]
This is intended. Some gameplay style will have a harder time against certain bosses. The warden who depends on barkskin is also dependent on terrain, and so that will be tricky in cases where enemies can manipulate terrain as well.
