### ISSUE TITLE
Recycle spell giving only SoI and PoH?

### ISSUE THREAD

**Issue by gatopeich** [00-Evan/shattered-pixel-dungeon#1542]
On latest version using the Recycle spell on 2 scrolls produced 2 scrolls of Identify. Then on 2 potions, 2 potions of Healing.

I have a +4 RoW and a lucky weapon, and every other succubus is dropping a scroll of transmutation... related?

Is the randomness broken?

**Comment by 00-Evan** [comment]
It's obviously a little uncommon to get two sets of two items in a row, but it's entirely possible. Identify and Healing are also the most common possible results.

**Comment by gatopeich** [comment]
I went and spent about 30 recycle spells,  and I actually got a bit of everythingt. Looks like I had strange luck there.
Thanks for responding!
