### ISSUE TITLE
What is the best way to debug the game ? keep crashing when setting breakpoints in WelcomeScene

### ISSUE THREAD

**Issue by whiletrue111** [00-Evan/shattered-pixel-dungeon#1549]
hello , 
How do you handle debugging the game , i try to set break points in WelcomeScene.java starting in the create () call 
and the game stack and i unable to move with the debugger until i kill the app . 
what is the trick to debug the game ?

**Comment by 00-Evan** [comment]
This is a place to report technical issues with the game, not for asking for advice on how to work with the source code. Feel free to email me if you'd like help with that. As I mentioned in your previously reported issue, I'd suggest using Android Studio instead of Intellij.
