### ISSUE TITLE
Performance seems to degrade as I interact with shopkeepers.

### ISSUE THREAD

**Issue by SamSkulls** [00-Evan/shattered-pixel-dungeon#155]
Android 4.4.2, Shattered Pixel v0.4.2a

Oftentimes, as the game progresses I notice that loading the trading dialog begins to take longer (1 to 1.5 seconds) and eventually the app crashes as it tries to load the shop dialog. (Game data is saved, though; I've always been able to resume after restarting the app.)

This is just my supposition, but it seems to be some kind of leak associated with loading or unloading the floor a shopkeeper is on; just talking to the same shopkeeper over and over doesn't reproduce the misbehavior.

**Comment by 00-Evan** [comment]
There was a memory leak in 0.4.2 which was fixed in 0.4.3. However more leaks may exist.

Could you please update to the latest release (0.4.3a) and verify if you're still experiencing this?

**Comment by SamSkulls** [comment]
Sure thing. I'll let you know if it happens in the newest version.

**Comment by 00-Evan** [comment]
Further memory leak bugs have been fixed indev, I can confirm there is no leakage involved in interactive with shopkeepers.
