### ISSUE TITLE
Charm does not prevent bow

### ISSUE THREAD

**Issue by voronaam** [00-Evan/shattered-pixel-dungeon#1553]
When: Succubi charms Huntress
What: Huntress tries to attack Succubi
Expected: She can not use weapons to do that
Actual: bow still works

With the Point Blank sufficiently researched Huntress can ignore the core mechanic around Succubi fight and just always attack with the bow - charmed or not.

**Comment by TamamoSupremacy** [comment]
All ranged attacks work tho. Magic and thrown weapons. This was always a thing. It helps you actually kill the damned things...

**Comment by 00-Evan** [comment]
This is intended, charm is effecting against enemy AI and melee attacks.
