### ISSUE TITLE
Scorpions skip turns when cornered

### ISSUE THREAD

**Issue by voronaam** [00-Evan/shattered-pixel-dungeon#1554]
Scorpions try to get out of character's melee range. But if they have nowhere to go (hero blocks the only path out, perhaps others are blocked by traps) the Scorpions just skips the turn until it is dead.

Alternatively, it could do the same thing a Thief does - when they have nowhere to run they get angry and at least melee attack the player. Since Scorpions have just the ranged attack they'll get the usual accuracy penalty and it will not change the outcome of the fight much, but at least they would not look bad just staying in the hallway doing nothing.

![photo_2023-11-15_22-27-06](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2351069/98e43bf2-4cf7-4221-81a6-2d339a174970)

**Comment by 00-Evan** [comment]
This is intended, scorpio do not have a melee attack.
