### ISSUE TITLE
Pressing the space bar to pick up an item will triggers the talent need wait

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1557]

**Comment by 00-Evan** [comment]
This is intended. Spacebar is a combo button for waiting or pickup item (as a convenience). Because of that, I let it trigger the talent just in case the player wanted to wait in that situation.

**Comment by Lyx0527** [comment]
You didn't understand what I meant
The result is that the talent is triggered by picking up items

**Comment by 00-Evan** [comment]
I do understand what you said. I let picking up items trigger the talent in this case because the same button is also used to wait.
