### ISSUE TITLE
If hero leave a floor, Drowsy's turn of enemies may be reset

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1558]
Drowsy left 1 turn

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Drowsy uses the game's standard actor time delay functoinality before triggering, which is preserved when moving between floors. Can you give me any more information about how you encountered this?

**Comment by 00-Evan** [comment]
I'm still not able to reproduce this. Additionally, the example you showed me is not from Shattered Pixel Dungeon. Please don't report issues encountered in other PD versions.

**Comment by Lyx0527** [comment]
I found this bug in SPD 2.2.1
