### ISSUE TITLE
Oh or old music back please 😂🥺

### ISSUE THREAD

**Issue by MarshMeadow** [00-Evan/shattered-pixel-dungeon#1559]
I would love to have the option of trun on old or new music in the game

**Comment by 00-Evan** [comment]
Duplicate of #1437 and #763

In general I am not interested in adding toggles that revert feature updates.

**Comment by Shekel-JF** [comment]
Well, why would you force it on people when a lot of community find it less fitting than the old one?

**Comment by Saquial-g** [comment]
What a shame...
