### ISSUE TITLE
Add a description of what the challenges do in game

### ISSUE THREAD

**Issue by iTwenty** [00-Evan/shattered-pixel-dungeon#156]
Hi and thanks for the wonderful game!

AFAIK there's no description of the challenges inside the game. One has to refer the wiki for that. Would be nice to have those descriptions inside the game itself. I am thinking something like a small "i" or "?" icon next to the checkbox.

Let me know if you are interested in this. I might send a PR your way if you are!

**Comment by 00-Evan** [comment]
I'm very dissatisfied with the current challenge system, and want to rework it completely at some point. When that happens the new system will definitely feature proper descriptions.
