### ISSUE TITLE
staff imbue with leveled wand does not work as labeled

### ISSUE THREAD

**Issue by pierre-gautier** [00-Evan/shattered-pixel-dungeon#1560]
![Screenshot_20231208-235048](https://github.com/00-Evan/shattered-pixel-dungeon/assets/26608043/958a7cce-4102-429e-a73f-b116ffd6415b)

According to the text the staff should be level 3 but turns out level 2

**Comment by 00-Evan** [comment]
Does the wand have any levels granted by arcane resin? Resin upgrades aren't considered true upgrades and so won't be transferred with the staff.

**Comment by pierre-gautier** [comment]
Oh, that must be it, thanks.
Maybe it's worth writing it somewhere !

**Comment by 00-Evan** [comment]
From arcane resin's description: "Resin upgrades are overridden by scrolls of upgrade and similar items, and do not apply when imbuing a wand into the Mage's staff."

**Comment by pierre-gautier** [comment]
My bad 🙇
