### ISSUE TITLE
Warden can exit (and re-enter) troll quest cave with seed of fadeleaf

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1561]
Supposing the troll quest is on 13, fadeleaf teleports me to the exit of floor 12. Now I can do whatever I want and resume the quest later.

**Comment by 00-Evan** [comment]
This was already reported to me via email a little bit ago, I'll track that fix in this issue.

**Comment by 00-Evan** [comment]
Fixed in commit 5f9926e3ea2f801da9f614517657c19f42e059ec
