### ISSUE TITLE
Place for discussion

### ISSUE THREAD

**Issue by indra87g** [00-Evan/shattered-pixel-dungeon#1563]
Hi Evan, can you enable the discussion feature for this repository? So that we Shattered Pixel Dungeon players can share our experiences in playing this game and we can also give our rating to this game. This discussion feature may also be useful for developers who want to remake this game so they don't get confused.

Thank You

**Comment by 00-Evan** [comment]
I'm not really sure I like the idea of treating Github like a social media website. Discussions could be useful but I'd like to keep them limited to the sort of thing people post issues about. If you want a social media place for Shattered you're better served by an actual social media site, e.g. Lemmy: https://lemmy.world/c/pixeldungeon
