### ISSUE TITLE
Show max damage of enemy on examine

### ISSUE THREAD

**Issue by alexiayaa** [00-Evan/shattered-pixel-dungeon#1565]
I couldn't find a similar feature request on a quick search, so apologies if it's already been suggested.

It would be a nice QoL feature to be able to see the maximum damage an enemy can deal when examining it, so that I don't have to constantly go to the wiki to determine whether an enemy can kill me in its next hit when I'm in a tough situation.

**Comment by 00-Evan** [comment]
I do think that Shattered could potentially show a bit more information about enemy stats, but I'm wary about just information dumping in their description. I really dislike RPG games that just tell you all the internal numbers about an enemy, as it makes the game feel more like a spreadsheet than a game.

**Comment by alexiayaa** [comment]
Fair enough. How about putting it in some sort of in-game guidebook (ideally accessible during gameplay) instead?

**Comment by 00-Evan** [comment]
A bestiary or similar is something I'd like to add in the future, but it's not a priority currently.
