### ISSUE TITLE
Don't require double swipe for system gestures on iOS

### ISSUE THREAD

**Issue by alexiayaa** [00-Evan/shattered-pixel-dungeon#1566]
On iOS, I have to double swipe to be able to background the app or pull down the notification/control center. This is great for full screen games that you may accidentally close with a swipe, but Shattered Pixel Dungeon, being a turn-based game where events don't happen continuously in the background, as well as being a portrait game that doesn't even hide the status bar, it's just an annoyance. I wasn't able to find it in the Info.plist on a quick look, but I know this is something app developers are able to control.

**Comment by 00-Evan** [comment]
This isn't something I can directly control unfortunately. It has to do with whether Shattered tells iOS to prioritize system gestures or app gestures. If I set it to prioritize system gestures, then instead of requiring two swipes, there is a noticeable delay whenever you interact with the game at the bottom of the screen, as your device waits a moment to see if the input becomes a system gesture.

**Comment by alexiayaa** [comment]
I see. This can't be adjusted during runtime, can it?

**Comment by 00-Evan** [comment]
I don't think so, it's a configuration that's set on launch. Even if it were changeable at runtime I wouldn't want to put in a setting for it. While I appreciate that swiping twice is annoying, having to wait a second every time you tap on inventory or quickslots is much worse.

**Comment by alexiayaa** [comment]
My idea was to add extra borders when that option is enabled to avoid that issue. It's only worth considering if it can be changed after installation though, you wouldn't want to force everyone to have less screen space for the game.

**Comment by 00-Evan** [comment]
There is actually already a setting for that, sort of. You can turn 'fullscreen' on or off in the settings. I don't recall whether this affects how many swipes it takes though.

**Comment by alexiayaa** [comment]
It doesn't, I have it off and it still needs two swipes.
