### ISSUE TITLE
A suggestion and an unknown reason soft lock

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1567]
When a warlock heals through soul mark, display icons and numerical values

soft lock
【破碎地牢-2.3.0版本豺狼地卜师任务实况-哔哩哔哩】 https://b23.tv/AwLxbww
04：11

By the way, I think the gnolls variant is much easier than the crystal variant

**Comment by 00-Evan** [comment]
Your link gives a 404 error

Icons for soul mark were added in BETA-1.1

**Comment by Lyx0527** [comment]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/ffac6134-e470-4f30-9ad1-379d5c824121

I have tried many times to send the video directly, but all have failed.
Copying the link directly and opening it outside of GitHub may be feasible
