### ISSUE TITLE
Crazy Thief spawning in floor 5

### ISSUE THREAD

**Issue by yesseruser** [00-Evan/shattered-pixel-dungeon#1569]
Hi,

I do not know whether this is intentional, but in the Android Beta (2.3.0-BETA-1.2) the Crazy Thief spawned in floor 5 of the sewers. See picture.
![Screenshot_20231217-144034.png](https://github.com/00-Evan/shattered-pixel-dungeon/assets/67008763/ce9a9124-28a3-438a-9b1e-02158d378773)

**Comment by 00-Evan** [comment]
duplicate of #1368, #1416, etc.
