### ISSUE TITLE
Aldonu esperantan tradukon

### ISSUE THREAD

**Issue by verdulo** [00-Evan/shattered-pixel-dungeon#157]
Mi elŝutis version 0.5.0 de la ludo kaj mi rimarkis, ke la **internacia lingvo Esperanto** ne estas elektebla. Jam fine de decembro mi finigis plene traduki la ludon per Transifex. Konklude, mi esperas, ke vi estimos mian laboron kaj aldonos mian tradukon al la sekva eldono de via bonega ludo!

**Comment by 00-Evan** [comment]
This isn't the appropriate place to talk about translation issues, please message me on Transifex.
