### ISSUE TITLE
Unreachable room generated

### ISSUE THREAD

**Issue by eliminmax** [00-Evan/shattered-pixel-dungeon#1570]
In the Android beta for v2.3.0, Floor 4 generated with an unreachable room. The dungeon seed is YQH-MRT-QZQ.

![Screenshot_20231217-093652.png](https://github.com/00-Evan/shattered-pixel-dungeon/assets/33302691/1326014b-2dc7-4bc3-84aa-ba22463e4b49)

Screenshot taken in v2.3.0-BETA-1.2, but I may have started the game in the previous beta build.

**Comment by 00-Evan** [comment]
Afraid there is a connection there, you just haven't revealed it: 
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2347603/8122d750-84ef-4f15-b624-2ab4628570e3)

**Comment by eliminmax** [comment]
Oh. My bad - thought I'd been pretty thorough between the Talisman of Foresight and heavy usage of the search function. I guess not. Sorry.
