### ISSUE TITLE
Long tap to move hero on cell with chest or item.

### ISSUE THREAD

**Issue by drizt** [00-Evan/shattered-pixel-dungeon#1573]
Hello. 

Atm no way to go on a cell with item or chest without picking up item. But hero can be moved to cell with item if tap on opposite wall. If no wall no way to go on this cell. Sometimes need to move on such cell without extra actions. For example in room without floor and with 4 golden chests and keys. Or in battle in some cases need to move chat on the next cell with item. So please add this feature.

**Comment by 00-Evan** [comment]
Sorry but I don't plan to add functionality that uses long-tap when interactive with the game world. It would be too easily to trigger it while intending to pan the camera.
