### ISSUE TITLE
Psionic Blast and Sprit Hawk

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1576]
Sometimes, Psionic Blast do not harm enemies in the hawk's field of view

**Comment by 00-Evan** [comment]
Psionic blast should target every enemy that's in a visible cell, which would match whatever the player visually sees as visibile. Can you be more specific about what circumstances cause this bug?

**Comment by Lyx0527** [comment]
An enemy that the hero cannot see, but the hawk can see. 
Reading the Psionic Blast Scroll, only the hawk is killed and the enemy is not harmed. 
It seems to trigger randomly. 
It is likely unrelated to the blinded of the hawk, as enemies within close combat range of the falcon will not be injured. And the Retribution Scroll that cannot kill the hawk can take effect normally.
It seems to have been caused solely by the death of the hawk. 
Warding wand does not have a similar bug.

**Comment by Lyx0527** [comment]
There is another situation where Psionic Blast Scroll cannot damage all visible enemies.
If the Dark Fist eliminates illuminated due to Psionic Blast Scroll, other enemies seen through illuminated may not be injured.

**Comment by 00-Evan** [comment]
Ah, this has to do with the order that the scroll is affecting targets in. Probably it should build a list of targets first and then affect them.

**Comment by 00-Evan** [comment]
Fixed in commit 025ba0e12d7272ae978df997153afb956c009859
