### ISSUE TITLE
There are two automatic behaviors that need to be canceled

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1577]
1. When time freezes or cloaked, heroes will automatically pick up items. 
Especially when time freezes, many times I just want to escape danger, but I waste time because of automatic pickup. 
2. When hero is under vertigo, they still insist on automatic pathfinding. 
Players always tend to do nothing after triggering the Confusion Gas Trap, because players who only want to randomly take one step will see that hero take more than ten steps due to their unstoppable automatic pathfinding, even if there are enemies nearby.

**Comment by 00-Evan** [comment]
1. automatic item pickup is only based on enemy presence, that's intended.
2. this is also intended, you don't get to control your movement under vertigo, including how many steps you take.
