### ISSUE TITLE
perspective view hides dark gold

### ISSUE THREAD

**Issue by sethoscope** [00-Evan/shattered-pixel-dungeon#158]
With the new depthy visuals, it's not possible to see dark gold in the east, west, or south walls.

![screenshot_20170213-201919](https://cloud.githubusercontent.com/assets/534043/22915299/0b8f288c-f22b-11e6-9c69-9050936d2df5.png)

**Comment by 00-Evan** [comment]
Dark gold no longer spawns in those walls, it's only ever present there in floors generated pre-0.5.0

The frequency of gold ore spawns on camera-facing walls was increased to compensate for this.
