### ISSUE TITLE
Savegames and disk space

### ISSUE THREAD

**Issue by basxto** [00-Evan/shattered-pixel-dungeon#1580]
I ran into the issue that my savegame got corrupted because I ran out of disk space.

Since savegames can’t be easily restored in this type of game, I propose to first write into a new file and only when it passes corruption checks to delete the old one and rename the new one.

I used Steam version v2.2.1

**Comment by 00-Evan** [comment]
That is exactly what the game already does.

Write new temp file -> erase old file -> rename temp file

There's not a lot that the game can do if writing save files silently fails, but the above system does help in cases of things like file system locking or sudden power loss.
