### ISSUE TITLE
List pit rooms in diary

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#1583]
Sometimes I don't have the tools to deal with a pit room and need to return to it later. It would be nice to have pit rooms listed in the diary, similar to other landmarks like animated statues and sacrificial fires.

**Comment by 00-Evan** [comment]
I'd like to eventually overhaul landmarks in general, but for now this is a fairly simple addition, sure. It probably makes the most sense to landmark the 'distant well' on the prior floor though.

**Comment by 00-Evan** [comment]
Closing this for now as I'm unfortunately not planning to do this soon. Landmarks currently rely on a game actor to exist on or near their location to assign them. Distant wells have no such thing right now. I've noted that this would be a good room type to have in the journal in the future though.
