### ISSUE TITLE
When reforge, it is difficult to determine which equipment will be destroyed if the upgrades are the same

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1585]
Enhance and enchantment may be lost as a result. 
Before new quest, it always destroyed the right one, but now it has been changed to destroy the left one, resulting in many unexpected situations. 

By the way, players cannot re determine what the quest content is after accepting it, as the blacksmith's dialogue is the same
![Screenshot_20240102_184406](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/b4f7bca2-d9aa-4943-880f-a116c9061dde)

**Comment by 00-Evan** [comment]
Fixed in commit 08e36c724c8c0dc9373793e5509941b474ce34c3
