### ISSUE TITLE
Duelist unable to harvest gold in Blacksmith quest

### ISSUE THREAD

**Issue by 1IlIlI1** [00-Evan/shattered-pixel-dungeon#1586]
I believe I recently read that you've done some changes to the quest, so forgive me if this is a non-issue or operator error.  I will double check the documentation, but I believe I have found an issue.  

While playing a duelist->monk character, on the blacksmith quest where I need to farm 40 gold with a pickaxe, my duelist seems to unable to use the pickaxe.  The game forces the pickaxe combo move, or equip-swap.  Upon trying the pickaxe from inventory the game responds with "there is no target".  I've tried multiple standing locations and using the screen touch, but nothing seems to give.

Love Shattered Pixel Dungeon!  Keep up the great work!

**Comment by 00-Evan** [comment]
The mining functionality has changed, it's no longer an action under the pickaxe item. Instead simply tap on the cell you want to mine when you're in the new quest's mining area. Mining is no longer possible in the regular game area.
