### ISSUE TITLE
The room with rotberry is very small

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1587]
![Image_1704538045640](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/3b6a803c-095f-4121-8063-1b5a1324d36e)

WVK-MJT-FNM

It seems that there are still bugs with it

**Comment by 00-Evan** [comment]
Fixed in commit cb98b8863786af83336af7ff9655ca0e44e37cde
