### ISSUE TITLE
Heightened Sense and Imp

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#1588]
![Screenshot_20240107-001539](https://github.com/00-Evan/shattered-pixel-dungeon/assets/92562082/3aad8c7b-3139-44cd-8d4c-f9208cf9fb00)

Well without any visual contact the Imp was able to contact. The heightened Sense made the Imp visible but there is no chance that Imp can see me. If the Imp worked just like other entities in the dungeon.

**Comment by 00-Evan** [comment]
This is intended, the imp says hello when you see it, even with mind vision.
