### ISSUE TITLE
Implement Wayland support

### ISSUE THREAD

**Issue by TadaCZE** [00-Evan/shattered-pixel-dungeon#1589]
If you use SPD on Linux, the game will use X11 as it's backend. However, most of the Linux community has moved on from the X server to Wayland, meaning that it has to be used with Xwayland. And that works _fine_ (at least on a regular PC), or at least as fine as it was on X11, but it means that it can't take advantage of the improvements that Wayland brings:

- A minor performance boost
- Reduced latency
- Losing a depenency
- (The actually relevant one) **Touchscreen support**

The fact is, that the graphics library that SPD uses (LWJGL) already has Wayland support, so I believe implementing Wayland support would be relatively easy.

**Comment by 00-Evan** [comment]
Wayland support is determined by the code libraries Shattered uses, mainly libGDX. I have no control over the windowing system directly. If you want libGDX to support Wayland, I suggest opening and issue on their github page: https://github.com/libgdx/libgdx

**Comment by TadaCZE** [comment]
Well... There _is_ a solution, but you're not going to like it.

You can start SPD with a special Java argument which makes LWJGL use another version of GLFW specifically patched so that it disables some error checks. It was originally made to allow Minecraft to run under Wayland but it works here too.

If you want to test that it works do this:

1. Have Arch Linux installed on your PC
2. Install `glfw-wayland-minecraft-libdecoration` from the AUR
3. Run `java -Dorg.lwjgl.glfw.libname=/usr/lib/libglfw.so -jar shatteredpd.jar`

And it works! The only thing that is broken is the icon on the window border, which I think nobody honestly cares about.

In practice, it means you would have to compile your own GLFW and package it with the linux release and provide a startup script which enables this option.

**Comment by TadaCZE** [comment]
But yes, that is the hacky solution.

A better one would be for GDX to support Wayland directly.

**Comment by 00-Evan** [comment]
Yeah sadly that's not something I'd consider doing. I do plan to keep updating Shattered's depencies though, so if/when libGDX supports Wayland then Shattered will support it fairly soon after.
