### ISSUE TITLE
Spellbook does not trigger mage Inscribed Power

### ISSUE THREAD

**Issue by ulysses-sl** [00-Evan/shattered-pixel-dungeon#1590]
Platform: iOS 17.1.2
Version: 2.3.0-BETA-1.3

Spellbook artifact does not trigger mage's Inscribed Power talent.

Talent view 1
![IMG_6327](https://github.com/00-Evan/shattered-pixel-dungeon/assets/6335756/13344052-4d58-496f-9ba6-92617954fd74)

Talent view 2
![IMG_6328](https://github.com/00-Evan/shattered-pixel-dungeon/assets/6335756/321a6f1b-ca27-4135-a019-e016f3efafe9)

Before using the Spellbook
![IMG_6329](https://github.com/00-Evan/shattered-pixel-dungeon/assets/6335756/c67e2b2b-b73a-4c46-bc09-9155b662de6f)

After using the Spellbook
![IMG_6330](https://github.com/00-Evan/shattered-pixel-dungeon/assets/6335756/c88f4783-29f4-4e3b-a941-616236b6b776)

**Comment by 00-Evan** [comment]
This is intended. The talent triggers on reading a scroll, not when a scroll's effect is triggered by another item.
