### ISSUE TITLE
Items picked up in non visible quickslot when visible quickslot is available

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1591]
In the case when two different depleted quickslots are assigned to the same item, the leftmost quickslot will receive the item when it is picked up, even if it isn't visible, and the other icon will disappear. In fact, a non visible quickslot is always prioritized over a visible one.

**Comment by chorby-short** [comment]
This is observable with a specific setup using issue 1517, which allows two quickslots to exist for the same item based on whether or not they are in a bag.

**Comment by 00-Evan** [comment]
This bug requires you to use a specific setup to trigger a separate bug to get two quickslots with the same item placeholder, and then also change your screen size to reduce the number of quickslots. Sorry, I'm not interested in fixing a quirk that requires such a specific purposeful setup.
