### ISSUE TITLE
Unexpected ranged melee weapon attack behavior when charmed

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#1592]
v2.2.1 on Android

Trying to attack a succubus from range with a ranged melee weapon, while charmed by it, will make you move towards it. I would expect it to do nothing. The succubus is in attack range, you just can't attack it. I don't see what moving towards it is achieving - it feels like a bug to me.

My scenario was being a Battlemage with a Staff of Disintegration and a Ring of Haste. It happened many times that I tapped the attack button without realizing I was charmed and got hit unnecessarily due to the unexpected move.

**Comment by 00-Evan** [comment]
This is intended. If you're not able to attack an enemy then you will approach them, this includes if an effect like charm is preventing the melee attack, or if you're out of range.

**Comment by MiroslavR** [comment]
> This is intended. If you're not able to attack an enemy then you will approach them, this includes if an effect like charm is preventing the melee attack, or if you're out of range.

The fact you mention being out of range here makes me think we're not talking about the same thing. I'm talking about this red attack button:

![attack-button](https://github.com/00-Evan/shattered-pixel-dungeon/assets/7346770/57fc66c9-54b9-4f96-ad14-be178a0ca043)

The attack button does not appear when the enemy is out of range, which also makes me think its intention is to attack, not move. I think you're talking about tapping on the enemy's tile, where this behavior makes some degree of sense because tile tapping is normally also used for movement.

How about hiding the attack button when the enemy has you charmed, just like when the enemy is out of range?

**Comment by 00-Evan** [comment]
I skim messages often in order to get through them all in a reasonably timely manner. The screenshot wasn't necessary, you could have just re-iterated you were using the attack button.

Currently the attack button is exactly equivalent to tapping on the enemy, I'd rather not introduce UX complexity by having the two actions differ in specific cases. Will consider more clarity around charming in general in the future though.

**Comment by MiroslavR** [comment]
> I skim messages often in order to get through them all in a reasonably timely manner. The screenshot wasn't necessary, you could have just re-iterated you were using the attack button.

No need to be condescending. I just wanted to maximize being understood, especially since I'm not a native English speaker.

> Currently the attack button is exactly equivalent to tapping on the enemy,

It's not, though. The attack button is not available when the enemy is out of range, whereas tapping on the enemy is.

Anyway, thanks for your consideration.

**Comment by 00-Evan** [comment]
> No need to be condescending. I just wanted to maximize the chance of being understood, especially since I'm not a native English speaker.

You were the one who sent a screenshot with a red big circle around the attack indicator, as if I didn't know what it was. Apologies for being confrontational though, I wasn't aware you weren't a native speaker and that does make including that screenshot a lot more understandable.

> Currently the attack button is exactly equivalent to tapping on the enemy,

What I meant was that tapping on the attack button is the exact same as tapping on the enemy's location. I'd rather not change that to be 'same as tapping on enemy, except in these specific cases where it does something slightly different'.

I think the best change for this would be changing the behavior of tapping on an enemy you are charmed by entirely, which isn't possible for v2.30 currently as it'll require text changes.
