### ISSUE TITLE
The buring effect of the gnoll guard is not displayed

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1593]
Screenshot↓

![Screenshot_20240112_210639_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/87411658/6fd2a713-48bd-4a20-bf7c-15c8b31f705a)

![Screenshot_20240112_210633_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/87411658/8af657fe-e7d1-4f43-8f47-dc0aa2d614f7)

**Comment by 00-Evan** [comment]
This has been reported a few times but I have been unable to consistently reproduce it. Can you give me any more information about this scenario? For example, have you defeated any gnoll guards or sappers prior to burning this one? If so, what did you use to kill them? Was the guard lit in fire from outside of your field of view initially?

**Comment by 00-Evan** [comment]
Nevermind, I was able to reproduce this after some more testing. Will fix in BETA-1.5

**Comment by 00-Evan** [comment]
Fixed (finally) in v2.3.0-RC-1
