### ISSUE TITLE
Request: ability to use stacks in Alchemy.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1594]
If you are crafting several of the same item, it is incredibly annoying to keep having to go to the inventory for ingredients repeatedly. It would be much more convenient to put the entire stack in the alchemy table, and simply deduct one from a stack when an item is crafted.

This is already essentially how liquid metal works when crafting telekinetic grab, and it would be handy if that behavior was more widespread.

**Comment by 00-Evan** [comment]
The alchemy interface doesn't do this as it would make certain recipes impossible. For example, if items were added a stack at a time, and you had many seeds, it would be impossible to specify how many of a particular seed type you wanted to add.
