### ISSUE TITLE
Sound effects are distorted

### ISSUE THREAD

**Issue by LupusEtFlos** [00-Evan/shattered-pixel-dungeon#1596]
I'm running the game on an Acer laptop, using Android x86, the LineageOS 14 build more specifically. Every sound effect plays in a distorted fashion, as if slowed down or if the tempo was changed, while the OST is fine. It has always occurred since the first time I played it back in 2021, and it's the only game to exhibit this behaviour. Could it be related to OpenAL? If so, I do have a means of choosing from a few presets, which requires a reboot , but if there's perhaps something else I could do, maybe compile it for my specific hardware with a small change rather than switching the entire OS' sound settings just for this game, I'd love to try.

Thanks in advance. The game is amazing, I've been playing it for several years, acquired it on Steam last year too :) but I must play it on every device I come across. Was even considering a PS2 or PS4 port at one point. :P

**Comment by 00-Evan** [comment]
Glad to hear that you've been enjoying the game! I'm afraid I don't know what specific issue may cause this, but lineageOS has has problems playing back audio in Shattered before. For reference, Shattered's Android build uses the Android SoundPool library for sfx playback of pretty bog-standard MP3 files.

Closing this as there's no changes to be made ony my end, but feel free to keep commenting.

**Comment by LupusEtFlos** [comment]
Thank you for your reply! I forgot to mention I had an Xperia E3 with LineageOS 14 as well, and it had no issues with this game. I can't help but think it is merely a quirk with Android x86. If I manage to make a capture, or even find a solution, I'll post it here, should someone be interested in running such OS on a computer and also enjoy your game. :)
