### ISSUE TITLE
Leaderboard on PC Version ?

### ISSUE THREAD

**Issue by indra87g** [00-Evan/shattered-pixel-dungeon#1598]
Hi Evan, can you add a leaderboard to the desktop version of Shattered PD?

I think you can use Gamejolt API to make it. With the Gamejolt API, you can create a leaderboard for the desktop version of Shattered PD. This leaderboard will later be connected to Gamejolt.

Or maybe, you have another idea...

USEFUL LINKS
Gamejolt Java API - https://gamejolt.com/f/java-api/226
How To Use API on Java - https://gamejolt.com/f/how-to-use-the-api-in-java/341203
Another Java API - https://gamejolt.com/f/another-java-api/305
Gamejoltclient for libGDX - https://gamejolt.com/f/gamejoltclient-for-libgdx/235999?sort=top
gdx-gamesvcs-core-gamejolt Java documentation - https://jar-download.com/artifacts/de.golfgl.gdxgamesvcs/gdx-gamesvcs-core-gamejolt/1.0.0/documentation

Thank You !

**Comment by 00-Evan** [comment]
My main concern with adding a leaderboard for things like dailies is cheaters. There is just no way for me to ensure that the top of the leaderboard won't be immediately filled with illegitimate scores.

The gamejolt API is also over 10 years old from your links, I would prefer to use something that's being maintained. Additionally, if I were to add a leaderboard, I would want it to function across platforms, which would necessitate using my own servers, which also create a lot of additional logistical burden. Ultimately it's just not feasible versus working on other content.
