### ISSUE TITLE
Throwing an artifact into a Well of Transmutation can result in getting nothing back

### ISSUE THREAD

**Issue by squigish** [00-Evan/shattered-pixel-dungeon#16]
If all artifacts have already been obtained.

I haven't actually observed this, this is just my conclusion from reading the code.

I'd be happy to test this and submit a PR for a fix, if you'd like.

**Comment by 00-Evan** [comment]
This should be working correctly.

In the case of no artifact available a null item will be returned, which will cause the artifact to pop back out of the well and not be consumed (see WellWater line 77 and lines 95-105).
