### ISSUE TITLE
fog of war bugs

### ISSUE THREAD

**Issue by Highseekerz** [00-Evan/shattered-pixel-dungeon#160]
opening door with throwing items does not update fog of war
here is example link
http://m.imgur.com/vS4DcUk

**Comment by 00-Evan** [comment]
that looks like a properly updating fog of war to me, you're seeing through the open door.

**Comment by 00-Evan** [comment]
I am hopeful that this will be fixed in 0.5.0b, but I cannot reproduce it on any of my tester devices. Let me know if you still get this when 0.5.0b rolls around.

**Comment by 00-Evan** [comment]
I 'think' this commit should fix this bug: 96989edb32e10a7227bff0f9fe2fe7b78fe28c33

feel free to re-open if you're still experiencing problems on 0.5.0b
