### ISSUE TITLE
Auto movement steps on Firebloom and all plants

### ISSUE THREAD

**Issue by gatopeich** [00-Evan/shattered-pixel-dungeon#1600]
The path finding algorithm could do with a few improvements:

1. Don't step on plants (stop before?) Specially on Fireblooms.
2. Favor diagonal movement, most times it is the best option but is only used when the direction is exactly on 45 degrees angle.
3. Prefer tiles with no trap potential (water, rugs, etc)

All those are to avoid annoying mishaps.

I might be able to produce a pull request...

**Comment by 00-Evan** [comment]
This is intended, plants are not classified has hazards to be avoided as some of them produce positive effects, and enemies should not avoid them.

Regarding your other points, I would prefer to keep pathfinding as simple as possible, and not make assumptions about which route the player may want to take when approaching a destination.

**Comment by gatopeich** [comment]
We could at least assume that the player does not want to step on a Firebloom at (1,3) when standing at (1,1) and tapping on a door at (3,5). Nobody expects to run straight into the Firebloom...

At least the player auto-path should stop before stepping on a Firebloom, like it stops when spotting an enemy.

**Comment by gatopeich** [comment]
We could at least assume that the player does not want to step on a Firebloom at (4,1) when standing at (1,1) and tapping on a door at (7,4). Nobody expects to run straight into the Firebloom...

See this example, most people won't like it when they tap on the door and get straight into the plant:
![Screenshot_20240118-203057~3](https://github.com/00-Evan/shattered-pixel-dungeon/assets/7722268/9af13ed0-c8ac-4a51-8cee-6cafc242b76c)
(Green is the expected path after many years of roguelike gaming)

And even worse here, where the plant is hidden from view but we will inevitably step on it:
![Screenshot_20240118-203919~2](https://github.com/00-Evan/shattered-pixel-dungeon/assets/7722268/c39287e1-3eff-4f06-a424-4dc5cc20bbb4)

I have played a good deal of roguelikes and I dont remember one of them not doing diagonal movement first!

At least the player auto-path should stop before stepping on a Firebloom, like it stops when spotting an enemy.

**Comment by gatopeich** [comment]
And BTW, diagonal movement should cost 1.4X 🙂
