### ISSUE TITLE
Key for Goo spawning far away from kill location

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [00-Evan/shattered-pixel-dungeon#1601]
I don't have any footage of this bug, but after defeating Goo, the key spawned in a completely different part of the level than where Goo was killed.  
This left me really confused, as i thought the key had failed to drop. I don't know if this is intended behavior, but it doesn't seem like it considering the key seems to usually always drop where Goo was killed.

In case it matters, i was playing as a thief, on version `v2.1.2` and on seed `QTG-SYK-KGC`.
  
As a side note, i originally circled the whole level and i couldn't find the key. I then closed the game and came back later, and the key was now somewhere in the lever (although not where i killed Goo), but it might just have been that i forgot to check this room the first time around.

**Comment by 00-Evan** [comment]
The key uses pretty standard logic for dropping items when defeated, so there shouldn't be any situation where this would happen just for Goo specifically. What did you use to defeat Goo, perhaps something that might change Goo's position right at the killing blow?

**Comment by Matthieu-LAURENT39** [comment]
I used an un-echanted +1 dagger, and the only thing that might be of note is that i killed it with a surprise attack.
i did check, my armor didn't have the curse of dislacement either.

**Comment by 00-Evan** [comment]
Hm, then there's no real way to verify or reproduce this I'm afraid. When Goo dies it drops the key on its position in the same way other enemies drop their loot. I'm going to close this for now, but feel free to comment if you encounter this issue again.
