### ISSUE TITLE
Allied mobs prioritize other allied mobs instead of targeted hero when amok

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1602]
When allied mobs are amok, they will only attack the hero when there are no other mobs in their field of vision. This should not be the case when the hero has the targeted debuff; it's wierd that even though enemy mobs are forced to target the hero first, allied amok mobs target the hero last.

**Comment by 00-Evan** [comment]
fixed in commit 7ad704c43b43bf811326019157e370e447fed49a
