### ISSUE TITLE
Non-level up sound effects dampened after headphone use

### ISSUE THREAD

**Issue by Merpington101** [00-Evan/shattered-pixel-dungeon#1605]
I use an HP laptop that uses Windows 11. I installed my version of SPD from itch.io on January 19 2024

When I first launched the game, all sounds functioned normally. If I plug in headphones while the program is running, all music and sound effects become muted until the game is opened again. If headphones are plugged in before opening the game, music and leveling up the character or their talents are normal volume, but all other sound effects are significantly quieter. This does not fix when closing the game and reopening and persists even when headphones are no longer plugged in.

**Comment by 00-Evan** [comment]
There shouldn't ever be a case where some sound effects are surpressed and other's aren't, as they all play through the same audio subsystem. Your headphones may have some sort of software 'audio enhancement' enabled, which cases some sounds to be suppressed.

In general the game does not handle switching audio devices well right now though, and this is already planned to be improved in a patch for v2.3 as I will be updating the game's internal game library, which handles audio. This may not address your issue in particular though.

**Comment by Merpington101** [comment]
I'll see if I can fix something on my end, this is the only game this has happened to me in and I wasn't sure if it was the game or my device. Thanks for clarifying!

**Comment by Merpington101** [comment]
After looking into it, you are correct. Once I turned off immersive sound, everything functions normally.

**Comment by 00-Evan** [comment]
Glad to hear you were able to fix it! The fact that it only triggered on some sound effects made me suspect it was some form of audio 'enhancement' that was listening to the sfx and attempting to 'improve' certain sounds.
