### ISSUE TITLE
Bug: Not being able to mine gold as duelist on mobile

### ISSUE THREAD

**Issue by Randomuser909** [00-Evan/shattered-pixel-dungeon#1606]
Instead of mine, it says pierce (duelist's ability with it) the action mine is missing

**Comment by 00-Evan** [comment]
This is intended. The mine action is no longer tied to the item menu, it's now triggered by simply tapping on a wall tile in the new quest area.

**Comment by Randomuser909** [comment]
It's not letting me though

**Comment by 00-Evan** [comment]
Are you in the new mining level? The quest no longer takes place in the regular mines floor that the blacksmith is on. Take the ladder down from his workshop.

**Comment by Randomuser909** [comment]
I... Did not realize that was there, sorry for wasting your time

**Comment by 00-Evan** [comment]
No worries
