### ISSUE TITLE
Texturing issues when rocks fall into tall items.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1609]
Appears to happen to all(?) items whose sprites extend above the top gridline of the tile the item is on
![Screenshot_20240126-160136](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/ab830ad8-a420-4f45-aa19-102c6a4c8aa6)

**Comment by 00-Evan** [comment]
I'm aware of this visual quirk and opted to leave it. It's due to how the game's tilemap rendering works, and changing it for this case would require substantially more work that it appears.
