### ISSUE TITLE
Embers don't appear on floor 26 terrain

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1610]
This includes it's appearance on Yog's floor 25 podium and demon spawner forms as well. The embers are still there if you examine them, but their sprite is missing. This may be intended because this has been the case for a long time, but it is still annoying and seems unnecessary.

**Comment by 00-Evan** [comment]
fixed in commit 9de10a0e96f6ed9864db5ab7ca0710e1b2e1a895
