### ISSUE TITLE
Why is the armor provided at the beginning cursed?

### ISSUE THREAD

**Issue by undefined-hestudio** [00-Evan/shattered-pixel-dungeon#1611]
Why is the armor provided at the beginning cursed? I didn't replace the armor, but it was cursed.

![IMG_20240129_105732.jpg](https://github.com/00-Evan/shattered-pixel-dungeon/assets/119711513/2e32ad18-71c0-45fc-9a3d-d9d1989aaa81)

**Comment by 00-Evan** [comment]
The armor is never cursed when it is initially given, but it is possible for it to become cursed.

**Comment by undefined-hestudio** [comment]
thanks！
