### ISSUE TITLE
Request: a repeat button for alchemy.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1613]
Going into the inventory manually when you are making several of an item is a chore. It would be a lot faster if there was a button on the interface to repeat the previous recipe, if the player has the materials for it.

**Comment by 00-Evan** [comment]
This functionality is already partially provided by the alchemy guidebook. However, I am planning to make more significant changes to the alchemy interface in the next update (to go along with trinkets), and am considering something like this.

**Comment by 00-Evan** [comment]
Added in commit 8efb48d83ff105a10e033ee370463225ced84626
