### ISSUE TITLE
Wand cursed the app

### ISSUE THREAD

**Issue by hjek** [00-Evan/shattered-pixel-dungeon#1614]
This wand was so cursed it crashed the whole app.

![cursed wand](https://github.com/00-Evan/shattered-pixel-dungeon/assets/11958965/7d8048e9-4df3-4f55-914d-73a6b8f45273)

Version 2.3.0, seed FVF-LMS-LKS.

**Comment by 00-Evan** [comment]
This is intended actually, The game just closes itself. It's a reference to an old legendarily unhelpful error message: https://en.wikipedia.org/wiki/Abort,_Retry,_Fail%3F
