### ISSUE TITLE
Looting in flight doesn't give warning that flight will wear off

### ISSUE THREAD

**Issue by denis-kralj** [00-Evan/shattered-pixel-dungeon#1615]
Experienced this in the room where 4 golden chests are found. When looting one while on the last turn of flight, there isn't a pop up like when you move that the flight loss will result in a fall. Not sure if it is an introduced bug, but it seem inconsistent given that movement does warn you of the risk.

**Comment by 00-Evan** [comment]
The chasm warning is only intended to trigger on standard movement actions, I'm not interested in extending it to handle any action while you are over a pit, or that would move you onto a pit.
