### ISSUE TITLE
Equipped items known to be clean can be uncursed while under degraded debuff

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#1618]
v2.3.1 on Android

While under degraded debuff, you can use a scroll of remove curse on equipped items that are known to be clean. Using it acts as if a curse got removed but nothing really happens.

**Comment by 00-Evan** [comment]
This is intended. Scrolls of remove curse can be used to clear the degraded debuff, and when that is the case they are usable on any item affected by degradations.

**Comment by MiroslavR** [comment]
> Scrolls of remove curse can be used to clear the degraded debuff

Interesting. I didn't know that.

However, in my case the degraded debuff didn't get cleared. I used it on an item that wasn't affected by degradation. I think it was an artifact.

**Comment by MiroslavR** [comment]
> However, in my case the degraded debuff didn't get cleared.

I cannot reproduce this part anymore.

Still, why are the last three items not grayed out?
![equipment](https://github.com/00-Evan/shattered-pixel-dungeon/assets/7346770/19206fb2-fe51-4aaf-9cf1-48cf14b6ebc3)

**Comment by 00-Evan** [comment]
Using the scroll will break the degraded debuff regardless of what item it's used on, so you can use on anything.
