### ISSUE TITLE
game does not respect "Play Music in Background" when changing scenes in background

### ISSUE THREAD

**Issue by EarthlySkies** [00-Evan/shattered-pixel-dungeon#1619]
Description
===========

With the following conditions, the game does not respect an unset "Play Music in Background" option. Instead it continues to play music even when the game window is unfocused.

System info
-----------

Official release: Yes
Game version: 2.3.2
Game build: MacOS native executable
Operating system: MacOS Sonoma 14.4

Steps to reproduce
------------------

1. Unset/disable the "Play Music in Background" option from the game settings.
2. Start/load a game.
3. Switch focus away from the game window (e.g. Alt-Tab) during the "Loading..."/"Descending..." screen.
4. The game now plays sounds on the background regardless of the unset option.

Expected behavior
-----------------

The game should respect the unset "Play Music in Background" setting and be quiet as normal.

**Comment by 00-Evan** [comment]
Fixed in commit 19ac7e7a45be34d1af968f9cf1966dc89fac090e
