### ISSUE TITLE
Wandmaker quest Newborn Fire Element is able to cast fireball range attack after being teleported outside the room with a Displacing Dart

### ISSUE THREAD

**Issue by ChuiyuWang1** [00-Evan/shattered-pixel-dungeon#1620]
On the turn the Element preparing its fireball attack, I thrown a Displacing Dart to it and the next turn it was in another room but still able to cast the fireball.

**Comment by 00-Evan** [comment]
Fixed in commit 78429602f884cb638c4d0faa56fe26ced4200ec2
