### ISSUE TITLE
Game closes about 5 seconds after opening

### ISSUE THREAD

**Issue by possiblyneal** [00-Evan/shattered-pixel-dungeon#1621]
If i run from console I get the following output:

[ALSOFT] (EE) Failed to connect PipeWire event context (errno: 112)
[Controllers] added manager for application, 1 managers active

Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-18-amd64 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Dell Inc.
Product Name: Inspiron 7573

**Comment by 00-Evan** [comment]
Hm, closing after a few seconds is an interesting error case. Does this occur when running the latest v2.3.2 and also the previous v2.2.1? There were some internal changes in 2.3.2 that may be related to this.

https://github.com/00-Evan/shattered-pixel-dungeon/releases

**Comment by possiblyneal** [comment]
I should note that I am using the flatpak version which is 2.3.2. I am new to Debian and Linux, I downloaded the zip files for those versions. I don't know how to run them. Debian advises against running software outside of their repositories or flatpak anyway. I've already broken it a few times and trying not to reinstall for the 5th time. Sorry if that makes this a dead end. I'm happy to test anything else out for you.

**Comment by 00-Evan** [comment]
Unfortunately I don't provide support for unofficial distributions of the game. the easiest way to try running it directly might be to install java on your system and use the .jar distribution. If flatpak supports reverting to older versions of software you could also try that.

**Comment by TheShadowOfHassen** [comment]
> I should note that I am using the flatpak version which is 2.3.2. I am new to Debian and Linux, I downloaded the zip files for those versions. I don't know how to run them. Debian advises against running software outside of their repositories or flatpak anyway. I've already broken it a few times and trying not to reinstall for the 5th time. Sorry if that makes this a dead end. I'm happy to test anything else out for you.

I use the flatpak and my version runs perfectly. However, after a brief web search, it looks related to either flatpak permissions or your pipewire.

I'd install flatseal and make sure shattered pixel dungeon has pipewire permissions. If so, it's something wrong with your system.

> Unfortunately I don't provide support for unofficial distributions of the game. the easiest way to try running it directly might be to install java on your system and use the .jar distribution. If flatpak supports reverting to older versions of software you could also try that.

The flatpak is the java. :-)

I would really encourage you to consider making flatpak an official source. It's much easier for Linux users than downloading from source, and it's really easy to maintain. (I should know, I've been doing it for the past few releases.)

**Comment by possiblyneal** [comment]
I understand completely. I didn't know that flatpak was unofficial. So you are aware, the pixel dungeon page on discover, the package manager for KDE Plasma, offers a report bug button that takes you to this github.

**Comment by possiblyneal** [comment]
@TheShadowOfHassen could you share your flatseal config? is that even a thing?

**Comment by TheShadowOfHassen** [comment]
> @TheShadowOfHassen could you share your flatseal config? is that even a thing?

 No it isn't but you're right. There isn't a pipewire option.

I think you have a problem with your system's audio, try updating, and restarting. If that doesn't work, reinstall your pipewire.

What version of debian are you running?

**Comment by 00-Evan** [comment]
@TheShadowOfHassen 

> I would really encourage you to consider making flatpak an official source. It's much easier for Linux users than downloading from source, and it's really easy to maintain. (I should know, I've been doing it for the past few releases.)

I'm afraid this convo demonstrates really well why that's a bad idea. I have no knowledge of the flatpak/flathub system, how to build for it, and how to help users troubleshoot it. I don't want to officially endorse a release unless I can support it properly.

I've got nothing against unofficial builds though, the game's open source for a reason. The only time I have ever reccomended against one was the F-Droid distribution, and that's because of significant technical issues with their platform versus getting APKs on github. You might consider adding yourself as a support link for the flatpak version, although I'm happy to recieve messages from flatpak users that don't relate to the distribution specifically.

I'm going to close this issue as there's nothing I can do on my end, but please feel free to. keep troubleshooting, @possiblyneal I hope you're able to get this resolved.

**Comment by possiblyneal** [comment]
@TheShadowOfHassen 
I've updated, restarted, reinstalled pipewire and checked pixel dungeon along the way. It didn't work. My work around is to restart and play without opening any other programs.

**Comment by TheShadowOfHassen** [comment]
Honestly, it sounds like a bug with pulse audio or flatpak. If you're not on Debian stable, it should be fixed eventually.

**Comment by TheShadowOfHassen** [comment]
Sorry @possiblyneal, but I think I might have made a new discovery. Could you run : pipewire --version please?
