### ISSUE TITLE
Request/clarification: Should Ring of Energy affect duelist weapon charges?

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#1625]
The Duelist's talent `Weapon Recharging` states:
```
+1/+2: The Duelist gains one primary weapon charge every 10/6 turns when under the effect of wand or artifact recharging buffs.
```
This does not (presumably intentionally) seem to trigger when the Duelist is wearing a Ring of Energy. It might avoid some confusing to add the word "temporary" to the talent description to clarify that the ring is not affected by this talent:
```
+1/+2: The Duelist gains one primary weapon charge every 10/6 turns when under the effect of temporary wand or artifact recharging buffs.
```
Related, it could be neat if the ring affects weapon charge rate too.

**Comment by 00-Evan** [comment]
The talent is specifically referring to the 'wand recharging' buff and the 'artifact recharging' buff. Ring of energy does not apply either of those buffs.
