### ISSUE TITLE
Cant climb down stairs when there's posonous gas

### ISSUE THREAD

**Issue by nrdmn** [00-Evan/shattered-pixel-dungeon#163]
Hi,
I can't climb down stairs if there's poisonous gas on the same tile as the stairs. If I walk on that tile, nothing happens. I'm using version 0.5.0a.
I think this is a bug.

**Comment by 00-Evan** [comment]
This is intended, movement and actions are interrupted when you take damage. If you tap on the stair again when you are standing on it you will use the stairs.
