### ISSUE TITLE
Thieves still drop 1 gold on the way back to the surface

### ISSUE THREAD

**Issue by vahnrr** [00-Evan/shattered-pixel-dungeon#1631]
On the way back with the amulet of Yandor, all looting from ennemies is disabled as intended.
However thieves (green/purple hooded ennemies) still drop 1 gold when hit.

I found this out on the Android v2.3.2 of the game.

**Comment by 00-Evan** [comment]
The ascension challenge doesn't specifically prevent enemy drops, but the hero will obviously be overlevelled for item drops from most enemies. Thieves dropping one gold when hit isn't a standard loot drop, so this is intended.
