### ISSUE TITLE
General speed issues

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1633]
I've made a similar report, with the talisman of foresight, but you fixed that one. This one is about caustic ooze, the debuff. If you are too fast, and you go onto water in a half turn, the caustic ooze effect doesn't go away until a full turn is met. This happens with fire in water as well. Also talisman of foresight's foresight effect lasts an extra turn too long.

**Comment by 00-Evan** [comment]
This is intended, you need to spend a turn on water to remove debuffs like burning or ooze, as they need a chance to act, recognize they are on water, and expire.
