### ISSUE TITLE
When playing with the translation pen (Android 5.0.2), the archive was lost when the device unexpectedly lost power.

### ISSUE THREAD

**Issue by undefined-hestudio** [00-Evan/shattered-pixel-dungeon#1634]
When playing with the translation pen (Android 5.0.2), the archive was lost when the device unexpectedly lost power.

**Comment by 00-Evan** [comment]
This is probably entirely related to the power loss, and having nothing to do with using the translation pen.

The game will try to save itself when the device powers down, but there's nothing it can do if it get suddenly interrupted by power loss, which can lead to corrupted save data.
