### ISSUE TITLE
Maze room generated without chest in the corner

### ISSUE THREAD

**Issue by jokrefta** [00-Evan/shattered-pixel-dungeon#1635]
Not sure how useful this will be since I can't reproduce the issue, but I had a run where the hidden maze room didn't generate with a chest. There should be a chest in the top left corner - I can find it there if I start a new game with the same seed. But in this one instance, it was missing.

![Screenshot_20240312_004316](https://github.com/00-Evan/shattered-pixel-dungeon/assets/48812097/92849cec-c739-4b94-9d78-ea7333bcd2a7)

Seed VCN-XJN-MYB,
version 2.3.2

**Comment by 00-Evan** [comment]
There's not a lot I can do to potentially fix the issue if it's not reproducible. Was there anything that might have happened to the chest, such as an explosion destroying it?
