### ISSUE TITLE
A strange floor, maybe a seed generation bug

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1636]
screenshot↓(I've used Stone of Clairvoyance)

![Screenshot_20240314_113928_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/87411658/afa2659d-8bf6-4c38-a3ff-30a0923b03bd)
![Screenshot_20240314_113024_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/87411658/bca82adc-c9cf-460b-a697-5b667406621d)

This floor is strange because:
1. rather tiny, with only five rooms and one corridor 
2. floor 3, but no crabs generated when I first descend to this floor.
3. 3 mobs genrated in the 3x3 room.(Scared me!)
4. the upper left of the map is simply filled with walls. Maybe originally it's used to genrate other parts of the map?

**Comment by 00-Evan** [comment]
This is rare, but working correctly. That's a giant sewer pipe room with both of its connections in one corner, which means most of the room will be filled in with wall.
