### ISSUE TITLE
Huntress Natures Bounty

### ISSUE THREAD

**Issue by Cold-Control** [00-Evan/shattered-pixel-dungeon#1637]
v2.3.2 windows version.
0 berries dropped and i choose to skillup nature's bounty as first and second skill and i just cleared depth 3, character is lvl 4 1/2
On an older version i have v2.2.0 it works as intended.

**Comment by 00-Evan** [comment]
I'm assuming you did end up finding barries. The drop rate isn't garunteed, but does keep increasing if you haven't found any, which makes situations like this rare but possible.

**Comment by Cold-Control** [comment]
Hi! Yes, after the next level I found a bunch of them.
Can I just say I've been playing your game for many years and i
absolutely LOVE IT.
Thank you so much for your hard work.

**Comment by 00-Evan** [comment]
Thank You!
