### ISSUE TITLE
ghost does not use projection on weapons

### ISSUE THREAD

**Issue by patman-cp** [00-Evan/shattered-pixel-dungeon#1638]
V 2.3

When the ghost is outfitted with a weapon that has projection, she doesn't use it.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Equipping a projecting weapon on the ghost correctly increases their attack range by 1 from a quick test. Can you give any more info about the circumstances where you encountered this?

**Comment by patman-cp** [comment]
I'm "directing" the ghost to a location, and equip it with either a projecting great axe or projecting stone gauntlet (ring of wealth run) but it only attacks when the mob is right next to the ghost.

I can upload a video, but don't think that really helps other than proving that the above is true.

The game is still in progress.

**Comment by patman-cp** [comment]
OK, put a video of it here: https://www.youtube.com/shorts/SCDRK37sJIc

(Gah youtube seems to change every time I use it, no idea why it's in "shorts".)

**Comment by 00-Evan** [comment]
The ghost is not able to see through the furrowed grass, which is why they aren't attacking at a distance.
