### ISSUE TITLE
When finding a cooked blandfruit from hero's remains, sometimes you get a ____fruit named Blandfruit

### ISSUE THREAD

**Issue by benzarr410** [00-Evan/shattered-pixel-dungeon#164]
![screenshot_2017-03-14-20-54-44](https://cloud.githubusercontent.com/assets/25698061/23928970/50084734-08f9-11e7-8e6c-e83ae70e5059.png)
My brother found this, Droid 5.0, Shattered 0.5.0b, or whatever the newest is.

**Comment by 00-Evan** [comment]
thanks will fix in the next update.

**Comment by 00-Evan** [comment]
fixed in commit 4515e5ab79c4ab8f52d0279fd5f45dd4ade2dfd9
