### ISSUE TITLE
Gnoll geomancer places rocks on exit tiles

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1640]
Sometimes, the gnoll geomancer can generate rocks on the same tiles as the metal ones that surround the exit. This causes a visual bug due to the tiles being on a higher layer than the rocks, so it looks cut off. I don't have a screenshot, but it should just be a really easy fix.

**Comment by 00-Evan** [comment]
I've edited your post as I do not accept code contributions/suggestions. Will look into this quirk regardless.

**Comment by 00-Evan** [comment]
Fixed in commit 8f237dc66ae8b83389be968b48a41a2aefcef7dc
