### ISSUE TITLE
After defeating yog, the vision is still only 1

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1641]
Leaving and returning to the 25th floor, or reloading the game can restore normal visibility
![Screenshot_20240318_234117_6f3fe77889fbecf862f7061166760abf](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/4450ab3d-1e49-4288-8492-96fbd4592661)

**Comment by 00-Evan** [comment]
Fixed in commit 24f5d738cfaa293a45b5ae3602f2a547f43109e8
