### ISSUE TITLE
Boomerang may be lost in rare case

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1643]
If the hero uses props（such as aqua blast） to push themselves into the chasm while the boomerang is about to return, the boomerang will never return.

**Comment by 00-Evan** [comment]
looks like this is happening because the actor thread is continuing to process if chasm falling happens as a result of the pushing effect, and not the hero's action.

**Comment by 00-Evan** [comment]
Fixed in commit 7195d81d7b18e9333ec8e2805a696d67e66ef41d
