### ISSUE TITLE
A small error of the Armband

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1645]
If the package is full and you steal items from the store, the energy of the armband in quick slot will not immediately change.
![Image_1710942184937](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/541f28ad-b51f-44b6-87b6-8d2362fbc2f6)

**Comment by 00-Evan** [comment]
Fixed in commit ec165ecbe70d9ea61f539950306a12c0c3d12f74
