### ISSUE TITLE
Quick Setup mentions needing Java 11 - project actually requires Java 17

### ISSUE THREAD

**Issue by wongjustin99** [00-Evan/shattered-pixel-dungeon#1647]
[This page](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/docs/getting-started-desktop.md) mentions needing Java 11 as a minimum. It appears to actually require Java 17. 

Switching to Java 17 fixed this so I could build.

**Comment by 00-Evan** [comment]
Fixed in commit ddd2b2fa3b987b7bc943fb4eb61b711965c4e2cc
