### ISSUE TITLE
No text found in latest 0.5 beta on shortsword

### ISSUE THREAD

**Issue by brunal** [00-Evan/shattered-pixel-dungeon#165]
![screenshot_20170317-104237](https://cloud.githubusercontent.com/assets/921168/24045663/b19951ee-0b17-11e7-9508-3fe20a244f4c.png)
![screenshot_20170317-104243](https://cloud.githubusercontent.com/assets/921168/24045664/b1a95b8e-0b17-11e7-949a-d8575ea2868d.png)

**Comment by 00-Evan** [comment]
Betas do not have an associated source release, so github issues are not the correct place to report bugs. Please email me directly. Regardless, I will get this fixed.
