### ISSUE TITLE
Easy mode for kids

### ISSUE THREAD

**Issue by piec** [00-Evan/shattered-pixel-dungeon#1650]
Hi Evan,

Thanks for you great game.

I quickly hacked a patch to make an easy mode fork my kids a few weeks ago https://github.com/00-Evan/shattered-pixel-dungeon/commit/219a4a7920e461b631c9898f8102d3ef9957508e

Would this be something you would be interested in adding to the game as a variant/option when starting a new game or should I keep this a a fork?

Cheers,
Pierre

**Comment by 00-Evan** [comment]
Afraid I don't accept code contributions. Github issues are open mainly for bug reports.

As far as difficulty goes in general, I have considered adding a 'starter mode' at some point in the future, with toned down difficulty and a max of floor 10, mainly focused on teaching players how the regular game works, but otherwise am not interested in adding difficulty settings to the game.

**Comment by TheShadowOfHassen** [comment]
Random stupid idea: Perhaps you should set the starter mode in a different dungeon, with different easier mobs, and a backstory for the warrior. (A training hall or something?)

**Comment by 00-Evan** [comment]
> Random stupid idea: Perhaps you should set the starter mode in a different dungeon, with different easier mobs, and a backstory for the warrior. (A training hall or something?)

This is possible of course, but would substantially increase the work required to make such a mode, and would slightly go against the point of trying to prepare the player for the main dungeon.

Just as an example, one of the changes a starter mode might have is that all food heals a % of missing HP when starving, which would help players build the habit in starter mode and continues it in the main game.

**Comment by TheShadowOfHassen** [comment]
> Just as an example, one of the changes a starter mode might have is that all food heals a % of missing HP when starving, which would help players build good food eating habits in starter mode and continue it in the main game.

I don't see how putting that in a separate dungeon would detract from the main part of the game, in a way it could allow it to make more sense. I.E. explain why in the dungeon food won't heal you.

**Comment by 00-Evan** [comment]
> > Just as an example, one of the changes a starter mode might have is that all food heals a % of missing HP when starving, which would help players build good food eating habits in starter mode and continue it in the main game.
> 
> I don't see how putting that in a separate dungeon would detract from the main part of the game, in a way it could allow it to make more sense. I.E. explain why in the dungeon food won't heal you.

Changing the environment creates the possibility of the habit only applying in that separate environment.

**Comment by TheShadowOfHassen** [comment]
> Changing the environment creates the possibility of the habit only applying in that separate environment.

I don't think that would happen. I mean, if you want to keep it the same it's your game, but I figured this would be an interesting way to add more lore about one of the heroes... Maybe explain why the warrior broke his seal.

**Comment by piec** [comment]
> Afraid I don't accept code contributions. Github issues are open mainly for bug reports.

No issues, I'll probably try to occasionally rebase my patch and stay up to date.

> As far as difficulty goes in general, I have considered adding a 'starter mode' at some point in the future, with toned down difficulty and a max of floor 10, mainly focused on teaching players how the regular game works, but otherwise am not interested in adding difficulty settings to the game.

That could be cool :+1:

**Comment by piec** [comment]
Also related: https://github.com/00-Evan/shattered-pixel-dungeon/issues/1033#issuecomment-1188213198

**Comment by piec** [comment]
Some people are writing to me about it so I just updated my easy version (for kids): https://github.com/piec/shattered-pixel-dungeon/releases/tag/v3.3.6-easy

**Comment by ghost** [comment]
What specific changes are there? Because I downloaded it and played up to
Goo, but I don't see the difference. It says it's "for kids" — I expected
it to be easier or something, maybe even simplified text. I don't know, it
made me curious, so I decided to download it.

**Comment by piec** [comment]
@agneljsc-ui, you have more HP, and less hunger
When you run the game, check that you see "v3.3.6-easy" and that you start with 60 HP

**Comment by ghost** [comment]
Ah, I didn't notice xd

I feel a bit embarrassed 😳
