### ISSUE TITLE
Dwarf Ghouls summoned by Summonning Trap are able to duplicate themselves in full health when they stand up again

### ISSUE THREAD

**Issue by ChuiyuWang1** [00-Evan/shattered-pixel-dungeon#1651]
Seed: HJZ-QXR-MHG
Challenges: Hostile Champion, Badder Bosses, On Diet, Barren Land, Swarm Intelligence, Into Darkness
Location: Floor 16 secret summonning trap room

The summonning trap summoned many dwarf ghouls, warlocks and elements, among which one ghoul is giant champion and another ghoul is anti-magic champion. I used a Scroll of Psionic Blast to eliminate all warlocks, elements, and because of the anti-magic ghoul champion, I cannot eliminate any of the ghouls. The room then had some empty spaces because of the mob eliminated. After 4 turns (or so), all the downed ghouls should stand up again with 5 health, but nearly each of the ghouls stand up with duplicating themselves. The duplicated ghouls were all in full health, and filled the empty spaces in the room, so as the champion ghouls did. 

Normally I don't think single downed ghouls could generate full-health replicas. The dwarven king could also summon single ghoul, and when they were downed, they just lied down, and then stand up with 5 health if there were living ghouls nearby. I was wondering if this was intended.

**Comment by 00-Evan** [comment]
Ghouls always generate a partner on the first action they have, in the case of summoning traps that partner-creation logic is delayed because of the summoning.
