### ISSUE TITLE
Suggestion: Make the crazy thief use up the ankh when he dies.

### ISSUE THREAD

**Issue by TadaCZE** [00-Evan/shattered-pixel-dungeon#1653]
The crazy thief is supposed to be human (just corrupted in some way). Wouldn't it make sense for an ankh to be useful to him just as much as to the player?

**Comment by 00-Evan** [comment]
I decided not to do this when implementing their new steal mechanic back in the day. Letting them steal an ankh to begin with already felt cruel enough.
