### ISSUE TITLE
Picking up an item while inventory is full repeatedly produces makes the item move indefinitely.

### ISSUE THREAD

**Issue by TadaCZE** [00-Evan/shattered-pixel-dungeon#1654]
Or, simply put, it makes the item go weeeeeeeeeeeeeeeeeeee right up.

This is an issue only with the animation - purely visual. It doesn't actually change the item's position. To reproduce, you just have to have a full inventory and repeatedly try to pick up the same item.

**Comment by TheShadowOfHassen** [comment]
I can confirm that it happens. But I kind of enjoy it going Wheeeeeeee! All the way up to the top of the map.

I think if @00-Evan keeps it around he should add an achievement if you get it up far enough.

**Comment by 00-Evan** [comment]
This is intended actually, see: #1540, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1468, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1436, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1355, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1150, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1073, https://github.com/00-Evan/shattered-pixel-dungeon/issues/689, https://github.com/00-Evan/shattered-pixel-dungeon/issues/640, https://github.com/00-Evan/shattered-pixel-dungeon/issues/203, https://github.com/00-Evan/shattered-pixel-dungeon/issues/40
