### ISSUE TITLE
Into darkness challenge reduces visible distance more on PC than on mobile

### ISSUE THREAD

**Issue by mxruben** [00-Evan/shattered-pixel-dungeon#1655]
With the "Into Darkness" challenge enabled, you have a visible distance of 2 tiles on mobile. On PC, this is reduced even more to just 1 tile, making it much more difficult.

**Comment by 00-Evan** [comment]
From a quick test the range is 2 on both platforms. You might have been playing on a dark level on PC, which also reduces visibility and does stack with the challenge.
