### ISSUE TITLE
Monks equipped with tier3 weapons can also obtain +1 talent effect even when they have +3 talent

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1659]
Should we emphasize that +3 also has a gain of +1+2 at the same time?
![Screenshot_2024_0413_232707_com shatteredpixel shatteredpixeldungeon statistical](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/316b0344-b9a7-4aef-b954-74eb6d7b5389)
![Screenshot_2024_0413_232539_com shatteredpixel shatteredpixeldungeon statistical](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/a061c33e-f76f-4098-a45d-062797ae4ef1)

**Comment by 00-Evan** [comment]
I opted not to do this for unencumbered spirit for the sake of brevity, the talent description was already very long.
