### ISSUE TITLE
Lucky enchantment and Dagger/Dirk/Assassin's blade interact incorrectly

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#166]
The lucky enchantment forces a roll between min and max.
The assassin's blade forces a roll between (min+max)/2. 

The lucky enchantment overrides the damage roll on proc, which must occur after the damage calculation of the assassin's blade.

Perhaps the correct solution is to set the min() function (if hero.enemy is defined) in the assassin's blade (and dagger and dirk) class instead of overriding damageRoll()?

**Comment by 00-Evan** [comment]
This is known, and I have previously stated this is working as intended.

Similarly to how you're suggesting changing the game logic, it all depends on whether a stealth weapon's bonus is affecting it's minimum or affecting the roll. My stance has been that stealth weapons roll more favorable, but their minimum damage stat is unchanged. Lucky forces a min or max hit and ignores rolling, and therefore overrides the bonus of a stealth weapon.

**Comment by camlost** [comment]
Ok.

**Comment by 00-Evan** [comment]
I'm deciding to re-open this.

The current behavior for lucky is problematic, even if technically correct, and lucky needs some help in the balance department regardless.

I've decided that I'm going to slightly rework Lucky, to instead either double damage or set it to 0. This means it'll interact much more nicely with any sort of damage-altering effects.

**Comment by 00-Evan** [comment]
changed in commit 7b47dc5200ffc7309b5be7c571b84b342e107787
