### ISSUE TITLE
Taste Vengeance ought to be obtainable multiple times

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1660]
Especially considering the other remains-related badge is repeatable, there's no reason this one shouldn't be.

**Comment by 00-Evan** [comment]
I'm not entirely sure what you mean by this, all badges can only be unlocked once. Do you mean having the badge show up on a given run in the rankings screen?

**Comment by chorby-short** [comment]
Yes. I guess 'endorsed' would be the proper phrase.

**Comment by 00-Evan** [comment]
Yeah I can see that, it's being treated a bit too much like meta badges such as "beat the 1st boss with every hero" atm.
