### ISSUE TITLE
Literally no exit generated?

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1662]
![where](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/ef871f4b-d079-485d-99c7-5c5d60063ab5)
As you can see, it didn't generate an exit tile. You can still just jump down, but I don't think this should happen. My best guess is that somehow the exit ladder generated on the same tile as the Troll's quest ladder and the quest ladder took priority. Either way, never seen this before. Seed is FFT-XCR-VHD.

**Comment by TheShadowOfHassen** [comment]
Do you have a scroll of magic mapping? The room with the exit might be hidden.

**Comment by Howdidibreakit** [comment]
I'm pretty sure that the exit cannot be in a hidden room, I've never seen it happen before, and hidden rooms always have a special tiling that the exit can't generate on.

**Comment by 00-Evan** [comment]
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2347603/ced80103-65ce-4627-baa7-dc24a73d6978)

**Comment by Howdidibreakit** [comment]
well that's a first

**Comment by 00-Evan** [comment]
> well that's a first

You were on a secrets floor, which randomly hides some groups of rooms. That can lead to the exit being hidden.
