### ISSUE TITLE
Suggestion: Stone of Blink preventing chasm damage

### ISSUE THREAD

**Issue by jessdwitch** [00-Evan/shattered-pixel-dungeon#1665]
It'd be a cool solution to chasm rooms to throw a Stone of Blink down the chasm and safely teleport down to the bottom. As it stands, throwing it down there causes no teleportation, and the stone to appear somewhere random on the floor below.

**Comment by 00-Evan** [comment]
This has been suggested a few times, and while I agree that it is cool thematically, it would be really overpowered. Consider that featherfall does this and is very popular and powerful despite being a much more expensive item.
