### ISSUE TITLE
Some damage sources use the wrong icon type

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1668]
Life Link shows physical damage. Magic damage or white damage should be more reasonable

**Comment by Lyx0527** [comment]
Arc electricity and bonus damage of Shock Elemental deals physical damage.But these damages will not be weakened by armor or elemental rings.

**Comment by 00-Evan** [comment]
There are likely a few cases of this where I missed giving certain damage sources the correct indicator (the actual game logic is correct though). They're all simple fixes though.

**Comment by Lyx0527** [comment]
> (the actual game logic is correct though)

I think I need to emphasize that elements rings cannot reduce the non-physical damage of shock elementals, which is different from shocking enchantment.

**Comment by 00-Evan** [comment]
> > (the actual game logic is correct though)
> 
> I think I need to emphasize that elements rings cannot reduce the non-physical damage of shock elementals, which is different from shocking enchantment.

Perhaps I should clarify what I meant. The icons are typically not strictly tied to game logic, and so showing the wrong icon does not mean the damage type is incorrect, they are separate issues.

**Comment by 00-Evan** [comment]
Fixed in commit 83bd90608bed904b5cc1d5f7ff4092f50a4b14e0
