### ISSUE TITLE
Heroes are always more inclined to chase allies rather than walking to the target location

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1670]
The purpose of players clicking on positions without enemies is often to move. Chasing allies is meaningless, it also can lead to heroes walking uncontrollably long distances. This like chasing enemies who charmed heroes, can bring a bad experience.

**Comment by Lyx0527** [comment]
In the narrow corridor, when players click behind their allies, the hero will choose to detour to their destination instead of directly approaching their allies and exchanging positions with them.

**Comment by 00-Evan** [comment]
Pathfinding doesn't automatically trigger extra actions such as swapping places with an ally. It is intended that allies are considered blocking when it comes to pathfinding, and that the hero picks a route that goes around them if you tap behind them. It's also intended that if the player does tap on an ally that the game assumes the player wants to interact with them, and so the hero will keep moving toward the ally even if they move away.
