### ISSUE TITLE
Missing stones after converting scroll in alchemy pot

### ISSUE THREAD

**Issue by mbaz** [00-Evan/shattered-pixel-dungeon#1671]
Version: 2.3.2

I used an alchemy pot to convert a scroll of upgrade into two stones of enchantment. Afterwards, the scroll was gone but the stones were not in my inventory. The velvet pouch happened to be full, which may be the problem.

If the issue is indeed that the pouch was full, I suggest either disallowing the conversion, or having the stones appear on the ground as items to be picked up.

**Comment by mbaz** [comment]
I found them in main inventory -- sorry for the spurious report :facepalm:

**Comment by 00-Evan** [comment]
No worries, the game does have catches for the situations. They fall to the ground if your inventory is totally full.
