### ISSUE TITLE
Potions splash into particles with wrong color

### ISSUE THREAD

**Issue by TrashboxBobylev** [00-Evan/shattered-pixel-dungeon#1672]
So we have this little strength potion right here, it is very purple and mysterious, should splash into magenta particles, right? (that's what the code says it should do, as it supposedly picks the color from sprite):
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/22856970/27f8037b-391c-46a5-8a10-5ed32480c875)

It explodes into blue particles:
![javaw_4xpaSMEnqD](https://github.com/00-Evan/shattered-pixel-dungeon/assets/22856970/8c3ce8f4-fd6c-41f0-836e-ce3ed6f18370)

Encountered while developing Summoning: Reincarnated 0.3.0 and confirmed in Shattered PD 2.3.2.

**Comment by TrashboxBobylev** [comment]
I just checked and this thing might have been actually present for a really long time:
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/22856970/9fb70d44-cca9-497d-9ec7-e322480da214)

**Comment by 00-Evan** [comment]
Thank you for the report, but please do not make suggestions for how to specifically investigate/fix the code for a bug. I have deleted the relevant messages

**Comment by 00-Evan** [comment]
Fixed in commit 25ddbcf0719368f685b50d5f68e380df6e413f55
