### ISSUE TITLE
Item color after Strongman skilling

### ISSUE THREAD

**Issue by basxto** [00-Evan/shattered-pixel-dungeon#1673]
I skilled 1 point in `Strongman`, raising my strength to `16 + 1`

The `:17` of a `Plate Armor of Swiftness +1` in my inventory stayed red. The number only became white after dropping it and picking it up again.

version: 2.3.2

**Comment by 00-Evan** [comment]
Fixed in commit 811a3b5050d5a54d828aabd6198a525a25374ba4
