### ISSUE TITLE
The mage turns invisible when he tramples grass

### ISSUE THREAD

**Issue by ZuperZeus** [00-Evan/shattered-pixel-dungeon#1675]
version v2.4.0-BETA-1 
With:
-Empowering Meal +1
-Scholar's intuition +2
-Lingering magic +1
-Backup barrier +1
-Inscribed Power +1
-Arcane Vision +1
None of these mention invisibility when trampling grass, and at the beginning of the run this didn't happen, the only unusual thing besides the above might be a Rat Skull +3, but dropping it doesn't change this, is this a bug or intended behaviour I missed somewhere?

**Comment by 00-Evan** [comment]
Do you have a glyph of camouflage on your armor?
