### ISSUE TITLE
Wandmaker blocked the way

### ISSUE THREAD

**Issue by Aresf0** [00-Evan/shattered-pixel-dungeon#1676]
![Screenshot_2024-05-01-23-14-17-138_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/129938108/46ca4cd7-1f0b-4ded-acbe-78814a2f856e)

**Comment by 00-Evan** [comment]
This should be fixed in BETA-2
