### ISSUE TITLE
Holiday potions should have some potion properties

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1677]
Perhaps not in terms of being stored in the bandolier, but it is weird that they don't break when thrown off dose the player, for instance. If you don't want them broken fully, I feel like a few additional items á la blandfruit chunks could be created; you already have one auxillary holiday food item in leftovers.

At the very least, there should be some lore reason they can't break otherwise.

**Comment by 00-Evan** [comment]
Internally they are considered food items, and putting in the extra work to have them behave differently when thrown seemed unnecessary. They also shouldn't be available in the game yet, don't go changing your system clock ;)
