### ISSUE TITLE
Grass is showed trough the door

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#168]
If there's grass behind a door which is placed on a horizontal (screen) wall, you haven't seen the part underneath it but there's grass you'll see that one grass tile.

**Comment by 00-Evan** [comment]
working as intended, allowing the player to slightly see through doors was a design choice.

**Comment by OffifialMITX** [comment]
Why that? (Not like I have a problem with it)

**Comment by 00-Evan** [comment]
It makes doors much easier to see, there were consistent complaints about door visibility during beta tests. Allowing the player to figure out what tile is right next to the door isn't the reason I did the change but it is part of it.

**Comment by OffifialMITX** [comment]
Ok, then.
