### ISSUE TITLE
Trinkets should get listed in the item lists (as should missles, for that matter)

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1680]
Is there any reason they shouldn't be? They can be added as the player picks them up. Yes that would make nine tabs, but that isn't any more than the alchemy book. It would reduce the player's dependency on outside sources, which was the whole point of providing weapon/armor etc. lists to begin with, right?

**Comment by a-One-Fan** [comment]
Seconded; Personally, I don't care about the number of tabs, and I think there should also be tabs for curses, glyphs and enchantments.

**Comment by 00-Evan** [comment]
I'm aware that the catalog there is becoming increasingly dated, but for now it is only meant to contain items which can be identified.

**Comment by chorby-short** [comment]
Is there any chance the trinkets can be listed in the alchemy guide then? There's already one fewer page this update, and they are technically something you brew.
