### ISSUE TITLE
Notify user of broken seal glyph transfer mechanics exceptions

### ISSUE THREAD

**Issue by svew** [00-Evan/shattered-pixel-dungeon#1681]
I just recently learned that apparently "naturally occurring" glyphs cannot be transferred by the warrior's broken seal if they have "runic transference".

While playing however, there was no indication that this wouldn't work, so when detaching the seal failed to carry the glyph with it, it seemed like a game bug rather than a limitation of the ability.

My suggestion is to either:
- Add a note to the "Runic Transference" ability that only glyphs the user has manually applied can be transferred
- Or, show a notice when the user detaches the broken seal from armor with a natural glyph that the glyph won't transfer for this reason

**Comment by 00-Evan** [comment]
Hm, the broken seal used to make this more clear in it's description. The talent makes reference to the seal, which can't be used to '
steal' an upgrade from a random armor. I'll consider adjusting the seal's descriptions, but the talent itself should still just make reference to the seal.

**Comment by 00-Evan** [comment]
Fixed in commit d39a9b7709585d56b45f59c1fba410da348ad00f
