### ISSUE TITLE
Boss will constantly chase heroes in black smoke or behind high grass

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1682]
This makes the boss's actions counterintuitive. How about making them stop chasing heroes when they are close to them and can't see them?

**Comment by 00-Evan** [comment]
Which boss?

**Comment by Lyx0527** [comment]
DM300, fists

**Comment by 00-Evan** [comment]
In that case this is intended. Fists can always see you to a degree because of Yog-Dzewa, DM-300 needs to have an idea of your location so that it can tunnel to you or use abilities when you're behind walls.
