### ISSUE TITLE
Swift Equip and Hourglass

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1683]
If turn until charge use is 0, switch weapon will use 1 charge and set timefreeze turn to 2.

**Comment by 00-Evan** [comment]
I assume you're referring to the beta

**Comment by 00-Evan** [comment]
whoops, didn't mean to close this, Am planning to have it fixed in BETA-3 actually.

**Comment by 00-Evan** [comment]
Fixed in BETA-3
