### ISSUE TITLE
Duelist's rapier shows "Target can't be reached" when too close

### ISSUE THREAD

**Issue by svew** [00-Evan/shattered-pixel-dungeon#1684]
When you play as the Duelist, and try to user her rapiers "lunge" attack on an enemy that's directly next to you, the action fails, and the text shows "Target can't be reached". This seems misleading, because "can't be reached" means that something is too far away, not that it's too close.

Can we change this message so if the rapier's lunge is used on an enemy too close (or any ability that's being used too close) it shows a message that says "Target is too close"?

**Comment by 00-Evan** [comment]
That's correct, you can't reach the target with the ability as they're below the minimum range.

**Comment by svew** [comment]
I'm gonna push back a bit on what you said, but if you're not feeling convinced then I won't push it any further, it is after all just a little wording thing. However...

If you polled any number of people asking whether "can't be reached" means A) it's too far, B) it's too close, or C) it's either too far or too close, everyone would choose A. I'd be shocked if even a single person chose the other two options, except in the case that they thought it was a trick question somehow.

"Reach" starts at the origin and extends out, it doesn't start from some distance away and continue some even further distance. Saying "target can't be reached" due to it being too close is flat out incorrect and it doesn't make sense. I'd probably even say the same thing about "out of range", though there are some specific cases where "range" doesn't necessarily start at 0.
