### ISSUE TITLE
layout index error

### ISSUE THREAD

**Issue by HMYang33** [00-Evan/shattered-pixel-dungeon#1686]
![Screenshot_2024-05-06-02-03-28-583_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/94346595/289a977c-b3ba-41ba-8fc5-9eb43542220e)

2.4.0 beta
Android

**Comment by 00-Evan** [comment]
Thanks for closing this, just noting it as a duplicate of #1674
