### ISSUE TITLE
Troll Blacksmith generated without any inactive traps

### ISSUE THREAD

**Issue by a-One-Fan** [00-Evan/shattered-pixel-dungeon#1689]
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/100067309/367f67e1-930b-4dde-8290-779f3ca30aca)
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/100067309/767dc7f9-17c7-4528-a79d-0b6a77de6197)
I got the scroll holder first.

**Comment by 00-Evan** [comment]
It is exceeding rare, but possible, for the game to naturally spawn a trap on that tile after the room itself has generated with an open passage there.

Unfortunately I'm not able to reproduce this levelgen with the given seed, was this floor generated prior to the v2.4.0 beta?

**Comment by a-One-Fan** [comment]
> It is exceeding rare, but possible, for the game to naturally spawn a trap on that tile after the room itself has generated with an open passage there.
> 
> Unfortunately I'm not able to reproduce this levelgen with the given seed, was this floor generated prior to the v2.4.0 beta?

Sorry, I forgot to include the challenges, which should be hostile champions, badder bosses, barren land and swarm intelligence. Or... It's possible that I started this partially in Beta 1 and forgot.
