### ISSUE TITLE
"null" dew

### ISSUE THREAD

**Issue by complaining-user-engine** [00-Evan/shattered-pixel-dungeon#169]
Sometimes running over grass reveals dew represented by "null" in red letters.

If you stand on the same spot the "underfoot" indicator shows the proper graphic for this pickup.

Any other nearby dew has had the proper graphic too.

On Version 0.5.0b from f-droid

**Comment by SamSkulls** [comment]
I've seen this as well. Version 0.5.0a from f-droid. Same behavior, no idea how to reproduce.

**Comment by 00-Evan** [comment]
@complaining-user-engine 
@SamSkulls 

What devices do you guys have? Might help narrow it down as to whether it's an f-droid specific issue.

Also, as an aside, that is a great name @complaining-user-engine

**Comment by SamSkulls** [comment]
Galaxy Tab 4, Android 4.4.2.

**Comment by 00-Evan** [comment]
I've had someone using the google play version, so this is (thankfully) not an f-droid specific issue.

I'll look into this.

**Comment by 00-Evan** [comment]
There's been no development here, and nobody has reported this issue in quite some time, so i'm closing it. Feel free to post again if you encounter it.

**Comment by internecivusraptus** [comment]
I had encountered this bug recently on desktop version (v0.6.1b)
