### ISSUE TITLE
desc of Flurry of Blows

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1690]
It said 'This ability has no cooldown ', but all ability will be cooled together.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. The ability does not apply the cooldown if the monk has just attacked normally, as intended.

**Comment by Lyx0527** [comment]
What I mean is, "this ability needs cooldown" means "other abilities can still be used". In fact, while this ability requires cooldown, Monk cannot use other abilities.

**Comment by Lyx0527** [comment]
I see, thanks
