### ISSUE TITLE
make "picked up potion of experience" statement highlighted like upgrade scrolls and strength potions

### ISSUE THREAD

**Issue by kilsw1ch** [00-Evan/shattered-pixel-dungeon#1692]
i think it makes sense as exp pot can be used instantly like soU and poS without any harm and there's no "special" scenario to use it.
plus a lot of times the player carries on without realizing there's a free level or talent to be unlocked until they check the inventory

**Comment by 00-Evan** [comment]
Scroll of upgrade and potion of strength are special progression items, which is why they get green text. other consumables can be valuable of course, but that highlight is only meant for progression items.
