### ISSUE TITLE
suggestion: rogue with silent steps 2 makes it very easy to mine 40 gold in any troll quest(crystal/geomancer) 

### ISSUE THREAD

**Issue by kilsw1ch** [00-Evan/shattered-pixel-dungeon#1693]
what i've noticed is that all enemies(can't confirm) are asleep in these quests which allows the player to just stroll through the level collecting gold and dodging enemies. even if you return without killing the mini boss, you still get a upgrade plus reduced point of favor.
so i suggest some enemies spawn awake like the champions or are alerted when you mine gold in their vicinity, say 5-6 tiles away

**Comment by 00-Evan** [comment]
This is intended. Both of the bosses are designed so that you really want to deal with the regular enemies first, or you risk getting swarmed. I'm fine with some players choosing to only partly complete the quest as well.
