### ISSUE TITLE
remove curse cancelation rare case

### ISSUE THREAD

**Issue by kilsw1ch** [00-Evan/shattered-pixel-dungeon#1694]
when there is nothing in a player's inventory that is cursed/unidentified and you read a remove curse(lets say accidentaly) it gets wasted in a sense that there's no use of it. i think a one time cancelation should be allowed mostly cuz players are trying to read unidentified scrolls to identify them. 
tho keeping it as is makes it more grim which is good

**Comment by 00-Evan** [comment]
If you read the scroll and it was identified, you would be able to cancel it, but it's intentional that you can't choose to cancel a scroll you haven't identified yet, as otherwise you would get to identify it for free.
