### ISSUE TITLE
v2.3.0  The order in which the knockback effect of spike and elastic take effect is not fixed

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1695]

**Comment by Lyx0527** [comment]
Maybe I use a wrong word again.
Fixed: arranged or decided already and not able to be changed.
Spike with a elastic spear, enemy may knocked back 1 tiles, or 2 tiles. It's random.

**Comment by 00-Evan** [comment]
Okay, in those cases elastic should probably override spike, given that it pushes for 2 tiles instead of 1.

**Comment by 00-Evan** [comment]
Fixed in commit a8c429c9f89e685b3ba40c9fdba6ac11cb56f38b
