### ISSUE TITLE
Weapon ability of stone gauntlet was forgetten

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1696]
![{6D867208-CF00-4732-8D68-823788E4F836}](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/f88db112-3b35-4058-87f2-4a15c35b8fe6)

**Comment by 00-Evan** [comment]
I'm not sure what the issue is here. Also please report translation issues on Transifex.
