### ISSUE TITLE
Empowering Meal and Strengthening Meal

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1699]
If a zap or an attack deals damage more than one time, buff(zaps remaining) will consume quickly.

**Comment by 00-Evan** [comment]
Do you mean in cases where an attack damages multiple enemies at once, or one enemy multiple times?

**Comment by Lyx0527** [comment]
Yes, such as fireblast and lash with whip. In fact, I did not notice the latter situation, but it does not fully comply with Desc.

**Comment by 00-Evan** [comment]
I've decided to keep the functionality as-is, but will adjust wording for better clarity.

**Comment by 00-Evan** [comment]
Fixed in commit be01f3fdfe2f3ca409a8a4a88ae0f1d34c820dd0
