### ISSUE TITLE
Potion of Might appeared in the dungeon

### ISSUE THREAD

**Issue by squigish** [00-Evan/shattered-pixel-dungeon#17]
I was a rogue (no subclass) on one of the prison levels (I think it was level 6). It definitely did NOT come from a well of transmutation, since none had appeared in that run, and if it had, I would have used it for an artifact. 

I'm at a loss to understand how this could have happened. Could it possibly be some sort of roundoff error having to do with the floats used in the random potion generation? That doesn't make much sense to me, but it's the best bad explanation I can come up with.

**Comment by 00-Evan** [comment]
Did you have a ring of wealth?

**Comment by 00-Evan** [comment]
Assuming you had a ring of wealth, which will cause potions of might to appear in the level, albeit very rarely. Please feel free to comment if this is not the case and I'll reopen this issue.
