### ISSUE TITLE
The old wanker may spawn on the staircase, preventing the explorer from going up a floor before completing his quest

### ISSUE THREAD

**Issue by brunal** [00-Evan/shattered-pixel-dungeon#170]
![screenshot_20170322-210929](https://cloud.githubusercontent.com/assets/921168/24220968/51f3e318-0f44-11e7-8f35-df196312d158.png)

**Comment by 00-Evan** [comment]
What version are you playing?

**Comment by brunal** [comment]
v0.5.0c-BETA-2 according to the main menu.

**Comment by 00-Evan** [comment]
I thought so. I will fix this, but betas don't have an associated source release, so this isn't the right place to report issues with them.

In future please email me if you're having beta issues.
