### ISSUE TITLE
Duelist Monk can Dash onto Enemies

### ISSUE THREAD

**Issue by troylmadsen** [00-Evan/shattered-pixel-dungeon#1700]
BETA

Duelist monk is able to dash onto an enemy that is unseen. In the picture provided, I was standing in the corner 3 spaces to the left. The message in chat was for clicking on a space 4 to the right. The Scorpio was not visible while standing in the corner to the right.
![Screenshot_20240508_185559](https://github.com/00-Evan/shattered-pixel-dungeon/assets/22381506/474fe7da-aff9-49d7-8526-dec28b22869b)

**Comment by 00-Evan** [comment]
This should be fixed as of BETA-3
