### ISSUE TITLE
Magical Catalyst spawns in the toxic gas room, replacing the gold supposed to be in the chest. 

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1702]
![Screenshot_20240510_132322_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/87411658/6c30f209-1f2e-411f-84d3-cc5992e918fd)

**Comment by 00-Evan** [comment]
This is intended. The catalyst can appear within a special room on floor 1-3 in place of certain types of regular loot.
