### ISSUE TITLE
Eye of Newt does not allow auto targeting of detected enemies 

### ISSUE THREAD

**Issue by Geoffevans42** [00-Evan/shattered-pixel-dungeon#1703]
Hey, so I'm doing a battlemage run with +3 Eye of Newt as a trinket, and I've discovered that if it allows me to detect an enemy with mind vision, the enemy is not targeted by my staff if I select it.

Also, it might be cool to make the mind vision work like the potion, allowing you to see secret areas. Kind of useless as it stands.

**Comment by 00-Evan** [comment]
auto targeting generally does not trigger for mind vision enemies, to prevent performance issues caused by the game constantly trying to target enemies behind walls.
