### ISSUE TITLE
Pylon activates after killing DM-300?

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1704]
![Screenshot_20240512-200820](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/4341f8b9-c6b0-433a-8247-88c8ff407be2)

So this happened in the game I was just playing. Not sure what causes it, but perhaps it's related to the change to pylon activation at 100 and 200 DM hp? A third pylon activated after killing the DM300, and after killing it rentering the floor the water is still electrifies even though there is no particle effect.

![Screenshot_20240512-201054](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/f902c393-e586-473a-bdc0-5b8c463c8700)

**Comment by chorby-short** [comment]
Additional player/world information.
![Screenshot_20240512-202102](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/be30e384-e0a4-4c55-8258-d6c66552a599)
![Screenshot_20240512-202105](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/0ced4336-0298-46a1-9250-fe3772b1db9e)
![Screenshot_20240512-202107](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/e4b84342-16cd-4dfa-bef4-a9baf7eb0788)
![Screenshot_20240512-202110](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/7a939fba-74f2-455d-8726-4334fbb947fe)
![Screenshot_20240512-202119](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/4c393a68-6099-4307-9556-ceab596d7f9e)

**Comment by LordVipul** [comment]
Not only that, but the traps and water also shock you even if you defeat the pylon.

Also, if you go down and come back up, the lightning animation doesn't show but stepping in water or on the trap still shock you.

![Screenshot_2024-05-13-11-04-39-400_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8437613/f25234c9-bd65-4345-84dc-3e930f891018)

Seed:
![Screenshot_2024-05-13-15-26-51-792_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8437613/96c408b4-f88a-4837-93ec-62c55a7ae963)

**Comment by tigamai** [comment]
Reproduced on all 2 attempts on RC1.

**Comment by 00-Evan** [comment]
Fixed in 2.4.0-RC-2
