### ISSUE TITLE
(v2.4.0-RC-2) Turns until hourglass charge use: -0

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1707]
Just a small quirk I found.  When under a speed-boosting effect and the timekeeper's hourglass drops to 0 turns until charge use, it displays as -0 (negative zero) turns instead.
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/157346301/332a1a4a-418f-4486-97ab-05c0a8505d8d" width="200">
Confirmed this in both v2.4.0-RC-2 and v2.4.0-RC-1 using Nature's Power & Growing Power +4 for boosting speed
Probably worth checking for this with swiftthistle too, I didn't have any to test

**Comment by 00-Evan** [comment]
This is due to floating point rounding errors, the true value of time left is something like -0.000001, which the game treats as 0 to avoid rounding errors removing one extra time freeze action. The game isn't doing that for the buff display though, so it shows -0 instead of 0.
