### ISSUE TITLE
alchemy book and number of liquid metal received

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1708]
Alchemy book recipes look like you get one liquid metal regardless of how many thrown weapons you convert.  But I assume that converting more thrown weapons gives you more liquid metal.
![Screenshot_20240515-182010](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/a5a4cea9-6725-41d5-a034-169e45c3de84)

**Comment by 00-Evan** [comment]
Unfortunately the quantity of liquid metal varies by the thrown weapons used. It's not possible to just stick a quantity there and have it be remotely accurate, so the game just uses one.
