### ISSUE TITLE
Crystal mimics are still too easy to detect, even with the tooth

### ISSUE THREAD

**Issue by voronaam** [00-Evan/shattered-pixel-dungeon#1709]
Having a Mimic Tooth is supposed to make most of the non-combat interactions with mimic chests to be the same as with real chest to make it harder for the player to spot.

Crystal ones have one simple difference though. When a player walks into a room with crystal chests and then walks out of it and then uses the Search button on the chests:

 - the real Crystal Chest shows information about what's inside (a ring, a want, an artifact)
 - The mimic shows information about the pedestal it is standing on

Unrelated, I think there is a noticeable difference in the shade around the regular brown chest and the mimic at rest. Comparing core/src/main/assets/sprites/items.png and core/src/main/assets/sprites/mimic.png it seems the real chest have darker shade around them. Which is still the case with the tooth, as the same "at rest" sprite is used.

**Comment by voronaam** [comment]
2 mimics and one real chest in this room:

![photo_2024-05-16_09-47-51](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2351069/8456fcbf-f221-44ad-a494-d547725fe8dc)

**Comment by 00-Evan** [comment]
The mimic tooth trinket isn't intended to make mimics impossible to notice, if you're paying attention they should still be detectable. That border darkness in particular is intended, it's the only remaining visual difference with the tooth trinket.

Having examining reveal them in particular is intended as well (if you just examine them directly they have a health bar), as at that point you're clearly aware of the possibility of it being a mimic.

I don't want to create a situation where the only reliable way to detect mimics is to used a ranged attack against every chest.
