### ISSUE TITLE
Challenges on the ranking list

### ISSUE THREAD

**Issue by verdulo** [00-Evan/shattered-pixel-dungeon#171]
If you activate any challenge, then on the ranking list all games have visible text 'Challenges' with marked challenges instead of only the games, which I played with challenges.

**Comment by 00-Evan** [comment]
I removed some code from rankings regarding challenges a while ago when I improved how they were stored. Looks like I forgot this case, will fix.

**Comment by 00-Evan** [comment]
fixed in commit 1227c818759aa8790ff7fe14bfe2579c5a4c87a6
