### ISSUE TITLE
Ascension slow effect does not trigger when that stage is reached

### ISSUE THREAD

**Issue by jameshw-dev01** [00-Evan/shattered-pixel-dungeon#1710]
Found a minor bug
During ascension, I got the message that the amulet was slowing me down (was using +7 ring of haste) but it actually didn't.

**Comment by 00-Evan** [comment]
Thanks for the report, I'll look into this.

Unfortunately I've had to edit your message, I don't accept code contributions/suggestions due to copyright concerns.

**Comment by 00-Evan** [comment]
fixed in commit 38d43220720dcbbbedbfdb62c74380a015dcc35b
