### ISSUE TITLE
2.4.0 android: can't cancel creating trinket

### ISSUE THREAD

**Issue by DPlFnAz5J91kerf** [00-Evan/shattered-pixel-dungeon#1711]
[![](https://i.imgur.com/86KdV6qm.jpg)](https://i.imgur.com/86KdV6q.png)

**Comment by 00-Evan** [comment]
That is intended, you've spent the energy and started the crafting process, so you're expected to pick a trinket. If you hate all of the effects you can always just drop the trinket and continue the run without one.

**Comment by 00-Evan** [comment]
> Is it possible to spend energy only after a final decision?

From a technical standpoint, yes, but I want the player to commit to getting a trinket once they're started the recipe.
