### ISSUE TITLE
Has this sentence ever appeared in the game?

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1712]
![{@3SB5C%0BCRPWLE6Q33{K3](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/8c2ff551-c5b6-406f-b95a-cb959f8cbca2)
It seems to be related to SmokeBomb, but I cant find it in the game.

**Comment by bluestmango** [comment]
I believe that shows when you examine the smoke from one of Tengu's countdown bombs. Don't have any runs close enough to check for sure right now

**Comment by 00-Evan** [comment]
That's correct, this text appears when examining the smoke coming from Tengu's timed smoke bombs.

**Comment by Lyx0527** [comment]
@00-Evan
![Screenshot_2024_0520_232143_com shatteredpixel shatteredpixeldungeon statistical](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/88f22519-cd0b-4833-8665-c5d7687dd93c)

**Comment by 00-Evan** [comment]
Ah, there were internal code changes here a while ago that removed the smoke as a blob entity, and made it purely visual. As of then the description is unused. In the future, please report text issues or ask test questions on transifex btw, this place is more for the game's code.
