### ISSUE TITLE
Visual glitch involving picking up items when the inventory is full

### ISSUE THREAD

**Issue by mvonweis** [00-Evan/shattered-pixel-dungeon#1713]
This is a funny little glitch that I found in 2.4.0 on the iPhone. Not tried on other platforms.

How to reproduce:
- Fill up the inventory, then step on an item.
- Push the little button (above the backpack icon) to pick it up. Because the item doesn’t fit in the backpack, it does a small bounce on the screen.
- Quickly hit the button again, before the item hits the floor. Keep hitting the button.
- With each tap, the item floats higher and higher on the screen. Eventually it disappears off the top.

**Comment by 00-Evan** [comment]
This is intended actually, see: #40.

Other duplicates of this are: #1654, #1540, #1468, #1436, #1355, #1150, #1073, #689, #640, #203.
