### ISSUE TITLE
v2.4.1 "Avoidable" attacks are often unavoidable

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1716]
When facing certain enemies with avoidable attacks (telegraphed by red boxes), it's not uncommon that the safe space will land in a wall (presumably) or a similarly unwalkable square, rendering the attack unavoidable

<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/157346301/5ca451e4-68a5-4d11-8286-0dfacd8b65b9" width="150">
<img src="https://github.com/00-Evan/shattered-pixel-dungeon/assets/157346301/0f0b2ab7-9fec-4f44-9283-a77bf732774b" width="150">

The situations in those screenshots actually were avoidable with freerunning, but this also happens with other classes/subclasses

I've noticed it most commonly with DM-300, though the big crystal, gnoll sappers, and maybe even the geomancer (amazing quest btw, best one in the game) have done it too

**Comment by 00-Evan** [comment]
That is intended I'm afraid, you're limiting your movement options by standing next to walls. There's only a guaranteed safe adjacent tile if you're standing in open space.

**Comment by 00-Evan** [comment]
@

**Comment by bluestmango** [comment]
Makes sense. Really, it's the score deduction that bugs me. I hate that the player gets penalized for doing what they were forced to do (running through narrow tunnels to the pylons).
