### ISSUE TITLE
can't swap with recently corrupted ally

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1717]
This may be similar to the "can't pick up gold" issue.
I just corrupted this golem, but can't swap or warp with them.
Clicking on the golem's square does nothing.
![Screenshot_20240524-141913](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/069f32b7-bff4-4ac5-9a35-41532ad04e7f)
![Screenshot_20240524-141926](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/b48c11f0-b2b8-48b0-bf73-75aae2996b50)
![Screenshot_20240524-142125](https://github.com/00-Evan/shattered-pixel-dungeon/assets/8593007/1eb2ebba-8445-4903-8648-f90cdba4bcab)

**Comment by protective1** [comment]
And the same thing happened to resolve it - I clicked the square to the left, and next turn I was able to switch with the golem.

**Comment by 00-Evan** [comment]
That's intended, Golems are large characters and can't move into enclosed spaces like doorways.
