### ISSUE TITLE
Redundant door leading to the same area

### ISSUE THREAD

**Issue by fuggla** [00-Evan/shattered-pixel-dungeon#1718]
The door within line of sight to the left, see [screenshot](https://github.com/00-Evan/shattered-pixel-dungeon/assets/5972188/6de33597-9e59-4532-ac1c-a55704801e00).

- [Seed](https://github.com/00-Evan/shattered-pixel-dungeon/assets/5972188/450d8b7c-aa82-4262-800a-306a5f0d0585): KPJ-VBY-JFH
- Version: 2.4.0
- Platform: Android 14
- Source: F-Droid

Thanks for all your work on Shattered, I've played it a lot over the years.

**Comment by 00-Evan** [comment]
Thanks for the report, but this is intended. Levels can sometimes 'merge' adjacent rooms, which can lead to little pointless doorways like this. More specifically, there are three rooms around that little wall and door segment. The left and bottom room are merged, and the right and bottom room are merged, making a U shape, but the left and right room aren't merged to each other, leaving this little bit of wall behind.
