### ISSUE TITLE
Items get auto picked up when under the effects of a chilling trap, causing the hero to freeze

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1719]
I stepped on a hidden chilling trap and then attempted to take two steps out of range to avoid freezing, but I stepped on an item and the game auto-picked it up, causing me to freeze. I assume this would be a situation where the auto-pickup should not happen.
![Screenshot_20240524-161904](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118607635/c8f3bdc2-a23c-4114-a001-143dbc613c47)

**Comment by 00-Evan** [comment]
I'm afraid this isn't intended. It's generally better, I find, for the game to not make complex assumptions about what the player wants to do, but rather have pretty simple logic when it comes to things like pathing and actions. So in this case the simple rule is "if enemies are present, auto-pickup is disabled."

I understand that's frustrating in this situation, but I'd rather not have a bit list of different specific 'player is in danger' cases where auto-picked turns off.
