### ISSUE TITLE
Rapidly touching an item on the ground causes it to fly into the air

### ISSUE THREAD

**Issue by SamSkulls** [00-Evan/shattered-pixel-dungeon#172]
Android 0.5.0b, kernel version 4.4.2

Normally, if you touch an item to pick it up, and your inventory is full, it does that little "hop" animation. I just noticed that if there's more than one item on the ground on that tile, then touching the item seems to add velocity to whatever motion vector the item has for its animation, but doesn't reset its position as it would if there were only one item on that tile.

**Comment by 00-Evan** [comment]
This is intended, its been in the game for years and it's too fun to fix:

https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/sprites/ItemSprite.java#L150
