### ISSUE TITLE
Feature request: dead zones around buttons on mobile

### ISSUE THREAD

**Issue by philomory** [00-Evan/shattered-pixel-dungeon#1720]
Currently, when I play on my phone, if I go to tap the inventory button or the "attack nearby enemy" button (or other buttons, but, usually one of those two), if my finger misses by a smidge, it ends up registering as a tap on the map behind the button, which, depending on floor layout and current zoom level, can result in the character running halfway across the map in a single input. This can be a real problem if it happens at an inopportune time (most times are inopportune times).

My gut reaction was to suggest a confirmation prompt before accepting input that would move you more than, like, 20 tiles if you're currently engaged with an enemy (like the one you get if you tap on a chasm), but, on consideration I think that would probably get in the way as often as it helped, and it wouldn't even solve the problem in all cases. A better solution would probably be a dead zone around the buttons such that inputs which just barely miss the buttons don't get passed through to the map.

**Comment by 00-Evan** [comment]
This actually already exists for most UI elements, the buttons are generally 1px (that's a pixel in the game's graphics, so usually 10 actual pixels on a modern phone) larger than they appear to be on each side. There often isn't room to increase these deadzones without making button overlap with each other.

**Comment by philomory** [comment]
I'm not sure whether this would be feasible to implement, but I would suggest that the ideal (in lieu of implementation difficulties) would be to have a larger dead zone, but one that cannot actually interfere with the buttons. Conceptually, the idea would be to have three input-handling "layers"; the first layer is the layer on which the buttons exist; the input coordinates are checked to see if they intersect any button, and if so, that button is triggered. If not, the touch event is passed to the next layer, which is the dead zone layer. This layer is formed by taking the bounding boxes from all buttons in the previous layer, expanding them by N pixels, and unioning them. If the input coordinates intersect with this invisible object, then the event is consumed without effect, otherwise it is passed to the next layer down (which is the map).

In Apple's terminology this is the "responder chain". Obviously SPD isn't built on UIKit, and I don't know how feasible it would be to implement the same pattern here.

Realistically, I'm not expecting this gets implemented, I just wanted to explain for the sake of clarity what I had in mind, and how button dead zones can be handled (conceptually) without overlap becoming an issue.

**Comment by 00-Evan** [comment]
While I appreciate the suggestion (and this could by done in Shattered with some effort, albeit not in the way you describe), I suspect doing this would just lead to a bunch of messages from players asking why tapping on a certain location doesn't do anything.
