### ISSUE TITLE
UI bug with Deathless Fury

### ISSUE THREAD

**Issue by philomory** [00-Evan/shattered-pixel-dungeon#1721]
If you trigger Dealthless Fury, and then, while in cooldown, spend a talent point to increase your rank in Deathless Fury, the cooldown UI gets a little... confused.

![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/200123/c6279fa3-a54d-42fd-ae6c-95c4a7bb5016)

Separately, it's not entirely clear what the correct behavior should actually be, in this scenario (I can think of at least 4 options), but, whatever it is, the cooldown UI probably shouldn't look like that.

**Comment by 00-Evan** [comment]
fixed in commit 7d225041b31e1ab3973b1cdb7f3d61c22f90690d
