### ISSUE TITLE
Flurry of Blows doesn't increment combo

### ISSUE THREAD

**Issue by jessdwitch** [00-Evan/shattered-pixel-dungeon#1722]
If a monk has a sai equipped she builds combo on-hit with "melee or thrown weapons", but Flurry of Blows does not increment the counter at all. I don't know if this also applies to other combo weapons.

**Comment by 00-Evan** [comment]
Thanks for the report. I am aware of this, currently flurry of blows doesn't trigger a few on-hit effects that it probably should. Even if the decision here is that it shouldn't (i.e. fists aren't weapons), it should at least be that way intentionally.

**Comment by 00-Evan** [comment]
I've decided to adjust the wording on combo strike such that it only triggers from regular attacks, flurry of blows is an ability attack, and therefore won't affect combo.

**Comment by 00-Evan** [comment]
fixed in commit 53fab368e6fa2b057c8473b4d6bf601074da09ab
