### ISSUE TITLE
Alchemy UI doesn't let you clear too few liquid metal to create Telekenesis.

### ISSUE THREAD

**Issue by Glazed** [00-Evan/shattered-pixel-dungeon#1724]
I added 15 liquid metal to the pot, produced Telekinesis which used 10, leaving 5 in the pot. The new "x" button is grayed out. It's a very minor issue, but I figure you'd want to know.

![Screenshot_20240531-151431](https://github.com/00-Evan/shattered-pixel-dungeon/assets/1869438/78c78c69-8ed5-4fb8-9156-106ee6aeec54)

**Comment by 00-Evan** [comment]
Fixed in commit 5bef46bc90040ef4b3787e89056eb7b8d8e18a99
