### ISSUE TITLE
Gateway trap teleports sheep with hero when sheep summoned on the Gateway trap

### ISSUE THREAD

**Issue by Shamzik** [00-Evan/shattered-pixel-dungeon#1728]
Is it a bug? I think only the sheep should have teleported.

![Screenshot_2024-06-05-10-53-26-879_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/43345462/2bd8a0bc-c3cd-4f22-aa3c-6c50d3c96659)
![Screenshot_2024-06-05-11-23-36-980_com shatteredpixel shatteredpixeldungeon](https://github.com/00-Evan/shattered-pixel-dungeon/assets/43345462/7427d030-1382-44b3-9c3e-835be6fa486c)

**Comment by 00-Evan** [comment]
Were you standing next to the gateway trap here? It teleports all characters in a 3x3 grid around it.
