### ISSUE TITLE
Visual grid only partially visible for Tengu fight

### ISSUE THREAD

**Issue by jkadin** [00-Evan/shattered-pixel-dungeon#173]
It looks like the visual grid isn't drawing correctly after getting through the maze on the Tengu boss fight. Might already be fixed in 0.6 with the new level gen code though?

**Comment by 00-Evan** [comment]
Thanks for reporting this, will be fixed in 0.6.0

**Comment by 00-Evan** [comment]
fixed in commit 3c48ea8c3a6efaff1b686d7e0477f4ea0ff7c9d3
