### ISSUE TITLE
A suggestion(About online mode)

### ISSUE THREAD

**Issue by Zymjason** [00-Evan/shattered-pixel-dungeon#1730]
I like the game very much, but have a small suggestion about the gameplay. I think why not add **a multiplayer online mode** to the game (e.g. using a LAN to enable interaction). Because when I introduce this game to my friends, we can only play each separately and experience no cooperation. If this mode is developed, one difficult problem to solve is the timeliness of actions, which I think will affect the whole game experience and is an important problem to solve (I hope to see this feature in version 2.5). You guys are already doing a great job, I love this game, and if this feature could be developed, then I think it would be the icing on the cake! Thanks for reading!

**Comment by 00-Evan** [comment]
Unfortunately multiplayer isn't really feasible to add. Aside from all of the networking code I would need to add, the game itself is entirely designed around one player. Most of the game's systems would break or need serious changes to work in multiplayer, and even then gameplay would be very awkward as you describe. Player would spend most of their time waiting for other players to take their turns.
