### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by CORRUPTEDUSER404** [00-Evan/shattered-pixel-dungeon#1731]
Dropped items can be made to float out of screen by repeatedly repeatedly attempting to pick them up and rapid succession when inventory is full. (Bounce animation not resetting properly and restarting from current location)

I haven't sure this is due to my device or if it's due to the game itself as I'm not able to isolate them

Note: if the animation is allowed to completely end it will snap back to it's proper position.

example of note
![20240606_165414](https://github.com/00-Evan/shattered-pixel-dungeon/assets/108518174/7dc00ae3-a753-43ac-96ba-b172b54c9fcc)

Edit: dictation error

**Comment by 00-Evan** [comment]
This is intended actually, sort of. See: https://github.com/00-Evan/shattered-pixel-dungeon/issues/40.

Other duplicates of this are: #1713, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1654, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1540, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1468, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1436, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1355, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1150, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1073, https://github.com/00-Evan/shattered-pixel-dungeon/issues/689, https://github.com/00-Evan/shattered-pixel-dungeon/issues/640, https://github.com/00-Evan/shattered-pixel-dungeon/issues/203.
