### ISSUE TITLE
bug of the ring of roots

### ISSUE THREAD

**Issue by baserker2** [00-Evan/shattered-pixel-dungeon#1732]
When I challenged the boss Tengu, the effect of the Ring of Roots and Bones disappeared

**Comment by 00-Evan** [comment]
Sorry but I don't know what you mean. There is no ring of roots in Shattered Pixel Dungeon.

**Comment by rtgggggg** [comment]
do you mean ring of might?

**Comment by ChuiyuWang1** [comment]
Should be Ring of Might.

**Comment by 00-Evan** [comment]
Closing this as there was no reply, feel free to comment again and I'll re-open.
