### ISSUE TITLE
Stopped gaining experience after potion of divine inspiration

### ISSUE THREAD

**Issue by jessdwitch** [00-Evan/shattered-pixel-dungeon#1734]
I drank a potion of divine inspiration, got the 2 points, and now it seems my experience is locked at 6. A potion of experience did successfully level me up, but I was still locked at 6.

![Screenshot_20240609-094051](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2289086/ff1a5216-9f92-4d94-8009-8d3ecc9eb033)
![Screenshot_20240609-094120](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2289086/5eae0d4b-ae3e-4e16-985f-34adb5da589c)
![Screenshot_20240609-094239](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2289086/a71a62aa-957e-4119-be43-a91fba68e00c)
![Screenshot_20240609-094926](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2289086/7d5c1180-acd5-488f-a2dd-8d1466c46c89)

Killing Yog seems to have broken the "curse":
![Screenshot_20240609-100138](https://github.com/00-Evan/shattered-pixel-dungeon/assets/2289086/74ee24ca-f26e-46d9-8604-9881a831492f)

**Comment by 00-Evan** [comment]
This is working correctly I'm afraid, and has nothing to do with the potion. Enemies in the demon halls cap out at awarding exp at level 28, so it's not possible for you to level furhter from fighting those enemies. Ascending would let you continue gaining exp to to level 30.
