### ISSUE TITLE
Request: option to make the quickslot swapper localized to each save file.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1735]
When playing in portrait on mobile, I only want there to be a toggle slot when I currently have 6 items to quickslot. Going between save files, I find myself somewhat irritated that the quickslot preferences apply to all of them, as I'd rather toggle the swapper on in individual runs when needed, which isn't always the case. The default can be based on the start of the game, a là waterskin.

**Comment by 00-Evan** [comment]
Honestly I am dissatisfied with the swapper in general. I'd rather not complicate it further by having it be the only setting that is per-save, but I do agree that it's currently functionality, that essentially offers a trade-off, is not ideal.

**Comment by chorby-short** [comment]
I suppose I was more asking for it to be an option.

**Comment by 00-Evan** [comment]
There is already an option to turn the swapper on and off, it's under toolbar settings into the menu.

**Comment by chorby-short** [comment]
That's not what I'm saying. I'm saying and additional toggle on whether to preserve that setting between save files.
