### ISSUE TITLE
Game caught exception using staff with Wondrous Resin on DM-300

### ISSUE THREAD

**Issue by Vovkiv** [00-Evan/shattered-pixel-dungeon#1736]
When I casted stuff on DM-300, Woundrous Resin +3 zapped into DM-300 and caused this.

![Screenshot_20240614-230650.png](https://github.com/00-Evan/shattered-pixel-dungeon/assets/54743395/838803eb-f4d2-4cdd-9f09-4dafdea03509)

Game version 2.4.2, seed TJL-QGL-CQJ

**Comment by 00-Evan** [comment]
Thanks for the report, this is intentional actually! It's a reference to an old, legendarily unhelp error from MS-DOS: https://en.wikipedia.org/wiki/Abort,_Retry,_Fail%3F

The game only appears to crash, it actually just saves and closes.

**Comment by Vovkiv** [comment]
Lol
Maybe there could be some badge/achievement that could hint about this, because I seriously thought I got error
