### ISSUE TITLE
wards and sentries are removed after getting amulet

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1739]
Are wards and sentries meant to be erased on every level before the return run?
I played a wand of warding battle mage.  Before fighting the final boss, I ran up to the beginning of the dungeon and created multiple sentries on every level before getting the amulet.  I expected an easy return run for the exit.  Sadly, for the return run, all of my sentries has been deleted.
(I still won, but it was not quite as easy as I hoped.)

**Comment by 00-Evan** [comment]
That is intended, specifically to prevent that kind of strategy. Each floor is reset as you ascend to it to ensure that existing enemies don't result in a difficulty spike, or vice-versa for existing allies.
