### ISSUE TITLE
[admittedly the least significant bug ever] Hero may land on pitfall trap then stands on chasm

### ISSUE THREAD

**Issue by mheder** [00-Evan/shattered-pixel-dungeon#174]
If you fall (through pitfall trap) and land on another pitfall trap you get "!!! text not found !!!" and will stand right on top of chasm. 

![SPD-bug](https://cloud.githubusercontent.com/assets/6235860/25042078/7731004c-2115-11e7-846b-d8cdb3eb31f5.png)

**Comment by 00-Evan** [comment]
In 0.6.0 it will be impossible to land on enemies, items, or traps after falling, this should fix this incidentally.

**Comment by 00-Evan** [comment]
fixed in commit 7ab1e18c91509ae39fe56bb694eb1569392a2d12
