### ISSUE TITLE
Corrupted enemies + noisemaker bomb

### ISSUE THREAD

**Issue by jellicle1** [00-Evan/shattered-pixel-dungeon#1742]
Put a noisemaker bomb in a room and guarded the door with my weapon with corrupting enchantment. Corrupted an enemy in the doorway and it ran past me into the room to seek out and kill itself on the noisemaker bomb.

Expected behavior: Corrupted enemies should not seek out or attack the noisemaker; noisemaker should not trigger on character, corrupted enemies, ghost, etc.

**Comment by 00-Evan** [comment]
I'm afraid that is intended. Less intelligent ally characters will still do things like be beckoned toward noises, they are essentially still regular denizens of the dungeon, just with flipped allegiances. Noisemakers also explode when anything gets near to them.

Intelligent allies, such as the sad ghost, are not attracted by these things.
