### ISSUE TITLE
Piranha enemy behavior when corrupted 

### ISSUE THREAD

**Issue by denis-kralj** [00-Evan/shattered-pixel-dungeon#1743]
## Issue details
When the piranha enemy gets into a corrupted state (e.g. with wand of corruption), it then proceeds to try and exit the pool where it is located. Upon touching the ground, it dies because it cannot survive outside of water.

## Expected behavior
I would imagine that the Piranha wouldn't stop swimming, probably trying to attack other Piranha enemies in the same pool or other enemies within the area and connected to the body of water. Otherwise I would expect it to just idle in the body of water.

**Comment by 00-Evan** [comment]
I'm afraid I'm not able to reproduce this. Corrupted piranhas simply switch which characters are valid targets (like other corrupted mobs), there isn't any change to their pathfinding behaviour.

Was the piranha also affected by a debuff like amok or vertigo? Those debuffs can override pathfind decision making and could cause the piranha to move onto land and die.

**Comment by denis-kralj** [comment]
Good question, I didn't look at the debuff list so I cannot answer that question. I'll keep an eye out, maybe it will happen again. Cheers!
