### ISSUE TITLE
Lit bombs never go off if revived in a boss fight

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1744]
![Screenshot_20240630-103837](https://github.com/00-Evan/shattered-pixel-dungeon/assets/101913866/4f294479-d88c-4cbf-b891-cc334cc73c62)

The fuse still shows as lit, but it just doesn't explode

**Comment by 00-Evan** [comment]
This behavior is intended, but the fuse should not visually persist, I'll get that fixed.

**Comment by 00-Evan** [comment]
fixed in commit 651cc8631a7f9ae9156dc6dd16828f69765561df
