### ISSUE TITLE
Cursed wand can cause plant to appear in the same space as a closed door 

### ISSUE THREAD

**Issue by jokrefta** [00-Evan/shattered-pixel-dungeon#1745]
Saw this after shooting a cursed wand at a closed door. 
![Screenshot_20240630_233249](https://github.com/00-Evan/shattered-pixel-dungeon/assets/48812097/021ca7cc-f7d0-4ea5-bff8-4c0aa8810403)

**Comment by 00-Evan** [comment]
After a little testing I've decided to leave this as-is, the behavior is consistent with throwing seeds to create plants.
