### ISSUE TITLE
Can't use custom seeds on Android

### ISSUE THREAD

**Issue by XMaskedPro** [00-Evan/shattered-pixel-dungeon#1747]
I don't know if it's because I haven't beaten the game or if it's a bug, maybe it's not on android. Just let me know please

**Comment by 00-Evan** [comment]
That is intended, you need to have a win before unlocking custom seeds.

**Comment by XMaskedPro** [comment]
I just wanted to make sure because I couldn't find it anywhere on the changelogs

**Comment by XMaskedPro** [comment]
Sorry for the annoyance

**Comment by 00-Evan** [comment]
No worries!
