### ISSUE TITLE
I just got a cursed wand error, and it told me to exit, retry or abort... what?

### ISSUE THREAD

**Issue by XMaskedPro** [00-Evan/shattered-pixel-dungeon#1748]
I just don't know what happened its so confusing

**Comment by TheYsconator** [comment]
That is one of the random effects of a cursed wand. It is a joke: https://github.com/00-Evan/shattered-pixel-dungeon/blob/d7d2809776147d4a1f09095c830d971d8ac7cf8b/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/wands/CursedWand.java#L436

**Comment by XMaskedPro** [comment]
I half expected it was a joke half was like "did I get hacked..."
