### ISSUE TITLE
0.6.0b-5 Level Generator : Chasm secret room on depth 2 with no chasm room on depth 1

### ISSUE THREAD

**Issue by pierredadt** [00-Evan/shattered-pixel-dungeon#175]
It seems the new layout generator can forget a chasm room as of version 0.6.0b.
I didn't take the time to restart enough times to reproduce it, but after searching for the whole 1st depth three times I came to this conclusion.

**Screenshots :** 
![depth1](https://cloud.githubusercontent.com/assets/27410810/25850168/7fedd9ac-34c1-11e7-9151-d6419482a6a6.png)
![depth2](https://cloud.githubusercontent.com/assets/27410810/25850171/823227f4-34c1-11e7-85a3-07d7a6683654.png)

**Seed:** ZBVAJVOGB

**Comment by 00-Evan** [comment]
Beta issues do not have an associated source release, and this is therefore not the appropriate place to report them. I have closed this issue, however I do have a fix for this planned for beta-6.
