### ISSUE TITLE
Add the option to (customize) limit max zoom out.

### ISSUE THREAD

**Issue by bps86** [00-Evan/shattered-pixel-dungeon#1750]
Currently on mobile, there's an issue where on mobile, having miss click is happen much often and it's not a pretty good experience. There are multiple feedback to prevent this such as confirm move and other feedback, which might mess up the difficulty of the game. I have a suggestion to fix this problem, by adding customizable max zoom out feature.

The reason to add this feature is to prevent over-zoom out, because some people like me doesn't want to zoom out until the tile hitbox is smaller than the thumb. It's a feature to make miss click less likely to happen, at cost of environment scouting which makes it more harder and require more focus(player must look around because of smaller fov). I hope this feature can be implemented if possible. Thank you

**Comment by 00-Evan** [comment]
I'm not sure how adding a maximum zoom out setting would be beneficial here. If the game is too zoomed out, you can simply zoom the view back in using a pinching gesture (or scroll wheel or controller buttons, depending on your input method). the game remembers this so you wouldn't need to change the zoom setting again unless you wanted to.

**Comment by bps86** [comment]
I see, understood. For benefit, it's mostly beneficial for people who tend to forgot the correct size of tile hitbox with the thumb, and unconsciously just pressed the tile without zooming in back after zooming out too far, resulting in miss click(although I must say that is the fault from the user here). It's like an fov setting from fps games to me. A debug/interface saying on how much zoom user currently using would also be helpful(normal's 1x, max's 1.5x, etc), but I won't ask too much for that. Thanks for the respond tho, appreciate it.

**Comment by 00-Evan** [comment]
One thing that's interesting is that your thumb actually has the same hitbox as a finger, the touchscreen reports either as a single point in screen space, it's just about which point the touchscreen interprets the touch to be at. So it is possible to tap exactly on a tile even if it's small, but of course doing that gets increasingly difficult.

**Comment by bps86** [comment]
Hmm, understood. Yeah, it was difficult on small tile, I agree. I'll try to be careful next time,
