### ISSUE TITLE
Suggestion: Add effect icons to known scrolls and potions in shops or on the floor.

### ISSUE THREAD

**Issue by Glazed** [00-Evan/shattered-pixel-dungeon#1751]
While you're adding quality of life and UI changes, have you considered adding known scroll and potions icons on those items when they're on the floor? You know, the same icons that you see in your backpack.

It gets really tedious examining scrolls over and over in shops. I never remember the scroll runes or potion colors because they change each run. It would go a long way to making shopping faster and easier.

And when you throw a consumable at a well of knowledge, you'd immediately see what it was without having to open the backpack. And you would see known consumables in hazard rooms without having to examine them. Stuff like that.

**Comment by 00-Evan** [comment]
I understand how this would improve clarity, but it would look very odd for interface elements to be added to item sprites that are appearing in the game world, and not in interfaces.

**Comment by Glazed** [comment]
I have an idea to use my idea but preserve the look of in-game items most of the time: only show the labels when you've tapped the examine button and the game is waiting for you to tap something. You're about to tap the ground item(s) anyway to bring up a window to show what each is one at a time, so instead, identify all known items with little icons at that time.

It's a clever compromise, don't you think?

**Comment by 00-Evan** [comment]
I agree that your suggestion is better as a compromise, but it still results in UI elements appearing in the game world. Is this primarily an issue in shops? I do plan to eventually move shops to be based on an interface, which would also solve this problem.

**Comment by Glazed** [comment]
Yes, it's primarily shops. A UI for shops is an interesting idea.
