### ISSUE TITLE
choose examine

### ISSUE THREAD

**Issue by rtgggggg** [00-Evan/shattered-pixel-dungeon#1752]
I found it difficult for touchscreen players to navigate to certain squares because when they click on these squares, they usually open them instead of moving to them, which may result in wasting one turn in some cases

![Screenshot_2024-07-10-20-59-31-03.jpg](https://github.com/00-Evan/shattered-pixel-dungeon/assets/137588737/48f851d3-5b20-4840-bd1b-439da2cdc0b1)
![Screenshot_2024-07-10-20-59-53-80.jpg](https://github.com/00-Evan/shattered-pixel-dungeon/assets/137588737/5a6b0eb2-3116-4523-9ce3-6da654fe355e)

I think it would be more convenient to add the "Move to:" option in the "choose examine" interface.

**Comment by 00-Evan** [comment]
It would be very odd for a gameplay action to be tied to the examine button.

I'm fine with the game mostly making players interact with these items when they're selected.

**Comment by rtgggggg** [comment]
How about long pressing to move and clicking to open

**Comment by rtgggggg** [comment]
> It would be very odd for a gameplay action to be tied to the examine button.
> 
> I'm fine with the game mostly making players interact with these items when they're selected.

How about long pressing to move and clicking to open

**Comment by 00-Evan** [comment]
Unfortunately long pressing isn't a possible action in the game world. The player may already hold a press in order to pan the camera, and it would be very easy for someone to mean to do one input and accidentally do the other.
