### ISSUE TITLE
Weapon Drop Rate Information

### ISSUE THREAD

**Issue by bps86** [00-Evan/shattered-pixel-dungeon#1753]
I was looking for a way to find weapon drop rate chance such as Greatsword, but couldn't find one. I've been looking through changes, buff nerf but alas there was none. The only changes I see regarding to weapon drop rate are in 0.8.0(Although I might missed some, please correct me). I wish there was a way to find each weapon drop rates for better planning as I always saved my upgrades for some specific weapon.

**Comment by bps86** [comment]
I'll leave this as closed as I was informed that all Tier 5 weapon have the same drop.

**Comment by 00-Evan** [comment]
In general I don't think the game should share specific item droprates anyway. As you've discovered, all T5 weapons have the same base chance.
