### ISSUE TITLE
Missing crystal keys on v. 2.4.2

### ISSUE THREAD

**Issue by mortengan** [00-Evan/shattered-pixel-dungeon#1754]
*Disclaimer*
I am not sure if this is the right place, and hope that it is not me who is blind - if this should be directed somewhere else, do let me know.

*Issue*
This has happened a couple of times for me, where I have a crystal door on a level, but without a crystal key. Below is an example of a dungeon on level 3, where I have used a Scroll of Magic Mapping, showing that I have explored the whole level.  I have been unable to find any crystal key.

Game Version: 2.4.2
Dungeon Seed: TJN-CVQ-MZP

*Screenshot of map*
![Screenshot_2024_07_14_14_25_19_77_6f3fe77889fbecf862f7061166760abf](https://github.com/user-attachments/assets/d134d61b-9173-4da9-9c33-ef463d894e8b)

* Screenshot of seed*
![photo_2024-07-14_14-27-20](https://github.com/user-attachments/assets/902ec08e-17fa-418f-80bd-6117e696a589)

**Comment by 00-Evan** [comment]
This is a specific room type, where the key for the door is within the room itself. There is a way in of course, look for a hint on the previous floor.

**Comment by mortengan** [comment]
got it - as long as its not a bug. Thanks for the help :)
