### ISSUE TITLE
wand of regrowth with the challenge barren land

### ISSUE THREAD

**Issue by rtgggggg** [00-Evan/shattered-pixel-dungeon#1756]
Because this challenge will remove all plants, and the wand of regrowth can form plants, so that tile will not have tall grass

I think that since the challenge has removed plants, then the wand of regrowth should not be allowed to try to generate plants

Because my English is not very good, I used a translator. I'm sorry if it caused any difficulty in understanding

**Comment by 00-Evan** [comment]
That is intended. The game still attempts to place plants, and challenges generally do not replace a removed effect with a different one.
