### ISSUE TITLE
Duplicate well of health not showing in the landmarks

### ISSUE THREAD

**Issue by Ekter** [00-Evan/shattered-pixel-dungeon#1757]
Hi, I just found this, and I don't know if it's a bug or not, but if there are two wells of health on the same floor(with one from a hidden room for example), then only one of them is reported in the landmarks tab.

I will keep my run like this if you want me to test something, I didn't try to drink a well yet.

Here are screenshots with the seed if you want to reproduce:
![Screenshot_20240720-195404](https://github.com/user-attachments/assets/06716dcf-a975-44da-9b9f-967e4cea7bea)
![Screenshot_20240720-195415](https://github.com/user-attachments/assets/98b47d2e-fdf9-41a5-86cb-1c7fd27f82f8)
![Screenshot_20240720-195422](https://github.com/user-attachments/assets/d15d50e4-6ef1-4633-acb8-ca2511f52dd8)
![Screenshot_20240720-195431](https://github.com/user-attachments/assets/480dbd40-55ff-4f93-a8ad-ceab59009c12)

I hope it can help, I think it is a minor issue anyway.
I have already seen double gardens a lot of times, but I never thought about checking the landmarks for that

**Comment by 00-Evan** [comment]
This is intended, landmarks do not support duplicates of the same landmark on the same floor, and there's not much point in adding that functionality as you're told whether the floor contains the landmark either way.

The game does check if other wells of health exist before removing the landmark entry when one is cleared.

**Comment by Ekter** [comment]
Ok thanks!
