### ISSUE TITLE
Character sprite can be replaced by a black square

### ISSUE THREAD

**Issue by pierredadt** [00-Evan/shattered-pixel-dungeon#176]
I don't really know to reproduce it, or if it is voluntary reproducible at all.
I didn't expect such a thing to happen.

**Screenshots :**
![black_mage](https://cloud.githubusercontent.com/assets/27410810/25850711/927080c8-34c3-11e7-910b-fe692c9260e2.png)

**Comment by 00-Evan** [comment]
I don't have any reason to believe this issue is beta-specific, so I've edited this issue to remove beta references and left it. Will need more information before I can really take action though.

**Comment by 00-Evan** [comment]
I'm calling this one tentatively fixed in commit 41685ce45c16e875155099c205294db0dea44bac, feel free to comment if you experience this again and I'll reopen.
