### ISSUE TITLE
linux multi-monitor: doesn't remember monitor

### ISSUE THREAD

**Issue by draeath** [00-Evan/shattered-pixel-dungeon#1760]
I'm not sure how much of this is something you can control, but on X11-based multi-monitor setups the game launches on the primary display and does not remember it's geometry. This occurs even when running it in a window, instead of fullscreen.

Ideally it will remember the last location and size, and try to set itself back to that on subsequent launches. Irritatingly, the trick of using KDE's Window Rules overrides does not seem to work with this game, and I'm not sure why.

This means for each play session I must toggle out of fullscreen, drag the game window to the appropriate display, and fullscreen it again.

Game version: Steam, Linux native, v2.4.2
Distribution: openSUSE Tumbleweed x86_64
Environment: KDE Plasma 6.1, QT 6.7, xorg 21.1. 2x 1920x1200 displays.

    draeath@redacted:~/.steam/steam/steamapps/common/Shattered Pixel Dungeon> md5sum bin/Shattered\ Pixel\ Dungeon 
    96492b2131d8b595a45f96571d391195  bin/Shattered Pixel Dungeon

----

I am happy to compile and run tests, if necessary or helpful.

**Comment by 00-Evan** [comment]
Thanks for the suggestion, I'll admit that I haven't looking into multi-montior functionality much. I'll see if there is any reasonably feasible way to have a libGDX application remember its previous monitor and default to it.

**Comment by 00-Evan** [comment]
Good news, this actually can work! it's a little brittle though because it relies on the OS always reporting monitors in the same order, but that should be okay. At least monitor 0 is guaranteed to be the primary monitor, so this shouldn't affect the most common case of wanting fullscreen to be on primary monitor.

**Comment by draeath** [comment]
Nice, thanks!

**Comment by 00-Evan** [comment]
Implemented in commit 41422a9147775aea59846ab6be7e81583bf0efe8
