### ISSUE TITLE
Scroll of enchantment discarded without warning

### ISSUE THREAD

**Issue by soulstenance** [00-Evan/shattered-pixel-dungeon#1762]
**Bug summary**
When using a scroll of enchantment, canceling the enchantment will discard the scroll with no warning.

**Steps to reproduce**
1. Use scroll
2. Pick item to enchant
3. Press cancel

**Result**
Menu closes and scroll is lost.

**Expected behavior**
A message should pop up indicated that proceeding will discard the scroll OR scroll should not be discarded at all.

**Platform**
Android

**Game version**
2.4.2

**Comment by 00-Evan** [comment]
That is intended, the scroll is discarded as you're seen the enchantment options. The window mentions that pressing cancel will still consume the scroll.

**Comment by soulstenance** [comment]
> That is intended, the scroll is discarded as you're seen the enchantment options. The window mentions that pressing cancel will still consume the scroll.

I understand why it would be discarded. I did noticed after posting this that there is a small warning in the dialog about this. Given the high cost of these scrolls (Scrolls of upgrade are limited and you're forgoing an upgrade to make one of these), I still think a pop up warning is warranted as in other cases where you're doing something _presumably_ stupid.

Alternatively removing the cancel button altogether could be an idea. There's no benefit to using it as far as I can tell.

Also, semi-related - I've seen cases where a cancel button would be useful where one didn't exist at all, like when picking a trinket (one can cancel by force closing the game).

**Comment by 00-Evan** [comment]
> > That is intended, the scroll is discarded as you're seen the enchantment options. The window mentions that pressing cancel will still consume the scroll.
> 
> I understand why it would be discarded. I did noticed after posting this that there is a small warning in the dialog about this. Given the high cost of these scrolls (Scrolls of upgrade are limited and you're forgoing an upgrade to make one of these), I still think a pop up warning is warranted as in other cases where you're doing something _presumably_ stupid.
> 
> Alternatively removing the cancel button altogether could be an idea. There's no benefit to using it as far as I can tell.
> 
> Also, semi-related - I've seen cases where a cancel button would be useful where one didn't exist at all, like when picking a trinket (one can cancel by force closing the game).

In the case of trinkets being able to cancel via force-quit is actually a bug, the player is supposed to be forced to pick a trinket once they've started the process. As for the scroll, the cancel option is mainly there if all options are detrimental, such as if you have an existing enchant you'd rather keep.

**Comment by soulstenance** [comment]
> In the case of trinkets being able to cancel via force-quit is actually a bug, the player is supposed to be forced to pick a trinket once they've started the process. As for the scroll, the cancel option is mainly there if all options are detrimental, such as if you have an existing enchant you'd rather keep.

You are right, it's more of a useless bug. None of the offered trinkets were to my liking so I was trying to generate new options by force quitting. It didn't work though so I just discarded it. Regarding SoE, I guess the cancel option is useful if you already have a desirable enchantment, fair enough. Keep up the good work! :slightly_smiling_face:
