### ISSUE TITLE
Dying to a worn dart trap doesn't get written to the in-game log

### ISSUE THREAD

**Issue by JFomit** [00-Evan/shattered-pixel-dungeon#1766]
Based on the fact, that the cause of death is always logged, its absence in case of a dart trap seems like a bug.

<details> 
  <summary>Screenshot of the problem</summary>
  
![Screenshot 2024-08-15 223458](https://github.com/user-attachments/assets/70133046-5bc6-4e44-874f-bdc26945ad5a)

</details>

**Comment by 00-Evan** [comment]
Also applies to poison dart traps (the direct dart damage, not the poison)

**Comment by 00-Evan** [comment]
fixed in commit c9d10562c0e6b783718bb90d9b46207a91bc650c
