### ISSUE TITLE
curse wand

### ISSUE THREAD

**Issue by rtgggggg** [00-Evan/shattered-pixel-dungeon#1767]
I used the curse wand to turn a necromancer who had already summoned a skeleton into a sheep, but the skeleton it summoned did not die

![_-1142019692__148495826__8ae7318347d0dc04e4c3f83d7e7ee67b_298914544_Screenshot_2024-08-15-13-21-44-87_0_wifi_0_1723699395000.jpg](https://github.com/user-attachments/assets/2a10f869-8ca7-46ab-a3de-0ae86d827ef9)

I found it at statistical

**Comment by 00-Evan** [comment]
Please don't report issue encountered in other versions of Pixel Dungeon, I am only able to fix errors encountered in Shattered.

Even if this does occur in Shattered, it is intended though. Turning enemies into sheep completely removes them, and skips all regular on-kill logic.
