### ISSUE TITLE
tons of pickaxe

### ISSUE THREAD

**Issue by Highseekerz** [00-Evan/shattered-pixel-dungeon#177]
see this http://gall.dcinside.com/rlike/111658
i just go to main menu and talk to blacksmith again and i got one more pickaxe lol

**Comment by OffifialMITX** [comment]
... it doesn't look like "one more", rather like one million more.

**Comment by 00-Evan** [comment]
This was an issue in a previous beta  and is fixed in later betas for 0.6.0

Betas do not have an associated source release, so beta bug reports are not appropriate here, I've closed this.
