### ISSUE TITLE
Picking up unstackable above stackable

### ISSUE THREAD

**Issue by Surhan-code** [00-Evan/shattered-pixel-dungeon#1770]
When there's an item that you can't pick up above another item that you can pick up (a stackable that you already have in your inventory) and you spam the button the item starts flying.

**Comment by Surhan-code** [comment]
https://github.com/user-attachments/assets/337c05ef-4dd1-4ed9-8f3a-229ec4df62b9

**Comment by rtgggggg** [comment]
This is intended, you can see it at #1731
