### ISSUE TITLE
can't swing using button

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1771]
Clicking button won't swing at blob.
Clicking directly on blob, however, will swing at him.

How this happened: Killed a first blob (who dropped gold pile) in doorway to left  A second blob came, which I saw early thanks to eye of newt.  Walked into doorway as shown on screenshot.   Button to swing at second blob appeared on screen.  However, pressing it does nothing.  I have to click directly on the second blob in order to swing at it.

![Screenshot_20240819-141607](https://github.com/user-attachments/assets/d4c4e1eb-6708-488d-8d53-2c28287f4440)

**Comment by 00-Evan** [comment]
This has occurred sporadically over the last few years, with scattered reports and no way to reproduce the issue I'm afraid. I can re-test with these exact circumstances and I won't reproduce the problem.

I'm closing this as there's nothing to be done about it currently, but feel free to comment again if you encounter the issue again.

**Comment by protective1** [comment]
@00-Evan Is there anything I can do next time it happens to better help debug this?  I'm on Android.

**Comment by protective1** [comment]
![Screenshot_20240907-205357](https://github.com/user-attachments/assets/15124fb7-4d21-4995-89c1-41fce31a4025)
It happened again.  Guard chained me down towards him from doorway.  Clicking whip button doesn't attack.
![Screenshot_20240907-205618](https://github.com/user-attachments/assets/0cbe3a60-a0c5-4e5d-93f6-db8958ee86f4)

**Comment by protective1** [comment]
![Screenshot_20240907-205644](https://github.com/user-attachments/assets/f41642dd-7e4c-4a4d-b0d0-266c8ac7f020)
![Screenshot_20240907-205653](https://github.com/user-attachments/assets/4e6af826-6f50-4e84-8b53-98b490d71e8e)
![Screenshot_20240907-205658](https://github.com/user-attachments/assets/01873cba-0e14-4152-a024-0852b7fcab30)
![Screenshot_20240907-205704](https://github.com/user-attachments/assets/7bd2c678-b55d-4de4-9f41-5ea8ff6a78dc)

**Comment by 00-Evan** [comment]
I actually made a small tweak to the attack indicator in v2.5.0 (currently in beta). So this issue may possibly be resolved since then.

**Comment by protective1** [comment]
Hi Evan - it happened again.  But after I exited the game and came back in, then clicking on the rat button worked as normal.

<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/66a7ca4a-813a-4045-a968-94677adaa118" />
<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/5aa147e9-d175-4164-83f4-412b6dc14107" />
<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/88c07da0-511b-4a6f-977b-53b5ebdcf5f8" />
<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/5b6c953d-6c6a-44ad-941e-693b7c9d7982" />
<img width="1080" height="2220" alt="Image" src="https://github.com/user-attachments/assets/2da64c7f-e0b5-4578-afb8-fd7c047f8855" />
