### ISSUE TITLE
Animations skip when interupted.

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1772]
This is a minor issue, but whenever an animation ends while another event that is dependent on an animation ending to complete, it skips the second animation. Example, eating food and then immediately trying to open a chest. This makes the chest open instantly, because they use the same animation, and the item pops out when the animation is done.

**Comment by Howdidibreakit** [comment]
i'm an idiot i forgot this was already in the game lol

**Comment by 00-Evan** [comment]
Yeah this is a bug I've known about for a while, I'm fine with this sort of animation cancelling beign in the game as long as players can't intentionally use it for an advantage. Previously this could be used to do things like open chest remotely, and I did fix that.
