### ISSUE TITLE
Cleaning a single tipped dart

### ISSUE THREAD

**Issue by Surhan-code** [00-Evan/shattered-pixel-dungeon#1773]
When cleaning a single tipped dart it gives you three options (clean all)(clean one)(cancel) ,I mean cleaning all or one is the same if I only have one.

**Comment by Surhan-code** [comment]
https://github.com/user-attachments/assets/12ee4ba9-ee7d-4b9a-a65a-02efce927507

**Comment by Surhan-code** [comment]
![Screenshot_٢٠٢٤٠٨٢٦_٢٢٥٥١٦](https://github.com/user-attachments/assets/210fdaf5-8a72-4b99-b97f-3ae3de2a495a)
I can't explain the feeling

**Comment by 00-Evan** [comment]
fixed in commit e8cf6d0a0b7f6d503edb557bd95be63a3312d62b
