### ISSUE TITLE
Tengu could catch fire and never extinguish it though on the water tile

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1774]
![IMG_20240824_221912](https://github.com/user-attachments/assets/616a7456-ba3e-4f2d-8a7c-d15a2e3271dd)

Tengu could catch fire and never extinguish it though on the water tile

**Comment by 00-Evan** [comment]
The particle effect shown in your screenshot is not present in Shattered Pixel Dungeon. Please don't report issues encountered in other PD versions, or in modified versions of Shattered.

**Comment by koisikawa** [comment]
> The particle effect shown in your screenshot is not present in Shattered Pixel Dungeon. Please don't report issues encountered in other PD versions, or in modified versions of Shattered.

I tried to reproduce it in SPD. Here's the screenshot.

![Screenshot_20240825_233934_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/64c8ed7c-77f7-4f33-8266-29fe72e6436b)

**Comment by koisikawa** [comment]
And it still remain in v2.5.0

![Screenshot_20240827_113403_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/a4822c97-e743-481a-b286-b500b52b12a2)

**Comment by 00-Evan** [comment]
Thanks for reproducing the issue in Shattered Pixel Dungeon.

This is leftover code from quite a while ago that was made to prevent Tengu from triggering his own traps (internally within game logic he is considered to be flying). Probably having that is no longer relevant, and it could be removed.

> And it still remain in v2.5.0

Are you surprised by that? Bugs that aren't listed as fixed tend to still exist after an update.

**Comment by koisikawa** [comment]
> Are you surprised by that? Bugs that aren't listed as fixed tend to still exist after an update.

That's just casual because of the recent update. Sorry for the unnecessary comment.

**Comment by 00-Evan** [comment]
fixed in commit b70870c105d3589fcabbb7d0d6b79db7bd98c2e6
