### ISSUE TITLE
Weird button behavior

### ISSUE THREAD

**Issue by nurgalinchik** [00-Evan/shattered-pixel-dungeon#1775]
Hello, Evan, great job on the beta! So I don't know if it's supposed to be this way, but when I logged into the game, it gave me the victory pop-up right away, I thought it was strange. And also, when clicking play, and after that clicking on the arrow thing, the UI just fades, until I click anywhere on the screen again, which is a little bit weird too! I'll post if there are any more issues with the beta.
![image](https://github.com/user-attachments/assets/0373e38f-a910-4373-9568-d25e440ddbfc)
![image](https://github.com/user-attachments/assets/2380ea51-fc6e-4b10-a006-a9a6654b5099)

**Comment by 00-Evan** [comment]
As you've mentioned, that is intended. The right button is meant for hiding the UI and viewing the splash art.
