### ISSUE TITLE
Weird Goo Boss room

### ISSUE THREAD

**Issue by TobinLeNain** [00-Evan/shattered-pixel-dungeon#1779]
![Screenshot_2024-08-27-15-03-04-817_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/c94d47e1-b3b5-4cb1-9a88-ecfa567a8d4d)
As you can see, the left side of the room is missing a plank column.

edit : I'm in the latest beta (2.5-BETA)
          The seed is GPQ-YBS-LCC

**Comment by 00-Evan** [comment]
That is intended, the wooden floor only spawns between doorways in that room. There is a hidden door in the bottom-left corner that the floor is hinting at.
