### ISSUE TITLE
Gfx mob low hp (bug?)

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#178]
When a mob's hp is very low it looks like it doesn't have any. My suggestion is to always show at least 1 green px row.

**Comment by 00-Evan** [comment]
I can agree with this, I'll adjust the logic to always round up to the nearest display pixel

**Comment by 00-Evan** [comment]
changed in commit 7cdbb43818020ac98d61908a8e2bc79dede074bf
