### ISSUE TITLE
French translation overlapping with the seed

### ISSUE THREAD

**Issue by TobinLeNain** [00-Evan/shattered-pixel-dungeon#1780]
![Screenshot_2024-08-27-15-12-29-633_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/f289cea9-08c4-4cf9-a90a-cb516a085bf9)

The french translation "Graine de génération" is overlapping with the seed.
That's all of it, but I don't know if i need to post this on the github or in transifex.
 So I started here since for me, it's more like a glitch than a translation mistake.

**Comment by 00-Evan** [comment]
Translation issues should be reported on the game's Transifex project. This isn't a UI glitch, the translation is too large for the space given for the text.
