### ISSUE TITLE
Different armor values in upgrade menu

### ISSUE THREAD

**Issue by Halifay** [00-Evan/shattered-pixel-dungeon#1781]
Using scroll of upgrade on armor shows different block values compared to armor description
![image](https://github.com/user-attachments/assets/6c3e2473-7a77-496b-be7b-802d5a5676a4)
![image](https://github.com/user-attachments/assets/92da39c9-c19c-43a0-921f-0ecbcf4448ed)

**Comment by 00-Evan** [comment]
fixed in BETA-2
