### ISSUE TITLE
"Big Game Hunter" Badge endorsed multiple times

### ISSUE THREAD

**Issue by Dimedime-d** [00-Evan/shattered-pixel-dungeon#1782]
![Screenshot_20240827-132149.png](https://github.com/user-attachments/assets/4131b72c-ac3d-4846-95ea-fe91ed842369)

After cataloguing every rare enemy, any other enemy kill, pick up item, furrow grass re-activates the "badge endorsed" message, including across different save files.

**Comment by 00-Evan** [comment]
fixed in BETA-2
