### ISSUE TITLE
Custom notes can be used to identify consumables 

### ISSUE THREAD

**Issue by Jaykman017** [00-Evan/shattered-pixel-dungeon#1783]
![Screenshot_20240828-023142](https://github.com/user-attachments/assets/796be800-af90-46a1-a6a8-23ce074a0883)
Potion labeled "t", unidentified

![Screenshot_20240828-023149](https://github.com/user-attachments/assets/e34415ae-190f-4b16-a483-139c322568d8)
I can see the custom note applied to the potion of strength

**Comment by Jaykman017** [comment]
This also works for scrolls, but not rings

**Comment by frozenKelp** [comment]
how do you make custom notes?

**Comment by 00-Evan** [comment]
fixed in BETA-2
