### ISSUE TITLE
Mimic not dropping payload when turned into sheep

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1784]
This is in 2.5.0-beta-1. Here are the steps that triggered the bug:

With wondrous resin, hit mimic with a thrown spear, then zapped with wand. Extra wand effect turned the mimic into a sheep. Mimic dropped the thrown weapon, but not its contents.

Thanks!

**Comment by 00-Evan** [comment]
Thanks for the report, but I'm afraid that is intended. Turning enemies into sheep effectively deletes them from the game, including any loot they had.
