### ISSUE TITLE
Item type note not working for rings

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1786]
Hello again. 2.5.0-beta-1

If I add an "item type note" to a ring, the note doesn't appear in the item description the way it does with potions/scrolls, making the note less useful. It works when I use the inventory item note, but then I won't get the benefit if I find another ring of this type without identifying it (like if I transmute it to something else first).

![Screenshot_20240828-124432](https://github.com/user-attachments/assets/c55e2c90-567a-4b88-a494-cd070951cf70)
![Screenshot_20240828-124411](https://github.com/user-attachments/assets/d2f4a09c-cba7-4110-9ac1-2f0a3b45ce89)
![Screenshot_20240828-124500](https://github.com/user-attachments/assets/6eac6ae2-c56b-467c-a493-3ef3d27ca3e6)

A related, minor UI gripe: when I have both types of note on the item, it's hard to tell which is which from the journal screen, so it's not so clear which one is ok to delete. Maybe only allow inventory item notes for items other than potions/scrolls/rings?

I'm really appreciating the notes addition otherwise. Also, the transition screens are fantastic! Thanks for all your hard work here.

**Comment by 00-Evan** [comment]
Glad to hear you're enjoying the feature, sounds like there are two separate issues here:

- The game doesn't seem to 100% clearly distinguish notes on a type of ring, and a specific ring. These should both be possible, as rings both have type identification and specific properties.
- rings don't show their notes in inventory when not IDed

Will look into both of these

**Comment by 00-Evan** [comment]
Small adjustment here, I've gotten this fixed indev and have decided that rings can either have a note for a ring type, or a note for a specific ring, but not both.

**Comment by 00-Evan** [comment]
Fixed in BETA-4, although it looks like there will be followup adjustments in a future beta too.
