### ISSUE TITLE
Killing flies over chasms 

### ISSUE THREAD

**Issue by Surhan-code** [00-Evan/shattered-pixel-dungeon#1787]
https://github.com/user-attachments/assets/5728d7e2-55c6-4884-98f2-7ebb33712a0b

This happens rarely because of pathfinding and the  fact that you don't plan to kill them there but it plays an animation that doesn't make sense

**Comment by kilsw1ch** [comment]
also the dropped loot which is healing potion(not considering ring of luck) drops straight into the chasm and is destroyed which is rather annoying. 
could we make it so that the dropped item is never wasted cuz there's no way of telling which segment of the fly is going to drop the potion.

**Comment by 00-Evan** [comment]
> also the dropped loot which is healing potion(not considering ring of luck) drops straight into the chasm and is destroyed which is rather annoying. could we make it so that the dropped item is never wasted cuz there's no way of telling which segment of the fly is going to drop the potion.

That's intended I'm afraid, killing a character over chasms means you risk anything they drop falling into a chasm.

**Comment by 00-Evan** [comment]
fixed in commit f81f32297e071cb5d98ae7efff3f9556968b7897
