### ISSUE TITLE
Demon reaper not taking a leap towards a spirit hawk which is towards the center of a chasm

### ISSUE THREAD

**Issue by wismos-0rg** [00-Evan/shattered-pixel-dungeon#1788]
![Screenshot_20240830-121642_Trebuchet.png](https://github.com/user-attachments/assets/b82a292c-3f8a-4149-b4c5-43f91f722f44)

wasn't able to upload video due to file size limitation of github free, please check the video on the folllowing google drive link: https://drive.google.com/file/d/1kPmhjyfKwZsrJFY1uakAt2nn5AUBwWRa/view

**Comment by 00-Evan** [comment]
It is intended that ripper demons refuse to leap directly into chasms vs. flying enemies, but they should refuse to start leaping alltogether.

**Comment by 00-Evan** [comment]
after re-checking previous logic I'm changing my stance on this, the error is specifically that rippers don't want to leap exactly on a character surrounded by chasm, I'm going to allow them to die that, they'll get a hit in then fall to their death.

**Comment by 00-Evan** [comment]
fixed in commit 5563ceb3cd3df0f314b129dd83ddb5586746d9ba
