### ISSUE TITLE
Encountered Dark Fist not showing in bestiary 

### ISSUE THREAD

**Issue by wismos-0rg** [00-Evan/shattered-pixel-dungeon#1789]
so this is the first time i have encountered dark fist after installing beta and while i expect it to be logged in bestiary as soon as i encounter it, that doesn't happen for some reason, same with yog, is it necessary to defeat them to get them logged in bestiary?

![Screenshot_20240830-152931_Shattered Pixel Dungeon.png](https://github.com/user-attachments/assets/80aee321-5160-4138-af88-e9045088cdd5)

![Screenshot_20240830-152922_Shattered Pixel Dungeon.png](https://github.com/user-attachments/assets/322c73a0-ae2e-4cac-8cc8-b1091a172b72)

**Comment by 00-Evan** [comment]
Yes, enemies must be defeated to be added to the bestiary.
