### ISSUE TITLE
"Tengu defeated"

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#179]
This message comes __always__ when the second part of the fight begins.

**Comment by 00-Evan** [comment]
I'm aware of this one, it's because Tengu's death logic is a but different. It's very minor so fixing it isn't a high priority, but this is definitely a bug.

**Comment by 00-Evan** [comment]
This should be fixed as a part of the Tengu fight rework in 0.7.5, please let me know if you run into it again.
