### ISSUE TITLE
Scroll of challenge arena not cleared when ascending

### ISSUE THREAD

**Issue by jellicle1** [00-Evan/shattered-pixel-dungeon#1790]
Situation: playing around with a cursed wand on level 25 before ascending. Cursed wand generated a scroll of challenge arena which I think enclosed the up stairs. I ascended the staircase. On level 24, there were red squares of "bubbles" but not in a circle, instead spread across the entire floor in a series of lines. Additionally I had the icon in my status bar indicating however many turns remaining of challenge arena. When I moved off the staircase, these all disappeared and there was no sign of the challenge arena.

Supposition: the challenge arena isn't getting fully cleared when ascending/descending stairs. I'm not sure what the exact intent is - like, if I went back to floor 25, should the arena still have been there? Does time tick for it when you aren't on the floor? I guess this is an edge case that was never really considered.

Anyway, seems to be only a cosmetic bug since it cleared when I left the staircase, so low priority.

**Comment by 00-Evan** [comment]
This should already be fixed as of BETA-2,  which beta version did you encounter this on?

**Comment by jellicle1** [comment]
V2.5.0-BETA-1 on Android

**Comment by 00-Evan** [comment]
Okay then this should already be fixed as of beta-2, please let me know if you run into it again after updating
