### ISSUE TITLE
there are two notes

### ISSUE THREAD

**Issue by rtgggggg** [00-Evan/shattered-pixel-dungeon#1791]
I only took one note of this ring, but it appeared twice
![Screenshot_2024-08-31-08-29-42-16.jpg](https://github.com/user-attachments/assets/6fe5cfd3-4029-4275-8eba-f4bde7a0718d)

![Screenshot_2024-08-31-08-29-47-25.jpg](https://github.com/user-attachments/assets/025e18fd-7315-46b9-8ec1-a1717aa54ee1)

**Comment by rtgggggg** [comment]
And known types of rings will not be labeled in the journal 
because scrolls and potions are labeled, so they appear abnormal
![Screenshot_2024-08-31-10-22-35-50.jpg](https://github.com/user-attachments/assets/a4ba45e7-d84e-4405-88d6-5360c7080d31)

![Screenshot_2024-08-31-10-22-40-15.jpg](https://github.com/user-attachments/assets/4aaae4d0-35ae-497b-b6c2-a50b02e8339e)

**Comment by 00-Evan** [comment]
Fixed in BETA-5
