### ISSUE TITLE
Arcane Resin does not state that it is overridden by blacksmith upgrades

### ISSUE THREAD

**Issue by regorxxx** [00-Evan/shattered-pixel-dungeon#1792]
After using the upgrade reward on a wand +1 (with resin), the resin upgrade is simply lost and replaced with the troll upgrade.

While that may be right (since it would require 2 resin for the final +2), it is not working in a clear way for the final user. Also it's applied without warning, so you loose both the free upgrade (the final level is the same) and/or the resin (to be reused).

I know there is a warning somewhere about resin upgrades not being "true" upgrades, but totally forgot about the wand using resin while using the troll UI. If the logic is left as is (resin could be gained back), it would be great to have some kind of warning when trying to upgrade a wand, either by scroll or any other method.

**Comment by 00-Evan** [comment]
From re-reading the deacription of arcane reson, it seems that scrolls of upgrade are mentioned specifically, it is probably better to state 'regular upgrades', to make it more clear that the blacksmith's upgrade does count against resin here.

**Comment by 00-Evan** [comment]
fixed in commit 8a3e5995754d3af4efc68e171942e3003d7ba6f3
