### ISSUE TITLE
Beta 4: Plants not added to catalog via examine

### ISSUE THREAD

**Issue by TheYsconator** [00-Evan/shattered-pixel-dungeon#1795]
https://github.com/user-attachments/assets/a6ee1d12-70a0-44a0-99e0-1bd5ea3af021

The changelog states that plants and traps are now added to the catalog after examine. However, in at least one case, this was not the case for me (see video). I have not tried if it does work for traps or other plants.

**Comment by 00-Evan** [comment]
Fixed in BETA-5
