### ISSUE TITLE
Bug with Fully Stocked Badge on mobile.

### ISSUE THREAD

**Issue by DarthIlius** [00-Evan/shattered-pixel-dungeon#1796]
So when I died I got Fully Stocked badge, when I switched out and into the game, though I still have Scroll of Transfusion unidentified. I had it in my inventory unidentified (I checked scrolls after death)

![Screenshot_2024-08-31-17-52-15-038_com.shatteredpixel.shatteredpixeldungeon.jpg](https://github.com/user-attachments/assets/5c15969c-882e-4e5e-8760-7b668bb2ddbe)

![Screenshot_2024-08-31-17-55-13-066_com.shatteredpixel.shatteredpixeldungeon.jpg](https://github.com/user-attachments/assets/2a783654-9d34-4730-9ff6-1f22b21454d5)

![Screenshot_2024-08-31-17-55-42-520_com.shatteredpixel.shatteredpixeldungeon.jpg](https://github.com/user-attachments/assets/7f9ec3ac-fce0-4691-aacb-cc34fb340301)

**Comment by 00-Evan** [comment]
Fixed in BETA-5
