### ISSUE TITLE
Suggestion: Move "Consumables" to the first tab in the journal instead of equipment

### ISSUE THREAD

**Issue by jessdwitch** [00-Evan/shattered-pixel-dungeon#1805]
Love the new journal!
It's possible I'm an exception, but the most common reason I go into the journal is to check known potions and scrolls for that specific run. It'd be nice if it was the first tab to come up when clicking into that tab, instead of equipment.

Also, really like that scrolls and potions are now visible at the same time, and thank you for the very nice update!

**Comment by 00-Evan** [comment]
Glad to hear you like the new journal!

I put equipment first as that made the most logical sense, those items are more important than consumables. the catalog tab and journal window do remember what tabs you were on last though (even scroll position), so you should only have to navigate there once per play session.
