### ISSUE TITLE
Parchment Scrap +3 does not always flag item as uncursed

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1807]
I have a Parchment Scrap +3, which says in the description that weapons and armor will have a curse probabiliy of 0 %. I defeated a skeleton and it dropped a Shocking Sword, which was flagged as unknown (purple background) instead of uncursed (blue background).
![Screenshot_20240906_012704](https://github.com/user-attachments/assets/395c05ad-2f05-42b3-9fa3-35ac72a6e3e5)
![Screenshot_20240906_012721](https://github.com/user-attachments/assets/8bcc560e-f7d4-4467-bd5d-1ac293e2cd61)

**Comment by 00-Evan** [comment]
That's intended, identifying curse state is not part of the parchment's functionality, even if it is turned to 0%.
