### ISSUE TITLE
Notes bug

### ISSUE THREAD

**Issue by rtgggggg** [00-Evan/shattered-pixel-dungeon#1808]
No matter how many notes I take on this item, it won't show up

![Screenshot_2024-09-06-17-45-38-28.jpg](https://github.com/user-attachments/assets/048ed5ca-8419-4c6b-8968-449b3f54a0ca)

![Screenshot_2024-09-06-17-44-51-67.jpg](https://github.com/user-attachments/assets/0565b19e-7007-40df-8a90-92eec17fc68d)

**Comment by 00-Evan** [comment]
Fixed in RC-1
