### ISSUE TITLE
Berserker dies

### ISSUE THREAD

**Issue by camlost** [00-Evan/shattered-pixel-dungeon#181]
I had a berserker die without triggering the "refuse to die" mechanic.  I'm guessing it's due to the use of a slow weapon and a timing issue?

Potentially relevant data
- Character had not "refused to die" at any point prior.
- Character was wielding a slow weapon (flail).  
- Character had used an ankh before, but had none in inventory.
- Character was killed by gnoll brute (enraged).

**Comment by 00-Evan** [comment]
hmm, was the ankh blessed or regular?

**Comment by 00-Evan** [comment]
I've made a few improvements to the resilience of berserker logic in commit 479dd40bf750549e3b9ec16cbf6ea4eb7c09d9f7

I'm going to close this for now, but please let me know if you get this issue again.
