### ISSUE TITLE
Self-destruct joke too obscure

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#1810]
I got the CursedWand.veryRareEffect(case 2) "crash". Nicely done and the wording does indeed come across as satire, but I still believed it was actually caused by some unexpected internal state, not chosen intentionally. Like the "guru meditation error" was actually a kind of "uncaught exception" handler back then.

That said, the Wondrous Resin +3 wording _suggests_ one is safe from being harmed by it, which is not true. Similar to how 'blazing' is classified as enchantment when it's really one of the worst curses 🤪 🤣 🙃

**Comment by patman-cp** [comment]
> I still believed it was actually caused by some unexpected internal state

But that's the intention ...

**Comment by 00-Evan** [comment]
Sorry but I don't plan to remove this joke. It is considered a neutral effect as the results are entirely cosmetic.

**Comment by spixi** [comment]
@00-Evan We got so many amazing new cursed wand effects like the bubble particle effect or the holy glow effect. Maybe the crash effect could get a small rework by just returning to the title screen instead of closing the app as I mentioned before.
