### ISSUE TITLE
journal behavior

### ISSUE THREAD

**Issue by kilsw1ch** [00-Evan/shattered-pixel-dungeon#1811]
i have already won the game multiple times, but the journal doesn't take those runs into consideration.

everything except the items already present in the journal like the potions or weapons are identified which is good.

everything else like the bestiary or thrown weapons are totally blank saying that "You haven't found and identified that item in any of your runs yet." 

this could be a bug or an issue, or just intended behavior and if so, it truly doesn't feel right to say in "any" of your runs yet.

changing the given reason might help.

**Comment by kilsw1ch** [comment]
just tested it with gboard, works as intended. 

so the issue is with swiftkey keyboard, not the game, which i think is due to some compatibility issues.

i can replicate the issue and post a video if you would like.

**Comment by 00-Evan** [comment]
Feel free to share a video of the keyboard error, but yes I'm afraid I can't commit to fixing a bug with 3rd party keyboard apps.

Regarding the bestiary, it is intended that anything you fill out there persists between runs. Do you mean that you can do something like kill a few rats, have the rat entry by recorded in the bestiary, then close the game, re-open it, and the rat entry is gone?

**Comment by kilsw1ch** [comment]
the bestiary records and it does persist between runs, but what i'm stating that it doesn't show the progress i've already made.

for better clarity, i've won the game before the beta, which means i've already fought all the regular enemies, used all thrown weapons and have obtained the amulet as well, but the game outright says that i haven't found or identified the mentioned items before in any of my runs, which is not true.

i might be making an unnecessary fuss out of an intended feature i guess, but i can't understand the reason behind the journal disregarding all my previous runs and working on the newer runs only.

**Comment by kilsw1ch** [comment]
ah, i get it.
