### ISSUE TITLE
(2.5.0-BETA-5) Items already in the inventory aren't added to the journal

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1814]
In situations such as returning to an old run, existing inventory contents (items, enchantments, bags, etc.) don't get added to the journal automatically, leading to an inventory full of items that the player has seemingly never heard of

**Comment by 00-Evan** [comment]
I'm fine with this, as it's exclusively an issue for existing runs and doesn't affect gameplay in any way.
