### ISSUE TITLE
Idea suggestion. Need shortcut of custom note function from inventory.

### ISSUE THREAD

**Issue by YouIG** [00-Evan/shattered-pixel-dungeon#1815]
Hi evan. 

I have some simple idea of quick access to custom note function.

Currently if we want to take a note need 3 steps now. 

1. Press the 'Book' button on top-right side. 
![step 1](https://github.com/user-attachments/assets/b40e39f7-8740-4d52-9b80-a3b03dd13c67)

2. Press the 'Plus' button on top-right side of pop-up. 
![step 2](https://github.com/user-attachments/assets/7e80b7f5-e030-4507-9935-b6e2340c924e)

3. Select note what you want. 
![step 3](https://github.com/user-attachments/assets/127bb3f4-cb08-42ff-8da8-2bf93e9df317)

It's quite inconvenient to take a quick note while playing the game.

Our fingers mostly stay on down-side of the phone. So to take a note we need to move the finger to the top-right side of the phone every time and I feel this is so inconvenient. 

I think players mainly take a note about the items, So if we have quick access button from inventory, I guess it is much more convenient. 
![note shortcut](https://github.com/user-attachments/assets/314d4a38-97e0-48bf-9668-97b0e143d743)

**Comment by 00-Evan** [comment]
That spot is already being used for rename functionality for equipment.

I understand the desire to place custom note functionality directly in the inventory, but for the moment I decided against it as the inventory UI is already stuffed with different functionality, and I wanted custom note functionality to all exist within one place. The fact you didn't realize that UI spot is already being used showcases that pretty well.

**Comment by YouIG** [comment]
Oh, there is misunderstanding.

I already known exist of 'rename' button on that spot and I thought it will be not bad even with that 'rename' and 'note' button same position.

I meant with that picture is just a example UI of quick access button about custom note.

Anyways I understand what you mean. Hope you improve QoL about custom note in the near future.

Thank you evan.

**Comment by 00-Evan** [comment]
So then you're suggesting the former rename button would then open a sub window letting you pick between rename or making a custom note? From the main menu, that would mean getting to the note entering UI would take 4 presses, more if the item were in a separate inventory bag from the default one.

**Comment by YouIG** [comment]
Yes, I think that could be the better solution. 

My points of that suggestion was while we playing the game, our fingers mostly stay on down-side of the phone. (mostly bottom-right side / near by inventory button)

So even though it takes same or more amount of presses, UI near by down-side is much more convienient for most players I guess. (for those who playing the game as portrait.)

I mainly use the custom note for 'unknown items' like potions and scrolls, not for equipments a lot.

By the way, I wonder how many players use that 'rename' function as intended so far. In my case, I used that as semi-custom notes function before 2.5.0 update. 

So there is no 'rename' function for those consumable items, making simillar icon of 'rename' button to consumable items as quick access to custom note is not that bad I think.
