### ISSUE TITLE
I have found a very funny bug

### ISSUE THREAD

**Issue by FunnyDudeislazy** [00-Evan/shattered-pixel-dungeon#1816]
Here how to do it

First, drop a item on the floor, then drop an another item in the same position, the first item you dropped earlier, then make your inventory is full, and pickup it and do it for a long item and you see that the item will fly, and it's very funny

![Screenshot_۲۰۲۴۰۹۰۸_۲۲۲۴۲۳](https://github.com/user-attachments/assets/74b8868b-2c49-47e5-bbf8-6f619875e1a8)
As you can see, I clicked so many time and it's flying, it's not a game breaking bug, rather a funny one

**Comment by 00-Evan** [comment]
This is intended actually, sort of. See: https://github.com/00-Evan/shattered-pixel-dungeon/issues/40.

Other duplicates of this are: #1770, #1731, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1713, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1654, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1540, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1468, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1436, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1355, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1150, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1073, https://github.com/00-Evan/shattered-pixel-dungeon/issues/689, https://github.com/00-Evan/shattered-pixel-dungeon/issues/640, https://github.com/00-Evan/shattered-pixel-dungeon/issues/203.

**Comment by FunnyDudeislazy** [comment]
I mean it's not really important, so yeah, but I didn't knew that there's people reporting this small yet unnoticeable bug
