### ISSUE TITLE
Font rendering issue in new note feature

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1818]
When you insert a non-Latin character, e. g. ♡ 'WHITE HEART SUIT' (U+2661) in the text box in a note, it is rendered as a placeholder symbol. However, when you also insert a Japanese kana, e. g. あ, the correct symbols are shown.
![Screenshot_20240909_232458](https://github.com/user-attachments/assets/6f571c31-017f-4f93-98b5-a755ab05b6a9)
![Screenshot_20240909_232535](https://github.com/user-attachments/assets/7d1e7ece-cda7-4935-9073-87a34611f6f2)

**Comment by spixi** [comment]
![Screenshot_20240909_234106](https://github.com/user-attachments/assets/379797fb-02a1-45f1-9b0b-65ab83732a21)
![Screenshot_20240909_234124](https://github.com/user-attachments/assets/4390ac11-b426-4488-bbde-b564ccae2b08)

**Comment by 00-Evan** [comment]
Alright so you're reporting two separate things here:

- for special characters, the game does not support special characters. They may incidentally work depending on which font is used, in the case you mentioned the game switches to system font for Japanese characters, and so may incidentally support different symbols.

- for underlining, the game uses _ as a special character for text highlighting. Probably there should be some logic here to prevent it being used for that purpose in item descriptions.

**Comment by 00-Evan** [comment]
fixed in commit 943222ca96dd641d8532b1f15330a6e87ed62b78
