### ISSUE TITLE
Duelist's 'Heavy Blow' always make enemy 'Dazed' whether it is not surprised attack

### ISSUE THREAD

**Issue by YouIG** [00-Evan/shattered-pixel-dungeon#1819]
![Not surprised](https://github.com/user-attachments/assets/ebfbc896-e20d-496f-b8dc-c2997833a98b)
![Heavy Blow](https://github.com/user-attachments/assets/76825d97-4cd8-4ee5-92ba-ba1596b44a22)
![Dazed](https://github.com/user-attachments/assets/d11323e0-c9b2-43b1-91b0-e02122148672)

It happened entire game to whole enemy. 

Firstly I thought maybe it is buffed but I couldn't find any mention about it on previous patch notes.

**Comment by spixi** [comment]
I think that this is intended. The additional damage boost is a bonus only granted for surprise attacks. The War Hammer is already a very accurate weapon, so that bonus is to balance it better against the Assassin's Blade.

**Comment by YouIG** [comment]
But as I attached a picture the description of 'Heavy Blow' is still same and there is no mention about it on any patch notes. 

If it was really intended, it is good for us though.

**Comment by spixi** [comment]
> Wait, spixi I think you may misunderstood my post.
> 
> I mean it is 'Bug Report' for 'Heavy Blow' dazing enemy every time, even it was not surprised attack.
> 
> Not about why 'Heavy Blow' dazing enemy.
> 
> and I misunderstood what you mean too lol.

Yes and that is correct. "Heavy Blow" always hits and always dazes the target. In addition there is a damage bonus, but only when it is a suprise attack.

**Comment by YouIG** [comment]
OMG you are right. Thank you and sorry spixi. I'll delete this post in 1 hour
