### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by OffifialMITX** [00-Evan/shattered-pixel-dungeon#182]
I __really__ like the "[floating item](https://drive.google.com/open?id=0B8HcTODSY2XzSThpdm8zX0NaQUk)" feature ;-)

**Comment by 00-Evan** [comment]
not a bug, actually a feature: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/sprites/ItemSprite.java#L150

**Comment by OffifialMITX** [comment]
Oh...
