### ISSUE TITLE
Region introductions are not added to the journal

### ISSUE THREAD

**Issue by maximpeplin** [00-Evan/shattered-pixel-dungeon#1820]
Discovered regions do not show up in the journal (except for the sewers), even though I have reached them several times.
![Screenshot_20240910-175229_Shattered_Pixel_Dungeon](https://github.com/user-attachments/assets/15caef32-837b-4f3f-8ef5-c2849d3ebe09)
The version is V2.5.0-RC-1.

**Comment by 00-Evan** [comment]
fixed in commit 0368b61d89745ba5a92f357f87b3f9e2393792d1
