### ISSUE TITLE
Spamming the pick-up button with a full inventory causes the item to rise indefinitely

### ISSUE THREAD

**Issue by User-23415** [00-Evan/shattered-pixel-dungeon#1822]
Normally when you attempt to pickup an item you don’t have room for, it plays a short animation where it bumps into the air for a short time. However, if you rapidly press the pickup button, the animation cannot finish, and the item sprite rises through the air. It teleports back to its normal spot when you stop spamming.

Steps to recreate this issue:
1. Walk over an item you don’t have space for in your inventory.
2. Spam the pickup button as fast as you can.

**Comment by 00-Evan** [comment]
This is intended actually! Sort of. See: https://github.com/00-Evan/shattered-pixel-dungeon/issues/40.

Other duplicates of this are: #1816, #1770, #1731, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1713, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1654, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1540, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1468, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1436, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1355, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1150, https://github.com/00-Evan/shattered-pixel-dungeon/issues/1073, https://github.com/00-Evan/shattered-pixel-dungeon/issues/689, https://github.com/00-Evan/shattered-pixel-dungeon/issues/640, https://github.com/00-Evan/shattered-pixel-dungeon/issues/203.
