### ISSUE TITLE
Entry in notes revealed existence of secret well of health

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1823]
Hello. I have another possible bug to report:

When exploring a floor, I found a well of health, which I consumed. Normally, consuming the well would remove the entry from the floor grid in the adventuring notes, but this time it didn't disappear. I went back up and found that there was a second, secret well of health on that floor that I hadn't found previously. The note gave its existence away.

Attaching some supporting screenshots:
![Screenshot_20240910-140925](https://github.com/user-attachments/assets/5ff765b7-8763-4828-ac48-c0c7cd369da7)
![Screenshot_20240910-140933](https://github.com/user-attachments/assets/325ce4ef-b6db-4be5-a0bf-95047e0da3b9)
![Screenshot_20240910-140943](https://github.com/user-attachments/assets/3bb74b1e-10f4-4cb1-94c7-225d54b1b1b8)
![Screenshot_20240910-141005](https://github.com/user-attachments/assets/da758ef4-4b32-436d-823c-625aeffdc4e2)

**Comment by 00-Evan** [comment]
fixed in commit ef43f245836cf1f7b59c72aa67e733447292c3d3
