### ISSUE TITLE
Sniper's Mark doesn't display remaining turns

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1826]
The duration of sniper's mark currently isn't displayed anywhere; the only way to know how long it lasts is to let it run out
<img src="https://github.com/user-attachments/assets/0ef1e8cf-94f0-471d-a583-c3d2fcf83636" width="270">
This is especially tricky with the Shared Upgrades talent, as the sniper's mark icon doesn't "count down" like it should, instead, it stays full until the mark duration hits 4 turns, and then starts dropping

<img src="https://github.com/user-attachments/assets/df3320e0-c4b6-4640-9db5-4bf45d43eb39" width="100">

The icon i'm referring to, just for clarity

**Comment by 00-Evan** [comment]
fixed in commit be15d9737ba27fc4ed111b3aa327638862b2cc74
