### ISSUE TITLE
this is not a bug

### ISSUE THREAD

**Issue by FunnyDudeislazy** [00-Evan/shattered-pixel-dungeon#1827]
i don't know that much about java

but but how do i changed a hero name in java?
like for e.g i want to change warrior name to josh, how do i do that?

**Comment by bluestmango** [comment]
why are you asking here???? look on reddit or something, this is for bugs

**Comment by FunnyDudeislazy** [comment]
where i can find it? also i will spend my time in java for some learning

**Comment by 00-Evan** [comment]
This is primarily a place for reporting technical issues with the game.

As for your question, do you mean changing names in the code, or renaming your hero within the game as a player?

If you mean the code, take a look at the name() method within Hero.java, around line 400.

If you mean ingame, the hero rename button is in the hero select scene, assuming you've unlocked it (paid versions or google play supporters)

**Comment by FunnyDudeislazy** [comment]
![VSCodium_4ImJDNqgXO](https://github.com/user-attachments/assets/7eadcef7-e764-4dc3-9dfc-e954f2edf039)
is this the code?

**Comment by 00-Evan** [comment]
> ![VSCodium_4ImJDNqgXO](https://private-user-images.githubusercontent.com/163767224/367197196-7eadcef7-e764-4dc3-9dfc-e954f2edf039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzkwNTksIm5iZiI6MTcyNjIzODc1OSwicGF0aCI6Ii8xNjM3NjcyMjQvMzY3MTk3MTk2LTdlYWRjZWY3LWU3NjQtNGRjMy05ZGZjLWU5NTRmMmVkZjAzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNDQ1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmM1ZjI4ZmQwZmFkNDQ5MzYxNWU3NTFjZjBiYzlkOWY3NDU3ZjQzZjc0M2IyNjNlYWQyMDgzN2ZlYjIzOTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2ZPS8-Szv8gJfncmRUfZ5Z_0Ipvaqhhiwp91zyNS3wY) is this the code?

yea that's correct

**Comment by FunnyDudeislazy** [comment]
now, there's need to be a warrior name string vaule, right?
