### ISSUE TITLE
Passive Summoned Guardian 

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#1828]
I stumbled upon an alarm trap on level 12 but left the level before engaging the Summoned Guardian. On my way up after getting the Amulet, I've met the guardian again, but it's completely passive. It doesn't move. It doesn't attack. It just stays there. 

I'm attaching a screenshot for all it's worth of myself fraternizing with the statue.

Dungeon seed is: ZSD-MJX-YDK.

![Screenshot_20240911-225449](https://github.com/user-attachments/assets/7685f0d3-544b-467b-8455-9f0884e7e4cd)

**Comment by 00-Evan** [comment]
fixed in commit f5f7568ac9ec62ce3c19db1d76e93c5841ad75d6
