### ISSUE TITLE
Near(?)-impossible UI imperfection in upgrade window

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#1829]
The "upgrade lost" text may be missing for extreme item levels >= 28:
https://github.com/00-Evan/shattered-pixel-dungeon/blob/3643145a8a2b936b0c72317f8276d33bb6b5f5ea/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/windows/WndUpgrade.java#L351
... because casting to int before the Math.min (2^28*10 == -0x60000000)

Irrelevant if the max number of upgrade scrolls without forbidden runes is less than ... 24? +2 levels findable +2 from blacksmith? Dunno, never paid attention in non-highscore runs.

**Comment by bluestmango** [comment]
Shouldn't be an issue, the theoretical max is +25. +4 ring from imp, 15 SoU, +2 from troll, and +4 from curse infusion
