### ISSUE TITLE
Migration from a 2.4 save can mark catalog entries as unknown that are present in inventory

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#1830]
Catalog init for "completed in earlier versions" [seems to draw only from badges](https://github.com/00-Evan/shattered-pixel-dungeon/blob/f6299e07c8e40134b2960dc546d1e5f94fb98923/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/journal/Catalog.java#L391-L409), but should maybe also have scanned the current inventory.

To repro (just the easiest I could think of, should affect some more items):
- Uninstall and reinstall 2.4.2 to clear out remnants
- Start a Huntress and get a trinket, don't lose the bow, save
- Upgrade to 2.5 and load that game
- Check inventory and catalog: Spirit Bow and Trinket are missing and marked unidentified

Since people will upgrade and regenerate these entries quickly this is likely not worth fixing.

Side note: I learned from commit messages that I need to _examine_ to get the Rot Heart entry, killing it isn't enough.... But Grandmaster Researcher is close!

Another side note: 2.5 feels overal like... pure genius. So much has gotten so much nicer or more interesting, feels like more than 2.2. to 2.4.

**Comment by 00-Evan** [comment]
I'm fine with this, badge conversion occurs because those entries may not be in the catalog at all otherwise. I wanted to preserve existing catalog entries, but otherwise expect players to fill the catalogs in with new games.
