### ISSUE TITLE
A couple of minor textual errors

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1831]
First, the word "the" is incorrectly capitalized in the SoU description. "Unfortunately, **The** upgrading magic can also erase enchantments..."

<img src="https://github.com/user-attachments/assets/471d1956-d03c-4745-812c-548e10c6c612" width="250">

Second one's a bit subjective, but I found the wording of Wand Preservation a bit unclear. Rather than 1 use each time the hero levels up, I read it as 1 use per level the hero gains **or has gained** (i.e. a level 10 hero would be able to use the talent 10 times). IMO, something like "once per level up" would be clearer

<img src="https://github.com/user-attachments/assets/05d182c7-dc74-4189-b974-4778ece65105" width="250">

**Comment by 00-Evan** [comment]
Will fix the first one, ty

As for the second one, I feel like "once per level up" reads the exact same as "once per hero level". adding clarity hear would require something like "once per hero level after the talent is used" or "has a cooldown of one hero level". I opted not to phrase it like that as it breaks consistency with the +1 text.

**Comment by 00-Evan** [comment]
fixed in commit 575ad36eca805ec888b118db485479139d8b7418
