### ISSUE TITLE
Chaotic Censer softlock + deletion of save v2.5.0

### ISSUE THREAD

**Issue by Viking344** [00-Evan/shattered-pixel-dungeon#1832]
Entered a new floor with a +3 Chaotic Censer.

On turn 0 or 1 of the new floor (character still standing on stairwell during softlock), the censer let out one particle of shrouding fog, then endlessly spewed corrosive gas at infinite speed, preventing the turn from ending.

Upon force-closing the game, the run is listed as a loss with cause of death: burning

V2.5.0
Huntress
Floor 5
Wayward Spear (cursed)
Leather armour of repulsion +2
Armband of Thieves
Ring of Force +2
Ring of Evasion

Badder bosses/hostile champions

Edit: Run listed as a death with negative run duration in rankings

![Screenshot_20240913_093015_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/a1792473-7e59-49fd-adfb-dd3377aca17c)

**Comment by 00-Evan** [comment]
Hm, it seems unlikely that this was an error with the chaotic censer directly, more likely a problem with turn processing, which in turn meant the censer kept getting to act, hence the ridiculous game duration being shown. Can you give me any more information about what was happening during and just before descending to a new floor?

**Comment by 00-Evan** [comment]
Another user has also repotred this so there's definitely something up with the censer specifically, possibly on floor 5 as well (though that me be a coincidence). I'll be taking a look into this soon to try and figure out what's up.

**Comment by bluestmango** [comment]
Out of curiosity, what does cause this?

**Comment by 00-Evan** [comment]
> Out of curiosity, what does cause this?

To be honest I have not been able to 100% reproduce the issue. There are other bugs with the censer atm though, including a crash bug which I suspect is leading to this. The Censer's logic happens in the game's actor thread, not the main thread, so it is possible for a crash to happen there without the game immediately closing in some cases.

**Comment by 00-Evan** [comment]
hopefully fixed in commit dea5aa38b96ffcd010f6cf4002bcfcd79261944f

let me know if you encounter this again and I'll re-open
