### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [00-Evan/shattered-pixel-dungeon#1833]
https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/build.gradle#L6 This repo is not allowed. How about I remove it and also bump the min sdk to 19 for this version and revert it later? Or we should just skip this version until AGP is updated?

**Comment by 00-Evan** [comment]
I'm afraid I have no involvement in the F-Droid build of the game, I'd recommend that you open an issue with them.
