### ISSUE TITLE
The prizes in the toxic gas room may be on the trap tile

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1834]
![Screenshot_2024_0916_124838](https://github.com/user-attachments/assets/68fd3da7-09a5-4762-b9f8-fd730789556f)

I'm not sure if it could be considered as an issue. I decided to raise it first anyway.

**Comment by 00-Evan** [comment]
In general it is fine for levelgen to place traps inside of special rooms, or on top of items, however there is precedent for traps to not spawn in rooms which make use of their own traps (e.g. secret gold hoard rooms, or standard rooms with fire/explosion traps). 

Whether this room uses its own traps is debatable though, and unfortunately making this change would alter level generation, which I try to avoid doing in patches, so I'm going to close this issue for now but will add it to my list to consider for a future update.
