### ISSUE TITLE
The field of view in the dark levels is still four tiles.

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1835]
![Screenshot_20240916_231306_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/f6b78d6e-f7dc-4330-988b-a26a8ee1e9ea)

The field of view was five tiles when I first came to this level. But it changed to four the second time I came here.

**Comment by 00-Evan** [comment]
fixed in commit e88c6894c5f587a7a78d1db86a5e8fc6cc563e75
