### ISSUE TITLE
Wayward cursed weapon not registering correctly.

### ISSUE THREAD

**Issue by VencedorL0L** [00-Evan/shattered-pixel-dungeon#1838]
So, I am collection-hunting (focusing on getting every single collection asap) and I am doing great, only missing some curses in the whole collection book. I find a sacrificial room. "Great", I think, "a guaranteed curse". Then I use it, and get my weapon. "Wayward, I am sure I didn't register that yet, perfect", then I equip it and...
![Screenshot_2024-09-17-07-51-40-638_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/aaf8e996-548a-47d1-8d63-20cf36a1f75d)
![Screenshot_2024-09-17-07-51-38-482_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/c14d7fea-332a-4aad-9264-b253a06fb909)
![Screenshot_2024-09-17-07-51-35-813_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/8f9bb6a7-7ba7-4855-9543-c135601d817c)
![Screenshot_2024-09-17-07-51-33-042_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/544a728f-0b89-43dc-8ac4-dcb2a3870841)
![Screenshot_2024-09-17-07-51-26-663_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/b408a019-a5e5-497b-b79c-a3af81fc5adf)
![Screenshot_2024-09-17-07-51-10-342_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/4e7abf9d-cd82-4109-951e-ededcffa4c27)
![Screenshot_2024-09-17-07-51-05-226_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/ac4d4ac4-fe1b-45d5-ad1f-00617da907aa)
Using 2.5.1, android. I've been playing and filling up the entries since snapshot-2 or so.

**Comment by VencedorL0L** [comment]
It fixed as I identified the weapon

**Comment by 00-Evan** [comment]
Yeah the weapon has to be identified for the curse to register in the catalogs

**Comment by VencedorL0L** [comment]
Oh, ok. It'd seem reasonable for the weapon to be able to be in the register without identify if you know the curse, just thought that that's how it worked
