### ISSUE TITLE
new strange bug in 2.5.2

### ISSUE THREAD

**Issue by Ardes-Lc** [00-Evan/shattered-pixel-dungeon#1840]
rat and white rat can fly after this update,they can fly over the chasm 
with no wings and can hurt hero.

version:v2.5.2
seeds: all seeds have this problem
challenge:hostile champions/bladder bosses
language:Chinese

I tested with my old game and ripper demon
has no such bug. Snake has no too.More mobs haven't test yet and I'd like to report it first.
It's weird but fun isn't it🤔
![Screenshot_20240918_011806](https://github.com/user-attachments/assets/c92f1c66-7cdd-482d-95ae-b4aec19cb1f0)
![Screenshot_20240918_012022](https://github.com/user-attachments/assets/f20911df-b7e8-4647-938b-dd09a31eb4c4)

**Comment by 00-Evan** [comment]
I've already released an amended v2.5.2 that should fix this, please try updating.

If you're getting the game via Google Play then please wait a half hour or so as the amended v2.5.2 goes through review.
