### ISSUE TITLE
Embers and embermoss don't appear in the search window on floor 26 terrain.

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1841]
![Screenshot_20240917-220931](https://github.com/user-attachments/assets/2bf21b92-595f-4321-b490-c966621dc1e8)
![Screenshot_20240917-221020](https://github.com/user-attachments/assets/ab343062-49c9-4a29-aeac-0f130decd4ba)

**Comment by 00-Evan** [comment]
This is a quirk caused by custom tile visuals, I'm fine with leaving it as-is.
