### ISSUE TITLE
eye of newt causes monsters to awaken through doors

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1842]
Monsters awaken even before you enter a room when you have the eye of newt.
Is this supposed to happen?  Does seeing monsters mean they can also see you?
Talisman of foresight does not seem to have the same effect.
![Screenshot_20240917-230205](https://github.com/user-attachments/assets/c52c3485-de56-40a4-b535-d1c723f38b25)

**Comment by protective1** [comment]
The web is from a monster inside the room.  I have never opened the door to the room.

**Comment by 00-Evan** [comment]
Did you have the swam intelligence challenge enabled, and do you know if any other creature saw you around this time? My immediate suspicion is that this only appears to be caused by seeing the enemy, but is in fact caused by something else.

**Comment by protective1** [comment]
Yes, I had the swarm intelligence challenge enabled.
I can't be sure whether another enemy saw me - I can't see much because the into darkness challenge is also enabled :)

**Comment by protective1** [comment]
Sorry - I should have recorded the seed.  Then you could look at where this is on the map to see if there's a turn to the right up from  my current position from which a monster could have seen me.  
There are no positions where a monster could have seen me from what we can see of the map on the screen, because there are no monsters down/right (I would see them with the eye of newt), and the path up is blocked by the grass.  But again, I can't remember if the path above turned towards the right.

**Comment by 00-Evan** [comment]
I did a little testing and wasn't able to reproduce anything relating to this, I'm going to call this as a mis-report due to swarm intelligence, though feel free to comment on this and I'll re-open if you can provide more evidence.

Keep in mind that with eye of newt enemies will be able to see you before you see them in more open spaces.
