### ISSUE TITLE
Salt cube and 'well fed' turns remaining oddity

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1843]
Hello,

This one is either a minor textual oddity or a minor bug, and may or may not be worth fixing, but when using salt cube +3 the 'well fed' buff turns remaining counter ticks down every other turn, instead of every turn, but the duration then ticks down by 2.

So, for example, it might say "17 turns remaining." Take one step, still says "17 turns." Take another step, now says "15 turns."

**Comment by 00-Evan** [comment]
Yeah this is because the speed of the buff is being affected by the salt cube, but the timer can only update when the buff actually acts. I'm fine with leaving this quirk as-is.
