### ISSUE TITLE
Cannot use any text input on Android

### ISSUE THREAD

**Issue by LeandreBischoff** [00-Evan/shattered-pixel-dungeon#1845]
Hello,

With the recent addition of Adventuring Notes, I was excited to try it out ! However, I discovered that there is a bug that is preventing me from creating one.

When trying to add a Note, I click on the + sign and select a category in the "Add a custom note" popup. I can see briefly that the text input appears, my keyboard pops up and very quickly close itself, and the text input disappears.

I then tried others text input, and it seems that they're all broken. The Notes in the Pantheon doesn't work either.

Here is a screen capture of it :
https://github.com/user-attachments/assets/a2066d0b-6382-41b2-959b-3335cbc105bd

I'm on the last version, 2.5.2, on an Android 14 phone with GBoard as my default keyboard.

**Comment by 00-Evan** [comment]
The keyboard you're using is changing the size of the game screen, which prompts a scene reset. This happens on some devices if the fullscreen setting is enabled in settings.

Unfortunately there's not really anything I can do about this, software keyboardd are not supposed to change the app size and if they do it forces a scene reset.
