### ISSUE TITLE
Something wrong in journal's record

### ISSUE THREAD

**Issue by Ardes-Lc** [00-Evan/shattered-pixel-dungeon#1846]
First is sandals of nature's update not included in journal. I was update it to +10 in a game and no record in it. Is the special update method wasn't written in record code? or caused by transmutation?(I trans it at the end of the game.)
After I test it I found another mistake that is use upgrade scroll on mage's staff will record twice in journal. I guess the reason is upgrade is regarded as acting on both staff and the wand in it.
Attached screenshots.
![Screenshot_20240921_010101](https://github.com/user-attachments/assets/a8c62058-936d-4792-a8c2-ed27b4981036)
![Screenshot_20240921_011903](https://github.com/user-attachments/assets/fc98ae4c-1d2f-4dcf-b5ce-74471bec035a)
![Screenshot_20240921_011907](https://github.com/user-attachments/assets/8534106b-d095-4544-8eb8-2fa47a478dea)
![Screenshot_20240921_011915](https://github.com/user-attachments/assets/785c72f9-916a-45eb-aafe-032586d34725)
![Screenshot_20240921_011921](https://github.com/user-attachments/assets/9032e7a0-cf7c-4f75-a89f-cea7a504d476)

**Comment by Ardes-Lc** [comment]
upgrade,sorry for misspelling😂

**Comment by Ardes-Lc** [comment]
and I found another mistake(may be not?) is upgrade the staff only record the staff but no in the wand inside it. I'm not sure that's a mistake or intended🤔

**Comment by Ardes-Lc** [comment]
And I found another mistake(maybe not?) is upgrade the staff will only record staff but no on the wand inside it. I'm not sure it's mistake or intended🤔

**Comment by 00-Evan** [comment]
It is intended that upgrading the mage's staff only counts as a staff upgrade, and not an upgrade for the wand inside of it.

**Comment by 00-Evan** [comment]
fixed in commit 1bfe1f6060b24b65752ab99de0803445d1078429
