### ISSUE TITLE
Curse of stench does not work

### ISSUE THREAD

**Issue by LordElamak** [00-Evan/shattered-pixel-dungeon#1848]
Hi Evan,
My huntress is equipped with a Leather Armor of Stench, but there's no effect (no gas). Furthermore the curse of stench has not been registered in the equipment list.
See attached screenshots.
Device: Samsung Galaxy A51
OS: Android 13
![SmartSelect_20240922_103810](https://github.com/user-attachments/assets/bd254256-cda0-4790-88a2-d2cf656e8b78)
![SmartSelect_20240922_110458](https://github.com/user-attachments/assets/739cc4cc-46e7-4726-894d-5ee1b54adb96)
![SmartSelect_20240922_110515](https://github.com/user-attachments/assets/cba64901-6eb8-4812-8d81-5c43a38f6d98)
![SmartSelect_20240922_110548](https://github.com/user-attachments/assets/3843d502-b439-46e6-a352-0c5f99d7ec45)

**Comment by 00-Evan** [comment]
The stench effect does not trigger until you get attacked, at which point it has a 1/8 chance to activate.

It is intended that glyphs/enchants/curses do not appear in the catalog if you haven't identified the item they're attached to.

**Comment by LordElamak** [comment]
Ok, thanks for the explanation.
