### ISSUE TITLE
Inconsistent energize values for one Wild Energy and Reclaim Trap vs a stack of either

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#1849]
A single item of Wild Energy and Reclaim Trap returns 2 energy in an alchemy pot, but a stack of 5 of either returns 12. 

I tested converting the whole stack of Reclaim Trap and it indeed returns 12 energy. I tested converting the whole stack of Wild Energy one by one and that gives a total of 10 energy.

![Screenshot_20240922-103821](https://github.com/user-attachments/assets/61ad9264-3a6b-4142-be58-391009cb983e)
![Screenshot_20240922-104057](https://github.com/user-attachments/assets/d7e97019-b2c2-46c4-b258-6df356705ed4)

**Comment by 00-Evan** [comment]
This is intended, Energy can only be given in whole numbers so in cases like this it rounds down if you're only energizing one item from a stack.
