### ISSUE TITLE
[Feature] Explored Tiles

### ISSUE THREAD

**Issue by larssorenson** [00-Evan/shattered-pixel-dungeon#185]
Hello,  
  
As I continue to play the game, I've found myself often wishing there was a mechanic in the game to track what tiles I have explored. The player already has a "Journal" which tracks what special rooms are on what floors, and what certain potions and scrolls are. Why not include the ability to track what tiles have or have not been explored?  
I propose either a meta-feature, one that exists in the menus/journal and possibly be toggled at the player preference, or a new item.  
The new item could be an artefact that only sometimes drops, limiting the influence of it on the game (and keeping it from being too easy) or it could be a consistent drop such as the dew vial or an item that always appears in the first shop.  
  
A third possibility, which would be vastly more involved and I would open a new Issue to detail if you think it's worth discussing, would be to add a fifth class to the game. This class, aptly named Explorer, would have this feature as an innate ability. Edit: I realized that this class might just start with an unique artefact not unlike the cloak of shadows.   
  
Let me know what you think!
  
Thanks,  
Lars

**Comment by 00-Evan** [comment]
I feel like a lot of this concern (I've heard several things about wanting better ways to discover secrets, or to track what's been searched) is coming from the more loose level structures that can exist in the new levelgen. I'm planning on reworking secret rooms fairly soon, which should help with this a bunch, secrets will become more rare but they will also be less crucial to discover.
