### ISSUE TITLE
[Feature Request] Mark notes on unidentified potion and scroll

### ISSUE THREAD

**Issue by sacredsky** [00-Evan/shattered-pixel-dungeon#1850]
Since some players play this game across sessions, information like "this potion maybe a heal potion or this is not a heal potion" on unidentified potions and scrolls are easily forgotten. Hope there is a feature to take notes.

Such as for an unidentified potion there is a button to list all available unknown potions with a check box, the check box loops through [√], [X], [ ] to let the player take notes.

**Comment by TheYsconator** [comment]
Since the latest version it _is_ possible to ake notes! When in a game on version 2.5, you can tap the journal icon (the leftmost icon of the two in the top-right of the screen). On the menu that opens, you can go to the leftmost tab ("Adventuring notes") to take notes.

**Comment by sacredsky** [comment]
Thanks for letting me know! I didn't notice that!
But still, a checkbox-like approach to an item might be easier for marking unidentified purposes.
