### ISSUE TITLE
Left hand enhancement please (tablet layout)

### ISSUE THREAD

**Issue by derei** [00-Evan/shattered-pixel-dungeon#1852]
@00-Evan  Hi, I recall there was another issue/request regarding ui for left handed users. The issue was for a phone layout and it ended up closed as not planned.
However, I am asking you to reconsider the following aspect: on a tablet (landscape mode), the important ui elements (life, messages) appear on the bottom left corner and a left-handed user will effectively cover that area with their hand whilst playing, and thus obstructing it from view. This can be very frustrating at times.

Proposed solution:
1. the left and right panes could be swapped (inventory to the left and life stats+messages to the right).
Or:
2. option for the life stats and messaages to be displayed in the upper-left corner, similarly to mobile interface (but the messages tooo), and therefore free the bottom-left corner of information.

I'd greatly appreciate it if you'd consider the left-handed players. We already have a lot of strugles on a daily basis.... (imagine using an ergonomic scissors with left hand, for example 😆), and speaking in the name of all lefties: we would love to be able to enjoy this game better.

Thank you.

**Comment by 00-Evan** [comment]
Unfortunately doing something like this would require re-writing large amounts of UI code and creating new assets for the flipped UI elements. 

You can still access the mobile UI on tablets from the settings, which then lets you use the various UI layout customizations which are there. the larger UI modes are primarily designed for desktop monitors.

**Comment by derei** [comment]
I understand and is unfortunate. Perhaps in time you may consider the effort to be worth.

The mobile layout only solves the issue in part.

Thank you nonetheless and best wishes!
