### ISSUE TITLE
mind vision reveals hidden keys

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1853]
Just went down to 2nd floor with mind vision active.  Walking near wall reveals hidden golden keys.  This doesn't make sense to me - why are keys being revealed, and why did they only reveal when I walked to their nearest wall?
![Screenshot_20240928-105917](https://github.com/user-attachments/assets/29a9805d-26cd-41ee-b976-342bcc23570d)
![Screenshot_20240928-110007](https://github.com/user-attachments/assets/632207a5-1392-4a43-a936-1fe079c5de68)
![Screenshot_20240928-110016](https://github.com/user-attachments/assets/124adb18-a2e6-4d4b-a411-c09cf4df6211)

**Comment by protective1** [comment]
![Screenshot_20240928-110658](https://github.com/user-attachments/assets/5314c3d3-5d44-4341-8ff0-176e543fae46)

**Comment by protective1** [comment]
Apparently I can see 1 space (plus the wall space)  through walls - it's not just keys.

**Comment by protective1** [comment]
![Screenshot_20240928-114841](https://github.com/user-attachments/assets/73295d4f-6a49-4967-86b0-b93821f10ef9)

**Comment by protective1** [comment]
Apparently this is standard behavior for mind vision.

**Comment by 00-Evan** [comment]
As you mentioned, this is standard intended behaviout for mind vision.
