### ISSUE TITLE
Stone of detect magic

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1854]
This isn't a bug, or issue, as much as an opinion about a change in beta, so feel free to just close without comment. But it seems like removing the stone of disarming takes away a lot of utility. I personally use them at least a few times per run. The detect magic stone is neat, but it seems like its functionality belongs more as an additional way to use a stone of intuition, which would make those actually useful at later levels.

Just my opinion, of course. I love the bomb/explosion changes.

**Comment by 00-Evan** [comment]
There are a few reasons why I decided for stones of detect magic to exist in this form:
- Disarming, while obviously useful, is not a very unique effect. The game is filled with all sorts of different ways to disarm traps, ranging from simply throwing items to other alchemy recipes like storm clouds or aqua brew.
- One of the points of intuition/divination as alternatives to identify is that they deal purely with consumables, that's the main tradeoff compared to using scrolls of ID as they are.
- 'Soft-identifying' items by learning their curse state and whether they are upgraded is almost as good as identifying them fully. Letting something with a quantity of 2 that does this come from scrolls of ID would invalidate ID scrolls as an item completely. Remove Curse is a more powerful effect to begin with, and so the stones have a larger power budget this way.
