### ISSUE TITLE
New v2.5.3 beta bombs cannot break barricade

### ISSUE THREAD

**Issue by ChuiyuWang1** [00-Evan/shattered-pixel-dungeon#1855]
The game was inherited from v2.5.2, dungeon seed VND-BGP-GJT. On floor 7 corpse dust room, I tried using a bomb to open it but failed.

**Comment by 00-Evan** [comment]
Fixed in released version of v2.5.3

**Comment by TheYsconator** [comment]
Is this the fix in commit 2fef96f21caff859ba9322a427aa60d35da7d340 ?
