### ISSUE TITLE
(Minor, Clarity) Chalice of Blood prick and Monk Meditate

### ISSUE THREAD

**Issue by SomeTroglodyte** [00-Evan/shattered-pixel-dungeon#1857]
From game text, it is not immediately clear a Monk's Meditate won't help against Chalice-Prick damage (only buffs that do are Barkskin and Rock Armor - the Meditate damage resistance effect is only coded in Char.attack). Maybe mention in the yellow text that it works only for incoming attacks? Three extra words should fit.

**Comment by 00-Evan** [comment]
It isn't possible to prick the chalice while meditating either way, as the meditation damage resistance does not persist after the hero regains control of their own actions.
