### ISSUE TITLE
qol/bugfix 

### ISSUE THREAD

**Issue by delveticas** [00-Evan/shattered-pixel-dungeon#1858]
when you have only 2 unidentified scrolls left and use stone of intuition on one of them and guess incorrectly it doesnt identify it even though it is 100% obvious which one it is, because of this its impossible to use the scrolls to upgrade the unstable spellbook

i also think the game should identify the last scrolls or potions automatically, but thats maybe a different case

**Comment by 00-Evan** [comment]
I'm afraid this is intended, the game does not automatically identify something for you, even if there are no other candidates.
