### ISSUE TITLE
Furrowed grass won't be trampled by throwing or dropping items when Huntress is on it.

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1860]
![Screenshot_20241003_235436_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/90d4126c-3095-44d7-9c25-4bd691eb4c13)

**Comment by 00-Evan** [comment]
I'm fine with leaving this quirk as-is.
