### ISSUE TITLE
Flashbang's damage is "typeless", not electric

### ISSUE THREAD

**Issue by TrashboxBobylev** [00-Evan/shattered-pixel-dungeon#1862]
The "new" Flashbang bomb is supposed to be electric and deal damage with electricity, but it sends a type object of `Electricity` instead of `Electricity` object, like other electric damage (pylons, tengu's shocker, shocking dart), making Flashbang's damage technically typeless, making it being unaffected by anti-magic effects and deal full damage to shock elemental.

![image](https://github.com/user-attachments/assets/45779415-f38b-4d70-bc0e-982a9170af7e)

**Comment by 00-Evan** [comment]
Fixed in commit e92ed1276ca453279c927ba5a268c0391a9f76d4
