### ISSUE TITLE
The damage display of the bomb

### ISSUE THREAD

**Issue by rtgggggg** [00-Evan/shattered-pixel-dungeon#1863]
Before opening a game, the description of the bomb is 4-12, but after opening a game, it becomes another number
![Screenshot_2024-10-04-13-02-26-36.jpg](https://github.com/user-attachments/assets/cd958a6c-7a5e-421c-be5e-b88beb1cb770)

![Screenshot_2024-10-04-13-02-07-88.jpg](https://github.com/user-attachments/assets/3485aae5-3d6b-4ceb-85bb-9a28d683f1d8)

**Comment by TrashboxBobylev** [comment]
This also might apply to anything, that calls for `Dungeon.hero` in their item description.

**Comment by 00-Evan** [comment]
Fixed in commit 77ea415dc72490698612f2c8f16ac9661ae01061
