### ISSUE TITLE
"Gravity Chaos" cursed wand effect is unused

### ISSUE THREAD

**Issue by TrashboxBobylev** [00-Evan/shattered-pixel-dungeon#1864]
During implementation of last very rare new cursed effect, it was set to 100% rate, but during [commit that fixed that debug thing](https://github.com/00-Evan/shattered-pixel-dungeon/commit/0d5a8dd57c9f8c19a52c12a07f6b8ec81131f0a6), "Gravity Chaos" was never added into list of cursed effects, making it not appear in the final release.

![image](https://github.com/user-attachments/assets/61d437c5-8bc4-4d55-be9f-445d1a140b5e)

**Comment by 00-Evan** [comment]
Fixed in commit 2e69f141182bfdaa3573bdfbd68a348c02ae40ff
