### ISSUE TITLE
tengu invisible 

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1865]
I have a ring of haste.  There are multiple turns where tengu is invisible.  Is this supposed to happen?
![Screenshot_20241003-185809](https://github.com/user-attachments/assets/cb3693cb-ceb8-496c-9269-90e00d715cea)

**Comment by 00-Evan** [comment]
It looks like Tengu is just outside of your FOV here, is he in the bottom right in this picture?

**Comment by protective1** [comment]
That's a good point - probably he was just it of my vision.  It happened a lot during this fight and I thought I was getting bad timing with the ring of haste and some kind of teleport delay.
