### ISSUE TITLE
Gnoll Geomancer fight activated early with mind vision

### ISSUE THREAD

**Issue by rpdelaney** [00-Evan/shattered-pixel-dungeon#1867]
Reproduction:

1. Be in geomancer cave
2. Drink potion of mind vision
3. Read scroll of terror

When in the Geomancer's room, he will immediately start using his abilities and attacking the player. When the player mines through the rocks and attacks the Geomancer, the message "Make sure you're ready before you continue!" is printed, although the fight has already begun.

**Comment by rpdelaney** [comment]
I did not test if other effects (retribution, etc) would also do this.

**Comment by 00-Evan** [comment]
Fixed in commit 8a143658fba9ed9bd2b8fd3f137ab3e8b847b1aa
