### ISSUE TITLE
When the crazy thief steal a honey pot and get away with it the bee defends nothing

### ISSUE THREAD

**Issue by Surhan-code** [00-Evan/shattered-pixel-dungeon#1869]
The bee defends the place where the thief stole from you , and when that happend to me another thief came and stole another honey pot but he didn't try to escape with it he just continued fighting

**Comment by Surhan-code** [comment]
I have a video but it's size is not allowed

**Comment by 00-Evan** [comment]
If you can send the video to me I can double check, but that sounds about right. When the thief escapes the bee has nowhere to go for and so would default to the last location the pot was at, which was where it was stolen.
