### ISSUE TITLE
Ambicious Imp blocks way from the fall-down well room.

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#187]
After falling down into the well room and unlocking the door, the Imp is on the way, forcing to jump down again.

<img src="https://user-images.githubusercontent.com/173219/27478613-05b865fa-5819-11e7-92c6-d7d6fe2b7f57.jpeg" width="400">

**Comment by 00-Evan** [comment]
Well that's tremendously unlucky.

I'll adjust the way the imp can spawn in the next update to prevent this.

**Comment by 00-Evan** [comment]
fixed in commit d407144e28f8862ecb554a1d53e7a5f401924961
