### ISSUE TITLE
Flatpak Closes Shortly After Launching

### ISSUE THREAD

**Issue by The0zymandias** [00-Evan/shattered-pixel-dungeon#1871]
Hello, 

I am running the flatpak version 2.5.1 (the newest version on Flathub as I write this) of Shattered Pixel Dungeon on linux (specifically Debian 12 with kernel 6.1.0-26 and KDE Plasma 5.27.5) and the application would close itself shortly after launching.  I had to change the permission with Flatseal to allow Shattered Pixel Dungeon to run in the background to fix the problem, but I was given no indication to do this.

**Comment by 00-Evan** [comment]
Sorry but I don't provide support for unofficial distributions of the game. Please contact the maintainer of that release,
