### ISSUE TITLE
Gladiator can't jump to the enemies in some cases.

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1877]
With "Enhanced Combo" +3, Gladiator still can't jump to the enemies, just like the cases in the pictures below. 

![IMG_20241016_191544](https://github.com/user-attachments/assets/3d372b78-3de3-4337-8cc2-782a5a100b7b)
![IMG_20241016_191555](https://github.com/user-attachments/assets/779ac603-b38c-4136-b556-a9a3829039bd)

But Assassin can strike the enemies if cloaked enough in these cases. Maybe it's an imbalance.

**Comment by 00-Evan** [comment]
Thanks for the report, but this is intended. The jump is less permissive than the Rogue's blink, it cannot go around walls or place you over hazards like chasms.

**Comment by koisikawa** [comment]
At least in the first picture, all the Gladiator needs to do to get close to the enemy is take a step forward, but he can't. It seems a bit silly anyway.😂

Perhaps it would be better to allow players to freely choose the landing point of the jump, whose legality would be decided by determining whether there is an enemy on the jumping path, whether the jump will be blocked by the something, whether the actual landing point is safe and so on.

It's just like using throwing weapons, which may make the jump more flexible but not excessively permissive.
