### ISSUE TITLE
Sometimes the enemy that suffered physical damage doesn't try to find the hero.

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1881]
This often occurs when the enemy is attacked by throwing weapons after it fails to track the hero. This had happened before v2.5 as well, but now it happens rather frequently.

**Comment by 00-Evan** [comment]
Can you be more specific about the behavior your observing? By 'try to find the hero' do you mean move to the position they were attacked from? What does the enemy do instead that appears to be incorrect? A specific example, possibly with video, would also be helpful.

**Comment by koisikawa** [comment]
https://github.com/user-attachments/assets/f04d9dd0-8af1-4e60-a046-b8f0aa55dc8b


https://github.com/user-attachments/assets/9698bf1d-2b95-462e-ae80-83b10f076359

Here are the videos for answering the questions.

In the first video, when attacked by a throwing weapon, the fist goes left instead of going to the hero. In the second video, the fist is blind, and it does the same.

**Comment by 00-Evan** [comment]
One of your videos does not work even when downloaded separately.

It's hard to tell exactly what's happening from such a minimal example, but it's possible the first already had you set as its target and isn't finished moving toward a previous position it thought you were at. Getting shot by a ranged attack does not immediately override the current target destination in all cases.

**Comment by koisikawa** [comment]
The content of the other video is that the fist still doesn't go to the hero even when attacked by whip, the melee attack.

As for whether the fist tries to head towards the previous target, I'm not sure. Since the appearance of the fist, it has never seen the hero. It was only attacked several times in the air of paralytic gas before its blink. And then, this situation happened. Will the attacks make the fist aware of where the hero is?

**Comment by 00-Evan** [comment]
Currently attacks only draw aggro if the character didn't already have a target. The fist is probably already aggroed onto the hero and so is not having it's target position updated.

I'll consider making the functionality more robust, but for now this is intended.

**Comment by koisikawa** [comment]
That's right. I even accidentally discovered more such situations today and found it difficult to determine whether the enemy is wandering or heading towards a target. This functionality really needs to be adjusted.
