### ISSUE TITLE
Black screen on launch when running on igpu (AMD Radeon RX Vega 8) 

### ISSUE THREAD

**Issue by wiwestor** [00-Evan/shattered-pixel-dungeon#1883]
Laptop automatically assigns igpu to run this game which renders nothing except in game cursor
Changing to discrete nvidia graphics card makes everything render properly
![Shattered_Pixel_Dungeon_xsLsNZBkbS](https://github.com/user-attachments/assets/e8422f2d-8e03-473c-840f-3dc226bfd6d6)

**Comment by wiwestor** [comment]
It appears that the problem is caused be image correction feature that increases image sharpness from amd's control pannel , turning it off fixes the issue

**Comment by 00-Evan** [comment]
Glad to hear that you were able to find a fix! Unfortunately Shattered has no control over which GPU is selected to play it (it is a very lightweight game so using the iGPU does make some sense), nor does it have any way to override any sort of image enhancement feature. Closing this as there's nothing to do on my end.
