### ISSUE TITLE
Add a targetable last-seen ghost of enemies when losing sight (breaking LOS, mind's eye expiring etc)

### ISSUE THREAD

**Issue by rando-username** [00-Evan/shattered-pixel-dungeon#1885]
As huntress, sometimes you can encounter enemies, and choose to reapproach in a ranged way to get surprise attacks. Such attacks need to be manually aimed since the target is no longer visible. 

A targetable last-seen location of the enemy that fades after X turns would be useful in these situations. 

Would be applicable in any kind of targeting scenario after losing sight of the enemy.

**Comment by 00-Evan** [comment]
I'm afraid It's intended that autotargeting only works for enemies that you can see. being able to manually target enemies outside of FOV is fine, but I'd rather not have the game do it for you.

**Comment by rando-username** [comment]
I do think there's a bit of nuance seeing as you'd have to see the target first and not have the benefit of predicting its movement, but I get the motivation. Thanks for considering it anyways.
