### ISSUE TITLE
Gravestone not dropping items when Silver Supporter

### ISSUE THREAD

**Issue by pdaup** [00-Evan/shattered-pixel-dungeon#1888]
Gravestone (hero remains) only drop class specific item (seal shards etc.) - not other items from the dead hero's inventory. This started happening after becoming a Silver Supporter.

**Comment by 00-Evan** [comment]
Do you have custom seeds or challenges enabled? Both of these prevent remains from containing items from previous runs.

**Comment by pdaup** [comment]
Yes, challenges enabled. Did not know this, thanks!
