### ISSUE TITLE
[v2.5.4] Heavy lag on Android

### ISSUE THREAD

**Issue by timothee-muller** [00-Evan/shattered-pixel-dungeon#1889]
**Device:** Volla Phone X23
**OS:** VollaOS (based on Android 13)

**Issue**
I get heavy lag/freezes almost all the time. The frame rate does not go above 5, so the game is unplayable in this state.

**Fix**
Muting the game's music fixes the issue instantly. Unmuting it at any point causes an immediate frame drop.

I wonder if this may have been caused by my specific android ROM (which also replaced Google services with microG)

**Comment by 00-Evan** [comment]
Unfortunately I can't really offer support for issues encountered with 3rd party ROMs. Shattered uses the standard Android media playback engine, and the soundtrack files are .ogg to save on storage space. Presumable VollaOS has some trouble with OGG decode/playback. Other ROMs like lineageOS has been reported with issues relating to OGG files in the past.

**Comment by timothee-muller** [comment]
Thank you for the quick reply and the explanation. I'm fine with playing the game with no music. I mainly opened the issue to share the fix with other users of 3rd party ROMs. If they don't mind missing out on the music as well.
