### ISSUE TITLE
(bug + workaround) Tengu killing ghost causes player to freeze? (v0.6.1)

### ISSUE THREAD

**Issue by draco123456ftw** [00-Evan/shattered-pixel-dungeon#189]
When Tengu killed my ghost partner in the first Boss stage my players character froze in a running animation and wouldn't let me move or attack

The problem was solved easily by quitting to make menu and continuing the game

**Comment by 00-Evan** [comment]
Did Tengu kill the ghost with a melee attack or a ranged attack?

**Comment by draco123456ftw** [comment]
Cannot remember, sorry

**Comment by 00-Evan** [comment]
tested with both melee and ranged attacks, can't reproduce.
