### ISSUE TITLE
cursed wand crash

### ISSUE THREAD

**Issue by delveticas** [00-Evan/shattered-pixel-dungeon#1890]
![Screenshot_2024-11-02-10-27-43-959_com shatteredpixel shatteredpixeldungeon](https://github.com/user-attachments/assets/0bd5fb88-e44d-4c5e-9fe7-ce758dbe0534)

**Comment by TheYsconator** [comment]
Intended; your progress is saved.

See also: #1614, #1748, #1810 and probably some more.

**Comment by 00-Evan** [comment]
As mentioned, this is intended, it's an easter egg.
