### ISSUE TITLE
frustration with blacksmith 

### ISSUE THREAD

**Issue by delveticas** [00-Evan/shattered-pixel-dungeon#1891]
blacksmith's items feel so inconsistent and random, its so often that i get worse items from him than i get from sad ghost quests, which is incredibly frustrating considering how much effort it takes to complete his quest. maybe its a good idea to either nerf sad ghost's loot or make blacksmith's more consistent

**Comment by 00-Evan** [comment]
Afraid I have no plans to further buff the smith rewards. You get an additional option, things are much higher tier, and the outright chance of getting upgraded gear is notably higher than from the sad ghost. You can also get an extra rewards, such as an extra upgrade, if you have the full 3000 points.
