### ISSUE TITLE
Stacked scrolls left on the ground between fight 1 and 2 of Tengu disappear 

### ISSUE THREAD

**Issue by Kemipso** [00-Evan/shattered-pixel-dungeon#1892]
Hello,

If leaving stacks of scrolls on the same tile in the corridor before entering the second part of the Tengu fight (where he generates incendiary clouds), all scrolls except for one stacks will disappear after the fight ends.

Steps to reproduce, on android v2.5.4:
1. Reach floor 10, beat the boss (1st stage)
2. In the corridor before the second part of the battle, drop stacked scrolls on top of each others. In my specific case:
> 2x Scroll of remove curse
> 4x Scroll of recharge 
> 1x Scroll of teleportation
3. Complete the second part of the battle successfully.
4. Only 1 scroll is left (in my case the scroll of teleportation)

Unfortunately, I do not know if the problem is "a stack of identical items would disappear", or if it is "multiple stacks of different items all on the same floor tile would disappear, except for the last one".

Please let me know if something is unclear, or of course if this is somehow intended (nothing seems to suggest it is, but this games keep surprising le ;-)

Thanks a lot for your game!

Bests,
Hugo

**Comment by 00-Evan** [comment]
I'm afraid I'm not able to reproduce this. Testing with your provided steps results in the correct quantities of scrolls appearing in tengu's arena after the fight.

It's worth noting though that if you did drop the scrolls just before the arena, they will actually carry into the arena with you (as they're still on valid tiles after the map swap). Do you think it's possible that this occurred, and you didn't notice the scrolls getting destroyed on the group by Tengu's fire ability?

Thanks for the kind words!
