### ISSUE TITLE
share doesn't

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1893]

**Comment by protective1** [comment]
Shard of oblivion says, "for each unidentified you have equipped or recently used".  I had recently used unidentified wand, so shard was active about halfway.  I used an unidentified scroll (mirror image), but the shard meter did not replenish.
![Screenshot_20241102-214535](https://github.com/user-attachments/assets/729feb3c-5dd4-4cbc-9f80-ea28f93d666d)
![Screenshot_20241102-214540](https://github.com/user-attachments/assets/2aa79ce1-e7bd-480d-aea7-7a93e435013e)
![Screenshot_20241102-214545](https://github.com/user-attachments/assets/f7c9cce1-8365-4e1b-a405-46ebc785b973)
![Screenshot_20241102-214552](https://github.com/user-attachments/assets/79f5586f-6c1d-4b97-a8da-b609712a2ea1)
![Screenshot_20241102-214718](https://github.com/user-attachments/assets/8eb58d19-b008-41b0-b61d-3c8d5aab9059)
![Screenshot_20241102-214725](https://github.com/user-attachments/assets/c49197e1-b8e8-4761-9881-4e71d04bd156)

**Comment by 00-Evan** [comment]
That is intended, the shard of oblivion only works with equipment.
