### ISSUE TITLE
Blacksmith upgrade option does not show the new UI

### ISSUE THREAD

**Issue by Kemipso** [00-Evan/shattered-pixel-dungeon#1894]
Hello,

The "Upgrade" option of the blacksmith instantly upgrades whichever item you select, instead of first showing a preview of what the upgrade result would look like.

It's a bit disconcerting, as one would expect the new UI (made for scrolls) to show the predicted outcome.

Steps to reproduce, on Android v2.5.4:
1. Talk to the blacksmith, located somewhere between floor 12-14
2. Select Upgrade, the inventory opens
3. Select an upgradable item, such as a ring of evasion +0
4. The ring of evasion upgrades to +1 instantly without showing the upgrade UI

Bests,
Hugo

**Comment by 00-Evan** [comment]
This is intended, the upgrade preview window is used when consuming items like scrolls of upgrade or magical infusion, it does not appear for every possible upgrade effect in the game. It also isn't used for blacksmith reforging, for example.
