### ISSUE TITLE
Why doesn't scroll of siren's song cleanse the Amok debuff?

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#1895]
The main time this would come up is with the Spellbook. I once used a scroll of rage, and then I tried to use a Scroll of Sirens Song from it, and was taken off guard by the fact that the amok debuff wasn't cleared and thus the enthralled enemy immediately attacked me.

**Comment by 00-Evan** [comment]
Amok and enthrall are not meant to be mutually exclusive.
