### ISSUE TITLE
During the time freeze, throwing the aqua brew still causes water release.

### ISSUE THREAD

**Issue by koisikawa** [00-Evan/shattered-pixel-dungeon#1897]
I find that most (maybe all) of the thrown potions don't take effect immediately before the end of the time freeze. Is it reasonable for the aqua brew to be an exception?

**Comment by 00-Evan** [comment]
It will vary based on the specific potion effect. Most potions don't act directly themselves but instead spawn a gas or other area effect which then acts. Aqua Brew spawns a direct effect, which means that it occurs immediately even with time freeze. I don't intent to change this.
