### ISSUE TITLE
touch control lost if window opens while zooming

### ISSUE THREAD

**Issue by 00-Evan** [00-Evan/shattered-pixel-dungeon#19]
All ability to move within the game is lost if a window is opened while the player is zooming their screen. Returning to the main menu and loading resolves this. Easiest to reproduce with tip signs.

**Comment by Sarius997** [comment]
@watabou this also happens in pixel dungeon

**Comment by 00-Evan** [comment]
issue has been fixed indev, will close this ticket with a reference to the commit when the source for 0.2.4 is released.

**Comment by 00-Evan** [comment]
fixed in commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/f587e7e13e580a88ffcaf755428d0e578f7824d3
