### ISSUE TITLE
Item catalog doesn't show newly discovered item after item transformation

### ISSUE THREAD

**Issue by erikhuizinga** [00-Evan/shattered-pixel-dungeon#190]
After I transformed a wand using a transformation well (or whatever I should call it), I got a new and never before discovered wand. My item catalog didn't show the wand until after my game ended and I started a new game. I believe this isn't the intended behaviour of the catalog; instead, it should have shown the newly discovered item immediately.

I can't easily reproduce this bug, but it doesn't seem too difficult to reproduce for the developer.

**Comment by 00-Evan** [comment]
There are a couple hiccups with the new item catalog that I need to address. Another one is items being IDed on death.

**Comment by 00-Evan** [comment]
fixed in commit d274dc03202964366acaedc4ec277880754cc8cf
