### ISSUE TITLE
Under certain conditions, the enemy can see the hero, but he can't see them

### ISSUE THREAD

**Issue by j123123** [00-Evan/shattered-pixel-dungeon#1900]
There is an enemy here, I don’t see him, he sees and can attack:![scr1](https://github.com/user-attachments/assets/ddcc4bc3-54ab-4018-a4a2-961f08fe6f48)

If I take that position, the previous position behind the grass will be visible.
![scr2](https://github.com/user-attachments/assets/de1c82c1-953e-470e-8dbf-9ff64b150ac9)

**Comment by j123123** [comment]
I'm not sure if this is a bug or intended. But such asymmetry of the field of vision is not very good in my opinion

**Comment by 00-Evan** [comment]
This is in fact intended. Shattered Pixel Dungeon uses recursive shadow-casting, which is not symmetrical https://www.roguebasin.com/index.php?title=FOV_using_recursive_shadowcasting
