### ISSUE TITLE
Suggestion：heroes should avoid to trampled plants(or just negative plants).

### ISSUE THREAD

**Issue by Ardes-Lc** [00-Evan/shattered-pixel-dungeon#1904]
imagine that: you see a chest and prepare to open it, then you click it and watching hero walking to a sorrowmoss, and boom, you lost half of life. Sometimes you even have to use healing, even though that's unnecessary if hero doesn't step on it. I know roguelike should have some unexpected and unpredictable event, but it is absolutely not accord with this weird wayfinding. It is... not the operational issues, not the game features, just something wrong on the underlying logic. It's really frustrating, just like someone knocked you heavily and you just do nothing. on the other hand, someone noticed a danger plant and just step it is kinda weird right. XD
So I send this suggestion and hope you think about this. spd is a good game and I wish it become better. So that's all.

——from a player who step on 2 sorrowmoss in a floor and feel angry and funny

**Comment by 00-Evan** [comment]
Unfortunately this isn't as simple as you might like. Setting plants to avoid would mean that both the player and enemies would avoid all plants. There is not currently functionality for something to be considered avoidable for the hero but not enemies.

I'd rather just leave things as-is than implement that.
