### ISSUE TITLE
Can't take Screenshot?

### ISSUE THREAD

**Issue by Tokiki17** [00-Evan/shattered-pixel-dungeon#1907]
Taking screenshots isn't allowed by the app or your organization
But other apps on my phone can take screenshot normally

**Comment by Ablackdog** [comment]
![0678AA660DCBE027B5C4107BDD63D61C](https://github.com/user-attachments/assets/4b949be3-0146-48ea-a03c-05f23def4ae8)
![D2682BCB4A023EDDE0D9700BCE7131C2](https://github.com/user-attachments/assets/9a3d4923-3d9f-4761-ba0d-ef87ef058cf1)

**Comment by 00-Evan** [comment]
Afraid I have no idea why this would happen. Shattered Pixel Dungeon does nothing to try and disallow screenshots.
