### ISSUE TITLE
Missing crystal keys for choice room

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1909]
![Screenshot_20241128_193342](https://github.com/user-attachments/assets/7cdc7eba-ad86-4b21-95cc-46f637396f74)
Seed: TSP-MWV-NCK
Version: 2.5.4
Floor 9 is missing two crystal keys. I only found one of three.

**Comment by 00-Evan** [comment]
From looking at your screenshot it seems you've found and used three keys, which is the correct amount for that type of room.

**Comment by spixi** [comment]
@00-Evan Oh thank you. You are absolutely right. 3 keys is correct. I just saw that I missed the two rooms in the middle. I had no place in my inventory, so I turned back after the boss and just forgot that I already opened them.
