### ISSUE TITLE
Copy to Clipboard button for seed in Games in Progress dialog

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1911]
The custom seed input dialog when starting a new run already comes with clipboard support. However the Games in Progress dialog has no Copy to Clipboard button.

It would be useful if the seed could be copied from the Games in Progress dialog to the clipboard.

**Comment by 00-Evan** [comment]
It's intended to not allow seed copying from games in progress, you can't start a seeded run using the same seed as an active run.
