### ISSUE TITLE
Projecting enchantment does not work on Gnoll Geomancer

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#1915]
I have Staff of Disintergration, which has build-in projecting because I am a Battlemage. Trying to attack the Gnoll Geomancer from 1-tile away, just ends up walking up to it. I don't know if that is intended behavior, but my intuition told me that I should be able to hit him, because I understand that he accepts only melee attacks.

If this is a bug and that is the case, I haven't tested it with an actual projecting enchantment on a weapon and/or melee weapons that have greater than 1-tile attack range.

Edit: What adds to my confusion is that the attack indication appears when standing 1-tile away; I count the tile where I am standing as zero.

**Comment by 00-Evan** [comment]
This is correct if you're attempting to attack the geomancer while it is encased in rock. It's not that you're forced to use melee, you're forced to attack with the pickaxe specifically, in order to break through the rock and start damaging normally.
