### ISSUE TITLE
Upgrade scrolls not applied correctly to wand leveled up with arcane resin

### ISSUE THREAD

**Issue by kdaviper** [00-Evan/shattered-pixel-dungeon#1916]
Applied 5 scrolls of upgrade to a level 3 wand of overgrowth, ended up with only a level 5 wand instead of a level 8 wand. Wand was obtained as level 0, and upgraded to 3 using arcane resin

**Comment by Sarius997** [comment]
This is intentional as the arcane resin description says the following at the end: "resin upgrades are overridden by other upgrade sources however (such as scrolls of upgrade)"

**Comment by 00-Evan** [comment]
As mentioned above, this is intended. From the description of arcane resin: "Resin upgrades are overridden by other upgrade sources however (such as scrolls of upgrade), and do not apply when imbuing a wand into the Mage's staff."
