### ISSUE TITLE
Bug: ankh can respawn player without access to pack

### ISSUE THREAD

**Issue by flytape8490** [00-Evan/shattered-pixel-dungeon#1917]
When the player dies and is resurrected by the ankh, it is possible to be spawned behind a locked door with no way back to your pack (I already checked all walls, there's no other hidden paths) 

![Screenshot_20241204_214100](https://github.com/user-attachments/assets/fbc9dbf2-58d2-4aa5-aa96-a25851f661a7)

**Comment by 00-Evan** [comment]
You're playing on a secrets floor type here, which can hide some normal doors. You're definitely still able to make it back, you need to search for a hidden door.
