### ISSUE TITLE
Chaotic Censor Issue

### ISSUE THREAD

**Issue by TheRanenEmpire** [00-Evan/shattered-pixel-dungeon#1919]
I had just gotten past stage 1 Tengu and decided to sleep. The Chaotic Censor activated during this time and gave me around 2 billion turns of vertigo and kept cycling through turns, without any change. I was unable to to access my inventory or stop it at all.

**Comment by 00-Evan** [comment]
Thanks for the report, but this is a duplciate of #1868 

Regardless, can you let me know your device model so I can see if I recieved any automated logs about this error?

**Comment by TheRanenEmpire** [comment]
Oh okay, sorry about the duplication, I hadn't read the previous reports. I'm currently using a Huawei P30 lite
