### ISSUE TITLE
Wishlist item

### ISSUE THREAD

**Issue by rayksland** [00-Evan/shattered-pixel-dungeon#192]
Waiting to regain health takes longer at higher levels. This is inconvenient and doesn't make sense. A higher order being shouldn't be less resilient than a lower simply because it has higher health capacity. I suggest that the wait time should be based on percentages.

**Comment by 00-Evan** [comment]
Health regen works this way specifically to make it less valuable in the later stages of the game. At that point you are expected to rely more on healing items.

**Comment by rayksland** [comment]
But every once in a while, there are none. So fighting for a corner of peaceful regeneration should still be an option.On Aug 21, 2017 10:14 AM, Evan Debenham <notifications@github.com> wrote:Health regen works this way specifically to make it less valuable in the later stages of the game. At that point you are expected to rely more on healing items.

**Comment by 00-Evan** [comment]
It is an option, but one that gets increasingly less viable as the game progresses due to hunger. Regarding enemies interrupting you though, I do plan to allow for a few more parts of the dungeon which don't have enemies randomly walking into them.

**Comment by rayksland** [comment]
With piranhas being easier to kill (extra reach weapons like spears, and ethereal chains to pull them onto dry floor) I've starved less often. I just think that storywise it makes good sense for a seasoned adventurer to know when to rest and be able to benefit from it.On Aug 22, 2017 8:58 AM, Evan Debenham <notifications@github.com> wrote:It is an option, but one that gets increasingly less viable as the game progresses due to hunger. Regarding enemies interrupting you though, I do plan to allow for a few more parts of the dungeon which don't have enemies randomly walking into them.
