### ISSUE TITLE
RFE, mobile UI: make some area not tappable

### ISSUE THREAD

**Issue by llevrel** [00-Evan/shattered-pixel-dungeon#1921]
Hi,

Sorry for the clumsy title, I've been struggling with it ^^'

On mobile at least (I don't use desktop), tapping on any part of the screen will do something. When this is not a clickable icon, the click will "land" on the map, resulting in doing a move or firing.

Some icons are very small, like the tiny trophy on top (to access challenges) or the buff/debuff icons for the hero or bosses. The window asking to aim (when throwing, shooting, zapping) is "tap transparent" as well. So if you miss the spot, you end up suddenly walking or firing to an undesirable or nonsensical place.

Maybe the whole upper and bottom borders could be made insensitive to "map tapping"?

**Comment by 00-Evan** [comment]
Almost all tappable areas in the main UI already have a tap region that's larger than their appearance, specifically to reduce mistaps. You can also access buff information from the hero info window, or challenge information from the game menu, so you're never forced to tap on those smaller icons, they're mostly there for quick convenience.
