### ISSUE TITLE
[Feature Request] Add Male and Female versions for all the in game heros.

### ISSUE THREAD

**Issue by v3xed-v0id** [00-Evan/shattered-pixel-dungeon#1925]
This is purely a cosmetic thing, but i would love it if both Male and Female versions for all the heros existed, Thank you.

**Comment by 00-Evan** [comment]
I agree it would be nice to have more cast diversity, this is something I'd like to continue to improve (probably through NPCs at the moment, not even more heroes), but for the heroes themselves I'd prefer for them to each have a singular visual identity, so I'm not planning on let the players customize appearance, gender, etc.
