### ISSUE TITLE
Advice on mage balance

### ISSUE THREAD

**Issue by laamfun** [00-Evan/shattered-pixel-dungeon#1927]
I think the mage is too weak in the early stage.,I don't know if other players have this feeling.,My suggestion is how about the mage's own cloth armor at the beginning with electric potential enchantment.,I'm using translation software to process this text.,There may be some ambiguity.,You can reply to ask me further.

**Comment by laamfun** [comment]
I would like to thank the maintainers for their hard work, thank you very much, this game is amazing

**Comment by 00-Evan** [comment]
Thanks for the suggestion! I regularly run analytics numbers on the various heroes, and all of them are similarly powerful in the early stages of the game currently. The mage in particular was pretty strong during some of the v0.9 updates, as he benefited quite a bit from early talents. I scaled back the melee damage on his staff to compensate.
