### ISSUE TITLE
Trap set off by nothing?

### ISSUE THREAD

**Issue by bluestmango** [00-Evan/shattered-pixel-dungeon#1928]
![Screenshot_20241213_193229.jpg](https://github.com/user-attachments/assets/549789fb-f4b1-485b-b291-d38a5b88b810)

The hammer in that doorway killed a spectral necromancer, then something immediately set off a blazing trap and burned the scroll. 

I can't think of anything that could have triggered it, I wasn't using a RoW or lucky weapon

**Comment by 00-Evan** [comment]
Spectral necromancers drop an extra scroll of remove curse, which lands in a random cell adjacent to them. That's what set off the trap here.
