### ISSUE TITLE
[Feature request] Some form of a cheat code to unlock seeded runs / challenges / characters early

### ISSUE THREAD

**Issue by scarecat** [00-Evan/shattered-pixel-dungeon#1929]
While i think its good that those features are locked until the player gets familiar with the game, it gets very tedious to have to do this for every new save game (or every new device). Setting up multiple player tournaments also wouldn't require them to have to beat the game prior to playing on a custom seed.

Naturally I don't think such a feature should be encouraged, nor shown as an available option anywhere normally.

**Comment by scarecat** [comment]
Update: I realised i can manually edit badges.dat to add a VICTORY badge, which does exactly what I wanted to do, so this isn't really needed.

**Comment by scarecat** [comment]
Actually that won't work on Android outside of Google Play,  so maybe it could be up for discussion.

**Comment by 00-Evan** [comment]
Sorry but I don't intend to add any cheat or unlock codes to Shattered.

**Comment by scarecat** [comment]
> Sorry but I don't intend to add any cheat or unlock codes to Shattered.

Fair enough
