### ISSUE TITLE
Cleric's Holy Tome is still usable when affected by the Blinded debuff

### ISSUE THREAD

**Issue by mgr01** [00-Evan/shattered-pixel-dungeon#1932]
The hero needs to read the tome to cast spells, right? Similarly to how the Unstable Spellbook cannot be used while blinded.

**Comment by 00-Evan** [comment]
The tome contains holy scriptures and such but for now I've decided the Cleric doesn't need to actually read it to cast their spells. I've erred on that side so that blind doesn't shut the entire class off.
