### ISSUE TITLE
Duplicated artifact

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#1935]
I have found the Chalice of Blood twice this run.

![Screenshot_20241222-105721](https://github.com/user-attachments/assets/df888e28-1e43-4cc3-a576-6592da394e68)

I'm not sure if it's a bug, but it's the first time I find the same artifact twice in many years of playing.

v.3.0.0-BETA-1.0

QTF-WND-MWH

**Comment by 00-Evan** [comment]
This run was originally from before v3.0.0. Thanks to the new artifact, the internal list of spawned vs. not spawned artifacts is reset, leading to the possibility for duplicate artifacts in that run in particular.
