### ISSUE TITLE
(Suggestion)Publishing the app on f-droid

### ISSUE THREAD

**Issue by Dantoza** [00-Evan/shattered-pixel-dungeon#1936]
Hello, would it be possible to get SPD on f-droid or IzzyOnDroid?

**Comment by 00-Evan** [comment]
Shattered is already unofficial available on F-Droid: https://f-droid.org/packages/com.shatteredpixel.shatteredpixeldungeon/

I would recommend getting the game from github instead though (use obtanium if you want any external program to manage updates, etc.)
