### ISSUE TITLE
Option to make camera not move when selecting enemies

### ISSUE THREAD

**Issue by Anonymous3-a** [00-Evan/shattered-pixel-dungeon#1938]
When using TAB to select enemies, the camera always moves to the current position of said enemy. I would prefer to either have it folow the enemy, or not move the camera. It's still easy to tell what the selected enemy is, because the health bar is a little thicker. It would be nice to have an option for this.

**Comment by 00-Evan** [comment]
Sorry, I'm afraid I don't plan to add a specific setting for this. I will consider making the 'camera follow intensity' setting also apply to enemy targeting though.
