### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by Anonymous3-a** [00-Evan/shattered-pixel-dungeon#1939]
The leveling up menu thing (don't remember the name) says "Reach level 12 and use the item from the second boss to unlock more talents." but the second boss is on level 10.
![image](https://github.com/user-attachments/assets/f54b8117-14b0-482d-8ebb-e3a1e9225788)

**Comment by TheYsconator** [comment]
There's a difference between 'floor' and 'level'. You have to reach level 12, and floor 10 (and use the item you get from the boss).

**Comment by Anonymous3-a** [comment]
Oh, whoops. Sorry.
