### ISSUE TITLE
Beta releases are violating GPLv3

### ISSUE THREAD

**Issue by Anonymous3-a** [00-Evan/shattered-pixel-dungeon#1940]
Release v3.0.0-BETA-1.1 says:
> <b>Note that this is a beta release, and may be missing features and polish, or contain bugs.</b> Additionally, there is no public source code for beta releases.

This violates the terms of the GNU GPL v3, which this repository is licensed under.

EDIT: Why is the source code not public for beta releases?

**Comment by 00-Evan** [comment]
Shattered's source code is not public for beta releases to prevent other developers from taking half finished features from the beta and implementing it into public releases before I do. This has happened in the past and led to users who didn't know any better accusing me of copying.

I've explained this in more detail previously in #1237
