### ISSUE TITLE
No key for statue room

### ISSUE THREAD

**Issue by DPlFnAz5J91kerf** [00-Evan/shattered-pixel-dungeon#1941]
I used magic map to find hidden rooms.
ShatteredPD-v3.0.0-BETA-1.1-Android.apk

[![map.jpg](https://i.ibb.co/23zwdVr/map.jpg)](https://i.ibb.co/v4NbkyW/map.jpg)

[![Screenshot_20241225-205616.jpg](https://i.ibb.co/997d0Kz/Screenshot-20241225-205616.jpg)](https://i.ibb.co/d0RHvC1/Screenshot-20241225-205616.jpg)

**Comment by 00-Evan** [comment]
When testing the floor generation, a key spawns on the tile one above and to the right of that pitfall trap. It's likely your key fell down to the next floor when the trap triggered.
