### ISSUE TITLE
Horn of Plenty abusing food talents

### ISSUE THREAD

**Issue by CaptainCrusher** [00-Evan/shattered-pixel-dungeon#1945]
When using Horn of Plenty, you can snack many times instead of eating in order to trigger your meal talents. For most hero's this is fine, but with cleric and duelist it allows your weapon and holy tome abilities to be used on every single enemy. Horn of Plenty is far too easy to upgrade to allow these sort of shenanigans.

**Comment by 00-Evan** [comment]
For the moment at least this behavior is intended. Other classes can also use the horn in this way for lots of wand or artifact charges. I do keep an eye on balancing and will tone the talent down for the Cleric if needed.
