### ISSUE TITLE
Cleric is too good in the sewers and prison

### ISSUE THREAD

**Issue by CaptainCrusher** [00-Evan/shattered-pixel-dungeon#1946]
Cleric's ability to deal five extra damage and a guaranteed hit is too powerful in the sewers. I have literally no trouble getting through the sewers and prison when I can one tap half the enemies I come to. After the sewers and prison, cleric seems fairly well balanced because the ability doesn't scale very well.

**Comment by 00-Evan** [comment]
I plan to make balance adjustments based on Analytics data once more of that comes in. Please use issues to report technical problems with the game, not for balance suggestions.
