### ISSUE TITLE
Cursed Infusion - Suggestion 

### ISSUE THREAD

**Issue by jagprog7** [00-Evan/shattered-pixel-dungeon#1948]
Typically I reroll cursed infusion until I get a suitably weak curse (e.g. dazzling). With 4 rolls given from the recipe, there's a high likelihood for this. This is stale, because there isn't much variety.

I suggest the following:
 - have more detrimental curses give +2
- have the recipe for cursed infusion provide fewer (only one?) in the output

**Comment by 00-Evan** [comment]
It's intended that the item gives you some control over which curse you get by letting you re-roll

**Comment by CapnPants** [comment]
Also curse infusion doesn't just give 1 upgrade it gives 1+(item level/6) rounded down.
