### ISSUE TITLE
[Feature Request] Let the user change language

### ISSUE THREAD

**Issue by conchyliculture** [00-Evan/shattered-pixel-dungeon#195]
I've been playing the game in english for so long now on my French android, the sudden translation of all the item names and various text overflowing issues is super disconserting =)

**Comment by 00-Evan** [comment]
You're able to change the language anytime by pressing the button on the top-left of the main menu. It'll be highlighted in orange as your current language is unreviewed (hence the overflowing issues) 

If you want to help with translations, anyone is free to contribute through transifex: https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/

**Comment by conchyliculture** [comment]
Damn I feel stupid now. Clicked all around and never noticed that menu. Thanks!
