### ISSUE TITLE
Restore some signposts

### ISSUE THREAD

**Issue by verdulo** [00-Evan/shattered-pixel-dungeon#196]
As you have moved some texts to the journal, you have removed some informations about the plot of the game. Please consider restoring signposts on levels 5, 15, 20 and maybe on the level 21 (shop). I also suggest to add on the level 10 new item "Letter" in the same cell as the key.

**Comment by 00-Evan** [comment]
The current guidebook system is actually coded with the intention of expanding it into a full documents system, which will let you find all sorts of lore stuff within the game and reference them anytime from the journal. When that happens those tiny lore bits from the signposts will return.

In the meantime though I have no intention of returning signposts.

**Comment by verdulo** [comment]
I'm talking about signposts on depth 5 with text: "Go back now, this area is polluted and closed..." or on depth 20: "No weapons allowed in presence of His Majesty". It's no point to put these texts into the guidebook, isn't it? What about restoring the text from depth 10 as letter?

**Comment by 00-Evan** [comment]
The exact text won't be the same, but the information will be preserved when lore documents are added.
