### ISSUE TITLE
[Feature request] Add a bestiary to the guidebook

### ISSUE THREAD

**Issue by James-Arnold** [00-Evan/shattered-pixel-dungeon#198]
Add a bestiary which reveals information after defeating enemies to the guidebook. Reveal information in stages:

- Name, icon, description
- HP
- Resistances and weaknesses
- Attacks and other notes

Perhaps add a badge or two for completion

**Comment by 00-Evan** [comment]
This is a place to report issues with the source code, not to make suggestions.

I will likely include an information hub for enemies at some point, but I've not currently decided on what info will be included.
