### ISSUE TITLE
Translate mistake

### ISSUE THREAD

**Issue by pda11111** [00-Evan/shattered-pixel-dungeon#200]
In items.weapon.melee.handaxe.desc in core/src/main/resources/com/shatteredpixel/shatteredpixeldungeon/messages/items/items_ru.properties used word "топорище", which translated as helve or handle, not blade, which translated in russian as "лезвие".

**Comment by 00-Evan** [comment]
All translations are handled through Transifex. The translations you see on the source only correspond to the time of release and are likely outdated.

You're of course welcome to contribute on Transifex: https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/
