### ISSUE TITLE
[0.6.1b] Evil eye instantly firing laser after smoke bomb

### ISSUE THREAD

**Issue by draco123456ftw** [00-Evan/shattered-pixel-dungeon#201]
When playing as rogue class with the armour upgrade, if I use smoke bomb to escape an evil eye's charging beam, it will stop charging the beam and go mobile, but the next time it attempts to fire it will fire the beam immediately instead of having to charge up.

 This doesn't happen when stopping the beam when using the warrior class's heroic leap to stun.

**Comment by 00-Evan** [comment]
I'm aware of issues with evil eye AI. basically I initially programmed their beam with the expectation that they would never be interrupted, but of course there are situations where they can be interrupted. I plan on making their logic more resilient to this in 0.6.2

**Comment by 00-Evan** [comment]
fixed in commit fdc2293f00187a5621b7316afd004e800c94bc7e
