### ISSUE TITLE
Full bag with multiple tapping causing sprite to fly up

### ISSUE THREAD

**Issue by doctormo** [00-Evan/shattered-pixel-dungeon#203]
If you have a full bag, tapping to pick up certain items that have an up and down animation (drop animation?) allow the user to make the sprite fly up and up so long as the next tap happens before the animation has completed.

**Comment by 00-Evan** [comment]
This is intentional. It's a bug from the vanilla game that's too fun to remove =P.

**Comment by doctormo** [comment]
Cool.
