### ISSUE TITLE
Latest source code for the new translations?

### ISSUE THREAD

**Issue by protron** [00-Evan/shattered-pixel-dungeon#205]
I wonder if there is a way see the source code of the versions not released yet (as master branch seem to match v0.6.1b).

Because I'm translating the latest in transifex and I see a lot of new strings in there which I couldn't found in here (for instance actors.buffs.preparation).

I guess most translators doesn't look at the source code while translating, but I think is useful in some cases to be able to see how it used. For instance I wanted to see what some %d are filled with.

**Comment by 00-Evan** [comment]
I publish the source for a new update shortly after that update goes live, betas do not have an associated source release.

I'll be happy to answer any questions you might have about the text though.
