### ISSUE TITLE
Chest room with traps without any debuffs

### ISSUE THREAD

**Issue by pda11111** [00-Evan/shattered-pixel-dungeon#206]
I start play and game generate chest and traps room with traps, which are not bad for player

![Screenshot](https://i.imgur.com/q8oVzHr.png)

**Comment by 00-Evan** [comment]
Please do not report beta issues here, as there is no associated source code to point to.

I am aware that these traps don't do quite enough damage in the early stages of the game though, i'm looking to adjust this in the next beta.
