### ISSUE TITLE
Mimics dynamically spawned over chasms don't immediately fall down

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#207]
(Minor bug/quirk)

I managed to get this bug shooting a cursed wand at a wall over a chasm and it chose the mimic outcome, but it didn't instantly fall down and die to spawn its delicious loot

**Comment by 00-Evan** [comment]
fixed in commits be198f1907af37bfa868d0d4b212b25a7b57bf10 and 913a5042881e103572f5fdc204c77c6d24de58ce
