### ISSUE TITLE
Message history, a la NetHack

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#21]
It would be nice to be able see a history of messages that already disappeared from your screen.

**Comment by 00-Evan** [comment]
Having a full message history is possible, with a couple compromises. I wouldn't want to store a massive string in a player's save file so it would either not persist between game sessions, or have a fairly small size limit. 

Additionally I would want to have better formatting than what's current available, so I would first like to investigate the game log and see about cleaning up what gets printed on it and how its spaced.

Still certainly possible, I'll put this down as a future enhancement.

**Comment by 00-Evan** [comment]
An update on this.

Given the recent translation additions it has become in-feasible to support this, a permanent game log would not only have to work with all languages but may cause performance issues given the new rendered text system. While there should be ways to improve performance in the new text system, and I will pursue that, I'm avoiding screens with large amounts of non-static text moving forward.

Additionally, just showing a big game log dump isn't really the best way of recording information. If I were to make an update that better lets players keep track of what has happened in their game, it will probably be through an expanded journal interface.

**Comment by mindkeep** [comment]
A couple of us were chatting about something similar to this on Reddit here: https://www.reddit.com/r/PixelDungeon/comments/11jdauu/is_there_a_way_to_expand_the_message_history_on/

I wanted to see if something like this had been suggested and well, here we are. Rather than make a new request, thought I'd give this a bump.
