### ISSUE TITLE
Floor 2 locked room without any key 

### ISSUE THREAD

**Issue by schapira** [00-Evan/shattered-pixel-dungeon#210]
In a couple of games playing mage I have a locked room in second floor without having a key to open it. That happens so many times.

**Comment by egordorichev** [comment]
If you had a hole in the first floor, that's fine. It's a room, where you fall from the first level, and the key is inside of it. 

(Asked already, please, search, before creating a new issue.)

**Comment by 00-Evan** [comment]
As @egordorichev said, this is likely due to a special room type that requires you to jump down from the previous floor. I'm going to close this under that assumption, if you'd like to pursue this further feel free to reply with a screenshot.
