### ISSUE TITLE
Automatical routing takes the path using tiles in area accessible for attack by enemies

### ISSUE THREAD

**Issue by KOLANICH** [00-Evan/shattered-pixel-dungeon#212]
For example a room, a rectangle of water in the middle, a key and a pirranha guarding it. There are safe tiles near walls. I froze the time with hourglass, took the key, unfroze the time, tapped on exit out of the room. The path routing algorithm took the tiles near the water, so YASD.

So I think the routing algo should take in account which tiles are reachable to enemies.

**Comment by rmiddle3** [comment]
I think fixing this issue would just cause more issues here. As it is your character will already stop it's auto-path if they are damaged. Besides that it would make weaving through enemies more tedious if you're just trying to escape a room or unwinnable situation especially if there are rage enemies. How much of your movement should be decided by the algorithm and how much should you decide on? Wouldn't be much of a game if it played itself.

**Comment by 00-Evan** [comment]
My answer is basically the same as @rmiddle3 . Pathfinding should get the closest route from point A to B, and the more layers of complexity the trickier it gets as a game mechanic. If you want to take an in-optimal route because it's better for some other reason, you need to specify it.
