### ISSUE TITLE
F-Droid build 0.6.2a failed

### ISSUE THREAD

**Issue by shurke** [00-Evan/shattered-pixel-dungeon#213]
It seems that the automated build does not work for 0.6.2a:
https://f-droid.org/wiki/page/com.shatteredpixel.shatteredpixeldungeon/lastbuild_224

**Comment by 00-Evan** [comment]
This is because F-droid does not currently support the latest release of gradle: 4.3

There is no issue with shattered's code here, F-droid needs to update their gradle support.
