### ISSUE TITLE
Targeting enemy with wand gives "You can't target yourself!"

### ISSUE THREAD

**Issue by bjthinks** [00-Evan/shattered-pixel-dungeon#219]
See screenshots below.

**Comment by bjthinks** [comment]
http://tinypic.com/r/3148228/9
http://tinypic.com/r/1zpnvjt/9

**Comment by bjthinks** [comment]
To be clear, I'm touching the staffing my quickbar, then the burning skeleton who is not the default target.

**Comment by bjthinks** [comment]
s/staffing/staff on/

**Comment by 00-Evan** [comment]
This is a quirk of the current targeting system. The game traces a line from your position to the enemy's position, and in this case that line overlaps with a wall. The wand bolt will end up on the first cell before a wall, which in this case is your cell. It is possible to 'bank' the shot around or behind the skeleton, to have them be hit while not directly targeted. This is how the auto-target works, it will try every cell in a 5x5 grid around your target in hopes of finding one which works.

**Comment by bjthinks** [comment]
Thanks for the explanation. Great game BTW! :)
