### ISSUE TITLE
[v0.6.2e] Buggy main menu music playing

### ISSUE THREAD

**Issue by draco123456ftw** [00-Evan/shattered-pixel-dungeon#222]
(Device: HTC 10)

When in the main menu and pressing the phone's lock screen button, the music keeps playing while the screen is locked.
When unlocking the phone, it plays the main music again over the main menu music that's already playing.
Pressing the exit button at the top right also does not stop the music and opening up the app again also again plays main menu music over the main menu music.

**Comment by 00-Evan** [comment]
There were some issues with playing music in earlier 0.6.2 patches, which version are you running?

**Comment by draco123456ftw** [comment]
v0.6.2e

**Comment by draco123456ftw** [comment]
i sat my phone on my table enjoying the music and I think the music might also be playing twice when it loops as i'm noticing more echoing

**Comment by 00-Evan** [comment]
I'm looking into possible audio player weirdness as part of 0.6.3, but so far haven't been able to reproduce this. It might be a device-specific error, which means it will be very tricky for me to hunt down and fix.

Can you verify that you don't get this issue on vanilla pixel dungeon, or (if you recall) previous versions of shattered?

**Comment by draco123456ftw** [comment]
Very strange. I was playing around with the glitch, seeing what various things triggered it and also confirming it didn't happen in the original version. 

I then decided to uninstall and reinstall the app through the play store and the issue is gone! It might have just been a corrupt install or something.

At least I can work towards a full highscore list of completed games again ^^

**Comment by 00-Evan** [comment]
Well that's very interesting, I wonder if a particular setting caused this, i'll do a bit more testing...

**Comment by 00-Evan** [comment]
Not able to reproduce this, and seeing as reinstalling fixed it anyway I'll call this one closed for now. Feel free to comment if you run into it again.
