### ISSUE TITLE
Investigate & possible implement adb backups

### ISSUE THREAD

**Issue by wolfgangkarall** [00-Evan/shattered-pixel-dungeon#226]
Hi,

I don't know the reasoning behind setting android:allowBackup="false" for a game application, but seeing that my kids would like to transfer their game progress to their new devices I really would appreciate if you could set it to true in an upcoming release. :)

Cheers
Wolfgang

**Comment by TheYsconator** [comment]
It probably is set to false to make it more difficult for people to cheat.

It is, however, possible to transfer your ranking page entries to another device, by signing in to Google Play Games in-game. Your badges and rankings entries will transfer to any other device on which you log in as well. To the best of my knowledge, your games-in-progress will not be transferred.

**Comment by wolfgangkarall** [comment]
My kids don't have Google accounts, they have F-Droid-only devices, so I guess that will not work.

And is cheating in a single-player game really still a thing? And if you're that serious about it to mess with the backup files, I guess it's easier to cheat by using the source code, change allowBackup to true, compile it in Android Studio and get all the high-score-showing screenshots for bragging that you want. ;)

But for regular users, not being able to backup/transfer the game data is an unnecessary nuisance.

**Comment by 00-Evan** [comment]
As has already been mentioned, backup is disallowed to prevent cheating. Obviously stopping all forms of cheating is impossible, but I do want to prevent all of the easy ways, to dissuade the average player from cheating. For someone struggling through shattered the temptation to cheat can be massive, so it's best to make it as inaccessible as possible.

Keep in mind that there is no unlocked extra power in shattered, so if a player has already progressed a bunch through their skill, they'll likely recover all their badges/rankings on a fresh save very quickly.

**Comment by wolfgangkarall** [comment]
Hi,

well, I've just built the game myself with android:allowBackup set to "true" and luckily the old device was running Cyanogenmod, so getting the data was possible. Of course that means I'll need to run my own modified version of the game on my kids device in the future. I can live with that, they don't care that much about new versions anyway.

I think it's a sign of the times that vendors (even of open source software) make decisions instead of letting their user base decided (in this case the decision being "will I cheat (mostly myself) by fiddling with save games?"), in this case for the 'benefit' of protecting a minority ("players that can't bring themselves not to cheat if it's too easy") instead of the majority ("players that want to make proper backups").

Anyway, thanks for the game, my kids enjoy it a lot.

Cheers
Wolfgang

**Comment by 00-Evan** [comment]
If your device had root then you could have also used an app like titanium backup, or copied the games data folder directly.

I control aspects of how the user can play the game just like any other developer of a game would. Shattered isn't some utility software where customization and control is purely a virtue, there needs to be a definitive game experience and making cheating too accessible can easily compromise that. All you need is a relatively small critical mass of cheaters and people will begin to doubt if anyone's accomplishments are legitimate.

Also, the vast majority of users have access to Google Play services, and can then do a full backup through the cloud functionality of Google Play games.  Users who don't have play services are usually rooted, and therefore have control over their save files regardless of any restrictions I impose.

**Comment by wolfgangkarall** [comment]
Indeed copying the data folder back after installing my version of the application (that I could then adb backup to a the non-rooted new device) was how I resolved the issue.

For the rest, I do not agree (especially not with the 'Google Play services' is a backup), as cheating in open source software is bound to be easy. But it's your software, so it's your decision.

**Comment by 00-Evan** [comment]
Good news! I decided to review the documentation and it may be possible to implement backups in a selective manner. This would allow users to backup progression data such as badges/rankings, but not runs in progress. This would limit cheating while also letting users preserve their most important data.

Will investigate this for the next update.

**Comment by 00-Evan** [comment]
I've now got this working indev. ADB backup (and other apps which make use of ADB backup) work for android version 4.0+. This also works with auto-backup on android 6.0+.

All data is backed up except runs in progress.

**Comment by 00-Evan** [comment]
implemented in commit 3b5adde8badf5414da41a7970fcf404075f89d8a

**Comment by n-o-o-b** [comment]
> Users who don't have play services are usually rooted

I know this is an old issue but I wanted to say I think this is an incorrect assumption. Lots of people use custom ROMs without Google Play Services (e.g. GrapheneOS, /e/OS, iodéOS, LineageOS with microG) and don't want root. A lot of the time root is unnecessary and is a security risk (at least theoretically, but probably in practice too, as it increases the attack surface of the device).

**Comment by 00-Evan** [comment]
> > Users who don't have play services are usually rooted
> 
> I know this is an old issue but I wanted to say I think this is an incorrect assumption. Lots of people use custom ROMs without Google Play Services (e.g. GrapheneOS, /e/OS, iodéOS, LineageOS with microG) and don't want root. A lot of the time root is unnecessary and is a security risk (at least theoretically, but probably in practice too, as it increases the attack surface of the device).

You're replying to a message from 8 years ago. The landscape of custom ROMs has changed and I agree that assuming a custom ROM user has root isn't a good idea anymore. It's also not relevant here at all anymore as ADB backup support was implemented but then that feature was subsequently killed by Google. These days backup providers such as seedvault exist for custom ROMs.

**Comment by n-o-o-b** [comment]
Yes. I am glad the perception, or the practice of people, has changed. I read the discussion about ADB, and also about Seedvault. I don't know enough about Seedvault but it is a shame that backup via ADB was killed as it seems like that was potentially a straightforward (and one would hope reliable) method for backups not using a third-party service (that is, third-party to stock Android or to Shattered Pixel Dungeon).

**Comment by 00-Evan** [comment]
> Yes. I am glad the perception, or the practice of people, has changed. I read the discussion about ADB, and also about Seedvault. I don't know enough about Seedvault but it is a shame that backup via ADB was killed as it seems like that was a potentially a straightforward (and one would hope reliable) method for backups not using a third-party service (that is, third-party to stock Android or to Shattered Pixel Dungeon).

Indeed, it was a great tool for making simple local backups, why do you think Google killed it?

**Comment by n-o-o-b** [comment]
I think that may be a rhetorical question but nonetheless I'll answer it: I think they couldn't sufficiently track the data which was being transferred through it and control the workflow (because it was not fully in their ecosystem, there being another device that was connected that was running another operating system) and because as a result, or additionally, they couldn't monetise it.
