### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [00-Evan/shattered-pixel-dungeon#227]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by 00-Evan** [comment]
I'm aware of this new functionality, however currently oreo is running on 1.1% of devices, and I'd rather wait for more OEMs to implement this feature before working with it in shattered.

**Comment by mueller-ma** [comment]
Some launcher backport it to older android versions.

**Comment by 00-Evan** [comment]
indeed, but my primary concern isn't people who use nova launcher or similar, but people who are using things like the stock samsung launcher. Google has laid out standards for adaptive icons but my worry is that OEMs will stretch or break them, so I'd rather not design an adaptive icon before I know what it'll look like on a wide range of devices.
