### ISSUE TITLE
"Find" action text doesn't fit in screen

### ISSUE THREAD

**Issue by demothorg** [00-Evan/shattered-pixel-dungeon#228]
Hi!

SPD version: 0.6.3a. Language: russian.
For zoom 7x and 8x text doesn't feet in screen (1080x1920).

6x:
![screenshot_2018-02-20-21-17-36-397_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/4014972/36441788-b6265f30-1684-11e8-9984-cfb0a6aca78b.png)

7x:
![screenshot_2018-02-20-21-17-55-177_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/4014972/36441789-b652bc56-1684-11e8-9c3d-7808fcf5cff5.png)

**Comment by 00-Evan** [comment]
Please report all translation-related issues on the translation project: https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/

You are also welcome to sign up and help translate if you'd like.

**Comment by demothorg** [comment]
I don't think it is a translation issue.

**Comment by 00-Evan** [comment]
It is a translation issue because the current translated text is too large to fit into the area provided for it. A new or adjusted translation is needed that uses fewer characters.

**Comment by demothorg** [comment]
Why the game cannot wrap text?

**Comment by 00-Evan** [comment]
The game can wrap text of course, but the solution here isn't to take the current text and turn it into a 4-row tall mess. I would much rather use a shorter translation instead of trying to make the current one fit.

**Comment by demothorg** [comment]
Ok, I'll report this to transifex. But I think it is still issue in general case.

**Comment by 00-Evan** [comment]
That may be true, if a shorter translation is not possible then I will reconsider that part of the interface.
