### ISSUE TITLE
Add programmatically Items in Inventory

### ISSUE THREAD

**Issue by cliffgr** [00-Evan/shattered-pixel-dungeon#229]
Is there any method that i can add items (WeaponsId , potions etc) programmatically like:
Just for Testing proposes.
addInventory(Item item);

**Comment by TheYsconator** [comment]
You should take a look at the class where the different hero Classes are initialized. The mage, for example, starts with different items than the warrior, and these items are added to the inventory in that class.

**Comment by cliffgr** [comment]
Thanks 

```
 Dagger dagger=new Dagger();
 dagger.identify().collect();
```
