### ISSUE TITLE
Speech bubble outside the map

### ISSUE THREAD

**Issue by chrunchyjesus** [00-Evan/shattered-pixel-dungeon#232]
Found a speech bubble outside of the map. It might have been caused by the teleportation of Lloyd's Beacon on a monster, since I used it a few times on that level.

I do not know whether it is a bug in the original Pixel Dungeon or this, so I think I'd post it here. Correct me if I am wrong and I will report it on the original Pixel Dungeon.

Also, thanks for the awesome improvement on this game.

[Screenshot](https://user-images.githubusercontent.com/20382692/36748164-52ed2a3e-1bf7-11e8-9ded-1dfdaae20866.png)

**Comment by 00-Evan** [comment]
I've had a couple of reports of this in 0.6.3. Did this occur shortly after using one of the new sleeping darts?

**Comment by chrunchyjesus** [comment]
I have used sleeping darts on that level. However, I am not sure whether it popped up shortly after since I found the speech bubble after clearing the whole level, long after my last use of darts.

**Comment by 00-Evan** [comment]
fixed in commit 65c90e222a38a8d1bcf0136811f7176b5c00885f
