### ISSUE TITLE
Lost boomerang

### ISSUE THREAD

**Issue by pcercuei** [00-Evan/shattered-pixel-dungeon#233]
I noticed that sometimes (rarely), when I throw the boomerang to an enemy in a direct line without obstacles, the boomerang drops on the floor (or maybe it's a mis-click?).
Anyway, it happened to me while aiming at a bat above a hole; the boomerang fell into the hole and is lost forever. Bug, or feature?

**Comment by nspu** [comment]
1) The boomerang drop below or beside the enemy?(If it drop beside, it's probably a missclick)

2) When the boomerang fell into the chasm, it will be add to the next level. So if you don't find it in the next level maybe it's a bug.
[This a code when an item is drop into the chasm.](https://github.com/00-Evan/shattered-pixel-dungeon/blob/d36c063ba82f10f916456f452ed93982b021325c/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/Dungeon.java#L388)

**Comment by 00-Evan** [comment]
At specific tricky angles the game's targeting system will fail to reach an enemy, this is something i'd like to improve but it's not a priority atm.

As for the falling boomerang, dropped items can always be found in the depth below, so it is not lost forever.
