### ISSUE TITLE
Tengu - plant on wall

### ISSUE THREAD

**Issue by Beridok** [00-Evan/shattered-pixel-dungeon#235]
Self-explanatory via image.
Using plant on Tengu fight might result in plant being visible in wall after defeating him.
![screenshot_20180310-003436](https://user-images.githubusercontent.com/13395942/37452511-1e24e914-2835-11e8-988f-7d11348fe135.png)

**Comment by 00-Evan** [comment]
Thanks for letting me know about this. Seems that the level should be clearing plants whenever it is changed around, but currently isn't.

**Comment by 00-Evan** [comment]
fixed in commit 67bdd5b5fce5fd13e6258250de6f99d4da9aac02
