### ISSUE TITLE
Cannot build a release version

### ISSUE THREAD

**Issue by LukasAnda** [00-Evan/shattered-pixel-dungeon#236]
Hi, I've tried to build  release version of this game (I added some stuff, and added Firebase ads) but now, when I install the game, the strings are missing, debug works fine, but otherwise I am getting !!!NO TEXT FOUND!!!. Here is my build.gradle if you are interested:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        resConfigs "en_US", "cs", "tr", "ca", "ko", "pl", "it",
                "eo", "ru", "zh_CN", "de", "fr", "es", "pt", "fi", "hu", "in"
    }
    buildTypes {
        debug {
            applicationIdSuffix ".indev"
            versionNameSuffix '-INDEV'
        }
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(':SPD-classes')
    implementation 'com.google.firebase:firebase-ads:11.8.0'
}
buildscript {
    repositories {
        jcenter()
    }
}
`

**Comment by 00-Evan** [comment]
This is a place to report technical issues with the game and code, not to ask for assistance with sticking advertising in an open source game.

If you have renamed the class package structure, you'll need to adjust the values in messages.java and proguard-rules.pro

**Comment by LukasAnda** [comment]
Oops sorry :D I was just testing if I can implement other libraries. The debug works just fine.

**Comment by 00-Evan** [comment]
It's likely that you need to adjust the proguard config, if you changed the package structure. Proguard is not run on the debug build.

**Comment by LukasAnda** [comment]
okay thanks. but it looks like this
# retain these to support class references and meaningful stack traces
-keepnames class lukasanda.** { *; }
-keepnames class com.watabou.** { *; }
-keep class lukasanda.shatteredpixeldungeon { *; }
-keep class com.watabou.noosa.game { *; }
-keepattributes SourceFile,LineNumberTable

**Comment by 00-Evan** [comment]
You probably want to put a com. before lukasanda

**Comment by LukasAnda** [comment]
yay, thanks, fixed now
