### ISSUE TITLE
Falling down a chasm due to prismatic force and dying doesn't kill player

### ISSUE THREAD

**Issue by DanielHutt** [00-Evan/shattered-pixel-dungeon#238]
I was low on health and used my wand of prismatic force on an enemy near a chasm. This pushed me into a chasm which resulted in the death text but my character was not dead. Movement was stopped and hp was at 0.

**Comment by sotpapathe** [comment]
This has also happened to me but instead I fell due to the potion of levitation effect ending while being over a chasm.

**Comment by 00-Evan** [comment]
fixed in commit 5056176c57c00400b53621888863c4d9bbba0fe2
