### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by gsantner** [00-Evan/shattered-pixel-dungeon#245]
Currently the game seems to be completly incompatible with gamepads. If would be great if it can be used with one.

As in mapping, there are 4 spells, so ABXY could be mapped to that. And movement to move keys.

**Comment by 00-Evan** [comment]
I eventually plan to move to a multiplatform code for shattered, most likely libgdx. When that happens I will consider alternate control schemes. Until that time i'd rather not implement a system that will likely be changed/rewritten when I do that move.

**Comment by basxto** [comment]
How far have you moved to libgdx already?
Is it possible to tinker around with gamepad support on a fork?

**Comment by gsantner** [comment]
@basxto 
<https://github.com/00-Evan/shattered-pixel-dungeon-gdx> 

![grafik](https://user-images.githubusercontent.com/6735650/70375963-03a21300-18fc-11ea-9555-1ffab1d8f018.png)


@00-Evan 
As the other project is kinda dead now. Can you please reconsider this issue and reopen it?

**Comment by 00-Evan** [comment]
I don't plan to work on this right at the moment as the new desktop version is not fully functional just yet (its in beta atm), and the old codebase is not dead as it will be receiving 0.8.0.

**Comment by basxto** [comment]
Well, the android app would be nice with gamepad support, too.
There are bluetooth gamepads around after all.

**Comment by 00-Evan** [comment]
As mentioned, gamepad support will be universal when I implement it. My focus at the moment is ensuring the new desktop version is at feature parity with the old one and has no major bugs.
