### ISSUE TITLE
scrolls don't burn

### ISSUE THREAD

**Issue by beatnickgr** [00-Evan/shattered-pixel-dungeon#247]
![photo_2018-05-27_15-11-36](https://user-images.githubusercontent.com/17930530/40587412-59bc21fa-61d7-11e8-9281-ff1e4ba2bd3b.jpg)
Scrolls should burn when the grass is on fire

**Comment by 00-Evan** [comment]
This is working correctly, most scrolls will burn but scrolls of upgrade in particular are resistant to it. This is because losing those in particular to fire is disproportionately damaging to a run.
