### ISSUE TITLE
 bug : corpse dust (level 7)

### ISSUE THREAD

**Issue by beatnickgr** [00-Evan/shattered-pixel-dungeon#248]
How to reproduce

    the warrior talks to the old wand maker, if he tells you to get corpse dust
    kill the old wand maker (with fire?)
    go get the corpse dust
    => the ghosts will follow you on this level and all the next levels until they kill you.

expected behavior = the ghosts will only follow you on this level but not the next ones.

**Comment by 00-Evan** [comment]
This is intended behavior, corpse dust will continue to spawn wraiths on you regardless of your location.

**Comment by beatnickgr** [comment]
The wraiths followed me until they killed me, was I supposed to drop the corpse dust?

**Comment by 00-Evan** [comment]
The corpse dust has a fairly powerful curse, you will not be able to remove it without the wandmaker. This means that taking it and not talking to the wandmaker will likely end your run.

Although certain people have developed a strategy involving a staff of corruption that puts the wraiths on your side...

**Comment by beatnickgr** [comment]
In my case the wandmaker was not there anymore, I think I had killed him
with fire or something.
So i could not talk to him, that's why the wraiths killed me.
Having no staff of corruption, it would be nice that the wraiths follow
(not me but) the corpse dust itself, and stay where i dropped it...

**Comment by 00-Evan** [comment]
It is not possible to drop corpse dust, it is bound to you until the wandmaker gets rid of it. The item specifically overrides interaction behavior so that it is not possibly to drop it through regular means.

Similarly there shouldn't be any way to get rid of the wandmaker, he is immune to all effects.

**Comment by beatnickgr** [comment]
Well, next time i make him disappear, i'll open a new bug.
Thanks for your help!
