### ISSUE TITLE
double death, double rankings

### ISSUE THREAD

**Issue by rscmbbng** [00-Evan/shattered-pixel-dungeon#249]
Hi, I lost a game by using blast wave on a field of disintegration traps. The game twice said I died, once by killing myself with blast wave and once by the disintegration trap. It also shows up twice in the rankings. 

Nice game btw

**Comment by 00-Evan** [comment]
fixed  in commit a6d744c6a79fd455f82edb9c34778c2ffdb6581e (specifically the changes to WandOfBlastWave.java)
