### ISSUE TITLE
Typo in huntress description

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#25]
> Huntresses start with 15 points of Health.

That should read 25.

**Comment by 00-Evan** [comment]
The huntress does, infact, start with 15 points of health.

If you think the huntress should be buffed, you'll be happy to know she is going to get some help in the next update, but her health total will remain at 15.

**Comment by nyuszika7h** [comment]
Then there is a bug, because I checked and it said I have 25 HP.

**Comment by 00-Evan** [comment]
Did you gain any levels? Did you find a ring of might? Did you drink any potions of might?

**Comment by nyuszika7h** [comment]
I did level up a few times, yes. No ring or potion of might.

**Comment by 00-Evan** [comment]
that would be it then, you gain +5 max hp whenever you level up. At level 3 you would have 25 health.

**Comment by nyuszika7h** [comment]
I see, I guess I've never realized that so far.

**Comment by 00-Evan** [comment]
No worries. Also thanks for pointing out the grammar mistake in the label, has been fixed.
