### ISSUE TITLE
How to contribute at translation ?

### ISSUE THREAD

**Issue by Zatalyz** [00-Evan/shattered-pixel-dungeon#252]
Hello,
I like to play at Shattered Pixel Dungeon, but I discovered this app late because the lack of translation in the description repelled me. Bad excuse, and now I'd like to help make the game a success.

I had never contribute on android app, and  I am lost...

So : 
- how we can translate description of the game on Fdroid? The game is partially translated, having the description translated will also reassure other players that the game is in their language. 
- Where we can help to translate string on the game? It is translated into many languages and there is little missing in my own language. I can translate from English into French. Is there a weblate somewhere? 

I suggest you to create page in wiki to explain how to contribute (for translation and maybe other thing), it can help other people to improve Shattered Pixel Dungeon.

**Comment by TheYsconator** [comment]
Heya! :) The translations are handled using transifex. If you change things on there, they'll magically appear in this repo some time later.

Shattered Pixel Dungeon's transifex:
[https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/](https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/)

**Comment by 00-Evan** [comment]
See #211 , which may lead to translations being available on f-droid.
