### ISSUE TITLE
Window auto closes on textbox click

### ISSUE THREAD

**Issue by TheYsconator** [00-Evan/shattered-pixel-dungeon#254]
SPD closing textbox bug https://imgur.com/a/0rt09bO

These windows close on tapping the textbox. The bug occurs both when using Swiftkey and the Samsung default keyboard. I am using a galaxy s8 with the latest OS. The game version can be seen in the gif.

**Comment by 00-Evan** [comment]
This is an issue with the galaxy S8. Its keyboard behavior is inconsistent with other phones when immersive mode is enabled. Immersive mode is temporarily turned off when the keyboard is activated, which causes the scene to reset itself, as the game window dimensions have changed. 

This can be solved by disabling immersive mode in the settings, it's the "hide navigation bar" option.

This issue appears to be exclusive to the S8/S8+, I've never had it reported for any other device model.
