### ISSUE TITLE
Unnecessary confirmation message when throw Potion of Strength into Well of Transmutation

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#255]
When you are about to throw a Potion of Strength into a Well of Transmutation, a confirmation message appears. However, the Potion of Strength always turns into a Potion of Might, which is strictly better. The confirmation message is unnecessary in this case.

**Comment by 00-Evan** [comment]
Fair point, but the next update will make this moot regardless, so I have closed this issue.
