### ISSUE TITLE
Gold in wall bug, and graphical bug

### ISSUE THREAD

**Issue by TheYsconator** [00-Evan/shattered-pixel-dungeon#256]
See images on https://imgur.com/a/CW4IQpl

On the first image, you can see Gold in the wall on the King of Dwarves' floor. The player died, in a previous run, in the area of the King of Dwarves. In the next play through, there was (probably due to the picking up of bones, but that is unconfirmed) Gold in the walls. This bug is definitely on the most recent public (non-beta) version of the game.

On the second image, you can see that the Game Over sprite overlaid over the menu. This bug took place on 30/06 (June)/2018; I don't know exactly what version that is. :/

**Comment by 00-Evan** [comment]
Thanks for the report, the gold issue should be quite easy to reproduce, so I'll get that fixed.

As for the overlay, this has occasionally popped up but the reproduction steps are never consistent, can you possibly give me a bit more info about what you were doing before seeing that?

**Comment by TheYsconator** [comment]
Aww sorry; at the moment I can't remember anything special about the overlay run. If I encounter it again, I'll let you know immediately, so I still know what I was doing.

**Comment by 00-Evan** [comment]
fixed in commit a6d744c6a79fd455f82edb9c34778c2ffdb6581e (specifically the change to CityBossLevel.java)
