### ISSUE TITLE
Teleporting on top of enemy with Lloyd's Beacon

### ISSUE THREAD

**Issue by amangrewal** [00-Evan/shattered-pixel-dungeon#257]
I'm sorry I didn't take any screenshots of this.

I had set Lloyd's Beacon to return in the doorway of the shopkeeper on Level 6. I used Lloyd's Beacon on Level 6 and returned on top of a Gnoll Brute. I stepped off the brute, and the door closed with him still in the doorway. He continued fighting inside a closed door.

**Comment by schumaml** [comment]
Will we get telefrags for these cases? :)

**Comment by 00-Evan** [comment]
@schumaml sadly not, the game will try to push them out of the way.

**Comment by 00-Evan** [comment]
fixed in commit bc14ea0aa0881b756531c6630e3cf558fbb5caf9
