### ISSUE TITLE
Scroll of magic mapping don't burn

### ISSUE THREAD

**Issue by beatnickgr** [00-Evan/shattered-pixel-dungeon#258]
I burned the grass with a wand, but the scroll is still there.
It's a scroll of magic mapping.

![photo_2018-08-08_20-09-52](https://user-images.githubusercontent.com/17930530/43856118-e8988a54-9b47-11e8-942d-475063c26913.jpg)

related issue https://github.com/00-Evan/shattered-pixel-dungeon/issues/247

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Tested in a variety of different ways and magic mapping always burns. Do you have any other information that might be relevant? Was the scrolls under a tombstone?

**Comment by beatnickgr** [comment]
No tombstone, the scroll appeared after the grass was burnt.

**Comment by 00-Evan** [comment]
Well then I suppose we have to settle this one as 'cannot reproduce'. because in all my tests magic mapping scrolls did burn in fire. If you get this bug again and have any more info to share feel free to comment on this ticket and i'll re-open it.
