### ISSUE TITLE
Ritual not possible once all four candles are together

### ISSUE THREAD

**Issue by Mbodin** [00-Evan/shattered-pixel-dungeon#259]
I am being asked to perform a ritual. I found the place and the four candles. Here is the thing: I can’t individually drop the candles, it is either all of them or none. As a consequence, I can’t drop each four candles in the four angles of the ritual place. At best, I can place them in the middle of it. ☺ I have the feeling that this makes me miss some of the game. Is this on purpose? Maybe I am missing something. I am using version 0.6.5c of the game.

**Comment by TheYsconator** [comment]
Did you try throwing them?

**Comment by 00-Evan** [comment]
@Mbodin throw the candles into the desired location.

**Comment by Mbodin** [comment]
Indeed, I did not try this. And it works ☺ Thank you!
I did feel helpless, though. Maybe there could be an action added to the candles (or to any object with more than one occurrence?) to propose to drop one? This would prevent other people to be blocked at such places. What do you think?
