### ISSUE TITLE
Native design for "Enter a Hero Name" dialog

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#26]
That dialog has a Gingerbread theme. It would be nice if it supported the Holo and Material themes, depending on the Android version being used. It's a minor thing, but it bugs me.

**Comment by 00-Evan** [comment]
I plan to do work on these popup dialogs in the next update and following patches.

**Comment by 00-Evan** [comment]
Just a quick update, it is possible to skin the dialog to look more PD-eque, but it won't be perfect. Additionally, as I have to release the source code, get the desktop version out, and get moving on 0.3.0, the priority for this has shifted a bit. This may end up in a later patch to 0.2.4, but for now it has been deferred.

**Comment by jimbo1qaz** [comment]
How do you enter hero name?

**Comment by 00-Evan** [comment]
@jimbo1qaz this is a donation feature, it's available (along with a few other cosmetic extras) for those who donate money to support development of the game.

**Comment by 00-Evan** [comment]
Yup, this one is finally getting done.

**Comment by 00-Evan** [comment]
An update here. I've been doing some looking into the best way to implement this and came up with 3 options:

1. Skin the current Dialog window implementation to better mimic PD's theme
2. Move to 100% native components and implement my own keyboard input handler
3. 'Cheat' by using a native Pixel Dungeon window and overlaying an Android edittext ontop of that, simulating the effect of a 100% native implementation.

Option 1 is very awkward as working with android's dialog styling is full of pitfalls and is subject to the usual Android platform fragmentation bullshit. Plus even in an ideal case it almost certainly won't look like a native window.

Option 2 would be A LOT of work for what amounts to a fairly small feature, and so isn't feasible.

Option 3 seems like our winner here, it's a little hacky but is relatively easy to implement and will give a look that will fit in perfectly with the rest of the game.

**Comment by 00-Evan** [comment]
Implementation based on Option 3 is complete, looks quite nice I'd say:

![image](https://cloud.githubusercontent.com/assets/2347603/18613331/1aa0ca1a-7d46-11e6-88bc-2515f2929913.png)

As the rename features are not open source they won't be posted here, but the text input window implementation is generic and will be included in the source.

**Comment by 00-Evan** [comment]
Implemented in commit b87a1d5a8ca19435333ac809fed90e968d4d84c1
