### ISSUE TITLE
Notification "You catch fire!" appears twice

### ISSUE THREAD

**Issue by beatnickgr** [00-Evan/shattered-pixel-dungeon#261]
![screenshot_20180909-162608](https://user-images.githubusercontent.com/17930530/45265813-608cf000-b451-11e8-842c-9e9021af1280.png)

**Comment by 00-Evan** [comment]
that would probably be because you caught fire twice. Did you step out of water and then back into it? or was fire temporarily spread above the water and you were caught in that?

**Comment by beatnickgr** [comment]
I step into the water, i drink an unindentified potion, i catch fire, and the notification appears twice.
No need to move in/out of water.

I didn't try it with an identified potion.

**Comment by 00-Evan** [comment]
The potion was liquid flame. You caught fire one, the water put it out, and caught fire again because the AOE flame effect lasts for 2 turns. Working as intended.

**Comment by beatnickgr** [comment]
It might make sense for a programmer, but on the end user's side, when i drink a potion once, i cannot get burned twice. It would make more sense to say that it took me 2 turns to put it out, therefore i expect only 1 notification.

**Comment by 00-Evan** [comment]
regardless of your impression, you caught fire twice, so the message is displayed twice. You can feel like it should work another way if you want to, but there is no technical issue here.

**Comment by beatnickgr** [comment]
I would compare fire with caustic ooze, both of them last more than 1 turn.
As the caustic ooze doesn't display a new message on every turn, i would expect liquid flame to behave the same.

**Comment by 00-Evan** [comment]
both caustic ooze and fire do not apply a message every hit, they apply a message every time they are applied to the hero. If you were to get repeatedly oozed by an enemy while standing in water the message would display once for every time you are oozed, just as it is doing for fire in this case.
