### ISSUE TITLE
[Feature Request] Always show notification bar

### ISSUE THREAD

**Issue by pjbarnoy** [00-Evan/shattered-pixel-dungeon#262]
Hey, could we have an option to always show the status/notification bar? Thanks!

**Comment by 00-Evan** [comment]
Can you explain what your use for such a feature would be? It's possible obviously, but adding in a setting for it complicates the options menu, so there is a cost to implementing it. 

e.g. If 1/10k players use it and gets a mild convenience, but every single player who opens the options menu gets the extremely mild inconvenience of a setting they won't care about, it's a net loss.

**Comment by pjbarnoy** [comment]
It's mostly for convenience. I play a lot at work and need to stay on top of my notifications. My Note9's screen is taller than 16:9 so I wouldn't mind sacrificing the few extra pixels. Also, when I do swipe down from the top to access my notifications, it sometimes registers as a touch and moves my character accordingly. This gets frustrating when I forget to open the menu before swiping down.

Honestly, I wish this were a per-app setting throughout Android, but until then...

**Comment by Jacobnine87** [comment]
I don't see much reason for that option to be added. Does your device not vibrate or show the notification bar momentarily when you get a new notification?

**Comment by 00-Evan** [comment]
@pjbarnoy just wanted to follow up regarding this. Ultimately my stance on this is that it's not worth adding a setting to the options menu so I'm closing this issue, but I appreciate that it's annoying usability concern for you regardless.

Does swiping down from above your screen work to consistently show the notification bar without registering as an action ingame?
