### ISSUE TITLE
Damaging Tengu after healing him freezes the game

### ISSUE THREAD

**Issue by meltdown95** [00-Evan/shattered-pixel-dungeon#263]
Game version: 0.6.5c

Scenario:
1. During the second phase of the fight, heal Tengu over the half of his health.
1. Deal damage to Tengu.

Result:
Game freezes during the animation of the effect that caused the damage.

Notes:
* Reproduction rate is 100% if Tengu is healed before receiving any damage during the second phase.
* If Tengu is healed up from low HP, there is a chance that game won't freeze on damage.

**Comment by 00-Evan** [comment]
fixed in commit 02e0de6273d09f8c7287c0b5827e6f899d91a505 (specifically changes to Tengu.java and PrisonBossLevel.java)
