### ISSUE TITLE
A bug with Sad Ghost

### ISSUE THREAD

**Issue by endlesssolitude** [00-Evan/shattered-pixel-dungeon#264]
I went upstairs when Sad Ghost was combating against an enemy.Afterwards I went back and killed the enemy by boomerang.Sprisingly the Sad Ghost went to where it had the combat and fought with an invisible"enemy".That enemy didn't has health bar and when I tried boomerang to attack,it dropped on the ground indicating there was nothing.The invisible"enemy" could even dodge.There was particles when the "enemy" was attacked.After it died I got experience.Is it a serious bug?

**Comment by 00-Evan** [comment]
fixed in commit a6d744c6a79fd455f82edb9c34778c2ffdb6581e (specifically change in DriedRose.java)
