### ISSUE TITLE
teleportation trap resets fog of war

### ISSUE THREAD

**Issue by Draika** [00-Evan/shattered-pixel-dungeon#265]
v0.6.5.c
On a dark floor 14 after clearing the level, I stepped on a trap and the fog of war got reset as if I haven't explored the areas I was in previously.

On a side has anyone gotten the chalice recently on their runs? I feel like I never get it these days haha. I get chains and unstable spellbook all the time but never that.

**Comment by 00-Evan** [comment]
That is a warping trap, and is working as intended. Warping traps function like teleportation traps but also reset your knowledge of a floor.
