### ISSUE TITLE
Glyph of Thorns too strong?

### ISSUE THREAD

**Issue by bjthinks** [00-Evan/shattered-pixel-dungeon#266]
I just killed a Scorpio by pressing nothing but the rest button. I took a grand total of 20 damage. Many other enemies have fallen after a series of misses with my weapon...
Level 28 battlemage
Worn equipment:
Vampiric Glaive +4
Mage Robe (Plate) of Thorns +5
Ring of Furor +1
Timekeeper's Hourglass

**Comment by 00-Evan** [comment]
This is not a place to make game design suggestions.
