### ISSUE TITLE
If gold is dropped on top of mystery meat, examining the tile doesn't show the meat

### ISSUE THREAD

**Issue by anowlcalledjosh** [00-Evan/shattered-pixel-dungeon#267]
1. kill a crab and have it drop meat
2. fight another enemy that drops gold on the tile (e.g. gnoll scout)
3. examine the tile, observe that it just displays the amount of gold and doesn't give the disambiguation dialog to choose between gold and meat

**Comment by 00-Evan** [comment]
That is intended functionality, only the top item in a stack is visible. The dialog you mention only appears if there are multiple of an item, a trap, an enemy, a plant, etc. on one tile.

**Comment by L0j1k** [comment]
I'm interested in changing this behavior to include showing the modal/dialog for multiple items on a single square, or at least a justification for why it works the way it does? I feel that it is inconsistent and somewhat surprising behavior.

**Comment by 00-Evan** [comment]
It is a quirk of how item stacks are programmed. While it could be adjusted it may lead to issues such as being able to examine items inside of chests.
