### ISSUE TITLE
Locked door to floor 6 after defeating the blob 

### ISSUE THREAD

**Issue by Nixxen** [00-Evan/shattered-pixel-dungeon#269]
After defeating the blob and looting the key the door remained locked and impossible to open.
Found the rat king and looted his chests, still unable to open. Completely closing the game and starting the save again made the door able to be unlocked.

**Comment by Nixxen** [comment]
Forgot to mention, this is version 0.6.5c

**Comment by 00-Evan** [comment]
To be clear, you're claiming you defeated Goo, collected the key, and were then unable to interact with the locked gate, correct?

**Comment by Nixxen** [comment]
Correct. Tried running around to see if there was something to interact with but there was nothing other than the rat king. After trying once more to open the door I closed the game completely and loaded up the same save - and this time it worked.

**Comment by 00-Evan** [comment]
I haven't been able to reproduce this. Closing for now, please feel free to re-open if you encounter this again.
