### ISSUE TITLE
Paralysis and toxic gas potion "failsafe"

### ISSUE THREAD

**Issue by TheSSJ** [00-Evan/shattered-pixel-dungeon#270]
I happened to get this combination once in a while where I first drank an unidentified toxic gas potion and then by accident took an unidentified paralysis potion. Guess what happens: instant death because our hero can't snap out........

Could you build in a small failsafe that you snap out of paralysis maybe at 1HP to be able to take a health potion or teleport out of the toxic paralysis room? Last time I died with this unfortunate combo I had a plate armour +11 on for 16 :( a won run

**Comment by TheYsconator** [comment]
Isn't this the risk of drinking unidentified potions? :/

Anyway, I'm not Evan, but I do know that he generally tells people that Github Issues is not the place for suggestions regarding mechanics or design.

I _think_ the best place for you to post this kind of comments would be the PixelDungeon subreddit, which can be found here: [reddit.com/r/PixelDungeon](http://reddit.com/r/PixelDungeon).

**Comment by TheSSJ** [comment]
I am not on Reddit and don't get this platform honestly :D 
But you're right, it's definitely my fault of mindlessly drinking potions, but snapping out of paralysis happens sooner with enemies than with the hero (my opinion)

**Comment by 00-Evan** [comment]
The rules for breaking from paralysis are the same for the player and enemies. In this case the failsafe is already there: don't drink another potion if you're standing in toxic gas.
