### ISSUE TITLE
Not able to press the 'Continue' or 'Changelist' buttons after updating

### ISSUE THREAD

**Issue by TheYsconator** [00-Evan/shattered-pixel-dungeon#271]
I'm just assuming this is due to the update, but it might be a coincidence as well. After opening the app, I'm no longer able to press buttons on the WelcomeScene (thus preventing me from playing). I have cleared the cache of the app and rebooted my phone, I have not yet cleared all data.

I doubt it makes a difference, but FYI: I'm running the app on a Samsung Galaxy S8, and I'm launching Shattered from Game Launcher. There were no related problems during the beta.

**Comment by 00-Evan** [comment]
v0.7.0 or v0.7.0a?

**Comment by TheYsconator** [comment]
Ah sorry; the page didn't add your comment while I was typing.

The problem definitely is due to mapping being off. For these specific buttons, I had to press north of the buttons. The same goes for the changelist button, but all the 'top' buttons (settings, language, play, stats and exit) work fine.

**Comment by TheYsconator** [comment]
On second thought: I think the top buttons are also off; if I press them on the lower part of the button they don't activate.

**Comment by 00-Evan** [comment]
hmm, do you have the navigation bar hidden? does changing that affect anything?

**Comment by Nananas** [comment]
I have a similar issue (v0.7.0a, not on an S8). The navigation bar was hidden. Enabling fixes it.

**Comment by 00-Evan** [comment]
God dammit, I'm able to reproduce this in an emulator environment. seems that part of the window layout isn't updating correctly with the nav bar disabled. Will release an amended v0.7.0a ASAP

**Comment by TheYsconator** [comment]
The navigation bar was hidden on my phone as well, and enabling does indeed seem to fix the problem.

**Comment by 00-Evan** [comment]
amended v0.7.0a has been released to google play (I reverted the bugfix which caused this).

source will come out in a few minutes, then I'm going to bed.. ugh..

**Comment by 00-Evan** [comment]
fixed in commit a93deaa2a7194a18ff2ae35d5137188eeae9c2b5
