### ISSUE TITLE
Scroll of enchentment consumed when locked

### ISSUE THREAD

**Issue by SecT0uch** [00-Evan/shattered-pixel-dungeon#274]
My phone locked itself (inactivity) when I had to choose the effect of the scroll of enchentement. I lost the scroll.

**Comment by 00-Evan** [comment]
This isn't really avoidable unfortunately. If the scroll was refunded when the window was force-closed then it would be very easy to abuse, the scroll has to be gone the moment the window opens. Locking and unlocking your phone shouldn't normally cause the window to close, but if android forces the game to close or destroy its scene to free up memory, then the game can't really preserve the window. In the vast majority of android devices the game should stick around in memory unaffected for some time, but certain phones (or devices with 'task killer' apps installed) may force the game to close the moment it isn't in focus.

**Comment by SecT0uch** [comment]
I'll look into that. Thanks
