### ISSUE TITLE
New challenge mode: "No up staircases"

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#28]
With that challenge mode enabled, when you go down a staircase, there's no matching up staircase, so you cannot ascend.

**Comment by 00-Evan** [comment]
I have a working list of challenge ideas for when I eventually overhaul the challenge system (not happening anytime soon). This is actually one of the ideas I already have in that list. Here the entry in my list(note that this is all work in progress, nothing is final):

Name: Don't look back
Difficulty: 1 star 
Item/Class Limitation: lloyd's beacon removed 
Desc: Orpheus can relate. You may never ascend a staircase, going down a floor is final.

As I already have this recorded elsewhere, and it is going to be quite a while before I address challenges (besides perhaps re-adding degradation as a challenge) I'm going to close this to keep the issue tracker clean.

**Comment by joshtriplett** [comment]
Fair enough; thanks for the quick feedback.

On a related note, have you considered making Lloyd's Beacon a randomly available artifact, in addition to having it be randomly dropped by Goo?
