### ISSUE TITLE
Shattered Honeypots Don't Stack in Inventory

### ISSUE THREAD

**Issue by amangrewal** [00-Evan/shattered-pixel-dungeon#280]

**Comment by 00-Evan** [comment]
This is sort of working as intended. Shattered honeypots are each 'owned' by a bee, and that particular bee will care about that honeypot. Because of this, it's not really possible to have them stack.

That being said, pots which no longer have a bee probably should be able to stack with eachother. I'll look into clarifying this and potentially improving the stacking functionality.

**Comment by spixi** [comment]
Wouldn't it be easier if Bees protected the nearest Shattered Honeypot? So you could even make more use of the pots and lure them to a certain target. (Elixir of Honeyed Healing is oneshot only).

**Comment by 00-Evan** [comment]
I'm considering behavior changes to various allies in an upcoming update. Likely going to roll this into that as well. The issue is that I don't want to have multiple bees all competing to get closer to the same pot, especially seeing as they're hostile to eachother now.

**Comment by spixi** [comment]
What about Bees don't attack each other? That would make it much easier.

**Comment by 00-Evan** [comment]
Bees attacking eachother was a specific balance change made in 0.7.0 to make them less effective when stacked together.

**Comment by 00-Evan** [comment]
added in commit 9dd77eedd3d53bd6c559bd2eab68ba0dab91fd65

**Comment by spixi** [comment]
How can you decide now, which pot belongs to which bee, for example when you want to throw a pot somewhere to allure a bee there?

**Comment by 00-Evan** [comment]
Bees still keep track of either the location their pot is at, or the character holding their pot. When a pot is dropped, thrown, or picked up it will find a bee on the cirrent level with information that matches it and update that bee accordingly.

This is functionally equivalent to the old logic except for the specific case where the player is holding multiple broken pots and has multiple bees chasing them, and is depending on a specific bee to go to the location which they throw a pot to, intead of any one of the bees which are following them.
