### ISSUE TITLE
Thrown Items Do Not Reappear in Quickslot After Thief Steals Them

### ISSUE THREAD

**Issue by amangrewal** [00-Evan/shattered-pixel-dungeon#281]
Version 0.7.1b

I don't know the exact steps to reproduce because I can't control what the thief steals.
Most likely the following has to happen:
-Have a thrown item quickslotted
-Have the thief steal the item
-Throw the remaining items at the thief, so that the quickslot gets grayed out

When you pick up the item, the quickslot remains grayed out.

**Comment by 00-Evan** [comment]
Fixed in commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/86199bb40f64cf31140e64961f17c3cc32b2680a#diff-4e36dc646b81eab1b97ea6f5cd8ee5ea
