### ISSUE TITLE
Somehting getting wrong on moving on a trap.

### ISSUE THREAD

**Issue by ajira86** [00-Evan/shattered-pixel-dungeon#282]
I thing that I walked on a ConfusionTrap and loose control of my hero. In a room with holes you can fall to the next level (and die if you have not sufficient health).

But the last time, I was in a room without any hole but die by falling in the next level after walking on a trap. Is there something wrong with ConfusionTrap ?

**Comment by 00-Evan** [comment]
Sounds like you triggered a pitfall trap. They are rare traps which cause you to fall as if you stepped on a pit. Feel free to reply if you'd like more info, but im closing this as its not a technical issue.
