### ISSUE TITLE
Throwing Knives not identified

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#283]
In HeroClass.java

```knives.quantity(3).collect();```

should be

```knives.identify().quantity(3).collect();```

I don't know, whether that would change anything, but technically, the attribute ```levelKnown``` will never been set at the moment, although missile weapons are upgradable now.

The stones of the warrior are already correctly implemented.

**Comment by 00-Evan** [comment]
Thrown weapons naturally spawn with their level known (see line 49 of MissileWeapon,java), there is no need to identify them in initialization.

I do agree that there is a needless inconsistency here though, I'll remove that line from warrior's stones.

**Comment by spixi** [comment]
Do you think, you could make it possible to make missile items to be appear upgraded (in chests, remains or from the Gnoll Trickster)  and cursed in the future? This would be very interesting.
