### ISSUE TITLE
Unfortunately, Shattered Pixel Dungeon has stopped.

### ISSUE THREAD

**Issue by sokolgeo** [00-Evan/shattered-pixel-dungeon#285]
Unable to launch latest version from F-Droid - get the subject error message.
Version 0.7.1d (323) - Added on 2019-01-27 https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon/

My system is "Replicant 6" Android on two tablets: Galaxy Tab 2 7.0 https://redmine.replicant.us/projects/replicant/wiki/GalaxyTab270P31xx and Galaxy Tab 2 10.0 https://redmine.replicant.us/projects/replicant/wiki/GalaxyTab2101P51xx 

The Replicant is de-blobbed version of Android without any Google services https://en.wikipedia.org/wiki/Replicant_(operating_system)

Does Shattered Pixel may be require some Google services installed? 

How does one gets logs when Android version crashes?

**Comment by 00-Evan** [comment]
The open-source variants of Shattered make no use google play services. Even the google play version only uses them optionally and has them turned off by default.

I'll need a stack trace to be able to do anything about this though, it should be printed to your device's logcat.

**Comment by sokolgeo** [comment]
Sure, please find attached.
[logcat_02-11-2019_22-07-39.txt](https://github.com/00-Evan/shattered-pixel-dungeon/files/2853073/logcat_02-11-2019_22-07-39.txt)

**Comment by 00-Evan** [comment]
So from that crash report it looks like Shattered Pixel Dungeon isn't able to find a screen config to use. Shattered requires a config with at least 5/6/5 bits for red/green/blue, and 0 bits for alpha. Usually this means the game will use the extremely common RGB888 config, but for some reason your device doesn't seem to offer a valid config. Shattered uses a custom screen config chooser, so it's likely that shattered is doing something specific which is exposing an error in Replicant's EGL behavior.

I would suggest contacting the devs of Replicant about this, feel free to link them to this issue. The relevant Shattered Pixel Dungeon code is here: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/SPD-classes/src/main/java/com/watabou/glwrap/ScreenConfigChooser.java
(note that the comments for the preference constants are current wrong, the comments for PREF_LOW and PREF_HIGH are switched. I will fix that)

As this isn't an issue with Shattered's code, I've closed this.

**Comment by sokolgeo** [comment]
Thank you for looking into this.
For all having the same problem - the ticket on Replicant side is created here: https://redmine.replicant.us/issues/1910
