### ISSUE TITLE
ArtifactRecharge should not recharge Alchemist’s Toolkit

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#288]
The ArtifactRecharge buff, when inflicted by Scroll of Mystical Energy, should not recharge Alchemist’s Toolkit, because that would allow the player to obtain infinite alchemic energy. The number of obtainable Reclaim Traps is limited by the number of metal shards times three, so this issue only affects Scroll of Mystical Energy.

**Comment by 00-Evan** [comment]
This is not a technical issue. If you would like to make design suggestions, please email me.

My stance on this, by the way, is that infinite energy is fine if the user is willing to farm to the point where they can have so many scrolls. They would be able to get the exact same effect from infinite potions of experience regardless.
