### ISSUE TITLE
Minor graphic bug when teleporting in a row

### ISSUE THREAD

**Issue by Highseekerz** [00-Evan/shattered-pixel-dungeon#289]
when you throw blink runestone to teleporation trap or fadeleaf the screen and hero doesn't move to proper position. see links
[https://youtu.be/rhOFLWataMM](url)

**Comment by 00-Evan** [comment]
fixed in commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/e383c285ec11eb95c6111a1a1570bb0a1e65f6e7#diff-91733ee2ff6a3bb7660bfa32470c1afe
