### ISSUE TITLE
New challenge mode: "one-item inventory"

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#29]
One item is enough to hold the door keys dropped by the bosses.

**Comment by 00-Evan** [comment]
Restricting inventory space is a really interesting concept, and definitely will have one or two challenges themed around it in the challenge system rework I mentioned in #28 

There are a lot of ways to do a challenge themed this way, restricting to a single slot is certainly effective at reducing inventory but I wonder if there is a way to do it that forces more decision-making from the player, e.g. forcing a player to use all items before they descend. This is something I'll consider.

I'm closing this for the same reason as #28 , thanks for the suggestion.

**Comment by joshtriplett** [comment]
I can think of a couple of levels of inventory-related challenge.  One-item inventory would be a massive challenge.  "one item of each type" (e.g. one potion, one scroll, one weapon) would be a moderate challenge.

I wouldn't suggest just "half-sized inventory" or similar; that's less a creative-thinking challenge and more just obnoxiously annoying.

I like your idea of "cannot descend stairs while carrying items".
