### ISSUE TITLE
Auto-aming of Spirit Bow quickslot button does not always work

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#291]
If a new enemy hides behind grass, the auto-aming of the Spirit Bow’s quickslot button does not always work, even if the Huntress can see that enemy.

**Comment by 00-Evan** [comment]
This is working as intended. Quickslot autotargeting does not attempt to lock onto enemies seen through mind vision by default. This is for performance reasons as the alternative is having it constantly trying to target many enemies whenever you drink a potion of mind vision. Attacking the enemy once will cause the targeting to lock onto them.
