### ISSUE TITLE
Where is the game's main loop?

### ISSUE THREAD

**Issue by KOLANICH** [00-Evan/shattered-pixel-dungeon#293]
Hello. Could you, please, mark the game's main loop (where iteration over all the actors is done) with a comment making it easily searcheable?

**Comment by TheYsconator** [comment]
Not the author of the app, but I do have some experience with the source code. Just having the main loop is not that interesting for general changes (I've modded the game quite a bit, and have never used a 'main loop' as far as I'm concerned). If you can let me know what you'd like to change, I might be able to point you in the right direction.

**Comment by KOLANICH** [comment]
>If you can let me know what you'd like to change, I might be able to point you in the right direction.

I am just investigating if it is possible to transform this game into a some kind of MMO (not for human players, but for AI bots). I wonder if the main loop assume that actions of mobs and NPCs have any relative order, or if they are unordered (I guess it is easier to implement a single player game assumming the order, but for multiple actors controlled by different AIs we need this unordered, otherwise AIs moving first will have advantage).

**Comment by 00-Evan** [comment]
You'll want to Look into process() in Actor.java for the main loop of actors. This is initially called in GameScene.java.

I've closed this, as it isn't an issue with the game.

**Comment by KOLANICH** [comment]
Thanks.
