### ISSUE TITLE
Ring of Might doesn't affect "level reached" badges

### ISSUE THREAD

**Issue by anowlcalledjosh** [00-Evan/shattered-pixel-dungeon#294]
If you have a Ring of Might equipped, you can have an effective strength of more than 13, but the "badge endorsed" text doesn't pop up until you've drunk three Potions of Strength. I haven't tested, but I assume this also affects obtaining the badges for the first time.

(I'm still on 0.7.2-beta1.4, so it's possible this has been fixed since then.)

![image](https://user-images.githubusercontent.com/9433472/54595486-a0e5b000-4a2a-11e9-99d3-186ef70d2020.png)

**Comment by 00-Evan** [comment]
Effective strength isn't your permanent strength. The badge is meant to tie into strength potion use and not your current strength score.
