### ISSUE TITLE
Stealth option of Cloak of Shadows not always available

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#295]
When the Cloak of Shadows only has one charge, the Stealth option is not available from the inventory. The only workaround is to quickslot the Cloak, because the quickslot button works, even if there is only one charge left.

**Comment by 00-Evan** [comment]
Huh, that's a leftover from when the cloak required at least 2 charges to use, funny that it's lasted so long. Probably nobody noticed it as people usually just quickslot the cloak. I'll get that fixed either way though.

**Comment by 00-Evan** [comment]
fixed in commit here: https://github.com/00-Evan/shattered-pixel-dungeon/commit/8a4fd11eb9900279f291458a596e899ef45eccfc#diff-301610509d5a61a01568a8b9202962ab

**Comment by spixi** [comment]
Even if you have zero charges, you need the Stealth action to unstealth.

It must be:

```if (stealthed || ( isEquipped( hero ) && !cursed && charge > 0 ) )```

**Comment by spixi** [comment]
@Evan-00, The only case, you don't quickslot the Cloak is, when you have many wands, missiles or a certain artifact. Sometimes you want to unstealth (e. g. to attract enemies). My code above should fix that.
