### ISSUE TITLE
Possibility to add quickslots

### ISSUE THREAD

**Issue by SecT0uch** [00-Evan/shattered-pixel-dungeon#299]
Would it be possible to add one or two quickslots (via the Settings) if the screen is large enough ?
I'm mainly playing on the desktop version and as a huntress or a mage I often miss it.

**Comment by 00-Evan** [comment]
the desktop and android versions have the same number of quickslots.

Regarding having more than four, it's quite easy to do from a technical perspective, but I don't really want to further encourage players to juggle items. I already feel like shattered provides a bit too much at a time with wands and thrown weapons as-is. I'm likely going to try and address this problem in other ways.

**Comment by Niektory** [comment]
Could you reconsider this please? I don't think it would really "encourage" anything, just make doing what we're already doing more convenient. You could remove them again when you address this problem in other ways but for now it would be very helpful.

**Comment by 00-Evan** [comment]
If I add more slots I will never be able to take them out without a lot of anger from the players. The whole point is that rather than making consistently using a bunch of items convenient, I'd prefer to adjust to make it less necessary to use all those items.

**Comment by Niektory** [comment]
If removing them would cause a lot of anger from the players, then it follows that adding them would cause a lot of joy, am I wrong? ;-)

**Comment by 00-Evan** [comment]
Directly giving the players what they want is often not what is best for the game.
