### ISSUE TITLE
New artifact: Bag of Holding

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#30]
Increases inventory capacity, by increasing amounts with artifact level.  At maximum level, 2x capacity.

One possible idea for leveling up: the bag could gain experience every time you identify an item via use rather than via a Scroll of Identify.  However, that would make it much easier to level the bag when you find it early (via potions and scrolls) than when you find it late (only armor and weapons to ID).

When cursed, becomes the Bag of Devouring: every time you pick up an item (other than a boss-dropped key or the amulet), it has a small chance of being devoured instead.

**Comment by 00-Evan** [comment]
I feel like this is already being handled by bags purchased from shops, especially now that bag generation has been tweaked to favour giving the player bags they need more.

Would you really find a use for an artifact like this given that bags are available?

**Comment by joshtriplett** [comment]
Wildly so, yes.  I'm *always* short of inventory space through most of the game, and the persistent state of my inventory is "full".  To the point that I've sometimes carried an extra item or two through a floor by throwing it down corridors.  Finding a Bag of Holding (especially early on) would be as big a game-changer for me as finding Lloyd's Beacon (a bit more so because it wouldn't require backtracking).

The other alternative would be adding more item-specific bag types, such as a potion-holding bag (does the new Bandolier do that?) or ammo bag/quiver (holds all types of throwable items).

Actually, that brings up an idea for another artifact, too.

**Comment by joshtriplett** [comment]
As another alternative, have you seen the change in recent versions of Angband, adding an option (on by default) that turns off selling to shops (except selling for 0 gold as an identification mechanism), but increases the amount of gold found in the dungeon such that you end up on average having the same amount of gold that you would have had by selling items?

That rather drastically changes the feel of the game, making it unnecessary to drag around "vendor trash" that you're just going to sell for gold.  Instead, you only pick up and carry around items you're actually going to use.  So, no more dragging around spare weapons and armor just to throw them at the next shop in the hopes of buying one more healing potion; if you find a weapon or armor you aren't going to use, you just leave it on the ground.  (Leaving more room to carry around potions or seeds that you might use strategically.)  That would take a significant source of tedium out of the game.

You could also look to Angband for some of the analysis and multipliers they used to increase gold drops/piles.

**Comment by 00-Evan** [comment]
The new bandolier does infact hold potions. Additionally shops will now stock whichever bag you need most, which should further help inventory issues. 

Some level of inventory managment and decision making is good for the game I feel. While obviously forcing the player to constantly juggle items or leave large piles of things behind is too much, I see carrying around some amount of stuff you simply intend to sell as fine. Additionally, the amount of duplication of weapons and armor will reduce significantly with the weapons and armor rework, which should make for less objective 'vendor trash' overall.

As for angband's solution, I would prefer to rebalance the game so carting items around becomes less of an issue, something I hope my recent bag changes have contributed to. Some level or inventory management is important, and I'd rather not nullify it through too many bags, or through an option that basically cuts out a portion of the game.

**Comment by 00-Evan** [comment]
@joshtriplett 

I've been thinking on the change to Angband you mentioned, as well as monitoring player's feelings on inventory management, and I think I've come up with a good solution for Shattered.

As of patch 0.2.4d, which went live recently, shops now stock a 'merchant's beacon' which you can buy and activate later. The beacon lets you sell items to the shop from afar, but is used up after one session.

I'd be interested to hear what you think of this change, given that this was a significant issue for you.

**Comment by joshtriplett** [comment]
@00-Evan Haven't played the new version far enough to find a merchant's beacon yet, but based on that description, it may help a bit, mostly because it's only 5 floors between shops.  It doesn't at all eliminate the problem of carrying around items for the sole purpose of selling them; it just means you have more opportunities to do so.  Personally, I still prefer the Angband-style approach where you can simply ignore whole classes of items and not even bother picking them up let alone holding on to them.

Here's a good question: how drastically would it really change the game to have the merchant's beacon allow you to sell at any time without the "one session" limit?  Or, alternatively, to just disable selling entirely and multiply the average size of a gold pile/drop by a fixed amount?

Honestly, with such a change to Shattered, I'd be happy even with a *smaller* inventory size, because most of the time roughly a third to half of my inventory is being lugged around for the sole purpose of selling it at the next shop.  Inventory management is still important (and note that it's still important in Angband as well, in that you don't have enough inventory space to carry around everything you actively want to have available for use), and I think questions like "should I really carry around this fire potion just in case I find a wooden wall or a potion bandolier" are interesting, but questions like "should I lug around this longsword to sell at the next shop" (the selling price of which may pay for another healing potion that will end up saving your life) are *not* interesting.

**Comment by 00-Evan** [comment]
@joshtriplett I suppose I just don't see carrying items with the intent of selling as such a negative thing. 

You are right that it doesn't represent as strong of a gameplay decision as deciding to carry resource items, but I do see it as a positive aspect of the game. It creates points of satisfaction both when finding these items, and when selling them after a fight. I don't like the angband solution as it kills that satisfaction; while the end gold is the same, being able to collect and 'cash-in' items is more satisfying for most people. My main concern was that this too often made inventory management a pain, as space was getting tight, the beacon is attempting to address this.

To be clear, by 'session' I mean that when activated the beacon lets you sell as much as you want, as if you were in pixel mart, before breaking once you are done selling items. This means that if half your inventory is vendor trash you can sell it all in one go.

**Comment by joshtriplett** [comment]
@00-Evan It's your call; I don't personally find it more satisfying to find and sell an item I can't use rather than finding gold, but *shrug*.  I did understand what you meant by "session", and I do agree that the new merchant's beacon relieves some of that pressure, but I don't think it'll solve the problem, considering that sometimes I've had to make multiple trips to a shop within 5-level increments.  There's a reason I normally set Lloyd's Beacon to the shop door; that cuts those trips in half when I find Lloyd's Beacon.

What if the merchant's beacon doesn't break, but there's an x% penalty on sale prices if you sell remotely rather than in person?  Then if your inventory gets full, you can start selling low-value items first to make room until you reach the next shop.
