### ISSUE TITLE
Glyph of Multiplicity can spawn rats in Goo boss level

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#301]
I don‘t know, whether this is intentional, but if the player have a glyph of Multiplicity and is attacked by the Goo, a Marsupial or Albino rat may spawn.

This is, because ```SewerBossLevel``` does not override the ```createMob``` method of ```RegularLevel```. Because Goo is a boss and there is no roster for level 5 in the bestiary, a Marsupial Rat or its alternative form Albino Rat is generated. In the same way, Mimics (from cursed wands) can spawn rats.

This oddity only occurs in the sewer boss level, because all other special levels have an overriden ```createMob``` method doing nothing.

**Comment by 00-Evan** [comment]
This is definitely an issue if for no other reason than inconsistency.

it is intended that multiplicity create a random enemy if the one you're fighting is unique, but this behavior definitely isn't working correctly in boss floors. The game should either use the spawn table of the prior floor, or shouldn't spawn anything at all.

**Comment by 00-Evan** [comment]
fixed in commit 7c8a9c27aae90e624091174f39646ce5981d9b78
