### ISSUE TITLE
Using a scroll of retribution in a shop will wipe it out

### ISSUE THREAD

**Issue by unfa** [00-Evan/shattered-pixel-dungeon#302]
I've recently played a game where I was trying some scrolls out in a shop at level 11.

One of them was a scroll of retribution - my character was blinded and weakend, but also...

The shopkeeper as well as all items in the shop have disappeared without a trace...

I don't think that was an intentional effect...

**Comment by 00-Evan** [comment]
This is intended behaviour. Any sort of harmful effect being inflicted on them will cause shopkeepers to flee.
