### ISSUE TITLE
Blessed Ankh - Balancing

### ISSUE THREAD

**Issue by ShalokShalom** [00-Evan/shattered-pixel-dungeon#303]
I just lost to the fire elementar on level 7 because I used the blessed Ankh and thought it is some upgraded version of the Ankh.

Actually, it is worse. 

I had a Glaive +1, Ring of Might +1, Ring of Furor +1 and a Mail Armor of Obfuscation +2.

On level 7.

I had 69 runs and this was the strongest until.

Then I die because the blessed Ankh is actually worse then the normal one, if you have no health potion left.

Why? I thought it will restore my health, like the other one does. How does it make sense to restore so little health that the character dies by the very next hit?

**Comment by 00-Evan** [comment]
This is a place to report technical issues with the game, not to make balance suggestions.

Blessed ankhs are significantly better than regular ankhs in that they don't destroy all the items in your inventory and reset the floor. Neither of them are meant to be healing items, but rather are meant to be a safety net if the player misjudges a situation. I adjusted blessed ankhs to only slightly heal you a while ago as people were stacking them and using them as healing potions.

**Comment by ShalokShalom** [comment]
Well, the casual Ankhs are healing items and its a downgrade when they lose this ability.

**Comment by 00-Evan** [comment]
With the exception of all-challenge runs (where healing is so rare that ankhs are worth it) most players do not consider regular ankhs to be healing items because of all the items you lose in order to use them. Blessed ankhs were basically created because regular ones were considered useless by most players.

**Comment by ShalokShalom** [comment]
I used it in a case of emergency
