### ISSUE TITLE
Floor traps aren't well indicated.

### ISSUE THREAD

**Issue by a-raccoon** [00-Evan/shattered-pixel-dungeon#314]
Floor traps, the little plus symbols on the floor, aren't well indicated as traps, or even bad things. No message is displayed "Ouch! You hit a trap!" or any animation or ingame tutorial to suggest something bad happened to you. Unless you watch a YouTube walk-thru, one might think you're supposed to hit these checkpoints.

**Comment by LoneWolfHT** [comment]
I never watched/read any tutorials and I found out pretty quickly that traps aren't good. There may have even been an ingame tip come to think of it :thinking:

**Comment by a-raccoon** [comment]
If so, then I missed it.  I didn't mean to miss it.  ¯\\\_(ツ)\_/¯

**Comment by 00-Evan** [comment]
This is why the game has an 'examine' button prominently placed in the UI. The player is means to examine anything they don't know about.

**Comment by a-raccoon** [comment]
Why are other damage and activities reported in the status, but not trap damage?

**Comment by 00-Evan** [comment]
If you're referring to damage numbers above the hero, traps do show that.

If you mean output in the game log, that does happen but only for non-visible traps. Enemies hitting you also doesn't put anything in the game log though.
