### ISSUE TITLE
[Bug] Thrown weapon deleted when used as final blow in Tengu bos fight

### ISSUE THREAD

**Issue by matematikaadit** [00-Evan/shattered-pixel-dungeon#315]
So, it happened recently. Don't know what causing it so I will just list all the pre-conditions

1. In the final phase of Tengu Boss fight
2. Having Thrown Hammer +6
3. Having Dried Rose Ghost active and attacking the Tengu
4. Using the Thrown Hammer as the final blow to the Tengu

What actually happened

* The fight ended, the Tengu defeated
* You and the ghost teleported back to the chamber
* There's the book in the floor that you got after defeating the Tengu
* The Thrown Hammer +6 is nowhere to be found, it's somewhat deleted

What should happen

* Usually, you also got back any thrown weapon you use in the floor in the final chamber

**Comment by 00-Evan** [comment]
Are you using version 0.7.3a? This should be fixed already as of that patch.

**Comment by matematikaadit** [comment]
Ah, didn't realize that there's an update. Will check it again.
