### ISSUE TITLE
Thrown weapons are still disappearing in the Tengu fight

### ISSUE THREAD

**Issue by Indecision6326** [00-Evan/shattered-pixel-dungeon#316]
Even in 0.7.3a, in which the changelog says thrown weapons disappearing during the Tengu fight has been fixed, one of my darts still disappeared after I killed him (see picture below).

![Tengu Died, Dart Vanished](https://user-images.githubusercontent.com/42480723/58425753-a5e96000-8068-11e9-8760-2a53e3a7ee56.PNG)

Even after scrying with the Talisman of Foresight, I found the second dart to be nowhere on his floor. I suppose 0.7.3b will want to address this....

**Comment by 00-Evan** [comment]
Odd, this was working for me indev, but I'm now able to consistently reproduce losing the final thrown weapon again. Will investigate.

**Comment by 00-Evan** [comment]
fixed in commit 8b971725579d69a553ca587dca3bff8c939e6a2e
