### ISSUE TITLE
Add a joystick feature for easy control of the hero

### ISSUE THREAD

**Issue by chrisbarth01** [00-Evan/shattered-pixel-dungeon#317]
#### Components 

The idea/component / I want to suggest is that a joystick for directions should be added to the game app

---

#### Proposal Description 

The game is quite interesting; I couldn't even resist it till I failed. It is a bit odd and difficult how the users are to control the hero in the game. Presently, the hero is controlled by tapping on the screen and doing it this way makes his movements not to be constant. I am suggesting that a joystick icon should be added to the down right corner of the screen where are user can easily  fix-place his/her finger without having to be tapping on the different angles of the screen. 

---

#### Mockup/Example

The first image is the present look of the app while the second image is an example of the feature which I'm suggesting. 
![20190528-111610](https://user-images.githubusercontent.com/49325171/58510376-7fbedf80-8190-11e9-8525-804012bdaf62.png)

---

![20190528_162916_0000](https://user-images.githubusercontent.com/49325171/58510287-4b4b2380-8190-11e9-96d6-18ee79a5eb12.png)

---

#### Benefits

If this idea is considered and added to the game app, users will find it more easy to move the hero to any part/angle of the screen without having to be tapping randomly on the screen. Not just that, users will also find it easy as their finger will be in a specific position while the hero moves, making them to be more focused in the game. 

---

#### Conclusion 

This feature is very necessary and needed in the app. I just have a feeling that the PO will consider it as controlling the hero is presently more difficult than my proposal.

**Comment by 00-Evan** [comment]
Unfortunately most people have the exact opposite opinion to yours, which is that the current control scheme is much superior to emulating a traditional controller via the touch screen. Consider that walking to a location requires a single tap, whereas moving to that location via analog stick will require many inputs. It is also much harder to be precise with analog control, especially when it's a software stick and not a physical one.

It's possible that in the future I might be able to add this if/when I add physical controller support, but at the moment this is not something which I am considering.
