### ISSUE TITLE
Using a Potion of StormClouds after Tengu fight causes graphical glitches

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#319]
After you defeated Tengu, use a Potion of StormClouds. The drawn water looks glitchy.

**Comment by spixi** [comment]
![Screenshot_2019-05-30-13-01-27-217_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/58628975-6fffe200-82db-11e9-9dd1-48c653f289f8.png)

**Comment by spixi** [comment]
![Screenshot_2019-05-30-13-01-27-217_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/58629007-873ecf80-82db-11e9-91b7-cab7cfad7020.png)

**Comment by spixi** [comment]
![IMG_20190530_130523](https://user-images.githubusercontent.com/3192596/58629053-9de52680-82db-11e9-984d-5a74e3c64658.jpg)

**Comment by 00-Evan** [comment]
This is a consequence of the custom visuals which are used to make the ground effect. Seeing as there's no logical reason to throw a potion of storm clouds there I don't think this is an issue worth addressing.
