### ISSUE TITLE
Lloyd's Beacon improvement: don't forget location

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#32]
When I find Lloyd's Beacon, I tend to use it for a quick warp back to the most recent shop.  However, using the beacon drops the remembered location, and it's easy to forget to re-set it before heading back down.  Why not have the beacon keep the last used location permanently until explicitly re-set?

**Comment by 00-Evan** [comment]
Sure, I don't see any reason why this can't be done as a small convenience fix, I'll roll it into the next patch.

**Comment by joshtriplett** [comment]
Thanks!

**Comment by 00-Evan** [comment]
This has been corrected in version 0.2.4a, will close this ticket with a reference to the commit once the source is released.

**Comment by 00-Evan** [comment]
implemented in commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/bfd3dd70888855bb4f0be5d80f7917e25a04e59a
