### ISSUE TITLE
Additional bag

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#320]
As there are now more throwing items (and they can be upgraded, which consumes even more space), the space in the bag and in the wand holster is getting tight. 

With catalysts, the easier dart tipping and Elixir of Honeyed Healing you addressed this issue, but it is not really fixed. For example, there are items like the Arcane Bomb, which you are usually carrying a long time until the Dwarf King boss battle.

One possibility would be adding the chain from Sprouted, which holds rings and ankhs or the other possibility would be a quiver for throwing items and bombs.

**Comment by 00-Evan** [comment]
The magical holster already carries 20 items, surely that is enough for almost any run. Also the additional types of thrown weapons doesn't mean more thrown weapons spawn within the game overall.

I do intend to keep improving inventory management but I don't think new bags need to be added.
