### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NinjaBoyLao** [00-Evan/shattered-pixel-dungeon#321]
Wand of Transfusion will sometimes add shielding to enemies, on the second or more zaps on the same enemy. The description of the wand says nothing about this, only mentioning that you're supposed to receive shielding and recover health when you use it. Should the shielding effect not stack on yourself and be slightly increased on concurrent zaps?

**Comment by videogamer1002** [comment]
this is intentional. transfusion charms enemies, and heals allies. once an enemy is charmed its treated as an ally, so it will get healing on concurrent zaps. if it is at full health, it will get shielding.

**Comment by 00-Evan** [comment]
As videogames said, the want gives your health to allies and saps energy from enemies. Charmed enemies are considered allies.
