### ISSUE TITLE
Request for a bigger post-game

### ISSUE THREAD

**Issue by contrapunctus-1** [00-Evan/shattered-pixel-dungeon#322]
After having completed the game with all subclasses, I find myself wishing that SPD had a bigger post-game. (As a beginner it felt like the game itself was too long, and now it feels like it ends too soon :sweat_smile:) Perhaps some further challenges can be added, or maybe there can be some way to kick back and enjoy your character instead of continuing to worry about food and health? Some possibilities (thinking aloud, pardon me if it sounds crazy) -
1. Obtaining the Amulet makes the character immortal, or works as a Ring of Wealth on steroids (so the scarcity anxiety is handled)
2. New bonus depths to explore below Demon Halls
3. Defeating Yog resets all floors above? So all monsters and bosses respawn, treasures regenerate, etc

Or some combination thereof?

Thanks for reading.

**Comment by 00-Evan** [comment]
Post game content is something I would like to add in the future, but right now it's too far off to consider. There are still a few big holes in the gameplay that already exists.
