### ISSUE TITLE
Infinite Trap Reclamation

### ISSUE THREAD

**Issue by Indecision6326** [00-Evan/shattered-pixel-dungeon#323]
I found a problem with the new version of the Reclaim Trap spell: when dropped, it loses the reclaimed trap, thus allowing for another trap reclamation. In addition, dropping the spell doesn't reduce the stack size, meaning that one can deactivate any number of traps by making a single stack of them. I believe this'll need to be addressed in 0.7.3c.

**Comment by 00-Evan** [comment]
I'm aware of this, and it is somewhat intended, as reclaim trap is meant to lose the trap currently stored when dropped. I opted to not penalize the player for dropping the spell, as the majority of traps can either be avoided or safely triggered from a distance through a variety of means. If it ever becomes a semi-common strategy to use reclaim trap in this way I will likely adjust it to lose one from the stack if dropped while charged.

There is also no plans currently to release a 0.7.3c, I'm moving on to the next update. I know it's not your intention to be bossy, but please don't try and tell me what to do.
