### ISSUE TITLE
Auto-aim targets piranhas

### ISSUE THREAD

**Issue by echaskaris** [00-Evan/shattered-pixel-dungeon#325]
It is annoying losing ranged weapons because they land on the fish or wasting a wand charge. You can make it so that the piranha is targeted only if it's the only monster visible. The piranhas I'm talking about are the ones where there is a body of water and planks around it, as well as ground to walk on on the outside. Thanks.

**Comment by 00-Evan** [comment]
I'd prefer to keep auto-targeting behavior as consistent as possible. Piranhas are an enemy, so the system will target them automatically if there are no closer enemies. I don't think it's a good idea to have specific exceptions to that rule, especially seeing as you can just manually target the enemy you want to attack once, and the auto-aim will then go for them. Additionally, the appearance of health bars (whichever one is larger) shows you who you are mainly targeting before you even start to target.
