### ISSUE TITLE
Ring of force is broken

### ISSUE THREAD

**Issue by renatobellotti** [00-Evan/shattered-pixel-dungeon#326]
Strength doesn't change when I put on ring of force +2 or not.

Class: Rogue level 11 on depth 9

Version: 7.3.a from F-Droid

Please let me know if you need further information.

**Comment by curtiszimmerman** [comment]
The Ring of Force does not modify your strength. It modifies the damage you deal without a weapon. A lot. It also adds a bit of damage if you are using a weapon, but not nearly as much. The Ring of Might is the ring which adds to your strength.

**Comment by renatobellotti** [comment]
I understand, sorry for the inconvenience. Great game, by the way! :)
