### ISSUE TITLE
Piranhas don't give any XP

### ISSUE THREAD

**Issue by Cyberpangolin** [00-Evan/shattered-pixel-dungeon#327]
Piranhas are very dangerous mobs, especially at the beginning of the game: they are quick and can make lots of damage, which makes them challenging enemies. I think they must give (lots of?) experience if you kill them, especially in the first stages.

**Comment by curtiszimmerman** [comment]
The point of piranhas is that they are guaranteed to give you one piece of mystery meat. They also guard a (typically) good item. However as you noted, they are very dangerous foes, and give no experience whatsoever. The result of this is that if you are on a run where food is scarce, you can burn a bunch of turns with a ranged weapon and get yourself some meat. This is also the only guaranteed source of meat in the game, which is needed to create a pot (meat) pie. These fish are deliberately tough opponents.

**Comment by 00-Evan** [comment]
Piranhas are primarily meant to be avoided, not fought. If you are able to kill them with ranged attacks the garunteed meat they drop is already a pretty nice reward. I don't really want to further incentivize killing them.
