### ISSUE TITLE
Earth Guardian and Great Crab impasse

### ISSUE THREAD

**Issue by countbuggula** [00-Evan/shattered-pixel-dungeon#328]
In the new 0.7.4-beta-2 release, playing as a mage, I obtained a wand of living earth, imbued my staff with it, and upgraded it to +4.  On level four I encountered the Great Crab and upon casting my wand at it summoned the Earthern Guardian.  The Great Crab however does no damage to the gaurdian, and the guardian (or myself) can't hit the crab because it's always aware of an enemy and blocks every attack.  So the two are stuck standing next to each other attacking each other with no effect, and nothing I can do stops them.
An idea to address this without nerfing the guardian might be to allow attacks to be effective in the Great Crab when flanked by an ally.

**Comment by 00-Evan** [comment]
Betas do not have a corresponding source release, and so issues with beta functionality should be emailed to me, not reported here.

**Comment by countbuggula** [comment]
Sorry, I couldn't find instructions to submit bug reports for the beta, I'll email you in the future.

**Comment by 00-Evan** [comment]
No worries, the best way to contact me regarding bugs is always to email me.
