### ISSUE TITLE
Labyrinth on 3 level

### ISSUE THREAD

**Issue by psydvl** [00-Evan/shattered-pixel-dungeon#329]
I think, screenshot show enough info. Also I do full perimeter search. 
![Screenshot](https://user-images.githubusercontent.com/43755002/61467359-24d18980-a984-11e9-9255-d380a635db3b.jpg)
Oneplus 5, Android 9, v0.7.4-RC-1

**Comment by psydvl** [comment]
Rest level part
![Screenshot](https://user-images.githubusercontent.com/43755002/61468477-08365100-a986-11e9-86f7-27ccb91351f4.jpg)

**Comment by 00-Evan** [comment]
Working as intended, that's a type of secret room.
