### ISSUE TITLE
Artifact idea: Bottomless Quiver

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#33]
Holds all types of throwable items / ammunition.  Levels up from +1 to +10 as you put more types and quantities of ammunition in it (perhaps feeding it ammunition like the horn of plenty, or perhaps just placing unique types inside).  Has a level/10 chance of not actually using up ammunition when thrown at an enemy (so, if you have 5 darts inside, and you throw a dart at an enemy, then level-out-of-10 times you'll still have 5 darts inside after the throw).

**Comment by joshtriplett** [comment]
A similar mechanic could work for other types of artifact bags, too: a seed bag that gave a chance of not using up a seed when thrown/planted, a scroll case that gave a chance of not using up a scroll when read, and a wand quiver that gives a chance of not using up a charge when zapping a wand.  These would automatically replace the more mundane bags if found.

**Comment by 00-Evan** [comment]
I have had a concept for a bag like this floating around for a bit, it could be huntress exclusive, as part of her rework, or a general bag that would go along with the wand holster. I'm not sure it works best as an artifact though, bag is its own class of item.

Still, bags can and probably should have some side benefit, like the scroll holder and potion bandolier protecting their respective items from burning/freezing. As seeds are so common the seed pouch may stand on it's own, but a quiver could have some small benefit, and after the wand rework the wand holster will probably be getting a benefit too.

**Comment by 00-Evan** [comment]
Also, as an aside:

I really appreciate your feedback, but for gameplay related stuff I would prefer if you email me. Technical stuff, or utility improvements (e.g. the beacon remembering, looking into ranged weapon targeting) fit perfectly here. Suggestions and discussion relating to game design don't really work well with an issue tracker though, as accepting suggestions is rarely as binary as fixing with a changelist or closing a ticket.

**Comment by joshtriplett** [comment]
Fair enough, will do.
