### ISSUE TITLE
0.7.4: Warrior's seal didn't carry upgrade with it

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#330]
I found a piece of armor with a +1 upgrade already on it. I took the warrior's seal off the initial cloth armor (not enchanted), put it on the found armor, then took it off to put that enchantment on a better piece of armor (scale). However, the upgrade didn't come off with the seal.

**Comment by 00-Evan** [comment]
Working as intended. The seal can only transfer an upgrade it was given, it cannot be used to steal an upgrade from another armor. I specifically coded it this way so that a random +1 armor can't be essentially converted into a free scroll of upgrade.

**Comment by joshtriplett** [comment]
On July 22, 2019 11:58:51 PM PDT, Evan Debenham <notifications@github.com> wrote:
>Working as intended. The seal can only transfer an upgrade it was
>given, it cannot be used to steal an upgrade from another armor. I
>specifically coded it this way so that a random +1 armor can't be
>essentially converted into a free scroll of upgrade.

The description of the seal (as an item and in the warrior's description) doesn't document that, and it affects strategy, so it would be good to know from the beginning.
