### ISSUE TITLE
Automatic capitalization of sentences (translations)

### ISSUE THREAD

**Issue by osoitz** [00-Evan/shattered-pixel-dungeon#331]
The way a sentence is constructed can be different in different languages. This means that an object that in English appears in the middle of the sentence, and therefore must be written in lowercase, in a translation might need to go at the beginning of the sentence and be written with capital letter.

The translation could be fixed manually but 1) these sentences are often constructed using variables, ("You now have -variable-") so it's difficult for a translator to know which strings go there, and 2) in a future these strings could be reused in a different context were they shouldn't be capitalized.

A way to solve this problem would be to automatically capitalize the first letter of the sentences in runtime, at least for languages that use the Latin alphabet (if I'm not mistaken all capitalize the first letter of a sentence).

**Comment by 00-Evan** [comment]
This already happens in most places. You can see for example that item names aren't capitalized in the raw text, and the game will dynamically apply caps based on the context. Generally the only cases where strings are hard-coded capitalized is when they only show up one specific way, such as buff names.

Which contexts are you seeing this issue in specifically?

**Comment by osoitz** [comment]
I'm seeing this in the following string:

You now have: 1%s

Resource
actors.properties
String Hash
6e88a2a455d778216f1bbedea15f2786 
Key
actors.hero.hero.you_now_have

**Comment by osoitz** [comment]
Another one:

It has a _%s._ 


Resource
items.properties
String Hash
1afcad350cbffb8333177267b53af974 
Key
items.weapon.weapon.enchanted

**Comment by 00-Evan** [comment]
I see your point. I attempted to phrase strings like that so that the structure should be similar in most languages. From taking a quick look at both of those strings they do follow the same pattern in almost all cases, with only basque and asian script languages breaking that structure.

Adjusting the capitalization on those phrases could be done but I'd consider it a fairly low priority issue, especially seeing as it would be time-consuming to go through all the existing phrases, and then either have translators re-translate them, or adjust the caps on every translation myself.

**Comment by spixi** [comment]
That wonʼt work fir some languages. For example in Dutch, the diphthong “ij” is considered to be one letter like in “ijs” which must become “IJs” when capitalized. Also some languages the of word compositions may be different and they may start with prefixes or include prepositions which should not be capitalized. It is best to do the capitalization manually.

**Comment by 00-Evan** [comment]
Sorry for the extremely late movement on this. I am going to adjust the two mentioned strings, and am open to make more incremental adjustments in future updates. It's probably best to do this one at a time, prioritizing the most often problematic strings, rather than doing them all at once.

**Comment by punk4eva** [comment]
You are working hard and you are managing to fix many bugs !! Keep it up you are doing great :)

**Comment by 00-Evan** [comment]
Fixed in commit db1595906953de73833a47d40e045071c986ede7
