### ISSUE TITLE
[RFE] Meat distracts piranha

### ISSUE THREAD

**Issue by whitel** [00-Evan/shattered-pixel-dungeon#332]
I think it would be cool if I could throw raw meat in the corner of a piranha pool and the piranha would go to it, ignoring me.  Not for very long maybe enough time to get the item and the meat would be consumed.

**Comment by 00-Evan** [comment]
I agree that this would be cool thematically, but it's a sort odd niche mechanic, and would further detract from potions of invisibility being the intended way to avoid the piranhas.
