### ISSUE TITLE
[RFE] Log scrollback

### ISSUE THREAD

**Issue by whitel** [00-Evan/shattered-pixel-dungeon#333]
I would love to be able to see the history of the log (the one in the bottom left). Sometimes, I get a message and miss it or I have stepped away from this run of the game and I need a reminder. I just think it would be handy.

**Comment by whitel** [comment]
I am, potentially, interested in implementing this but want to be sure it is a desired feature beforehand.

**Comment by 00-Evan** [comment]
The major issue with doing something like this is storage. Just holding onto a few messages in memory is fine, but for a dedicated 'message history' feature to work decently then a long history of messages would need to be saved to the game file, and there would need to be some way to switch the message language if the user changes languages from the main menu. I've also been steadily putting fewer and fewer things in the game log.

I might look into letting the player configure how long they'd like the game log to go on for though. Currently it kills messages after 4 lines, but that could easily be increased/decreased.
