### ISSUE TITLE
Challenges may cause empty locked room

### ISSUE THREAD

**Issue by mbakke** [00-Evan/shattered-pixel-dungeon#344]
I have been trying out challenges lately and found a locked room without any items on floor 11. Just a boring old statue and some grass. There was another locked room on the same floor with two blue chests.

This is a Freerunner with all challenges except "pharmacophobia" enabled.

**Comment by 00-Evan** [comment]
Generally this occurs when a room was going to spawn an item that is blocked by the specific challenge.  That empty room was likely an armory room that would have spawned 2 or 3 sets of armor. I am steadily moving challenges away from removing certain items from the game, but for now this is working as intended.
