### ISSUE TITLE
Minor graphical glitch, when Ghost is spawned in a door

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#346]
When the Ghost is spawned in a door, their head is missing. This is only a smaller graphical oversight.

![photo_2019-10-03_12-09-38](https://user-images.githubusercontent.com/3192596/66119254-98c11c80-e5d8-11e9-8c5d-56b1828279ca.jpg)

**Comment by 00-Evan** [comment]
Hmm, this should have been corrected in a previous bugfix, will look into it.

**Comment by 00-Evan** [comment]
fixed in commit 6f1251aeb7093272ff2683812f0f73a91628fa00
