### ISSUE TITLE
Tengu can see me while I'm invisible

### ISSUE THREAD

**Issue by Zoldiru** [00-Evan/shattered-pixel-dungeon#347]
Hello !

I just fought the new Tengu as the thief, and during the last phase of the boss (don't remember if it was the same at the first phase), he was still able to see me while using the cloak or a potion.
Is it a new ability or a bug ?

Thanks :)

**Comment by 00-Evan** [comment]
This is working correctly, I didn't want the cloak of shadows to totally invalidate the new Tengu boss fight. Tengu even announces this by saying: "I can still hear you, Coward!". Note that he does suffer a significant accuracy penalty, so going invisible is still definitely worth it.
