### ISSUE TITLE
HP bar of already killed skeleton

### ISSUE THREAD

**Issue by LyraLover228** [00-Evan/shattered-pixel-dungeon#348]
I fought the necromancer, they summoned a skeleton, I killed it, but the health bar stayed on its place.
![There is a HP bar of killed skeleton](https://user-images.githubusercontent.com/21143379/66712476-cf9bed00-eda5-11e9-9240-6c71932e59cb.jpg)

**Comment by 00-Evan** [comment]
fixed in commit 1b636c7d0d5eef26167dae41a62ac2f3015be188
