### ISSUE TITLE
New text render system

### ISSUE THREAD

**Issue by Vovkiv** [00-Evan/shattered-pixel-dungeon#349]
After update,on russian language,when i open any seed's menu,it looks like this:
![Screenshot_20191013-201310](https://user-images.githubusercontent.com/54743395/66719320-e1f24700-edf6-11e9-993b-ba7b2dc6b43f.png)

**Comment by 00-Evan** [comment]
Please do not report beta issues here, as they don't have an associated source release. You should email me with any issues: Evan@ShatteredPixel.com
