### ISSUE TITLE
Asking for support

### ISSUE THREAD

**Issue by gloeyisk** [00-Evan/shattered-pixel-dungeon#352]
Hello! Is it possible if we make Discord server for this game? Like for Announcements, General and Off Topic chats, Suggestions, or anything else?
It'd be great place to talk between developers, players, and fans. Thank you.

**Comment by 00-Evan** [comment]
Pixel Dungeon does have both a discord server and subreddit which welcome various versions of the game. I am the admin of both of those communities.

Subreddit: https://www.reddit.com/r/pixeldungeon
Discord: https://discord.gg/KBfMN8X

I also do run a Patreon now, and the $200 goal is a specific Shattered Pixel discord server, though that might be a bit more exclusive than what you're asking for: https://www.patreon.com/ShatteredPixel
