### ISSUE TITLE
Corrupting necromancer leaves summons active

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#353]
Killing a necromancer immediately destroys the skeletons it has summoned. However, corrupting a necromancer leaves its summoned skeletons alive and uncorrupted (though new skeletons it summons will start out corrupted). That can result in a nasty surprise if you're focusing on the necromancer and expect the skeletons to die with it.

It seems like either the summoned skeletons should immediately be corrupted along with the necromancer, or the necromancer should "dismiss" them and have them immediately destroyed just as if the necromancer was killed.

**Comment by 00-Evan** [comment]
This is working as intended. When designing necromancers I wanted them to be able to make new summons when corrupted, but that makes them such an extremely powerful corruption target that I decided the corruption shouldn't affect the skeleton they already created.

**Comment by joshtriplett** [comment]
On October 24, 2019 8:43:07 AM GMT+03:00, Evan Debenham <notifications@github.com> wrote:
>This is working as intended. When designing necromancers I wanted them
>to be able to make new summons when corrupted, but that makes them such
>an extremely powerful corruption target that I decided the corruption
>shouldn't affect the skeleton they already created.

That's perfectly fine as a mechanic, but I'm wondering if that could be documented somewhere. I feel like Shattered Pixel Dungeon doesn't normally have "surprise, you're dead, now you know something for your next games" moments, and this was one.

**Comment by 00-Evan** [comment]
I definitely agree that undocumented mechanics and "surprise, you died!" moments are bad (with a few exceptions, e.g. summoning trap rooms) and I do hope to remove them whenever reasonable.

In this case though I don't think there's an elegant way to explain it, and I also don't think it's severe enough to get the player killed unless the run was already in a shaky place to begin with. I also don't think this is super unexpected, as the necromancer isn't dieing and the current default for corruption is not to affect related minions (e.g. rot lashers, yog's larva)

**Comment by joshtriplett** [comment]
> In this case though I don't think there's an elegant way to explain it

Currently, the necromancer has a line in its description saying "Killing the necromancer will also kill the skeleton it summons.", and the skeletons have "This skeleton has been summoned by a necromancer. It behaves just like a regular skeleton, and will die when the necromancer which summoned it is slain.". Adding something short like "The skeleton will fight on even if the necromancer's loyalties change." would suffice.

> I also don't think it's severe enough to get the player killed unless the run was already in a shaky place to begin with.

It's not that the run was shaky, it's that it goes against existing learned tactics involving summoners, namely "make sure to kill the summoner quickly".

Also, this wasn't with a wand, this was with a weapon that randomly ended up with a corrupting brand. So there wasn't a choice to corrupt the necromancer or not.

**Comment by 00-Evan** [comment]
I don't think a sentence in an enemy's description that explains a specific interaction that will show up in very few overall runs is an elegant solution. Including the line about killing the necromancer, by contrast, is highly relevant to basically every run and is an important piece of information that everyone should know before fighting them.

I also don't think this goes against learned strategies, as targeting the summoner is still clearly the better option. You will have to clear the skeleton but your freshly corrupted necromancer is already in the middle of summoning a new skeleton to help. By contrast targeting the skeleton before the necromancer will result in it being healed while it attacks you with no help incoming.
