### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by AndersenJ** [00-Evan/shattered-pixel-dungeon#354]
According to the readme.md in the https://github.com/00-Evan/shattered-pixel-dungeon-gdx repo, this codebase is currently being transitioned to multiplatform support. Is there any recent progress on that? I'm especially interested in desktop support.

**Comment by 00-Evan** [comment]
The readme on this repo actually explains a bit of that state as well. Currently the game compiles for desktop just like the current desktop repo, but is missing many desktop-specific features. You can make release JAR builds but I would only recommend using the desktop functionality in this repo for debugging at the moment. If you don't plan to release right away I would suggest using this repo now, as I intend to bring this codebase into feature parity and retire the current desktop repo sometime around or shortly after the next update (0.7.6).

I'm going to close this as it's not an actual issue, but feel free to reply if you have other questions.
