### ISSUE TITLE
New game on game over popup bug

### ISSUE THREAD

**Issue by valtsu41** [00-Evan/shattered-pixel-dungeon#358]
When I die and open the new game menu (without going to the main menu) and click on the character class details, the info popup goes _behind_ the new game menu popup.

**Comment by 00-Evan** [comment]
I can't reproduce this directly, but this is a known bug in other cases with an easy fix. Will correct in the next update.

**Comment by 00-Evan** [comment]
fixed in commit 1bc5845e7751446cc106128433ab1d1adedafb03
