### ISSUE TITLE
Ankh not generated in shop

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#36]
It looks like there's an issue with the new shop generation code: when I got down to level 11, the shop there didn't have an ankh for sale.  Screenshot:
![ankhless](https://cloud.githubusercontent.com/assets/162737/6433951/385b02ba-c031-11e4-85c8-32948771fbb8.png)

**Comment by 00-Evan** [comment]
This is working as intended. From the tumblr post detailing the update (comes with some extra info): 

>As I reworked how shops work internally in the last update, the limit for items stocked has gone up from ~15 to 39. With all that extra space, I decided to put some more stuff on offer. Players should be less encourage to sell many items, and more encouraged to pick choices strategically with the money they have. Global gold has been increased a little bit to compensate for this. Additionally all shops except the first one (which stocks both) will now stock a weightstone OR an ankh.

This chance was meant as a nerf to ankh stacking.

**Comment by joshtriplett** [comment]
Thanks for the clarification; I only had the release notes to go on, which didn't mention that detail.

I do really like the new shops; in the game that screenshot came from, the level 6 shop had a wand and the chalice for sale, and the level 11 shop had an artifact, the new container, and a wider variety of useful potions and scrolls.

**Comment by 00-Evan** [comment]
Moving forward I always want to offer the release notes ingame, so they'll be a little light on detail. I also post updates to reddit, tumblr, twitter, and facebook, and those posts will contain an extra section with some more detailed info.
