### ISSUE TITLE
Graphics glitch

### ISSUE THREAD

**Issue by nift4** [00-Evan/shattered-pixel-dungeon#360]
https://www.directupload.net/file/d/5651/mmrslxmo_png.htm

It occurred multiple times in the 3 years I have the game.

**Comment by nift4** [comment]
I sadly don't have logs...

**Comment by 00-Evan** [comment]
This is a known bug that has been infrequently reported, unfortunately I have never been able to reproduce it.

The current fog of war code is, quite honestly, a mess, and I will probably be refactoring it at some point in the future. Hopefully that will fix this incidentally.

I've leave this open as a point of reference but action may not be taken on it for a bit.

**Comment by 00-Evan** [comment]
Hopefully addressed as part of code changes in commit 4a6b0130c0c41bd59265583dad02958a52147315

Feel free to comment if you get this again in v0.8.1
