### ISSUE TITLE
Minor graghic bug with wards

### ISSUE THREAD

**Issue by Highseekerz** [00-Evan/shattered-pixel-dungeon#364]
![rlike-20191214-141114-000](https://user-images.githubusercontent.com/24786276/70843793-9baf7780-1e7b-11ea-8f92-68bf39e74029.jpg)
![rlike-20191214-141114-001](https://user-images.githubusercontent.com/24786276/70843795-9fdb9500-1e7b-11ea-8f76-6217d9a15231.jpg)
Ward's frozen effect still appears after its effect ends

**Comment by 00-Evan** [comment]
The version your playing is several patches out of date. The latest public release is 0.7.5e, and the latest beta is 0.8.0-BETA-2.0.

You can update from the releases page [here](https://github.com/00-Evan/shattered-pixel-dungeon/releases), or from Google Play.
