### ISSUE TITLE
Cannot assign some keys to actions in Key Bindings menu

### ISSUE THREAD

**Issue by louisroyer** [00-Evan/shattered-pixel-dungeon#367]
Running [ShatteredPD-v0.8.0-BETA-3.2-Desktop.jar](https://github.com/00-Evan/shattered-pixel-dungeon/releases/download/xbeta/ShatteredPD-v0.8.0-BETA-3.2-Desktop.jar) on debian.
```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)
```
How to reproduce:
- in Key Bindings menu, select any key and try to replace it with `L` or `Y`
- please notice I can still assign some keys as `Q`, `W`, `E`, `R`, `T`
- this has been tested with QWERTY keyboard (`setxkbmap en`)

I suspect only keys present in default key bindings map are allowed, but this is annoying when you want to play fully with keyboard (as I was playing with old gdx port).

Also when using keyboard different from QWERTY (as with `setxkbmap fr` or `setxkbmap fr -variant bepo`), while keys (only keys with same position as well working keys in QWERTY) are correctly assigned, the menu is displaying wrong key label.

**Comment by 00-Evan** [comment]
Should now be fixed as of beta-4.0
