### ISSUE TITLE
Source code inconsistency

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#37]
These are mostly minor issues, but worth mentioning.

- The license boilerplate is missing from some of the files.
- Tabs and spaces are mixed inconsistently.
- Some lines have trailing spaces.

**Comment by 00-Evan** [comment]
yeah I haven't bothered to keep up with some of this. I've tweaked my IDE to make the spacing more consistent (code was tabbed, intellij seemed to like spaces instead) and may make one big change to correct all inconsistencies in future, or just keep slowly correcting them as I go.

Same goes for the licence boilerplate, which I actually should do as the GPL requires it, I'll leave this ticket open as a reminder for that.

**Comment by 00-Evan** [comment]
An update, I'm planning to addressing this immediately after releasing 0.3.0.

It doesn't make sense to do this in the middle of 0.3.0 as I want to keep the change history clean (putting it between releases means people diffing from 0.2.4 to 0.3.0 and 0.3.0 to 0.3.1 won't have to deal with the noise), but it will be resolved shortly after.

**Comment by 00-Evan** [comment]
this has now been addressed in the PD-classes repo, will knock off the other two shortly.

**Comment by 00-Evan** [comment]
fixed in commits cebdff0221c2bffda4a21fa0ae38b134795b83b3 and 684c2caacb1775c98db4fb82306b5893a0c824a3

will also make similar commits to fix any issues with the GDX version.
