### ISSUE TITLE
Feature Request: Export game saves

### ISSUE THREAD

**Issue by urain39** [00-Evan/shattered-pixel-dungeon#371]

**Comment by 00-Evan** [comment]
I don't intent to allow exporting any runs in progress, as it would be extremely easy to use that functionality to cheat. On Android it is also already possible to back up your other game data using Google Play Games, or Androids built in backup functionality.

If/when Shattered becomes available on more platforms, I may look into functionality to let players sync their overall progress between platforms.

**Comment by urain39** [comment]
🤔Okay, thanks reply.

**Comment by mhmdanas** [comment]
> If/when Shattered becomes available on more platforms, I may look into functionality to let players sync their overall progress between platforms.

Now that this is the case, would you mind considering adding this? I don't need some kind of automatic sync; I just want a way to export my overall progress to a file and then import it elsewhere (possibly on another platform).

**Comment by 00-Evan** [comment]
@mhmdanas unfortunately I did look into this and it's not really technically feasible. I would need to set up my own server structure, account system, security, etc.

Save export didn't really work either because the game would need a bunch more permissions to be able to read/write to user storage on phones, and it would make cheating extremely easy.

**Comment by mhmdanas** [comment]
> unfortunately I did look into this and it's not really technically feasible. I would need to set up my own server structure, account system, security, etc.

To be clear, that's not what I'm asking for, I just want the ability to export my data (badges, settings, etc, NOT saves) to a file.

> Save export didn't really work either because the game would need a bunch more permissions to be able to read/write to user storage on phones, and it would make cheating extremely easy.

Why would saving the overall progress (not game saves) make cheating easy? For Android, the permission doesn't have to be granted if the user doesn't want to import/export their data, and also, you could use SAF to only require access to a specific folder for the exports/imports.

**Comment by 00-Evan** [comment]
@mhmdanas players could quite easily download complete save games with all badges from the internet and import them. It doesn't help them win a specific game but does let them cheat the badges screen and rankings.

SAF is sadly not feasible as it only supports down to Android 4.4, Shattered runs on as low as Android 4.0. I would need to have multiple implementations for more recent and older android versions. Permissions also much be declared in Shattered's app manifest, even if they aren't used.

**Comment by mhmdanas** [comment]
Okay then, I don't agree with you, but I respect your decision.
