### ISSUE TITLE
Bug: Cannot leave Level 15, after coming back to it

### ISSUE THREAD

**Issue by daniel-wtd** [00-Evan/shattered-pixel-dungeon#372]
Hey,

first I want to thank you for this cool game.

I think, that I ran into a bug.

After beating the boss at level 15 and descending to 16, I was going back to some previuos level. I found another sword for the Smith ;)
Now, I cannot leave level 15 and descend to 16.

Version: 0.7.1b
OS: Fedora 31
App: via Flathub

Would be awesome, if you can have a look. If any addtional information is needed, please feel free to reach out to.
![Screenshot from 2020-03-12 20-50-00](https://user-images.githubusercontent.com/6490538/76561390-827e8d00-64a3-11ea-817b-ac1ec5bcc4c3.png)

**Comment by 00-Evan** [comment]
So you're unable to descend to floor 16, even after moving to the exit that's 2 tiles above you in the picture?

Unfortunately, there isn't a lot I can do to help you, as you're running an unofficial build of the game based on code that's over a year old. The latest version is 0.7.5e and 0.8.0 is going to come out of beta fairly soon.

**Comment by daniel-wtd** [comment]
yep, that was my problem. Thanks for the clarification :)
