### ISSUE TITLE
Corrupted Summoned Guard doesn't drop weapon

### ISSUE THREAD

**Issue by azrdev** [00-Evan/shattered-pixel-dungeon#373]
Step on an alarm trap to summon the (two?) guards somewhere on the level, similar to the animated statues. When you kill them, they drop their weapon, but when you corrupt them with a staff of corruption, they don't.

Version v0.7.5c from f-droid

**Comment by 00-Evan** [comment]
This is intended. They would be rather useless corruption allies if they were unarmed. When they die after corruption ends they drop their weapon as normal.
