### ISSUE TITLE
Corrupted piranha vanishes when tapped to change places

### ISSUE THREAD

**Issue by azrdev** [00-Evan/shattered-pixel-dungeon#374]
Version v0.7.5c from f-droid

**Comment by 00-Evan** [comment]
Are you switching places with the piranha over land? If so it's probably dieing.

**Comment by azrdev** [comment]
I'm sorry, forgot to describe the circumstances: The piranha is in water (obviously), I'm on an adjacent land tile. So the piranha swaps to a land tile, but even if it died then regularly (and there shouldn't be a safeguard against such action) shouldn't there be a drop (mystery meat) from it, and shouldn't there be a death message in backlog?

**Comment by 00-Evan** [comment]
All of these are intended, but i can understand how it is confusing:
- characters only give a 'you defeated X' message if you actually kill them
- the corrupted prianha won't drop meat as they already give their drop on corruption
- current piranhas are coded to disappear if they are on land, probably I should tweak this to play their death animation instead.

**Comment by 00-Evan** [comment]
Fixed as a part of commit aa263b6f0a4b3884eef57f64d2000f76f6e26398

Relevant changes were in core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/Piranha.java
