### ISSUE TITLE
Tengu's poison trap triggering unexpectedly after beating first stage

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#375]
Version: v0.7.5e

I believe this happens if you get a thrown weapon stuck in Tengu and he happens to be standing on one of his traps before disappearing.

**Comment by 00-Evan** [comment]
This is actually already fixed indev, and will be rolled out with 0.8.0 early next month.

**Comment by 00-Evan** [comment]
Fixed as a part of commit 05363c95fd4c09bc82f25f06d97c59bafdba13be

Relevant changes were to core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/NewPrisonBossLevel.java (Tengu traps are now cleared before tengu is, instead of after.
