### ISSUE TITLE
Random Crashing, Corrupting data Files

### ISSUE THREAD

**Issue by UltraBlackLinux** [00-Evan/shattered-pixel-dungeon#378]
Hello, 
Im on Android 9 and I got those Logs from the (newest version of the) game (sorry for stupid format, forgot adb logcat): [LOG.txt](https://github.com/00-Evan/shattered-pixel-dungeon/files/4407430/LOG.txt)
Please fix this, the game is already hard enough (lol) and it makes me really upset if it corrupts all time.
Ty

**Comment by 00-Evan** [comment]
It looks like your game is crashing in android platform code when it is attempting to save the game. This then results in the save file being corrupted when you open up the game and it tries to load up.

Unfortunately there's nothing Shattered can really do about this. The game is telling your device to write a certain file to disk, and the device is then encountering some sort of error and crashing the app. Usually this is the result of device instability but it's very hard to say for certain.
