### ISSUE TITLE
Boss Floor appears as F1

### ISSUE THREAD

**Issue by Metonym** [00-Evan/shattered-pixel-dungeon#38]
On 0.2.4d, I started a new game as a warrior and was instantly put in front of a boss door.

![screenshot_2015-03-22-22-10-43](https://cloud.githubusercontent.com/assets/6331403/6774765/d8a8a666-d0e2-11e4-9f0c-d1459dc5e7dc.png)

![](https://dl.pushbulletusercontent.com/3optHA6GqZQxy2FLvmDOU40u0r6VdTvN/Screenshot_2015-03-22-22-09-31.png)

![](https://dl.pushbulletusercontent.com/bneCBkiaoQ7DMYDou7eYjSb16yrUYSMy/Screenshot_2015-03-22-22-09-01.png)

**Comment by 00-Evan** [comment]
This has aleady been addressed and an update has been sent out.

Google it taking abnormally long to release said update, so i'm afraid all that can be done atm is wait, will close this once that update is out.

**Comment by 00-Evan** [comment]
update is now available, please update if you're still having this issue.
