### ISSUE TITLE
ghost player after defeat

### ISSUE THREAD

**Issue by binkley** [00-Evan/shattered-pixel-dungeon#381]
I saw this comment on @watabou 's Pixel Dungeon:

https://github.com/watabou/pixel-dungeon/issues/59#issuecomment-609359890

The description from the original poster of that issue thread:

> In certain conditions, a "ghost" of the player can appear after death. Includes but not limited to being killed during movement, in which case pressing the "continue movement" button will spawn the ghost.

Frankly, this sounds neat!  I'm not sure what the "continue movement" button means.  Calling it a bug (as this issue thread does) is maybe not quite right; perhaps it is more of an Easter egg feature.

Is this post-death condition present in Shattered?

**Comment by 00-Evan** [comment]
It is a bug, and is the result of the game not properly recognizing when the hero has died, and allowing them to continue moving while other parts of game logic consider them dead.

I believe this is fixed in Shattered, I haven't heard any reports of it in years.
