### ISSUE TITLE
Desktop packaging

### ISSUE THREAD

**Issue by FantasyCookie17** [00-Evan/shattered-pixel-dungeon#382]
This isn't actually a bug or anything, however I originally installed the Flatpak from Flathub (https://flathub.org/apps/details/com.shatteredpixel.shatteredpixeldungeon) a while ago, and after reading your blog, I noticed that the version there is still at 0.7.1, which isn't the most recent one. I'm not sure whether this is an official build by you, and I don't know how this entire situation will change with the move to LibGDX. It would simply be nice if desktop users could have the most recent version as well. Also the README said that some desktop features were not working? At least arrow keys for movement (though not diagonal movement) and QWER for the hotslots work.

**Comment by 00-Evan** [comment]
Currently any distribution of the desktop version outside of github is unofficial. I'd suggest talking to the maintainers of that build.

**Comment by FantasyCookie17** [comment]
> Currently any distribution of the desktop version outside of github is unofficial. I'd suggest talking to the maintainers of that build.

Ok, so this is indeed not made by you. I should have looked further into it… It was really inactive for quite a while now, so it was probably abandoned.
