### ISSUE TITLE
Keyboard shortcut for sleep

### ISSUE THREAD

**Issue by kjssad** [00-Evan/shattered-pixel-dungeon#383]
version: v0.8.0 for desktop

`ctrl + wait key` doesn't put the character to sleep.

**Comment by 00-Evan** [comment]
I've removed the use of ctrl as a modifier key in the new desktop codebase. There should probably just be a keybinding for sleep, I'll look into adding that in a patch or 0.8.1.

In the meantime, you can sleep by long-pressing the wait button, which is how the functionality is achieved on android phones.

**Comment by 00-Evan** [comment]
functionality added in commit d75fa20337da86493726dfa53540dcefb5bdbdd4
