### ISSUE TITLE
Enemies killed by a blazing weapon could drop grilled meat

### ISSUE THREAD

**Issue by lupino3** [00-Evan/shattered-pixel-dungeon#386]
Hi,
just a minor feature request: when an enemy is killed by a blazing weapon, how about having it drop grilled meat, if it has to drop meat?

If you think this is a good idea, I'd be happy to contribute a patch, if you point me to the code location of the drop.

Thanks!

**Comment by 00-Evan** [comment]
I'd rather not make grilled meat, and by extension frozen carpaccio (as they should be consistent) more accessible. This would make the blazing and chilling enchantments notably stronger, and they are already doing quite well. It's also already possible to grill meat using blazing but requires some planning, as the enemy has to be ignited on/around flammable terrain.
