### ISSUE TITLE
Whip can attack through wall

### ISSUE THREAD

**Issue by naviact** [00-Evan/shattered-pixel-dungeon#388]
In some cases, whip can attack enemies though a wall when using huntresa. One example is through the pillar in a ring hallway. It doesn't work through a door. This may happen for other ranged melee weapons as well.

**Comment by 00-Evan** [comment]
This is intentional, reach weapons are allowed to 'curve' around terrain, but can't go straight through it.

**Comment by naviact** [comment]
I should have guessed such a common situation wouldn't be unresolved at this point. Thanks for the explanation.
