### ISSUE TITLE
Hard reset on Fairphone 3

### ISSUE THREAD

**Issue by berangersix** [00-Evan/shattered-pixel-dungeon#389]
The game sometime reset the phone ( black screen for some ms followed by a phone restart). It mostly happen during level changed( juste after using stair).
The save could be lost. The phone is on Android 9. 
I have no clue of the cause, i will post a log.

**Comment by 00-Evan** [comment]
The game crash may be the game's fault but the only way for it to prompt a device-wide crash is if there is some other hardware of operating system issue present.

Without some kind of details or logs there's really nothing I can do about this. If you are able to post a log then I will re-open the issue.

**Comment by berangersix** [comment]
Hello,
Sorry for the delay, it took me some times to root my smartphone for log.
Here you could find 2 logs. I do log running a script bch.sh. This script continuously write dmesg and logcat to file, and stop when phone reset. If you have other idea, I am open to suggestions.
[bugspd389_a.zip](https://github.com/00-Evan/shattered-pixel-dungeon/files/4606254/bugspd389_a.zip)
This crash seems to only happen with mage, my game is in French.
Reading the log, i see these strange results : 
1.Audio library crash 
W/AudioTrack(10002): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 18432
2.File saving
05-08 16:14:56.832 E/storaged(  711): getDiskStats failed with result NOT_SUPPORTED and size 0
3.libprocessgroup kill.

Sorry for not doing better report, but i am a android beginner.
Regards,
Beranger Six

**Comment by 00-Evan** [comment]
I don't think you need root to copy logcat output, but thank you regardless.

All of the log messages I can see relating to shattered look pretty normal. The audio output messages are fairly common and just mean that the device didn't want to play the sound effect in low latency mode, and that shouldn't result in instability. The file saving message isn't even related to Shattered (different process ID). I also don't see any stack traces or tombstone messages that would point toward crashes or errors in Shattered's code. I do see some stack trace messages but they're all happening at the system level, and may be totally normal.

The fact that audio log messages are showing up just before the log ends on both cases definitely points towards sound effect playback as a possible cause, but there shouldn't be any reason why that would cause your device to crash, at least on Shattered's end. You could try turning off sound effects if you wanted to test that.

This message on your log is also troubling, though I have no idea how common using debug kernels in production is:
```
[    0.000000] **********************************************************
[    0.000000] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    0.000000] **                                                      **
[    0.000000] ** trace_printk() being used. Allocating extra memory.  **
[    0.000000] **                                                      **
[    0.000000] ** This means that this is a DEBUG kernel and it is     **
[    0.000000] ** unsafe for production use.                           **
[    0.000000] **                                                      **
[    0.000000] ** If you see this message and you are not debugging    **
[    0.000000] ** the kernel, report this immediately to your vendor!  **
[    0.000000] **                                                      **
[    0.000000] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[    0.000000] **********************************************************
```

I'd suggest contacting the manufacturer of your device, you may have a hardware or firmware error that Shattered is exposing for some reason.
