### ISSUE TITLE
Level 1 needs to be more interesting

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#39]
In most cases, after fully exploring level 1, I have to walk around a lot, wasting hunger, just to get enough experience to level up.

**Comment by 00-Evan** [comment]
There's no hard requirement to level up on floor one, it's entirely reasonably to level up early in floor 2 instead. How would you propose making the first floor more 'interesting', especially considering that new players start there?

**Comment by nyuszika7h** [comment]
I know, but I heard it's better to be at least on the same level as the floor you are on, because things are generated based on your level, or something like that.

**Comment by 00-Evan** [comment]
That's partially true. It is a good idea to keep your level roughly the same as the floor you're on, as gaining levels make your character significantly stronger. level and item generation is not affected by your level however.

I'll take a look into exp on level 1 though, I do agree that, given rats only give 1 experience point, you can often not have much exp going into level 2 without doing additional hunting.

**Comment by 00-Evan** [comment]
After investigating this I've made some tweaks to the way floor 1 level generation works. Basically, the game will now more generously place rats on the first floor, such that if you fully explore it, you are garunteed level 2. 

This will be available as part of 0.3.0

**Comment by 00-Evan** [comment]
fixed in commit 9fad20a071ce431e03929af098b2d588225855df
