### ISSUE TITLE
chmod +x ./gradlew

### ISSUE THREAD

**Issue by TheYsconator** [00-Evan/shattered-pixel-dungeon#393]
This is more of a personal request than a bug, but could you give the gradlew file execution permissions and push that? I mean, most of the people that would want to build for desktop using terminal (on Mac, at least) will have to give that file +x permissions anyway.

**Comment by 00-Evan** [comment]
Will look into this, should be a simple tweak to the file's properties on git.

**Comment by TheYsconator** [comment]
Ah before spending too much time on it; I'm able to literally just do 'chmod +x ./gradlew', and then git status gives me one changed file that I can stage and commit.

Let me know if that doesn't work for you, then I can help you figure out why that doesn't work for you - if you want. This shouldn't be something that costs you too much time, at all.

**Comment by 00-Evan** [comment]
I'm on windows but git supports linux style syntax for changing file permissions regardless of OS. It's a simple `git add --chmod=+x -- gradlew`

**Comment by 00-Evan** [comment]
fixed in commit e23d618c242d849d847dd0da86f5d8ceea7fe79d
