### ISSUE TITLE
One-hit corruption

### ISSUE THREAD

**Issue by Xylonator5** [00-Evan/shattered-pixel-dungeon#394]
I was playing through as a rogue (assassin), somehow was able to have use of the Assasins Blade, enchanted it with corruption, and hence I was able to one-shot various enemies. In some occasions, when I one-shot an enemy and it gets corrupted, the enemy just disappears and doesn't fight for me, it just vanishes, but you can still see the health bar and see it taking damage (due to the corruption)

**Comment by 00-Evan** [comment]
Fixed as part of assassin changes in commit fa4d0e908d3bbf88d1a6fc088e3ac8120c899df2
