### ISSUE TITLE
Cannot use scroll of remove curse against armor degradation

### ISSUE THREAD

**Issue by TheSSJ** [00-Evan/shattered-pixel-dungeon#395]
I noticed that the description text for degradation mentions that the curse can be immediately lifted with a scroll of upgrade or remove curse. While it indeed works for the scroll of update I cannot apply a scroll of remove curse as the armor I am wearing is "greyed out"

So either the degradation curse description should be amended or the armor would need to be treated as cursed so that you can use the appropriate scroll

**Comment by 00-Evan** [comment]
Probably the best course of action here is to lift the restriction on using remove curse when the item's true level doesn't match its effective level.

**Comment by 00-Evan** [comment]
fixed as a part of commit e49eb27a12bb16d753d35f8ebd1b11f98bdb5efd , specifically the changes to ScrollOfRemoveCurse.java
