### ISSUE TITLE
Enemy that interrupts Huntress' sleep is sometimes not visible

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#396]
Version: v0.8.0a

As the Huntress, when your sleep gets interrupted by sensing a nearby enemy (without having a direct line of sight), that enemy won't be drawn, but can still be examined and shows on the enemy indicator. Manual waiting does not have this problem.

**Comment by 00-Evan** [comment]
fixed as a part of commit e49eb27a12bb16d753d35f8ebd1b11f98bdb5efd , specifically the changes to checkVisibleMobs() in Hero.java
