### ISSUE TITLE
Corrupted entities attack sleeping mimics

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#398]
I've noticed in 2 different necromancer runs that my corrupted ghosts will search for and attack mimics. I would suggest corrupted entities to ignore sleeping mimics, because first of all it defeats their purpose and it could be potentially dangerous to start an unwanted fight. I would generalize and propose not to attack entities that are not hostile until attacked, for example statues, but my problem is with mimics. They are supposed to be a surprise.

Version : 0.8.0b

**Comment by 00-Evan** [comment]
The game makes a distinction between intelligent ally characters and non-intelligent ones. Generally intelligent allies are meant to go with the player and complement them, whereas non-intelligent ones are meant to act more independently.

Non-intelligent allies will attack a potential target regardless of its state, intelligent allies will ignore potential targets that are wandering, passive, or asleep.
