### ISSUE TITLE
Allow for quick-slot, wait, search, and inventory buttons to be on the left or right of the screen. 

### ISSUE THREAD

**Issue by brainard52** [00-Evan/shattered-pixel-dungeon#399]
I've got a particularly long phone in the XL variety, and it's uncomfortable to play this one-handed. Part of this is the placement of the buttons mentioned in the title.
![signal-2020-05-15-081759](https://user-images.githubusercontent.com/1023838/82064643-e7ac5580-9681-11ea-8994-6fe9f2e1d00e.jpg)

I think it would be nice to have the option of putting them on the left or right of the display. 
![InputMode](https://user-images.githubusercontent.com/1023838/82064710-fe52ac80-9681-11ea-9500-b6b6de8e4e39.png)

**Comment by 00-Evan** [comment]
I've actually been trying to pull back on the options menu as it's currently a bit of a bloated mess, with several choices used by only a tiny percentage of the playerbase (e.g. the option to have less than 4 quickslots, which I removed in 0.8.0). I don't really think it's feasible to support yet more placement options for the toolbar that will rarely be used, especially when putting it on the side would interfere with the indicators that currently go there.
