### ISSUE TITLE
An object on the floor fly if you pick it repeatedly with a full backpack

### ISSUE THREAD

**Issue by valerio-bozzolan** [00-Evan/shattered-pixel-dungeon#40]
A minor graphic bug.

Yes, the Seed is under my feet.

![photo238939261744818280](https://cloud.githubusercontent.com/assets/6052909/6857985/107d336a-d40b-11e4-9146-ac7ee8ad8fe6.jpg)

**Comment by 00-Evan** [comment]
This is a known issue.

Won't fix.

Too funny =P.

**Comment by anubiann00b** [comment]
Why would you not fix it? Personally I think it feels more like a bug than a possible easter egg...

It is hilarious though :)

**Comment by 00-Evan** [comment]
It is a bug, but not all bugs need to be fixed.

it's fairly rare (need a full invent + a pile with two or more items), and it is hilarious + causes no harm or real confusion.

It's like giants launching adventurers into orbit in skyrim, the bug has earned the right to stay.
