### ISSUE TITLE
Introduction: flathub app

### ISSUE THREAD

**Issue by daniel-wtd** [00-Evan/shattered-pixel-dungeon#400]
Hi,

I am one of the maintainer for shattered pixel dungeon over at <https://flathub.org>. I just wanted to introduce mysqlf and ask, if you want to add the flatpak option to your installations. If we need to meet some certain requirements or in case you want to discuss this with me, please feel free to ping me :)

- flathub: <https://flathub.org/apps/details/com.shatteredpixel.shatteredpixeldungeon>
- repo: <https://github.com/flathub/com.shatteredpixel.shatteredpixeldungeon>

We are currently having 0.8.0b with jdk11 bundled and the game is awesome as it is.

Hope, we can work together on this cool piece of software and I can support you spreading the desktop application.

Best Regards,
Daniel

**Comment by 00-Evan** [comment]
Hey Daniel,

I had noticed the flathub build a little while ago, thanks for helping spread the game, and for keeping it updated after the codebase recently changed.

While I'm happy to allow builds/distributions from others, I'm not currently looking to officially distribute the desktop version beyond github just yet. Probably when I do I'd prefer to start with a multiplatform service such as itch.io or steam.

I'm closing this for the sake of housekeeping but please feel free to reply.

**Comment by daniel-wtd** [comment]
Hi @00-Evan,

thank you for your response. Distribution via steam or itch.io sounds awesome. :+1: 

Keep up the good work, I will try to keep the flatpak updated. ;)

**Comment by PerAstraAdDeum** [comment]
Hi @00-Evan,

please authorize @dschier-wtd as a third-party distributor for your game. The game could then be [verified](https://docs.flathub.org/docs/for-app-authors/verification) on Flathub, which would add another layer of trust and raise confidence in the Flatpak. From what I understand, this wouldn't come with any extra maintenance burden for you.

It would allow a safe and easy way to enjoy the game for those players that aren't on Steam or Itch.io, and could therefore help spreading the game!

Best regards

**Comment by 00-Evan** [comment]
> Hi [@00-Evan](https://github.com/00-Evan),
> 
> please authorize [@dschier-wtd](https://github.com/dschier-wtd) as a third-party distributor for your game. The game could then be [verified](https://docs.flathub.org/docs/for-app-authors/verification) on Flathub, which would add another layer of trust and raise confidence in the Flatpak. From what I understand, this wouldn't come with any extra maintenance burden for you.
> 
> It would allow a safe and easy way to enjoy the game for those players that aren't on Steam or Itch.io, and could therefore help spreading the game!
> 
> Best regards

Sorry but I'm not interested in authorizing or otherwise endorsing unofficial distributions of Shattered Pixel Dungeon. People are welcome to keep making them though, of course.

**Comment by ElonSatoshi** [comment]
I'd love to see an official Flatpak distribution
