### ISSUE TITLE
Reloading causes Tengu's puzzle traps to vanish

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#401]
Version: v0.8.0b

As you enter a puzzle room, you get a glimpse of the traps until the end of the turn. However, if you exit the game and reload, the traps will vanish even though you didn't move or anything.

**Comment by 00-Evan** [comment]
fixed as a part of commit e49eb27a12bb16d753d35f8ebd1b11f98bdb5efd , specifically the changes to the FadingTraps class in NewPrisonBossLevel.java
