### ISSUE TITLE
Gold can spawn on Dwarven Metropolis walls

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#402]
Version: v0.8.0b

This can occur on the new DM-300 floor, which features walls from both Caves and Dwarven Metropolis. The gold is not visible but the gleaming effect is there. I haven't tried mining it.

**Comment by 00-Evan** [comment]
fixed as a part of commit e49eb27a12bb16d753d35f8ebd1b11f98bdb5efd , specifically the changes to NewCavesBossLevel.java
