### ISSUE TITLE
Charmed enemies receive healing from Wand of Transfusion

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#404]
Version: v0.8.0b

Including the undead. I'm not sure whether this is intended or not. Are charmed enemies considered allies? If they are, then you can close this but I would appreciate if you made the wand's description more clear.

**Comment by 00-Evan** [comment]
This is intended, as charmed enemies are considered to be allies by transfusion. Gameplay-wise this is mainly to prevent the player from using a single enemy as a constant shield battery during a multi-enemy fight.
