### ISSUE TITLE
Non-blessed ankh resurrection causes mimics to stop hiding

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#406]
I referred this on reddit, I thought it might be intentional, but you said you are aware of the bug. So, I looked at the code and I think I found the **cause** and the potential **solution**.

When the player dies with ankh, [resurrect()](https://github.com/00-Evan/shattered-pixel-dungeon/blob/de448a09932fe6510deefdf5ffe23994b6b368f0/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/scenes/InterlevelScene.java#L400) is called from [InterlevelScene](https://github.com/00-Evan/shattered-pixel-dungeon/blob/de448a09932fe6510deefdf5ffe23994b6b368f0/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/scenes/InterlevelScene.java).
That calls [Dungeon.resetLevel()](https://github.com/00-Evan/shattered-pixel-dungeon/blob/de448a09932fe6510deefdf5ffe23994b6b368f0/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/scenes/InterlevelScene.java#L411), which calls [reset()](https://github.com/00-Evan/shattered-pixel-dungeon/blob/de448a09932fe6510deefdf5ffe23994b6b368f0/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/Dungeon.java#L319) from [Level](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/Level.java) class.
That function iterates every mob in the level and calls the [reset()](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/Level.java#L288) function.
Now, mimics have `state = WANDERING;` in their [reset()](https://github.com/00-Evan/shattered-pixel-dungeon/blob/de448a09932fe6510deefdf5ffe23994b6b368f0/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/Mimic.java#L252) function.
That means, when it acts via [act()](https://github.com/00-Evan/shattered-pixel-dungeon/blob/de448a09932fe6510deefdf5ffe23994b6b368f0/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/Mimic.java#L125) function it checks whether it's not in `PASSIVE` state. More specifically, the condition is `alignment == Alignment.NEUTRAL && state != PASSIVE` and because it's not, it's revealed, calling its superclass' act() function, wandering for enemies.

Shouldn't it be `state = PASSIVE;` in the `reset()` function of every mimic class instead? Correct me if I'm wrong and not aware of some other case.

![101522196_869244460210715_950528347673198592_n](https://user-images.githubusercontent.com/1816060/83679377-fda99800-a5e7-11ea-8aa4-93d4e4bdb2f7.png)

**Comment by 00-Evan** [comment]
Thank you for the effort but I don't accept code contributions due to complications involving the GPLv3 license. I'll look into this for 0.8.1 but I hope you don't mind if I don't look at your suggested fix.

**Comment by Leajian** [comment]
Yeah, that's why I didn't fork, I didn't want to make another modified version of a modified version of the game. Complicates stuff. My suggested fix was an assumption, I might be wrong and I haven't tested it. You know the code better, I just looked on it for 5 hours. You do you, no problem.

**Comment by 00-Evan** [comment]
Fixed as a part of commit 2a622dc5f69e1994f163d9a4722d0826269c454a , specifically the changes to Mimic.java
