### ISSUE TITLE
RFE: stop on dew

### ISSUE THREAD

**Issue by whitel** [00-Evan/shattered-pixel-dungeon#410]
I think it would help gameplay if the player would stop running if they encountered a dew drop or a seed. I hate going one step at a time in a long row of grass but if I don't, I have to retrace my steps.

**Comment by 00-Evan** [comment]
Currently there are no cases where the hero pauses upon discovering an item, and I don't think that's good functionality to add as items aren't a threat like enemies are. Grass is also often moved through or around during combat, and interrupting motion in those cases would be very annoying.
