### ISSUE TITLE
Enhancement of Troll Blacksmith 

### ISSUE THREAD

**Issue by Aristurtlez** [00-Evan/shattered-pixel-dungeon#412]
Troll Blacksmith sounds really bad-tempered lol, but I'm wondering if more levels can be kept when you combine two identical equipment (e.g. you get a +3 instead of +2 plate armor when you combine two +1 ones), maybe by means of killing more enemies or cellecting more ore. Also, it would be great if I could combine identical equipments for multiple times.

**Comment by 00-Evan** [comment]
Upgrade transference is extremely powerful. I'd rather not amp up that aspect of the reward as a found upgraded item shouldn't just be able to be directly converted into upgrades for something else.

I am aware that the quest and reward are very lackluster though, and I do intend to improve them in the future.
