### ISSUE TITLE
tengu loses doom

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#414]
If you corrupt tengu until he gets the doom debuff in his first phase, he no longer has doom when he returns for the second phase, even though doom is supposed to be permanent until death.  Similarly, he teleports even when he's paralyzed.

**Comment by 00-Evan** [comment]
Previously this was intended, as Tengu was meant to be refreshed between phases. We now have a bunch more multi-phase bosses that don't exhibit this behavior though, so I'll change this.

**Comment by 00-Evan** [comment]
Fixed as a part of commit 5594172a416a029743e5cf5815ea8442abab5305 , specifically the changes to NewTengu.java and NewPrisonBossLevel.java
