### ISSUE TITLE
0.8.0b killed by friendly ghost

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#415]
I made the mistake of giving the friendly ghost (controlled with rose artifact) a shocking spear in 0.8.0b.  I ran up to a gnoll scout and fly and the friendly ghost killed us all in one hit.  I was hoping that I would at least get a badge for getting killed by an ally since it's not that easy to do :p. Is it intentional that the ghost's shocking spear hit me or is this a bug?  I know you don't get hit by your own shocking weapon.

**Comment by 00-Evan** [comment]
This is correct as of 0.8.0b, as shocking can harm allies. It's actually being adjusted to not harm them in 0.8.1 though.
