### ISSUE TITLE
0.8.1: Wand of Fireblast hurts hero

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#416]
First of all, thank you for the great work on 0.8.1. I really love that rings have now icons and the great artwork and new SFX.

Here is one bug, however. If the hero uses the Wand of Fireblast or a Potion of Dragon’s Breath and stands on a door or a grass tile, the hero is hurt by the fireblast. This behavior was different before. I guess, that is not intended.

**Comment by 00-Evan** [comment]
This was the original functionality of those items, but they were buffed a while ago to have less self-danger. This is unintended and I'll likely fix it in 0.8.1-beta-2

**Comment by 00-Evan** [comment]
Resolved in Beta-2
