### ISSUE TITLE
extinguish fire on self with frost wand

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#417]
In 0.8.0b.  Caught on fire with no water nearby (fire trap next to stairs).  Seemed unfair that I couldn't extinguish it by shooting myself with my wand of frost (can't target self).  I think I could put out fire on enemies with the wand, just not fire on myself.  And of course a potion of frost can be used to extinguish fire.  So it seems like, for consistency, wand of frost should be able to remove burning debuff on player.

I found water on a different level by taking the stairs, so I put the fire out.  But of course every time I returned to the level I caught on fire again because little time had passed for the fire on the stairs!  Eventually escaped by reading teleport scroll immediately from the stairs before catching on fire again.

**Comment by 00-Evan** [comment]
The consistent behavior is that wands cannot self-target. This is done to prevent accidental self-shots which can be extremely deadly with a highly upgraded wand. I'd rather not let wands self-target for this reason, and I also prefer not to make extremely specific rules like "cannot self target unless you're using a wand of frost and are on fire and the wand is low enough level to not seriously hurt you."

**Comment by protective1** [comment]
Would it make sense for the wand of frost to be able to shoot the neighboring ground and leave a chill square for a turn (that you could walk into)?  Or is hitting the ground inseparable from the pressure that can spring traps (blast and corrosion wands), which would make it overpowered?

**Comment by 00-Evan** [comment]
The wand currently doesn't target specific tiles, again I don't really think it's a good idea to change its general behavior for such a specific niche function.
