### ISSUE TITLE
can't place ward there costs turn

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#418]
Is it intentional that in 0.8.0b, getting the message "you can't place a ward there" costs you a turn? This feels unfair because other wands don't have that turn cost.  Wand of warding already feels a bit less powerful than other wands, and amazingly / unfortunately I found 3 wands of warding in a row so I used them quite a bit, even though it took 6 turns to set one up with all three wands.  I eventually died (with 10 healing potions) standing next to my ward because I didn't realize monsters don't prioritize hitting wards like they do earth elemental and I didn't realize that I was getting hit.

**Comment by 00-Evan** [comment]
Other wands also cost a turn when you miss, so this is consistent with their behavior. Wands cost no time when they cannot zap at all, and warding is consistent with other wands in that way.

I'm actually tweaking warding in 0.8.1 regardless though, to substantially reduce the cases where you can't place a ward somewhere.
