### ISSUE TITLE
Effects on floor tiles can be seen even outside line of sight

### ISSUE THREAD

**Issue by Random-Chain** [00-Evan/shattered-pixel-dungeon#419]
Version 0.8.0b

You can see effects on floor tiles like gas or fire by examining them, even if this tile is not in your line of sight. Tile description is updated when the effect is gone, so you can e.g. stay outside a room where a gas trap was activated and keep examining the floor until you see the gas is gone.

![Screenshot_20200619-221725](https://user-images.githubusercontent.com/58945606/85375639-42698480-b53f-11ea-8f53-93c7dcd3b6e3.jpg)

**Comment by 00-Evan** [comment]
Fixed as a part of commit 5594172a416a029743e5cf5815ea8442abab5305 , specifically the changes to WndInfoCell.java
