### ISSUE TITLE
Look across the big door of Level 5?

### ISSUE THREAD

**Issue by valerio-bozzolan** [00-Evan/shattered-pixel-dungeon#42]
![tmp_4690-screenshot_2015-03-31-14-20-521703272295](https://cloud.githubusercontent.com/assets/6052909/6935031/681383a4-d83e-11e4-85e8-a01699d67be6.png)

**Comment by 00-Evan** [comment]
This is a bug which pops up from time to time. Basically as a quirk of the game's level gen logic, it is very unlikely, but possible for this to happen.

I had hoped to have fixed it through other means but it seems like it can still happen rarely, i'll include a direct check for this next update which should finally completely kill this bug.

**Comment by valerio-bozzolan** [comment]
Can't the room simply have two other walls in the top? Near to the already existing single wall (the one after the door)?

**Comment by 00-Evan** [comment]
@valerio-bozzolan the intention is that rooms which collide with the exit, like what you see here, shouldn't happen. Forcing the tiles around the exit to be walls would work in most cases, but might introduce further problems (e.g. blocked hallways). I've got what I'm pretty sure is a solution which will 100% prevent rooms from spawning in the manner shown in the picture, which should resolve the problem permanently.

**Comment by 00-Evan** [comment]
This issue has been fixed indev, will be closed and commit referenced when the source for 0.3.0 is released.

**Comment by 00-Evan** [comment]
fixed in commit 08e77371114a76c99c08233d0b4a33d11cb8e744

**Comment by valerio-bozzolan** [comment]
Thanks!
