### ISSUE TITLE
v0.8.0: Burned down grass in a garden room is displayed as normal stumps

### ISSUE THREAD

**Issue by anarchuser** [00-Evan/shattered-pixel-dungeon#420]
(Android 6.0.1, v0.8.0)

I noticed in several independent runs that burning down grass in the special "Garden" rooms burns down the grass as intended, but continues using the sprite for unburned grass.
This "unburned" grass won't burn again; it behaves as it should.

The attached screenshots show such a situation:
* First, I burned down the whole room (notice the burned-down door at the entrance)
  * This burned down all the grass normally but displayed the old sprites
* Secondly, I used the Wand of Fireblast again - See first screenshot.
* Thirdly, on the immediately next turn - See second screenshot - the fire disappeared as expected from a non-inflammable floor

Notes:
* I could reproduce this in other runs on other floors (I haven't checked on all)
* I haven't checked if this happens every time or only casually (I usually don't burn down my precious dungeon)

![Shadow Grass while burning](https://user-images.githubusercontent.com/5949896/85391644-bcebd180-b54a-11ea-9ba8-bceca5a00515.png)
![Shadow Grass after burning](https://user-images.githubusercontent.com/5949896/85391653-bfe6c200-b54a-11ea-9ddb-801d7ef5e38b.png)

**Comment by 00-Evan** [comment]
This is intended, the grass in garden rooms is constantly being replenished.
