### ISSUE TITLE
Crystal mimic freeze freeze 

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#421]
I saw a room with crystal mimic
Planted icecap in the door to freeze it
I was standing next to the icecap and got frozen along with the mimic as it ran
But the whole game freezes too
When I force quit and restarted the floor's progress was not saved.

**Comment by MrCocoNuat** [comment]
V0.8.1 beta 2

**Comment by 00-Evan** [comment]
Icecap affects a 3x3 AOE, so you becoming frozen is intentional. I'm not able to reproduce that game freezing issue, although force-quitting the game would result in lost save data as the game wouldn't have the chance to save.

Feel free to comment if you encounter this problem again.
