### ISSUE TITLE
Shadowmeld invis sound when loading game

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#423]
Stand in a garden for shadowmeld, then quit. When resuming, while the game loads, the "whoosh" of invisibility effect starting is heard.
Since neither cloak or potion do this I think this is unintended.

V0.8.1 beta2 but probably didn't start happening here?

**Comment by 00-Evan** [comment]
Fixed in commit 9cd9cb573086719376c82bb5485fc0fc0e591e85
