### ISSUE TITLE
Error: Could not find or load main class ShatteredPD-v0.8.1-BETA-2-Desktop.jar

### ISSUE THREAD

**Issue by Jung504** [00-Evan/shattered-pixel-dungeon#424]
java version "1.8.0_251"

**Comment by 00-Evan** [comment]
0.8.1-BETA-2 is no longer available, do you get the same error with the release version of 0.8.1? Could you also please include the full error message, such as in a screenshot?

**Comment by Jung504** [comment]
I get the same thing with 0.8.1.  That is the full error message. Launching by clicking the .jar just silently fails.

C:\Users\J\Downloads>java ShatteredPD-v0.8.1-Desktop.jar
Error: Could not find or load main class ShatteredPD-v0.8.1-Desktop.jar
C:\Users\J\Downloads>

**Comment by bwitt** [comment]
I think you have to say something like `java -jar ShatteredPD-v0.8.1-Desktop.jar`
