### ISSUE TITLE
Music sources?

### ISSUE THREAD

**Issue by GuiltyPixel** [00-Evan/shattered-pixel-dungeon#425]
I want to hack on the title theme, but I noticed that the original files are not tracked. Can we get a folder for musical asset sources? Just include a readme.md with info about any required VST plugins, samples, etc., the author data, and the license released under. If it's all in some proprietary format, we could work with note data from each track exported as midi or something else interoperable.

**Comment by 00-Evan** [comment]
I'm afraid there are no available sources for the game's music files, just the assets that are packaged with the game.
