### ISSUE TITLE
Sometimes picked up items don't show up in the bag

### ISSUE THREAD

**Issue by Kishan-Gupta** [00-Evan/shattered-pixel-dungeon#427]
The item shows up after I close and re-open the bag.

I couldn't reproduce it at will. What information should I gather the next time it happens?

**Comment by 00-Evan** [comment]
any information at all about what circumstances this occurred in would be helpful, there isn't really much for me to go on here. It's definitely not happening generally or I'd be getting lots of reports. For now I'm closing this issue as there are no actionable details, but feel free to comment if you get this issue again.
