### ISSUE TITLE
[Minor] Final screen (Earthen Guardian and the Sad Ghost)

### ISSUE THREAD

**Issue by Nimn** [00-Evan/shattered-pixel-dungeon#428]
When finishing with Living Earth Wand and the Sad Ghost, only the Earthen Guardian is shown on the final happy ending screen. It would be nice to display both.

Thanks for your very good work!

**Comment by 00-Evan** [comment]
This is intended, I didn't want a bunch of allies to crowd out the ending screen, especially as I may add more in the future. The game tries to look at what things you've levelled and picks based on that.

**Comment by Nimn** [comment]
It is a game design choice. Ok!
My earthen guardian and the sad ghost made a great team at the end of the game and I expected to see them both for the final picture ;)
