### ISSUE TITLE
Ripper leap glitch

### ISSUE THREAD

**Issue by GuiltyPixel** [00-Evan/shattered-pixel-dungeon#429]
A ripper demon jumped at me while I was surrounded and occupied the same tile as the PC.

![Annotation 2020-06-29 211000](https://user-images.githubusercontent.com/12185502/86075172-035e9600-ba4d-11ea-9153-fa33b797a1be.png)

Version 0.8.1-desktop

**Comment by 00-Evan** [comment]
This is intended, rippers will stay ontop of their target in the very rare case that they don't have an open adjacent tile to move to.
