### ISSUE TITLE
Hunger: Challenging or Punishing

### ISSUE THREAD

**Issue by anubiann00b** [00-Evan/shattered-pixel-dungeon#43]
This is more of a game design issue.

Hunger is a very core component of the game. I feel like it's not challenging, but instead punishing.

The problems I see are:
 * If you explore or wait for too long you can starve with no hope of even finding enough food to recover
 * If you die you're sent back to the very beginning of the game, losing all progress.

Don't get me wrong, those are both very traditional aspects of a roguelike that I myself often enjoy. On the other hand, making the game less punishing would appeal to a larger audience and make the game more fun overall..

Check out these resources on game challenge:

http://plus10damage.com/blog/2015/2/4/challenge-vs-punishment-the-difference-between-good-and-bad-difficulty
https://www.youtube.com/watch?v=ea6UuRTjkKs

**Comment by 00-Evan** [comment]
Hey, apologies for the delay in my reply. Been delaying with lots of messages and dev work and this must have slipped through the cracks.

Firstly, more as a note on semantics, I seriously disagree with the negative use of the word punishing here. Punishing implies that the game is hard on the player for making mistakes, which is a necessary component of challenge. If you fail to time a jump well in super meat boy, for example, you are punished with death, but get to try again. Certainly a game can be too punishing(e.g. meat boy with permadeath), but in the same vein a game could be said to be too challenging.

I think it is more an issue of fairness, consistency, and a proper difficulty curve, which I do think are relevant here. Hunger is obviously consistent, but I do agree that it can be perceived as unfair, and I also agree that PD's difficulty curve is too heavily slanted towards the earlygame, perhaps as an artifact of a time when the game only had 5 floors. Hunger is not difficult to deal with for vets as they understand it's more of a strategic resource than a meter they need to keep topped up. Giving that knowledge to new players is something I've tried and has success at, but I am always looking for little ways to reduce the pressure of hunger in the earlygame.

I am considering rebalancing how much damage hunger does throughout the game as well (to perhaps make it more relevant late), if I do so I will likely also reduce the damage a bit in the earlygame, again to make players feel less pressured into constantly keeping their hunger topped up.

However, the core principle of dawdling = starving = dieing = retrying is appropriately punishing and is not something I am going to change.

**Comment by anubiann00b** [comment]
Semantically, I see challenging/punishing as a fine line that you want to stay just on the right side of.

I like the idea of scaling down the damage early. It maintains the core mechanic without making it too difficult for new players.

**Comment by 00-Evan** [comment]
I'm closing this ticket as discussion has ended, please feel free to comment again and I'll re-open.

When I do make changes to hunger I'll consider what I mentioned above.
