### ISSUE TITLE
CeremonialCandle invisible

### ISSUE THREAD

**Issue by GuiltyPixel** [00-Evan/shattered-pixel-dungeon#430]
I had an unobtainable ceremonial candle spawn. I searched the whole map, then opened the map file and changed the candle position to a known position using another obj for reference. But it was still invisible... I tried another location, still, just 3 candles in total. it even said 'seen' in the file. Soooo... I changed my inventory count to 4 and proceeded. Here is the map data: 

[depth9.dat.zip](https://github.com/00-Evan/shattered-pixel-dungeon/files/4849032/depth9.dat.zip)

**Comment by 00-Evan** [comment]
In the save file you provided the 4th candle was immediately above the exit stairs, underneath two maces.
