### ISSUE TITLE
Deadlock during Yog fight

### ISSUE THREAD

**Issue by GuiltyPixel** [00-Evan/shattered-pixel-dungeon#431]
"SHPD Render Thread":
  waiting to lock monitor 0x000002b1cfd1ee80 (object 0x00000000c7fbf6f0, a com.shatteredpixel.shatteredpixeldungeon.sprites.FistSprite$Rusted),
  which is held by "SHPD Actor Thread"
"SHPD Actor Thread":
  waiting to lock monitor 0x000002b1cfd24280 (object 0x00000000c7f3ab98, a com.watabou.noosa.Group),
  which is held by "SHPD Render Thread"

[thread-dump.txt](https://github.com/00-Evan/shattered-pixel-dungeon/files/4849922/thread-dump.txt)

v 0.8.1-desktop

**Comment by GuiltyPixel** [comment]
My Java debugging skills are rusty but let me know if I can provide anything else.

**Comment by 00-Evan** [comment]
A few people have reported a similar deadlock, seems to happen when multiple characters freeze at the same time. Probably needs a sync block somewhere.

**Comment by 00-Evan** [comment]
(hopefully) fixed in commit ea4d45da7f82d3e92a0b57f765bfd0903ee59dff
