### ISSUE TITLE
mimics are too easy to identify  

### ISSUE THREAD

**Issue by medrod** [00-Evan/shattered-pixel-dungeon#433]
first approach
- place your character next to a chest 
- move to the opposite site of the chest
- if you go though the chest it's not a mimic

 second approach
- enter a room with chest 
- leave the room
- if chest is still visible it is not a mimic

**Comment by 00-Evan** [comment]
Mimics are not supposed to be hard to identify if you pay attention or have a strategy for them. Making the tricky to identify would also make opening chests tedious.
