### ISSUE TITLE
Did text feed ever indicate upgrades?

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#434]
I may be finally going senile, but didnt the text feed say, "You picked up: X +Y" when you picked up an upgraded item before? Because now it shows only the name and enchant, no "+Y". I first noticed this from items identified in wells, and later just throwing them on the ground.

v0.8.1

If this is some serious Mandela effect then pardon me

**Comment by 00-Evan** [comment]
I'm pretty sure Shattered hasn't ever done this. The functionality also isn't in the original Pixel Dungeon either .

**Comment by MrCocoNuat** [comment]
Ah, I was remembering the function of the scroll of identify
