### ISSUE TITLE
[Improvement] Smooth camera movement

### ISSUE THREAD

**Issue by theFireProjet** [00-Evan/shattered-pixel-dungeon#435]
### Description
Currently, the camera sticks completely to the character when it is walking. The character can only walk into eight directions that are multiples of 45 degrees. This means, the camera movement is not very smooth because it suddenly changes direction when the character makes a turn.
<img src="https://user-images.githubusercontent.com/61639215/86291460-47899c00-bbef-11ea-9013-b2528ab2e24c.png" alt="angular path" width="180">

### User experience
The problem with the current camera behaviour is that the abrupt movements impact most of the content that is displayed on the screen. The image filling the largest area of the screen is moving and changing directions suddenly during the whole gaming experience. This is very exhausting and tiring for the eyes over time. That's why smoother camera movements would vastly improve the comfort while playing the game.

### Suggested behavior
* The camera should speed up smoothly, so that it doesn't change instantly from not moving to moving at the full speed of the character.
* The camera should follow a smoothened path, so that it doesn't change direction abruptly in steps of 45°.

<img src="https://user-images.githubusercontent.com/61639215/86291463-48bac900-bbef-11ea-9eeb-5438a646674d.png" alt="smoothened path" width="180">

**Comment by 00-Evan** [comment]
The camera has actually used smooth panning since v0.7.5.

Following patches to 0.7.5 it follows very quickly though, almost in the snapping pattern that you describe. This change was made due to overwhelming feedback that the smooth camera felt sluggish and distracting, players strongly disliked having the camera deviate from centering on the hero by any significant amount.

**Comment by theFireProjet** [comment]
That's disappointing but I guess you can't change players' minds if they like it better the way it is. I personally don't think that's most convenient.

**Comment by 00-Evan** [comment]
I've dealt with user change resistance a bunch over the last 5 years of developing Shattered. I do think some of the negative feedback on the camera panning was change resistance to start, but a lot of it was sustained, whereas change resistance generally quiets down within a week at most. It's possible that the pan could be slowed slightly to smooth out turns a bit, but feedback was clear that having it noticeably deviate from the heroes position was very disorienting.
