### ISSUE TITLE
Add more stair case sprites

### ISSUE THREAD

**Issue by master-bob** [00-Evan/shattered-pixel-dungeon#437]
Hello,

I noticed that the floors don't quite line up. That is on floor x 13 left and 13 down (relative to the staircase) will be 13 left and 13 up on floor x-1.

As such, I thought it would be nice to see the floor staircases not always be in the same direction, maybe you "enter" the staircase from the right instead of always from the left. This could be done in a random manner to give the player the idea that the floors don't line up, or even in a more structured manner so if one where to 3d map it out it would all line up.

I hope that makes sense and is possible to do. 

Thank you for making a great game!

**Comment by 00-Evan** [comment]
I agree that the stair sprites could be improved, but I'd rather redo them entirely to work better with the existing art style (they're pretty flat at the moment) instead of spending time of spritework just to fix minor details like alignment between floors.
