### ISSUE TITLE
Stop movement when blocked by ally

### ISSUE THREAD

**Issue by nseverson** [00-Evan/shattered-pixel-dungeon#438]
The movement pathing algorithm will reroute if an ally comes into view and blocks the current path, and another longer path is available. I suggest stopping movement when the conflict arises to prevent (for example) suddenly moving the opposite way around the floor loop on a cleared floor. Or adding an option for this behavior.

**Comment by 00-Evan** [comment]
Since 0.8.0 there are already checks to prevent this. If the players current path is blocked for any reason, they will only reroute if the new path is less than 2x the length of the old one.
