### ISSUE TITLE
Green blowfish

### ISSUE THREAD

**Issue by RayBone612** [00-Evan/shattered-pixel-dungeon#439]
What good is having armor if it doesn't protect you at all against these green blowfish that can shoot webs through walls and doors and round corners and trap you for five moves you made the game ridiculous version 8 and above I'm losing interest in this game quickly I thought maybe you would have fixed some of the problems and dialed back some of the crap you did with the strength of the creatures I know instead you added an updated sound file  sound effects 
Can you please make version 7 available to download until you fix the strength of the creatures in version 8 I'm sorry but the game was highly playable now it's just like go 2 level die start over go 5 levels die start over go 15 levels. If your lucky but then die because you don't have enough invisibility potion or the mine potionbecause you wasted all of your potions trying not to die from the blowfish that can destroy you no matter what type of armor you are wearing or how much you have upgraded that armor it's like I don't know what good it is upgrading armor because it doesn't do any good anymore the only armor that seems to give you a little bit of protection is the level 14 armor but then you upgrade to level 16 armor and using why I got better armor but then you find out the creatures can kill you quicker now. Like I said I used to love this game I like some of the things you did but you screwed up the creatures making them way too strong and making armor useless

**Comment by TheYsconator** [comment]
It is possible to download any previous release [here on Github](https://github.com/00-Evan/shattered-pixel-dungeon/releases).

As Evan has stated multiple times, you should send him an email with all your non-bug related inqueries. As an alternative, you can try the [subreddit](reddit.com/r/pixeldungeon) or the [Discord server](https://discord.gg/KBfMN8X).

**Comment by 00-Evan** [comment]
@TheYsconator I'm actually being a bit more lenient about non-bug reports here, as github is currently the game's second biggest distribution channel.

@RayBone612 A lot of what you're complaining about here isn't reflected in the game at all. Spinners cannot shoot webs through walls, and while some enemies can penetrate armor, armor is more important overall in 0.8.0 thanks to more enemies having abilities that counter high damage builds. Spinners in particular have always penetrated armor with their poison effect, and that hasn't been made any stronger in 0.8.0, they just got a more aggressive web shooting ability so they could better counter ranged attacks. Enemies in floors 9 and earlier were almost entirely unchanged in 0.8.0.

**Comment by RayBone612** [comment]
I downloaded and I'm currently playing the 0.7.?  version and I'm up on the levels where the green blowfish I guess they're called spinners and I found they're not nearly as deadly as they are in the version 0.8. releases I'm using level 12 armor with one upgrade and they're not able to kill me as easily or they haven't killed me yet fact is I'm actually able to keep my health up at 100% without using any health potions.  You said that they're not able to shoot webs through walls but in that version 8 they are well not not through walls but they're shooting around corners and through doors several times they shut their web and is passed through me when around the corner and put up a barrier there and then they shoot another Weber right in front of me so I'm trapped I can't move backwards I can't move forward my only recourse is to waste spells and potions in hopes that they won't kill me until the web dissipates

**Comment by RayBone612** [comment]
Or if I'm lucky enough to have a teleportation scroll use one of them to get  out of there
