### ISSUE TITLE
Level generation bug? No key for locked door

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#44]
I'm on level 2 and used a Scroll of Magic Mapping, however there is no key for the locked door anywhere.

**Details**

- Using the latest version (0.3.0b).
- The game was started in this version.
- This has happened once in an earlier version too.
- I can't find any items that I haven't picked up yet.

**Comment by 00-Evan** [comment]
Try looking for a room to drop down from on floor 1, should look like it's missing half of its floor.

If you can't find this room, feel free to comment with a picture of the locked room and I'll re-open this ticket.

**Comment by nyuszika7h** [comment]
Ah, the chasm. That worked, thanks.
