### ISSUE TITLE
Battlemage staff of Magic Missile doesn't empower Staff of Regrowth

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#440]
I'm not sure whether this is how it's supposed to work, but feel free to remove this bug report.

I recently did a Wand of Magic Missile battlemage run. The WoMM is supposed to increase the level of other wands after shooting. This worked for the attack wands (I tried fireblast, lightning and corruption) but regrowth didn't show any increase in power. Even though it was supposedly +10, it still produced grass as if it was +1 (very small garden as opposed to a large area of grass).

**Comment by 00-Evan** [comment]
regrowth and fireblast both scale in power based on charge use and level. The amount of grass regrowth generates will be higher, as it's considered to be +10, but the cone AOE won't be larger as it's still consuming just one charge.
