### ISSUE TITLE
Duplicate artifact 

### ISSUE THREAD

**Issue by CovaliuLucian** [00-Evan/shattered-pixel-dungeon#441]
https://github.com/00-Evan/shattered-pixel-dungeon/blob/b3783295bf46e3dc429ae47af4306277f9f73d6a/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/Generator.java#L505

![image](https://user-images.githubusercontent.com/13623071/86598688-27b6f700-bfa6-11ea-82c9-b12d653c7043.png)

This seems like something that shouldn't happen. The first talisman was a rose that i transmuted with a scroll and the second one I got from a golden mimic.

**Comment by 00-Evan** [comment]
hmm, probably some logic isn't triggering correctly then, might be a side-effect of generator changes I made in 0.8.1.

**Comment by 00-Evan** [comment]
fixed in commit 0b568f5a58994567125d2337c149ecb0fd613c10
