### ISSUE TITLE
magic missile wand doesn't empower other magic missile wand

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#442]
I happened to get a second magic missile wand and noticed that the second magic missile wand doesn't get empowered by the first magic missile wand, unlike forother wand types.  Is this intentional or a bug?  If intentional, why should magic missile not empower a second magic missile wand?

Love the new sounds btw.

**Comment by 00-Evan** [comment]
This is intended, to prevent circular magic missile buffing logic.

i.e. I don't want to let a player do this or similar: +10 MM -> applied +10 magic charge buff -> +0(buffed to +10) MM -> applied +10 magic charge buff -> +0(buffed to +10) MM -> ....

It's also sort of the point of magical charge that it enables MM to work with other, non-MM wands.

Glad to hear you like the new sfx!
