### ISSUE TITLE
Two alchemy spot on one level

### ISSUE THREAD

**Issue by psydvl** [00-Evan/shattered-pixel-dungeon#443]
Looks like bug. 
Left alchemy spot was hidden in "maze".
Right - locked with key. 
![Screenshot_20200716-121624](https://user-images.githubusercontent.com/43755002/87653512-49f70480-c75e-11ea-8058-bd2f1de0369d.jpg)
0.8.1a

**Comment by Leajian** [comment]
It's not a bug, it's bonus room.

**Comment by 00-Evan** [comment]
As mentioned this is intended. You can rarely get both a regular and secret alchemy room on the same floor.
