### ISSUE TITLE
Horn of plenty stops replenishing (desktop version 0.8.1a)

### ISSUE THREAD

**Issue by Oblomov** [00-Evan/shattered-pixel-dungeon#444]
Got an uncursed horn of plenty early, managed to bring it to +10 with several rations and a couple of pies, but for a few turns now it seems to have stopped producing food. I'm attaching a zip of the associated game dir. Exiting and re-entering doesn't seem to fix it, so the bug seems to survive serialization.
[empty-horn-of-plenty.zip](https://github.com/00-Evan/shattered-pixel-dungeon/files/4942385/empty-horn-of-plenty.zip)

**Comment by 00-Evan** [comment]
The horn of plenty charges based on exp gain, not time. This is to prevent using the horn to stall and farm.

**Comment by Oblomov** [comment]
Oh sorry, thanks.
