### ISSUE TITLE
"Floor is Locked" debuff remains after defeating Yog-Dzewa

### ISSUE THREAD

**Issue by Random-Chain** [00-Evan/shattered-pixel-dungeon#445]
v0.8.1a

After defeating Yog-Dzewa, the "Floor is Locked" debuff doesn't disappear. 
Floor isn't really locked, it's just the debuff icon still being shown. It disappears once you take the first step in floor 26.
On other bosses, it's gone as soon as they're defeated (when you get the "Boss Slain" message).

![Screenshot_20200724-220917](https://user-images.githubusercontent.com/58945606/88434326-9f8b7b00-ce08-11ea-975c-2610598bb38e.jpg)

**Comment by 00-Evan** [comment]
Did you have any affects that increase your movement speed? Currently the floor lock debuff detaches on its own after a turn when the floor is unlocked. If you were going at a very high speed that would explain it persisting.

**Comment by Random-Chain** [comment]
No, I didn't have any haste buffs/swiftness glyph etc. I have another screenshot from a few turns later where it's still "locked", if you want more proof. It didn't go away until I went down to floor 26.
I've saw this once on 0.8.0 as well. Just managed to finish a game on 0.8.1a and noticed it still happens.

**Comment by 00-Evan** [comment]
I've taken a look into the code and can see how this is happening. Will fix in 0.8.2, thanks!

**Comment by 00-Evan** [comment]
fixed in commit a3455335f47e37a3ab7d13ee1838089ca1704e3d
