### ISSUE TITLE
Font is too small for desktop environments

### ISSUE THREAD

**Issue by VedVid** [00-Evan/shattered-pixel-dungeon#446]
**Issue**  
The font size used for messages, items descriptions, class entries, etc. is hard to read for me. I don't have perfect eyesight, but I don't remember having this issue just few versions ago.  
Enlarging text will make it more clear for sure, yet I don't think the font size is the only source of the problem. Another thing is that the black outline looks like it's poorly antialiased on my screen, and the letters seem to be very tightly packed.  
The size of the other UI elements is fine.

Screenshot: 
![image](https://user-images.githubusercontent.com/16949680/88590009-52064c80-d05a-11ea-9532-cd35a8850d20.png)

I'm sending uncropped image, to provide the user perspective and the scale between SPD text and other desktop elements.

**Game version**  
0.8.1a, desktop jar release.

**Other details**  
Windows 10, 64-bit; native resolution: 1920x1080; size of the game window doesn't matter, the text looks the same.

**Comment by 00-Evan** [comment]
Looks like you've got display scale set to a low value. Try increasing it in the settings.

**Comment by VedVid** [comment]
Hello, thank you for fast reply. It helped, indeed. I'm sorry for not checking the settings in the first place, somehow I was sure it's result of technical issue.
