### ISSUE TITLE
Equipment not getting identified in death

### ISSUE THREAD

**Issue by Bionic64** [00-Evan/shattered-pixel-dungeon#448]
![Screenshot_2020-07-31-00-47-41](https://user-images.githubusercontent.com/69026559/88998562-b4fd1b00-d2c8-11ea-9858-81694d74907b.png)
I died in a warden run,didnt opened the inventory after i died,had an unblessed ankh but i didnt used it,after that i open hall of fame to check it,the plate isnt identified (it wasnt in the run),so i gone and tried to die with unidentified equipment,this time i opened the menu after death and had no ankh,the quarterstaff i found was identified after the death,and it is in the hall of fame.

Another important thing was that this run was started in 0.8.1 and i died while in 0.8.2 beta.

is it a bug of some sort,if not,im sorry.

**Comment by Bionic64** [comment]
Also it was on android

**Comment by 00-Evan** [comment]
Looks like this is an existing issue with Ankhs. If the player dies with one the game gets submitted to rankings before gear is identified.

**Comment by 00-Evan** [comment]
fixed as a part of commit 462b1027ccdcce9caf4411313955a71287727180 , specifically the change to WndResurrect.java
