### ISSUE TITLE
There's a bug related to traps

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#449]
I'm not sure if it happens to every kind of em, but when you throw something onto a dart trap the game crashes

Took a video of it happening [here](https://youtu.be/vyjwQRhMk5c)

**Comment by 00-Evan** [comment]
This has already been addressed in beta-3. Beta 3 is out on github and should be available on Google Play soon.

**Comment by N8fall** [comment]
tyty
