### ISSUE TITLE
Visual effects duration tweaks

### ISSUE THREAD

**Issue by Niektory** [00-Evan/shattered-pixel-dungeon#451]
1. When a gas disappears from a tile (corrosive gas for example) it takes a while for the particle effect to end. So when I'm waiting for it to disappear to enter a tile I have to wait 2-3 seconds between each turn if I don't want to waste turns. It would be nice if the effect ended more quickly (ideally instantly).

2. I think ripper demons' crosshair effect disappears too quickly. It's easy to miss if you're not looking at the place it appears at at that exact moment.

**Comment by 00-Evan** [comment]
Regarding your points:

1. Ending the effect instantly won't work as it would be very visually jarring, I do understand the annoyance that the effect persists for quite a while which requires the player to pause to be sure about its current location.

2. I don't want the crosshair to persist for a long time as it's very visually noisy (which it also needs to be to be noticeable). It currently lasts for two seconds, which I think is appropriate in the vast majority of cases. If it were to persist I'd like to also design it to be less visually noisy, or at least become less noisy after a couple seconds.

I'm going to close this issue as it's a design suggestion that I don't currently have an plans for. I am aware of these though (and similar issues players have with other vfx, such as DM-300s rockfall) and they are on my list of things to look into. At some point I may make a standardized hazard indicator which can be used universally.
