### ISSUE TITLE
Dried Rose keeps recharging during "floor locked"

### ISSUE THREAD

**Issue by vxiiduu** [00-Evan/shattered-pixel-dungeon#452]
This is in v0.8.2-beta-3.
I was fighting against Tengu. After he teleported to the second room, I stopped to heal a little. Even after I stopped regenerating HP and wands stopped recharging, the dried rose kept recharging. Not sure if this is intentional behavior or not, but I don't think it is, considering the purpose of that "floor locked" stuff.

**Comment by 00-Evan** [comment]
Was the ghost active or not? I can see cases where the rose might not be respecting locked floors while the ghost is alive, but when it's passive it should stop charging.

**Comment by vxiiduu** [comment]
The ghost was active. Fortunately I recorded that gameplay and the relevant part is https://youtu.be/JPkR2IZv5IE?t=1883 which shows my mage staff and the rose in the quickslot.

**Comment by 00-Evan** [comment]
Yeah it's a bug. Unfortunately 0.8.2 is about to release so I'll include a fix in 0.8.2a instead.

**Comment by 00-Evan** [comment]
fixed as a part of commit b8178b15b72bf4e2d778963569972961eec7d96f
