### ISSUE TITLE
Multiple attempts needed to progress to amulet of yendor area after defeating Yog-Dzewa

### ISSUE THREAD

**Issue by vxiiduu** [00-Evan/shattered-pixel-dungeon#453]
This is in v0.8.2-beta-3.
After defeating Yog, I went to the gate which leads to the long corridor to the amulet of yendor. The character did not enter the gate, instead just standing on that tile as if it were a normal tile. This has happened twice, and each time I just did a bunch of random stuff (go up to the previous floor, then come back down again, and go in and out of the gate area multiple times) before it would finally let me in.

**Comment by 00-Evan** [comment]
You might be tapping on the wall tile behind the exit, rather than the exit tile itself. There is no difference to the coding for that floor exist versus any other one.
