### ISSUE TITLE
Long-press tile to provide contextual actions menu

### ISSUE THREAD

**Issue by Oblomov** [00-Evan/shattered-pixel-dungeon#455]
A feature request: would it be possible to provide a list of possible actions after long-pressing on a tile? These could be something like: walk to (allow walking to a tile with a chest or stairs etc without interacting with it), inspect (same as clicking on the tile with the magnifying glass, which is the one I'm most interested in), interact (if there is anything in the tile in question), shoot/zap (with any quickslotted item).

**Comment by TheYsconator** [comment]
Whilst I do believe being able to walk on stairs without actually having to use them would be nice, I think long-pressing for such a popup may not be the best implementation. Most of the functions that you mention (namely inspecting, interacting and shooting a wand) will probably be faster by just pressing the buttons that are already in the game.

Given that it adds additional clutter to the interface to add the same functionality on two places, I'd consider simply adding 'long press = walk without interact' before a full contextual actions menu. However, even that will add a somewhat new game mechanic ('long-press in world') for a niche/rarely-occuring problem.

Which problem(s) (besides the 'walk without interact') are you considering to be solved by adding such a contextual actions menu?

**Comment by 00-Evan** [comment]
Unfortunately something like this can't work as holding your finger on the game environment is already used for scrolling and zooming. A long-tap action could easily be accidentally triggered when trying to scroll or zoom.

a context-menu is something that's also more common for desktop on right click, and that is something I hope to do when expanding the desktop interface.

**Comment by Oblomov** [comment]
@TheYsconator I find that having to click in two/three separate places to achieve an action to be rather borthersome. In fact, what prompted this FR was the discovery that I could pick whatever the hero was standing on by just clicking on the hero tile (I used to go and click all the way to the icon in bottom right).

@00-Evan thanks for pointing out the technical issue on mobile. I'd guess for the desktop version these things could be achieved by using right-click versus left-click, but I can see how this would be problematic on touch interface. Maybe some more sophisticated gesture such as long press + tap with other finger might work, but one would indeed be left to wonder if it's worth it.
