### ISSUE TITLE
Wraith don't spawn over traps

### ISSUE THREAD

**Issue by blackk100** [00-Evan/shattered-pixel-dungeon#456]
I'm not sure if this is intended behaviour, but when grave-digging, wraiths do not spawn over tiles where traps are present.

In the screenshot below, the grave was at the position where my character is currently. When I dug up the grave, I was between the statue and the trap and the grave to the top-right.

![Screenshot_20200811-143647](https://user-images.githubusercontent.com/22541378/89879897-3619b380-dbe1-11ea-8873-c27e7ee84854.png)

This was on v0.8.2 Android.

**Comment by 00-Evan** [comment]
This is because wraiths currently check if terrain is freely passable (no hazards), when they should probably just ensure that there isn't a wall at their spawn location. I'll adjust this.

**Comment by 00-Evan** [comment]
Initially fixed as a part of commit b8178b15b72bf4e2d778963569972961eec7d96f , but I now realize that isn't a full fix. Will fix properly in the next release.

**Comment by 00-Evan** [comment]
fixed in commit 5387559191e6d06c344ad9c2eb620768585cc591
