### ISSUE TITLE
Unique music for each area of the dungeon

### ISSUE THREAD

**Issue by LightningAA** [00-Evan/shattered-pixel-dungeon#457]
It'd be really nice to see *each zone of the dungeon get it's own music*, it'd help create more atmosphere and make the game's music more interesting to listen to. It would also be cool to see unique music for boss fights, maybe even a unique song for each boss.

**Comment by 00-Evan** [comment]
Agreed, but this isn't the sort of change that can really be tracked in a github issue, seeing as it's not really actionable in the same was as a technical change.
