### ISSUE TITLE
DM-300 mentioned in description text before being seen

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#461]
It's a little bit strange that when you're examining the gate in level 15 of the caves, DM-300 is mentioned in the gate's description text even before the player knows DM-300 exists.  Because 0.8.1 changed this battle to allow the player to explore before DM-300 appears, the text might need to be tweaked.

**Comment by 00-Evan** [comment]
I'd rather leave this in for clarity, given that the player is presumably examining the gate to know how to get through it.
