### ISSUE TITLE
Game shuts down when I try to go down

### ISSUE THREAD

**Issue by S0rigin** [00-Evan/shattered-pixel-dungeon#462]
Game shuts down whenever I try to go down to the 7th floor.
I tried to go down by the stairs first, but the game shut down. And then I tried to fall down to the 7th floor but it also didn't work and the game shut down, and when I turned on my game again, my character was on the 6th floor but got all the debuffs and damage.
Sorry about my bad English, and I'm really enjoying this game. Hope this bug will be fixed soon! @

**Comment by 00-Evan** [comment]
Apologies for this, v0.8.2a introduced a new crash bug that happens a low percentage of the time, but locks the run when it happens. v0.8.2b is currently being released and will fix this.

**Comment by 00-Evan** [comment]
fixed in commit 422288d8573cc930b426086352a790848cf914c7
