### ISSUE TITLE
Projecting bow not targeting through walls

### ISSUE THREAD

**Issue by langdon** [00-Evan/shattered-pixel-dungeon#463]
I think this is a bug but obviously very hard to replicate. If you are playing as Huntress and apply a projecting enchantment to your bow, targeting through walls doesn't seem to work. I *think* targeting with a projecting weapon through walls also doesn't work in general. The issue may be limited to "first attack" but I am not sure.

Android v0.8 (not sure which minor release)

**Comment by 00-Evan** [comment]
This is intended. Autotargeting does not lock onto enemies which you can only see thanks to mind vision, you have to manually target them.
