### ISSUE TITLE
Seed never goes back to bag

### ISSUE THREAD

**Issue by langdon** [00-Evan/shattered-pixel-dungeon#465]
If you overfill your "Velvet Pouch" so that items go to your Backpack and then later reduce the number of items in your pouch, seeds to do not go back to the pouch (they remain in the backpack).

Android v0.8 (not sure which minor release)

**Comment by 00-Evan** [comment]
fixed in commits 39c5da606125cc51df89feb7db311e00bdb4f867, and 67627f7a2f7d6c2aaf81fa421c3458175ed0853f
