### ISSUE TITLE
Enhancement: Alchemy pots report how much energy they have left

### ISSUE THREAD

**Issue by langdon** [00-Evan/shattered-pixel-dungeon#466]
Sometimes you come back to level for the Alchemy pot. However, I hate committing to travelling all the way back to the pot only to discover that it does not have enough energy to perform the action I want. I think it would be nice if when you "search" the pot (from a distance), it would report how much it energy it still has.

**Comment by TheYsconator** [comment]
Adding to that: it would be nice if that info is also visible in the journal -> floors menu (where alchemy pots are listed as well).

**Comment by 00-Evan** [comment]
including this info in the journal is reasonable, but I don't want to let the player examine things through walls.

**Comment by 00-Evan** [comment]
I've decided to defer this until later as adding this sort of variable text function to landmarks requires a lot more code changes than expected. Honestly I'm likely to just refactor them entirely at some point.

**Comment by spixi** [comment]
I only request the feature of knowing the remaining energy in the journal after you opened the potʼs menu once.

**Comment by TadaCZE** [comment]
Also there is a problem that when multiple landmarks of the same type exist on one floor, the GUI just displays one.

**Comment by 00-Evan** [comment]
made redundant by commit efeda9c5ff0f1487467229d50da24ee2d2bb5160
