### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by blockerman-git** [00-Evan/shattered-pixel-dungeon#471]
when viewing changes in landscape mode, sometimes not all the text shows on the screen because of it being too long

**Comment by 00-Evan** [comment]
can you provide a screenshot? I do test minimum screen sizes when writing the changelog

**Comment by blockerman-git** [comment]
sure.
![Screenshot_20200818-195246](https://user-images.githubusercontent.com/64559426/90579706-7b635580-e18c-11ea-8fc7-c2c77397c0ea.png)

**Comment by 00-Evan** [comment]
Alright, so it looks like this is happening with specific changes windows at minimum device res in landscape. I'll do a pass on these, maybe make the windows a bit wider.

**Comment by 00-Evan** [comment]
Fixed in commit d6f73bc3fa8b00ec1e0fceaa6435999a12ba7ff8 , titled message windows now dynamically scale their width in landscape mode.
