### ISSUE TITLE
Enchantment is not mentioned in Mage's Staff's title

### ISSUE THREAD

**Issue by LyraLover** [00-Evan/shattered-pixel-dungeon#472]
Reproduction: use stone of enchantment on mage's staff
Version: Desktop 0.8.2b
OS: Arch Linux 5.7.12-arch1-1
Java: openjdk 14.0.2 2020-07-14
![image](https://user-images.githubusercontent.com/21143379/90567862-7f569e00-e1b3-11ea-8294-aeb39046022d.png)

**Comment by 00-Evan** [comment]
This is a side effect of some internal changes I made to item names in 0.8.2b, will fix in the next release.

**Comment by 00-Evan** [comment]
Fixed in commit 8e752aceef0e0d6f228b60ba2beceb9e9ad86a0b
