### ISSUE TITLE
Feature Request: Vertical Sync on desktop

### ISSUE THREAD

**Issue by ObiDriftKenobi** [00-Evan/shattered-pixel-dungeon#475]
Currently on the desktop version, the display is tearing while the character moves.
Is a feature such as V-Sync possible to implement? I haven't found anything like that in the settings.

Thank you for reading.

**Comment by 00-Evan** [comment]
closing this as there's been no followup. As mentioned before the game already tries to use vsync, but it may be being overridden in your case.
