### ISSUE TITLE
Selling dried rose loses equipment.

### ISSUE THREAD

**Issue by misterbeebee** [00-Evan/shattered-pixel-dungeon#477]
Selling dried rose loses ghost's equipment.

1. Probably merits a warning popup.

2. Not sure if equipment is paid for.

**Comment by 00-Evan** [comment]
I'll look into this. Either the rose should be unsellable with equipment, or the price should include the ghost's equipment.

**Comment by 00-Evan** [comment]
Fixed in commit 71df55ef11d4877561ab869d961ae65bd2bdb911

**Comment by misterbeebee** [comment]
Thank you!
