### ISSUE TITLE
monk parries lightning

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#480]
If you shoot a monk with the lightning wand, it plays the "parry" sound.  I didn't notice whether or not the monk was taking damage.  Is the monk supposed to be able to block lightning?

**Comment by 00-Evan** [comment]
Wands attacks skip accuracy checks entirely, so this shouldn't be possible. The code that would trigger the parry sound is simply never called into.

Was the monk perhaps also being attacked by another character?

**Comment by protective1** [comment]
I guess that's likely the monk was being attacked by someone else, as I am unable to recreate this.  While I didn't see any allied creatures, it was hard to tell because the monk was surrounded by ghouls and inside a corrosion cloud when I shot the lightning.
