### ISSUE TITLE
v0.8.1 change log shows incorrect info

### ISSUE THREAD

**Issue by hughbowls** [00-Evan/shattered-pixel-dungeon#483]
"-Sniper shot damage scaling with distance increased, now caps at 3x damage, up from 2.5x."
The damage is still capped at 2.5x

shattered-pixel-dungeon/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/SpiritBow.java
line 169-174
`//as distance increases so does damage, capping at 3x:`
`//1.20x|1.35x|1.52x|1.71x|1.92x|2.16x|2.43x|2.74x|3.00x`
`int distance = Dungeon.level.distance(owner.pos, targetPos) - 1;`
`float multiplier = Math.min(2.5f, 1.2f * (float)Math.pow(1.125f, distance));`
`damage = Math.round(damage * multiplier);`
`break;`

**Comment by 00-Evan** [comment]
good catch, I'm about to release 0.8.2c so I'll include a fix for this in that.

**Comment by 00-Evan** [comment]
Reopening as source code hasn't been released just yet.

**Comment by 00-Evan** [comment]
Fixed in commit 61e7ccd40e45eca381176083ae413a388b181bb4
