### ISSUE TITLE
the crystal chest has escaped

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#487]
I'm an invisible assassin standing at the only exit to the room.  The crystal mimic is right next to me inside the room.  The mimic disappears in a puff of smoke and the message appears, "the crystal chest has escaped!". It feels unfair that it just teleported out of the level when I'm standing right next to it blocking the only room exit.  Is this a bug?

**Comment by 00-Evan** [comment]
This is happening because the chest is cornered, but can't see the hero. Thieves have an extra check for invisible heroes that crystal mimics are missing, where they should be equivalent.

**Comment by 00-Evan** [comment]
Fixed in commit 77249e84ea1e460bb511c9d03f8d9b43361cd6ec
