### ISSUE TITLE
Max health boost doesn't stack

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#488]
I saved up a few strength potions, and used alchemy to turn them into elixirs of might. Drinking both of them only seems to have given me the same max health boost as drinking one.

I would have expected the max health to stack. Saving up strength potions rather than drinking them has a substantial trade-off, both in equipment you can't use and in the lack of additional damage; the max health boost also fades with levels. Given all of those factors, it seems reasonable for each potion to apply its boost.

**Comment by 00-Evan** [comment]
This is intended for now as I decided against allowing alchemy items to stack. I don't want people to use alchemy items purely as a tool against bosses, which stacking would encourage.

**Comment by joshtriplett** [comment]
@00-Evan The Elixir of Might seems a little different there, since it has a long-lasting effect that lasts for several entire experience levels. That seems very different from a short-term buff.

In that case, if you don't want to support that, would you consider adding a note in the description of the Elixir of Might that it doesn't stack, so that people can know before saving up potions to try that with?

**Comment by 00-Evan** [comment]
In general I'm going to be re-evaluating the balance of a bunch of alchemy recipes in the future. I still don't want any outright boss killers, but I've clearly been too conservative when balancing a lot of alchemy recipes. Elixir of might will likely be changed at some point along with these rebalances.
