### ISSUE TITLE
Father fall should have an indication (as a buff)

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#489]
The feather fall spell doesn't have any indication that it's active.

Perhaps it could be a differently colored version of the levitation buff icon?

**Comment by 00-Evan** [comment]
I decided against doing this to reduce clutter, especially as the player should be using the spell just before jumping, so it would be adding an icon just to remove it moments later. Internally the buff lasts for 30 turns, which should be plenty of time for the player to jump down a chasm.

**Comment by joshtriplett** [comment]
@00-Evan What about an indication in the confirmation dialog asking if you're sure you want to jump? Mentioning in that dialog that you have the feather-fall spell active would help.
