### ISSUE TITLE
Trap names lowercased in 0.3.0c?

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#49]
[![Screenshot](https://i.imgur.com/nsszyUdl.png)](https://i.imgur.com/nsszyUd.png)

**Comment by 00-Evan** [comment]
This is the most commonly reported issue in 0.3.0c. I think that's so amusing given how small it is.

You are correct though, names should be uppercased and this is an oversight, will fix next patch.

**Comment by 00-Evan** [comment]
fixed in commit fba591af687a6e09aeb953d6479efd1e3b4aa20d
