### ISSUE TITLE
can't hide in garden while using mind vision potion

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#490]
Normally if you enter a garden out of enemy view you become invisible.  However, this doesn't happen while you are using a potion of mind vision, which seems like a bug.

**Comment by 00-Evan** [comment]
This is because the shadowmelded buff breaks as soon as an enemy is in your vision. Probably it should do additional checks to ensure the visible enemy is next to you.

**Comment by 00-Evan** [comment]
Fixed in commit dc4b05be4328ed0226e932a090a9b2944d8b1ede
