### ISSUE TITLE
cave spinner shoots through wall

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#491]
Cave spinner shot web through wall!  In screenshot, cave spinner was out of sight and shot web from right.  I placed ward to reveal cave spinner's position, then took the screenshot.  Cave spinner may have moved one square while I placed the ward, but there is no space where it could have been to shoot the web as shown without shooting through the wall that juts out.
![Screenshot_20200830-221053](https://user-images.githubusercontent.com/8593007/91676718-bcedec00-eb0e-11ea-9c1c-5748d552c05a.png)

**Comment by protective1** [comment]
Before I placed the ward (immediately after cave spinner shot) the screen looked like this.
![Screenshot_20200830-221040](https://user-images.githubusercontent.com/8593007/91676755-dc851480-eb0e-11ea-9315-8ff3dfff498e.png)

**Comment by 00-Evan** [comment]
The original design intent here was to ensure spinners couldn't be messed with by using the corners of terrain. Their clearly doing their job just fine though, and people generally feel their too oppressive, so I think it's fine to add some collision logic to their web shots.

**Comment by 00-Evan** [comment]
Fixed in commit 4ed1a33cb0a450d0e47b9e93c84a4d46b5ae83ec
