### ISSUE TITLE
Question about contributions

### ISSUE THREAD

**Issue by Atrate** [00-Evan/shattered-pixel-dungeon#492]
As I've read in some previous issues and pull requests, you're not accepting contributions due to (rightful) concerns with app stores being forced to take down an app at any contributor's request.

My question is simple: isn't there a way around it? E.g. signing a simple waiver relinquishing the contributor's rights to the project/contributed code or releasing the code (only the PR related code, not the app itself) into the public domain? 

Also, how does this all relate to image assets? Are asset contributions welcome?

**Comment by 00-Evan** [comment]
Ultimately this is all a question of enforcement, and I don't have any precedent that a waiver-based approach would be enough in the eyes of Apple. Additionally, I generally want to keep Shattered a solo project (plus help in specific spots), and so don't have any intention to accept contributions to the code or direct assets. As far as I'm aware the game's assets are also licensed under GPLv3.

**Comment by comradekingu** [comment]
That doesn't make sense, fortunately. Besides, does Apple even allow GPLv3 in their store?
CLAs only help the host party relicense, not actually get the usage terms of the license. That part is in the license.

**Comment by 00-Evan** [comment]
Apple's app store does violate the GPLv3 license, hence why all copyright holders need to be in agreement before a GPLv3 app can be released there (functionally the iOS binary isn't a GPLed one). This is why I want to keep the number of copyright holders at 2, myself and Watabou.
