### ISSUE TITLE
Zapping a wand when time is stopped crashes game

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#493]
![20200902_095059.gif](https://user-images.githubusercontent.com/69068719/91919768-04889980-ed02-11ea-99bf-5d4227385278.gif)

Thankfully it didn't damage the save file, so I could go on with unstopping time first and then firing away

**Comment by 00-Evan** [comment]
This has already been fixed, update to v0.8.2d
