### ISSUE TITLE
caught on fire descending into floor 20

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#494]
![Screenshot_20200901-231438](https://user-images.githubusercontent.com/8593007/91928183-679a1200-eca9-11ea-9985-e2870decbd93.jpg)
I went down the stairs on floor 20 and immediately caught on fire.  But it's not clear why this would happen.  I'm not wearing any cursed gear.

**Comment by 00-Evan** [comment]
You probably dopped a potion of liquid flame into a chasm on the previous floor. That potion landed and ignited the area next to the stairs.

**Comment by protective1** [comment]
I see - I remember killing a fire elemental over a chasm on the previous level.  So, unfortunately for me, it probably dropped the potion of liquid flame as "treasure".
