### ISSUE TITLE
dewcatcher is deadly in tengu's lair

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#495]
When low on strength in phase 1 of Tengu's Lair, I used the wand of regrowth and created a dewcatcher.  Unfortunately for me, stepping on this dewcatcher flung dew which triggered many surrounding poison dart traps, shooting multiple darts at me.  The dewcatcher doesn't seem to trigger traps on other levels.  Have I just been really lucky previously, or is that an inconsistency with dew drops and Tengu's traps?

**Comment by 00-Evan** [comment]
Dewcatchers won't drop dew over a visible trap, but will spread them onto hidden traps. Tengu traps are considered to be hidden traps.
