### ISSUE TITLE
Going back from character selection screen exits app

### ISSUE THREAD

**Issue by atavakoli** [00-Evan/shattered-pixel-dungeon#496]
## Version

0.8.2

## Steps to reproduce

1. Go to the main menu
2. Click "Enter the Dungeon"
3. If there are in-progress games, click "New Game"
4. Click back (the Android native back, not the in-game top-right button)

## Expected

I return to either the main menu or the "Games in progress" selection screen.

## Actual

The app exits.

**Comment by 00-Evan** [comment]
fixed in commit 07a64ba2d3d8cb0c5ab3f59a4c22f736588981be
