### ISSUE TITLE
missiles activate armor glyphs

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#498]
Playing as huntress, using bow to shoot an animated statue that's wearing armor of repulsion causes me to bounce dangerously all over the place.  Similarly, while wearing highly upgraded armor of thorns, I threw a dart of healing at my prismatic image and now have serious bleed damage!  While tragically humorous, is it intentional that these armor glyph effects can affect the shooter of a missile weapon or is this a bug?

**Comment by 00-Evan** [comment]
This is intended. Thrown weapons are physical attacks and so do proc glyphs.
