### ISSUE TITLE
Trap lost upon throwing Reclaim Trap

### ISSUE THREAD

**Issue by TimothyPolizzi** [00-Evan/shattered-pixel-dungeon#499]
If you throw a Reclaim Trap spell after picking up a trap, the trap information is lost. This can be done ad infinitum to clear any number of traps in a room. I'm going to assume this is not the intended functionally of the spell as there is a limited number of charges.

**Comment by 00-Evan** [comment]
This is an unintended result of the spell clearing the trap when dropped to prevent the player from stacking multiple traps. Probably the item should not be droppable when it contains a trap.

**Comment by 00-Evan** [comment]
Fixed in commit de9d629a7fad898bbfd58e52f353469a0bb75302
