### ISSUE TITLE
Found two artifacts

### ISSUE THREAD

**Issue by ReallyBasic1** [00-Evan/shattered-pixel-dungeon#500]
![Screenshot from 2020-09-12 19-30-33](https://user-images.githubusercontent.com/53022868/93007416-7ea0f580-f52e-11ea-8b97-1f2973be33b7.png)
As you might see in the inventory, I have two horns of plenty. I am not sure if this is supposed to happen.

The cause: probably the ring of wealth. I saw a green flash after killing a thief, and it dropped the horn of plenty, though I already had one equipped.

**Comment by 00-Evan** [comment]
Wealth drops artifacts in the exact same way as other game systems, so that shouldn't be the case. Was this run carried over from a previous v0.8.2 patch, or did you get either of the drops from heroes remains? There are known issues regarding item uniqueness for both of those.

**Comment by ReallyBasic1** [comment]
I am not 100% sure where I got the first one, but the second one I know I got from a thief. I also started the round after the v0.8.2 patch. Hope this helps :/

**Comment by 00-Evan** [comment]
Wait, sorry I actually just noticed the game's icon. It looks like you're playing an unofficial build of the game (the icon on the left is the original pixel dungeon icon, and the one at the top is the game's debug icon).

I don't provide support for unofficial distributions of the game, they may contain modifications that change game logic which make it impossible for me to reproduce bugs.

**Comment by ReallyBasic1** [comment]
Wait, do you mean the icon here? Because that is in grayscale, it isn't the green and yellow debug one that I have seen...
![Screenshot from 2020-09-26 20-52-58](https://user-images.githubusercontent.com/53022868/94353754-69ea5480-003a-11eb-9769-d3d44178b74f.png)

I have not been playing an edited version of this game, only the one I have directly installed through the ubuntu app store.

**Comment by 00-Evan** [comment]
The greyscale icon is the debug icon, the yellow and green icon is the one that should appear on release builds. Additionally the icon on the left is the one for the original Pixel Dungeon, not Shattered Pixel Dungeon.
