### ISSUE TITLE
Enhancement: Say what unidentified scrolls/potions aren't

### ISSUE THREAD

**Issue by radzo73** [00-Evan/shattered-pixel-dungeon#502]
**What?** Currently, if you use a Stone of Intuition and guess incorrectly, that's that. Chances are, by the time you find another Stone, you'll have forgotten what you guessed, or even which scroll you were guessing.

**How?** It would be a little blurb under the description for the unknown scroll/potion, something like "One thing's for sure; it's not a Scroll/Potion of [whatever you guessed previously]"

**Comment by 00-Evan** [comment]
Generally I don't think it's a good idea to append lots of text to item descriptions, or extraneous information to an item's state. This impacts save file size and can result in long bloated item descriptions, if users even remember to check the item description at all. At some point in the future I would like to implement a custom notes features, which would address this need nicely.
