### ISSUE TITLE
"Into darkness" Challenge active when "Swarm Intelligence" is.

### ISSUE THREAD

**Issue by Laserbean** [00-Evan/shattered-pixel-dungeon#504]
As the title says, the wrong challenge was active. I'm not sure if this happens to other challenges, but it was very obvious with the "into darkness" challenge. 
This is for the version 0.9.0-BETA-1.

**Comment by 00-Evan** [comment]
Their entries are currently swapped in the challenge menu, this will get fixed in beta-2, thanks!

**Comment by 00-Evan** [comment]
Fixed in BETA-2
