### ISSUE TITLE
Game crashes on using the amulet

### ISSUE THREAD

**Issue by Charismatix** [00-Evan/shattered-pixel-dungeon#505]
Every time I attempt to end the game using the amulet, the game crashes. I was able to end it by climbing out of level 1, however. Beta

**Comment by 00-Evan** [comment]
Are you playing on the latest version? There were crashes on game end initially but I released a new version of beta-1 which should address them.

**Comment by Charismatix** [comment]
Ah, I didn't see there was an update today

**Comment by 00-Evan** [comment]
Okay, let me know if you run into that error again, for now I'll close this.

**Comment by Charismatix** [comment]
Actually, I did already update
