### ISSUE TITLE
Splitting flies don't keep champion status

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#506]
I feel like fly swarms that split should probably give the new swarm the champion status, since it is supposed to be permanent. I do not know presently if that happens with corruption, which is also permanent.

Right now champion flies are really easy to defeat since every hit divides their hp in 2 and only results in more non-champion flies, and specifically, blazing flies just roast the other flies to death once they spawn.

Also, how do necromancers figure into this, since they cannot attack? Does the summon-gets-same-effect mechanic apply to champion too, or is this supposed to be limited to only corruption?

**Comment by 00-Evan** [comment]
I've decided to let these enemies grant their champion status to offspring characters (ghouls too). Will implement in beta-3

**Comment by 00-Evan** [comment]
This should be fixed in RC-1
