### ISSUE TITLE
Descending ladders not appearing

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#507]
![spd-20200926-210231-000.gif](https://user-images.githubusercontent.com/69068719/94340323-cb5ef300-003b-11eb-89f1-ce8fe454622b.gif)

This seems to happen rarely in the caves region, with the tile for ladders being replaced by burnt ones. Out of the few cases found, one report says that 'the ladders were burnt'. 

The gif above was taken by falling into a chasm and going up.

++++
![spd-20200926-211931-000.png](https://user-images.githubusercontent.com/69068719/94340588-05c98f80-003e-11eb-8b96-18850b179119.png)

It seems that burning up cobwebs override existing tile information, this pic was taken after burning em up where the burnt tiles exist now.

++++++
![spd-20200926-214122-002.gif](https://user-images.githubusercontent.com/69068719/94341036-3f4fca00-0041-11eb-9011-4d9e03f66ecb.gif)

A gif of it actually happening

**Comment by 00-Evan** [comment]
This has been fixed in BETA-2
