### ISSUE TITLE
Alchemy improvement suggestion: long press (or equivalent) to fill all slots

### ISSUE THREAD

**Issue by Oblomov** [00-Evan/shattered-pixel-dungeon#508]
When cooking potions or meat or when enhancing scrolls it's a bit boring having to add repeated items. Some kind of shortcut to fill as many (empty) alchemy slots as possible would be a nice improvement.

**Comment by 00-Evan** [comment]
You can already use the alchemy guide to quickly populate the interface with items.

**Comment by Oblomov** [comment]
The auto-population is too random. For example, if I want to brew a potion from seeds, it will auto-pick the first three seeds from the inventory, whereas what I'm looking for is for a way to fill all the slots with three copies of the same seed (or similarly, with two copies of a stone to enchant a scroll).
