### ISSUE TITLE
Huntress Survivalist Intuition rank 2

### ISSUE THREAD

**Issue by Talganoth** [00-Evan/shattered-pixel-dungeon#509]
I got the message that I had worn my armor long enough to become familiar with it. It was my starting cloth armor, starting weapon, and nothing else equipped.

**Comment by 00-Evan** [comment]
It's not possible for items that are already IDed to do this, and the survivalist perk doesn't change their logic either, it just applies a multiplier to the rate of identifying. As-is I can't reproduce this as it should be an impossibility in the code. let me know if you run into it again and can provide more details about what could trigger it.
