### ISSUE TITLE
Version 0.3.0e: Also raise versionCode

### ISSUE THREAD

**Issue by RealRancor** [00-Evan/shattered-pixel-dungeon#51]
Hi,

currently f-droid isn't detecting the new update 0.3.0e automatically as it seems you havn't updated the versionCode for this release.

**Comment by 00-Evan** [comment]
This is because the source for 0.3.0e has not been released yet, mainly because I was debating over doing a 0.3.0f, but I've decided to move forward with the next update and include patch-style stuff there instead. Source will be released shortly.
