### ISSUE TITLE
Beta version allows finding armor in 'Faith is my Armor' mode

### ISSUE THREAD

**Issue by Count042** [00-Evan/shattered-pixel-dungeon#510]
Updated to the newest beta version on Google Play.   When playing in 'Faith is my Armor' challenge mode with the Huntress, I now find armor, and when receiving an award from the friendly ghost, am given a 'Ghost's Armor' choice.

**Comment by 00-Evan** [comment]
Read the changelog and the challenge description.

**Comment by Count042** [comment]
Ah, yeah, I totally missed that.  Sorry for the inconvenience.
