### ISSUE TITLE
Assassin does not identify rings upon equip

### ISSUE THREAD

**Issue by biobot775** [00-Evan/shattered-pixel-dungeon#512]
v0.9.0-beta-2. Theif's Intuition +2 selected (see screenshot). Rings do not identify upon equip (see screenshot 2). First noticed in Prison section. Can confirm that rings did identify upon equip in Sewer section.

Regards,

Nick

![Screenshot_20201001-111407](https://user-images.githubusercontent.com/72214497/94828994-111f1100-03d8-11eb-8de2-3b187d1c0e53.png)
![Screenshot_20201001-111357](https://user-images.githubusercontent.com/72214497/94829012-15e3c500-03d8-11eb-8d3c-0c5c220c64a2.png)

**Comment by 00-Evan** [comment]
This should be fixed in RC-1
