### ISSUE TITLE
Warlock can use ranged magic when adjacent, when first spawned

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#513]
In the battle with the king on level 20, if you're standing next to one of the spawners when a warlock spawns, it can use its ranged debilitation magic despite being right next to you.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Standing in any position either adjacent or on top of the spawner causes the warlock to correctly melee.

**Comment by joshtriplett** [comment]
Is there something else in that battle that would produce the sound effect associated with the warlock's debilitation magic (given no other warlock present)?
