### ISSUE TITLE
Revived champion dwarven ghoul does not maintain champion status

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#515]
![spd-20201004-154446-000.png](https://user-images.githubusercontent.com/69068719/95008904-b8aa7680-0658-11eb-98dc-7a86c3c73893.png)

![spd-20201004-154447-001.png](https://user-images.githubusercontent.com/69068719/95008926-ccee7380-0658-11eb-8a76-dde18503dd87.png)

It probably should be kept as champion, as in an extension of [#506](https://github.com/00-Evan/shattered-pixel-dungeon/issues/506)

**Comment by 00-Evan** [comment]
I'll see about correcting this in the full release of v0.9.0 on monday.

**Comment by N8fall** [comment]
Appreciate your hard work, and thank you for answering

**Comment by 00-Evan** [comment]
Fixed in commit dd4aeb3f3af3864c5c92d3229f7e8d4c746101b1
