### ISSUE TITLE
Typo: "led"

### ISSUE THREAD

**Issue by kundor** [00-Evan/shattered-pixel-dungeon#517]
https://github.com/00-Evan/shattered-pixel-dungeon/blob/6127cacf5e1a0ba997aaf3b8c58dd1730658043d/core/src/main/assets/messages/windows/windows.properties#L189

Typo in this message: "led" is the past tense of "to lead", so it should be "being led by some terrible dark power".

**Comment by 00-Evan** [comment]
fixed in commit e3c67d62ffddccca71fb1c1b0ed543d0bf992cde
