### ISSUE TITLE
Can sell worn cursed Master Thieves' Armband

### ISSUE THREAD

**Issue by mpettitt** [00-Evan/shattered-pixel-dungeon#518]
It's not normally possible to sell cursed items which have bound to your hero, but you can sell the Master Thieves' Armband, even if it's cursed (and has been deducting coins).

Was in first artifact slot, while playing as a huntress, if that makes any difference.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. The armband is correctly unsellable to me while equipped and cursed. Feel free to comment if you have more info and I'll re-open this if I'm able to reproduce.
