### ISSUE TITLE
Piranha's are not affected by electric traps

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#519]
I found a weird interaction, in that Piranhas are somehow immune to being in water that is electrified!

It's pretty hilarious that they can swim around happily in water that's _glowing_ with electricity :stuck_out_tongue:, but not very realistic, and a little sad that the interaction didn't work.

This seems like a result of Piranhas having the `BLOB_IMMUNE` property, which is correct for all the other effects (e.g: gases, fire).

![image](https://user-images.githubusercontent.com/5109532/95537334-c4b77f00-0a30-11eb-983e-65dc5b58c9c8.png)

**Comment by 00-Evan** [comment]
Sending me the same message on multiple platforms is much more likely to make me ignore it, rather than consider it further.

The 'realism' inconsistency is noted but as I said to you previously piranha are intended to be immune to all area-bound effects.
