### ISSUE TITLE
opengl config

### ISSUE THREAD

**Issue by Sarius997** [00-Evan/shattered-pixel-dungeon#52]
I don't know if you @00-Evan  wanna make it possible to run shattered on an android emulator (which comes with android sdk), but if you want so, you should change the following  code in [PD-classes/com/watabou/noosa/Game.java](https://github.com/00-Evan/PD-classes/blob/master/com/watabou/noosa/Game.java#L119)
```java
    view = new GLSurfaceView( this );
    view.setEGLContextClientVersion( 2 );
    view.setEGLConfigChooser( false );
    view.setRenderer( this );
    view.setOnTouchListener( this );
    setContentView( view );
```

to
```java
    view = new GLSurfaceView(this);
    view.setEGLContextClientVersion(2);
    // view.setEGLConfigChooser( false );
    // changed to be able to run it on my android emulator
    view.setEGLConfigChooser(true);
    view.setEGLConfigChooser(8, 8, 8, 8, 16, 0);
    view.setRenderer(this);
    view.setOnTouchListener(this);
    setContentView(view);
```

**Comment by 00-Evan** [comment]
I have no problems with making this change, only concern was to investigate potential impact on users and the application.

Naturally this is a change that affects every part of the app's operation so if it had to chance to adversely affect anything I would want to know. Obviously this should be equivalent but there could always be a rare edge case, etc. 

I'm actually running a beta right now though so that's the perfect opportunity to test this.

**Comment by Sarius997** [comment]
I currently had no problems on my Samsung SIII mini, but I had not the time to test everything carefully.

According to the beta:

1. What exactly does the left handed mode do? (Probably there is one possible addition according to this one)
2. I found your post according to this on reddit today and will also participate

**Comment by 00-Evan** [comment]
glad to have you on the beta =).

Left handed mode isn't called as such in the UI, I just used the term in the post as reddit users have asked for it before. in the game it's called 'flip toolbar' and it does exactly what that implies, everything that was on the right goes to the left, and vice versa.

**Comment by Sarius997** [comment]
You can possibly add also a functionality I have implemented in shattered-ice-dungeon and pd-ice:
it gives you the possibility to switch the screen from landscape to so called "reverse landscape" which is possible since api level 9, and I have implemented it like the immersive mode, so it should not cause any issues.

This is a feature I have always been looking for, so it was one of the first features I implemented in shattered-ice-dungeon. This function gives me as a left-hander the possibility to play the game with each screen orientation I want and for me, reverse landscape is easier to use than landscape mode. 
If you wanna have a look at the necessary changes:
[Preferences.java](https://github.com/Sarius997/shattered-ice-dungeon/blob/master/src/com/shatteredicedungeon/Preferences.java#L32)
[ShatteredPixelDungeon.java](https://github.com/Sarius997/shattered-ice-dungeon/blob/master/src/com/shatteredicedungeon/ShatteredIceDungeon.java#L190-209)
[WndSettings.java part 1](https://github.com/Sarius997/shattered-ice-dungeon/blob/master/src/com/shatteredicedungeon/windows/WndSettings.java#L53)
[WndSettings.java part 2](https://github.com/Sarius997/shattered-ice-dungeon/blob/master/src/com/shatteredicedungeon/windows/WndSettings.java#L165-176)

this should be everything I have changed to implement reverse landscape mode. 
Currently:
- is saved in the preferences, but not loaded on starting the game
- is only available if you are in landscape mode, because it does not resize the view (only changes screen orientation), so there is much more to change according to make this independent from landscape mode

**Comment by 00-Evan** [comment]
My preference for this would be to just let the user lock the screen rotation and then otherwise have the app rotate in whatever way the device is oriented. I'm sure it's possible to put in a switch so that this'll work in API 8 without reverse-landscape too.

There are some hiccups to doing this at the moment though, may tackle it in this beta.

**Comment by Sarius997** [comment]
According to opengl config, I had an idea which would be a good solution:
```java
    try {
        view = new GLSurfaceView( this );
        view.setEGLContextClientVersion( 2 );
        view.setEGLConfigChooser( false );
        view.setRenderer( this );
        view.setOnTouchListener( this );
        setContentView( view );
    } catch (IllegalArgumentException e) {
        view = new GLSurfaceView(this);
        view.setEGLContextClientVersion(2);
        // view.setEGLConfigChooser( false );
        // changed to be able to run it on my android emulator
        view.setEGLConfigChooser(true);
        view.setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        view.setRenderer(this);
        view.setOnTouchListener(this);
        setContentView(view);
    }
```
So it should try to set the opengl config like in shattered and vanilla, but if this fails for some reason, it takes the other version. And it should work on a phone like it ever did, but if the application runs on an emulator, it should work too.
But this did not work, because the exception is not thrown here which [can be seen in the log](https://github.com/Sarius997/shattered-ice-dungeon/blob/savegame-hotfix/log.txt).

This version should work (and would be a better way then just choosing the version which is needed for an emulator for every device):
[Link to the code](https://github.com/Sarius997/shattered-ice-dungeon/blob/savegame-hotfix/src/com/watabou/noosa/Game.java#L120-137)
```java
    if (Build.BRAND.contains("generic")) {
        view = new GLSurfaceView(this);
        view.setEGLContextClientVersion(2);
        // view.setEGLConfigChooser( false );
        // changed to be able to run it on my android emulator
        view.setEGLConfigChooser(true);
        view.setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        view.setRenderer(this);
        view.setOnTouchListener(this);
        setContentView(view);
    } else {
        view = new GLSurfaceView(this);
        view.setEGLContextClientVersion(2);
        view.setEGLConfigChooser(false);
        view.setRenderer(this);
        view.setOnTouchListener(this);
        setContentView(view);
    }
```
According to the information I found on the internet, Build.BRAND contains "generic" only if you are using the application on an emulator, so on a normal phone, the standard version for setting opengl config is called and if it runs on an emulator it sets the configchooser true and sets a standard config.
To check if it chooses the right way, [I added this to TitleScene.java](https://github.com/Sarius997/shattered-ice-dungeon/blob/savegame-hotfix/src/com/shatteredicedungeon/scenes/TitleScene.java#L184-206), to show if it detects an emulator or a mobile phone.

**Comment by 00-Evan** [comment]
I don't think there is necessarily any issues with simply manually setting the EGLConfigChooser. My point was simply that I would want to be sure it didn't cause issues. I'm going to test the original change locally and if it works fine it will be in the next beta build.

**Comment by 00-Evan** [comment]
Well it's causing issues (I hate android fragmentation), so it looks like the game will have to revert to the boolean selection for now. One question I had though, what emulator are you running that caused this to have issues initially?

**Comment by Sarius997** [comment]
I am using a Android 5.0.1 emulator from the android sdk tools. I did not know that this can cause any issues, as it works fine for me (also on my mobile phone).

**Comment by 00-Evan** [comment]
There's a lot of variance in android phones, probably some manufacturers have some wonky native implementation of GLConfigs which don't play nice with the more direct config chooser.

Additionally I'm curious about that emulator issue. I haven't tested with a 5.0.1 emulator directly, but previous gen SDK emulators have always worked with the old code, are you letting the emulator use your host GPU?

**Comment by Sarius997** [comment]
Yes, the emulator uses my host GPU. 
Here, you can see all my settings:
![avd settings](https://cloud.githubusercontent.com/assets/10520581/8861802/ad3640c8-318c-11e5-80bd-192b50d8c410.JPG)

**Comment by 00-Evan** [comment]
hmm, I wonder why that happens for you, I just updated from 4.4 to the M preview and i'm not getting any trouble.

I would prefer a solution that trys to get a config using the boolean value and if it fails then manually specify, that's far less brittle than specifically looking for generic device brands. As far as i'm aware there isn't a reliable way to check if the config fails though.

**Comment by 00-Evan** [comment]
So I've done some further looking into this, including inspecting the source for how the config choosers work.

Do you still get the issue if you use this line?:
view.setEGLConfigChooser(8, 8, 8, 0, 0, 0);

if so, what about this one, or this one?:
view.setEGLConfigChooser(8, 8, 8, 0, 16, 0);
view.setEGLConfigChooser(true);

the first one is identical to using the boolean select with a false value, the other two are also equivalent.

**Comment by 00-Evan** [comment]
Okay, from looking into this it seems like the best option is to programatically look for a valid config, with increasingly loose criteria.

the issue here is that the provided code sets an 8 for the alpha value, which causes issues on some older devices, but conversely modern android emulators (and possibly other devices) don't have a config available for anything but an 8 for alpha.

The solution is to add a NoosaConfigChooser class, which extends EGLConfigChooser, to the core library which tries to set config information, firstly by very strict criteria (basically emulating the old boolean false option), then by looser criteria (lets things like alpha be 8 and just hopes the device is okay with it).

Will look into adding this later (hopefully still in 0.3.1), for now i've reverted the code change back to the old functionality.

**Comment by 00-Evan** [comment]
actually, as a last resort before adding an entire config chooser class, what about RBG565?

Like this:
'view.setEGLConfigChooser( 5, 6, 5, 0, 0, 0 );'

That seems to work in my test devices and in emulators, and it fulfills the goals of the other config (RGB888) in not having depth or alpha.

As a bonus, RGB565 is 16-bit so if there are no compatibility issues it should save a bit of bandwidth.

**Comment by 00-Evan** [comment]
The RGB-565 change was made in the last beta, no issues have been reported so far.

You can opt in to receive betas from google play here: https://play.google.com/apps/testing/com.shatteredpixel.shatteredpixeldungeon

Once the source is released this ticket will be closed with the commit referenced.

**Comment by 00-Evan** [comment]
new config based on RGB565 has now been in production for a week with no issues reported, think it's save to call this one resolved.

relevant commit: 05fa28830ee25f00deff234159911edcb3b7563b
