### ISSUE TITLE
Tengu's shockers not acting correctly after entering game

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#520]
Recorded it [here](https://youtu.be/D5C83NrK8Ik), and it seems to be a pretty consistent problem

**Comment by 00-Evan** [comment]
This seems to affect all of Tengu's abilities, elevating this to major.

**Comment by 00-Evan** [comment]
fixed in commit 6d038edb2bd9555432e37e8de0f422039df0ad15
