### ISSUE TITLE
Sad ghost not showing up in diary/log thing 

### ISSUE THREAD

**Issue by Laserbean** [00-Evan/shattered-pixel-dungeon#523]
This is for version 0.9.0b
![Screenshot_20201018-212722](https://user-images.githubusercontent.com/23738910/96362262-9d775500-1188-11eb-9490-f08a01f467f1.png)

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. The ghost correctly appears in the landmarks section of the journal when they are seen for me.

**Comment by Laserbean** [comment]
Well, I'm playing with a few challenges. This is another game but it still didn't show the sad ghost landmark.

![Screenshot_20201019-105655](https://user-images.githubusercontent.com/23738910/96386756-b2400100-11f9-11eb-8f22-f671e43d98ff.png)
