### ISSUE TITLE
Sad Ghost quest pre-identified before choosing

### ISSUE THREAD

**Issue by jusrombawa** [00-Evan/shattered-pixel-dungeon#525]
After finishing the quest, instead of showing the generic ghost's equipment options, it showed the item descriptions. [Here is a screenshot](https://i.imgur.com/IS9HYVX.jpg). I got the item fine (mail armor +1, if it matters). There doesn't seem to be any other related issue other than the item description showing.

**Comment by jusrombawa** [comment]
Update, I found a post on reddit that you changed the prompt to show the item name instead of the generic prompt. Yes I'm on 0.9.0b, sorry I forgot to mention. I'm closing this ticket, sorry for the hassle. I probably would just suggest to capitalize the names and maybe hide the strength requirements.

**Comment by 00-Evan** [comment]
The visual strength requirement is there as I don't want to expect players to know what tier every weapon is yet, given that the quest takes place in the early game. I am aware the interface is a bit awkward though, and will be improving that in v0.9.1.
