### ISSUE TITLE
Ethereal chains cannot grab ground tiles in Tengu's second room

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#527]
This is on v0.90b, level 13 warrior, chains at +3 or +4. 

The message "There is nothing to grab there." appears when targeting ground tiles in Tengu's second room (the round room, where phase 2 of the fight happens). This is the same message that appears when targeting chasm tiles in Tengu's hallway after defeating him.

**Comment by 00-Evan** [comment]
The chains require a piece of adjacent solid terrain to latch onto, they cannot just grab the ground.
