### ISSUE TITLE
Sad ghost rewards show the item names instead of just weapon/armor

### ISSUE THREAD

**Issue by TiarnaNaTuaithe** [00-Evan/shattered-pixel-dungeon#528]
Shattered version: v0.9.0b
Beta user: Yes
Device: Google Pixel 3a
Android version: 11

I've noticed in the last two games that I've played that the sad ghost reward shows me the exact items the ghost is offering, instead of just options for weapon/armor. It was nice to get a gauntlet+2 when otherwise I would have chosen the armor, but it seems like this is a bug :)

![Screenshot_20201026-181111](https://user-images.githubusercontent.com/42155489/97327665-194e5d00-186d-11eb-9568-f7ce37a06549.png)
![Screenshot_20201027-154854](https://user-images.githubusercontent.com/42155489/97327700-23705b80-186d-11eb-922d-0221dd3b7bb0.png)

**Comment by 00-Evan** [comment]
Check the changelog, this is intended.
