### ISSUE TITLE
Armored brute in shielded mode didn't have shield decay over time

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#532]
I ran into an armored brute whose shield didn't decay over time. I could still damage it, but I couldn't just avoid it and wait it out. I investigated it, and it showed the "Brute Rage" buff, but the amount is shielding didn't decrease with time, only with damage. In particular, I damaged it down to 1 shield remaining, but it's still active and able to move towards me.

**Comment by 00-Evan** [comment]
Armored brutes lose their shield much more slowly, this is intended. Their shielding drops by 1 every 3 turns, instead of 4 every 1 turn.

**Comment by joshtriplett** [comment]
On Tue, Nov 10, 2020 at 08:05:26AM -0800, Evan Debenham wrote:
> Armored brutes lose their shield much more slowly, this is intended. Their shielding drops by 1 every 3 turns, instead of 4 every 1 turn.

Ah, that makes sense. It was decaying so slowly (and from a round-number
perspective, going turns without decaying at all) that it wasn't obvious
it was decreasing.
