### ISSUE TITLE
Animation from ring of wealth drop can happen on the wrong tile when enemy dies while moving

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#533]
If an enemy dies on its move (rather than from something the player does), such as by walking through a trap or cloud or being on fire, and the player's ring of wealth triggers on the drop, the animation for the ring of wealth will play on the old tile, while the item drops on the new tile.

Cosmetic, but it breaks the association between the ring of wealth animation and the item appearing.

**Comment by 00-Evan** [comment]
fixed in commit 74ae04a616b182aeac2f4c97f9eb86d136717a29
