### ISSUE TITLE
nature's aid doesn't do anything

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#534]
Nature's aid talent has no effect.  Plants are trampled and no barkskin occurs.

**Comment by 00-Evan** [comment]
I've had a few people report this issue so far with no information about how to reproduce it. Grass is not considered a plant, if that's what you mean.

**Comment by protective1** [comment]
Okay - thanks for explaining.  I did not realize that grass was not considered a "plant" for this talent.
