### ISSUE TITLE
the 3rd boss battle is broken

### ISSUE THREAD

**Issue by DaKnig** [00-Evan/shattered-pixel-dungeon#535]
I got to the 3rd boss with a great build of a mage and ... the boss just doesn't appear anywhere even when I use mind vision. unless that's some new feature not documented in the changelog, this looks like a bug.
![No Boss On Floor](https://user-images.githubusercontent.com/37626476/99189131-5caf3380-2768-11eb-9601-29577cd6d1fe.jpg)

**Comment by 00-Evan** [comment]
DM-300 spawns when the player approaches a power pylon. This change was made in a patch to v0.8.0 and is designed to make the fight easier to understand by forcing the player to realize the pylons exist before the fight starts.
