### ISSUE TITLE
talisman of foresight reveals room but not secret door

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#537]
This seemed a little strange to me - the talisman of foresight revealed complete and entire secret rooms, but not the secret door to enter those rooms.
![Screenshot_20201114-215625](https://user-images.githubusercontent.com/8593007/99340908-ed643d00-2856-11eb-9f3b-d59522a4c935.jpg)

I used the talisman a few more times at different angles and eventually the door was found, but this seemed like an unexpected result.

**Comment by 00-Evan** [comment]
The Talisman scans on a per-tile basis. If the door isn't included in the scan it won't be revealed.
