### ISSUE TITLE
Conserved damage shared across kinetic melee weapon and kinetic bow

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#539]
If you get lucky and end up with a kinetic enchantment on both a melee weapon and the bow, you can use one to generate conserved damage, and then the other will apply that damage on its next attack.

Not sure if this is a bug or intended behavior, but it seemed sufficiently unusual to be worth reporting and checking about.

Then again, it's making for a rather entertaining game, and it's fun to do 50-90 damage with one shot of the bow.

**Comment by 00-Evan** [comment]
This is intended
