### ISSUE TITLE
CPU jumps on Desktop when minimized/idle

### ISSUE THREAD

**Issue by vshih** [00-Evan/shattered-pixel-dungeon#540]
I notice that the CPU really jumps whenever the desktop game is minimized or idle.

To investigate I started tracking framerate; when playing I get ~60 FPS; once minimized/idle it jumps up to ~400 FPS.

A little googling seems to indicate this is an issue with libgdx, or one of its libraries:

- https://github.com/kotcrab/vis-ui/issues/240
- https://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18770

**Comment by 00-Evan** [comment]
This is likely a video driver issue. The game already attempts to enforce a regular vsync fps limit, and it seems that's not getting enforced when the game is minimized on your machine. On my machine the framerate is not affected by minimizing. There also aren't any tools that LibGDX provides that allow me to adjust rendering rate, (the idle fps setting does not affect continuous rending mode, which Shattered uses). I would suggest opening an issue with LibGDX if you suspect there's a problem with the framework.
