### ISSUE TITLE
Rusted fist can take negative damage

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#541]
When the rusted fist converts damage taken into defered damage (https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/YogFist.java#L407), it doesn't check if the damage is greater than 0. As a result, the defered damage can be negative as you can see in this screenshot (https://i.redd.it/yfp0libwdz061.jpg).

**Comment by 00-Evan** [comment]
I'm already aware of this one, it's going to be fixed in the next update. I've leave this issue open for reference but in the future please don't duplicate bug reports you've seen elsewhere.
