### ISSUE TITLE
corrupted ghoul revive other ghouls

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#542]
A corrupted ghoul still helps other dead ghouls revive.  This is a screenshot waiting with my new buddy ghoul for his ex-companion to revive.
![Screenshot_20201128-170910](https://user-images.githubusercontent.com/8593007/100528035-3648b980-31a6-11eb-9377-29e53e649e2f.png)

We just waited for the dead ghoul to revive so that we could kill him and make the dwarf king leave his throne.

Note that if the corrupted ghoul had died instead of corrupting then the kneeling ghoul would also have died.

**Comment by 00-Evan** [comment]
fixed in commit 9ac85d3d773dd4970a495c48ed033db835be882a
