### ISSUE TITLE
Rockfall trap crashing game

### ISSUE THREAD

**Issue by mrswoman** [00-Evan/shattered-pixel-dungeon#544]
Ive tested it out with a few items( javlin, food ration, seeds, potions), i wasnt able to try a disarming stone because i didnt have one. 
 If you throw them at a rockfall trap to activte it the game crashs and sends to back to most recent floor enterance or where you last logged off leaving the trap still working.

**Comment by mrswoman** [comment]
Was playing on 9.1 beta when found

**Comment by 00-Evan** [comment]
Fixed in BETA-2
