### ISSUE TITLE
Beta mage crashing problem

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#546]
When activating shield battery while time is stopped via swiftthistle, the game stops functioning repeatedly as soon as the time stop effect ends

![20201202_204852.gif](https://user-images.githubusercontent.com/69068719/100869070-d91f7180-34df-11eb-83f7-878cfceb6052.gif)

**Comment by 00-Evan** [comment]
I'm aware of this bug with swift thistle, it'll be fixed in BETA-2

**Comment by 00-Evan** [comment]
Fixed in BETA-2
