### ISSUE TITLE
Game Crash on activating stonefall trap

### ISSUE THREAD

**Issue by daedals** [00-Evan/shattered-pixel-dungeon#549]
The game crashes if you throw an Arcane Stylus on a stonefall trap while standing in another room (see picture). Not really sure what circumstances are causing this. I can provide further details if necessary. It sets you back to fixed previous moment and is replicable. 
![Screenshot_20201203-202549](https://user-images.githubusercontent.com/44530593/101084437-3f72c580-35ae-11eb-9dad-cfa7c1aaf962.png)

**Comment by 00-Evan** [comment]
This should already be fixed, update to beta-2

**Comment by daedals** [comment]
Excuse me, should have looked at the closed section.
