### ISSUE TITLE
Request: text when wand of regrowth starts producing "furrowed" "grass"

### ISSUE THREAD

**Issue by lilwhitemouse** [00-Evan/shattered-pixel-dungeon#552]
I was super confused when this happened. A bit of text would have helped me realize what was going on a lot sooner.

"The wand is getting old and the new grass is not as healthy."?

**Comment by 00-Evan** [comment]
I'm planning on doing a large pass on description text relating to wands, staffs, and the battlemage in v0.9.2. This will likely be included in that. Though it is already mentioned in the item's description, and as the limit is constantly relaxed as the player levels up or upgrades the wand you might get a message about it in the game log very often.

**Comment by 00-Evan** [comment]
added in commit b7f2b29554454fe419157c2ac6314de7d4912434
