### ISSUE TITLE
Dieing from fire gives all death badges

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#554]
I died from fire and somehow got all death badges. I guess that this is not how it is supposed to be.
![Screenshot_2020-12-07-23-23-39-755_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/101412756-6c431780-38e3-11eb-840a-bc61cdbc4a2f.jpg)
![Screenshot_2020-12-07-23-25-15-331_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/101412789-7bc26080-38e3-11eb-86c2-28542cb2f2df.jpg)

**Comment by spixi** [comment]
Side note: It is also odd that death from deferred damage is the only death badge which is placed under the boss slain badge.

**Comment by 00-Evan** [comment]
Looks like this is a side effect of a change in v0.9.0. You got the YASD badge that game and the game incorrectly unpacked that into all of the lesser badges.

Deferred damage is correct as it's a silver badge and those are shown together.

**Comment by 00-Evan** [comment]
fixed in commit bffdeae055999224c1c10e6b581823394c2ea9ec

**Comment by spixi** [comment]
@00-Evan Now it seems that I don't get the Death from deffered damage badge at all in the statistics. But this is not a real issue, because you see the reason of death in the description and also not all kinds of death have a badge (e.g. pricking or electricity).
![Screenshot_2020-12-20-04-06-26-020_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/102704225-ef1b8900-4278-11eb-9e24-9cdbfc08776e.jpg)

**Comment by 00-Evan** [comment]
@spixi Seems that's unrelated, but I can fix it nonetheless.
