### ISSUE TITLE
Upgrading to 0.9.1-beta3 changed quickslot item

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#555]
I had a game going, and upgraded to 0.9.1-beta3. Previously, I had a staff of corruption in the rightmost quickslot. After upgrading, that quickslot now contains the dew vial.

**Comment by 00-Evan** [comment]
There have been no changes to quickslot logic in several updates, and updating between versions does not directly affect runs in progress unless there is specific logic for it. There's is no updating logic in place which touches quickslots atm. It's most likely that you accidentally assigned your vial to the quickslot toward the end of your previous session.

**Comment by joshtriplett** [comment]
I was actively using that quickslot item regularly, and would have noticed if it changed. I was in the midst of the final boss battle, and was using that staff heavily. It was still in the quickslot when I closed the game.
