### ISSUE TITLE
Freeze when DM-201 dies

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#556]
I had a DM-201 which was trapped between a dead end and a spider web. When it died, the game froze.

**Comment by 00-Evan** [comment]
Which game version did this freeze occur on?

**Comment by spixi** [comment]
I think it was one of the 0.9 betas, not the current 0.9.1-beta-4. I only faintly remember it, so it may be already fixed as DM-201s cannot entry dead ends anymore.

**Comment by 00-Evan** [comment]
There were a few freeze bugs fixed earlier in the beta. I'm closing this for now but feel free to comment if you get it again.

**Comment by spixi** [comment]
@00-Evan I guess i found it. 
https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/DM201.java#L129
https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/Level.java#L658
This will never terminate, if there are only solid tiles around the dying DM201. Caustic blob also uses a similar drop mechanic and can also appear in halls via distortion trap.

**Comment by 00-Evan** [comment]
fixed in commit d64200e907ea3b08578037c77bf100b9803f03e2
