### ISSUE TITLE
Huntress doesn't get bark skin 

### ISSUE THREAD

**Issue by langdon** [00-Evan/shattered-pixel-dungeon#557]
I am not 100% sure how the barkskin talent is supposed to work so this may be me. However, at 1pt in barkskin talent, I never seem to get the buff if I or a monster trample grass.

Version 9.1-beta-4 android

**Comment by 00-Evan** [comment]
Grass is not a plant, the talent triggers when plants (from seeds or placed by the level) are trampled.

**Comment by protective1** [comment]
Since this is a frequent misconception, would it make sense to change the talent description to say "when a non-grass plant is trapped..."?  I know it's redundant by game terminology, but in real-world terminology, grass *is* a plant, hence the common confusion.
