### ISSUE TITLE
Empowering Meal +2 does not affect Staff of Transfusion

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#558]
After eating a Ration of Food I zapped a Skeleton with Staff of Transfusion, but the extra damage of the talent Empowering Meal +2 did not trigger.

**Comment by 00-Evan** [comment]
Transfusion is not a damage wand, and so does not benefit from empowering meal. In a similar vein, the wand of warding does not benefit from empowering meal.
