### ISSUE TITLE
Staff imbued with Wand of Fireblast broken

### ISSUE THREAD

**Issue by bbottema** [00-Evan/shattered-pixel-dungeon#56]
Early Mage is difficult enough and finding (useful) wands attributes to that, so I was happy to finally be able to find and identify a Wand of Fireblast and imbue it in my staff. 

Unfortunately it proved to be suicidal as zapping with the staff sets my mage on fire, killing me more quickly than the enemy I was zapping. [Others too reported this](https://www.reddit.com/r/PixelDungeon/comments/37dinn/shattered_pixel_dungeon_v030_the_wand_rework/crmfu4p) issue.

**Comment by 00-Evan** [comment]
This is intentional. The wand will ignite flammable terrain, including where the player is standing. Part of using that wand effectively is being careful about positioning.

I may make some changes to the description for clarity's sake, but the issue reported is not a bug.
