### ISSUE TITLE
transmutation lost artifact levels of unidentified hourglass

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#560]
I found the hourglass in the dungeon. A well confirmed that it was uncursed. I hadn't equipped it yet. I reached the next shop, and stole/bought three bags of sand for it. Later on the same floor, I found a scroll of transmutation, and used it on the hourglass. That turned it into the unstable spellbook. I equipped the spellbook, and was disappointed to find it still level 0; I expected it to have the levels from the hourglass.

Playing 0.9.1-beta3.

**Comment by 00-Evan** [comment]
This is because the artifact was unidentified. Generally unidentified artifacts can't be upgraded, I'll consider how to correct this case.

**Comment by 00-Evan** [comment]
I've corrected this, though perhaps not in the way you were hoping for. Unidentified/cursed timekeeper's hourglasses will no longer spawn sand, this is consistent with how the dried rose functions.

**Comment by joshtriplett** [comment]
On Sat, Dec 12, 2020 at 04:08:24PM -0800, Evan Debenham wrote:
> I've corrected this, though perhaps not in the way you were hoping for. Unidentified/cursed timekeeper's hourglasses will no longer spawn sand, this is consistent with how the dried rose functions.

That doesn't seem unreasonable to me, as long as it's clear from the
description. I had a scroll of identify, I just didn't use it because I
didn't think I had to do so before leveling up the hourglass.

That said, does that mean that you have to identify the hourglass before
even generating a floor with a shop?

**Comment by 00-Evan** [comment]
> That said, does that mean that you have to identify the hourglass before even generating a floor with a shop?

Yes, that's the same as with the dried rose, though of course missing a shop is more punishing than missing a single level. All artifacts should need to be identified before their upgrade process can begin.

**Comment by 00-Evan** [comment]
adjustment was made in commit 267d04a82b3a146833d43eebe4482f3ec2719a04
