### ISSUE TITLE
can't create Arcane or Shrapnel bombs

### ISSUE THREAD

**Issue by patman-cp** [00-Evan/shattered-pixel-dungeon#561]
On v0.9.1a via Google Play, at alchemy pots I'm not able to combine a bomb with goo or shrapnel - it shows nothing after I've put them all in the pot.

**Comment by 00-Evan** [comment]
Odd, no changes were made to alchemy logic. Can you confirm that you have enough energy to craft those, and that other alchemy recipes work?

**Comment by patman-cp** [comment]
Other alchemy is fine.

I have a screenshot, not sure where I can put it but it shows 32 energy.

I also had some weird deja-vu thing after the switch to beta - I swear I repeated a few rooms (one was a well / fall into room) after starting the game and I think after the update from v0.9.1 to v0.9.1a.

**Comment by patman-cp** [comment]
Also, I tried it on another alchemy pot and it failed.

**Comment by patman-cp** [comment]
![Screenshot_20201216-112236](https://user-images.githubusercontent.com/42042889/102501072-dd947000-4031-11eb-8ef6-d81786015238.jpg)

**Comment by 00-Evan** [comment]
Those bombs require one goo blob or one metal shard, not two. Can you show me a screenshot of the recipe with just one?

**Comment by patman-cp** [comment]
Ugh! Don't know why I thought it was two, I've played so many time :-( I'll check when I get back to another pot.

**Comment by patman-cp** [comment]
Not a bug.
