### ISSUE TITLE
Chalice of life isn't draining life

### ISSUE THREAD

**Issue by patman-cp** [00-Evan/shattered-pixel-dungeon#562]
With 0.9.1a, a prick on the chalice seems to only decrease health by 1, no matter the chalice level - though I'm a bit hesitant to keep trying it.

**Comment by 00-Evan** [comment]
Armor can reduce the damage that the chalice deals, so you might be taking minimal damage on the first few pricks because of that.

**Comment by patman-cp** [comment]
OK - yeah it was just minimal damage, closing.
