### ISSUE TITLE
Possible to stuck the necromancer in a tunnel with wand of living earth

### ISSUE THREAD

**Issue by supermamie** [00-Evan/shattered-pixel-dungeon#563]
I am not sure that this is really a bug, but in a tunnel, if you cast the wand of living earth on a necromancer while it invoking, the skeleton can not spawn (it can not push the earth as the necromancer and player are both side), so the necromancer is stuck trying to do this, and can be killed easily.

![image](https://user-images.githubusercontent.com/693751/102475203-e00ac000-4059-11eb-9114-897a60383cfc.png)

**Comment by 00-Evan** [comment]
Hmm, I see your point that this situation is easy to reproduce with an ally. Probably in these cases necromancers should deal damage each turn that they are unable to summon their skeleton, if they aren't able to push whatever is blocking them. This is more of a balance change though, so I'll save it for the next full update.

**Comment by 00-Evan** [comment]
Changed my mind, this is niche enough to include in v0.9.1b even if it does affect balance slightly

**Comment by 00-Evan** [comment]
fixed in commit 96d0b046d0e8a1bb79cc2edb544c5a5860f338c8
