### ISSUE TITLE
tengu traps remain after defeating first phase

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#564]
Defeated first phase of tengu and poison dart traps remain.  I have a ring of fury.
![Screenshot_20201219-095210](https://user-images.githubusercontent.com/8593007/102692304-7b2da200-41e0-11eb-9438-612f4ad47fe6.png)

**Comment by 00-Evan** [comment]
This is a rare visual bug. The traps are actually removed, the visual effect of them fading persists.

**Comment by 00-Evan** [comment]
fixed in commit 50ec4f8dbed53b2b422906e3a366305f26c261df
