### ISSUE TITLE
Can't close Patreon invitation popup

### ISSUE THREAD

**Issue by HenriDellal** [00-Evan/shattered-pixel-dungeon#565]
When I finished level 5, I've got a popup which couldn't be closed. The buttons are not clickable and not properly sized. Clicking outside of the popup does nothing as well.

Version: 0.9.1

![Screenshot_20201221-184132](https://user-images.githubusercontent.com/29340702/102795029-40cd2c00-43bd-11eb-9c5c-859f6756b637.jpg)

**Comment by 00-Evan** [comment]
Hmm, thanks for reporting this. This has rarely happened a few times in the past and I've never been able to reproduce it. I'll take another look into it again and see if I've missed something.

**Comment by 00-Evan** [comment]
Unfortunately I'm not able to reproduce this, or identify any reason why it may happen. Fell free to comment if you have more info, or this happens again, and I'll reopen this issue.

You can also work around this by leaving the game, swiping it out of your recent apps list, and re-launching it.
