### ISSUE TITLE
Invalid locations for plants' spawn and planting

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#566]
I've came across a plant where it was scorched shortgrass underneath it.
![Screenshot_2020-12-23-01-18-59-53_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/103163105-42a24f80-4802-11eb-9815-367644d3b2a0.jpg)

Also, I was able to plant a firebloom on a door. I think it shouldn't happen.
![Screenshot_2020-12-25-03-31-37-91_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/103163124-7b422900-4802-11eb-9c3e-a8504079ec07.jpg)

**Comment by 00-Evan** [comment]
Both of these are possible in specific circumstances:

- wands of disintegration can torch grass, but do not destroy plants
- plants can be placed in open doors, and closing the door does not destroy them.

**Comment by Leajian** [comment]
About _plants can be placed in open doors, and closing the door does not destroy them_, I opened the door, closed it and then I threw it onto the closed door and it bloomed. Is that another circumstance?
