### ISSUE TITLE
Crash after opening a chest while levitation ends

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#567]
I was in a bonus room with 4 golden chests. I tried to optimize my pathing. I was on air, levitating with 1.5 rounds of the effect remaining, because I had a ring of haste +0. I was playing assassin, but **not** freerunner. After my attempt of opening the chest, the circles that indicate the rounds looked like overlapping each other, the game froze and after a while it crashed. When reloaded, the level was restarted to the point I entered it (sadly). This is the exact still-image of the freeze occurrence. I don't know if the next level generation failed (failed to calculate the position I would fall) or a miscalculation of the remaining levitation rounds caused it. I personally believe that some rounds would be spent opening it on the current level and some on the next while falling and that caused the game to fail finding the distance of the hero from the chest. I didn't dive deep into the code, but I think [this function](https://github.com/00-Evan/shattered-pixel-dungeon/blob/b61eb8c8a73d06955475aaec80dbb141a39b5ff2/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/hero/Hero.java#L846) is responsible. Unfortunately, I don't have any logs to provide more insight.
![Screenshot_2020-12-27-05-07-23-92_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/103163172-26eb7900-4803-11eb-992e-c291d45d41b7.jpg)

**Comment by 00-Evan** [comment]
I've attempted to reproduce this, and the game correctly lets the opening action complete before the hero gets dropped into the pit. The freeze, and deletion of save data, makes me feel like this may be a memory related crash in native code. Java code (like the function you mention) usually lets the game properly shut down as the crash happens.

This is likely a once-off and not possible to reproduce. Please feel free to re-open this if you encounter this issue again.
