### ISSUE TITLE
Windows java

### ISSUE THREAD

**Issue by krtfwd** [00-Evan/shattered-pixel-dungeon#569]
on a i3-560 (igd) using openjdk 15 I am getting the 
opengl 2.0 not supported error
Does not do this on linux I can play the game fine
Is this fixable on your end or do I have to do something about this ?
also when will you be releasing a version with jre included in it so its playable without downloading java

**Comment by 00-Evan** [comment]
windows drivers for old versions of intel IGP do not support opengl 2.0, and so cannot play the game. Bundling a JRE will not fix this.

**Comment by krtfwd** [comment]
:(
