### ISSUE TITLE
The previous imbue will be lost

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#570]
Staff imbue text has not been adjusted to reflect 100% wand preservation talent.  Text says that previous imbued wand will be lost, even though there's a 100% chance this won't happen.

**Comment by 00-Evan** [comment]
I'm making a general pass on improvements to wand/staff related text in v0.9.2, I'll look into this then.

**Comment by GrantMoyer** [comment]
Along the same lines, It would also be nice to display a warning that the wand *will* be lost if all the uses of the talent have been expended.

**Comment by 00-Evan** [comment]
text added in commit 9eb0b3400861ab87690116dc97415f662241c8da
