### ISSUE TITLE
Dualshock/Gamepad feature

### ISSUE THREAD

**Issue by toumbo** [00-Evan/shattered-pixel-dungeon#571]
As I installed the game from my linux-based pc (1), that great idea came to mind!

What if I could use my ps4 controler instead of keyboard?

Is this possible? Is it easy?

(1) https://snapcraft.io/shattered-pixel-dungeon

**Comment by 00-Evan** [comment]
This is something I plan to do, but it isn't a priority right now. Controller support in the game framework i use (LibGDX) is currently being improved, and there are several considerations when it comes to how the game may work with a controller, or how it might work with 100% keyboard (see #351)

**Comment by benkorpella** [comment]
Native support would be nice, but a work around could be mapping your controller buttons to the appropriate keys.

**Comment by 00-Evan** [comment]
Native controller support is now implemented for v1.2.0, will close this when that update released.

**Comment by 00-Evan** [comment]
Implemented over several commits in v1.2.0.

I do plan to make further improvements to controller functionality in future updates.
