### ISSUE TITLE
Awkward scrolling in the alchemy recipes menu

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#573]
It only works when you tap outside of any of the buttons there.

**Comment by 00-Evan** [comment]
This is working correctly, buttons grab the touch input, and so you aren't able to scroll by pressing on them. The game can't know whether you want to scroll or tab on that item, so it assumes you're trying to tap the item.

**Comment by MiroslavR** [comment]
What do you mean? It works elsewhere, e.g. in the Adventurer's Guide. This is a big usability issue, it took me forever to figure out it was even possible to scroll in the first place because the buttons take almost all the space.
