### ISSUE TITLE
Horn of plenty too powerful with new talent system

### ISSUE THREAD

**Issue by shortmanikos** [00-Evan/shattered-pixel-dungeon#574]
With the new talent system there are some talents that activate on eating. This makes the Horn of Plenty quite the unfair artifact. Maybe these talents could only activate when eating at least half a ration worth of food. To make my point clearer I just played the mage - eating 1 or 2 units from the horn of plenty every 10 turns basically gave me almost permanent  wand recharging for free.

**Comment by 00-Evan** [comment]
The horn of plenty has been an underperforming artifact for a while now. It is intentional that v0.9.1 indirectly buffs it.
