### ISSUE TITLE
can't assassinate out of field of view

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#575]
In prior versions, assassins could prepare a surprise attack and hit outside their field of view (assuming you know where the enemy is standing).  In the most recent version 0.9.1a this is no longer possible.  So an enemy can now escape the range of the prepared attack by walking through a door when previously that was not possible. This change really weakens the assassin's abilities.  I'm not sure in which version this change occurred because I haven't played assassin class for a while.

**Comment by Leajian** [comment]
I don't think that it was ever possible. You might be confusing this ability with assassin's upgraded armor, the rogue garb. It allows a teleport that can be cast anywhere in line of sight.

**Comment by 00-Evan** [comment]
This was a bug that was fixed in v0.9.0
