### ISSUE TITLE
unexpected behavior: can't assassinate when ward blocks the path

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#576]
If a ward (eg in a hallway) is blocking the walking path to a target then the assassin can't hit the target with a prepared attack.  This seems inconsistent with the fact that you can jump gaps (chasms) to hit a target of a prepared attack.  In the ward case you can't walk to the target so it's an invalid target. In the chasm case you also can't walk to the target, but it's valid.

**Comment by Leajian** [comment]
I think it's designed to dash onto rather than dash through. So, if the assassin can see, he can dash, even over chasms. But something blocking his field of view makes him unable to see a target. I guess it's not about pathing, it's about the line of sight and the viable tiles to teleport to.

**Comment by 00-Evan** [comment]
It looks like this is happening because the ward is adjacent to the enemy you are blinking to. In these cases the game doesn't want to let you end up on the ward, but is accidentally setting that tile as not even pathable for a jump. If the ward wasn't adjacent to the enemy you could go over it.

**Comment by 00-Evan** [comment]
Putting this one off to v0.9.2 as it requires more significant changes to logic than I anticipated.

**Comment by 00-Evan** [comment]
fixed in commit 94de68caadda4615957783d725ff2aeda60e7632
