### ISSUE TITLE
A corrupted Necromancer's skeleton isn't corrupted

### ISSUE THREAD

**Issue by antikovt** [00-Evan/shattered-pixel-dungeon#577]
Not really a bug or a problem, just wanted to bring it up to your attention. If you corrupt a Necromancer before killing his skeleton, the skeleton will stay normal and start attacking the Necromancer. It's kinda funny, but doesn't make logical sense, as the Necromancer is supposed to 'control' his minions. I would leave it as it is imo, but still

**Comment by 00-Evan** [comment]
This is intentional, mainly because getting a double corruption for free like this would be extremely powerful, and corrupting necromancers is already really useful.
