### ISSUE TITLE
Confirmation dialogue when selling SoC/PoS

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#579]
Even though this recommendation sounds foolish, accidents do happen. It would be nice to have a confirmation for those two.

**Comment by 00-Evan** [comment]
I prefer to err on the side of trusting the user that they are intending to give inputs, unless it is very easy to misclick (which is why chasms have a warning).

I do intend to eventually overhaul the shop UI though, and when I do that I will likely include a buyback button.
