### ISSUE TITLE
Can't descend if a dewdrop is blocking ladder

### ISSUE THREAD

**Issue by vshih** [00-Evan/shattered-pixel-dungeon#580]
It seems you can't descend a ladder if there is a dewdrop covering it and you have full health and a full vial. You get alerted that "you already have full health" after every attempt, and are stuck.

**Comment by antikovt** [comment]
Have you tried pressing the skip arrow if it is there?

**Comment by vshih** [comment]
I'm pretty sure it was not visible.

**Comment by 00-Evan** [comment]
Dew can be drank from the vial even if your health is full. You can simply drink from the vial and then collect the drop.
