### ISSUE TITLE
Rare "inescapable Tengu bombs" bug

### ISSUE THREAD

**Issue by antikovt** [00-Evan/shattered-pixel-dungeon#581]
Had this bug two times already where I had been going straight away from Tengu's bomb for three turns in a row and still got damaged. I don't know how to replicate it, sadly, but I've lost two perfect runs because of it :( I am 100% sure I didn't have any extra speed or slowdown.
Edit: All the bombs in the bugged fight behave this way

![Screenshot_20210105-125206](https://user-images.githubusercontent.com/76940779/103620188-e2738200-4f54-11eb-9075-be7179cdd3fc.png)

Also, a bit off the topic, but it would really help if you made the particle effect for the Tengu's bomb a little bit more dense and less spread out, so the area of effect would be easier to see. It took me several runs of trial and error to see that it's 5x5, not 7x7.

**Comment by antikovt** [comment]
I did have my bow augmented for speed though, now that I think about it. Could that have been the reason for this behaviour? I'm still sure I've been out of range of the bomb though. I thought I was crazy the first time it happened, but all the bombs in the fight have been acting this way

**Comment by antikovt** [comment]
Important update: I managed to replicate the situation by again playing as a Huntress with a Bow, augmented for speed. I'm attaching a screen rec and a couple of screenshots of my inventory.

https://user-images.githubusercontent.com/76940779/103653895-fafc9000-4f86-11eb-9fe8-d2a2e27ae03d.mp4
![Screenshot_20210105-184816](https://user-images.githubusercontent.com/76940779/103653961-16679b00-4f87-11eb-9d32-188f7bad25f8.png)
![Screenshot_20210105-184820](https://user-images.githubusercontent.com/76940779/103653974-1a93b880-4f87-11eb-91e1-f215acb83a5e.png)

**Comment by Leajian** [comment]
It seems like the explosion activated the other grenade earlier. I don't know if it's a bug or a feature. Interesting.

**Comment by antikovt** [comment]
> It seems like the explosion activated the other grenade earlier. I don't know if it's a bug or a feature. Interesting.

I mean, no, the bomb activated in time, it's apparent in the video. And even if it did activate one turn earlier, it still wasn't supposed to hit me, as I was out of range already two turns after it was thrown. It takes two turns of walking away from the bomb to get out of it's range, while I walked three.

**Comment by 00-Evan** [comment]
This issue was present in a beta release of v0.9.1b, and was fixed when v0.9.1b went live. Please update your game.
