### ISSUE TITLE
Runic Transference dialog is unclear if both glyphs are identical

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#582]
When an armor and the broken seal carry the same glyph, the "Choose a Glyph" dialog presents two identical options and it is unclear which one erases the glyph on the seal. One has to find out the hard way, or read the source code. :)

**Comment by 00-Evan** [comment]
fixed in revision aac9cf73674f72741a7b4f623e141e21594caee3

**Comment by MiroslavR** [comment]
So what happens now if I affix and detach the seal? Will the armor lose its glyph?

**Comment by 00-Evan** [comment]
> So what happens now if I affix and detach the seal? Will the armor lose its glyph?

Yes, the game now automatically prefers the glyph on the seal when both are identical.
