### ISSUE TITLE
feeding mechanics

### ISSUE THREAD

**Issue by vinniec** [00-Evan/shattered-pixel-dungeon#583]
I have known and played Pixel Dungeon before anyone started forking it.
I always liked it a lot but every time I started playing it again, I get tired of it immediately.
The reason is that every time my character was diving of starvation.
This thing is compounded even more by the style of play that some players have like me, I love to explore the whole level and have always hated generally racing against the time, also for this reason I like turn based game.
And it is extremely frustrating failing a game because you haven't the time to continue playing.
A few years ago I looked for an alternative and found lovecraft pixel dungeon, In which the feeding mechanic was less pressing because from the beginning of the game you could create food from plants. But that is an unsupported fork differently from yours which can now be considered the principal version of PD.
I can understand that this mechanic serves to balance the others, but in this way it becomes predominant and you end up playing trying not to starve.
In other roguelikes this mechanic has been tempered (for example in Lost labyrinth where I was the one who asked the developer to permit to the fruit also removed the thirst, in this game you could also die of thirst) or totally removed (like dungeon crawl stone soup recently totally drop out this mechanics, In this game there were different ways of finding food, for example slaughtering the monsters or there is some race like mummy or vampire, but they still decided to remove this because they follow the philosophy that no fun parts are superfluous).
So I'm not asking you to remove the food but to add some additional way of getting it, like for the monsters who already release meat but are still not enough. For example you could put the possibility of food appearing when using the search for secret doors, due to the fact that searching the level is a time-wasting operation, I believe this would balance the game better for people who explore more without too many modifying it for others. You could make the archer better at finding food than other classes such as talent for example.
Think about it a bit, if you really don't like it as a solution, you could put the option in the settings to disable hunger, to allow even those like me to enjoy the game.

**Comment by alanmcg** [comment]
This used to be an issue for older versions of pd, starvation was far too common. In the recent versions of shattered I haven't been close to running out of food for as many games as I can remember. You just have to learn how to use food correctly. Kill and cook fish / crabs whenever possible and eat from that food first. Fill up the dew vial asap and the dew drops you find later will allow you to keep your health up while "starving". I usually finish the game with 5 or more foods left over with this strat. Only eat when in starvation and health hits around 60%

**Comment by vinniec** [comment]
Sorry but for my games this is not true. Also now my current game with archer. I used the vial, got the talent for berries (but I will have had max 5-6 berries at the start of the game and that's it), I was also very lucky and found the stick that creates the plants (heat eventually creates gray plants). I am without food and I am surviving, but by now I have lost because I have no more way to regain life. I even used two blessed Ankhs because I no longer had any way to cure myself.

**Comment by vinniec** [comment]
I also got the "nature bounty" talent as quickly as possible, maxing out 5-6 berries at the first levels and then it became useless
![Uploading Screenshot_20210106-170904.png…]()

**Comment by 00-Evan** [comment]
How often are you eating food? Usually people starve because they are either taking much too long or because they are eating before they need to.

I have no intentions of removing the hunger mechanic right now, it's a necessary part of the game to prevent extremely boring but effective turtling strategies. Each floor generates at least 300 turns worth of food, plus various extra food from meat, shops, or talents. It is absolutely possible to explore every floor and still have food to spare. I would much rather improve the game's tutorialization so that players spend less time being frustrated and not knowing what to do.

I'm going to close this issue as there's no action to be taken, but I'll be happy to reply to you if you wanted to talk more about this.

**Comment by vinniec** [comment]
since I easily die of hunger I try to consume as little food as possible, if I have a full life I let the character starve to make the food last longer. obviously this is a feature of the game that you thought so, in fact I did not ask you to remove it but at least to make the game possible even for people like me, that maybe they are slower than the others but as you can see from the shoots I'm not an inexperienced, this is not an early stage of the game and if I had had more food I would not have been in this condition. So I'm not asking you to remove the mechanic, but couldn't you at least add a setting, a difficulty level, a line of text in a config file?

**Comment by vinniec** [comment]
For my opinion something simple can be insert a multiplier for starvation speed, so if the value is 1.0 al remain normal, as your default, if you lower this value you have more time, for example with 0.5 you can have twice of the time

**Comment by TheYsconator** [comment]
I guess that would be easy to implement indeed. However, following the same reasoning, settings could be added for damage multipliers, player's walking speed, value-of-loot multiplier, mob-type occurrences etc... That would add a whole menu of just sliders and settings, something I would consider twice before adding.

It also raises the issue of not everyone playing the same game. Or at least; on the same difficulty. Currently, if I see someone on Reddit who has played through the game with certain gear, or died inconveniently, I can sort of guess what that player has been through. That whole sens of 'community-connectedness' may be impaired if one can tweak the difficulty of this game this easily.

At least to my gut feelings, the hunger mechanic is rather balanced at the moment. Evan has the specific Firebase stats of course, and with that I think it is safe to assume he keeps the game balanced overall. The many players who have played through this game many times whilst still finding joy, may be seen as proof of his success.

In all, I think it would do you well to consider changing some tactics. The game is rather lenient towards exploration, but in my experience it has been rather unwise to use the 'search' function every couple of steps. There's plenty of little food-gathering and time-saving tricks in this game, and discovering those is -in my opinion- part of the fun.

Regardless - and I know this is a knockdown argument, you can always change the source code yourself and recompile. If you need help with that, don't hesitate to poke me.

**Comment by 00-Evan** [comment]
I think Ysconator's comment covers my thoughts pretty well, the only thing I'd really add is that even if I were to add an easier mode to the game I probably wouldn't touch hunger too much. It's really important that the player feels a need to keep moving through the dungeon, as otherwise there's a big advantage to just sitting in one region and farming forever until the player has enough items to proceed. I'm fine with allowing some amount of farming, but it has to be in specific circumstances, not as a general game strategy.
