### ISSUE TITLE
Poison dart trap doesn't activate

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#584]
I have found a poison dart trap which doesn't activate when walked on or when items are thrown onto it.
![Screenshot_20210106-225131_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/46329185/103823444-63746b80-5072-11eb-91ea-cad2ffff878f.png)

**Comment by 00-Evan** [comment]
Hmm, might be an issue with the trap's position (as its in a door). Could you give me the seed to that run? You can get it to going to your runs in progress, selecting that run, and long-pressing on the hero sprite on the top-left of the window

**Comment by pescepalla** [comment]
Aw, sorry that run ended already :/ Next time it happens I will make sure to include this information right away before my hero meets a grisly end.

**Comment by 00-Evan** [comment]
There isn't a lot I can do about this then, unfortunately. I can say though that the reason there isn't a door in that cell is due to a bug that is getting fixed in v0.9.1c, and so that may fix this incidentally. I'll use this to track that bug instead.

**Comment by 00-Evan** [comment]
fixed in commit e37a298e3d553f59d8c4d12983bc9fda621b5743
