### ISSUE TITLE
[Improvement] Do not center on the character while moving

### ISSUE THREAD

**Issue by theFireProjet** [00-Evan/shattered-pixel-dungeon#586]
#### Current Behaviour
In Shattered PD the player can move the view to look around on the current floor. As soon as the character moves, the view is centered back on the character and moves together with the character.

#### Suggested Improvements
The view should keep moving together with the character, but not center on the character. Instead while moving, the character should stay at the same position on the screen (the same position relative to the view) as it was.

Optionally as a replacement to the old behaviour, there could be a new button that allows the player to center the view on the character manually, only when that is appreciated. In addition the button could zoom in on the character to a comfortable level. (For comparison, this behaviour would actually be similar to the floating action button in Google Maps that zooms in and moves to the current physical location of the user.)

### Why? User Benefit
It's a useful feature to be able to center on the character. But if you think about actual gameplay scenarios, it is implemented in the wrong way in regards to convenient user experience.

While moving forward, it's not neccesarry to see what's behind the character, because usually that's already known to the player. Instead, it's more important to see upcoming threats in front of the character on the screen. Of course it's more likely that the player will encounter new enemies ahead rather than behind the character (especially if the area was not yet explored).
That's why centering on the character while moving is actually not useful. Instead before moving forwards, I want to adjust the view myself, to decide how much I want to see in front of the character and how much I want to see behind it.

Imagine the game is running on a modern phone with an aspect ratio that is much wider than 16:9 in landscape mode. If you want to move the character up or down in the dungeon, there is not much space on the screen to the bottom and top. So I would rather like to see what's ahead of the character than what's behind (what I've seen already).

**Comment by 00-Evan** [comment]
The vast majority of players prefer for the game's interaction to be consistent and simple. Requiring the player to constantly manually switch where the camera is relative to the player is not only unintuitive but cumbersome. Doing so automatically would also be confusing as the camera would be constantly flying around when the player changes direction, this would cause some serious motion sickness. Keeping the camera centered is the best compromise.

Modern phones with 16:9 ratios also have relatively large screens, allowing the player to zoom the game out and see as much or more than on old phones with smaller screens and 5:3 aspect ratios.
