### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [00-Evan/shattered-pixel-dungeon#587]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by 00-Evan** [comment]
I'm happy to allow F-Droid to build and distribute an unofficial version of Shattered, but due to serious technical issues with their platform (see #459 and #479) I am no longer endorsing or helping maintain their distribution.

**Comment by 00-Evan** [comment]
> [@00-Evan](https://github.com/00-Evan), you can use third-party repositories for the F-Droid that have different requirements for publishing apps. For example, [IzzyOnDroid F-Droid Repository](https://apt.izzysoft.de/fdroid/).
> 
> In any case, despite your stated **2021-01-10** refusal to work with F-Droid, F-Droid itself continues to work with you, because on [the application page](https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon/) the latest available version is 2.5.4 (802) dated **2024-10-13**.

As I mentioned above, I'm happy to let F-Droid continue distributing Shattered in an unofficial capacity. I would not consider taking the game's freely available source and packaging it as 'working with me'.
