### ISSUE TITLE
The game crashes in specific acts

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#590]
1. The crash occurs when I tried to imbue a +6 wand of regrowth to my mage's staff.

https://user-images.githubusercontent.com/76470428/104399114-5e904a00-5593-11eb-99c0-964501dfb517.mp4

2. The crash occurs as I moved adjacent to an activated power plant while fighting with DM-300.

![1610503635581_1610503635581_1](https://user-images.githubusercontent.com/76470428/104399247-a2834f00-5593-11eb-82d9-5cab25da402e.gif)

Equipments are here⬇️
![Screenshot_20210113-113105](https://user-images.githubusercontent.com/76470428/104399315-c2b30e00-5593-11eb-95c6-3890d233fbfe.jpg)
※ Hostile Champions challenge activated

Thanks in advance.

**Comment by 00-Evan** [comment]
This is already fixed in amended v0.9.1c, please update

**Comment by Hoto-Mocha** [comment]
> This is already fixed in amended v0.9.1c, please update

but its already v0.9.1c
