### ISSUE TITLE
Typo in Shield Battery description in 0.9.1c

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#591]
The mage can s**M**lf-target...

![138387465_957426951755985_8659250388737772223_n](https://user-images.githubusercontent.com/1816060/104437048-ff343900-5596-11eb-9e92-339861f0a649.jpg)

**Comment by 00-Evan** [comment]
fixed in commit 1c53ae6e7c8bf2b12613ead10b02232f00815212
