### ISSUE TITLE
DM-300 throws self into chasm

### ISSUE THREAD

**Issue by bhilmers** [00-Evan/shattered-pixel-dungeon#594]
Destroyed first pylon in the upper left. Used invisibility to traverse to 2nd pylon in the bottom right. The DM-300 seems to have continued in the direction I was last visible and drove into the chasm before I reached the 2nd pylon. Not sure if bug or viable strategy.

![Screenshot_2021-01-14-01-52-03](https://user-images.githubusercontent.com/77466683/104655014-e77db300-5671-11eb-8ba8-c2174743666b.png)

**Comment by Leajian** [comment]
That should be a hidden achievement.

**Comment by 00-Evan** [comment]
Hmm, there were minor changes to DM-300's logic in 0.9.1c, but nothing that should prompt such dramatic changes to it's movement logic. I'll look into this when patching bugs for v0.9.2

**Comment by 00-Evan** [comment]
fixed in commit c4bf878276e36ca0746cc909c03e8510b2b6abc7
