### ISSUE TITLE
Disappearing releases

### ISSUE THREAD

**Issue by fgaz** [00-Evan/shattered-pixel-dungeon#596]
Hi, I'm the maintainer of the shattered-pixel-dungeon NixOS package, and I noticed that some tags for earlier versions disappeared. This is a problem for distributions because it makes the packages for those versions not reproducible anymore.

It'd be great if all version tags were kept forever, or at least if temporary tags were marked in some way (as pre-release for example)

**Comment by 00-Evan** [comment]
I clean up tags for obsolete patches for the sake of housekeeping, as we'd easily be at 100+ tags by now. The source is still there for people who really want it, but there should be no reason to use a version like 0.9.1b over 0.9.1d.

**Comment by fgaz** [comment]
> I clean up tags for obsolete patches for the sake of housekeeping, as we'd easily be at 100+ tags by now

Tags are cheap though, having 100+ tags is not bad. On the contrary, I'd say it shows that the project is healthy :)

> but there should be no reason to use a version like 0.9.1b over 0.9.1d

The problem is that then when 0.9.1d is released, 0.9.1b suddenly becomes unbuildable. NixOS is fast-moving so this is not a big problem, but it could be for slower distributions, and there's still the issue of reproducibility. Bisects are also hurt by this since spurious build failures get created.

> 00-Evan closed this 8 minutes ago

Is the decision final?

**Comment by 00-Evan** [comment]
I'm willing to discuss this further, but I'd rather not maintain a history of patch releases that users should have no interest in. This just seems like unnecessary clutter to me. I don't really care how expensive tags are in terms of git's code, I care about how messy it becomes when you're trying to find the release you want.

Breaking build processes is a fair point though, I could wait a bit of time before clearing obsolete tags to help reduce the risk of this.

**Comment by fgaz** [comment]
> I could wait a bit of time before clearing obsolete tags to help reduce the risk of this

That would help a bit, but still it'd be nice if we found a way to keep them forever without clutter

> I care about how messy it becomes when you're trying to find the release you want

If it's about the github releases interface, a solution could be to just delete the github release, which is big and flashy, but keep the tag, which is rendered as just a line.

**Comment by fgaz** [comment]
By the way, this is not an insurmountable problem: I can work around it by pointing the package at the commit sha instead of the tag.

It's mostly a matter of consistency with the majority of projects where package maintainers can just use the tag, and of least surprise (I only noticed this after a while).

**Comment by 00-Evan** [comment]
I do already delete releases, my issue is that, last I checked, a tag without a release still leaves an entry in the releases page with seemingly no information. I want the releases page to be simple to understand, as non-technical users use it, so having a bunch of versions with no release info attached is confusing. I see releases/tags as a "simplified view" compared to the commit history, so I would rather remove versions that are meant to be directly replaced by a patch.

I appreciate that other open source projects behave differently, but I would rather de-emphasize bugfix updates compared to them as the vast majority of players don't care about bugfixes and just want to know what the new/changed gameplay features are.

**Comment by fgaz** [comment]
I understand, thank you for the explanation.

I guess I'll just explicitly use the hashes for this package then.

I also noticed that commits messages have the version at the beginning, so at least the version metadata is recoverable.

It'd be good to have all this information in a note in https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/docs/getting-started-desktop.md, so that other downstream maintainers don't trip up on this.

**Comment by SuperSandro2000** [comment]
Tags are far better for downstream package repos because they can never be from a fork. If we track a commit there is a risk that someone sneaks in a commit from a fork.

**Comment by fgaz** [comment]
It was brought to my attention that tags are no longer disappearing. Was there a change in policy? Can we rely on tags now?

**Comment by 00-Evan** [comment]
Yes, tags have been persistent since v1.0.0.
