### ISSUE TITLE
Golem lock on non-pathable targets

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#597]
Golem will lock on and stare the next enemy it could see, after a fight even if it can't pathfind to it. This makes the golem ineffective in some special cases (as presented in the screenshots), because it won't accompany you on the next zap. The golem can be spawned again on a different level, but returning to the level it was "stuck" on, it will be found in the same position with the same health.

The initial incident.
![Screenshot_2021-01-26-17-22-16-64_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/105867604-f2373100-5ffd-11eb-987c-96ca88f5d290.jpg)

Me, fighting with it on the next level (I'm pretty sure it lost some health, but I can't confirm and it's not demonstrated in this screeshot).
![Screenshot_2021-01-26-17-23-15-41_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/105867744-185cd100-5ffe-11eb-9e1f-ea02de0a4336.jpg)

Me, returning to the previous level, finding it there.
![Screenshot_2021-01-26-17-25-14-13_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/105867847-35919f80-5ffe-11eb-838f-0ae14cf7da6b.jpg)

I tried making it re-target, but it focused that mob again, that's why it looks rotated looking at me. This is reproducible.
I am about to make a suggestion described with words, not code, I don't know if it counts as a contribution for licensing reasons. If it does, stop reading here.

Otherwise, I suggest that quest entities should mark the tile under their current position (the current, because some can move, ie sad ghost, fresh elemental) as blocked/invalid.

**Comment by 00-Evan** [comment]
I see how this appears bad in this specific situation, but this is correct behavior.

When a character can see an enemy but can't reach them directly, and an alternative path is very inefficient, they will prefer to approach as much as they can and then wait for their target to become reachable.

The situation you have here can easily be resolved by killing the Gnoll or triggering one of the many traps that are blocking the golem.
