### ISSUE TITLE
Enhancement: Access Guide/Alchemy Book/Item List from the Main Menu

### ISSUE THREAD

**Issue by XTerminatorGR** [00-Evan/shattered-pixel-dungeon#599]
It would be handy to have access to these, without the need to start/load a game each time. A small button on the upper right part of the main menu should do the trick.

**Comment by 00-Evan** [comment]
I've actually previously restructured the main menu to remove links at the corners. The interface looks much cleaner now with just having buttons below the title and I'd like to keep it that way.

I likely will make the journal accessible from the main menu, but only when there's a bit more content to it, probably after I do a lore update.
