### ISSUE TITLE
Boomerang and the quick slot

### ISSUE THREAD

**Issue by prurigro** [00-Evan/shattered-pixel-dungeon#6]
Hey, I love the second quick slot you've implemented! One thing I've noticed however, is that when I use the boomerang via the quickslot while also having it equipped as a weapon (playing as the sniper class), the boomerang becomes transparent the same way it does when it falls to the ground, and tapping that quickslot brings up the bag to assign an item as though it was empty.

Cheers!

**Comment by 00-Evan** [comment]
Thanks for reporting this, there are a few edge cases with the new quickslot functionality that I plan to address with one final patch in a day or two, this will be fixed then.

**Comment by 00-Evan** [comment]
Fixed: https://github.com/00-Evan/shattered-pixel-dungeon/commit/944d2d33a231fab994ddbf59746bbaf12823f88e
