### ISSUE TITLE
Artifacts losing charges after game load, level is preserved

### ISSUE THREAD

**Issue by Tener** [00-Evan/shattered-pixel-dungeon#60]
I've seen this with two artifacts so far: Cloak of Shadows and Hourglass. After the game is loaded the artifacts appear to be upgraded (show proper +Level), but the number of charges is consitent with base level artifact.

I've read the code for serializing/deserializing charges and it looks fine. Perhaps this is somehow specific to my device.

**Comment by 00-Evan** [comment]
Interesting. What's your device then? Can you give any more details regarding when this happens, or does it happen all the time?

**Comment by 00-Evan** [comment]
Hey Tener,

After testing, I cannot reproduce this issue, and cannot find any evidence of others experiencing it.

Could you please provide more information about how/when you're getting this issue?

If there is no further comment then I will close this ticket.

**Comment by Sarius997** [comment]
Hey Tener, 

are you sure this happened in shattered pixel dungeon?

I recogniced this only in unleashed pixel dungeon.

**Comment by Tener** [comment]
@Sarius997 you are right, got confused somehow... this should be raised against Unleashed PD mod.
@00-Evan sorry for invalid bug report...
