### ISSUE TITLE
Feature request: Allow seeing item name/description when choosing alchemy ingredients

### ISSUE THREAD

**Issue by jessewdouglas** [00-Evan/shattered-pixel-dungeon#602]
When choosing ingredients to put in an alchemy pot, it'd be helpful to see the name/description of the item and a prompt to confirm using it. For example, I don't have all the seed types memorized by color yet, so I have to back out of the alchemy screen and look at the seeds in my inventory to figure out which one(s) I might want to use as an ingredient. It'd be a lot simpler to have this information available within the alchemy screen.

**Comment by 00-Evan** [comment]
This is already implemented, long-press the item in the inventory view to see a description.
