### ISSUE TITLE
corrupted monster dies when dwarf king returns to throne

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#603]
Corrupted ghoul during first dwarf king phase.  Hit dwarf king.  Dwarf king returned to throne and corrupted ghoul died.  This may have been a coincidence due to corruption health leak, but seemed suspicious.  Does dwarf king returning to throne kill all monsters, even corrupted ones?  Shouldn't corrupted monsters survive?

**Comment by 00-Evan** [comment]
It is intended that DK's minions all die (including corrupted ones) when he changes phase. This is mainly to prevent either of you from building up a  big stack of minions that would be used to steamroll later rounds with.
