### ISSUE TITLE
Corpse dust stops spawning after unblessed ankh revival.

### ISSUE THREAD

**Issue by scottcale** [00-Evan/shattered-pixel-dungeon#604]
Playing necromancer mage/warlock and died with unblessed ankh.
When I continued, I still had the corpse dust, but no more wraiths spawned.

Version 0.9.1d on Android Pixel
On level 12 or 13. Warlock level 15. Level 6 staff imbued with corruption. Staff is otherwise plain.
Etherial chains and Chalice equipped. No ring. Chain mail of potential

I was standing in an alchemy room next to the door. I pricked the chalice up to +5. The door opened and I was poisoned by a cave spider then hit once or twice more. I don't know if I died from the poison or the hits.
Continued using the unblessed ankh. 
I noticed I had two more upgrade scrolls which I used to bring the staff to +8. Descended two or three more floors before I noticed I wasn't seeing any wraiths.
Decided to just see how far I could still get... and died permanently shortly after that.

**Comment by 00-Evan** [comment]
Reviving from an unblessed ankh clears all curse effects on the player, so it's correct functionality that it clears the corpse dust effect.

I'm likely going to redesign unblessed ankhs at some point in the future though, as the effect is too drastic (losing most of your gear) for most people to want to use.

**Comment by scottcale** [comment]
Oh. I didn't think of that. Thought it was a bug.

In that case. I suggest removing the curse from the dust. If wraiths don't
spawn, is there a reason to keep it undroppable? Then the player can choose
to drop it, or go back to wandmaker.

Appreciate your earlier reply. Don't expect another one here. Just hope
you'll consider.

Thanks for what you have already done to make the game more fun.
