### ISSUE TITLE
Minor : small error in grapics when you have vertigo, poisoned and you try to move

### ISSUE THREAD

**Issue by lele92007** [00-Evan/shattered-pixel-dungeon#607]
![Capture d’écran de 2021-02-06 16-26-39](https://user-images.githubusercontent.com/77411734/107122457-2fba7a80-6898-11eb-8e61-ae60eeb41ddc.png)
I've tried to move, but, i moved in a wall due to vertigo effect.
I think it woks with all forms of damage (just need vertigo)

PS : dsl I'm french ^_^

**Comment by 00-Evan** [comment]
Got this fixed indev, thanks!

**Comment by 00-Evan** [comment]
fixed in commit 041046cc74662f9ff44c162765dc3e8cef0c92cd
