### ISSUE TITLE
Scroll of upgrade and sad ghost trapped in secret room

### ISSUE THREAD

**Issue by zulvkr** [00-Evan/shattered-pixel-dungeon#608]
Is this abnormal behavior? I only found the secret room by chance after circling the whole 2-4 floor twice

v.0.9.1d

**Comment by 00-Evan** [comment]
As of v0.9.1 there is a type of level which can generate many secret doors, even potentially blocking important items/characters. You're warned about this when descending by the message: "The atmosphere hints that this floor hides many secrets."

You can search by double-tapping the examine button, you don't need to just keep walking by a place you suspect has a hidden door in it.
