### ISSUE TITLE
Wand of Magic Missile +2 not empowering other wands

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#611]
I currently have a Wand of Magic Missile +2, which despite its description does not activate the "empower" effect when zapped.

This is in version 0.9.1d.

The game is still active; happy to provide additional information that would help debug this.

**Comment by 00-Evan** [comment]
Did you have other wands that were below +2 in your inventory? The empower effect only appears if there are wands that can benefit from it.

**Comment by joshtriplett** [comment]
Yes. They were even in my quickslots.

The game has since closed and reopened, and I now can't seem to reproduce it with the same wand, so closing.
