### ISSUE TITLE
Thief is stuck when shouldn't

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#612]
![Screenshot_2](https://user-images.githubusercontent.com/1816060/107899521-2b045f00-6f47-11eb-87c3-c26c67dce002.png)
(When I'm referring to thief, I mean the damaged one.)

Thief's "stuck flag" is falsely set to true when exchanging positions with his allies. On the left screenshot, the thief stole from me and immediately changed positions with necromancer. During that moment, the thief said the characteristic "#!%$" above his head, thinking he is stuck.

On the right screenshot, you can clearly see the thief that just stole from me doesn't flee in the next round.

I'm pointing out again, this happened when necromancer wanted to change positions with thief, while the thief was fleeing, because he just stole something.

**Comment by 00-Evan** [comment]
Hmm, I'll look into that. The thief definitely shouldn't care if the hero's path to it is blocked.

**Comment by 00-Evan** [comment]
fixed in commit 44b80b24a915de9b308e0f58cbdd9a8d6f4e03d8
