### ISSUE TITLE
Impossible targeting with spear

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#613]
![unnamed](https://user-images.githubusercontent.com/1816060/107899841-242a1c00-6f48-11eb-840f-7ed96bbcde64.jpg)

Spear can target necromancer, because it was hit before it spawned a skeleton while remaining in spear's range. I don't believe that is intentional, because I cannot hit the necromancer through a skeleton.

**Comment by 00-Evan** [comment]
This is intended. Reach weapons are allowed to 'curve' a bit, so in this case because the necromancer is open on the right you're able to hit them.
