### ISSUE TITLE
Some problematic interactions

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#614]
- Mage can utilize a cursed wands' charges to obtain shields with no precautions. He is the only hero that has an unfair advantage over the others interacting with cursed wands.
- Thieves as Projecting Champions can pickpocket you on (projecting) hit. Little counterplay for that, I would comment it as overpowered. The same occurs with any type of champion that gives the thief projecting ability. **The screenshot below**, demonstrates a scenario that would only be fair if I happened to have stone of blink.

![unnamed (1)](https://user-images.githubusercontent.com/1816060/107900299-4b351d80-6f49-11eb-83ec-dfb18817b65c.jpg)

**Comment by 00-Evan** [comment]
Those are both intended. I decided to allow shield battery to work on cursed wands, as I felt this added some interesting utility to the talent.

As for projecting thieves, that is nasty, but powerful combos are one of the points of the challenge.
