### ISSUE TITLE
Visual Charm

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#617]
![Screenshot_20210216-031659](https://user-images.githubusercontent.com/79112244/107988674-7d0eb880-700b-11eb-94c8-a335ee485d9d.png)
V0.9.2 friendly battle axe +1 is equiped. Triggeres charm and status says 10 turns but sometimes ends in 5 turns whether hit, not hit by enemy, hit other enemy.

**Comment by 00-Evan** [comment]
From the buff's description: "The shock of pain will lessen the duration of charm." If you get attacked while charmed its duration is reduced by 5 turns.
