### ISSUE TITLE
Leftover bones

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#618]
![Screenshot_20210216-033612](https://user-images.githubusercontent.com/79112244/107988975-2786db80-700c-11eb-9b9a-f9f2eaf07a31.png)
Necromancer sees me, begins to summon. I moved through doors skeleton follows but left some of his bones. Exit and enter game fixed it. V0.9.2 beta

**Comment by 00-Evan** [comment]
This should now be fixed in beta-2
