### ISSUE TITLE
BETA Another Bug & Game Crashed

### ISSUE THREAD

**Issue by cgnj512** [00-Evan/shattered-pixel-dungeon#619]
Version: 0.9.2beta
Platform: Windows10,liberica JDK

- Another bug
A player has reached lv.12, used up all talent points in the first two talent levels ,and hasn't killed Tengu and gotten the book. When going down the stairs, he receives the message "You have unspent talent points!". The lvl3 points cannot be used at that time.
- Game Crashed
I was trying to drop a wand and it crashed:(
![crashed](https://user-images.githubusercontent.com/57553913/108004202-1f409780-7030-11eb-9fab-f39976956677.PNG)

https://user-images.githubusercontent.com/57553913/108004234-37b0b200-7030-11eb-9c15-09e08a96e82c.mp4

**Comment by 00-Evan** [comment]
This bug was fixed in the proper beta release, please update.
