### ISSUE TITLE
Freerunner cant build momentum.

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#620]
![Screenshot_20210216-130128](https://user-images.githubusercontent.com/79112244/108020539-8cb3ee80-7057-11eb-9f48-101ba39b2f13.png)
Is momentum mechanic changed? I cant build momentum while moving. And can only do it with cloak with speedy stealth talent or hourglass 'freeze time around me'. I only need 1 turn with the artifact to build momentum then i can disable the artifact and can now proceed to build momentum to full cap'10'. I think im too 1 turn slow to build momentum? Cause sometimes while moving tiles I get this ending animation of momentum running out and can never build one.

**Comment by Lonestick** [comment]
![Screenshot_20210216-131656](https://user-images.githubusercontent.com/79112244/108021538-b79f4200-7059-11eb-8cac-d3691b31f31d.png)
Im in negatives now. This seems to occur when recovering momentum then i opened and moved to woodlocked room or when moving to next floor. Moving with negative triggers freerunning button, freezes when pressed. Moving continuesly with negative momentum eventually turns it to positive momentum. If i stop and wait till my momentum runout, still cant build momentum without cloak or hourglass. Im starting to think my base momentum is in negatives thats why i cant build any and hourglass freezes it and cloak talent gives +2 base momentum already.

**Comment by 00-Evan** [comment]
This is fixed in beta-2, please update.

**Comment by Lonestick** [comment]
> This is fixed in beta-2, please update.

Oh! Thanks, can i know where to get the update? My only source is playstore but it doesnt have an update still.

**Comment by 00-Evan** [comment]
> 
> 
> > This is fixed in beta-2, please update.
> 
> Oh! Thanks, can i know where to get the update? My only source is playstore but it doesnt have an update still.

BETA-2 should be out on the play store as of late last night.
