### ISSUE TITLE
Beta: freerunner stamina management.

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#621]
![Screenshot_20210216-134553](https://user-images.githubusercontent.com/79112244/108023689-0e0e7f80-705e-11eb-88b4-6c2025374dc7.png)
It should take less time recovering if you only use 1 turn of momentum(2 turns freerunning) like in the picture. It would make sense that you spend less time to recover with short burst of speed and longer time after marathons.

**Comment by 00-Evan** [comment]
This is an intended mechanic to make freerunning at low momentum not worthwhile. The cooldown is 50 turns regardless of how much momentum you build, minus the time you spend freerunning.
