### ISSUE TITLE
Beta: Shielding Dew, how does it work?

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#623]
![Screenshot_20210217-000226](https://user-images.githubusercontent.com/79112244/108088646-abe06980-70b3-11eb-9f17-d5041400871a.png)
Tried picking up with and without dew vial, alsk tried drinking from dew vial but no shield appears.

**Comment by 00-Evan** [comment]
The talent grants you shielding if your health is already full. A few people have been confused by this, so I'll likely tweak the description.

**Comment by 00-Evan** [comment]
This description has been adjusted as of beta-3
