### ISSUE TITLE
#Beta# Light Cloak recharge.

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#624]
Will it be affected  by scroll of recharging, ring of energy, mystical meal, etc. While on inventory? 30% recharging is too little for assasins so I guess it should be freerunners talent. It will be doable though if it can be affected by recharging items, that way it wouldnt be too slow.

Ps. I dunno where to write question like this. I wanna put it on reddit but its in beta so..

**Comment by 00-Evan** [comment]
This is not a place to ask questions about the game. It is to report technical issues or make improvement suggestions. For Reddit, you can simply reply to the latest Shattered announcement thread, or just pm me.
