### ISSUE TITLE
#BETA2# Battlemage's Mystery Charge too strong

### ISSUE THREAD

**Issue by cgnj512** [00-Evan/shattered-pixel-dungeon#625]
Nice to see that some bugs are fixed in BETA-2.
A battlemage successfully got the Amulet of Yendor. The gameplay was much easier after he found the Horn of Plenty. That's because the Tier-3 talents contain "Mystery Charge" and it can always charge the horn when the battlemage hit somebody with his wand. Food is really no longer needed and the horn recharges in very short time. This feature is too strong.

Additionally, the talent point message bug is still not fixed yet. The player can't upgrade his lv3 talent but the system gives message that the points are not used. Hope this will be fixed in next version.

**Comment by 00-Evan** [comment]
This is not the place to complain about game balance, please use this place for reporting technical issues with the game, or suggesting technical enhancements.
