### ISSUE TITLE
0.9.2 BETA-2 Lost my combo after reviving from blessed ankh

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#626]
I was fighting a guardian after stepping on an alarm trap. My combo was at 9 and my health was low but I wanted to use Fury so I attacked expecting to reach the 10th combo and survive. The combo did went up to 10 but I died. The blessed ankh revived me and my combo was at 10 still but when I picked one combo from the list nothing happened and the combo was lost.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Getting revived by a blessed ankh correctly allows use of combo moves for me. Did you select the parry move? Recall that parry only preserves combo if you parry something, and reviving from a blessed ankh give you extra time to act. This would mean parrying right after being revived would result in nothing to parry.

**Comment by ShinKeyKai** [comment]
That's probably what happened then, cause I remember not choosing Fury because I miss clicked
