### ISSUE TITLE
"Descending..." indefinitely from level 6 to 7

### ISSUE THREAD

**Issue by apricot-azumi** [00-Evan/shattered-pixel-dungeon#627]
The game gets stuck in level transitioning screen (Desending...) when trying climbing down the ladder from level 6.

Version: 0.9.1d (512)
Seed: 4212280542745
Challenge Mask: 0

Installed from Google Play.

Level 9 Rogue
Talents:
1, 1, 1, 2
0, 0, 0, 2, 0 (1 unspent)

**Comment by 00-Evan** [comment]
should be fixed in commit 75e8ba7fd994a3c42cd52468cdf6fedb43f730cc
