### ISSUE TITLE
0.9.2 BETA-2 Shared enchantment not working correctly

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#628]
The tier-3 talent 'Shared enchantment' for the Sniper shares the enchantment from the bow to a thrown weapon in a determined percentage according to the talent level. At level +3 is supposed to be a 100% chance but is not like that. It occurs but not at a 100% chance.

**Comment by 00-Evan** [comment]
Regular enchantments do not always activate. The "100%" in the talent does not mean that an enchantment like blazing will activate every time, but rather than the weapon has a 100% chance to act as if it has the enchantment.
