### ISSUE TITLE
Rogue blinks through obstacles.

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#629]
![Screenshot_20210219-161029](https://user-images.githubusercontent.com/79112244/108476669-48318880-72cd-11eb-8f51-c2ef5c99e1d6.png)
Beta//
Rogue was able to assasinate bat through blacksmith and traps.

**Comment by 00-Evan** [comment]
That's working as intended. The blink is supposed to be able to go over hazards.
