### ISSUE TITLE
Pitfall Traps on Floors Before Bosses

### ISSUE THREAD

**Issue by SamuelS42** [00-Evan/shattered-pixel-dungeon#63]
Pitfall traps appear on floor numbers ending with 4 or 9.
Activating these crashes the game.

**Comment by 00-Evan** [comment]
pitfall traps appearing before boss floors is intended, crashing is not.

Are you running on version 0.3.1c, or an earlier version? This was an issue in 0.3.1 and was fixed in 0.3.1a

**Comment by SamuelS42** [comment]
When it happened I was running 0.3.1a  from fdroid.

**Comment by SamuelS42** [comment]
I did not directly step on the trap.
I threw a item onto it.
