### ISSUE TITLE
No music on Xiaomi MI5

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#630]
Music doesn't play and game might get stuck for a short time unless music is disabled. This happens only on the mobile version of the game. The PC Java version plays music normally.

Model Xiaomi MI5 on LineageOS 17 (both with Google Play Services and Microg). Music and sound normal in other apps.

**Comment by 00-Evan** [comment]
This is a known issue with LineageOS, for some reason it does not like playing .ogg files. See the last few comments in #340
