### ISSUE TITLE
Huntress splash art

### ISSUE THREAD

**Issue by cum-squirter-nerd-hurter** [00-Evan/shattered-pixel-dungeon#631]
All the artwork for the classes is quite lovely, but I've wanted to edit the huntress' face for a while.

Before:
![before](https://user-images.githubusercontent.com/75985077/108610429-2116ac00-73de-11eb-8086-daf6f4604ab8.jpg)

After:
![after](https://user-images.githubusercontent.com/75985077/108610436-2d026e00-73de-11eb-9e96-3851969fb4e3.png)

Now it should look less like Tim Robbins.

**Comment by 00-Evan** [comment]
From the readme: "Note that this repository does not accept pull requests! The code here is provided in hopes that others may find it useful for their own projects, not to allow community contribution. Issue reports of all kinds (bug reports, feature requests, etc.) are welcome."

**Comment by cum-squirter-nerd-hurter** [comment]
>@00-Evan: From the readme: "Note that this repository does not accept pull requests! The code here is provided in hopes that others may find it useful for their own projects, not to allow community contribution. Issue reports of all kinds (bug reports, feature requests, etc.) are welcome."

I don't know if this is a "pull request", but okay. So will you look over the edit and consider it?

**Comment by cum-squirter-nerd-hurter** [comment]
@00-Evan pls ;_;

![Untitled](https://user-images.githubusercontent.com/75985077/108632855-ae5b0e80-7479-11eb-85a4-8fcbf691eeba.png)

**Comment by 00-Evan** [comment]
Sorry but as I mentioned I don't accept contributions.

**Comment by cum-squirter-nerd-hurter** [comment]
> Sorry but as I mentioned I don't accept contributions.

Okay :(

If it's a copyright thing, you could probably always edit it yourself in order to remedy the Cushingoid facies.

Are you also the author of the artworks, or is it another contributor? They're quite good - very atmospheric.
