### ISSUE TITLE
Teleportation Trap Erases Map Sight

### ISSUE THREAD

**Issue by zapcircuit** [00-Evan/shattered-pixel-dungeon#632]
I walked over a teleportation trap in level 13, and all the previous areas I've been to are now all dark (which signifies that you haven't been there before). Is this supposed to be a part of the trap's function?
![d3fd850399b932d787d107ffd301e64](https://user-images.githubusercontent.com/79499005/108806530-e0d14c80-75dc-11eb-8587-d8974d98157d.png)

**Comment by 00-Evan** [comment]
That was a warping trap. Those traps reset your knowledge of the level as well as teleporting you.
