### ISSUE TITLE
Delicious food language problems

### ISSUE THREAD

**Issue by zapcircuit** [00-Evan/shattered-pixel-dungeon#633]
This is an issue with the "That food tasted delicious" message. In this example, I changed the language from English to Chinese then back to English. And this and only this one message comes out wrong.

Screenshot:

![91c9a27e2f849fbd233fca4bf1f605a](https://user-images.githubusercontent.com/79499005/108822110-94483a00-75f9-11eb-9b3e-33af778c94d6.png)

**Comment by 00-Evan** [comment]
This can occasionally happen in the game log when languages are being quickly switched between, it doesn't have anything to do with the particular message. I'm fine with leaving it as-is given that the only way to reproduce it is quickly switching between languages.
