### ISSUE TITLE
Horn of Plenty does not replenish on prior floors

### ISSUE THREAD

**Issue by jjech** [00-Evan/shattered-pixel-dungeon#634]
The Horn of Plenty does not replenish with experience when visiting floors that have been previously visited. It only replenishes at the lowest visited depth.

To reproduce: obtain the Horn of Plenty, kill monsters, see it replenish. Now ascend one level and repeat — it will never gain more food except on the lowest visited depth.

**Comment by 00-Evan** [comment]
There is no logic in the horn of plenty which checks with depth you are on, it only cares about incoming experience. Are you sure that you are getting exp from the enemies that you're killing? Enemies stop granting exp after you reach a certain level.

**Comment by jjech** [comment]
> Are you sure that you are getting exp from the enemies that you're killing? Enemies stop granting exp after you reach a certain level.

Ah, that must have been it. Thanks.
