### ISSUE TITLE
had an issue with the latest tier 3 beta update where the reconfigured freerunner class sometimes gains and loses momentum at the same turn

### ISSUE THREAD

**Issue by h3ck713** [00-Evan/shattered-pixel-dungeon#635]
but it was able to semi remedy the problem by using the speedy stealth maxed out ps it was a old run from a previous update so it don't know if the old save had a update and problems insued :/

**Comment by h3ck713** [comment]
Also I am new to github and Is just found a bug(?) And I try to find a way to let you know

**Comment by 00-Evan** [comment]
Which beta version are you using? This was a known bug on beta-1 which should already be fixed. If you're using a later beta version, do you have any equipment that might affect your running speed?

**Comment by h3ck713** [comment]
No I didn’t even have a ring of haste or a speedy enchantment on my armor
so I don’t know and the beta version is v0.9.2-BETA

**Comment by h3ck713** [comment]
Also it may be because the run I was on was a old save before the update
and I updated it and played it which maybe a result of the bug as you said
for the older version of beta-1

**Comment by h3ck713** [comment]
Or it is the result of the loss of the boost gained from the speedy stealth
when you get out of stealth mode where it doesn’t revert to the original
gain of momentum but idk I’m just a gamer that enjoys what you make

**Comment by 00-Evan** [comment]
The bug was present on v09.2-BETA and was fixed in BETA-2. Update to the latest version and the freerunner should work normally.

**Comment by h3ck713** [comment]
Okay thank you
