### ISSUE TITLE
Attack button irresponsive

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#636]
There are rare cases when I'm playing on mobile, but they occur way too often to me, where when attacking an enemy with the attack button, after a while it stops working. Yesterday, I introduced a friend to this game and I coached him live playing on pc. The bug occurred to him as well and he was astonished. I explained to him that it was a bug that happened only to me, but apparently not. I cannot reproduce it. It seems really random, I cannot provide something insightful, anything I might say will be biased. This bug exists a long time and I thought I was paranoid. But I will say that there might be a correlation with faster than you enemies or you being faster than them. Not quite sure...

**Comment by 00-Evan** [comment]
This has been reported sporadically to me for a while with no consistent steps for reproduction. Some people get it frequently, some rarely, but it always seems to come and go. I think it's most likely a race condition but after several attempted fixes it still persists. Do you have any information about game state or your user input around the time that the issue tends to occur?

**Comment by 00-Evan** [comment]
Closing this issue as, once again, there is no way to reproduce it. Please continue letting me know if you run into this bug, but currently there is no way for me to address it.

**Comment by Leajian** [comment]
I came across it once again, but there is no sane way to reproduce it. I conclude that it might be a race condition too. I will reopen it if I discover the reason or any concrete evidence.
