### ISSUE TITLE
Levels with no keys to locked doors

### ISSUE THREAD

**Issue by jjech** [00-Evan/shattered-pixel-dungeon#637]
Occasionally, I seem to run across levels that have a locked door with no key. In these situations (which are quite rare) I've painstakingly scoured the level searching for a hidden room, to the point of dying of starvation after multiple iterations across all walls.

I've never had a scroll of magic mapping when this occurs, though I did once have a scroll of teleport and it did not take me to a new/unexplored area. 

Is it possible for keys to be hidden within secret rooms? Did I just get really unlucky in my search, or could there be a bug where locked doors can be generated without a matching key?

**Comment by jjech** [comment]
Most rooms with a locked entrance use level.addItemToSpawn to add the IronKey to the level. However, PitRoom.java takes a different approach. If I'm reading the code correctly I think the key for PitRooms drops from a skeleton. Could it happen that the skeleton did not spawn? Or that the skeleton with the key randomly spawned *inside* of the locked room?

**Comment by 00-Evan** [comment]
You are correct that the key spawns inside of these rooms. To access them, you have to find an alternate way of entry. Try looking for something suspicous on the floor above.

**Comment by jjech** [comment]
Ah, thanks. Always wondered what was the point of those rooms ;)
