### ISSUE TITLE
Shock trap that can't be triggered

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#638]
I came across a shock trap, and tried to use it against an enemy by zapping my staff of corrosion on it, but it didn't trigger. Later, after I was done with that enemy, I tried throwing an item on top of it, and that didn't trigger it either. Looking more closely at it, it also looks like it was generated in the same space as a rocky floor; not sure if that's relevant. Screenshots:
![Screenshot_20210227-104759](https://user-images.githubusercontent.com/162737/109397162-3a41c000-78ea-11eb-9216-dd0797232f16.png)
![Screenshot_20210227-104815](https://user-images.githubusercontent.com/162737/109397164-3ca41a00-78ea-11eb-9c5a-26c334085fc0.png)

**Comment by 00-Evan** [comment]
Hmm, This has been reported once or twice for 0.9.1 and I thought I fixed it in a patch. If you've still got the run, can you show me the seed for it?

You can access the run seed by going to games in progress, selecting that run, and the long-pressing on the hero's sprite in the top-left of the window.

**Comment by joshtriplett** [comment]
Sure. Haven't done anything in that game since the screenshot above.

Seed: 2016725253596

**Comment by 00-Evan** [comment]
Alright I'm able to reproduce the bug with that seed, will get it fixed next patch.

**Comment by 00-Evan** [comment]
fixed in commit dded52030aafe9ae2aee115bf0378132a7cc0de9
