### ISSUE TITLE
[Quirk] Subclass-independent Talents are not unlocked

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#639]
![Screenshot_2021-03-03-02-30-28-807_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/109738739-a3feea00-7bc8-11eb-9c00-50daa0d07232.jpg)

I reached level 13 as a mage but Empowering Scrolls and Ally Warp were not unlocked although they are subclass-independent. I don't know if this is intended, but the first two Tier 3 talents could be made available even if you have not read the Tome.

**Comment by 00-Evan** [comment]
This is intended. As the talent window says, T3 talents are unlocked after level 12 and when the hero has picked a subclass. I didn't want to make some of the T3 talents more accessible than others.
