### ISSUE TITLE
Option to disable/dim screen flash when getting blinded

### ISSUE THREAD

**Issue by XiangRongLin** [00-Evan/shattered-pixel-dungeon#642]
When my character is getting blinded the screen flashes completly white, which in turn also flashes me as the player.

It makes sense mechanic wise, but it is hurting my eyes whenever it occurs.

I would like to have an option to either disable or dim the flash.

**Comment by 00-Evan** [comment]
probably the easiest solution is to turn down your screen brightness, but I'll look into whether the effect can be softened a bit, especially as it might be helpful to photosensitive users. I don't intend to put a toggle in the options menu specifically to disable flashing effects though.

**Comment by 00-Evan** [comment]
I've turned down the intensity of the effect by 50% for v0.9.2b, Previously the effect was pure white at it's most intense. The most intense moment now looks like this: 
![image](https://user-images.githubusercontent.com/2347603/111380494-ce49b080-867a-11eb-9741-4be498e4be00.png)

The duration is still unchanged, so the effect looks similar overall, other effects (such as the red flash) are unchanged.

**Comment by 00-Evan** [comment]
effects were adjusted in commit b2fefa256fe3218ad16a572258fceda683917bb1
