### ISSUE TITLE
Sniper special ability locating and hitting out of vision enemies

### ISSUE THREAD

**Issue by XiangRongLin** [00-Evan/shattered-pixel-dungeon#643]
This occured while fighting Yog's fist that can blind me. 
I threw a dart at it.
It blinded me and teleported away. I don't have vision of him anymore.
I pressed the special attack button and the arrows locate him and hit him.

This also occured numerous times during the run, because i have an elastic bow. But there i thought it was just a feature, since the position, although out of vision, is still known. Because elastic just pushes them backwards in a straight line.

In this case this should not be possible, the fists position is completly random here

**Comment by 00-Evan** [comment]
This is an interesting edge-case, but I'm fine with allowing it. In most cases there will not be a projectile line to the fist and so using the sniper special won't work.
