### ISSUE TITLE
Vertigo not working in tunnels?

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#644]
So I threw a seed of stormvine in front of this fetid rat with the intention of making it fall in the shock trap but the rat stood still until the vertigo effect ended. Like for 3 or 4 turns. Maybe this happened because the rat has no escape? I was blocking one side of the tunnel and a gnoll was blocking the other side. As you can see in the first pic, the door at the gnoll side is opened, meaning the gnoll was there so technically the rat has some space to move.
![Screenshot_20210310-003456](https://user-images.githubusercontent.com/47122537/110668499-23348500-81aa-11eb-86c9-93722544fbe5.png)

Here the gnoll gets closer when I was fighting the rat
![Screenshot_20210310-003515](https://user-images.githubusercontent.com/47122537/110668527-2af42980-81aa-11eb-91bf-eb33d9c2f628.png)

**Comment by 00-Evan** [comment]
Vertigo picks a random direction to move in, and if that direction is in a wall the character simply won't move that turn. So in this case the rat was vertigoed, it was just bumping into walls or the gnoll instead of into the trap.
