### ISSUE TITLE
Necromancer's summoned skeletons can be fooled by obfuscation when the necromancer isn't

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#645]
I was standing in a room next to a necromancer that was not aware of me. I hit it, and it was suddenly aware. It immediately started summoning. When it was done summoning a skeleton, that skeleton proceeded to walk out of the room, ignoring me. As soon as the door closed behind the skeleton, the necromancer began summoning another.

I realize that in general monsters aren't aware of what other monsters know (outside of the challenge mode where they do), and that's not what I'm asking for here. I'm wondering if summoned skeletons by a necromancer that's aware of the player could themselves be made aware of the player immediately upon summoning.

**Comment by 00-Evan** [comment]
Necromancers don't summon a new skeleton if their current skeleton leaves, they teleport their existing skeleton next to the hero. This is meant to handle cases where the skeleton misses the hero but the necromancer doesn't, rather than tying their AI together.
