### ISSUE TITLE
Items thrown down pit leading to locked room can end up outside that room

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#646]
In one of the dedicated pit rooms that leads to a locked room on the next floor, jumping down the pit will *always* put you in the locked room, but throwing an item down can put it elsewhere on the floor. This can be an unpleasant surprise if you threw an item down expecting to have access to it before leaving that locked room.

**Comment by 00-Evan** [comment]
This isn't really possible with the current implementation of how things fall into pits. The location that an item lands in isn't determined until you descent to that level (important, as the level may not have been generated yet), and there is currently no method to track which specific location an item fell from. In general I don't want to add more features to throwing items into chasms as well, I'd prefer to continue improving inventory management so players aren't compelled to chuck items into pits in the first place.
