### ISSUE TITLE
Excess Charge not triggering when staff is overcharged

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#647]
Version: 0.9.2

**Comment by 00-Evan** [comment]
This is a known bug that's already been fixed in v0.9.2a.

I have edited your issue. Please do not include code suggests, I do not accept pull requests in any form.

**Comment by 00-Evan** [comment]
Fixed in commit 84fe9b5d93015f99148de792adc3119a2be0241c
