### ISSUE TITLE
Falling down the pit to locked room sometimes crashes game and resets level

### ISSUE THREAD

**Issue by HeDidNothingWrong** [00-Evan/shattered-pixel-dungeon#649]
Version v0.9.2, Android 11 on Poco F2

Second time this happened, if first time wasn't same version then it's also recent one.

How to replicate:
1) Jump into pit to locked room in next lvl (example, lvl 16 -> 17)
2) ???
3) Game freezes prior to loading next lvl
4) Force kill game
5) Load game
6) The game starts from same level (example, lvl 16) as if you just started it and had no progression

Succees rate:  infrequent and unknown, just happened 2 times to me in last month or so. Also happened on early levels, so I don't think depth has anything to do with it

**Comment by 00-Evan** [comment]
I've had one or two reports of this with no way to reproduce it. Some people claim the game crashes, others say it freezes. Can you give me any more details about what exactly you're seeing? What exactly do you see when the game has frozen?

**Comment by HeDidNothingWrong** [comment]
Last time it was frozen prior to falling down to next level (char and all on screen, before loading screen), whether the character was in air or last tile before it, I don't remember. Also don't remember whether the falling scream sound was played.

It was however frozen in that state, whatever I clicked nothing happened. Killed the process, loaded the game and it started that level again (items, inventory, discovery etc. were all as if I first started it).

If it happenes again I'll take a SS and post here, but this might take a while as it's somewhat infrequent.

**Comment by Leajian** [comment]
Could be related to https://github.com/00-Evan/shattered-pixel-dungeon/issues/567 and https://github.com/00-Evan/shattered-pixel-dungeon/issues/627 with regards to level gen, as https://github.com/00-Evan/shattered-pixel-dungeon/commit/75e8ba7fd994a3c42cd52468cdf6fedb43f730cc looked like a "dirty hack" and not a fix. That means there is a slight probability for a crash to occur to anyone if the game happens to fail level gen for some reason. Maybe something related to PatchRoom class?

**Comment by 00-Evan** [comment]
> Could be related to #567 and #627 with regards to level gen, as [75e8ba7](https://github.com/00-Evan/shattered-pixel-dungeon/commit/75e8ba7fd994a3c42cd52468cdf6fedb43f730cc) looked like a "dirty hack" and not a fix. That means there is a slight probability for a crash to occur to anyone if the game happens to fail level gen for some reason. Maybe something related to PatchRoom class?

These two issues are totally unrelated. The game's code is capable of self-reporting levelgen hangs to me, and they don't produce the 'freezing' behavior that people mention here. I appreciate it's not the most elegant thing ever but 75e8ba7fd994a3c42cd52468cdf6fedb43f730cc was also not a "dirty hack". It added logic for the game to be able to recognize when a result couldn't be found in two cases, and handle them as an error case, rather than looping indefinitely. Similar logic is used all over the game's code for these sorts of operations.

**Comment by 00-Evan** [comment]
I'm going to try and address this in v0.9.2b, though unfortunately I can't make any guarantees as I'll have to reproduce it first. Knowing roughly when the freeze kicks in visually gives me at least something to go on though.

**Comment by ShinKeyKai** [comment]
This also happened to me a couple times being the most recent minutes ago. For me the game always freezes after choosing the option to jump. The option highlights like if the button is pressed and the game freezes. The level I was jumping to was already generated cause I visited that floor before, so I don't think it is related to the level generation.

This is how it looks for me when it freezes (it didn't happened here, I just take the screenshot while holding the button)
![Screenshot_20210318-151141](https://user-images.githubusercontent.com/47122537/111676039-8357a680-87fc-11eb-9353-b74adc180f40.png)

**Comment by 00-Evan** [comment]
@ShinKeyKai did you hear the hero falling sound effect?

**Comment by ShinKeyKai** [comment]
> @ShinKeyKai did you hear the hero falling sound effect?

I always play muted but I just tested after reading your reply and went to the same spot that my last screenshot and it froze again. And yes, the hero did the falling sound effect.
Also, this seems to happen when I tap the pit from far away and choose to jump. But I'm not sure.
I haven't finished this game so if you need the debug info I can provide it.

**Comment by 00-Evan** [comment]
Great news! The bug is a thread deadlock and I've been able to reproduce it by manually inserting some delays into the game logic. I'll definitely have this fixed in v0.9.2b.

**Comment by 00-Evan** [comment]
Fixed indev, I'll likely be rolling out v0.9.2b to beta users on Google Play tomorrow. Given that threading changes have a high potential for bugs that I can't catch locally, please do test v0.9.2b to make sure it works for you when it's released.

**Comment by 00-Evan** [comment]
(hopefully) fixed in commit 3e7a48d59b40f9632c5be4661d2e41c99c863469
