### ISSUE TITLE
Map generation created room missing wall

### ISSUE THREAD

**Issue by XiangRongLin** [00-Evan/shattered-pixel-dungeon#650]
I think there is a wall missing here. This is on floor 2, going south.
![image](https://user-images.githubusercontent.com/41164160/111034885-ee2d6a00-8417-11eb-810f-976d8ab5efd4.png)
![image](https://user-images.githubusercontent.com/41164160/111034897-fdacb300-8417-11eb-8bf4-2ee5da973cd1.png)

**Comment by 00-Evan** [comment]
That's intended. Since v0.9.1 rooms can often be merged together.
