### ISSUE TITLE
Not interrupted by out-of-FOV attacking enemies

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#651]
If the dungeon is dark and hostile champions are activated, projecting ones will hit you even if you can't see them. I'm ok with them staying still out of my sight, that is the challenge. The problem comes on the first encounter. I present a case where movement frustrates the player.

I had little HP and I moved into the dark. A projecting bat started hitting me, out of my sight and the game did not interrupt me, my hero kept moving and I literally had no reaction time left to stop that non-sense. For some reason the game acknowledged that this was my intention. As far as I am concerned, the source code does not trigger any interruption while taking damage that way. The code took into account cases where the damage came from specific sources. But, prior to hostile champions' introduction, we were fighting enemies they were always visible to the player.

**Comment by 00-Evan** [comment]
When the hero takes damage, they are interrupted regardless of the damage source, with the exception of hunger or deferred damage. Enemy visibility, or whether the damage originated from an enemy, is not taken into account at all. The reason visible enemies seem to be better for this is that they also interrupt the hero when they come into view, separately from when they deal damage.

The only other case where taking damage does not interrupt the hero is when the player has pressed the 'continue moving' button. In such a case the game assumes the player wants to keep moving to the destination regardless of currently present interruptions, and so taking damage is ignored.

The variable that tracks this is updated every time the player is able to give input to the hero, so the next time the hero waits for input for any reason they will again start being interrupted by taking damage.

Were you using the continue moving indicator?

**Comment by Leajian** [comment]
I'm aware of the continue moving button interaction. I have re-encountered similar situation with a non-champion mob and you were right, on damage it interrupts. I need to test again with a projecting champion out of FOV, because I might have been wrong. The reason why I reported that is because I was quite sure it didn't press the 'continue moving' button. But, since I now believe I was wrong, I'm closing it here.
