### ISSUE TITLE
Mystical Charge talent no longer seems to activate

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#652]
In 0.9.2a, the Mystical Charge buff talent no longer seems to trigger.

I have that talent at level 3, but striking with the staff doesn't have any visible effect or buff, and artifacts don't seem to charge any faster.

In case it matters: I have a staff of corrosion, and my inventory includes the unstable spellbook (equipped), the horn of plenty (unequipped), and the hourglass (unequipped).

**Comment by 00-Evan** [comment]
There weren't any changes to artifact recharging in v0.9.2a, and the spellbook is also the slowest-charging artifact in the game. With mystical charge at +3 you'd need to land 7 hits to give it one charge. Artifacts have to be equipped to get recharging.

The talent doesn't have a visual indicator for itself though, it's expected for it to piggyback on the existing vfx for striking with the staff.

**Comment by joshtriplett** [comment]
I see; thank you for clarifying. I had assumed that "turns worth of artifact recharging" meant turns of the same buff that a scroll of mystical energy provides, so when that buff didn't appear, I was concerned that something was preventing that trait from taking effect.

Sorry for the noise.
