### ISSUE TITLE
potion of levitation animation, swiftthistle

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#654]
This is debatable, but I feel like potion of levitation animation should not be delayed by swiftthistle's time bubble.  Right now, there's no visual indication that you are levitating after drinking a potion of levitation under swiftthistle.  The text says, "you rise up into the air!", but the graphics show your feet on the ground.

![Screenshot_20210312-224916](https://user-images.githubusercontent.com/8593007/111077874-3062b400-84c9-11eb-8ef2-cafcc011c002.jpg)

**Comment by 00-Evan** [comment]
That's a fair point, especially as the particles are attached to the hero. I'll look into this in a future patch/update.

**Comment by 00-Evan** [comment]
I've opted not to change the behavior of the particles, however I am making a tweak to the hero sprite instead. an idling hero that is levitating now plays the flying animation, instead of standing.

**Comment by 00-Evan** [comment]
animations adjusted in commit 96b25f85220c908aefb928278cadcc386e332ad2
