### ISSUE TITLE
Ally Warp teleport behind locked doors

### ISSUE THREAD

**Issue by Zagrox11** [00-Evan/shattered-pixel-dungeon#655]
There are the cases, where you can teleport into an inaccessible area with Ally Warp talent. It can possibly soft lock the game.
![S10316-13151680](https://user-images.githubusercontent.com/67317633/111264534-0a751500-866b-11eb-8e0a-aad9238f8e27.jpg)

**Comment by Leajian** [comment]
How did you manage to make allies there? Disintegration zap with Necromancer's Minions talent? But what did you kill? A spawned wraith from corpse dust/cursed rose?

**Comment by Zagrox11** [comment]
> How did you manage to make allies there? Disintegration zap with Necromancer's Minions talent? But what did you kill? A spawned wraith from corpse dust/cursed rose? I mean, that's the only possible scenario I can think of, but I'm not sure if killing a wraith has a chance to "respawn" it as a friendly wraith. If yes, that's inherently the problem, it shouldn't be allowed and problem solved. (The last sentence/period was not a contribution nor suggestion, just sharing a thought. The developer is free to use my ideas without asking my permission.)

This is a corruption wand, not disintegration. The wraith spawned from corpse dust and I corrupted it.

**Comment by Leajian** [comment]
> > How did you manage to make allies there? Disintegration zap with Necromancer's Minions talent? But what did you kill? A spawned wraith from corpse dust/cursed rose? I mean, that's the only possible scenario I can think of, but I'm not sure if killing a wraith has a chance to "respawn" it as a friendly wraith. If yes, that's inherently the problem, it shouldn't be allowed and problem solved. (The last sentence/period was not a contribution nor suggestion, just sharing a thought. The developer is free to use my ideas without asking my permission.)
> 
> This is a corruption wand, not disintegration. The wraith spawned from corpse dust and I corrupted it.

My question is how did you corrupt it through the walls?

**Comment by Zagrox11** [comment]
> > > How did you manage to make allies there? Disintegration zap with Necromancer's Minions talent? But what did you kill? A spawned wraith from corpse dust/cursed rose? I mean, that's the only possible scenario I can think of, but I'm not sure if killing a wraith has a chance to "respawn" it as a friendly wraith. If yes, that's inherently the problem, it shouldn't be allowed and problem solved. (The last sentence/period was not a contribution nor suggestion, just sharing a thought. The developer is free to use my ideas without asking my permission.)
> > 
> > 
> > This is a corruption wand, not disintegration. The wraith spawned from corpse dust and I corrupted it.
> 
> My question is how did you corrupt it through the walls?

I corrupted it, then entered the boss area and used Ally Warp talent to switch places with corrupted wraith.

**Comment by Leajian** [comment]
The other case I imagined, zapping a spawned wraith with disintegration wand with a small chance to respawn it as an ally with the talent, is impossible according to source code. So, ignore it. https://github.com/00-Evan/shattered-pixel-dungeon/blob/889c5b5621b9dbee83e46a750cc571566bb4c06f/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/Mob.java#L693

**Comment by 00-Evan** [comment]
Ally warp probably needs a pathfinding check similar to ethereal chains, will add that, thanks.

**Comment by 00-Evan** [comment]
fixed in commit b2fefa256fe3218ad16a572258fceda683917bb1
