### ISSUE TITLE
Excess Charge talent shielding AND healing

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#656]
I have the Excess Charge talent at level +3 and what is suppose to do is, have a chance of shielding the mage for every charge his staff has when hitting with it. But it never says it heals. And that's what is doing for me. I also have the Chalice of Blood +10 so this might be the reason. But I'm not sure, because my character was starving when this happened so the Chalice shouldn't even work there.

Here is at the beginning of the the fight, I'm starving so the chalice isn't working
![Screenshot_20210318-141503](https://user-images.githubusercontent.com/47122537/111669918-06293300-87f6-11eb-900e-712ba5aee713.png)

Here is after the talent activates, shielding me AND healing me
![Screenshot_20210318-141518](https://user-images.githubusercontent.com/47122537/111670238-5e603500-87f6-11eb-81e2-e3b20170e112.png)

**Comment by 00-Evan** [comment]
Do you have the mystical charge talent? That would grant artifact recharging, which translates to health for the chalice.

**Comment by ShinKeyKai** [comment]
Yes I do. I didn't know the artifact recharging worked in the chalice. Then is working properly, my bad.
