### ISSUE TITLE
Sniper follow-up shot unable to target with projecting enhancement

### ISSUE THREAD

**Issue by Oblomov** [00-Evan/shattered-pixel-dungeon#657]
Hello,

I just completed a Sniper run with a projecting enhancement to the bow and the talent to extend the bow enhancement to thrown weapons. During the final boss fight I hit Yog with a (normal) thrown weapon from behind one of the pillars, and the follow-up shot icon appeared, but clicking it wouldn't work. I stepped aside so that Yog was directly visible and the follow-up shot worked.

**Comment by 00-Evan** [comment]
Odd, they should use the exact same logic. I'll look into that.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this, from my tests sniper's mark correctly accounts for projecting.
