### ISSUE TITLE
Animation on Evil Eye dewdrops can be applied to item in adjacent space

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#658]
When the evil eye dies, and spawns multiple dewdrops, if one of the dewdrops moves into an adjacent space that already has an item in it, the animation of the dewdrop moving from the evil eye's space to the adjacent space can be applied to the item instead, making it look like the item moves from the evil eye's space (which it wasn't in) to the space the item is already in.

I saw this happen with a scroll. Killed an evil eye next to the scroll, then it looked like the scroll flew from the evil eye's space to the space already containing the scroll.

**Comment by 00-Evan** [comment]
This is an interesting side-effect of dew drops always dropping to the bottom of item heaps. I'll add a check to account for this on evil eye deaths.

**Comment by 00-Evan** [comment]
fixed in commit f0996a2b8562d232ba777be1922893a1346eef32
