### ISSUE TITLE
remove curse: dialog allows choosing uncursed items

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#659]
The remove curse dialog allows you to pick blue highlighted items, which are unidentified, but known not to be cursed.
![Screenshot_20210321-192328](https://user-images.githubusercontent.com/8593007/111924650-fc186600-8a7b-11eb-821d-d26206e76401.jpg)

**Comment by 00-Evan** [comment]
As it happens, this is already being addressed in v0.9.2b

**Comment by 00-Evan** [comment]
fixed in commits c91b90a5144d6c62e95cb5763c8e4c1231bca92f and d9457bc01d68fded478f82f0da04ab7b67b2be64
