### ISSUE TITLE
Gladiator Enhanced Combo - leap targetting needs work

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#660]
Gladiator's "Enhanced Combo #3" leap (for slam/crush/fury) is a cool idea, but I feel like it needs some work.  For example, you can't target the shock elemental in this screenshot, even though the shock elemental is only 2 tiles away, has empty squares around it (except for the monk), and the combo meter is full.  "You must target an enemy in attack range".

Related to this, leaping combos seem to have a propensity for jumping me into holes.  Ideally, this leaping combo would allow you to choose the square to land on, or at least attempt to not jump you into hazards.  I'm guessing that there's always a specific square, relative to you and the target, which the leaping combo sends you to, but it's not very user-friendly.

![Screenshot_20210315-221410](https://user-images.githubusercontent.com/8593007/111924723-4699e280-8a7c-11eb-907f-8ed6d362941f.jpg)
![Screenshot_20210315-221419](https://user-images.githubusercontent.com/8593007/111924707-3550d600-8a7c-11eb-8e81-8052e747fa48.jpg)

**Comment by 00-Evan** [comment]
The pit part is actually being fixed in v0.9.2b, otherwise though this is intended. Unlike something like the Assassin's blink (which is more permissive), the combo leap uses projectile logic, and so can be blocked. It does not curve around terrain or enemies.

**Comment by 00-Evan** [comment]
fixed in commit 8c51d26a0acc5d4c0ab02074ee775799f454a058
