### ISSUE TITLE
Enhancement: view (sub)class abilities

### ISSUE THREAD

**Issue by JumperPunk** [00-Evan/shattered-pixel-dungeon#662]
After choosing a class or a subclass, there isn't a way to see what abilities are associated with that choice. This is useful to get the nuances of the abilities, or when playing as less familiar classes. Some of these abilities can be seen in detail through the applied buffs, but not all of them. My best guess is a new tab on the stats/talents/buffs dialog is the best place to put it.

**Comment by 00-Evan** [comment]
This already exists in the game within hero select, but I agree that it would be nice to put that information somewhere more accessible to someone who's ingame. I was already planning on making such changes in v0.9.3, but I'll keep this issue open to track that.

**Comment by 00-Evan** [comment]
added in commit 4cb3fe024aa84109b87a51d53729606964653587

0.9.3 also included major improvements to the info windows for heros/subclasses in general.
