### ISSUE TITLE
Tiles wrongly stay visible after blinking

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#665]
1. Stand in the middle of a large room.
2. Blink a fair distance towards an enemy.
3. Watch as the tiles behind you stay visible when they should be outside of the vision range.

Version: 0.9.2a

**Comment by 00-Evan** [comment]
Assuming you're referring to ally warp, this is fixed in v0.9.2b, please update to the latest version.

If not, please be more specific about what type of blink you're referring to.

**Comment by MiroslavR** [comment]
I'm referring to the rogue's blink ability.

**Comment by 00-Evan** [comment]
The rogue does not have a blink ability. Do you mean the Assassin's blink, or the smoke bomb ability on the rogue's armor?

**Comment by MiroslavR** [comment]
The Assassin's blink.

**Comment by MiroslavR** [comment]
I just checked and the smoke bomb doesn't suffer from this issue.

**Comment by 00-Evan** [comment]
Okay, I'm able to reproduce this, will get it fixed in v0.9.3. Please be more specific when reporting issues in the future, I can't guess which effect you mean if you give a generic description.

**Comment by 00-Evan** [comment]
fixed in commit 13471a3ffdeedda89c78ff4c383e40039da3adae
