### ISSUE TITLE
Able to select both rewards from ghost/wandmaker

### ISSUE THREAD

**Issue by roark-z** [00-Evan/shattered-pixel-dungeon#667]
Hey, I've found a bug when accepting rewards. If the player taps both buttons simultaneously, they will be able to receive both rewards. To replicate, complete the quest for either ghost or wandmaker, and select both options. Thanks Evan!

Version: v0.9.2a

**Comment by 00-Evan** [comment]
Hey, I'm aware of this and do plan to have it fixed next update. Due to the nature of this bug I'm going to close this issue and edit out details.
