### ISSUE TITLE
ethereal mirror images get caught in webs and trample grass

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#669]
According to the text, mirror images are ethereal and only become solid when attacking.  However, I had the problem where these ethereal mirror images kept trampling grass I was using for cover and getting stuck in webs.  Perhaps they're only pretending to get stuck in webs to complete the lifelike illusion, but if they're going to pretend to be a huntress, they shouldn't trample grass, only furrow it.
![Screenshot_20210326-072610](https://user-images.githubusercontent.com/8593007/113490769-5f51c180-949a-11eb-9b79-5250d82c3b2e.jpg)
![Screenshot_20210323-185224](https://user-images.githubusercontent.com/8593007/113490772-6082ee80-949a-11eb-858f-ab1952b85127.jpg)

**Comment by 00-Evan** [comment]
The 'ethereal' text is mostly for flavor, in effect they are invisible until they attack. I'll consider tweaking the description to avoid confusion.
