### ISSUE TITLE
Gladiator's enhanced combo leap - does it need extra combo meter?

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#670]
The Gladiator's Enhanced Combo talent text does not indicate that a leap needs a high combo meter.  However, in practice, that's what seems to be required.  In this circumstance, I'm trying to slam the DM300 from 3 tiles away, but I get the message, "You must target an enemy in attack range."
![Screenshot_20210327-184558](https://user-images.githubusercontent.com/8593007/113491022-bdcb6f80-949b-11eb-9dc8-81d858f0228a.jpg)
![Screenshot_20210327-184553](https://user-images.githubusercontent.com/8593007/113491023-bdcb6f80-949b-11eb-939b-c5020337c7c3.jpg)

- _+1:_ When the Gladiator's combo is 7 or higher, Clobber's knockback range increases to 3, it inflicts vertigo, and it can knock enemies into pits.
- +2:_ In addition to the benefits of +1, when the Gladiator's combo is 9 or higher Parry works on multiple attacks.
- +3:_ In addition to the benefits of +1 and +2, the Gladiator can leap up to combo/3 tiles when using Slam, Crush, or Fury.

**Comment by 00-Evan** [comment]
It's right there in the description: "can leap up to combo/3 tiles". At a combo of 4 you would only be able to leap 1 tile.
