### ISSUE TITLE
Cant work well on wearos[watch]

### ISSUE THREAD

**Issue by 1812z** [00-Evan/shattered-pixel-dungeon#671]
i play this game on my watch
almost everything can work well
but 1.Swipe right to exit
2.the text is too small,i cant see clearly

Thats small problems
just some changes

**Comment by 00-Evan** [comment]
Sorry but I'm not currently planning to support smartwatches in any capacity. Their screens are prohibitively small, and so supporting them would require an entirely new UI.

**Comment by 00-Evan** [comment]
@echo0x22 Afraid not. I'm fine with the game being played on wearables, but have no plans to officially support them. The most I would consider doing is very small targeted changes. e.g. if some specific Android configuration flag could be changed to improve the experience. More substantial things like interface changes just aren't worth the time commitment I'm afraid.
