### ISSUE TITLE
Huntress doesn't stop when furrowing produces items

### ISSUE THREAD

**Issue by benkorpella** [00-Evan/shattered-pixel-dungeon#672]
When the huntress furrows grass from the Rejuvenating Steps talent while walking, she doesn't stop.

**Comment by 00-Evan** [comment]
That's working as intended, why would you think that her movement is intended to stop when she spawns grass from that talent?

**Comment by benkorpella** [comment]
I think she is supposed to stop when an Item appears.  It is really annoying when your walking long distances and there's an item there, but you keep walking.
