### ISSUE TITLE
empty well locked rooms should not generate on the wandmaker's floor with rotberry quest

### ISSUE THREAD

**Issue by lele92007** [00-Evan/shattered-pixel-dungeon#673]
just see this post i found on the reddit :
https://www.reddit.com/r/PixelDungeon/comments/mmteai/it_may_be_a_bug_or_im_just_an_idiotread_comment/
i think it's not a minor bug because it don't cause any problem

-if you open the empty well room you can take the second key without falling in previous floor's chasm
-if you open the quest room you just have to fall in chasm

and it only happens when you have rotberry quest because both others quest use a "barricade"c with a PoF

**Comment by 00-Evan** [comment]
I'm aware of this and don't consider it serious enough to be work adjusting, the player just gets an easier pit room in rare circumstances.

**Comment by lele92007** [comment]
ok
