### ISSUE TITLE
Small improvement to desktop build readme

### ISSUE THREAD

**Issue by Khalarii** [00-Evan/shattered-pixel-dungeon#674]
So I cloned the repository and had some small issues getting the project to compile using JDK 16 but it worked perfectly fine for version 8. I was going to create a pull request with a small troubleshooting section added to the Quick setup part of the readme but noticed you do not want PRs. Love the work you do, simply superb game. Congrats!

### Troubleshooting
If you downloaded the latest JDK and you're getting compilation errors such as `Could not find tools.jar` or `module 'x' does not export 'y' to unnamed...` try uninstalling the JDK and installing [Version 8](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html).

**Comment by 00-Evan** [comment]
The guide is written for folks looking to compile with android studio primarily. I'll make a note on the quick setup guide that the current project is designed to work on JDK 8 (though thankfully it does seem that Android is moving to a more modern one soon).

**Comment by 00-Evan** [comment]
fixed in commit 741420bc34c9683beee6ccea3f3a367bf881dcbe
