### ISSUE TITLE
Extra chill damage or rooting on water

### ISSUE THREAD

**Issue by doctormo** [00-Evan/shattered-pixel-dungeon#675]
When fighting the elementals, I find that the fire elementals are much more interesting in terms of working out where I want to be when I fight them. Not in a doorway, on water if possible. But the cold elemental doesn't provide the same amount of strategic problem solving.

One suggestion could be that while water is good for fire elemental fighting, it could be bad for the cold elemental. Either by rooting the player on chill (freezing the water would be a neat graphic too) or by giving the player frostbite damage over time.

I'm not sure what to do about the other elementals. The electricity elemental could have extra damage on water too, and the chaotic elemental could just turn you into a sheep :wink:

**Comment by 00-Evan** [comment]
Cold elementals actually already do give substantially more chill if the player is in water.

Their melee normally has a 1/3 chance to give 3 turns of chill, and their ranged attack gives 3 turns always.
In water, all of their attacks are guaranteed to give 5 turns of chill.
Once the player has more than 10 turns of chill stacked on them they can be frozen.

Electric elementals also arc lightning more widely in water.

**Comment by doctormo** [comment]
I guess the question is, why doesn't it feel as punishing as being on fire that I never even noticed.
