### ISSUE TITLE
Adrenaline Surge depletion indicator is incorrect

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#676]
Adrenaline Surge, the buff Warden gains after trampling a rotberry bush, indicates its depletion (turns left) incorrectly in the upper left corner of the screen. When you freshly gain the buff, it appears as if a large chunk was gone already.

Version: 0.9.2b

**Comment by 00-Evan** [comment]
This is because the default duration of the buff is 800 turns (from the adrenaline surge potion). The warden gets a shorter effect and so it shows as 1/4 of the default duration.

**Comment by MiroslavR** [comment]
So you're saying the behavior is intended? It's pretty unintuitive, you know...
