### ISSUE TITLE
crash when tapping on mirror image

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#677]
I just came up the stairs - on my way up to win the game.  If I click on the mirror image (which was there when I came up the stairs), the game crashes.
I started the game and repeated the tap and the game crashed again.  Then Android popped up a dialog saying that the app keeps crashing.
This is on Android 11, Build number RQ2A.210305.006.
![Screenshot_20210412-210540](https://user-images.githubusercontent.com/8593007/114481993-bf034780-9bd3-11eb-8988-cfa232fa2871.jpg)
![Screenshot_20210412-210941](https://user-images.githubusercontent.com/8593007/114481989-be6ab100-9bd3-11eb-9e20-9ecd350f067b.jpg)
![Screenshot_20210412-210959](https://user-images.githubusercontent.com/8593007/114481991-be6ab100-9bd3-11eb-8a48-10bd49ef2743.jpg)

**Comment by Leajian** [comment]
I had something similar, but with no crash. My prismatic image was naked, like yours. That happened to me after upgrading my save from release to release.

**Comment by 00-Evan** [comment]
There were some errors relating to mirror/prismatic images during 0.9.2. The source of the bug was fixed in 0.9.2b but it does seem these images are still causing crashes if they stick around in save data. Will add some safety checks or similar to prevent these.

**Comment by 00-Evan** [comment]
This was a symptom of a larger issue to do with actor ID's not carrying over properly between save/load. Should now be properly fixed

fixed in commit 17929740513bdd932836d26d2fb30b3b58ce19fd
