### ISSUE TITLE
Gradle 7 Support

### ISSUE THREAD

**Issue by lorenzleutgeb** [00-Evan/shattered-pixel-dungeon#678]
It seems that https://github.com/00-Evan/pixel-dungeon-gradle already supports Gradle 7. Could we get a new release of this project that's compatible with Gradle 7 as well, please?

**Comment by 00-Evan** [comment]
I'm able to update dependencies on the vanilla repo more quickly as there's no content development happening there. Shattered is already updated to 7.0 internally and that will release with the next update as usual.

**Comment by 00-Evan** [comment]
fixed in commit f52ced5e74ab1e13405e01df5b00cd6d568aa916
