### ISSUE TITLE
Badge missing

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#679]
Even though I've completed the game with all subclasses, still I wasn't awarded the "Slain 3rd boss" badge.
![Screenshot_20210424-231702_Trebuchet](https://user-images.githubusercontent.com/46329185/115973228-b0158100-a553-11eb-942b-f2f5d0f50460.png)
![Screenshot_20210424-231637_Trebuchet](https://user-images.githubusercontent.com/46329185/115973251-d0ddd680-a553-11eb-9b7c-a68d62f662ad.png)

**Comment by 00-Evan** [comment]
It would be nice for the game to display your progress here, but you must have either won with the same subclass twice at one point, or did not pick a subclass until after defeating DM-300 in one of your runs.

You'll have to defeat DM-300 with whichever subclasses you're missing, unfortunately you can't tell what those are.

**Comment by pescepalla** [comment]
I've checked and I'm sure I won with each subclass. Maybe it's your second guess, then.
