### ISSUE TITLE
Prevent accidential harmful actions

### ISSUE THREAD

**Issue by KOLANICH** [00-Evan/shattered-pixel-dungeon#68]
Acidential taps (it seems like a touchscreen glitch which recognizes finger near surface (w/o touching) as a tap) can cause loss of health, destroying of items or death. I propose to
1 ask a confirmation for moving in the area the enemy will hit.
2 ask a confirmation for using wells, triggering traps, any unprofitable moves changing environment/items.
3 ask a confirmation for zapping wands in the way they will make no effect (to the wrong tile or wall for example).

**Comment by 00-Evan** [comment]
I don't think it's a good idea to give confirmation dialogues for every single negative action. there's a balance between warning too much, or too little. Right now shattered does do things like preventing the player from leaping into chasms, which makes sense as there are level layouts where tapping on chasm tiles is very easy to do. Conversely though, putting in warnings for every harmful action would be too much. Traps and enemies, especially, should be dangerous and putting in warnings for non-ideal actions takes away a lot of the impression of danger.

In the case of zapping with wands though, I feel like that problem has been pretty much solved with the recent auto-targeting improvements anyway.

Please do discuss this further with me if you want to, but as it stands this won't be implemented.

**Comment by KOLANICH** [comment]
>Traps and enemies, especially, should be dangerous and putting in warnings for non-ideal actions takes away a lot of the impression of danger.
When one fights enemies, he usually moves from them, not to them.
When ones sees dangerous traps, he usually avoids them (excluding trap rooms) rather stepping on them. So I think it won't harm the atmosphere if the game would ask whether the user really wants to move through the cells under attack because this kinds  of moves are usually accidential.

**Comment by 00-Evan** [comment]
Preventing someone from doing the unusual action is why this would ruin the atmosphere. Prompting the player before every possibly incorrect action establishes an atmosphere of safety. The game won't let the player make a mistake, so why worry? Obviously PD is a turn-based RPG at heart so things like reflexes should never be a factor in player skill, but putting a prompt before any possible incorrect action is taking things too far in my book. It gives the impression the game is babying the player.

There are, however, some exceptions where not prompting would become a usability issue, like chasms as I mentioned previously.

**Comment by KOLANICH** [comment]
>Prompting the player before every possibly incorrect action establishes an atmosphere of safety.

Yes. But I haven't said about every possible. I said about *obiviously* harmful actions. When you step on known fire trap you know it will be triggered and you will be burnt. When you walk around alive, unbuffed and hunting enemy you know it will hit you.

**Comment by 00-Evan** [comment]
Right, and so in these circumstances if you do those actions anyway if your fault and the game shouldn't prevent it. We both agree on big usability concerns like chasms, but I don't think obviously incorrect actions are appropriate for this. I feel its too close to the game not letting the player make mistakes.

Accidental taps are unfortunate but I don't think it makes sense for the game to try and decide for the player whether they meant to do a certain thing, or whether they know that they shouldn't be doing a certain thing.

**Comment by jimbo1qaz** [comment]
Armor of Bounce makes it very easy to walk into the enemy, instead of attacking it.
