### ISSUE TITLE
Sped up animations after using Freezing Potion, Scroll of Drowsiness and Swiftwhistle seed

### ISSUE THREAD

**Issue by LyraLover** [00-Evan/shattered-pixel-dungeon#680]
I was trapped and was low on health, so I needed to do something
1. Used unidentified potion, it happened to be Freezing potion
2. Used unidentified scroll, it was a Scroll.of Drowsiness
3. Threw a Swiftwhistle seed and stepped on a plant
4. Ate small ration

Animations appear to be sped up after these actions

[Video](https://youtube.com/shorts/INlxb2woqtc?feature=share)

**Comment by 00-Evan** [comment]
Looks like the animations aren't even playing, not that they're sped up. Probably this is due to a combination of the freezing and swiftthistle effects.

**Comment by 00-Evan** [comment]
fixed in commit 3cfe7256091234aa524224d5562b6c29826d6204
