### ISSUE TITLE
flatpak will not launch on pinephone?

### ISSUE THREAD

**Issue by gamerminstrel** [00-Evan/shattered-pixel-dungeon#681]
I am currently running Manjaro + Plasma Mobile on the Pinephone. The flatpak version of Shattered Pixel Dungeon will never successfully launch. If I launch from the terminal, I get the following error:

```
$ flatpak run com.shatteredpixel.shatteredpixeldungeon

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```

I would be happy to help troubleshoot or test changes, just tell me what to do if I can help!

**Comment by 00-Evan** [comment]
the flatpak version is not an official distribution, please report any issues to that project's maintainer.

**Comment by hfiguiere** [comment]
It's because the jar include x86_64 only binaries.... and there is not even build instruction how to rebuild these.

(PInephone is aarch64, like RaspberryPi 4)
