### ISSUE TITLE
haste and running through water while on-fire

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#682]
It seems that if I am hasted (e.g. a ring of haste), running through or standing in water while on fire does not always put the fire out.

**Comment by protective1** [comment]
![Screenshot_20210420-145044](https://user-images.githubusercontent.com/8593007/116593727-66c88700-a8ef-11eb-955d-39500bccbbc7.jpg)
![Screenshot_20210420-145103](https://user-images.githubusercontent.com/8593007/116593725-662ff080-a8ef-11eb-8f8c-9cd85a023c4e.jpg)

**Comment by 00-Evan** [comment]
This is working as intended. You need to be in water for a turn for it to extinguish fire, and so moving quickly can prevent you from standing in water for long enough.
