### ISSUE TITLE
upgrading item didn't increase count in quick slot

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#683]
I had two +2 boomerangs in my quick slot.  I upgraded another +1 boomerang.  The quick slot still shows two +2 boomerangs, even though inventory now has three +2 boomerangs.
![Screenshot_20210424-212356](https://user-images.githubusercontent.com/8593007/116592651-39c7a480-a8ee-11eb-9c13-13124e2148ed.jpg)

**Comment by 00-Evan** [comment]
fixed in commit 62f3b497abf0921facf812a1263db05851741732
