### ISSUE TITLE
cleaning 1 dart prompts to "clean all"

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#684]
Cleaning off 1 dart prompts the user to choose between "clean 1" or "clean all".  This prompt is confusing, because I think both choices only clean 1 dart.  I think the "clean all" choice shouldn't show when cleaning 1 dart.

![Screenshot_20210417-131948](https://user-images.githubusercontent.com/8593007/116593008-a347b300-a8ee-11eb-86f7-b352e45d691c.jpg)

**Comment by 00-Evan** [comment]
I'd rather keep the interface consistent, especially when people often tap based on muscle memory.

**Comment by protective1** [comment]
> 
> 
> I'd rather keep the interface consistent, especially when people often tap based on muscle memory.

The issue is that it's not clear if "clean all" will clean every dart in your inventory, or just this one.  Suppose I have 2 incendiary darts and 1 displacing dart.  I click to clean the displacing dart.  The "Clean all" choices implies it will also clean the 2 incendiary darts that I did not click on.

**Comment by 00-Evan** [comment]
You could just as easily argue that 'stack' is misleading as there's only one dart. I think the simplest solution to this would be to just include the dart being addressed somewhere in the window. I'll consider that for next update.
