### ISSUE TITLE
Message "Badge endorsed: X potions cooked" doesn't appear

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#685]
Normally, when I obtain a badge during a run, a message "Badge endorsed: BADGE" pops up. However after brewing potions and exiting alchemy UI I have never seen "Badge endorsed: X potions cooked" message show up, even though I got the badge normally at the end of the run. It seems like when the alchemy UI is opened, the message isn't generated.

**Comment by 00-Evan** [comment]
fixed in commit 1463afcaf2a550af263db09f6ab96078348c35e5
