### ISSUE TITLE
Back gesture in Alchemy Pot leads to titlescreen

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#686]
v.0.9.2b
When I use the back gesture (swipe from the right side of the screen to the center) on my Xiaomi Mi Mix 2S to close the alchemy pot dialog, the game returns to the title screen instead of just closing the dialog. (However, a workaround is available, you can click the small icon on the top right corner.) Thks behavior was different in earlier versions.

**Comment by 00-Evan** [comment]
This is an unfortunate error in the Android operating system. When the back button is pressed the game should handle it (and alchemy scenes are set to change the current scene back to the game scene) but every so often Android seems to decide that it wants to control the back press instead and resets the app.
