### ISSUE TITLE
Wards can suffer weird status effects (sleep, etc)

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#687]
Looks like `isImmune` wasn't implemented for the `Ward` class. There are some amusing interactions, such as sleeping wards, rooted wards, bleeding wards, and terrified wards.

I know you don't accept PR's, but this should do the trick.

```
		@Override
		public boolean isImmune(Class effect) {
			if (effect == Burning.class ||
				effect == Bleeding.class ||
				effect == Poison.class ||
				effect == Paralysis.class ||
				effect == Roots.class ||
				effect == Sleep.class ||
				effect == Drowsy.class ||
				effect == Terror.class ||
				effect == Drowsy.class ||
				effect == Cripple.class ||
				effect == Charm.class ||
				effect == MagicalSleep.class) {
				// The ward *can* be fully affected fully by frost/chill, ooze, corrosion
				// Perhaps we want it to also be burnable? I don't know if wards catch fire
				return true;
			}
			return super.isImmune(effect);
		}
```

Example images:

![rooted-ward](https://user-images.githubusercontent.com/5109532/117092980-029c3c00-ada3-11eb-8f0b-c6ee142d7cb8.png)
![drowsy-ward](https://user-images.githubusercontent.com/5109532/117092982-0465ff80-ada3-11eb-9289-6e3a2236012d.png)

**Comment by 00-Evan** [comment]
Wards are considered inorganic (immune to bleeding, toxic gas, and poison), but otherwise have no special abilities. This is working as intended.

**Comment by AddisonG** [comment]
Dunno why inorganic things can sleep, but hey - Sleepy wards are funny I guess.
