### ISSUE TITLE
Well of Healing doesn't fully heal players wearing cursed rings of strength

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#688]
If you have a **Cursed** Ring of Strength equipped, and you step into a Well of Healing, you will be left with only 90% hitpoints or so (depending on the level of the ring).

For example, I was left on 48/54 HP after stepping into this one, and had a Ring of Strength +1 (after removing the curse).

![well-of-healing_and_cursed-ring-of-strength](https://user-images.githubusercontent.com/5109532/117093169-9241ea80-ada3-11eb-9b81-cd101a25b683.png)

**Comment by 00-Evan** [comment]
Looks like this is happening because the well is cleansing curses after providing a full heal, so the health penalty from the ring of might is resulting in your health being reduced during the heal effect.

Probably the well should be adjusted to uncurse first, then heal.

**Comment by 00-Evan** [comment]
Appears this was incorrectly marked as resolved, apologies. Will fix in v0.9.3a

**Comment by 00-Evan** [comment]
fixed in commit 2d8305ed5b572524eb89457f3c6da4a2c222c59d
