### ISSUE TITLE
Item bounce animation bug

### ISSUE THREAD

**Issue by GrantMoyer** [00-Evan/shattered-pixel-dungeon#689]
When the inventory is full, items on the ground bounce to indicate they cannot be picked up. If the item's tile is repeatedly tapped, it will continue bouncing higher and higher until the tapping stops.

https://user-images.githubusercontent.com/6333127/117213340-7e10e400-adc9-11eb-9b69-f55863d8233c.mp4

**Comment by 00-Evan** [comment]
This is intended. see #640, #203, #40
