### ISSUE TITLE
Reforging short sword doesn't work

### ISSUE THREAD

**Issue by klement** [00-Evan/shattered-pixel-dungeon#69]
I was playing warrior and never got the option to reforge the starting sword offered.

**Comment by 00-Evan** [comment]
Did you upgrade the short sword first? You can only reforge to transfer upgrades one the short sword actually has upgrades on it.

**Comment by klement** [comment]
Oh, no I didn't. That's not clear from the description...

**Comment by 00-Evan** [comment]
Agreed. I'm going to be making big changes to the warrior very soon though anyway.
