### ISSUE TITLE
Enhancement: show which scrolls have been added to Unstable Spellbook

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#690]
Can you add a way to see which scrolls have already been added to Unstable Spellbook?  I have a hard time remembering which scrolls I've already added and which ones I'm still saving to add later.  Maybe you could dim out any previously added scrolls in the "Add" scroll selection dialog (similar to dimming items when using Identify / Remove Curse), or just list out the added scrolls in the Spellbook's description?

**Comment by 00-Evan** [comment]
Some similar functionality was added for the footwear of nature, I could look into doing this for the spellbook too.

**Comment by 00-Evan** [comment]
added in commit 82ce389a484f9f7318ca4b58f547cb31a12830f6
