### ISSUE TITLE
enhanced rings and remove curse

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#693]
When the rogue's Enhanced Rings talent is activated, non-cursed rings can be selected with Remove Curse.
![Screenshot_20210509-154722](https://user-images.githubusercontent.com/8593007/117598437-cefc4180-b115-11eb-82f9-c0f4c74e3f89.jpg)

**Comment by 00-Evan** [comment]
fixed in commit f51475b7d3c5a52aa56af732b82544520c811ac4
