### ISSUE TITLE
Unstable Spellbook - biased to repeat spell?

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#695]
Using the Unstable Spellbook I got Rage/Confusion 5x in a row.  This is not the first time I've felt like the spellbook is biased towards repeating the same spell again.  I feel like I'm more successful at forcing a repeat if I use the spellbook multiple turns in a row without clicking anything else.  But I can't think of a good way to record enough samples to test this theory (short of playing the game hundreds of times).  Is there a bias or is it just my imagination?

**Comment by 00-Evan** [comment]
The code is pretty straightforward here:

```
Scroll scroll;
do {
	scroll = (Scroll) Generator.randomUsingDefaults(Generator.Category.SCROLL);
} while (scroll == null
		//reduce the frequency of these scrolls by half
		||((scroll instanceof ScrollOfIdentify ||
			scroll instanceof ScrollOfRemoveCurse ||
			scroll instanceof ScrollOfMagicMapping) && Random.Int(2) == 0)
		//don't roll teleportation scrolls on boss floors
		|| (scroll instanceof ScrollOfTeleportation && Dungeon.bossLevel())
		//cannot roll transmutation
		|| (scroll instanceof ScrollOfTransmutation));
```

A random scroll is rolled using the default probabilities (no weighting based on previous rolls). The only additional modifications are that identify, remove curse, and magic mapping functionally have their probabilities halved, transmutation cannot be rolled, and teleportation can't be rolled on a boss floor.

Default probabilities are here:
```
SCROLL.classes = new Class<?>[]{
	ScrollOfUpgrade.class, //3 drop every chapter, see Dungeon.souNeeded()
	ScrollOfIdentify.class,
	ScrollOfRemoveCurse.class,
	ScrollOfMirrorImage.class,
	ScrollOfRecharging.class,
	ScrollOfTeleportation.class,
	ScrollOfLullaby.class,
	ScrollOfMagicMapping.class,
	ScrollOfRage.class,
	ScrollOfRetribution.class,
	ScrollOfTerror.class,
	ScrollOfTransmutation.class
};
SCROLL.defaultProbs = new float[]{ 0, 6, 4, 3, 3, 3, 2, 2, 2, 2, 2, 1 };
```

The previous scrolls that you roll should have no impact on future ones, though some scrolls are more common than others.
