### ISSUE TITLE
Corrupted enemies indirectly kill themselves in Dwarf King's lair

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#696]
I had a very upgraded corrupting battle axe in Dwarf King's lair.  I was fairly easily able to corrupt all of Dwarf King's summoned monsters.  However, because Dwarf King had Life Linked them, they were killing themselves indirectly by hitting the Dwarf King.  I'm just checking - is this intentional?  When an enemy gets corrupted, should Life Link remain?
![Screenshot_20210510-172009](https://user-images.githubusercontent.com/8593007/118067122-f1889780-b36d-11eb-96fa-e9353e709951.jpg)

**Comment by 00-Evan** [comment]
Life link isn't considered to be a debuff, so it is preserved when a character gets corrupted.
