### ISSUE TITLE
Magical Infusion doesn't end Degrade

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#697]
The description for Magical Infusion says, "This spell possesses the same magical power as a scroll of upgrade, but in a more stable form.  In addition to upgrading an item as normal..."  This text implies that a Magical Infusion has all the abilities of scrolls of upgrade plus more.

However, the text for Degrade states, "Using a scroll of upgrade or remove curse will end degradation immediately."  It does not specifically mention Magical Infusion.

I converted all of my remaining Scrolls of Upgrade to Magical Infusion.  Then after getting hit with a Degrade, I tried to use a Magical Infusion to remove Degrade, but that did not work.  Should Magical Infusion remove Degrade?

**Comment by 00-Evan** [comment]
fixed in commit 8eedc0d215cf67e48364339cb546cf774dded64c
