### ISSUE TITLE
Timekeepers hourglass statis == instant death

### ISSUE THREAD

**Issue by klement** [00-Evan/shattered-pixel-dungeon#70]
After triggering stasis, the hero dies after every creature attacks it freely while the player is unable to do anything (happened multiple times after I accidentally used the feature).

According to the wiki - the hero should be invisible (which would actually make sense) during the stasis, but it's not.

**Comment by 00-Evan** [comment]
This should be fixed as of 0.3.2c, which version of the game are you running?

**Comment by klement** [comment]
0.3.2b - the latest available in fdroid repos

**Comment by 00-Evan** [comment]
Okay good, this will be fixed when f-droid updates to 0.3.3, closing.
