### ISSUE TITLE
stepping on fadeleaf doesn't activate nature's aid

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#700]
Stepping on fadeleaf doesn't activate the Nature's Aid talent - is this a bug? Of course, it could be arguable whether the plant was activated in the player's vision since it causes the player to teleport away.  But my argument is that the activation comes first because that's what causes the player to teleport.  Therefore, it did indeed activate within the player's vision (before they teleported away) and therefore should activate Nature's Aid.

**Comment by 00-Evan** [comment]
Yeah the talent should probably trigger before the seed effect instead of after, which will resolve this. Will roll that info beta-1.1

**Comment by 00-Evan** [comment]
fixed in commit cfd2a5eb63e1a9781c22a495f058afda420e39da
