### ISSUE TITLE
Cursed wand can't apply soul mark

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#703]
I am not sure is it is a bug, but when I was checking how soul mark works, I noticed there is no mention of it in CursedWand class. It can't apply the soul mark effect on zap. Under certain circumstances cursed wand is actually a viable weapon, it would make sense if it worked with warlock's abilities like other wands do.

**Comment by 00-Evan** [comment]
This would be a fairly simple change to improve cursed wand synergy potential, sure.
