### ISSUE TITLE
Restored nature talent can root allies

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#704]
The huntress talent, restored nature, rooted my prismatic image when I drank a potion to heal myself. The talent description says it will root adjacent enemies not allies.

Here I'm trying to interchange position with the prismatic image but can't because it's rooted
![Screenshot_20210522-015939](https://user-images.githubusercontent.com/47122537/119215261-fa324980-baa2-11eb-8639-a295c5aec4ae.png)

I don't know if this has anything to do but me and my prismatic image are both charmed

v0.9.3-BETA-1.0

**Comment by 00-Evan** [comment]
fixed in commit 192700e6b482649f0d1b489a21774173d89dc858
