### ISSUE TITLE
Death mark not showing turns left

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#707]
It doesn't show an actual value when you tap the death mark as you examine an enemy
![Screenshot_20210523-032353](https://user-images.githubusercontent.com/47122537/119251320-6b91fb00-bb7c-11eb-9f1c-6db64c29b44a.png)

**Comment by 00-Evan** [comment]
This is already fixed in beta-1.1, please update.
