### ISSUE TITLE
Enhacement: Badges in journal

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#708]
I find it hard keeping track of the achievements Ive done and what Ive yet to do. It'd be easier if we could track it on out journal maybe? Lets jist say weve heard our ancestors talk about legends done by them and wrote it on our journal to achieve too.

**Comment by 00-Evan** [comment]
I'm not sure what you mean by this. The game already does have a comprehensive list of badges in the main menu, which includes the ones you haven't unlocked yet.

**Comment by Block-Vader** [comment]
I think what he means is being able to see badges you obtained during a run before it ends. Currently you can only see them in rankings once it's over.

**Comment by 00-Evan** [comment]
Closing this as no further post was made by the author.

I do agree it might be nice to see badges in a run in progress, but I worry it would also be confusing. You can easily see what badges you're missing overall from the main menu, and that's the information most players want when badge hunting. Showing the missing badges for a particular run in progress means players have two sets of missing badge information to look at, one of which is useless to most players and will tell them they're missing badges they already have overall.
