### ISSUE TITLE
stone of shock does not trigger summoning trap

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#709]
I threw a stone of shock into a summoning trap room and nothing happened (except I got paralyzed).
![Screenshot_20210523-181159](https://user-images.githubusercontent.com/8593007/119278329-9028ba00-bbf2-11eb-951c-c657bee2221a.png)

**Comment by 00-Evan** [comment]
fixed in commit 082c2393cb0a633d07cba2f9019bf5a8c5e422e8
