### ISSUE TITLE
ShadowMelded bug

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#710]
I was shadowmelded but preparation activation dont show
Enemies sees me even when cloaked
Also when Im shadowmelded and use cloak afterwards. Cloak ends along shadowmelded when I exist room
![Screenshot_20210524-153045](https://user-images.githubusercontent.com/79112244/119313653-6204b200-bca6-11eb-8546-664a08585c73.png)
![Screenshot_20210524-153501](https://user-images.githubusercontent.com/79112244/119313662-6630cf80-bca6-11eb-8e11-18022091cdf7.png)

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Cloaking, shadowmelding, and preparation interact correctly from my testing. Was there anything else in particular you were doing here?

**Comment by Zrp200** [comment]
@Lonestick Looks like cloak ran out normally? I really don't see the bug here, and I haven't had any issues with shadowmelded either. 
Further, the only way that would be possible is if `Invisibility.dispel()` was called when you leave the room, and it does not.

**Comment by Lonestick** [comment]
Must have been a 1 time issue. I really dont know what happened. Ill just close this :)
