### ISSUE TITLE
Not any available path when descending to a new floor

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#711]
I remember reading your blog something about there should always be an available path to go when you visit a new floor.
There were none here
![Screenshot_20210524-052812](https://user-images.githubusercontent.com/47122537/119320282-cea19180-bc51-11eb-8c8e-f6a46dce0625.png)

**Comment by TheYsconator** [comment]
The note (in orange) does mention that the floor holds many secrets. Did you search all along the walls?

**Comment by ShinKeyKai** [comment]
I know you can search by walls to find doors and yes, it says that that floor contains many secrets, but I thought that you would always had to have an available path.
But it makes sense for this floor.

**Comment by TheYsconator** [comment]
Hmm I don't have time to do some extensive searching through the source code right now, but a quick search gave me the following snippet:

```java
//don't hide if it would make this room only accessible by hidden doors
//unless we're on a secrets depth
if (l.feeling != Level.Feeling.SECRETS && n.distance == Integer.MAX_VALUE){
	d.type = Room.Door.Type.UNLOCKED;
}
```

So I guess that it indeed is not a bug but intended behavior on Feeling.SECRETS floors.

**Comment by ShinKeyKai** [comment]
Yeah, you're right. I remember that almost every door in that floor was hidden so that's probably it. I will close this issue.
