### ISSUE TITLE
Improvised Projectiles talent doesn't work on Tengu

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#712]
When I threw an item at him he didn't get blinded and the talent went on cooldown still. I thought is was because is a boss but I tested it on the DM-300 and it worked on it.

![Screenshot_20210525-025310](https://user-images.githubusercontent.com/47122537/119458724-6c10ca00-bd13-11eb-9d47-bd3712a0863f.png)

**Comment by TheYsconator** [comment]
As per NewTengu.java (line 333), Tengu is immune to Blindness. DM300 on the other hand is not (NewDM300.java (lines 597-606)).

The one time in code where IMPROVISED_PROJECTILES is used (Item.java (line 557)), it adds the Blindness Buff. Thus, if there's no additional checks (I haven't browsed through the whole codebase), I guess it's working as intended on a technical level.

**Comment by 00-Evan** [comment]
As mentioned by Ysconator, this is working as intended. The talent is applying when used against Tengu, but Tengu is immune to blindness.

I agree that the game still as a few unintuitive cases of enemy debuff immunity, but I don't intent to remove this from tengu, or offer some form of functionality refund if an effect is used against an immune enemy. (e.g. wands don't refund charges when used against bosses while they're immune).

**Comment by ShinKeyKai** [comment]
@00-Evan I can understand Tengu being immune. Maybe a message could prompt when this happens, like when enemies dodge or resist to paralysis.
