### ISSUE TITLE
Translation text doesn't fit

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#714]
Since some translation gets kinda long (spanish things) the text goes out of the windows.

![Screenshot_20210528-234418](https://user-images.githubusercontent.com/47122537/120055867-2a339c80-c00f-11eb-9c5a-7b5f5b362d35.png)

**Comment by 00-Evan** [comment]
This is a translation issue, not a code one. Please consider adjusting the text on transifex, or opening an issue there if it has been reviewed.
