### ISSUE TITLE
Adrenaline buff doesn't affact the Spirit Hawk

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#715]
I threw an Adrenaline Dart to the spirit hawk and the hawk received adrenaline buff.

And then I directed it to move other place.

Its movement speed was 4 tile/turn due to +3 of 4-3(swift spirit) talent, so it's supposed to move 8 tile/turn because of adrenaline.

However, it still moved 4 tile/turn.

Is this intended?

**Comment by 00-Evan** [comment]
Fixed in BETA-1.3
