### ISSUE TITLE
Rejuvenating steps talent works while levitating

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#716]
What the title says
![Captura](https://user-images.githubusercontent.com/47122537/120082563-0bc6b300-c09a-11eb-8776-dffc3b95a3ff.PNG)

Unrelated to the topic but I went to the main menu and reload the game and the buffs order got inverted

**Comment by 00-Evan** [comment]
fixed in commit 3b2aced50c7f198579f05f2426a9519eacdd8608
