### ISSUE TITLE
Game freezes when defeate DK

### ISSUE THREAD

**Issue by Vovkiv** [00-Evan/shattered-pixel-dungeon#717]
In moment when i kill Dwarf King, the game just freezes

**Comment by Scupake** [comment]
Happened to me once right after I updated the game to the latest beta

**Comment by 00-Evan** [comment]
I'll need more information to be able to reproduce this. What items were you using, was the game entirely unresponsive or were you just unable to direct the hero? A screenshot would be helpful.

**Comment by Vovkiv** [comment]
![Screenshot_20210530-230444](https://user-images.githubusercontent.com/54743395/120118617-23866000-c19c-11eb-90b2-3933af1460a6.png)
Game was entirely unresponsive, it happens 2 time in row
And this happens at that exact moment, when DK dies

**Comment by 00-Evan** [comment]
If you're able to get the bug again, can you show me a screenshot at the moment the game freezes?

**Comment by 00-Evan** [comment]
I've made a change in BETA-1.3 that should hopefully fix this. Closing this issue for now, but feel free to comment if you run into this again in BETA-1.3

**Comment by Vovkiv** [comment]
Okay
For now, it's seems to be fixed
Freeze didn't happened again, so yeah, thanks
