### ISSUE TITLE
Shadow Blade self proc

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#718]
Just noticed my clone uses Unstable enchants on itself.
![Screenshot_20210530-142724](https://user-images.githubusercontent.com/79112244/120094555-961f1d80-c153-11eb-8abb-10108efef605.png)

**Comment by 00-Evan** [comment]
Looks like the code for this mechanic isn't quite working. Will fix this shortly.

**Comment by 00-Evan** [comment]
Fixed in BETA-1.3
