### ISSUE TITLE
Invisible grass after Tungu bossfight

### ISSUE THREAD

**Issue by SamuelS42** [00-Evan/shattered-pixel-dungeon#72]
When using a wand of regrowth after the Tengu bossfight on floor 10 grass
sprite does not seem to get drawn.

all effects as well as plants seem to work fine.

(v3.3b)
[link to video](http://filebin.ca/2UgTYt3QglK9/ice_video_20160125-143525.webm)

**Comment by 00-Evan** [comment]
Yup, this is because grass is a tile type and the custom visuals used there are drawn over tiles. At some point i'm going to change grass to be a plant just like the other ones, and then this will work, but atm it's low priority.

**Comment by SamuelS42** [comment]
That makes scene, Thanks!

**Comment by 00-Evan** [comment]
No need to close this, it is a genuine issue, just a low-priority one.

**Comment by 00-Evan** [comment]
Fixed as part of converting certain level visuals to a terrain tilemap, see class here:  https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/ui/TerrainFeaturesTilemap.java
