### ISSUE TITLE
Staff of warding can't use all its charges to sustain wards

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#721]
My staff of warding is +2 but I can only use 4 out of 6 charges to sustain wards.
If I recall correctly a +2 wand of warding has 4 charges so maybe the game is treating the staff as a wand?
![Captura](https://user-images.githubusercontent.com/47122537/120419117-2fa72480-c338-11eb-886c-a19bfdbc4360.PNG)

**Comment by 00-Evan** [comment]
This is working correctly. The staff gives wands +1 max charges, but does not increase their level, warding's ward limit is tied to its level.
