### ISSUE TITLE
Korean Translation Text Problem

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#722]
It's been 0.9.3 beta 1 too, there are some text output problem in Dirk and Wand of transfusion's descriptions.

In Dirk's desc, there's the text "기ㅍ수ㄱ이", but the original intention is "깊숙이".

Similar in wand of transfusion's desc. There is the text "매호ㄱ 되ㄴ", but the original intention is "매혹 된".

So I checked the Transifex site to see if the translations are wrong, However they were correctly translated.

I waited for the update(cuz there was a chance that It was just unupdated), and now the problem is still there.

Please check this problem.

※ I fixed the wand of transfusion's desc's text and unreviewed because of grammer(매혹 된 -> 매혹된, etc), but I did it after beta 1.3 update.

![IMG_20210602_135757.png](https://user-images.githubusercontent.com/76470428/120429020-a3384880-c3af-11eb-9ef5-31312479d2b4.png)

![IMG_20210602_135844.png](https://user-images.githubusercontent.com/76470428/120429027-a59aa280-c3af-11eb-8c5e-842a2b67aa81.png)

I wanted to upload unedited In-Game Screenshot but the error occurs now. :(

**Comment by 00-Evan** [comment]
Okay, so there are two separate issues here:

**The recently changed text for the Dirk in beta-1.3, and the wand of transfusion text from earlier in the beta:** It looks like you're using some combination characters for symbols like 깊 (using 기 plus ᇁ, rather than just the 깊 character). The game does not know how to handle this, and so displays an error symbol. Please revert these changes to the text.

**The text prior to the beta:** I reverted the text for the Dirk, and copied characters from transfusion's battlemage description (which uses single characters for these combined glyphs) and tested both on desktop and Android. It displays correctly for me in all cases:
![image](https://user-images.githubusercontent.com/2347603/120525692-6ae03c80-c3a6-11eb-8afd-0c0eb08b72e8.png)
![image](https://user-images.githubusercontent.com/2347603/120526511-45076780-c3a7-11eb-8309-7c0909e012b4.png)

The incorrect text you're showing in your screenshot might be device-specific, what device are you using?

**Comment by Hoto-Mocha** [comment]
I'm using Galaxy S9+, but It happens not only me. The screenshots from other player are continuously uploaded on korean community,  so I guess it is not device-specific problem.

Same problem is reported today in Warrior's Heroic Leap talent(impact wave).

The screenshot has not taken from me, but I have same problem, too.

![Screenshot_20210603-081449.jpg](https://user-images.githubusercontent.com/76470428/120563572-e0e6b100-c443-11eb-97cd-5488563ac50b.jpg)

[차ㄱ지 하ㄹ 때 -> 착지 할 때]

![Screenshot_20210603-082904.jpg](https://user-images.githubusercontent.com/76470428/120564398-c7466900-c445-11eb-83fa-ba47a05c1277.jpg)

**Comment by 00-Evan** [comment]
It looks like impact wave is also using these combining symbols, here's what I'm seeing when I try to view that talent on desktop:
![image](https://user-images.githubusercontent.com/2347603/120564801-b19b5a00-c3d9-11eb-97a3-2c20db0bf096.png)

To explain more fully, currently the text for this talent is using two glyphs, e.g: 하 (Hangul Syllable Ha, codepoint D558), and ᆯ (Hangul Jongseong Rieul, codepoint 11AF). It's then up to the game to combine them correctly, and it has no knowledge of how to handle this. The correct solution is to use one glyph: 할 (Hangul Syllable Ha, codepoint D560)

Replacing these combining glyphs with their single glyph equivalent causes impact wave's text to display correctly:
![image](https://user-images.githubusercontent.com/2347603/120565169-7c433c00-c3da-11eb-86a4-a4bf62925502.png)

**Comment by Hoto-Mocha** [comment]
Oh, you updated the game.
I don't know about 0.9.2(prior beta)'s text, maybe That will be written in the correct way.
This problem occurs in 0.9.3 beta 1~1.4, so now.

You told me to use a single unicode like "깊" not a ㄱ+ㅣ+ㅍ, but korean text inputting way is only ㄱ+ㅣ+ㅍ->깊 one.

![Screenshot_20210603-094320_GitHub.jpg](https://user-images.githubusercontent.com/76470428/120569066-26a97680-c450-11eb-805a-3b6811e89d92.jpg)

⬆️To help understanding, I put the screenshot of korean keyboard.

Or entering unicode pool to find "깊" text in the Pacific Ocean of texts. It's impossible and so inefficient, right?

I can't understand why this happens and the difference of 깊 and 깊(<- copied in your sentence).

All of korean translations are written by that way(combined symbols), so why this happens the specific words?

I don't know how to fix that texts.

**Comment by Hoto-Mocha** [comment]
So you mean, do not use the symbol 하(D558)+ㄹ(11AF) and use 할(D560) one instead, right?

But There's no korean typing way to input "할" pressing only 'ONE' key as you can see the korean keyboard's picture above. The only way(as long as we can) to input 할 is ㅎ+ㅏ+ㄹ.

So we wrote 할 in the way ㅎ+ㅏ+ㄹ, and the problem happened.

But the "근" right next to that is correctly written, not 그+ㄴ.
If the korean inputting way was completely wrong, so why that text is unscathed?



They seemed to be no apparent problem when we wrote the letters.

![Screenshot_20210603-100739_Chrome.jpg](https://user-images.githubusercontent.com/76470428/120570639-8a816e80-c453-11eb-9fe5-5f3bdcfc3ed3.jpg)

Can you be aware of the 할 in the picture was actually written in 하+ㄹ?

**Comment by 00-Evan** [comment]
I'm not sure what has caused the text input to change, it's possible it's something to do with your particular keyboard, or perhaps Transifex has changed something.

The good news is I've looked into it and I think I can detect and correct this on my end. I already run a bunch of automated checks on translated text to ensure it isn't using glyphs the game can't support, and it seems pretty easy to add these cases to those checks. I'll run those checks and manually correct the affected text in beta-1.5

**Comment by Hoto-Mocha** [comment]
That's a great news. Thank you so much, you're the best👍

**Comment by 00-Evan** [comment]
This should now be fixed as of the most recent release (v0.9.3-RC-1)
