### ISSUE TITLE
three suggestions

### ISSUE THREAD

**Issue by logicminimal** [00-Evan/shattered-pixel-dungeon#723]
**first one:** make the chat specify how much gold you have collected when you collect gold 

**second one:** more quickslots.one with ability to horizontally scroll would be great

**third one:** the gold is basically useless after the imp's shop, this needs to be fixed, also another idea would be to add mysterious salesmans in every few floors that sell from useless to useful stuff, a salesman should only sell max 2 items

**Comment by 00-Evan** [comment]
This is not a place to make game design suggestions.
