### ISSUE TITLE
Thief passing through traps without activating them

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#726]
As you can clearly see, the thief has just stolen from me and run away to an unexplored room. However, when I entered, I was presented with the following situation as shown below. This means, the thief ignored the activation of the trap and left me wondering. Is this intended?

![Screenshot_2021-04-02-09-08-47-99_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/121055460-f0f4ec80-c7c5-11eb-8f66-1245ea9523cc.jpg)

**Comment by 00-Evan** [comment]
This is working as intended, characters other than the hero do not trigger hidden traps.

**Comment by JumperPunk** [comment]
If something is hidden, it doesn't exist to mobs. They can't go through hidden doors, and they can go across hidden traps. Your even log shows you just noticed something. Probably what happened is the traps were not revealed when the thief went across, then you noticed them when you stepped into the door.
