### ISSUE TITLE
Giant champion Swarm of flies can split into 1-tile wide tunnels

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#727]
After the split they seem to get stuck where they are (they didn't chase me down the tunnel at least) although I wasn't able to test that much. Not game breaking or anything but it seems inconsistent with the standard behaviour of giant champions.

![Screenshot_20210607-171722](https://user-images.githubusercontent.com/45757529/121102303-7f637100-c7ba-11eb-8688-73aa1d1b8b7c.jpg)

**Comment by 00-Evan** [comment]
Looks like my attempted fix for this didn't quite stick, will try again in 0.9.3a

**Comment by 00-Evan** [comment]
fixed in commit e80bc2c1c0cf720960b9e5eb7831aec367bec62e
