### ISSUE TITLE
Spirit Hawk Fading causes game to crash

### ISSUE THREAD

**Issue by mazoned** [00-Evan/shattered-pixel-dungeon#728]
After 50 turns, the Spirit Hawk that was chasing and attacking a scorpio disappeared; however, it caused the game to try and load the next turn by it (similar to former fadeleaf bug). I was able to exit out of the game and upon reentry, the scorpio did its attack and the game continued on as normal.

Version: 0.9.3 (544)
Seed: 2415551148067
Challenge Mask: 0

In the photo, the scorpio is in the doorway.
![191782956_1403703080016250_180690731699735548_n](https://user-images.githubusercontent.com/85546563/121141481-fd4e6900-c808-11eb-908c-dfb4a08c230c.jpg)
![190680902_152260496890423_6483673269891944099_n](https://user-images.githubusercontent.com/85546563/121141494-00495980-c809-11eb-8631-95cf70e146ba.jpg)

**Comment by 00-Evan** [comment]
I'm not sure what you mean by this: "it caused the game to try and load the next turn by it"

How was the game crashed if you were able to exit out of it?

**Comment by mazoned** [comment]
My bad, it did not crash but rather the next turn was infinitely trying to load but could not until I closed the app and reopened it.

**Comment by 00-Evan** [comment]
I see, in that case, was the game totally frozen, or were you just unable to make actions?

**Comment by mazoned** [comment]
I had the ability to open menus and whatnot, but had no ability to move, attack, use any items, etc

**Comment by 00-Evan** [comment]
Okay, I'll see about reproducing and fixing this in v0.9.2a

**Comment by 00-Evan** [comment]
fixed in commit ef256e53ebc9123a2eb66b50157fc151f3b1949d
