### ISSUE TITLE
returning boomerang ends invisibility

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#729]
When the boomerang returns, invisibility is disrupted.  While it's clear that attacking ends invisibility, the boomerang return attack actually happened a couple of turns ago.  You can throw the boomerang, activate the cloak, and then invisibility ends when the boomerang returns, which is unexpected.

**Comment by 00-Evan** [comment]
This is working as intended. The returning boomerang is considered a ranged attack.

**Comment by LeahLuong** [comment]
I just encountered this & I'm unsure if Evan understands there are multiple cases for a returning boomerang.

1) Your hero catches the boomerang.
2) An enemy catches the boomerang.
3) No 1 catches the boomerang.

It makes sense that, in the 1st case, your hero's position is revealed by the returning weapon. It doesn't make sense that invisibility is interrupted in the 2nd & 3rd cases.

I believe the latest patch notes contained an accuracy fix specifically for returning boomerangs. This would seem to imply there's room in the code for making a fix for distinctions like the 1 highlighted by this issue.
