### ISSUE TITLE
Message duplication after loading game

### ISSUE THREAD

**Issue by Zap0** [00-Evan/shattered-pixel-dungeon#73]
I just came across a weird issue with messages appearing multiple times after the game had been reopened after using other applications. I noticed the game was putting me back in the main menu and requiring to load the game anew as opposed to saving the state and simply reopening ingame. It seemed for every time I reloaded the game would repeat any new message it showed once more. Reload -> messages are shown twice, reload again -> every message appears three times etc.

After properly closing the application and reopening I've been unable to reproduce this behavior.

[Screenies](http://imgur.com/a/YbWEy)

I'm using 0.3.3b on android 4.4.2

**Comment by 00-Evan** [comment]
I've been aware of this bug I think you've just provided a crucial detail.

I haven't been able to reproduce this but your details should help with fixing this issue immensely. Sounds like the auto-transition back to the title screen isn't causing the original log to clean itself up properly. Should be able to get this fixed next release.

**Comment by 00-Evan** [comment]
The source for this fix has now been released.

relevant commit: 108e466516a06dc0d3e0743df99f454161f2baf0
