### ISSUE TITLE
On-hit effects (e.g. vampiric) can trigger on inactive pylons

### ISSUE THREAD

**Issue by markozajc** [00-Evan/shattered-pixel-dungeon#730]
Striking an invulnerable entity (such as the power pylons on on L15) with a vampiric weapon heals the player, which is likely unintentional.
This seems to only affect thrown weapons (especially the spirit bow) as melee weapons can't be used to strike invulnerable entities.

**Comment by 00-Evan** [comment]
There is a bug here, but your description is incorrect.

Invulnerable enemies cause attacking logic to cancel out before any on-hit effects are resolved. Pylons are not considered invulnerable when they are inactive though, they simply force all incoming damage to 0. They should use standard invulnerability behavior.

**Comment by markozajc** [comment]
I see, thanks for clarification.

**Comment by 00-Evan** [comment]
fixed in commit 0fb5c4a11f3cb9fef8b7d3268395ec9b4a18c6bc
