### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#731]
The game stopped in Yog boss fight.
And when I shut down the game and play SPD again, the floor resetted.

![Screenshot_20210610-155100_Video Player.jpg](https://user-images.githubusercontent.com/76470428/121478159-ac569480-ca03-11eb-8548-31f4f0ef9e82.jpg)

Game version : 0.9.3
Device : Galaxy S9+
Equipments :
![Screenshot_20210610-155011.jpg](https://user-images.githubusercontent.com/76470428/121478060-8df09900-ca03-11eb-940f-df3f7cabdb62.jpg)

https://youtu.be/emaHZ5ooX74
⬆️ Video for reference only

**Comment by 00-Evan** [comment]
This is a known freezing issue that I intend to resolve in v0.9.3a.

**Comment by 00-Evan** [comment]
fixed in commit 0a9d0ba919efe021d2720fbac4fd448a116d1d7b
