### ISSUE TITLE
Ratforcements attack each other on floor return

### ISSUE THREAD

**Issue by NervusTerminalis** [00-Evan/shattered-pixel-dungeon#734]
Steps to reproduce with v0.9.3:

> 1. Use Ratforcements to spawn > 1 allied marsupual rats adjacent to each other.
> 2. Exit game and return to the session or leave floor and return.

For one one or more turns, previously spawned allied rats will be alerted to each other and will attack each other if adjacent. During that time, rats are not presented as allied via player interaction. After one or more turns, the rats return to allied status.

**Comment by 00-Evan** [comment]
fixed in commit fc6b08e2f14ee08429c108469282398177a16f15
