### ISSUE TITLE
Crash after using regrowth bomb with prismatic guard

### ISSUE THREAD

**Issue by Orello06** [00-Evan/shattered-pixel-dungeon#735]
I tried attaching a screenshot, hope it works.

I happen to use a regrowth bomb to heal my prismatic guard. From the frame in the screenshot, I can still attack enemies, throw items or move, and enemies can still attack me, but immediately after that the game crashes everytime. When I opened the save again, it went back to the same position as shown in the screenshot.

I noticed the Prismatic Guard never moves each time, so I think that might be the problem. I can't try to move outside with the chains since I'm rooted. I have a set beacon though, might try that if that can help you.
![Screenshot_2021-06-14-18-19-24-02_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/85877429/121885680-9d8f1b00-cd3e-11eb-88d8-38b71e241209.jpg)

**Comment by 00-Evan** [comment]
It looks like the prismatic image has lost its reference to the hero. There were some bugs relating to this from before v0.9.3, is that run from before the update?

**Comment by 00-Evan** [comment]
I suppose I'll just add some safety checks to prevent crashes in these cases...

**Comment by 00-Evan** [comment]
fixed in commit 57d9f7ffad837dd29e38c975e7daa8f2cc581c91
