### ISSUE TITLE
About Ratmogrify

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#736]
![1623724044696_1623724044695_2.gif](https://user-images.githubusercontent.com/76470428/121984341-c27e9f00-cdcd-11eb-8204-7cfe167250e9.gif)

![1623724083833_1623724083833_2.gif](https://user-images.githubusercontent.com/76470428/121984354-c9a5ad00-cdcd-11eb-8736-267459ffbaec.gif)

This is actually 0.9.3(not 0.9.3a)'s video, but I think it still does(cuz there was no mention in 0.9.3a's bug fix).

Ratmogrified flying enemy does not fall into pit immediately.

Is this a bug, or intended?

**Comment by 00-Evan** [comment]
It's unintended, rats should fall into pits in these cases.

**Comment by 00-Evan** [comment]
fixed in commit 62de2e90e2b89e0f298969c68159db3baded6376
