### ISSUE TITLE
Issue with pitfall trap and the badge

### ISSUE THREAD

**Issue by skbzk** [00-Evan/shattered-pixel-dungeon#737]
It is possible to earn "Level completed without killing any monsters" badge while actually killing monsters.
To reproduce:
1. Step on the pitfall trap and fall down a floor before killing any monsters on this floor.
2. Climb the stairs to the floor you fell from (Scroll of Passage and Beacon of returning might also work but it has to be checked).
3. Complete the level as usual with killing monsters.
4. Descend to the floor you fell onto previously (again, Beacon of Returning, another pitfall trap or simply falling down a chasm might work).
5. After descending you should get the badge.

**Comment by 00-Evan** [comment]
You actually are earning the badge on step 1, the game simply isn't displaying it until step 5. I'll correct this so falling can trigger the badge's display.

**Comment by 00-Evan** [comment]
fixed in commit 5a733d72e8a4535b2db1569c8a0a97eb7725759c
