### ISSUE TITLE
On new floor, monster or item spawned in on top of hidden trap and immediately triggered it

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#741]
I went down some stairs, and immediately got the message "A hidden burning trap activates!". From the look of the next room, it looks like either the DM-100 or the Sacrificial Sword under it triggered the hidden trap.

![Screenshot_20210621-095608](https://user-images.githubusercontent.com/162737/122800050-54c3ee80-d277-11eb-8319-bcd4b1bf528b.png)

**Comment by 00-Evan** [comment]
This looks like it's working correctly, falling items can trigger traps.

**Comment by joshtriplett** [comment]
Ah, I see. Yes, I did drop an item down a pit from the floor above. I guess it was sheer luck that it happened to land on the same space as a monster *and* a hidden trap.

Thanks for the diagnosis. I primarily reported this because there had been issues with trap generation in the past, but yeah, this doesn't seem like a problem.
