### ISSUE TITLE
Kinetic enchantment on gnoll brute

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#744]
The description of the kinetic enchantment states that any excess of force from a killing blow will be stored and then applied on the next successful attack. Now, the gnoll brute enters in a rage state when they HP reaches 0, ignoring death for a brief time. That implies that they are still alive in that state so any excess of force from an attack that mades the gnoll HP reach 0 before they go on rage should not be stored.

Since any other interaction with the gnoll occurs after the rage (EXP gain, combo related talents, etc) I find it inconsistent for the kinetic enchantment to proc before the rage.

**Comment by 00-Evan** [comment]
Kinetic's exact logic if that the incoming damage is greater than an enemy's remaining HP + shielding, that excess damage is conserved. This is simplified in the description slightly for easier reading. I don't have any issue with how the enchant behaves against brutes, seeing as the excess conserved damage isn't being applied to the brute.
