### ISSUE TITLE
Soul mark on gnoll brute

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#745]
When the gnoll brute is marked with the warlock's soul mark and enters in brute rage, dealing damage to them won't heal you.
I assume that when they are in rage they are still alive so dealing damage to them should heal you.

**Comment by 00-Evan** [comment]
It looks like soul mark healing sometimes processes incorrectly if a character is at or near 0 hp and has shielding, will correct this.

**Comment by 00-Evan** [comment]
fixed in commit e984595c3237dc48d29ac2bef3ecbc4931622cb8
