### ISSUE TITLE
[Minor Bug] Badges sprites issue(s)

### ISSUE THREAD

**Issue by ghost** [00-Evan/shattered-pixel-dungeon#746]
Hello,

 •Sprites of badges "Level 12 reached" and "Level 18 reached" are swapped, we get the Tier-3 badge with level 12 and Tier-2 badge with level 18.

 •The Warrior badge is in the spritesheet but unavailable, I think that a tutorial in a fixed map (0th floor) can be a good idea for the game and the Warrior badge can be earned at the end of the tutorial. This can be a good way to extend the boss-slain-badges serie by removing the 4 badges n-th boss slain and instead evolve the Bronze Warrior/Mage/Rogue/Huntress badge to a Silver one when the boss2 is defeated with this character, a Gold one when the boss4 is defeated and a Diamond one when Happy End is reached.

**Comment by 00-Evan** [comment]
will fix the sprite swapping

As for the warrior badge, that's largely there are a placeholder as I made one for the other heroes. I am considering improvements to the new player experience but am not looking for specific suggestions on it.

**Comment by Luna4221** [comment]
•This 3rd point is subjective but I think badges with the same form as happy end looks better without the 2 extremums pixels at the top of the 2 diagonals. I attach a corrected spritesheet with a fix for the swapping, the subjective change and the form of the all-deaths badge that can be the same as others deaths badges to be more easy to see it.

![badges corrected](https://user-images.githubusercontent.com/86429567/123319802-34bf5400-d531-11eb-87a8-7e624727902a.png)

**Comment by 00-Evan** [comment]
Sorry but I don't accept code/asset contributions.

**Comment by 00-Evan** [comment]
fixed in commit 222c0046b118dfdc0c9798870a96fef45f68df03
