### ISSUE TITLE
please ask if I can pull to this warehouse

### ISSUE THREAD

**Issue by PixelMonkeyPro** [00-Evan/shattered-pixel-dungeon#749]
Hello, Evan, I’m glad you brought me a great game experience, in the process of playing, I often confused about the shortcut bar is not enough, so I tried to modify the code, please ask if I can pull to this warehouse, thank you.

**Comment by 00-Evan** [comment]
By "pull to this warehouse" do you mean "fork this repository"? If so, then of course you are allowed to, the game is open source after all. If you mean "make a pull request" though, then I'm afraid I don't accept code contributions.
