### ISSUE TITLE
Disappearance of an item

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#75]
There was a chilling trap with a lure of N of gold. After revealing the trap and throwing a gold key into it, the key disappeared, leaving only gold to be collected.

Also (not re-checked in the most recent version) burning a stack of M mysterious meats makes 1 chargrilled meat instead of M.

**Comment by 00-Evan** [comment]
I've just attempted to reproduce both of these bugs with no luck, can you give me any more information? They may only happen in very specific circumstances.

**Comment by vi** [comment]
About the trapped gold key the sequence is this:

1. Upon entering a new room, observe the gold coints item;
2. Try to get the coints - stopped by noticing the chilling trap on the same tile;
3. Looking for information about the cell - it shows gold coin's information, but not the trap's;
4. Backtracking a bit, one tile;
5. Throwing a golden key into that tile;
6. Trap disappears;
7. Collecting gold, frowning when no other items on that tile appear to be collectable (golden key blends in with gold coins? Hunteress is a blondie and thinks that it's just another coin?);
8. No way of accessing ring chest anymore.

Fire gluing together mystery meats into one was probably for some older version of the program.

**Comment by 00-Evan** [comment]
I'm willing to bet that what you ran into was a teleportation trap, not a chilling trap. If teleportation traps are triggered by an item, that item will get teleported. So in this case by throwing the key on the trap, that key was warped somewhere else in the level, which is why you didn't see it when you went to pick it up.

**Comment by vi** [comment]
1. Why didn't it teleported the gold as well?
2. Teleportation trap is supposed to place the item at some location on current floor. Was it just unlucky enough that the key was placed behind the door?

Maybe I inspected the trap after the event and saw "Inactive chilling trap", maybe not (I don't remember now), but it was coloured bluish.

**Comment by 00-Evan** [comment]
The trap teleports what triggered it, not what items are at its location, so in this case it teleports the key, which triggered it, but not the gold, which just happened to be there. And blue dots is the color of teleportation, chilling is very light-white blue.

The key shouldn't have been placed inside of a locked room, it may have appeared inside of a hidden room though.
