### ISSUE TITLE
Bug with Curse and Treasure chest

### ISSUE THREAD

**Issue by FDawnXingLin** [00-Evan/shattered-pixel-dungeon#750]
# There are two bugs in Ver 0.9.3c
## 2. When using the upgrade scroll to upgrade unidentified cursed equipment multiple times, the equipment attribute panel will have both "cursed" and "uncursed" attributes at the same time. When this equipment is used, the curse will still exist.

**Comment by 00-Evan** [comment]
1. These are crystal mimics, this is intentional

2. Cursed weapons can have their curse be weakened by upgrades. This means the item won't be bound to you when its equipped, but it does still have the curse enchantment.
