### ISSUE TITLE
You can see open doors, even out of sight. 

### ISSUE THREAD

**Issue by santids** [00-Evan/shattered-pixel-dungeon#751]
I've noticed you can see when a monster opens a door even if it's out of sight.

**Comment by protective1** [comment]
This is a duplicate of issue #732

**Comment by santids** [comment]
Sorry, I'll close this. However, doesn't seem really realistic to be able to spot things out of sight.

**Comment by protective1** [comment]
I guess I think of it as being able to "hear" the door open/close from a distance.  Maybe that's not exactly right but it helps me justify it in my head.
