### ISSUE TITLE
Curse of overgrowth and warden

### ISSUE THREAD

**Issue by namark** [00-Evan/shattered-pixel-dungeon#752]
https://github.com/00-Evan/shattered-pixel-dungeon/blob/eba806ef561921b86637cf26818e095556edec0d/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/armor/curses/Overgrowth.java#L46

I tried this expecting majestic synergy and was thoroughly heartbroken ;( 
The history suggest that the limitation was placed there along with the warden buffs, so maybe never play tested? Is it really that broken? The armor doesn't seem to proc very often and I tried a warden with full set of seed buffs otherwise and she seems weaker than say an upgraded staff of warding.

**Comment by 00-Evan** [comment]
Consider that the warden subclasses makes all the various harmful plant effects into positive ones, this would mean that uniquely for the warden one of the game's curses would instead be a pretty powerful glyph. This completely defeats the point of overgrowth being a curse. Overgrowth is already one of the game's most forgiving curses as it is.

**Comment by namark** [comment]
> warden subclasses makes all the various harmful plant effects into positive ones

Yes! That's that's exactly what I was aiming for! Are you saying it was tested and proven to be absolute god mode for warden? Cause if not I might give it a try myself and get back to you.

>This completely defeats the point of overgrowth being a curse

Only for warden when you get there. In early game and for all the other builds for the whole game it's still a mild curse.

To clarify my point a bit, I think it would be a pretty cool game mechanic to allow this. Being able to circumstantially and indirectly turn something that appears to be harmful on it's head and get something good out of it can be very rewarding for players who discover it in game.  
It would also be more thematically consistent. I read the overgrowth description, and I imagine an armor covered in greenery with actual flowers growing on it that get squashed every once in a while in combat. Logically it seems that warden should benefit from that, otherwise if it's meant to be just a random buff/debuff, thematically tying it to the plants only serves to confuse the warden player IMHO.

**Comment by LeahLuong** [comment]
Totally agree w/ namark on this 1. I was led to try this synergy when the chance arose & was disappointed. Curses like metabolism & multiplicity can be turned into blessings w/ the right build & I think overgrowth should be the same. It's not like wardens have the issue of running out of seeds. I don't think random, occasional procs would be OP for a subclass which is arguably the strongest of all, especially when there are more broken things you can do w/ the enchant slot on armor.
