### ISSUE TITLE
Sniper has incorrect FoV with magial sight

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#753]
Normally, Sniper's FoV is increased by 25% x farsight lvl. However, if the Sniper has magical sight, her FoV is increased by 50% regardless of talents (https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/Level.java#L1096). This is probably an "oversight".

**Comment by 00-Evan** [comment]
fixed in commit 967a7f89c9603b0e588fd7835b61f29362ad0678
