### ISSUE TITLE
Wand of transfution on skeleton's dying explosion

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#754]
When you kill a skeleton with a wand of transfusion, the explosion from the skeleton dying occurs first than the wand's shielding. And I feel it should be the other way around so you could mitigate the damage from the explosion.

Here I have 37 HP
![Screenshot_20210721-012759](https://user-images.githubusercontent.com/47122537/126431691-5b06a963-d5e6-4af5-b41b-f640487f5b0e.png)

I kill the skeleton with the wand and I receive the damage first and then get shielding
![Screenshot_20210721-012803](https://user-images.githubusercontent.com/47122537/126431829-5f7940fe-e9d6-47e0-8c79-bd9ce5bc36c3.png)

**Comment by 00-Evan** [comment]
fixed in commit abea48afc35b3a1c514da8a3ddc68978671bcaf1
