### ISSUE TITLE
Enhancement: Display Badges Online

### ISSUE THREAD

**Issue by dulsi** [00-Evan/shattered-pixel-dungeon#755]
Many platforms like Steam and Xbox allow people to display their achievements online for friends. There is an open source game achievement system I've been developing called Gamerzilla. I did a poor java integration to try it out. It needs more work. You can see it in my fork of shattered-pixel-dungeon. You can see my achievements on my test site:

[Gamerzilla Test Site](http://108.49.106.217/)

**Comment by 00-Evan** [comment]
Good luck with your project, but I am not interested in any external integrations or pull requests at this time.

If I add this sort of functionality it will almost certainly be tied to steam, google play games, or similar achievement services offered by the platforms Shattered already uses. Naturally, connections to these closed source services will never be needed to run the game.
