### ISSUE TITLE
Using Curse Infusion on wands will reset max charges after a save/reload

### ISSUE THREAD

**Issue by LogicalityDog** [00-Evan/shattered-pixel-dungeon#756]
With the talents "Shield Battery" and way too many excess wands sometimes, it's become useful to use curse infusion on extra wands to just have them in my back pocket as quick "oh heck" buttons. It turns out that for some reason, saving and re-loading the game after infusing them results in their max charges being reset back down (from four to three, in the case of a lvl1 curse infused magic missile). See picture below for issue, happened before this last update too but I forgot to post about it here, just did it on reddit.

![ShatteredPixel_CursedWandFlub_27jul2021](https://user-images.githubusercontent.com/88037788/127153346-7bcaa363-e9a8-4a95-be05-3044a0ffac21.jpg)

**Comment by 00-Evan** [comment]
fixed in commit 8328962579b83c7d41542d0092c2e8387ae20026
