### ISSUE TITLE
No ESC Key Support On Chrmoebook

### ISSUE THREAD

**Issue by Taemon-Coolz** [00-Evan/shattered-pixel-dungeon#757]
I would like to use the ESC key instead of the backspace key, but when I try to change the key bindings, it shows up as 'null' instead of 'Escape' and doesn't save.

**Comment by 00-Evan** [comment]
There's a good chance this will be incidentally resolved in v0.9.4, which includes updates to the game's libraries. I'm going to mark this as fixed in development for now, please let me know if you still run into it in the updating beta.

**Comment by 00-Evan** [comment]
This should now be fixed in v1.0.0 due to a libGDX update. Please let me know if you are still getting this problem.

Relevant commit: 9b63eb5e090c2036d915913039b80389cc7c7dbd
