### ISSUE TITLE
Wand of corruption doesn't wake up statue

### ISSUE THREAD

**Issue by santids** [00-Evan/shattered-pixel-dungeon#758]
Wand of corruption doesn't wake up statue. I'm using version v0.9.3c in Android

**Comment by 00-Evan** [comment]
Do you mean that debuffs from the wand of corruption do not alert the statue?

**Comment by santids** [comment]
Exactly

**Comment by 00-Evan** [comment]
Fixed in commit 475d70284caf8ebb09f20ed9ee71ef5c3c3cf755
