### ISSUE TITLE
Some ideas for more enemy and room varieties 

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#759]
Here are some ideas for more enemy and room variety.

Red Viper: Variant of Snake with 8 HP, which applys the poison debuff with its melee attack. 50 % chance to drop a seed.
Blood Bat: Has 45 HP and a small chance to apply the Bleeding debuff with its melee attack. Always drops a Potion of Shielding (limited to 3 per run).
Green Shaman: heals other mobs with its ranged attack, only attacking the player in a melee battle.
Specter: Purple variation of the Wraith which comes with a ranged magic bolt attack. No different stats and no extra drops. Sometimes spawned instead of a regular one. 

Cursed room: Room with money and/or an uncursed item with a high rate to be +1 or +2, but it costs HP to enter the room. Similar to the trap rooms, but not avoidable with Potion of Levitation
Secret shop: A secret shop which also may sell exotic scrolls, potions and enchanted weapons
Rat Queenʼs Room: On some days like Motherʼs Day (second Sunday in May) and International Women’s Day (March 8) the Rat Queen spawns instead of the Rat King. 1 - 3 chests contain a berry instead of money.
Colored locked room and/or colored chest
Only appears on the first three floors of a section. Can be opened by a colored key which is dropped by a champion which will spawn in a deeper floor of the same section (guaranteed on floor 4, 9, 14 or 19 if not spawned on an earlier floor).

**Comment by 00-Evan** [comment]
Thanks for the suggestions, unfortunately I don't accept contributions via github, this is mainly a place to report technical issues with the game, or suggest technical enhancements.
