### ISSUE TITLE
Game sometimes crashes

### ISSUE THREAD

**Issue by qoheniac** [00-Evan/shattered-pixel-dungeon#760]
The game sometimes randomly crashes and when I open it again the last saved state is when I entered the floor standing at the ledder. So all progress on the current floor is lost. This doesn't happen too often (maybe every ten floors on average) but still is a bit annoying. Unfortunately, I have no idea what causes it and the only thing I could find in the logs was this:

```
[DEBUG] pid: 32102, tid: 32123, name: SHPD Render Thr  >>> com.shatteredpixel.shatteredpixeldungeon <<<
```

Any ideas how to get more information about the cause are welcome. I'm playing version 0.9.3c on Android 9 without Gapps.

**Comment by 00-Evan** [comment]
Unfortunately there's nothing I can do about this without some actual information about what caused the crash. That log entry looks like it should have been larger but is cut off, in its current state it says basically nothing about the crash. Feel free to re-open this if you're able to get any more info, also consider trying the recently released beta for v0.9.4, which may fix your issue: https://github.com/00-Evan/shattered-pixel-dungeon/releases
