### ISSUE TITLE
Falling while invulnerable w/ ankh crashes game (0.9.4 beta 1)

### ISSUE THREAD

**Issue by jusrombawa** [00-Evan/shattered-pixel-dungeon#769]
Hi, I found a bug while playing a run on the latest beta (0.9.4-beta-1).

I jumped down a chasm, and it triggered a blessed ankh. I immediately jumped off again (with invulnerability), and the game crashed. Loading a save crashes the game again. The save file seems to be intact (still recognized as whichever class/level I was) but hard-locked. Starting a new run works fine.

I'm not sure how to get crash logs to send here, but feel free to follow up if you need any further info. Thanks.

**Comment by 00-Evan** [comment]
fixed in BETA-2
