### ISSUE TITLE
"Leafs" from staff of regrowth visible in empty quicksort cell even after it has been knocked off by monk

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#77]
Blazing Staff of Regrowth was available though quicksrt slot, showing sparkling green animation.
But after the staff was knocked off my a dwarf monk and quicksort's slot became empty, the frozen frame of that animation remained, as if some little leaves from the staff remained in mage's hand after losing it.

**Comment by 00-Evan** [comment]
fixed in commit 3de8225f9bf5c67a972df4526a0f400b11dd87eb along with other changes
