### ISSUE TITLE
Cant pass through

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#770]
I could go in with levitation or blink stones but too pricey
![Screenshot_20210812-115520](https://user-images.githubusercontent.com/79112244/129136266-57e57b0d-6c8c-4fee-a39a-5826a0608df7.png)

**Comment by 00-Evan** [comment]
Interesting.

This is behavior that has already existed for other unbreakable traps, but gateways are the first ones which make it genuinely impossible to get through a hallway. I'll see about tweaking this.

**Comment by 00-Evan** [comment]
fixed in BETA-2
