### ISSUE TITLE
0.9.4 Beta Resizing window on desktop causes the ankh resurrection menu to appear [Linux Desktop]

### ISSUE THREAD

**Issue by jacekjarosz55** [00-Evan/shattered-pixel-dungeon#771]
Steps to reproduce:
1. Start a game with any character ( on my example it was the Huntress )
2. Die in the game
3. Resize the window

![image](https://user-images.githubusercontent.com/72438686/129159220-2386d43a-bcae-4a17-b631-c657ba7b9ddc.png)
the shadow shows that there is a lot of windows on top of each other

Tested on Arch Linux with GNOME Desktop Environment on java 16 (openjdk)

**Comment by 00-Evan** [comment]
This was fixed in BETA-2
