### ISSUE TITLE
Crash after trying to pick up a lost bag.

### ISSUE THREAD

**Issue by Scupake** [00-Evan/shattered-pixel-dungeon#772]
I died in a boss room and I had an ankh, after I respawned I had all my items on me and there was a lost bag there, I tried to pick it up and the game crashed.

**Comment by 00-Evan** [comment]
This should be fixed very soon in beta-3, your run will be playable after that. Sorry for the trouble!

**Comment by 00-Evan** [comment]
fixed in BETA-2
