### ISSUE TITLE
Issues with rankings screen

### ISSUE THREAD

**Issue by Infiaria** [00-Evan/shattered-pixel-dungeon#773]
![image](https://user-images.githubusercontent.com/32031865/129384820-9acd2c70-34e6-4838-838c-b100e8c47dd6.png)

There are two issues in this picture:

+ It appears that using an unblessed ankh prematurely ranks the game before it finishes (seen in the screenshot as the No. 3 rank). Additionally, this causes the "games played" to increment incorrectly as well.
+ More obviously, death by a ratmogrified enemy does not display properly (It is already bad to admit being killed by one. I forgot I had low health).

**Comment by 00-Evan** [comment]
fixed in BETA-4
