### ISSUE TITLE
Throwing unidentified potions out of FOV doesn't identifies them

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#774]
This might be intended but doesn't sounds logical for the harmful potions since their effects spread to your FOV even if you throw them out of it.

In this case happened with a Potion of Liquid Flame, it was unidentified but I knew it was that potion so I threw it to burn a barricade. I threw it from far away because the gound was flammable and I wanted to burn some enemies as well.
Even though everything burnt, the potion wasn't identified.

The exact position from where I threw the potion and the barricade position.
![Captura1](https://user-images.githubusercontent.com/47122537/129400120-727fd638-ae44-48b4-83ba-84c3409bca44.PNG)

![Captura2](https://user-images.githubusercontent.com/47122537/129400137-ea7bedcb-fdaa-4899-b7bb-53ce8b1f2b03.PNG)

**Comment by 00-Evan** [comment]
This is intended, you didn't see the potion shatter.
