### ISSUE TITLE
Game froze while Ascending to the a floor.

### ISSUE THREAD

**Issue by Scupake** [00-Evan/shattered-pixel-dungeon#775]
I am running Androird 4.4.2. The animation kept playing. After I re-stared the game I found myself on the stairs as if I just ascended.

**Comment by 00-Evan** [comment]
I'll need more information than this, such as screenshots or descriptions of what was happening when the game froze.

**Comment by 00-Evan** [comment]
I'm closing this issue as no further info has been given. Feel free to comment if you have any more details and I'll re-open it.
