### ISSUE TITLE
Lock room buggy feature with scroll of transportation

### ISSUE THREAD

**Issue by KelvinHong** [00-Evan/shattered-pixel-dungeon#776]
Hi Evan, this is a buggy feature I found, maybe not of the v0.9.4 beta version, but have existed a long time.

When I try to use unidentified scrolls in the locked room before getting the key and unlocking the door, I accidentally used up a scroll of transportation, then it transport me out of the locked room. Is it possible to make it impossible to use the SoT in the locked room? Because the ability to transport beyond locked room is pretty problematic, and I wonder is it equally likely to transport into a locked room from outside? It might be a bigger problem as well. 

![ss1](https://user-images.githubusercontent.com/34021827/129497877-12065fef-df0c-4381-82a2-4e9037239797.jpg)
![ss2](https://user-images.githubusercontent.com/34021827/129497881-0b1b5cea-c891-4e5d-b258-bef769670908.jpg)

**Comment by KelvinHong** [comment]
If you're interested why I did that, I tried to cleanse the curse of the thieve band I found in the locked room: https://www.reddit.com/r/PixelDungeon/comments/p4kc6d/pov_jump_into_a_locked_room_got_cursed_thieve/

**Comment by TheYsconator** [comment]
Why would this behavior be buggy? I mean; you encounter this once (and either jump down once again or just leave the items). Next time(s) you know not to read scrolls if you haven't picked up the key yet. (Same goes for reading scrolls in the shop, I believe.)

Trying to prevent that would make the game a bit too hand-holdy - in my opinion. (I mean; even if you read the scrolls in the room after having picked up all the items you'll be good.)

(Unrelated, but I believe that a wreath spawning is an indication of an item being cursed.)

**Comment by 00-Evan** [comment]
As mentioned, this is intentional. You are able to get back to the room by going back up to the previous depth and dropping again. Scrolls of teleportation aren't able to put you inside of locked rooms.
