### ISSUE TITLE
Impossible Win Condition

### ISSUE THREAD

**Issue by BennyBeechee** [00-Evan/shattered-pixel-dungeon#778]
With the implementation of the new ankh system, you can get permanently trapped in a room with no way out but to erase the file, starve, or suicide. This is not a bug, per se, but a consequence of the new revival system. If you use an unblessed ankh to revive in the dungeon and while searching for your dropped items, fall/jump into the chasm with the well, you are unable to pick up the items from the dead skeleton on the floor you drop down to in order to get the necessary key to exit the room and head back up the stairs to retrieve your items. Therefore you are permanently trapped alone in the room and left to die. Maybe that's how the original skeleton got there in the first place. I don't think you intended this situation, but if you did, feel free to ignore this issue.

**Comment by 00-Evan** [comment]
I'm fine with this, it's basically impossible to do this accidentally and the key being stuck at the bottom of the item stack is necessary as it forces you to fight the wraith that may spawn.
