### ISSUE TITLE
Burning flying enemies set terrain on fire

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#779]
This is inconsistent at the least since they can't get on fire if they fly above a tile that is already on fire nor can they put the fire away flying over water if they are already burning. But they can set terrain on fire if they fly above it while burning.

I may be wrong in my first statement, I haven't seen a flying enemy fly over a burning tile in a long time.

![Screenshot_20210817-115257](https://user-images.githubusercontent.com/47122537/129752354-ffe2e8a8-3f10-47a8-8188-9b8eb703a89a.png)

**Comment by 00-Evan** [comment]
Fire does ignite flying enemies. I'm fine with this interaction, as fire can leap short distances (especially when something is engulfed in flame) but you would need to actually get down into the water to put yourself out.
