### ISSUE TITLE
Ankh's menu failed to appear after resuming the application from background

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#78]
> Yes, I will fight
> No, I give up

Taken a third option: decide later.

But when that "later" came, it offered no choice.

**Comment by 00-Evan** [comment]
This is perhaps a bit weird but technically correct.

To avoid save-scumming, the game is immediately deleted the second the player dies. In the case of the ankh, pressing 'yes' will restore the game files, otherwise they are gone. If you close the app, that is the equivalent of pressing no.

**Comment by vi** [comment]
In this case the menu should show a warning like "Minimizing the game may be equivalent to 'no' answer".

There is no way to avoid save scrumming, especially by root-wielding user in open source game, so it is not reasonable to trade UX for additional protection against save scrumming.

Save state may include explicit variable about this menu. Or restoring a savestate where health = 0, but there is unblessed Ankh in backpack should immediately pop up the menu.
