### ISSUE TITLE
Corrupted Ratmogrified entities becoming uncorrupted

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#781]
**Reproduce steps**:

1. Ratmogrify any enemy
2. Within the 6-turn window (as introduced in 1.0.0) corrupt the enemy
3. After the 6th turn it turns into it's previous form

**Comment by 00-Evan** [comment]
This is intended. Ratmogrified enemies do not have any of the properties of their original form, and vice-versa.
