### ISSUE TITLE
Change CFBundleDisplayName to “Shattered Pixel” on iOS

### ISSUE THREAD

**Issue by Taxyovio** [00-Evan/shattered-pixel-dungeon#782]
Currently the full display name is truncated into ellipsis on the home screen as “ShatterPixelD…”. Depending on device and text size, it might display a few more characters. But in no scenario it would display the full bundle name. I think it’s better to shorten it so this ugly truncation doesn’t happen.

**Comment by 00-Evan** [comment]
Please use this place to report technical issues or feature requests for the game. This is not the place for subjective design suggestions.

**Comment by Taxyovio** [comment]
> Please use this place to report technical issues or feature requests for the game. This is not the place for subjective design suggestions.

Then you should say so in the readme. This is totally waste of time for people passionate people who are trying to help.
