### ISSUE TITLE
Gateway trap target field should be visible after activation

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#788]
After the activation of a gateway trap, it would be nice when the target field  is marked with a special tile (like an inactive trap). It also should be keep care that there is never more than one gateway trap on a floor to avoid confusion where which trap goes and also to prevent endless loops (even if that is extremely unlikely).

**Comment by 00-Evan** [comment]
I feel like this would cause visual clutter, I'm also fine with the player being expected to remember where a gateway trap goes. Multiple gateway traps can be on the same floor and it's impossible for one to point at another.
