### ISSUE TITLE
Enhancement: Add date to to the rankings

### ISSUE THREAD

**Issue by mkldn** [00-Evan/shattered-pixel-dungeon#789]
I was looking through my rankings and started wondering when a certain round happened. It would be nice with a timestamp on each entry, that way you could or instance tell how long ago it was you actually beat the game and so on.

Not exactly a high prio thing, but would still be nice to have.

**Comment by 00-Evan** [comment]
Eventually I would like to improve the rankings screen, which could easily include a date field. Will defer this for now.

**Comment by 00-Evan** [comment]
Added in commit 900c689ad32b7076b0a03269a17cc55730ebb0ba
