### ISSUE TITLE
Icecap grows inside the wall after defeating Tengu.

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#79]

**Comment by 00-Evan** [comment]
Could you provide more detail please? Which location was the icecap planted in and though what stage of the fight did it persist?

**Comment by vi** [comment]
The last stage (wand of regrowth). It appears in the northen wall of the room with the book of mastery. One can still see it if go to that depth.

There was also a leftover seed (not in the wall, in regular area) persisted though the battle.

In general this reconfiguring level looks inviting for various minor glitches. In some previous version a pack of scrolls, dropped before fire-wielding battle, wasn't found after the battle...

**Comment by 00-Evan** [comment]
fixed in commit 2378f45fbbca75cd68846cd16785ba5ca7203818
