### ISSUE TITLE
Gateway trap getting deactivated

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#793]
I have managed to deactivate a gateway trap. It was next to a summoning trap. I stepped on the summoning trap and it teleported me and some enemies along. Then it remained inactive forever.

![Screenshot_2021-08-27-19-47-37-95_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/131162009-3050236b-6b4a-4d0d-83c1-161a7ba393b0.jpg)

**Comment by 00-Evan** [comment]
fixed in commit bb9ee6450f11636f74de1052573bf0f29095612a
