### ISSUE TITLE
Transmuting to a ring of might reduces strength

### ISSUE THREAD

**Issue by Le7Sel** [00-Evan/shattered-pixel-dungeon#794]
To reproduce the bug : Look at your strength stat (eg 15). Wear a non-ring of might. Transmute the ring to a ring of might while you still wear it. (Mine was unidentified, but I doubt it matters.) Unequip it once it is identified. The strength stat decreased (from 15 to 14).

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Transmuting a worn ring to might and back correctly removes/adds the might str bonus but no additional strength.
