### ISSUE TITLE
DM-300 sometimes pushes the player into inescapable rockfalls

### ISSUE THREAD

**Issue by antikovt** [00-Evan/shattered-pixel-dungeon#795]
Title self-explanatory
![Screenshot_20210829-135636](https://user-images.githubusercontent.com/76940779/131250563-8f183cef-5e05-4ab0-a2c2-38a814afe859.png)

**Comment by Leajian** [comment]
I had similar cases rarely. It mostly happens near corners obviously. Maybe the rockfall tiles are not spread apart based on pathable tiles.

**Comment by antikovt** [comment]
> Maybe the rockfall tiles are not spread apart based on pathable tiles.

That's what I thought exactly. Most likely there is a gap, but it's somewhere in a wall lol

**Comment by 00-Evan** [comment]
This is intended. When the player is in enclosed spaces an escape route isn't guaranteed, watch your positioning!
