### ISSUE TITLE
Skip next-level tiles at the end of a stage and fall

### ISSUE THREAD

**Issue by antikovt** [00-Evan/shattered-pixel-dungeon#796]
It's somehow possible to miss the next-level tiles at the end of a stage, specifically after the 4th boss was where I did it. I was unable to replicate the issue with one click, as I did it initially, though I was able to "slide" down a side and then get past the next-level line.

https://user-images.githubusercontent.com/76940779/131250701-f3531216-9134-4759-938f-293d6acec8ed.mp4

**Comment by 00-Evan** [comment]
This is intended, you're tapping past the steps down to the next floor and on the chasm behind them.

**Comment by antikovt** [comment]
Pretty sure stairs of any kind are not supposed to have a chasm behind them... I understand that left and right are intended, but forward is weird.
