### ISSUE TITLE
Choose Your Hero screen

### ISSUE THREAD

**Issue by NoahTheDuke** [00-Evan/shattered-pixel-dungeon#799]
I use an iPhone X and when I click the "Enter the Dungeon" button, the Choose Your Hero screen is cut off: ![image](https://user-images.githubusercontent.com/603677/131596380-751dee8b-4f7a-44c1-b54c-af8e2256155c.png)

**Comment by 00-Evan** [comment]
That is the correct visual, they are tabs popping out from the bottom of your screen. If Apple's touch bar is troublesome (I can't disable it =S) you can turn off fullscreen in the game settings.

**Comment by NoahTheDuke** [comment]
Ah cool, thanks!
