### ISSUE TITLE
DriedRose adding Petal

### ISSUE THREAD

**Issue by Sarius997** [00-Evan/shattered-pixel-dungeon#8]
I don't know if it is a real issue, but today I got the Dried Rose lvl 7 by throwing a lvl 7 Horn of Plenty in a Well of Transmutation and after that I still found round about 7 Petals, so this should maybe be reworked, because after upgrading the Dried Rose to lvl 10, one can do nothing with the other Petals you find. You can't even pick it up and sell in a Shop later.
Another point is, that if the Dried Rose is fully upgraded and you find a Petal and try to pick it up, the message: "You have no rose to add this petal to." is printed. 
Maybe the method public boolean doPickUp( Hero hero ) should look like this:
```
public boolean doPickUp( Hero hero ) {
    DriedRose rose = hero.belongings.getItem( DriedRose.class );

    if (rose != null && rose.level < rose.levelCap){

        rose.upgrade();
        if (rose.level == rose.levelCap) {
            GLog.p("The rose is completed!");
            Sample.INSTANCE.play( Assets.SND_GHOST );
            GLog.n("sad ghost: \"Thank you...\"");
        } else
            GLog.i("You add the petal to the rose.");

            Sample.INSTANCE.play( Assets.SND_DEWDROP );
            hero.spendAndNext(TIME_TO_PICK_UP);
            return true;

// this is what I would add to make clear why you can’t pick the petal up 
// maybe GLog.i() is not the best way to show this message
	} else if (rose != null && rose.level == rose.levelCap){

            GLog.i("Your rose is already fully upgraded.");
            return false;

    } else {

        GLog.w("You have no rose to add this petal to.");
        return false;

    }
}
```

**Comment by 00-Evan** [comment]
This is a known issue, it will be fixed in the next patch.

**Comment by Sarius997** [comment]
Okay.
PS.: I am the one who asked you concerning to programming a german version

**Comment by 00-Evan** [comment]
Fixed here:
https://github.com/00-Evan/shattered-pixel-dungeon/commit/49bab26d7bc2a8111fa862108d6718b5138d327c
