### ISSUE TITLE
This repository is not available in results when searching Github for "Shattered Pixel Dungeon",

### ISSUE THREAD

**Issue by vi** [00-Evan/shattered-pixel-dungeon#80]
because of it is a fork. Maybe it's time to detach it?

> me> I can't find 00-Evan/shattered-pixel-dungeon when searching Github for "shattered-pixel-dungeon".
>
> support> We don't index forks in the search because the vast majority of them are used only to submit pull requests, and if we indexed them then it would just make the results too noisy and not useful for anyone.
>
> me> Maybe renamed forks should be searchable?
>
> support> If you (ask support to) detach a fork from the parent, then it becomes searchable. Does that help?

**Comment by 00-Evan** [comment]
hmm, I wasn't aware you could ask github support to detach a fork.

Still, I rather like keeping the fork status as shattered is a fork, just a very big one, additionally you can still easily find the repo by searching on google.

Thoughts?

**Comment by vi** [comment]
> I rather like keeping the fork status as shattered is a fork

Github's notion of a fork is a place for launching pull requests towards the main repository. Do you plan making pull requests to the upstream Pixel Dungeon?

ShPxDn is a fork of PxDn, but not in a "Github fork" sense. So "forked from watabou/pixel-dungeon" may be transferred from system message to a part of repository description.

> you can still easily find the repo by searching on google

I fall back to this (or to searching e-mail for notifications about previous issues) after failing to get here in obvious way.

**Comment by vi** [comment]
For example, after detaching the [Network tool](https://github.com/00-Evan/shattered-pixel-dungeon/network) tool would be more meaningful, as it will show only repositories "pointing" at ShPxDn. Now the tool shows almost disjoint, "parallel" histories...

There's another option: reassign main repository from PxDn to ShPxDn (so the former will appear as a fork from the latter). But this is too strong move and is intended not for this case.

**Comment by 00-Evan** [comment]
Alright, I can agree with this then. I don't want to totally disassociate Shattered with the vanilla game, but clearly we are at a point where the repo should stand alone, especially if git's definition of a fork is causing issues.

I'll send a request to their support staff to detach this repo, and the PD-Classes one as well

**Comment by 00-Evan** [comment]
repositories are now separated.
