### ISSUE TITLE
Death Mark Bug

### ISSUE THREAD

**Issue by BennyBeechee** [00-Evan/shattered-pixel-dungeon#800]
When using the rogue's death mark ability on a scorpion while the rogue is invisible, the scorpion is alerted to the rogue's presence even though the rogue retains the invisible property. When used on a sleeping scorpion, the scorpion also awakens as if disturbed.

**Comment by 00-Evan** [comment]
This is worked as intended, sleeping enemies wake up if they are debuffed, though they aren't made aware of your exact location.
