### ISSUE TITLE
On fire while immune?

### ISSUE THREAD

**Issue by BennyBeechee** [00-Evan/shattered-pixel-dungeon#802]
While fighting the final boss's soiled fist as a rogue equiped with armor enhanced with a glyph of brimstone, I threw a potion of flame at the fist and when the flames from the subsequent fire reached me via the grass sprouted by the soiled fist, I caught fire. I did not unequip the armor in that time period so I should not have caught on fire. I took regular fire damage from that as well, which should also be nullified. This did not occur when using a wand of fireblast on the fist. Pictures attached.
![Screenshot_20210903-042135](https://user-images.githubusercontent.com/89070961/131975819-9fddf7b8-26bb-48ed-a2a2-ac2222117af4.png)
![Screenshot_20210903-042207](https://user-images.githubusercontent.com/89070961/131975836-12502587-c42d-430c-b74a-1522e091f1c1.png)

**Comment by 00-Evan** [comment]
This is working as intended, you're currently being affected by a scroll of antimagic, which prevents all magical effects, both harmful and positive. This includes glyph and enchantment effects.
