### ISSUE TITLE
Cursed rings and upgrade scroll interaction is different than other items

### ISSUE THREAD

**Issue by habahnow** [00-Evan/shattered-pixel-dungeon#803]
When you upgrade a cursed weapon or armor, text shows that the curse has been weakened, allowing you to unequip said item. 

With cursed rings, there is no text showing that, and you are unable to unequip the ring. 
Is this a bug or expected behavior? 
If this is intended behavior, i recommend text displaying the following after upgrading a cursed ring "The curse was not removed from the cursed ring with an upgrade this time. Cursed rings can not be removed without magic" or something to that effect since weapons and armor give you feedback on how the upgrade scroll affected it.

**Comment by 00-Evan** [comment]
Cursed rings and wands have a 1/3 chance to have the curse removed by upgrading. This is the same as the chance for weapons and armor to have the curse fully cleansed by upgrading. If you had a curse-weakened weapon/armor and failed the 1/3 chance you would get the same visual result as with the ring/wand.
