### ISSUE TITLE
killing Tengu also kills bee

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#805]
I threw a honeypot in phase 1 of Tengu's lair.  I left the living bee after defeating Tengu phase 1.  I defeated Tengu phase 2.  Returning to the phase 1 room, the bee is now gone.

**Comment by 00-Evan** [comment]
This is working as intended. Characters that are not reasonably near to you are lost whenever Tengu's stage transitions.
