### ISSUE TITLE
Possible bug: unblessed ankh resurrection on trapped tile

### ISSUE THREAD

**Issue by Jahfry** [00-Evan/shattered-pixel-dungeon#806]
Just had an unblessed ankh spawn me on an explosive trap. Given explosive tiles can destroy items (obviously not on character, unsure if they destroy vicinity items) this might be a bad result. 

Might not be something that needs fixing, as character is invulnerable, just documenting in case it's something to fix. 

![Screenshot_20210907-005841](https://user-images.githubusercontent.com/16520816/132307641-5a1bdd32-29d0-42a4-ae5d-8cb686baf777.png)

**Comment by 00-Evan** [comment]
fixed in commit 1eff353254d0a3541092c883b96735098cb16556
