### ISSUE TITLE
Can this game be online?

### ISSUE THREAD

**Issue by zenzx** [00-Evan/shattered-pixel-dungeon#808]
Can I play this game with my friends?

**Comment by TheYsconator** [comment]
At the moment, you can not play Shattered with friends (in the same map) at the same time.

One of the reasons I can imagine for this limitation, is that you (the player) basically moves the clock of the game forward by making actions. In other words: if you do nothing, the clock does not progress.

Keeping the clock synchronized is not trivial to implement with more than one player. The most obvious solution would be to have the clock hang until all players have made their action, and then progress all players in the next tick. However, that does imply that all players would have to wait for the other players before being able to make their next action. Intuitively, I think this is going to make for quite uncomfortable gameplay. 

On a technical level it should not be too difficult to port Shattered to web ('should' being the key term here), as it uses LibGDX. (However, note that porting to web is not necessarily needed for implementing multiplayer).

As I don't forsee Evan implementing this in the near-future, I would like to recommend you https://brogue.roguelikelike.com. It's not multiplayer per se, but I occasionally have my own run open on my main screen, and my friend's on the other, whilst hanging out on Discord. It makes for a multiplayer-esque experience.

**Comment by 00-Evan** [comment]
As was stated, there are major technical and game design limitations in the way of making the game multiplayer.

Some sort of pseudo-multiplayer, like weekly runs or user-enterable seeds (two players could both play on the same seed) is possible though.
