### ISSUE TITLE
Game seems to run at a low frame rate when activating iPad’s accessibility setting limiting FPS

### ISSUE THREAD

**Issue by built2spill69** [00-Evan/shattered-pixel-dungeon#809]
If, under accessibility settings, you limit your iPad’s screen refresh rate to 60hz, the game seems to struggle compared to running on 120hz.
I mean that it feels like the game runs at 30 frames per second instead of 60, particularly when you are moving (for the sake of comparaison, see how differently moves your hero compared to the waterfalls when you are standing still ; waterfall looks fluid).
Thank you.

iPad Pro 12 inches, iPadOS 14.7.1

**Comment by 00-Evan** [comment]
I don't have the hardware to test this, but I'll try to look into how this may be happening. If possible, can you record a video of the issue?

**Comment by built2spill69** [comment]
Please pardon me, the issue fixed itself. I could’nt replicate it at all today. Game feels fluid as intended. Thank’s !
