### ISSUE TITLE
[Minor] Ring of Wealth does not affect prison guard drop rates

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#81]
Found this while trying to break the system in half, but the guard drops seem separate from the monster drop logic.

**Comment by 00-Evan** [comment]
Yeah I can see why this is happening. Should re-tool that logic to work properly with drop rate like other enemies.

**Comment by 00-Evan** [comment]
fixed in commit c3910a127788ea0d123b64553fac45d17307b4ba
