### ISSUE TITLE
Tombstone Throwing weapon glitch

### ISSUE THREAD

**Issue by Skizoo8429** [00-Evan/shattered-pixel-dungeon#812]
When you throw a throwing weapon at a tombstone, the tombstone will bounce up like an item, but collect the throwing weapon as if it were an enemy, and the only way to get the weapon back is to uncover the tombstone.

**Comment by 00-Evan** [comment]
This is visually weird but technically correct. The thrown weapon is added to the stack of items that are under the tombstone.
