### ISSUE TITLE
Guidebook: no note made for distant well.

### ISSUE THREAD

**Issue by MattRCole** [00-Evan/shattered-pixel-dungeon#813]
If memory serves, the notes in the guidebook usually add the existence of any seen distant wells, but that doesn't appear to be working:

![Screenshot_20210913-205835_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/24833910/133188240-5bfd7e6f-daa6-4a9d-b55e-1dfdbe6b7837.png)

This is on the google play version of the game, v1.0.3

If more information is needed, please let me know.

If I remembered the notes incorrectly, or if this is an intended change, I apologize in advance.

Thank you so much for the attention and care you put into this project!

**Comment by 00-Evan** [comment]
No worries, the landmarks page never had an entry for distance well. It makes sense though, so I will consider this for the future.
