### ISSUE TITLE
Update Amazon Appstore version.

### ISSUE THREAD

**Issue by erperion** [00-Evan/shattered-pixel-dungeon#814]
Any chance updating Amazon Appstore version? Currently available version is 0.9.3c.

https://www.amazon.com/Shattered-Pixel-Dungeon/dp/B00OH2C21M

**Comment by 00-Evan** [comment]
The Amazon Appstore version has steadily had less and less activity as the years have gone on. These days platforms like Google Play or the iOS App Store get as many downloads in an hour as the Amazon version gets in a month.

Given that, plus the now uncertain future of what being on the Amazon AppStore means with Windows 11 (I would prefer to have a proper desktop version available to Windows, not an Android port via Amazon), I've decided to put that release on hold for now.

If you want to keep getting updates, it should be easy to download the APK from github and continue playing using that. I sign both versions, so the should be completely interchangeable.

**Comment by erperion** [comment]
That's alright I will use APK then. Maybe you should remove it from Amazon Appstore since you're not planning to update it.

**Comment by 00-Evan** [comment]
> 
> 
> That's alright I will use APK then. Maybe you should remove it from Amazon Appstore since you're not planning to update it.

I may in the future. For the moment I just want to leave it though, and the Amazon version does have an update prompt that points people to the github.
