### ISSUE TITLE
Teleportation trap vault vanishing chest

### ISSUE THREAD

**Issue by brooksambrose** [00-Evan/shattered-pixel-dungeon#815]
On iOS v1.0.3 a vault with teleportation traps eventually leads to a disappearing chest. Triggering the first four traps seemed to retain the chest, then after triggering the last trap in the row the chest is gone when returning to the room.

![IMG_1546](https://user-images.githubusercontent.com/1271481/133306143-d8a31590-945c-4b79-9d0e-de54df3e1d5a.PNG)

**Comment by 00-Evan** [comment]
This is odd but correct. Teleportation traps now trigger on everything in a 3x3 area, which can include the chest in these rooms. I am mulling over possibly making containers immune to teleportation in the next update though.

**Comment by brooksambrose** [comment]
Yup just realized this. I'll have to go looking for that chest 😄
