### ISSUE TITLE
Rogue Talent system issue

### ISSUE THREAD

**Issue by Skizoo8429** [00-Evan/shattered-pixel-dungeon#816]
The rogue starts with a 5x5 search without the talent being upgraded, and the talent itself is bugged, it says for both the first and second times you upgrade it, it says it goes from 5x5 to 7x7

**Comment by N1ghtmar** [comment]
but the rogue not starts with 5x5 search every round?

Em qua, 15 de set de 2021 15:59, Skizoo8429 ***@***.***>
escreveu:

**Comment by 00-Evan** [comment]
Read the talent more precisely. At +1 it boosts to a 7x7 circle, and +2 it boosts to a 7x7 square. The square is larger than the circle.
