### ISSUE TITLE
Dwarven Ghoul speed glitch

### ISSUE THREAD

**Issue by jonatan-hanssen** [00-Evan/shattered-pixel-dungeon#817]
Some kind of interaction between Elexir of Icy Touch and the Dwarven Ghoul revive causes them to gain insane amounts of speed. See this video: https://v.redd.it/x77v5rmtx3o71. No slowing items or debuffs were active on the player.

**Comment by 00-Evan** [comment]
Please do not re-post social media posts as issues here. I am already aware of the issue from that post so there's no need to duplicate.
