### ISSUE TITLE
unblessed ankh and quitting game

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#818]
If, when presented with the new unblessed ankh menu, you close the game, upon reloading the game, you cannot go back to this ankh menu.  Instead you are dead with no ankh, but the game is not over.

**Comment by protective1** [comment]
Furthermore, if from the game where you've died you go to the menu and start a new game, then that new game does not get saved.  Going back to the resume menu only shows the game where you've died with the unblessed ankh, not the new game that has been started.

**Comment by protective1** [comment]
Resumed the previous game (where I died with an unblessed ankh but then closed the game):
![Screenshot_20210919-152326](https://user-images.githubusercontent.com/8593007/133940292-7f6e8b4d-0c71-4d55-81ce-b4f32f81f494.png)
Clicked on menu to start new game:
![Screenshot_20210919-152344](https://user-images.githubusercontent.com/8593007/133940293-47c25498-2ff9-4790-8783-5db9def447dd.png)
New game is not getting saved:
![Screenshot_20210919-152354](https://user-images.githubusercontent.com/8593007/133940294-39779b84-ab41-4775-a225-911ad8b47062.png)

**Comment by 00-Evan** [comment]
fixed in commit f4ca0c4234f320e1d86f6226dc95b70746c4f7cd
