### ISSUE TITLE
power pylon shocks when frozen

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#819]
The activated power pylons in DM-300's lair still shock even when frozen.

**Comment by 00-Evan** [comment]
This is intended. Pylons are already fixed in place so freezing/stunning them does nothing.

**Comment by protective1** [comment]
But it seems that wards don't fire when frozen, so if the intention is that immobile creatures are immune to the effects of freezing then this is not consistent.
![Screenshot_20211003-000510](https://user-images.githubusercontent.com/8593007/135739307-6143b0b0-c46c-43ea-9379-549d8fb11ebe.png)

**Comment by 00-Evan** [comment]
Electricity is a passive effect that happens around power pylons, ward zapping is something the ward has to act to do.
