### ISSUE TITLE
Error: cannot read save file

### ISSUE THREAD

**Issue by dandeto** [00-Evan/shattered-pixel-dungeon#821]
I get the 'cannot read save file' error each time I try to descend to the second level. This renders the game unplayable. I've tried the latest release (1.0.3) apk and the google play version. I'm running Lineage OS 18 (android 11) on my Moto G7 Power. Is there something I'm doing wrong? This is the first time I've played the game.

**Comment by 00-Evan** [comment]
That's odd. When this happens It means the game is getting a file IO exception when it is attempting to set up or load the next level. If it happens when you first descend, it's likely that your device is preventing the game from creating the floor 2 save data for some reason. Can you provide any more details, such as logcat output?

**Comment by dandeto** [comment]
Sure thing! Here's some more info...
_Device Info_
LineageOS Version: '18.1-20210904-NIGHTLY-ocean'
Build fingerprint: 'motorola/ocean/ocean:9/PPO29.114-134/fee207:user/release-keys'
Revision: 'PVT1'
ABI: 'arm64'

Maybe this is the error? `java.io.FileNotFoundException: /mnt/expand/b85de564-555a-43ef-b12a-b098af5905e2/user/0/com.shatteredpixel.shatteredpixeldungeon/files/journal.dat: open failed: ENOENT (No such file or directory)`

That starts on line 2923, but I thought I'd provide more for context. Thanks for any help you can give! Seems like a fun game :)
[debug.txt](https://github.com/00-Evan/shattered-pixel-dungeon/files/7206638/debug.txt)

**Comment by 00-Evan** [comment]
Hmm, from looking at that log it seems there are a bunch of errors relating to trying to create save data, which lines up with what I was suspecting before. For example, you'll get:
`java.io.IOException: k.d: Error writing file: game1/game.dat (Local)`
and then right after:
`java.io.FileNotFoundException: /mnt/expand/b85de564-555a-43ef-b12a-b098af5905e2/user/0/com.shatteredpixel.shatteredpixeldungeon/files/game1/game.dat: open failed: ENOENT (No such file or directory)`

There's nothing the game can really do here, as your device is throwing errors when the game asks it to make save data. Uninstalling and reinstalling the game might help. I'm going to close this as it's not a problem with the game, but feel free to reply if you want to troubleshoot this further.

**Comment by dandeto** [comment]
Okay, sounds good. Thanks for the offer to help troubleshoot!

In the app info, it shows that no permissions are requested. I think that may be why it doesn't have permissions to write to the filesystem. Have you tested this on Android 11? I did some googling and found that you may need to add something to the manifest: [stackoverflow](https://stackoverflow.com/questions/66839849/android-studio-getting-error-ioexception-operation-not-permitted-while-creating). I was trying to give the app _files and media_ permissions, but the settings app won't let me.

**Comment by 00-Evan** [comment]
Shattered exclusively uses the internal app storage, which doesn't require any permissions to access. Again, I suspect this is a problem with your installation of the game, for example if you look at around line 6832 of the log:

`09-21 17:03:08.681  1376  1424 I PackageManager: Update package com.shatteredpixel.shatteredpixeldungeon volume from null to b85de564-555a-43ef-b12a-b098af5905e2
09-21 17:03:08.684  1376  1424 D CompatibilityChangeReporter: Compat change id reported: 135549675; UID 10218; state: ENABLED
09-21 17:03:08.771  1376  1424 D PackageManager: Instant App installer not found with android.intent.action.INSTALL_INSTANT_APP_PACKAGE
09-21 17:03:08.771  1376  1424 D PackageManager: Clear ephemeral installer activity
09-21 17:03:08.771   880  1467 E cutils  : Failed to mkdir(/mnt/expand/b85de564-555a-43ef-b12a-b098af5905e2/user/0/com.shatteredpixel.shatteredpixeldungeon): No such file or directory
09-21 17:03:08.771   880  1467 E installd: Failed to prepare /mnt/expand/b85de564-555a-43ef-b12a-b098af5905e2/user/0/com.shatteredpixel.shatteredpixeldungeon: No such file or directory
09-21 17:03:08.771   880  1467 E installd: Failed to prepare /mnt/expand/b85de564-555a-43ef-b12a-b098af5905e2/user/0/com.shatteredpixel.shatteredpixeldungeon: No such file or directory
09-21 17:03:08.772  1376  1424 E PackageManager: Failed to create app data for com.shatteredpixel.shatteredpixeldungeon: com.android.server.pm.Installer$InstallerException: android.os.ServiceSpecificException: Failed to prepare /mnt/expand/b85de564-555a-43ef-b12a-b098af5905e2/user/0/com.shatteredpixel.shatteredpixeldungeon (code 2)
09-21 17:03:08.778   880  1467 E cutils  : Failed to open(/data/misc/profiles/cur/0/com.shatteredpixel.shatteredpixeldungeon/primary.prof): No such file or directory
09-21 17:03:08.779   880  1467 E installd: Failed to prepare /data/misc/profiles/cur/0/com.shatteredpixel.shatteredpixeldungeon/primary.prof: No such file or directory`

try uninstalling and reinstalling the APK and see if that helps.

**Comment by dandeto** [comment]
I uninstalled and reinstalled several times on my phone before installing via abd. That did the trick, thanks! Looks like something with my OS is a bit broken...

**Comment by 00-Evan** [comment]
Glad to hear you got it working.
