### ISSUE TITLE
Missing shop on floor 6

### ISSUE THREAD

**Issue by nios9190** [00-Evan/shattered-pixel-dungeon#822]
After defeating the black goo boss I went to the next floor only to find that there was no shop. Was trying to figure out if there was a game seed or something to send you but here's screenshot for proof. Not sure what went wrong, or if this was intentional gameplay. 

![Screenshot_20210920-184922_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/91102642/134096650-ad9e3672-9aa2-490e-8652-fe9666b783a3.jpg)

**Comment by TheYsconator** [comment]
Did you try using the 'search' function all around the walls of the stairs going up? (That is; the stairs with which you would go to floor 5.) You can use the search function by double tapping the magnifying glass icon.

**Comment by TheYsconator** [comment]
Assuming you already tried that: you can find your game seed by going to the list of 'games in progress', select your save (so the pop-up shows, and you see the save's details and continue and erase buttons), and long-press the hero icon in the top-left.

**Comment by 00-Evan** [comment]
Shops are guaranteed to spawn on floor 6, you're on a secrets floor and the shop door is hidden. Try searching to the left and right sides of the entrance room.
