### ISSUE TITLE
My achievement in game

### ISSUE THREAD

**Issue by syerrif** [00-Evan/shattered-pixel-dungeon#824]
Who like this, play always win :)
![Screenshot (82)](https://user-images.githubusercontent.com/91103346/134156682-568b5339-f37a-4d93-91ad-22bc5601fce6.png)

**Comment by TheYsconator** [comment]
Nice achievement!

Be sure to post your achievement on the Pixel Dungeon subreddit; that's the place where this type of post will be appreciated (and viewed) more than here on GitHub. You can find that subreddit here: [https://www.reddit.com/r/PixelDungeon/](https://www.reddit.com/r/PixelDungeon/).
