### ISSUE TITLE
Can’t equip dried Ross

### ISSUE THREAD

**Issue by brooksambrose** [00-Evan/shattered-pixel-dungeon#826]
I transmuted level 10 boots into dried rose and it cannot be equipped. I have never seen or gathered a rose petal.

![image](https://user-images.githubusercontent.com/1271481/134460156-1d156d9f-5f22-4d16-bab5-b97065feb11f.png)

**Comment by brooksambrose** [comment]
I have not seen all the artifacts, but scroll of transmutation does not work on dried rose. "Nothing interesting happens".

![image](https://user-images.githubusercontent.com/1271481/134461627-0d33c3d0-ee62-443f-bfde-e1846575d599.png)

**Comment by 00-Evan** [comment]
Have you completed the sad ghost's quest on that run? The quest has to be completed for the rose to be equippable.

**Comment by 00-Evan** [comment]
Closing this under the assumption the ghost's quest was not completed, feel free to reply if that wasn't the case.
