### ISSUE TITLE
Hotbar Wand (of Regrowth) selectable after death

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#83]
A while ago (older version), I could activate a wand of regrowth (didn't do anything), even after dying.

**Comment by 00-Evan** [comment]
can't reproduce, do you mean that a quickslotted wand of regrowth is still selectable?

**Comment by jimbo1qaz** [comment]
maybe. it only happened once a few weeks ago.

**Comment by 00-Evan** [comment]
Do you remember the circumstances around that death? It may be that something triggers it.

**Comment by 00-Evan** [comment]
closed, can't reproduce. Please feel free to re-open this if you can provide more evidence or reproduction steps.
