### ISSUE TITLE
duplicate chest

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#830]
A chest was on a teleportation trap.  I threw a shattered honeypot at it.  I opened the chest and found a potion inside.  I found a second chest around the corner which had my shattered honeypot inside.  It's strange because the teleportation trap duplicated the chest.
![Screenshot_20210927-212440](https://user-images.githubusercontent.com/8593007/135007115-f57bdd82-e940-4b9a-a58f-8f52fa39b0e9.png)

**Comment by 00-Evan** [comment]
This is currently odd but intended. Throwing the item onto a chest makes it a part of the chest item stack, and when being teleported item stack type is preserved.

Regardless, I'm going to tweak teleportation traps to be unable to move chests in the next update.
