### ISSUE TITLE
Hotbar Ethereal Chains (unequipped) acts like tapping enemy

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#84]
If you have ethereal chains in hotbar, but not equipped in inventory, pressing it once brings up the targeting menu (despite the "not equipped" message). Pressing again chases and attacks the selected enemy.

**Comment by 00-Evan** [comment]
fixed in commit c632b016f871a08148a453634a31293649b1acbd
