### ISSUE TITLE
Ratmorgify makes all rats allies

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#844]
I've returned to the sewers and tried to ratmorgify a snake with ratlomacy. Afterwards, that ally came across other rats and they instantly became allies. I was able to use Ally Warp on them (as a Mage) and I could not target them with a melee attack. They treated me as an ally as well. However, their description did not mention anything related to our alliance. My original ratmorgified snake had indeed altered description, but the other rats did not, they were normal. What is more, this alliance never expires. I suspect that any newly spawned rat coming across in another rat, makes it their our ally Is this indented?

**Comment by 00-Evan** [comment]
Ratmogrify does turn all regular rats into allies, that is intended.
