### ISSUE TITLE
Play sound in silent mode on iOS

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#846]
Is there a chance you could add an option to play sound on iOS even if the device is in silent mode (i.e. vibration only for calls and notifications, but media volume is **not** muted)? My phone is always set to vibrate only and it's a bit inconvenient to have to unmute it when I want to play the game with sound and remember to mute it again when I leave the game.

Many other games do this and it might make sense to some people but I dislike this as media volume is separate for a reason, and there are apps and games that can play sound fine in silent mode when media volume is not muted.

**Comment by 00-Evan** [comment]
option added in commit b7119acd3e55afaf43ab16251c577a217b7c4969 (will be added to other languages in 1.2.0)
