### ISSUE TITLE
Endure inconsistency

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#848]
Hi there, yet another issue with how the damage calculation is handeled.
Endure description clearly sais it applies before any other form of damage reduction. However, this is only the case if the damage comes from another character (at src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/Char.java#L290). However, if not, ring of tenacity and armor of antimagic (at src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/hero/Hero.java#L1182) is applied before endure damage reduction and subsequent bonus damage is calculatec (at src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/Char.java#L530). This will make endure much weaker is the player uses ring of tenacity as their main source of damage reduction.

**Comment by 00-Evan** [comment]
fixed in commit 5024931e40513d06caaecc7df7b31fa979f54e54
