### ISSUE TITLE
Running the flatpak failure

### ISSUE THREAD

**Issue by Troltos** [00-Evan/shattered-pixel-dungeon#849]
I installed Shattered Pixel Dungeon from the flatpak (and made sure it was correctly the aarch64 version, it did not have issue with that by default) 
I ran
$ flatpak run com.shatteredpixel.shatteredpixeldungeon
and got
bwrap: exevp com.shateredpixel.shatteredpixeldungeon.sh: Exec format error

it is fundamentally similar to https://github.com/flathub/us.zoom.Zoom/issues/250
however the workaround they found did not work for me.
I tried
flatpak run --command=sh com.shatteredpixel.shatteredpixeldungeon
and then running 
shatteredpixeldungeon
but the output was
sh: shatteredpixeldungeon: command not found
other flatpaks are working normally so the issue is not with my install of flatpak

**Comment by 00-Evan** [comment]
Sorry, but I don't provide support for unofficial releases of the game. I'd suggest contacting the maintainer of the flatpak release.
