### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by mecurc** [00-Evan/shattered-pixel-dungeon#850]
Hi! I found out that jar package doesn't work on apple silicon.

Startup command: `java -jar ShatteredPD-v1.0.3-Desktop.jar`

The error on startup is:
```
Error: ShatteredPD must start on the first thread in order to work on macOS.
  To avoid this error, run the game with the "-XstartOnFirstThread" argument
  Now attempting to relaunch the game on the first thread automatically:

[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by 00-Evan** [comment]
The current verison of libGDX which shattered uses (1.10.0) only supports intel macs, and not the new apple sillicon ones. This will be resolved when libGDX releases their next update.

In the meantime, please run the game using a JRE made for intel macs, so that the game can run through Rosetta 2. I also plan to bundle a JRE with the game soon, which will also run via rosetta 2.

**Comment by mecurc** [comment]
Thank you for your great work 👍

**Comment by valynor** [comment]
>**The current verison of libGDX which shattered uses (1.10.0) only supports intel macs, and not the new apple sillicon ones. This will be resolved when libGDX releases their next update.
**

Could you please revisit the Apple Silicon issue? Intel Macs are now pretty much a thing of the past and it would be great to run this gem natively on macOS.

**Comment by 00-Evan** [comment]
> > **The current verison of libGDX which shattered uses (1.10.0) only supports intel macs, and not the new apple sillicon ones. This will be resolved when libGDX releases their next update.
> > **
> 
> Could you please revisit the Apple Silicon issue? Intel Macs are now pretty much a thing of the past and it would be great to run this gem natively on macOS.

unfortunately, while libGDX has been updated, some dependencies (such as steamworks4j) still only have ARM support in shapshot builds. Additionally the JVM that's bundled with shattered is for intel macs and switching to an ARM-based JVM would mean dropping support for intel macs. I'm not interested in doing separate builds for intel and apple sillicon.

**Comment by valynor** [comment]
The last new Intel Mac was from 2020, we're probably already past the point where there are more Apple Silicon devices than old Intel Macs. 

I honestly think it would make sense to drop support and switch to ARM64 for macOS.

**Comment by 00-Evan** [comment]
I'm not going to drop support for 4 year old macs unless I'm forced to. Shattered is a very low-spec game and I'm proud of the fact that it runs seamlessly on pretty aged hardware.

The current minimum requirement for mac is OSX 10.10 Yosemite, from 2014, and I don't plan to increase that without a decent reason. I'll probably consider this more seriously if/when Apple starts to wind down Rosetta 2.

**Comment by SaturnWorks** [comment]
I am launching the game in exactly the same way, but with version 3.3.8, using native JDK21. It seems to work fine.

**Comment by 00-Evan** [comment]
@SaturnWorks sounds like you're using the plain java version, not the one with bundled Java. The plain java version also does not have as many dependencies as the paid versions of Shattered distributed via Steam or others.

My last comment here was also about 18 months old. Apple has now started sunsetting Rosetta 2 and so sometime in this year or early next year I will be ending support for Intel macs and moving toward a native build for apple silicon.

**Comment by valynor** [comment]
@00-Evan from what I've heard you should be able to use the iOS version on macOS with some minor adjustments.

**Comment by 00-Evan** [comment]
@valynor Unfortunately that would only be distributable on the App Store, and I have no interest in making a mac version available there.
