### ISSUE TITLE
Dungeon 4 and 5 waters some times don't cancel burning effect!

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#852]
This happened recently 1.0.1v  Dawrf level dungeons and even the last dungeons... (I didn't use potion of levitation)

**Comment by Mellotic** [comment]
It happened to me twice in a single game

**Comment by Block-Vader** [comment]
Do you have any item/effect which increases movement speed? You have to be standing in the water AT THE END OF YOUR TURN for it to have any effect.

**Comment by 00-Evan** [comment]
As stated fire is only extinguished if you spend a turn on water, so if you have higher movement speed you need to wait.

**Comment by Mellotic** [comment]
I had no effect of haste at all...

**Comment by Mellotic** [comment]
I had no effect of haste at all...
