### ISSUE TITLE
Do sad ghost have the same effect of your equipment of rings?

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#854]
Ya right now I summoned my friendly ghost to help for no reason then a crazy thief come then we two go to kill him the ghost lands the last hit and I see a green flash of light (I have equipped right of wealth) and it drops a ring of wealth.. plz reply

**Comment by Mellotic** [comment]
(Sorry for English not my primary language)

**Comment by Block-Vader** [comment]
The ring can proc on any enemy death regardless the cause.

**Comment by 00-Evan** [comment]
As stated, the ring of wealth doesn't need you to be the killer for its effect to trigger.
