### ISSUE TITLE
Wand still shows as purple after removing curse with Scroll of Upgrade

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#855]
## Steps to reproduce
1. Pick up a wand with an unknown curse status (purple) that is actually cursed
2. Use a Scroll of Upgrade on the wand
3. Hit the 1/3 chance and get the message "The scroll of upgrade cleanses the curse on the item"

## Expected behavior
The wand's background should turn blue and say "This wand is free of malevolent magic."

## Actual behavior
The wand's background remains purple until equipped.

## Details
iPhone X, iOS 15.2 beta, Shattered Pixel Dungeon v1.0.3

**Comment by 00-Evan** [comment]
This is a bug but not in the way you think. The game is correctly leaving the curse status of the wand itself unknown, it shouldn't be displaying the uncurse message if the wand was initially unidentified.

**Comment by Mellotic** [comment]
Nice that we have someone playing in IOS 👍

**Comment by 00-Evan** [comment]
fixed in commit b1ef517a5ddb7867364af0d44162af3fb5413ceb
