### ISSUE TITLE
Not a issue... It's a Question

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#856]
Why do mobs spawn even after killing each and every one on that floor?🤔

I mean it should be logical you know🤨

**Comment by 00-Evan** [comment]
As you yourself mention, this is not an issue. Please avoid posting unrelated things here.

Enemies respawn so that there is a high enough number of them overall, without overwhelming the player when they enter a floor or leaving them bored once they've cleared it.
