### ISSUE TITLE
UX: Encourage user to use unknown stuff.

### ISSUE THREAD

**Issue by jtagcat** [00-Evan/shattered-pixel-dungeon#858]
I started playing the game, getting attached to the session. The part about death = game over should be elaborated on: you want to die, and start over.

I was holding on to potions and scribes, waiting for a knowledge unlock thing.

Try encouraging users to use unknown stuff.

**Comment by 00-Evan** [comment]
This is a place to report technical issues with the game or suggest technical enhancements, not to make vague game design suggestions.

If you mean that the game should make the player aware there is no way to permanently learn what items do, it states up-front that it is a roguelike, and there is a guidebook page that states potions and scrolls are different each run.
