### ISSUE TITLE
UI: Buffs display

### ISSUE THREAD

**Issue by jtagcat** [00-Evan/shattered-pixel-dungeon#859]
There's so much unused space there, and I keep clicking on they tiny, 3mm x 3mm squares to understand the buffs. Could their names be listed?

**Comment by 00-Evan** [comment]
Different displays have different amounts of real-estate, the buff bar is designed to allow space for several to display on minimum-sized screens. You can tap them for more info, or tap the hero's icon and go to the buffs tab to get a larger display.
