### ISSUE TITLE
UI: Increase transparency for event log items older than x

### ISSUE THREAD

**Issue by jtagcat** [00-Evan/shattered-pixel-dungeon#862]
Even though elsewhere I'm used to reading from bottom to up, I noticed I was reading top-down, with the oldest items first. They could've been a while ago.

The older items could be grayed / made more translucent. Either count or time.

**Comment by 00-Evan** [comment]
Please stop spamming this repository with multiple tiny feature requests, game design suggestions, and questions. You're welcome to create issues of course but if you continue spamming I'll have to block you.
