### ISSUE TITLE
Plants gone Invisible!

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#863]
I was warden (same run where I found the stone of intuition bug) I was in a room where it can only be unlocked by using potion of fire so I entered it looted the place, a spider was come so, I used my wand of regrowth so it only affected the ember area, once I killed the spider I was walking out the the room and got the effect of maybe time bubble plats effect but the thing is there was no plant at all... 
![Screenshot_2021-11-13-18-18-34-71_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/141644688-550bd07f-2a06-48e2-9397-e7a2990c49ed.png)
There was only one single tall grass...

**Comment by Mellotic** [comment]
It would make sense is the plant was there not the tall grass

**Comment by 00-Evan** [comment]
Hmm, possibly a bug where the plant was being invisibly placed in the regrowth AOE in a location where plants aren't supposed to go. Will look into this.

**Comment by Mellotic** [comment]
Yes...

**Comment by 00-Evan** [comment]
I've done some testing and I'm not able to reproduce this. The wand couldn't have placed the plant in a place other than that final tile with the grass on it, the first thing that happens in the wand of regrowth's logic is that it discards all cells where grass can't grow. There shouldn't be any way for plants to spawn without graphics either.

If you run into this again please feel free to comment and I'll re-open if there's anything that can be done about it.
