### ISSUE TITLE
New Item Request: Amulet

### ISSUE THREAD

**Issue by ReallyBasicGames** [00-Evan/shattered-pixel-dungeon#864]
Hello, 

I wasn't sure if you accept suggestions on things, so if not feel free to skip the reading and close this.

I would suggest adding an artifact simply known as 'the Amulet'.  It would be dropped the same way other artifacts would, but would provide magic damage resistance.  

This would be a more specific (yet more powerful) ring of tenacity, but would only work on magical attacks.  I will let you decide on how damage reduction would work.

While cursed, you will be to use wands, but all uses will be cursed. Also, unupgraded versions would increase the amount of magic damage you accept from all sources. 

It is upgraded by using wands and accepting magical damage. The more magical damage you take, the faster it upgrades, nearly guaranteeing to be level 10 when you reach the final boss, provided you have had it since the beginning of the game.

**Comment by Mellotic** [comment]
Nice but Evan may just close this without reading it, as he is already very pissed because of unwanted requests....

**Comment by 00-Evan** [comment]
@Mellotic Please don't speak for me in issues created by other people. I'm sorry that the issues

@ReallyBasicGames This place is more for technical issues/requests, the best place to reach me for game content suggestions is via email. Regardless, thanks for the suggestion. Generally I want to avoid artifacts with direct combat uses (dealing/reducing damage), as they tend to work better when providing utility effects. There's also already the ring of elements when it comes to magic resistance.
