### ISSUE TITLE
Demon Spawner's blood is missing

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#865]
After defeating Spawner I left the game... Then I joined again just to notice that there is no Demon Spawner makes on floor

![Screenshot_2021-11-14-14-48-10-65_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/141675061-e442531c-2139-4edf-82ee-1b101bb3a2aa.png)

**Comment by Mellotic** [comment]
And, Ya I won't be there of two three days so don't close the issue if I don't reply....

**Comment by Mellotic** [comment]
![IMG_20211114_145412](https://user-images.githubusercontent.com/92562082/141675163-af3e29fd-66ea-4f44-9bca-a884771314e6.jpg)
The demon Spawner was there

**Comment by 00-Evan** [comment]
I actually am closing this, but not because of a lack of reply. This is a tiny visual quirk that I'm aware of and have decided to leave alone. You could think of it as the base of the spawner shriveling and dieing off-screen.

**Comment by Mellotic** [comment]
So it was kind of intended
