### ISSUE TITLE
A Detected disintegration trap is still hidden

### ISSUE THREAD

**Issue by Dupontem** [00-Evan/shattered-pixel-dungeon#866]
When a disintegration trap is covered by a stack of gold coins only the lower part of the trap can be seen. That part of the trap is made invisibe if the next tile bellow is a wall.
The wall is displayed with a perspective respecting the point of view of the player that makes the trap hidden. 
I'm not sure if that must considered being part of the gameplay, because switching to the top view mode every time is just annoying.

**Comment by Mellotic** [comment]
This is intended... You need to be more careful with the traps or just use potion of levitation

**Comment by 00-Evan** [comment]
As mentioned this isn't a bug, though I admit it isn't ideal either. This almost always happens in rooms with lots of traps though, where it's reasonable to expect the player to examine every tile.

Also, I'm not sure what you mean by 'switching to the top view mode'?
