### ISSUE TITLE
Are Dead Adventure's Corpse common in Boss Level Dungeons?

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#867]
I discovered a Corpse of Dead Adventure it summoned a warth... The loot was a longsword... I have never come across any loot in boss dungeons in past runs... 🤔
![Screenshot_2021-11-16-22-10-43-96_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/142028536-ee87a563-e7cc-4c5d-a45c-4a8dc3172f12.png)

**Comment by Mellotic** [comment]
That leather Armor is mine actually....😋

**Comment by Mellotic** [comment]
Indeed the longsword is Cursed (that's common I know)

**Comment by ReallyBasicGames** [comment]
Pretty sure that is normal. A heap always appears on the last floor you died on (so if you died to the goo on the last run that is why it is there).

**Comment by Mellotic** [comment]
Nope I have never died to Goo recently

**Comment by 00-Evan** [comment]
Remains can spawn on boss floors if that's where a previous run died. Were the bones white or brown?

**Comment by Mellotic** [comment]
Brown...

**Comment by 00-Evan** [comment]
> Brown...

Those were heroes remains from a previous run then, which means this is normal functionality.

**Comment by Mellotic** [comment]
Plus the Last Run I didn't even had a long sword

**Comment by Mellotic** [comment]
If I remember I died at the Prison area

**Comment by Mellotic** [comment]
Quick Question... So all Brown Remains are all pervious hero deaths?

**Comment by 00-Evan** [comment]
> Quick Question... So all Brown Remains are all pervious hero deaths?

Yes, that's correct. White bones are generated by the game, brown bones (or white graves if you have supporter benefits) are from previous runs.

**Comment by Mellotic** [comment]
One more Can in the Same Dungeon spawn Two petal of SAD Ghost

**Comment by Mellotic** [comment]
![Screenshot_2021-11-17-00-16-35-43_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/142047050-0dc66cd8-3776-4ac1-8b8d-67f2bbe7f257.png)

**Comment by 00-Evan** [comment]
Yes, sad ghost petals can spawn faster if you find the rose at a later stage of the game.

Assuming you found it on floor 8, and therefore had 0 petals dropped so far, the game will try to generate ceil((depth/2 - 0)/3) =ceil((9/2)/3) = ceil(1.5) = 2 petals on floor 9.

**Comment by Mellotic** [comment]
Nice👍
