### ISSUE TITLE
EXP from Traps of summoning

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#868]
Well I discovered a room where the Remains of Adventurer... I knew it was a trap, knowing it I stepped in summoned a bunch of them.... Used scroll of Rage, Amoked them then all of them started to give exp... I thought it was indented but the next floor I found another Summoning trap I jumped in kill two Skeletons got no exp... Now this maybe an issue... Because I was level 6 and straight got to level 11 when I Amoked all of the summoned once and started a fighting frenzy.

**Comment by ReallyBasicGames** [comment]
From the code in the mob.java file, it looks like you only get XP from certain enemies up to a certain point before you just get none. 
If you already have roughly 5 levels above what your current depth is, you won't gain any XP when killing mobs.
```Mob.java Line ~ 670: int exp = Dungeon.hero.lvl <= maxLvl ? EXP : 0;```

**Comment by Mellotic** [comment]
Well I should be in the Right level when this happened

**Comment by Mellotic** [comment]
But I did get exp when killing non Summoned MoBs

**Comment by 00-Evan** [comment]
As mentioned, enemies stop giving exp after you pass a certain level threshold, which is different for each enemy. Summoned enemies and naturally spawning enemies are identical in this way.

**Comment by Mellotic** [comment]
OMG you guys are not getting my point..... Summoned Mobs Should not Give Exp Right.... Because I myself tried this but you aren't Supposed to Get Exp form Summoned mobs Guys....

**Comment by 00-Evan** [comment]
You are supposed to get exp from summoned mobs, as mentioned before the only thing that affects enemy exp rewards is what your level is in relation to the specific enemies your fighting. There are also some very specific things (e.g. chasm killing) which cause enemies to give reduced exp.
