### ISSUE TITLE
Dawrf's Multiply

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#869]
This may be intended 
![Screenshot_2021-11-18-15-21-19-73_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/142392310-192fe7b7-c3db-4689-b485-2cc31758c297.png)
As you can see I ran into a Summoning trap again..
I noticed only three Dawrf when I started to kill the they somehow they Multiplied... from three to six...

**Comment by 00-Evan** [comment]
That is intended. Dwarvern ghouls always work in pairs, so when one is generated it spawns a partner shortly after.
