### ISSUE TITLE
King of Dwarves death message uses %s instead of player class

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#87]
It seems like the latest release of SPD has an issue when killing the King of Dwarves.

The message uses "%s" instead of player class.

**Comment by 00-Evan** [comment]
I'm aware of this one, will be fixed in 0.3.5

**Comment by 00-Evan** [comment]
fixed in commit 0dae8acee78d40b595f4d787d8ff1a0fdbcd771e
