### ISSUE TITLE
Spider web removes frost effect from tiles

### ISSUE THREAD

**Issue by LyraLover** [00-Evan/shattered-pixel-dungeon#871]
Version: 1.0.3, Android 11
Steps:
1. Use potion of frost on area
2. Make Cave Spinner shoot web on tiles with frost
3. Remove spider web by throwing item at it

Unfortunatelly, I don't have a screenshot, but I will try to reproduce it again

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. spider webs and frost correctly stack when I test it, and clearing the web does not clear the frost.
