### ISSUE TITLE
Landscape mode doesn't take into account notch safe area

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#872]
On iPhones with a notch, playing in landscape mode results in some game text and a bit of the top right menu button being cut off, like this:

![Screenshot 1](https://user-images.githubusercontent.com/482367/143719886-67a817f0-ac4e-49a3-abd6-046f240b0431.png)

![Screenshot 2](https://user-images.githubusercontent.com/482367/143719893-7cbba1f0-a95c-4d7c-975d-827780c035fe.png)

iPhone X, iOS 15.2 beta 3, Shattered Pixel Dungeon v1.0.3

**Comment by 00-Evan** [comment]
the UI buttons are thankfully below the notch. Probably all that needs to happen is for the game log (or the action tabs, if it's the other way around) to shift over a little.

**Comment by 00-Evan** [comment]
fixed in commit cc221bc0899f3fcbe055b7fe89937f04b1859c08
