### ISSUE TITLE
Dart Trap Targetting is Unpredictable

### ISSUE THREAD

**Issue by GrantMoyer** [00-Evan/shattered-pixel-dungeon#874]
Dart traps target the closest creature, but if two or more creatures are the same distance from the trap, targeting is unpredictable. The cause of the unpredictable behavior is that the [poison dart targeting code][1] iterates through a HashSet of all creatures.

It's possible this is intended, but I don't think random behavior adds any mechanical depth in this situation. If the creatures were somehow sorted before iteration, the behavior would become predictable, and allow players to more effectively use dart traps against enemies.

[1]: https://github.com/00-Evan/shattered-pixel-dungeon/blob/4aed22a4f2ebea34e42fa961ee17f97588ca1acf/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/levels/traps/PoisonDartTrap.java#L57

**Comment by 00-Evan** [comment]
This is intended, I would prefer for the traps to prefer the closest character, and then be random after that. Even if it was made consistent it would be in an arbitrary way that wouldn't be easy to communicate like distance is.
