### ISSUE TITLE
Telekinetic grab doesn't work on Dwarf King

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#877]
When he goes into phase 2 and becomes invulnerable on his throne, you can't retrieve thrown weapons from him.

**Comment by 00-Evan** [comment]
This is because DK's throne is solid terrain, so the spell is stopping short. Will look into adding an exception here.

**Comment by 00-Evan** [comment]
Fixed as of RC-1
