### ISSUE TITLE
No text found case

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#878]
![Screenshot_20211206-133607.jpg](https://user-images.githubusercontent.com/76470428/144788096-408c08c2-40e4-46eb-a3e2-1ecd7cf3ad8a.jpg)

If i try drinking a potion of divine inspiration when I already have drunken 4 of them, the NO TEXT FOUND text prints.

**Comment by 00-Evan** [comment]
This one is already fixed in development, will be rolled out in the next beta.

**Comment by 00-Evan** [comment]
Fixed as of RC-1
