### ISSUE TITLE
Door trap getting canceled by enemy attacks

### ISSUE THREAD

**Issue by ShinKeyKai** [00-Evan/shattered-pixel-dungeon#879]
See screenshot for references. At the same time I was walking to the door trap a slime was walking to B, in A there was a potion. As I step on the trap, the potion teleports away, the slime attacks me and the turn ends. I'm now standing on the trap without it activating (at least for me and the slime, the potion did got teleported). I stepped on the trap again and we got teleported to C, me to the side of it and the slime right on C above a chest. I defeat the slime, open the chest and the potion wasn't there. Then I walk up to D and the potion was there. The door trap always go to C, I don't know how the potion ended on D. Also I was around C before and there was no chest there, I don't know where this chest came from.

![Captura](https://user-images.githubusercontent.com/47122537/145097975-98d4a664-0f3d-4526-9a89-199e04667e71.PNG)

**Comment by 00-Evan** [comment]
fixed in commit 9f0b86dc61ced519aae67def20ee9898229ace82
