### ISSUE TITLE
Scrolling/particle animation glitches

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#88]
Galaxy Nexus, CM11 4.4 rom.

Occasionally, the hero will freeze in the middle of an action (eg. attacking an enemy).

Occasionally, particle effects (blood, sewer wall outlets, etc.) will start at a negative size, zoom to zero, then appear normally. The hero does not move during glitched blood effects.

Occasionally, the map will jump off screen behind the hero's motion, scroll to the hero, then continue scrolling forward normally. The hero does not move while the map is scrolling improperly.

**Comment by 00-Evan** [comment]
You're going to need to provide some way to reproduce the issue, this isn't something I've ever observed or had reported before. Blood particles start at a hardcoded positive size and shrink, and kill themselves if their size ever becomes negative, so it should be impossible for them to behave in the way you're explaining.

Do any other applications perform oddly while not accepting input, at random? It is possible it has something to do with your device.

**Comment by jimbo1qaz** [comment]
Another related issue you probably don't have:

The item menu randomly starts shaking, then slows to a stop around a second later.

**Comment by 00-Evan** [comment]
Hmm, that is one that I've heard of before, but could never reproduce. Does this only happen for the inventory?

**Comment by tiw-gpidev** [comment]
I've had the shaking inventor happen on regular Pixel Dungeon as well so it might just be a rendering thing.

I have gotten the "offscreen scrolling back to hero" and its cousin "the hero seemingly moving out of map and then instantly warps to correct destination" but those never happened with frequency. The only thing in common was that I was practically moving from one end of the map to the other.

**Comment by 00-Evan** [comment]
@tiw-gpidev 

Has this happened in any other window that you can recall, or only the inventory? Also, what was your devices model and OS version at the time you experienced these issues?

**Comment by tiw-gpidev** [comment]
Only the inventory. This happened with an LG G2 and Android 5 as well as a Samsung Galaxy Tab 4 with 4.4. My current phone ASUS ZE550KL (5.02) has not had any of these issues happen yet.

**Comment by 00-Evan** [comment]
hmm, can you think of anything you might have done before opening the inventory that might have prompted it?

**Comment by tiw-gpidev** [comment]
No clear pattern I remember. Seemed to have done it after all sorts of things like resuming from sleep or normal gameplay or starting a new game.

**Comment by jimbo1qaz** [comment]
Same bug on Nexus 5X, with PureNexus 6.0.1. (only happened once in my playthrough)

**Comment by 00-Evan** [comment]
Clearly this is an issue but I can't really fix it without any means of reproducing, deferring it for now.

**Comment by 00-Evan** [comment]
In the recent engine updates in 0.4.2 I improved a lot of things and corrected some bits of logic which may have been causing the issues you guys were having.

For now i'm going to close this issue, but feel free to re-open or post another if you continue experiencing these errors, and can come up with some info about what seems to trigger them.
