### ISSUE TITLE
Unable to use Default Keybindings

### ISSUE THREAD

**Issue by edwardsaunders7** [00-Evan/shattered-pixel-dungeon#880]
For some reason, I am unable to use the default keybindings that have been set. The keys that do not work are as follow
- Escape
- Backspace
- Arrow Keys

I have tried resetting these as the same keys, but it appears that the client is unable to take in these keys at all -  only these keys.

Any ideas?

**Comment by 00-Evan** [comment]
Can you tell me what operating system you're using? Those keybinding work properly for me.

**Comment by repsej** [comment]
I experience the exact same problem.  

And also wait (w. space) doesn't work. 

Running SPD v.1.0.3 on Linux (Ubuntu 20.04.3 LTS 64 bit).

**Comment by repsej** [comment]
Btw. these keys do work:
qwer - quick slot
+- - zoom
i - inventory
s - search
h - hero
j - journal
z - sleep

**Comment by repsej** [comment]
I installed the game thru' the "Ubuntu Software" package manager.  

The package is listed as being created by Alan Pope.

**Comment by psydvl** [comment]
Same to me 
NixOS, GNOME with Wayland
Launched through `java -jar app.jar`

```
$ java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-nixos)
OpenJDK 64-Bit Server VM (build 17.0.1+12-nixos, mixed mode, sharing)
```

**Comment by edwardsaunders7** [comment]
I am also on Linux, Manjaro Gnome.

I have however fixed my problem, I had to simply change my keyboard language to a different layout (UK--> US),  to re-enable the inputs to the game.  I have since changed my keyboard back to UK, and it all works as expected :)

**Comment by repsej** [comment]
I can confirm the workaround :)

My keyboard is danish.

If I change the keyboard language to UK and start the game, then input works :)

If I start the game with keyboard language as Danish, then input doesn't work.
