### ISSUE TITLE
Quickslot bar update inconsistencies

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#881]
Quickslot bar is not updated for artifacts when Mystical Charge triggers. This results to 2 different charge readings for the same artifact.

In addition, when an artifact's charge updates naturally, the added charge is both added to the non-correctly updated (quickslot bar) reading and the correct (on the bag menu). This is not shown on the screenshot below, but I've noticed it. I might be wrong on that.

For example, notice the Talisman's charges.
![Screenshot_2021-12-08-19-47-56-50_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/145258977-ccef8e55-4029-4893-a542-c70e2e4a5106.jpg)

**Comment by 00-Evan** [comment]
This seems to only affect the talisman, will fix in the full 1.1.0 release

**Comment by 00-Evan** [comment]
fixed in commit fa9ec9b7a2f7aad92d12c64c472ec7d1d433a4a2
