### ISSUE TITLE
Rare forced quest or chasm fall

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#882]
There is a chance that a gateway trap teleports the wand maker directly onto the stairs, forcing you to either complete his quest or fall from the chasm. To solve that, you have to return from the stairs pushing him on the side. In my case, I wanted to decline his quest and keep the fresh embers, but not be forced to take the fall damage. I'm not sure if I could force a teleport by throwing a fadeleaf under his feet or not.

![Screenshot_2021-12-10-23-01-52-33_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/145641121-988e5f39-50ab-4c1e-978c-c82f25af3b18.jpg)

**Comment by 00-Evan** [comment]
Looks like gateway traps aren't checking whether the teleport target is immovable in all cases. Will get this fixed next release.

**Comment by 00-Evan** [comment]
fixed in commit a1b617c7073ff00a18645c37f6b4976435c439c8
