### ISSUE TITLE
Error on launch (no sound)

### ISSUE THREAD

**Issue by psydvl** [00-Evan/shattered-pixel-dungeon#883]
NixOS 21.11, GNOME 41.1 + Wayland 1.19.0, PipeWire 0.3.40

``` console
$ java -jar ~/App/ShatteredPD-v1.1.0-Desktop.jar
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
```

Everything, except sound, works fine

**Comment by psydvl** [comment]
Sound abailable when launched with
```
pw-jack java -jar ~/App/ShatteredPD-v1.1.0-Desktop.jar
```

**Comment by 00-Evan** [comment]
Was the game installed through the snap store? From a quick google there are sometimes permission issues with those installations and system resources.

**Comment by psydvl** [comment]
No, clear download from https://github.com/00-Evan/shattered-pixel-dungeon/releases/tag/v1.1.0

**Comment by 00-Evan** [comment]
Odd, unfortunately I don't think there's a lot that can be done in the game itself. For some reason the JAR is not being given permission to access /dev/dsp. I don't think there's any way for Shattered itself to request extra permissions or similar, they have to be granted to it by the OS.

**Comment by jasontbradshaw** [comment]
For posterity, I was having the same issue on SPD 2.2.1/NixOS 23.05/PipeWire 0.3.71/Wayland, and setting

```nix
pipewire.jack.enable = true;
```

fixed it for me with no other changes necessary. This made running `java -jar ...` work as expected.
