### ISSUE TITLE
Wand of Frost some how created Fire

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#887]
![Screenshot_2021-12-26-18-20-03-21_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/147408703-6ff94d5b-3cc3-4ded-93d9-fbace90e39e0.png)

That's a big Question now? I used my wand of Frost on Darven Gouls (not Firestone) and then That Frickin thing happened.

**Comment by Mellotic** [comment]
*Firestorm

**Comment by schumaml** [comment]
Did that make a Potion of Liquid Flame shatter, per chance?

**Comment by Mellotic** [comment]
First See this Data
1 I just entered the room and USED WAND OF FROST
2 No Traps were active 
3 If The Chilling effect made the Fire Potion Explode it should be 3x3 but it's 4x4

**Comment by fregkos** [comment]
The liquid flame potion was under the left ghoul's feet, that's why you couldn't see it. You can verify that this tile is also the center of the 3x3 splash effect. The reason you observed a wider area is because a round was spend and the fire was spread on the grass.

**Comment by 00-Evan** [comment]
Yeah this looks like a case of a fire potion below the left ghoul. The fire would get to act for a turn and spread, as stated.

**Comment by Mellotic** [comment]
I'm still not sure with your answer

**Comment by Mellotic** [comment]
![Screenshot_2022-01-01-15-24-32-48_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/92562082/147848150-9ae297e8-5142-416e-9418-b7268e016608.png)
Now this is the Picture after a turn

**Comment by Mellotic** [comment]
Now if the fire was spread 4x4 because of Potion of Fire touching the grass why didn't it ignite the door or the grass near it...

**Comment by 00-Evan** [comment]
That looks correct. The initial potion was 3x3, which spread once on the turn you threw it, and then one more time the next turn. Fire spreads in cardinal directions, not diagonal ones.

**Comment by Mellotic** [comment]
Promising but I have one more issue

**Comment by Mellotic** [comment]
![Screenshot_2022-01-02-22-00-59-18](https://user-images.githubusercontent.com/92562082/147916513-19e73c23-bb66-45bc-bca8-5ff505ed43cc.png)
What is this?

**Comment by fregkos** [comment]
That's a different issue. Please open another issue for that and describe any details there.
