### ISSUE TITLE
Feature Request: Ability to save a note for play continuation

### ISSUE THREAD

**Issue by LewisUD** [00-Evan/shattered-pixel-dungeon#888]
Hello there,

I've been thinking a wonderful feature to have would be the ability to save notes for yourself so that if you have to put the game down for a while there can be a reminder to yourself of where you were up to.  For example, I've just had to put the game down en route back up the dungeon to the troll blacksmith, 2 armours in hand.  The next time I load the game I may not remember this and continue back down the dungeon.  A simple note that read:
"go to lvl 12 - blacksmith 2x plate armour"
would make it much easier to jump straight back in.

**Comment by 00-Evan** [comment]
I've mentioned at least a few times that custom notes are something I plan on adding (e.g. in #502), and are now much more feasible that the game has platform-independent text input. At the moment there are other interface-based improvements that are taking a higher priority though.
