### ISSUE TITLE
"Wand preservation" talent counter/description ambiguity during imbue. 

### ISSUE THREAD

**Issue by MichaelMW** [00-Evan/shattered-pixel-dungeon#889]
The description says:
**_"This talent can preserve a wand up to three times"_**  [here](https://github.com/00-Evan/shattered-pixel-dungeon/blob/7f29a03078647ea503d3c866476568511aa5af84/core/src/main/assets/messages/actors/actors.properties#L575)

I interpreted it as:
**_"This talent can preserve EACH wand up to three times."_**
_(Counter set to three for each wand)_

However, according to the code [here](https://github.com/00-Evan/shattered-pixel-dungeon/blob/7f29a03078647ea503d3c866476568511aa5af84/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/MagesStaff.java#L213)
The actual effect is: 
**_"This talent can preserve up to three times."_**
_(Counter set to three in total)_

Could you please fix this behavior? So that it's more useful for multiple wand-swap. 
OR change the description so that it reflects the actual effect.

Btw, I'm a huge fan, bravo on all the great work Evan!

**Comment by 00-Evan** [comment]
Glad to hear you're enjoying the game!

The talent is designed to only preserve up to 3 times, the behavior is correct. You might also notice that the description of imbuing the staff includes a line to help address this ambiguity:

"The wand currently imbued in your staff has a X% chance to be returned at +0. Wand returns remaining: Y."

Or, when no talent is active:

"The wand currently imbued in your staff will be lost."

I appreciate that the description is slightly ambiguous, I'll consider adjusting it in a future update but for now I don't think it's worth making the translators go over the description for that talent again.
