### ISSUE TITLE
Spear Trap repeatedly damages player when picking up items with full inventory

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#89]
Sometimes an item spawns/falls on top of a spear trap. When I try to pick it up with a full inventory, I get damaged when I *fail* to pick it up. Every time I click the "pick up item" button, I take damage again.

When successfully picking up items, throwing, waiting, etc. (advance turn), the player does not take damage. Is this normal?

(This is the only instance I know of, where an action does not advance the turn, but still causes immediate effects (damage to the player))

**Comment by 00-Evan** [comment]
Hmm, I can see how this is a bit odd. Currently the item is removed from the floor, checks to see if the hero has room, and if not then the item is dropped back onto the floor.

It probably makes more sense to get the items reference, try to give it to the hero, and then remove it from the floor if the hero had room. This change would resolve the minor inconsistency you're seeing here.

**Comment by 00-Evan** [comment]
fixed in commit ef4fd423bb20ab3a96e7c63b8b72977871e3b253
