### ISSUE TITLE
Doesn't work Arcane Vision on 1.1.1

### ISSUE THREAD

**Issue by Skye7012** [00-Evan/shattered-pixel-dungeon#891]
When I zap an enemy, I don't gain mind vision

**Comment by 00-Evan** [comment]
Arcane vision does not grant mind vision, it grants you vision of the specific enemy that you shot at. The effect may not be noticeable if the enemy is already directly in your field of view.

**Comment by Skye7012** [comment]
Aaa, understood, thanks
