### ISSUE TITLE
Problem with Potion of Divine Inspiration on 1.1.1

### ISSUE THREAD

**Issue by Skye7012** [00-Evan/shattered-pixel-dungeon#892]
I had 2 potions of Experience, and after craft I got only 1 Potion of Divine Inspiration, not 2!
But previous I crafted 1 Potion of Divine Inspiration with 1 potion of Experience
Is it normal?

**Comment by 00-Evan** [comment]
Almost all recipes craft items one at a time, so you would have crafted one potion of experience into one potion of divine inspiration.

**Comment by Skye7012** [comment]
Oh, I see, I wrote wrong
There are another problem
I crafted 1 Potion of Divine Inspiration, but it took 2 potions of Experience
There is the real problem

**Comment by 00-Evan** [comment]
There isn't anything about that recipe which is different from any others, if there was a bug that caused items to get eaten I would have probably heard about it. Are you certain that you didn't end up with 1 of each potion?

**Comment by Skye7012** [comment]
Yes, I am certain
