### ISSUE TITLE
101% 

### ISSUE THREAD

**Issue by Mellotic** [00-Evan/shattered-pixel-dungeon#893]
Is this Normal?
![Screenshot_2022-01-03-15-09-01-06](https://user-images.githubusercontent.com/92562082/147916918-2fe135c4-a95b-4eeb-b5d0-9daae6fa784b.png)

It's not mine but got this for one of my Friends

**Comment by fregkos** [comment]
It seems that the ghost managed overhealing improperly. Did your friend happen to zap the ghost with a transfusion wand? It looks like it has a shield.
Also, please be more descriptive in your issue description.

**Comment by Mellotic** [comment]
Hey Evan, I recommend a version of Shattered Pixel Dungeon but not normal it should be like Creative mode... So it would be easy to recover the issue or bug happened to that player or maybe just us?

**Comment by 00-Evan** [comment]
fixed in commit b6630362a71eaa4501872b9c5be4e3777792080e
