### ISSUE TITLE
Backing out of metamorphosis dialog wastes the scroll

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#897]
This is regarding the Scroll of Metamorphosis. I want to find out what options I have for metamorphosing talents. I select a source talent and a dialog with target talents shows up. At this point it seems I am required to commit to selecting a target talent, or back out and waste the scroll. It would be nice if you could back out of the dialog gracefully.

For example, I wanted to see if I can have Rejuvenating Steps or Heightened Senses on my warrior. No such options were offered so I wanted to back out and try something else but couldn't. How was I supposed to know they wouldn't be offered?

**Comment by fregkos** [comment]
Indeed, I find that annoying too. I have to learn all the available replaceable talents via trial and error and it's not fun. Also, I think it serves no purpose to be punished like that. Especially if I have all my save-slots occupied by a single class, I have no way to check out all the other talents. I can't remember them all by heart.

**Comment by 00-Evan** [comment]
The scroll shows you a randomized variety of potential replacements, at which point you're committed to using it. If I let the player cancel at this point, they could keep trying to use the scroll to get the specific talent they wanted, or could back out at no cost if the talents they randomly got weren't ones they wanted. Working with what the scroll randomly gives you is one of the whole points of it, it's not meant to guarantee you a specific talent that you want. This is just like how the scroll of enchantment function.

**Comment by MiroslavR** [comment]
Ah, I didn't know the replacements were random. How about pre-calculating them at the point of using the scroll so they would be static for that use? The main dialog would still behave the same, it's just the subdialog that could be backed out of without cost. So if the replacements for one tier suck, you could at least try your luck on a different tier.

**Comment by 00-Evan** [comment]
That still lets you cancel the scroll for free if you don't like the options, which could let you then use it on another tier of talents, or turn it into energy.

**Comment by MiroslavR** [comment]
> which could let you then use it on another tier of talents

Yes, that's my proposal because it seems too punishing right now.



> or turn it into energy

How? If you back out of the main dialog with the tiers, the scroll gets consumed.

**Comment by fregkos** [comment]
That random part was not clear to me either. Maybe it was inferred somehow, but I also didn't realize it. A potential solution could be to be able to read the class information somewhere else, just like when you start a new game. Maybe a button on the save-slots screen.
