### ISSUE TITLE
[Quality of life improvement suggestion] resizable ui

### ISSUE THREAD

**Issue by Laar3** [00-Evan/shattered-pixel-dungeon#898]
it would be a really nice feature if it where possible to resize the ui to be a bit bigger as on devices like the pinephone the ui is a bit smaller than on the android build making it a bit harder to press menu buttons (still possible just a tiny bit harder). this is just a suggestion and i completely understand if its too hard or just not worth it for such a small subset of people (and its honestly not a big deal, just would be nice)

anyway, thank you for such a great open source game!

**Comment by Laar3** [comment]
![droid](https://user-images.githubusercontent.com/77225642/149311402-c59f0946-4724-47b6-a3de-ce835c33a7e2.png)
![native](https://user-images.githubusercontent.com/77225642/149311420-7791effc-292e-4ed1-817b-dc0ec9dd83e5.png)
just thought i should attach some pictures to show what i mean, the first is the game running through waydroid and the second is native, the size just makes the buttons a bit harder to tap.

**Comment by 00-Evan** [comment]
The UI scaling can be adjusted in the setting menu, there's a slider named "display scale" which adjusts this. Based on your display resolution it looks like there's space to set it to 5x (you're currently on 4x)

**Comment by Laar3** [comment]
sorry but i dont see the option, i only have visual grid and brightness and i dont see display scale in any of the other tabs

![pic](https://user-images.githubusercontent.com/77225642/149560591-67fcd7ad-0351-4cb7-8295-bbead8ebab6b.png)

**Comment by 00-Evan** [comment]
Hmm, from looking more closely at the font, it seems something on your device is causing the game to render at 360x720, and is then doubling that to 720x1440. You can tell as the font is being rendered in 2x2 pixel blocks, instead of 1x1. That would explain why the game is not letting you change display scale, as it thinks it's on a 360x720 display, which only has room for 2x scale.

**Comment by Laar3** [comment]
it could possible be an issue with my scaling being set to 2 in my window manager

**Comment by Laar3** [comment]
yeah its being affected by the scaling, if i disable scaling it shows the slider
