### ISSUE TITLE
Runic Transference should document what "regular" and "powerful" glyphs are

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#899]
The Runic Transference trait talks about "regular" versus "powerful" glyphs, but I haven't seen anything in the game that documents whether a glyph is regular or powerful.

For the purposes of planning a character's development through traits, it would help to know which glyphs were considered "regular" vs "powerful". In particular, an inscribed armor could say whether it has a regular glyph or powerful glyph, and the trait description could list regular glyphs (with the assumption that others are powerful).

**Comment by 00-Evan** [comment]
powerful glyphs are more rare and include "This powerful glyph" in the start of their description.

**Comment by joshtriplett** [comment]
@00-Evan Ah, sorry to have missed that. Thank you.
