### ISSUE TITLE
Badge for non-subclass victory?

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#9]
It's possible to beat the game without changing from your class to one of its two subclasses.  Seems like that ought to earn a badge.

**Comment by 00-Evan** [comment]
Indeed, there are actually a few oddities with badges at the moment.

One of the updates I have planned for the future is an overhaul to the badge system, which will resolve these sorts of issues. At the moment, seeing as I'm still reworking major parts of the game (wands are up next) it makes more sense to wait and address badges later.
