### ISSUE TITLE
Zip bomb?

### ISSUE THREAD

**Issue by Sanphobia** [00-Evan/shattered-pixel-dungeon#901]
I got an error from opening the .jar file from the latest release assets saying it was a potential zip bomb, is this normal?

**Comment by 00-Evan** [comment]
a .jar is a java archive, meant to be run by java, not a zip file editor (though they can still be opened like zip files if you want to look into their internal structure). I don't know what specific software you're trying to use to open the file but that should be false positive. I'm able to open the latest 1.1.2 jar file using 7-zip with no problems.

**Comment by Sanphobia** [comment]
Ah, I was confused at why it opened my zip extractor (Engrampa 1.26.0). Thanks for the clarification!
here's the output:
```
error: invalid zip file with overlapped components (possible zip bomb)
```
