### ISSUE TITLE
Harmless Curse trap 

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#902]
I guess Curse trap has the chance to select an already cursed equipment. This has no new negative impact for the player, making the trap harmless. 

For example, I used curse infusion to get Curse of Metabolism on my armor, because I found that helpful for my game phase. But stepping on the trap, probably selected this equipment again and left it unchanged. No other equipment of mine was additionally cursed.

**Comment by Mellotic** [comment]
Hey Evan, I have a Suggestion about a Version of Shattered Pixel Dungeon but it like Creative mode... Players are able to get any item and edit the Game but only the platform.. it can be very effective for Bug And Bug re- Confirmation.... But not on Real SPD

**Comment by fregkos** [comment]
How's that related to this issue? You are spamming right now. And to answer to your request, you can always compile the game yourself, edit the source code and give yourself all the freedom you want. You could even edit the save files and give yourself any item or change the seed. So please, don't post unrelated stuff to unrelated places. This is annoying.

**Comment by 00-Evan** [comment]
Cursing traps try to prioritize assigning a curse enchant or glyph, but will settle for just making it impossible to unequip a weapon/armor if they have to. Within those two tiers your weapon and armor are weighted evenly, so it is possible to have nothing happen even if you weapon was cursable (but not curse-enchantable). Cursing traps used to be much harsher, and could do things like curse rings/artifacts, or ovveride enchantments, but I've softed them up considerably.
