### ISSUE TITLE
Max health boost buff disappears when respawning from non-blessed ankh

### ISSUE THREAD

**Issue by Findereal** [00-Evan/shattered-pixel-dungeon#903]
Version : 
1.1.2

How to reproduce : 
Drink an elixir of might, have a non-blessed ankh in inventory (didn't try with blessed ankh, might cause the same behaviour). When you respawn, the max health boost is gone, even after retrieving the backpack.

Might be intentional ? Losing the boost would be lore-consistent (you are born anew after death), but so would keeping the boost (you are prevented from dying).

**Comment by 00-Evan** [comment]
Revival from an unblessed ankh cleanses all buffs and debuffs, this is intentional.
