### ISSUE TITLE
Unable to move diagonally with hardware keyboard on iPad

### ISSUE THREAD

**Issue by toph-allen** [00-Evan/shattered-pixel-dungeon#904]
Pretty simple: unless I’m mistaken, I can’t figure out a way to move diagonally when using a hardware keyboard to control an iPad.

**Comment by 00-Evan** [comment]
The iPad keyboard does not include a numpad, which is what the game's default keybindings use for diagonal movement. You can change keybindings in the game's settings.

**Comment by toph-allen** [comment]
Thanks for the info
