### ISSUE TITLE
Indicators can be triggered at the same time as autotargeting with frame-perfect input

### ISSUE THREAD

**Issue by 00-Evan** [00-Evan/shattered-pixel-dungeon#906]
See issue #828, most specifically this comment: https://github.com/00-Evan/shattered-pixel-dungeon/issues/828#issuecomment-1025175461

**Comment by fregkos** [comment]
I can confirm I am able able to make a missile miss while using the "continue moving" indicator with frame-perfect input.

**Comment by 00-Evan** [comment]
fixed in commit 7c596ccab7020352a1f9ff8c705ee5b76d690d95
