### ISSUE TITLE
'Information leak' - not-yet-used wands can be determined to be cursed/not based on ability to add to an alchemy pot

### ISSUE THREAD

**Issue by wolcen** [00-Evan/shattered-pixel-dungeon#909]
An unidentified and not-yet-used wand can be selected to place into the alchemy pot, based on whether or not the wand is actually cursed.

In other words, you can use the alchemy pot selection prompt to identify cursed wands without having to use them (or otherwise identify them).

**Comment by ondnipro** [comment]
Same with cursed spellbook and unidentified scrolls. Only remove curse can be read, other scrolls wil not used

**Comment by 00-Evan** [comment]
> Same with cursed spellbook and unidentified scrolls. Only remove curse can be read, other scrolls wil not used

That one's intended, there isn't really a way around that aside from making the player waste other scrolls, which would be too harsh.

**Comment by ondnipro** [comment]
@00-Evan such mimic disclosure is also intended?
![Screenshot_20220310_180806](https://user-images.githubusercontent.com/101347461/157731510-ed659813-3193-4b96-96a2-3deea2a256e1.jpg)
![Screenshot_20220310_180813](https://user-images.githubusercontent.com/101347461/157731528-2e9ad99d-36e7-4c86-af2b-44dff6af3787.jpg)

**Comment by 00-Evan** [comment]
@ondnipro Please don't embed full size images, it clutters up the thread, I've removed the embeds but kept the links to your images. This is intended, mimics are enemies and not items, and so they behave like enemies when it comes to vision.

**Comment by ondnipro** [comment]
> they behave like enemies when it comes to vision.

So one can harmlessly identify mimics by entering the room and then exit. If chest remains - it's clear, if not - mimic. May be they need to keep chest behaviour before was touched?

**Comment by 00-Evan** [comment]
@ondnipro Mimics can also be immediately IDed by examining them, watching them for an animation, or even just noticing some differences in their sprites. It's intentional that players will pretty quickly notice a mimic if they're paying attention. I prefered this to the alternative of forcing the player to try making an attack against every chest they encounter.

**Comment by 00-Evan** [comment]
fixed in commit 9225ce1854e93f35fdc499197593933729758fe2
