### ISSUE TITLE
[Humorous] 0.3.5a Multiple grim traps spawn in early floor

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#91]
I saw one initially and thought it would have been amusing as a rare occurrence but it seems that it replaced all of the "empty traps" in the level and it clearly was a bug.

http://imgur.com/a/zCG2M

**Comment by 00-Evan** [comment]
This one was in the wild for a couple hours last night and should already be fixed, download the latest update.
