### ISSUE TITLE
Visual glitch: guard's chain thrown at wrong space but still pulls from current space

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#912]
A guard came into view. I was in a door a few spaces below. I stepped up and to the left. The guard immediately threw his chain directly downwards, towards where I was. Despite that, it still grabbed me and pulled me adjacent to the guard.

**Comment by 00-Evan** [comment]
Looks like guards are visually targeting the current sprite center of their chains target, rather than where the sprite is going to be after it completes movement.

**Comment by 00-Evan** [comment]
fixed in commit a7e17632ba4c59957b1eea04d5a404128be74415
