### ISSUE TITLE
Troll Blacksmith

### ISSUE THREAD

**Issue by beatnickgr** [00-Evan/shattered-pixel-dungeon#914]
The troll blacksmith in level 13 

Reforged a wand with 3 charges and a wand with 2 charges into a wand with 4 charges. 
The new wand would be expected to have 5 charges at least, otherwise completing the quest actually downgrades the total number of charges.

Also reforged a scale armor +2 and a scale armor +3 into a scale armor +4. 
The new armor would be expected to be +6.
 +1 for reforging two simple armors, +2 of one armor and +3 of the other.

**Comment by TheYsconator** [comment]
That's in line with how it is implemented in code.

You basically get the highest of the two, plus one. There's also some special cases when enchantments/glyphs are involved, but you should take a look at the code for the specifics. Or just try things out! Nothing wrong with figuring out yourself how things work.

It's still quite useful though: you generally can't wear two armors at the same time, but with the Blacksmith's reward you can at least get some benefit of that other armor you've found. For wands the same goes (though I haven't checked the math here): you lose some total charges, but by having one higher level wand you do get a bit more firepower. It will probably depend on your run if that is an upgrade or not.

But now that you know, you can take that into consideration when deciding on doing the quest or not. If you don't need the reward, there's no real point in doing the quest.

**Comment by beatnickgr** [comment]
Thanks for your quick reply.

ARMORS and WEAPONS
Is there a difference between reforging armors & weapons of class
+3 and +2
+3 and +0
If not, shouldn't there be one?

WANDS :
Thanks, I wasn't aware the upgraded wand was more powerful (apart of more charges). Would be nice if you can do the maths and check if in total it is an upgrade or downgrade.

PS : Thanks for the great game, i have already sent you a tip, since I'm playing since a few years ;-)

**Comment by TheYsconator** [comment]
Ah I should start off by mentioning that I'm not Evan; I'm just a player who likes to keep an eye on the issues here on GitHub. (Though I'm sure Evan will poke in in a couple of hours as well.)

There currently is no difference in result depending on the level of the lowest level item. Quest improvements are planned (I believe for this year), so we'll both await those updates with excitement.

**Comment by 00-Evan** [comment]
Thanks for the support! This is intentional. The blacksmith takes the highest level of two items and gives it a +1, he does not combine the upgrades of both items. This is mainly so that getting lucky with a +2 item drop does not massively increase the power of a run.

I do intend to improve the blacksmith's quest rewards, but I likely won't allow him to merge the upgrades on two items.
