### ISSUE TITLE
Idea: Lower frame rate in Power Saver mode

### ISSUE THREAD

**Issue by danuker** [00-Evan/shattered-pixel-dungeon#915]
Hi!

Thank you for your work on this amazing game. I play it occasionally.

What I noticed is that in the "Power Saver" mode with lower resolution, the game still has buttery smooth animation, and uses up quite some battery.

I expect (as a non-Android developer) that **a lower FPS would significantly reduce power needs**, and less heat-up of the battery of my old device.

In moments the player is not performing any action, I believe FPS could be reduced dramatically (maybe 1 FPS).

I imagine, however, that there may be breakage of animations (like the gas effects) if they are defined in terms of frames and not time elapsed.

**Comment by 00-Evan** [comment]
Power saver was largely a feature I added to help some very old devices reach 60fps back in 2016. Most of those devices aren't even compatible with the game anymore. Additionally, when playing the game the actual processor and graphics usage is a relatively tiny amount of battery usage versus having the screen on constantly. In that sense the power saver setting is a bit misleading, as it doesn't really help battery at all on even somewhat recent devices.

Putting in a limiter would like result in very small battery savings on extremely old devices, and no change at all on anything else. This isn't the case for more demanding games of course, and for some of them an FPS limiter can make a big difference to power consumption.

Out of curiosity, what is your device model? Unless it's from 2013 or earlier I seriously doubt Shattered is chewing up much of its processor time.

**Comment by danuker** [comment]
I am using a ZTE Blade S6. I believe the game takes more battery than [RedReader](https://f-droid.org/en/packages/org.quantumbadger.redreader/) or [Space Trader](https://f-droid.org/en/packages/com.brucelet.spacetrader/).

But they are much simpler apps, and have not done any objective measurements, just a hunch.

Thanks for responding to my ticket! I thought GPU is significant, seeing the smooth frame rates.

**Comment by 00-Evan** [comment]
The Blade S6 has an Adreno 405 and a 720p resolution, with an uncapped framerate it could probably play Shattered at 300+fps, so at 60 the game should be barely stressing it unless there's a ton of stuff on screen. I can definitely see that the game would use up more battery than either of the apps you linked though, because they're using the Android UI toolkit, and aren't rendering entirely through openGL like Shattered it.
