### ISSUE TITLE
Rotberry seed dit not appear after burning

### ISSUE THREAD

**Issue by Woljtek** [00-Evan/shattered-pixel-dungeon#917]
Hello,

I met a strange behavior while I tried to get the Rotberry seed. I suspect a bug.

On level 8/9, during the old wandmaker quest, I attacked the red bulb in the room filled with vegetation in order to get Rotberry seed.
My weapon was "Unstable Spear +1". It made a fire enchantment attack which triggered a fire in the room. The red bulb seemed to be killed (or disappeared) in one turn. Thus, rotberry seed dit not appear after burning. 

Bad move for my game. Is an expected behaviour ?

I play on v1.1.2, with French translation (thanks to translator team !)

**Comment by 00-Evan** [comment]
This is intended, from the wandmaker's text when he explains the quest: "Using fire might be tempting but please don't, you'll kill the plant and destroy its seeds."
