### ISSUE TITLE
Award "Died fom toxic gas" disappeared 

### ISSUE THREAD

**Issue by ondnipro** [00-Evan/shattered-pixel-dungeon#918]
When i have not awarded "died from toxic gas" and "died from gas, poison, falling....." And finally die from toxic gas, that cumulative avard was avarded, bur "die from toxic gas" just disappeared.
![Screenshot_20220310_173354](https://user-images.githubusercontent.com/101347461/157700014-ca5df04d-035e-4747-9995-be8c2afe13ac.jpg)

Android v1.1.2

**Comment by 00-Evan** [comment]
You unlocked the YASD badge, which replaces all of the individual death badges.

**Comment by ondnipro** [comment]
@00-Evan all rings, all scrolls, all potions identified will also be replaced by "all items identified"?

**Comment by 00-Evan** [comment]
@ondnipro Yes. Lower tier boss badges are also replaced by higher tier ones, and it only shows the highest badge you've unlocked for badges that have a series (e.g. the four 'collect X amount of gold' badges). This helps prevent clutter.
