### ISSUE TITLE
Invisible enemies are not really invsible

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#919]
When an armoured statue has a camouflage glyph and gets the invisible status by stepping on grass, it is still visible. Invisible enemies should be really invisible. See that userʼs reddit post:
https://www.reddit.com/r/PixelDungeon/comments/tcjoep/found_out_what_an_invisible_enemy_looks_like_in/

**Comment by 00-Evan** [comment]
Please don't re-post issues that are posted elsewhere.
