### ISSUE TITLE
Small translation trash

### ISSUE THREAD

**Issue by demothorg** [00-Evan/shattered-pixel-dungeon#92]
In `src/com/shatteredpixel/shatteredpixeldungeon/messages/items/items_ru.properties`

Value `items.armor.glyphs.viscosity$defereddamage.desc` contains trash string `javascript:`
[See this fix](https://github.com/demothorg/shattered-pixel-dungeon/commit/75a40f7260dc9b9aacd0b1e96d0d41b593490364)

**Comment by 00-Evan** [comment]
Huh, no idea how that got there.

Regardless, all translation stuff is to be handled through the transifex site, including issues. I'll get this fixed, but i'm closing this issue as it's not the appropriate place.

**Comment by demothorg** [comment]
Ok, I unsterstand. I couldn't find issues on transifex site, because post this issue here. :)
Thanks for repsonse.

**Comment by 00-Evan** [comment]
Reviewed translations can't be edited by none-reviewers, but you are still able to post comments or raise issues in text as a regular user.
