### ISSUE TITLE
Ring of Wealth +7 drop tier?

### ISSUE THREAD

**Issue by chorby-short** [00-Evan/shattered-pixel-dungeon#920]
The description of the ring of wealth seems to imply that the maximum minimum drop tier is +6 (at RoW+21). Shouldn't it be +7 at RoW+28? You can achieve this level in the following scenario (there are lightly easier ways to get +28, but this is the way to reach the maximum level):

1. Get a +4 cursed ring from the Imp Quest, uncurse it, and transmute it to Wealth if it is not already Wealth
2. Dump all 15 SoU on it, and the Troll Blacksmith upgrade, making it +20
3. If you don't already have it, use Metamorphosis to get the Rogue's enhanced rings upgrade, giving your +20 ring an extra upgrade (now +21)
4. Farm until you get another ring, at +6. Transmute into Wealth again, with the additional +1 from the enhanced rings talent making it an effective +7. Because having two of the same ring also effectively gives one additional upgrade (the +0 level for the second ring), this will make you have a +29 ring combination, which higher than 28 (the 7th triangular number, which appears to be the pattern for drop levels), so the new minimum drop level should be +7.

Did I misunderstand something here? This is of course almost impossible to achieve but it is something that I am trying to accomplish at the moment with the Huntress, in order to get the theoretically maximum level of any item in SPD (a +8 curse-infused spirit bow, with both RoW's transmuted into RoSS's at levels +21 and +8, giving the bow an effective level of +39, which is completely insane but super cool!). Despite +28 and higher ring loadouts being difficult to obtain, they are theoretically possible, and the description should probably reflect that.

**Comment by 00-Evan** [comment]
Code comments are not meant to be all-encompassing. I'm describing the functionality of the ring not giving a description that I expect players of the game to use in decision-making.
