### ISSUE TITLE
[Beta 1.2.0] Wands can no longer be targeted with the keyboard

### ISSUE THREAD

**Issue by gitter-me** [00-Evan/shattered-pixel-dungeon#922]
Before you could activate the wand (for example with a quickslot) and the shoot with the arrow keys or the numpad (including diagonally). This no longer works only the mouse is usable.

**Comment by 00-Evan** [comment]
This is a bugfix for unintended functionality. Directional keys are currently meant to be used for movement, not targeting. I would like to let the player select a cell with only keyboard, but would rather properly implement the functionality (under #351).
