### ISSUE TITLE
[RFC] Consider incresing starting strength for Warrior to counter class disadvantage

### ISSUE THREAD

**Issue by diimpp** [00-Evan/shattered-pixel-dungeon#924]
Hey guys,

I'm new player and just done my first 18 games and what I'm noticing is that it's outright painful to play as `Warrior` in comparison to other classes.

There is nor affinity to ranged weapons, nor any kind of stealth, every fight is upfront and personal and broken seal is just not enough.
If I'm to compare `Warrior` to `Rogue`, then I've noticeably less search range and no rechargeable critical hit chance with cloak/invisibility, every mob in sight is agro on me.
If I'm to compare `Warrior` to `Mage`, then my mage problem is that I don't have enough space to store all those items and shops doesn't have enough items to purchase, while warrior problem is to find at least one food item and stop starving and being at 10-20-30 health all the time.

Again, I must face enemy directly head on (number of them at a time) and as result my play as `warrior` is heavily reliant on magic wands and random potions instead of brute force and that's directly due inability to equip higher level weapons/armor.

My latest stats looks like so. Why my `Warrior` level is higher and at lower dungeon level? Was I just dealt with rougher chances for this particular play? (**UPD**: Did another run with `Warrior` till 11 lvl dungeon, it was easier, but still money-less, food-less or poition-less, every mob still actively agro on me and I had  extra weird encounter after teleport with 7-8 mobs on me in the same room)

| Class  | Dungeon lvl | Hero lvl | Strength | Mobs killed |
| ------------- | ------------- | ------------- | ------------- | ------------- |
|  Warrior | 11  | 16  | 13  | 246
|  Mage   | 16  | 18  | 16 +1 | 259
|  Rogue |  12  | 15  | 15 | -
|  Huntress | 13  | 15  |  15 | -

So I propose to increase starting strength for `Warrior` to 11/12/13 without re-balancing anything else to counter class disadvantage.

What do you think? Is there such problem in reality or am I just inexperienced in the way of the wise yet?

**Comment by 00-Evan** [comment]
The warrior is less flashy than the other classes, and has fewer opportunities for skill expression, but in exchange he gets a lot of passive power from his seal (shielding and armor upgrade transfer). Warrior actually has the highest winrate among the four heroes, among all players who have won at least once already.

**Comment by Yavin86** [comment]
Hi
+1 for enforce #Warrior by granting him 11 strength on game start. It feels only natureal for #Warrior to have more strength than other classes.
Alternative solution - give "Strongman" ability on game start.
I'm old player and huge fan) By now I've done 215 attemts and 10 successeful walkthroughs and only 2 of them was with #Warrior. My favorite class #Mage but my top result was with #Huntress.
