### ISSUE TITLE
[Beta 1.2.0] Option to disable the custom mouse cursor

### ISSUE THREAD

**Issue by gitter-me** [00-Evan/shattered-pixel-dungeon#925]
I understand the mouse cursor matches the design and look and feel of the game, but the cursor zooms with the display scale (which for some may be a great feature). 

It would be great to have a toggle option to enable the mouse cursor of the operating system or the custom one (The new custom one should be the default)

**Comment by 00-Evan** [comment]
Is there a particular reason why you need this as a setting? The intention with having the cursor scale was both to match the art and to ensure it was always an appropriate size.

**Comment by gitter-me** [comment]
I'm used to a large display scale and I play mostly keyboard driven. When I move via keyboard keys the (now larger) mouse cursor is kinda in the way and blocks some vision.

As I already wrote I do understand the matching art and design and some will enjoy the larger cursor matching the size.

I'll try a smaller display scale and you can focus on more important tasks.

When you make the 1.2 source available here, I can adjust this for myself.

Btw. I'll use this opportunity to **thank you** for your huge efforts and the work you put in shattered (and also credit Watabou), I really enjoy playing the game and also reading the source (it's a clean OO-based code architecture)

**Comment by 00-Evan** [comment]
Thanks for the kind words! I will keep the mouse pointer feedback in mind and may implement a setting for it if it's a reasonably common request. Honestly there are a few things I'd like to improve about the current settings menu.

Removing the custom cursor in the code should be a very simple one line adjustment. I have the functionality encapsulated so you can probably just stick a return at the start of Cursor.setCustomCursor
