### ISSUE TITLE
Pancaked Achievement for dying of Bleeding after jumping

### ISSUE THREAD

**Issue by Krediman** [00-Evan/shattered-pixel-dungeon#926]
Version: v.1.2.0-Beta-1 on Android (version without google services)

When the hero (so far I only tried with Mage) falls into a chasm and does not die from the falling damage itself he gets the debuffs bleeding and crippled. If the hero dies a few turns later because of the bleeding, I still earn the Achievement "Pancaked".
In my understanding this should only happen if the hero dies immediately after jumping of direct falling damage. 
So far I have not found out what happens if the hero is bleeding for other reasons.

**Comment by 00-Evan** [comment]
This is intended, bleeding to death as a result of falling does count as a fall death.
