### ISSUE TITLE
Enhacement: Improove Layout for left handed players

### ISSUE THREAD

**Issue by Krediman** [00-Evan/shattered-pixel-dungeon#927]
As of 1.2.0-Beta-1 is is possible to switch the on screen buttons for move on, collect Item and attack monster, as well as the lower action bar but this will leave the button for iterating over the monsters in view on the right side of the screen.

![Screenshot_20220320-011854](https://user-images.githubusercontent.com/71612364/159142887-e908d5f5-2ed6-4e0d-9b6d-a23cb3ff58b0.png)

I suggest to also move this button to the left when switching the layout. This might involve mirroring the top bar as well.

**Comment by 00-Evan** [comment]
Sorry but I'm not planning additional UI mirroring options for buttons outside of the main toolbar area. Those buttons are already difficult to access due to their high position, and so aren't really meant to be tapped one-handed anyway.
