### ISSUE TITLE
Summoning trap inconsistency

### ISSUE THREAD

**Issue by Krediman** [00-Evan/shattered-pixel-dungeon#928]
Version: 1.2.0-beta-1 on android (the one without google services)
Visible summoning traps spawn Monsters on visible summoning traps (At least that's what I guess)

![Screenshot_20220320-110401](https://user-images.githubusercontent.com/71612364/159157437-0b93b136-f5af-4ddf-9402-a78d20bb1399.png)

I encountered a room full of summoning traps. By searching I discovered 3 of them (marked in red here) before triggering any. Then I triggered the trap on the square marked in yellow by throwing a piece of cooked meat there. This triggered all traps in the room including the two I already discovered. 

I would expect a discovered trap to behave like an invisible trap eg. it should spawn monsters only on non-trapped tiles or tiles with invisible traps.

**Comment by 00-Evan** [comment]
Summoning traps can spawn enemies on top of other traps (visible or hidden). That's intended functionality and the trap behaves that way regardless of whether it is discovered or not.
