### ISSUE TITLE
Missing solution to red sentry room

### ISSUE THREAD

**Issue by Krediman** [00-Evan/shattered-pixel-dungeon#929]
Version 1.2.0-beta-1
I encountered a red sentry room on level 8. 

To pass safely through the sentry Room I currently know the following solutions:
1. use a potion of haste
2. Use (at least) one potion of healing
3. Exit the room using a Fadeleaf

Other Ideas I had that do not work:
1. potion of invisibility (sentry still attacks)
2. destroying the sentry (seems to be immutable)
5. Wand of disintegration (neither destroys the wall nor damages the sentry)
6. potion of levitation (cannot fly over the wall)

As far as I know, the standard way for solving the Room is the potion of haste. It seems to me that a potion of haste is not generated with the room. I could not check this in the code because I did not find the definition of the red sentry room.
This happpened to me about 6 times now, so I guess it is actually a problem, unless I am missing something.

**Comment by 00-Evan** [comment]
This is fixed as of beta-2, please update.
