### ISSUE TITLE
Glaive should have extra reach. 

### ISSUE THREAD

**Issue by DoMiNeLa10** [00-Evan/shattered-pixel-dungeon#93]
The glaive seems to be like a better version of the spear, so it would make sense for it to have extra reach, but it doesn't have it.

**Comment by 00-Evan** [comment]
Currently the Glaive is a weapon with no unique properties. That is likely to change in a future update and another weapon will fill in that space.

Please send none-technical suggestions to my email, this place is for technical suggestions and bug reports
