### ISSUE TITLE
Play normal region music after boss is defeated

### ISSUE THREAD

**Issue by mnunesp** [00-Evan/shattered-pixel-dungeon#930]
In the beta version, no music plays after defeating a boss. Descending a floor then coming back plays the normal music. It's only really a prolonged issue when preparing for the 5th region at the imps shop. Maybe have the music fade back in after some time of silence? I do like the quiet before the fight.

**Comment by 00-Evan** [comment]
I am intending to improve boss music playback either a bit before or shortly after release. I'd rather not have the regular music start instantly but am going to look into perhaps starting it on a 5-10 second delay.
