### ISSUE TITLE
RC1 version number

### ISSUE THREAD

**Issue by Krediman** [00-Evan/shattered-pixel-dungeon#931]
I installed this file: https://github.com/00-Evan/shattered-pixel-dungeon/releases/download/1.2.0-beta/ShatteredPD-v1.2.0-RC-1-Android.apk
the filemane sais it is version 1.2.0 RC1
but in the app I see v1.1.2

**Comment by Krediman** [comment]
This seems to be only the case with the android version. the Android-Gplay version does not have this issue. I have not checked the desktop version so far.

**Comment by 00-Evan** [comment]
I am not at my build computer so I've removed the Android builds for now. Will re-post them later.
