### ISSUE TITLE
[Beta 1.2.0] Rooms inaccessible if opened in wrong order

### ISSUE THREAD

**Issue by Ba3henov** [00-Evan/shattered-pixel-dungeon#933]
An iron key has the chance of spawning inside a locked room.
![20220322_182547](https://user-images.githubusercontent.com/46943437/159669409-9536cc06-185c-4b0f-ad18-df89eb1283de.png)
In this run, I unfortunately used an iron key to open a coins room first (highlighted yellow), and now can't access the new goodie room (orange), inside which I suspect there's another key.

**Comment by 00-Evan** [comment]
This is already fixed in RC-1, and will be in the full release as well.
