### ISSUE TITLE
Sniper Mark Crash

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#934]
![1](https://user-images.githubusercontent.com/76470428/159885842-debc3ec5-ea5f-464a-b289-78b352036769.png)
![2](https://user-images.githubusercontent.com/76470428/159885856-8c0680b3-a61c-4a34-8b0e-0fab8e9434a4.png)

When I get Sniper Mark buff while I don't have a bow and then I put the cursor on the buff's action button, it makes crash.

It seems the hoverText makes NullPointerException.

**Comment by 00-Evan** [comment]
fixed in commit d1c477f8f27f80dc08feb52805aa841614566460
