### ISSUE TITLE
Game breaking bug when using the 1.2 beta installation

### ISSUE THREAD

**Issue by rowebyrowe** [00-Evan/shattered-pixel-dungeon#935]
Playing on a samsung galaxy s10.

After I installed the 1.2 beta, I tried to start a new character. I chose mage, the screen switched to Loading... with bricks sliding like an elevator. Then the screen went to black. Except it wasn't really black, it was just dark. I brightened the screen to the maximum and could make out descending.... . The top of the screen had some grey bricks visible. The rest of the screen was black like I was looking down a pit. The music also changed to what I presume is the sewers music. 

There was no interactivity from the screen, no menus, no backpack, nothing. The phone's back button wouldn't do anything either. The three vertical lines (sorry don't know the term for them) that shows all the active apps did work to get me out of the game and into the app chooser. I choose shattered and it goes back to the main menu. Trying to load into my character (who shows as if I just started) puts me back into the near-black screen, although it says Loading... instead of Descending... 
![Screenshot_20220324-221454](https://user-images.githubusercontent.com/18298291/160053292-b809bd99-2ede-4e44-8250-cc1bf9475ffd.jpg)
. Attached is an image of the screen mentioned above.

**Comment by 00-Evan** [comment]
The 1.2 beta is no longer the latest version, please update to the v1.2.0 release (for some reason Google is still holding it up, you can directly download the 1.2.0 APK via github)
