### ISSUE TITLE
Particles are not cleared after blast wave displacement

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#937]
As the title says, the picture below shows the moment of the zap with the wand of blast wave. The particles of the pumped up Goo, remained there.
![Screenshot_2022-03-05-20-49-42-84_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/160182593-30aaeaa3-48c2-497c-a6b0-788c8cc71039.jpg)

**Comment by 00-Evan** [comment]
The particles are tied to the location Goo was at, as those were the tiles it was threatening. They aren't cleared because Goo hasn't had a chance to act yet (you stunned it). I appreciate that this looks odd but it's a minor and rare enough visual quirk that I'm fine leaving it be.
