### ISSUE TITLE
No progress saving in Flathub Edition

### ISSUE THREAD

**Issue by hiimsergey** [00-Evan/shattered-pixel-dungeon#938]
Hello,
At first thank you so much for making the game accessible on Flatpak, especially with the new Computer Compatibility Update.
There is one issue in this edition though.

When you start, play and leave the game, no progress will be saved. That means that if you start it again, there will be the same Welcome Screen and afterwards you get to choose the warrior (and only him, even if you unlocked the other ones) and start a new game. No access to new ones.

**How to reproduce?**
1. Start the game
2. Play a bit
3. Restart the game
4. => Last game won't be saved.

**Setup**
DIistribution: KDE Neon 5.24
Flatpak version: 1.12.4
Version: 1.2.0

Thanks in advance!

**Comment by 00-Evan** [comment]
Glad you're enjoying Shattered, but I'm afraid I don't provide support for unofficial distributions of the game. I'd suggest contacting the maintainer of the flathub version to see if they can help. v1.2.0 does change Shattered's save directory in Linux, so it's possible something needs to be changed to accomodate that.
