### ISSUE TITLE
Ring of Force works on all attacks including thrown weapons

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#94]
I'm not sure if it's supposed to have a diminished effect for anything but knuckleduster-less fists, but it doesn't seem to be diminished at all since I'm hitting quite a bit harder with +3 ring of force with a dagger.

**Comment by 00-Evan** [comment]
The ring of force applies a flat +1 to damage on all attacks using a weapon, however with empty fists it completely replaces the default damage algorithm to something much stronger. If you found a +3 ring of force early on then the damage it adds to your dagger would be quite significant, although if you have 11 or 12 strength the damage with no weapons at all would be greater.

This is working as intended.
