### ISSUE TITLE
Crystal key tooltip - mention crystal doors

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#940]
Crystal keys can now open crystal doors in addition to crystal chests, so might as well include that information in their information dialog, right?

**Comment by 00-Evan** [comment]
I can't change this in other languages yet, but will get this oversight fixed in English in 1.2.1

**Comment by 00-Evan** [comment]
fixed in commit 933e845a32d552854dbc8c1ea96ac6c46fd2c11b
