### ISSUE TITLE
Sad Ghost freezes game after unblessed ankh resurrection

### ISSUE THREAD

**Issue by ItchScratcher** [00-Evan/shattered-pixel-dungeon#941]
I was playing as a warden with the sad ghost summoned from an equipped rose artifact.  After being killed by a dwarven ghoul, the sad ghost resurrected with me.  Immediately, the game froze, with the turn-tracking circle in the top-left corner constantly cycling.  Luckily, exiting to the main menu and reloading the game allowed me to keep playing, except for 2 more glitches that occurred.  

After reloading the game, the ghost slowly died as I searched for my inventory pack (I guess because my rose was no longer equipped).  But after recovering the pack, re-equipping the rose, the artifact behaved as though the ghost was still summoned, and wouldn't let me re-summon it.  I could only "direct" the ghost, which didn't exist anymore, and didn't re-spawn after changing levels.

Force-closing the game, and then reloading the game returned the rose to normal, except that its charge had gone from 100% down to 0%, which wasn't a major issue.

**Comment by 00-Evan** [comment]
I'll address the freeze as part of #945 , but I was able to reproduce the rose issue separately and will get that fixed in v1.2.1

**Comment by 00-Evan** [comment]
rose issues fixed in commit 02e2118f3c033432495ccc20e2ec7cf7d1d40ac3
