### ISSUE TITLE
Ability to unlock camera from player

### ISSUE THREAD

**Issue by Robert-K** [00-Evan/shattered-pixel-dungeon#942]
Whenever the player moves the camera snaps back to have them in the center of the screen. Especially on Desktop I'd like to be able to just keep the camera wherever I panned to and focus on the player manually.
Desktop makes it pretty viable to just zoom out and play like that (on mobile things get too small).
However the constant camera moves make this 'playstyle' pretty annoying.

If this isn't the right place for feature requests I'm sorry. Awesome work and congrats on the Steam launch!! <3

**Comment by 00-Evan** [comment]
A few people have noted something like this as a feature they'd like. I am planning on overhauling the settings menu in v1.3.0 and will consider adding this sort of functionality as a part of that update.

**Comment by 00-Evan** [comment]
@Block-Vader I'm aware that this one was missed for 1.3.0, was planning to re-prioritize it after figuring out exactly what I'm working on in 1.4.0, rather than re-assigning it to that now and then potentially deferring it later.

**Comment by 00-Evan** [comment]
Added in commit 41ea6aad60c0b9fcc9b105d563461e269734b3aa
