### ISSUE TITLE
infinite run lock on dwarf king

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#943]
I was fighting the dwarf king and the game locked with the player moving down towards the king.  The clock circle kept rotating.  Was resolved by killing game and restarting it, after which everything proceeded as normal.
![Screenshot_20220327-114828](https://user-images.githubusercontent.com/8593007/160608926-f1539384-b999-4f33-b99a-0e7b010a50ec.png)

**Comment by protective1** [comment]
In case it's relevant, my assassin has a +3 speed ring.

**Comment by protective1** [comment]
Debug info:
![Screenshot_20220330-000806](https://user-images.githubusercontent.com/8593007/160749761-0215c5b7-c22d-4830-b6da-dc820e995799.png)

**Comment by 00-Evan** [comment]
Moving this to #945
