### ISSUE TITLE
IMA FIRIN MAH LAZOR

### ISSUE THREAD

**Issue by przemyslaw-zan** [00-Evan/shattered-pixel-dungeon#948]
### Reproduction steps:

- In the backpack, have **Disintegration** and **Prismatic Light** wands **only**
- Use **Wild Magic** (mage armour ability)

### Expected result:

- Wands fire in a sequence

### Actual result:

- Wands fire simultaneously

TBH, it is a pretty cool effect of a massive beam blast, <sup>(hence the title - sorry)</sup> but it also makes hard to know how many shots were fired, so I'd consider this a bug. Possible solution could be introducing minimum wait time between shoots, something like 0.25s or 0.5s?

I've listed the wands that caused the behaviour in my case, but all wands that fire a beam instead of a projectile that takes time to travel are probably affected, so:

- Disintegration
- Lightning
- Prismatic Light
- Transfusion

**Comment by 00-Evan** [comment]
This is technically correct as those wands have an instantaneous firing time, but I understand your point that this seems odd with the wild magic ability. I'll look into how it could be tweaked.

**Comment by 00-Evan** [comment]
fixed in commit d51fed0f4db2bf3a7c93402b49d8c380c0113ec5
