### ISSUE TITLE
tengu second phase freeze on attack 

### ISSUE THREAD

**Issue by complaining-user-engine** [00-Evan/shattered-pixel-dungeon#95]
Every time he should take damage in the room after the maze this happens and I get reset to a state before it happens when I come back to game later

Am mage and I used a psionic blast scroll to win the first encounter, tengu's heath is oddly at 100% during second battle phase

**Comment by 00-Evan** [comment]
This is due to the scroll and is fixed indev. Afraid there isn't anything to be done for your current run.

**Comment by 00-Evan** [comment]
fixed in commit 82cdc7149f413403219ba30f454daa449e142e4d
