### ISSUE TITLE
Blazing champion too op

### ISSUE THREAD

**Issue by Travelingmerchant** [00-Evan/shattered-pixel-dungeon#950]
This was meant for the challenge " Hostile Champion ".
Of course fighting enhanced mob is sure fun and also troublesome. Even player can adopt own stratergy on it. 

Though, beating champion mob that roam around was not a big deal. But if it was blazing one, you might say goodbye to your progress. What actually make it worse when you these type of champion spawn in earlier floor (such as 1st floor, 6th, 11th ,ect) this hostile already creep behind the door and 25% damage buff make it more deadly beside every attack ignite target on fire.

**Comment by 00-Evan** [comment]
This is not the place to make subjective suggestions about game balance. Blazing champions can deal scary amounts of damage, but are notably less deadly if you fight them at range or around water.
