### ISSUE TITLE
feature request: wand-specific text to elemental blast armor

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#951]
Can you please consider adding wand-specific descriptive text to elemental blast armor's description? Right now if you look at the armor description it says, "in an effect that varies based on the wand in his staff".  It would be helpful if the text explained the specific effect.  As far as I can tell, the only time you can see a wand-specific description is when you first use the crown.

**Comment by protective1** [comment]
![Screenshot_20220402-194210](https://user-images.githubusercontent.com/8593007/161405101-13831c45-0e63-4120-8635-0f4482a72401.png)

**Comment by 00-Evan** [comment]
Elemental blast doesn't include specific text here for the sake of brevity, You can access the full description from the hero info window.

**Comment by protective1** [comment]
Thanks for pointing this out.
What I was looking for was text which includes the recalculated damage values, similar to how weapon description text is updated with recalculated values as upgrades are applied.

I have a staff of corrosion.  The elemental blast text says that its effect applies corrosion for 4 turns, starting at 6 damage.  The question I was looking to answer was, if I get the Elemental Power talent, which increases the power of the blast, is there a corresponding increase in the resulting corrosion duration or damage?  These upgrades to Elemental Blast are not reflected in any recalculated description text anywhere.

**Comment by 00-Evan** [comment]
None of the abilities currently do this, they all describe their base power, not their enhanced power after talents. In the specific case of corrosion, the starting damage is increased based on the elemental power talent and rounded to the nearest whole number. Having the talent at 0/1/2/3/4 would give you a starting damage of 6/7/8/10/11
