### ISSUE TITLE
troll blacksmith removes displacement from armor

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#953]
I gave the troll blacksmith a +1 plate armor with a weakened displacement curse, as well as a +0 plate armor (in that order).  I got back a +2 armor with no displacement glyph.  I would have expected either to get back +2 plate armor with a displacement glyph, or if not that, then for the blacksmith to complain that he couldn't work with armor that has a curse.  Is this intended behavior?

**Comment by 00-Evan** [comment]
The blacksmith is missing a check there atm, he should refuse to work with armor that has a curse glyph.

**Comment by 00-Evan** [comment]
fixed in commit 6bee83e8c1e83c096ba309c20d6768375f06acb9
