### ISSUE TITLE
Game crashes when descending stairs after slime boss

### ISSUE THREAD

**Issue by pressRtowin** [00-Evan/shattered-pixel-dungeon#954]
Latest android version from the play store. Used to play this a bunch a while back and just downloaded it again on my Tab S8 Ultra. After beating the first boss, the game crashes every time I try to descend to the next floor. Has happened 10+ times consistently now.

**Comment by 00-Evan** [comment]
I'm aware of this, v1.2.2 is currently distributed to a limited number of people on Google Play. I intend to pause that rollout and fix the bug before continuing with the v1.2.2 release.

**Comment by 00-Evan** [comment]
Fixed in commit f6d30c05d8847f10c9fc49880daad50c0c5d15f0
