### ISSUE TITLE
There are no introduction of the fire wall in v1.2.1

### ISSUE THREAD

**Issue by nvlie** [00-Evan/shattered-pixel-dungeon#955]
as title

**Comment by 00-Evan** [comment]
The same is true for almost every mechanic in the game, there is not a direct guided tutorial, instead the player is expected to use the examine button.

**Comment by nvlie** [comment]
i mean that there's no introduction when the examine button is used.![Screenshot_20220409-010241.jpg](https://user-images.githubusercontent.com/103258671/162488564-48ac15e7-a578-4e4f-bd75-d0f4a6445311.jpg)

**Comment by 00-Evan** [comment]
Oh I see, that is a bug then. I'm about to full release v1.2.2 so I'll include it in that.

**Comment by 00-Evan** [comment]
fixed in commit 5f4b2560d4faddec793e0459ac73d87fa4f2bf12
