### ISSUE TITLE
Enable downloads of iPad app from App Store on M1 Mac computers

### ISSUE THREAD

**Issue by brainard52** [00-Evan/shattered-pixel-dungeon#956]
It's relatively simple to enable M1 Mac support for iPhone/iPad apps.
https://developer.apple.com/documentation/Apple-Silicon/running-your-ios-apps-on-macos

It would be nice to be able to let the App Store manage updates.

**Comment by 00-Evan** [comment]
Sorry, but I would rather desktop users play one of the desktop versions (github or Steam atm). I'm not interesting in offering the game via the App Store outside of mobile devices.
