### ISSUE TITLE
freezing blob bug?

### ISSUE THREAD

**Issue by hughbowls** [00-Evan/shattered-pixel-dungeon#957]
Not sure if freezing blobs are working as intended, but during gameplay the freezing blobs won't increase the chill stack of characters nor will it freeze them if the chill stack is more than 8.

The problem might lie in this line of code assuming it is not intended.

shattered-pixel-dungeon/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/blobs/Freezing.java

Line 75 
if (chill == null || chill.cooldown() <= Chill.DURATION - 3f) {
	Buff.affect(ch, Chill.class, Dungeon.level.water[cell] ? 5f : 3f);
}

**Comment by 00-Evan** [comment]
It is intended that the chill caps at 10 turns. This doesn't impact gameplay at all as slowdown caps at 5 turns, but I agree the functionality could be smoother.

**Comment by 00-Evan** [comment]
fixed in commit 57727034ec06551357ae7e9fd1278b517d289cf4
