### ISSUE TITLE
Talent title error with Ratmogrify

### ISSUE THREAD

**Issue by hughbowls** [00-Evan/shattered-pixel-dungeon#958]
When choosing Ratmogrify as armor ability, all talent titles display !!No text found!!. Ratroic energy seems to be the exception.

Problem might lie here:

shattered-pixel-dungeon/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/hero/Talent.java

Line 221

**Comment by 00-Evan** [comment]
fixed in commit 68d1f047224c35297e4a8ade09a819589cb240bb
