### ISSUE TITLE
Steam cloud not working on Linux when playing on multiple operating systems

### ISSUE THREAD

**Issue by YoriMirus** [00-Evan/shattered-pixel-dungeon#959]
Hello. I have a desktop computer that runs Windows (Windows 10), Windows laptop (Windows 11) and a laptop that runs Linux (POP!_OS 21.10). 

Today I tried running Shattered pixel dungeon on my linux laptop and noticed that, despite the Steam Cloud data being downloaded, the game doesn't seem to detect them. If I run the game through proton experimental, the data get loaded properly, it seems to only happen on the native version of the game.

Is there a way to run without Proton without losing my data? The linux laptop is very old so I don't want to overwhelm it with a compatibility layer to run the game unless necessary.

**Comment by 00-Evan** [comment]
That's odd. I tested steam cloud functionality on a Ubuntu VM, and steam cloud did sync it correctly. Does Steam's UI show any changes with cloud sync status as you run/stop the game? Also, are you launching the game through Steam?

**Comment by YoriMirus** [comment]
Yes, I run it through the steam launcher.

While running natively, steam says that steam cloud is up to date. While opening the game, steam doesn't check for steam cloud like it does on Windows.

Now that I opened it the second time, the data from last time I opened it natively is there. So the data on the cloud and what is actually read by the game is different (maybe the linux version is storing the data somewhere else?). After creating a new character and playing it for a bit, I closed the game. Steam cloud synchronisation happened so steam detected the changes.

I then tried running the game on my Windows machine, Steam downloaded some data but I still don't have the data from my Linux laptop. I created a new character there and played it for a bit. Steam cloud sync activated like normal when I quit the game.

I then ran the game on my Windows laptop. The data from my Windows computer was loaded properly.

Afterwards I ran the game on my Linux laptop again. Steam cloud didn't activate for some reason, even though it should have since data on the cloud has changed. No data from my Windows computers got loaded and the data from when I played on the Linux laptop is still there.

**Comment by YoriMirus** [comment]
Okay I just tried running Shattered pixel dungeon in a POP!_OS virtual machine and the data loaded properly from the Windows computer. So either it's something with my laptop specifically or something goes wrong when Linux is run directly instead of in a VM.

**Comment by 00-Evan** [comment]
Hmm, have you made any configuration changes to XDG_HOME on your POP!_OS machine, or changed any configuration settings withing Steam cloud on that machine? Shattered's save data on linux is located in XDG_HOME/.shatteredpixel/shattered-pixel-dungeon/ , and Steam cloud sync checks "$XDG_DATA_HOME/.shatteredpixel/shattered-pixel-dungeon" on linux.

Assuming the game itself is changing files properly, the problem is either with Steam or something with your machine, as Shattered uses Steam auto-cloud, which means that cloud sync doesn't happen within the game itself at all.

**Comment by YoriMirus** [comment]
I'm not quite sure what XDG_HOME is (I'm a beginner when it comes to Linux, sorry), so I looked online, are you referring to my home directory? I looked at the hidden directories and couldn't find a .shatteredpixel directory. 

Typing ls -a or sudo ls -a doesn't show anything either, so the data folder definitely isn't located in my home directory.

Also I don't remember changing anything regarding syncing. Steam cloud is definitely enabled since the game works through proton experimental properly.

**Comment by 00-Evan** [comment]
Honestly I'm no linux pro either =P

XDG_HOME is a system variable for where application data should be stored, typically located in ~/.local/share

So, on Linux Shattered's save data should be in `~/.local/share/.shatteredpixel/shattered-pixel-dungeon/ `, check there and make sure data is getting modified correctly. 

It's also worth noting that prior to v1.2.0 Shattered saved data to `~/.shatteredpixel/shattered-pixel-dungeon/` , this was changed in 1.2.0 to better respect linux conventions.

**Comment by YoriMirus** [comment]
Okay I have made some progress, seems like the XDG_HOME variable isn't set. According to https://www.reddit.com/r/pop_os/comments/d72nqy/xdg_data_home_and_xdg_config_home_are_not_defined/ that is okay, however I found that the steam cloud data is located in ~/.var/app/com.valvesoftware.Steam/.local/share/.shatteredpixel

No idea why it puts there, but that's probably why the game can't see them as the game is probably looking somewhere else (then why does it work with proton though?)

Unfortunately I can't find where the game is storing the data to. There is nothing in .local/share and searching with nautilus doesn't find anything, only the steam cloud folder. Creating a symlink to the steam cloud directory in .local/share didn't do anything either.

Here is what appears when I type the printenv command, if that helps:

SHELL=/bin/bash
SESSION_MANAGER=local/pop-os:@/tmp/.ICE-unix/2135,unix/pop-os:/tmp/.ICE-unix/2135
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-pop:/etc/xdg
SSH_AGENT_LAUNCHER=gnome-keyring
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GTK_IM_MODULE=ibus
LANGUAGE=cs:en
LC_ADDRESS=cs_CZ.UTF-8
GNOME_SHELL_SESSION_MODE=pop
LC_NAME=cs_CZ.UTF-8
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XMODIFIERS=@im=ibus
DESKTOP_SESSION=pop
LC_MONETARY=cs_CZ.UTF-8
GTK_MODULES=gail:atk-bridge:appmenu-gtk-module
PWD=/home/misapc/.var/app/com.valvesoftware.Steam/.local/share/.shatteredpixel
LOGNAME=misapc
XDG_SESSION_DESKTOP=pop
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
SYSTEMD_EXEC_PID=3345
XAUTHORITY=/run/user/1000/gdm/Xauthority
WINDOWPATH=2
HOME=/home/misapc
USERNAME=misapc
LC_PAPER=cs_CZ.UTF-8
LANG=cs_CZ.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=pop:GNOME
VTE_VERSION=6402
G_ENABLE_DIAGNOSTIC=0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/8c74b5db_7337_4863_8de5_fe262166f683
INVOCATION_ID=65e0d967886f4cf48238c38324e08127
MANAGERPID=1794
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LC_IDENTIFICATION=cs_CZ.UTF-8
LESSOPEN=| /usr/bin/lesspipe %s
USER=misapc
GNOME_TERMINAL_SERVICE=:1.90
DISPLAY=:1
SHLVL=1
LC_TELEPHONE=cs_CZ.UTF-8
QT_IM_MODULE=ibus
LC_MEASUREMENT=cs_CZ.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=cs_CZ.UTF-8
JOURNAL_STREAM=8:35397
XDG_DATA_DIRS=/usr/share/pop:/home/misapc/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/misapc/.dotnet/tools
GDMSESSION=pop
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
LC_NUMERIC=cs_CZ.UTF-8
_=/usr/bin/printenv

**Comment by 00-Evan** [comment]
Odd, based on the location of that data though it seems that POP!_OS (ro maybe flatpak?) might be doing something where each app is given its own XDG_DATA sandbox, which would explain why syncing cloud data wouldn't work, as the ShatteredPD app itself would have no way to read/write to ~/.var/app/com.valvesoftware.Steam/.local/share/.shatteredpixel, and even if it could it would have no way of knowing that that's where it's supposed to look.

**Comment by YoriMirus** [comment]
Okay I have figured it out. It seems like the flatpak version of steam stores data in a different place than the debian version. On my laptop I had the flatpak version, so the game couldn't find the data. I verified this by downloading the flatpak version of steam through the pop os store on my VM and the game indeed couldn't read the data.

Considering this happens with a specific distribution of steam. It is safe to say this is a bug. Should I open an issue for this?

**Comment by 00-Evan** [comment]
Sure, If nothing else that might help with figuring out what's going on here more fully, and whether Shattered can adjust anything to better work with the flatpak Steam versions.

**Comment by basxto** [comment]
I just wanted to add that `${XDG_DATA_HOME}` doesn’t need to exist. It should only be used if it exists and is not empty, otherwise applications are expected to default to `${HOME}/.local/share`. That’s why `printenv` didn’t contain this environmental variable.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
