### ISSUE TITLE
Rogue class disbalanced

### ISSUE THREAD

**Issue by KOLANICH** [00-Evan/shattered-pixel-dungeon#96]
If rogue finds Horn of Plenty, he can feed it with 4 food rations (3 available on lvl 1 and one can be aval on lvl2) which makes him able to survive w/o food, trading health and satiety for horn full recharge with recharge of the rest of items as bonus. This will allow to upgrade Cloak of Shadows to lvl 10.

**Comment by 00-Evan** [comment]
I am aware that the horn of plenty has significant balance issues, this is jut one example of that.

Please send none-technical suggestions to my email, this place is for technical suggestions and bug reports
