### ISSUE TITLE
Cursed Upgrade bug

### ISSUE THREAD

**Issue by feazeyu** [00-Evan/shattered-pixel-dungeon#960]
As the description says, you shouldn't be able to stack them, however, after upgrading my platemail of repulsion to +6, I used 2 cursed ups and got to +8.
That's not all, first, I got a curse that teleports enemies, then slime and after another one got plants.
Occasionally, the slime and teleportation curse would trigger alongside the plants, implying they were still there, but the description doesnt say anything about stacking curses

**Comment by 00-Evan** [comment]
Curse infusion was buffed in 1.2.0, it can now boost by +2 or even +3 if the base level is high enough.

The overgrowth curse triggers all plant effects, including fadeleaf (teleportation). and Sorrowmoss (poison)

**Comment by feazeyu** [comment]
By slime i dont mean poison, I mean the corrosive slime Goo and fetid rat inflict upon you
