### ISSUE TITLE
Android key binding configuration for gamepads

### ISSUE THREAD

**Issue by basxto** [00-Evan/shattered-pixel-dungeon#961]
On android I had issues with configuring key bindings for my connected game pad.
The settings for key binding configuration were only available when a keyboard was connected.
So I had to connect game pad and keyboard with a USB hub in order to change the game pad bindings.

Version: 1.2.3

**Comment by 00-Evan** [comment]
I'm planning to make some adjustments to the settings menu in 1.3.0, which will include separate bindings pages for keyboard and controller.

**Comment by 00-Evan** [comment]
separate bindings window added in commit 8653439a4ff90cbc94c1b715de914f2481b850b1
