### ISSUE TITLE
Test Subject+2 + Scroll of Divination Only heals 9 health

### ISSUE THREAD

**Issue by RaymondDashWu** [00-Evan/shattered-pixel-dungeon#963]
# Expected behavior
Reading a Scroll of Divination with the talent Test Subject+2 should heal for a total of 12 health (4 new items discovered * 3 hp per).

# Actual behavior
Heals for 9 hp. For whatever reason, the last item doesn't seem to be counted. Possibly happens with Test Subject+1 as well only healing for 6.

**Comment by 00-Evan** [comment]
One or two of the things IDed by divination are rings. When you ID rings through divination, you're identifying the type of ring, not any ring in particular (they can still have their own properties like curses/upgrades), so you don't get a proc of the on-identify talents from them.
