### ISSUE TITLE
[Suggestion] Option to add more quickslots

### ISSUE THREAD

**Issue by BloodRaven0** [00-Evan/shattered-pixel-dungeon#967]
I think 6 slots are sometimes not enough for all the wands, thrown weapons, artifacts, armor abilities, and consumables that the player can find around the dungeon and might want to have quick access to.
Rummaging around the inventory looking for the item you want to use only slows down gameplay, while there is clearly enough room for more quickslots, especially on phones with larger screens and on the PC version. To prevent obscuring the screen too much when the player doesn't need the slots, I have two proposals (both could be available in the settings menu):

1. A slider in the options menu that could increase or decrease the amount of quickslots.
2. A setting (possibly "0" on the slider) that automatically scales the quickbar size by the slots used - there will always be one more open slot to put an item in, after which another slot will be made available.

Speaking of the PC version, there is a ton of screen real estate for more quickslots along the bottom of the screen, between the hero's health bar and the inventory. This depends on the screen resolution of course, but most PC's run at 720p or above, which is still enough.

**Comment by 00-Evan** [comment]
I don't want the player to have quick access to their entire inventory, especially if it would further clutter the UI.  Not all devices have enough real-estate for even 6 slots, some devices only show 4, and I'm currently looking into ways to extend that a bit so everyone has access to the full 6. Considering that the original game had just two slots, six is a good maximum for Shattered I feel.

it's worth noting that bags can be quickslotted to access a quick-use menu for their contents, you can also long-press the inventory to get a quick-use window for all your items. On desktop, items can be right-clicked to quickly access their use options, or middle-clicked to use them as if they were in a quickslot.

**Comment by BloodRaven0** [comment]
I see, I hadn't considered portrait mode, where slots really are limited to 4.
I don't see why slots should be limited to 6, just because the original PD had 2 though. 2 were extremely limited and frustrating. The more the merrier, we're not forcing players to use them (the default could be left at 6), just giving them options. Options are always nice.
Maybe a maximum length of the quickbar could be defined (for example it would be different between a phone's portrait and landscape modes), and if the slots selected in the settings exceed that length, then the quickbar would be made scrollable - by tap swiping on touchscreens and scollwheel on PC.

**Comment by 00-Evan** [comment]
Aside from the UI, more quickslots adds complexity burden. More items ready to go at one time makes any given encounter more complicated because there are more immediate options. This is a major reason why I've put so much work into alchemy recipes (e.g. arcane resin); they directly help to streamline gameplay (fewer items) without actually taking any items or effects out of the game.

This is why I've been very hesitant to add more slots, only finally going up to 6 in v1.2.0 after years of requests.

(apologies, meant to close this issue with my first comment. I'm happy to continue discussing this but have no plans to add more slots atm)
