### ISSUE TITLE
Class-specific item (warrior and mage) not properly equiped on new game

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#97]
I believe this bug started at 0.3.5 or so.

The warrior and mage have class-specific "add-on" items. The warrior's seal is attached onto armor, and the mage's wand of magic missile is infused into the staff.

On the first game under mage, the wand is not infused into the staff. When you start another game, the wand is still not infused. After infusing the wand once, all future games will spawn with a staff of magic missile.

The same thing happens with the warrior's seal. (Though I haven't tested starting a new game without attaching the seal)

**Comment by 00-Evan** [comment]
This is intended, it is a sort of tutorial meant to demonstrate the functionality of imbuing wands or affixing the seal.
