### ISSUE TITLE
Giant Crab does not block on loading save

### ISSUE THREAD

**Issue by lilwhitemouse** [00-Evan/shattered-pixel-dungeon#975]
What happens:

1. I attack the Crab after it comes thru a door - it does not block
2. I save the game, quit to main menu
3. I reload the game
4. I attack the Crab - it does not block(!)
5. Go to step 2; the Crab never blocks

Maybe it needs a status "Sees the player./n/nThe Crab will block the next attack..."?

**Comment by 00-Evan** [comment]
fixed in commit fc705449052e2d99a14821a738aa9ae8df8681e5
