### ISSUE TITLE
Wild magic self-zapping

### ISSUE THREAD

**Issue by Dimedime-d** [00-Evan/shattered-pixel-dungeon#977]
See recording. In the first Wild Magic, I tapped the space to the right of the Evil Eye, and in the second Wild Magic, I tapped on the Evil Eye.

https://user-images.githubusercontent.com/73413313/167256162-b1cbdcb5-3342-4a69-a275-0051b0d6d73f.mp4

I had 1 wand of lightning + 2 wands of prismatic light, so I could zap and blind myself.

The ability does stop you from targeting yourself when you tap yourself, but it seems you can still zap yourself if your path to target happens to be obstructed by a wall next to you

**Comment by 00-Evan** [comment]
This is intentional. I flip-flopped on this during development but ended up deciding to allow it as the alternative is stopping the ability at seemingly arbitrary moments, as several wands have different targeting behavior.
