### ISSUE TITLE
Deep Sleep not so deep

### ISSUE THREAD

**Issue by Lonestick** [00-Evan/shattered-pixel-dungeon#978]
https://user-images.githubusercontent.com/79112244/167609756-888c255c-fd33-40be-8aec-13da03b265cc.mp4

I think they also wake up when out of sight for a while it happened when i was farming in a garden room.

**Comment by Lonestick** [comment]
![Screenshot_20220510-184253](https://user-images.githubusercontent.com/79112244/167611160-abfe842d-fd6a-4a60-951a-6e32d1003722.jpg)
I fadeleafed back a floor.

**Comment by 00-Evan** [comment]
Do you have the amulet of Yendor? All enemies are attracted to the hero's position if they are in possession of the amulet, and this does wake up sleeping enemies.

**Comment by 00-Evan** [comment]
I realized I'm silly and could just look at the video. You did indeed have the amulet, so this is intended behavior.
