### ISSUE TITLE
Lack of a guide on how to compile iOS(might get rejected)

### ISSUE THREAD

**Issue by TextualMold9830** [00-Evan/shattered-pixel-dungeon#980]
There is no specific guide on how to compile for iOS. I got faced with many issues most of them I solved. The one that is bugging me is OpenGLES/OpenGLES.h not found in prefix file. I googled for the file didn't found it. My suggestion is to migrate to metal or atleast provide the OpenGLES.h

**Comment by 00-Evan** [comment]
There is a readme for iOS here, though it is much less comprehensive than other platforms: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/docs/getting-started-ios.md

You shouldn't need to add any code to the game itself to compile for iOS (I compile with the exact code you see here on github), the real trouble is with apple's build tools, developer certificates, etc.

Metal migration is not possible at the moment as libGDX does not support it.

**Comment by TextualMold9830** [comment]
I can make my own guide. It would help a lot of people

**Comment by TextualMold9830** [comment]
My only problem is OpenGLES in Xcode it says OpenGLES/OpenGLES.h not found.  I'd love some help with that

**Comment by 00-Evan** [comment]
Shattered is not compiled through xcode, its compiled through RoboVM via Android Studio or Intellij. You need to set up an xcode project initially, but do not compile through it. Look over the guide I linked in the getting started page (and the earlier 2019 version, which is linked in the 2020 post).

**Comment by TextualMold9830** [comment]
I compiled with robovm no changes done to sdk or game and when I open the app on my iPhone 6+ iOS 12 it crashes.

**Comment by TextualMold9830** [comment]
0:26:17.087 2022-05-21 20:26:17.086 ibtoold[4864:281222] DEBUG: Added to environment: {
[ERROR] 20:26:17.087     TMPDIR = "/var/folders/fy/5kq73c4s2mgfs66hhjppsgw80000gn/T/73077359-1066-418E-80E4-8099B2CE706A";
[ERROR] 20:26:17.087 }
[WARNING] 20:26:24.333 warning: no debug symbols in executable (-arch arm64) the errors I get when I compile with robovm in Android studio and I did put my own bundle identifier and.  provisioning profile.

**Comment by 00-Evan** [comment]
I'm afraid I don't know how to help you with that specific error, my knowledge on the iOS build process is limited so unless it's something I encountered specifically I won't be much help.
