### ISSUE TITLE
Cached Rations in crystal key room

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#981]
In some cases the Cached Rations chests may spawn in one of the Crystal Choice Rooms making them sometimes unavailable. They should not spawn behind one of the crystal doors.

**Comment by 00-Evan** [comment]
After double checking this I can confirm that cached rations already cannot spawn inside these rooms. The game avoids placing them anywhere where there is special floor, water, or a pedestal.

**Comment by LeahLuong** [comment]
I have found cached rations on the far side of a trap room, next to the chest there. Kinda silly the rogue would stash his future food in such a place but I guess you can never be too protective of your snacks.

**Comment by Pr0methean** [comment]
Maybe OP is counting as a "crystal key room" those rooms that can only be reached by jumping off a chasm on the previous floor.

**Comment by LeahLuong** [comment]
@Pr0methean I realize this but there is a corner case where these rations would be inaccessible @ the time the player can see them: the trap room's key item (levitation) is behind a locked door, the trap room's item is an iron key, & the player has already spent an iron key opening the wrong door. Unless the player has an alternate means of traversing the trap room, they'll have no choice but to ignore that food until they are properly prepared to secure it. It begs the question of how the rogue cached those rations (& why there) in the same way as the OP.
