### ISSUE TITLE
Ring of Might is ignored after death

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#982]
When you die while wearing a Ring of Might only your original Strength is shown and weapons or armor have a red Stength requirement, even if you could use them without drawbacks with your current strength. 
![Screenshot_2022-05-14-21-21-08-313_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/168445669-16845781-6e6d-4344-9857-5452b599898b.jpg)
![Screenshot_2022-05-14-21-21-13-358_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/168445671-f3cb1544-0b28-45d3-a42a-38069e4bd5a2.jpg)

**Comment by 00-Evan** [comment]
That is correct. You are dead and therefore not benefiting from the ring's strength boost anymore.
