### ISSUE TITLE
Ring of Might Bug

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#985]
Ring of Might's bonus maxHP is not applied when I load a save while having Degrade debuff.
I added some items for testing, but other than that, it is the same as the release version.
![image](https://user-images.githubusercontent.com/76470428/169635607-0fef9512-37f4-4e1c-950b-82c46245cc6d.png)
^ before loading save
![image](https://user-images.githubusercontent.com/76470428/169635595-13897534-3649-40d0-ba52-3978b2d61e94.png)
^ after loading save

**Comment by 00-Evan** [comment]
fixed in commit 0690524ea70d6295f740644a84823e8837cda16e
