### ISSUE TITLE
Teleportation Trap + Wand of Warding glitch

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#986]
I placed a ward and triggered a hidden teleportation trap this way. I was teleported and the message “The teleportation magic failed” appeared. I guess that this message appeared, because the ward could not be teleported. However, I did not expect that the player is also teleported.

**Comment by spixi** [comment]
![Uploading Screenshot_2022-05-21-18-16-51-762_com.shatteredpixel.shatteredpixeldungeon.jpg…]()

**Comment by spixi** [comment]
![Screenshot_2022-05-21-18-16-51-762_com shatteredpixel shatteredpixeldungeon](https://user-images.githubusercontent.com/3192596/169662341-ba56d4ae-258c-43a3-9ceb-6a478071709b.jpg)

**Comment by 00-Evan** [comment]
Teleportation traps trigger in a 3x3 AOE, so this looks correct to me. You triggered the trap, it teleported you as you were next to it, and failed to teleport the ward as wards are immovable.
