### ISSUE TITLE
Option to increase game/animation speed

### ISSUE THREAD

**Issue by WhitePhant0m** [00-Evan/shattered-pixel-dungeon#987]
I'd like to see a way to increase game/animation speed being added.
Traveling and combat can take a while time sometimes and it'd be nice if there was a way to speed that up.
Combat especially can take a long time if there are multiple enemies.
I think 2x speed would be fast enough, at least that's the speed I've been using through CEs speedhack feature for now.

While I could keep doing it the way I'm doing it right now, I'd like to see this feature on mobile as well, and I think other users would probably like this as a feature too.

**Comment by 00-Evan** [comment]
I've tried to tune the game to run at the reasonably fastest speed it can already, so I'd rather not add an option to make it run even faster. I imagine such a setting also wouldn't see much usage, people who speedrun shattered seem to be plenty fine with the current game speed, and you can't really get more demanding on game speed than that. There's also a decent chance that I will add a challenge with a real-time component in the future, which would only make a higher speed more undesirable.
