### ISSUE TITLE
request: blue outline the level after magic map use

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#988]
Sometimes when I read a foresight scroll, faint blue shadows appear around the map in locations where it has been revealed. This effect helps me remember where I have already explored.  Can a similar affect mark the levels where a magic map has already been read?  I find it difficult to remember which levels I have used a magic map on and think this simple tweak would help me remember.

**Comment by 00-Evan** [comment]
You should be able to just leave a small amount of a level unexplored after using magic mapping. That's already what's happening with foresight, you're magic mapping an area but not directly exploring it fully.

**Comment by protective1** [comment]
Oftentimes I'm reading the magic map after I've already explored the level (because I suspect I've missed a secret room).  Then I come back to play later, and read another magic map on the same level because I forgot I've already done that before.
