### ISSUE TITLE
Blandfruit + sunweed = poison?

### ISSUE THREAD

**Issue by andreasmjg** [00-Evan/shattered-pixel-dungeon#989]
Hi,

In the Pharmacophobia challenge, the blandfruit + sunweed (green seed) doesn't heal but poisons.

I think this should not be the case as it states healing potions and things based on healing potions will cause poison in the challenge.

IMJ blandfruit + green seed has nothing to do with healing potion / pharmacy, it's more like a herbal remedy, so should be healing, not poisoning.

**Comment by andreasmjg** [comment]
![Screenshot_20220526-182709_Shattered_Pixel_Dungeon](https://user-images.githubusercontent.com/34312687/170543342-8e3c35eb-3e41-479c-90b1-c6931b46fabc.png)

;-(

**Comment by 00-Evan** [comment]
Unfortunately this is intended. Sunfruit is equivalent to a potion of healing, which means it will harm you if you have pharma enabled. I'll see about mentioning Sunfruit in the challenge's description.

**Comment by andreasmjg** [comment]
Got it, thanks for the quick reply!
