### ISSUE TITLE
Mage's staff can be obtained from well of transmutation

### ISSUE THREAD

**Issue by un-logic** [00-Evan/shattered-pixel-dungeon#99]
In 0.4.0 when playing for Rogue if one would obtain Mage's wand (via transmutation) and imbue it with some other staff's magic this will cause game to crash on every attempt to move to another depth level.

**Comment by 00-Evan** [comment]
you should not have a way to attain the mage's staff as the rogue, how did you do that?

**Comment by un-logic** [comment]
Updated my comment: well of transmutation.

**Comment by 00-Evan** [comment]
getting the mage's staff from a well of transmutation should not be possible, will fix that.

**Comment by un-logic** [comment]
That's sad, but I guess this situation isn't unique to Mage's wand.
Also why should it crash the game anyways? I've obtained it at depth 2 or something, reached depth 9 and it was a OK, but somehow imbuing ruins everything. That's just property of an item why so serious?

**Comment by 00-Evan** [comment]
unsure, if you're crashing then please send a crash report from the popup that appears when the game crashes, that'll tell me exactly why the crash is happening.

**Comment by un-logic** [comment]
I'm using F-droid build and it doesn't show up any crash report, just plain 'Application %name% crashed' error followed by game restart. It is crashing upon depth change but only if Mage's wand was previously imbued during the run on previous depth level. Is there anything I can do to test it more thoroughly?

**Comment by LegitPsycho** [comment]
I also got a Mage's Staff as a Warrior by throwing starting weapon into well of transmutation.

**Comment by 00-Evan** [comment]
fixed in commit 97f354c342de5065c32be0b99fbe373ed91c3030
