### ISSUE TITLE
soul mark ended immediately

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#990]
I have empowering scrolls+2 talent.  I read the unstable scroll to activate this talent.  I shot the dwarf king with an empowered lightning wand.  A monster (I think it was the monk) said "soul mark",  but in the next turn was immediately not soul marked.
![Screenshot_20220527-184526](https://user-images.githubusercontent.com/8593007/170798089-5559c4b4-e198-46f7-8023-c7c7f941ee97.png)

The ghoul that is down was already down from melee hits before this event occurred.  The monk was one square either left or upper left before this turn.

**Comment by 00-Evan** [comment]
I'm not able to reproduce this. Soul mark's minimum duration is 10 turns, regardless of the wand's level. Was the monk life linked or similar? It's possible that DK used his life link ability and you mistook the "life link" text for "soul mark" in the moment.
