### ISSUE TITLE
request: Pinephone Support

### ISSUE THREAD

**Issue by bakerk98** [00-Evan/shattered-pixel-dungeon#991]
Is there any chance for a Pinephone port? It runs on ARM64 architecture 

https://www.pine64.org/pinephone/

**Comment by 00-Evan** [comment]
I'm not interested in creating an official pinephone distribution, but Shattered does already work on arm64 linux through the .jar version.

**Comment by bakerk98** [comment]
Fair enough! Thanks for the quick reply tho lol
