### ISSUE TITLE
About the Battlemage's Mystical Charge talent

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#992]
I checked the Battlemage's Mystical Charge talent grants 4 turns of artifact recharge effect regardless of level of the talent.

https://github.com/00-Evan/shattered-pixel-dungeon/blob/83452db0e0596e81ed75199f645a5100fe70b9cd/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/weapon/melee/MagesStaff.java#L163-L170

I think it is unintended, right?

**Comment by 00-Evan** [comment]
fixed in commit 59ca2f4790fa36f4c9c9dc9dafd4fb567c71f286
