### ISSUE TITLE
lullaby monsters don't stay asleep

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#994]
I used a scroll of lullaby to put monsters (on the other side of crystal door) to sleep.  However, they woke up when I did.  Aren't they supposed to stay asleep if I don't attack them?
![Screenshot_20220602-182145](https://user-images.githubusercontent.com/8593007/171862626-82240f27-7983-41d6-b5b7-678ea7fe1e9e.png)
![Screenshot_20220602-182155](https://user-images.githubusercontent.com/8593007/171862642-88816aa8-c332-4582-abe1-61f2b22b87a2.png)

**Comment by protective1** [comment]
And btw, I don't have the amulet.

**Comment by 00-Evan** [comment]
Is swarm intelligence among the challenges that you have enabled? That challenge alerts nearby enemies when another one sees you, and that 'alert' is able to wake sleeping enemies.

**Comment by protective1** [comment]
Yes - swarm intelligence is on.  Thanks for explaining.
