### ISSUE TITLE
Dwarf king no weapon badge 

### ISSUE THREAD

**Issue by betacon** [00-Evan/shattered-pixel-dungeon#998]
![Shattered Pixel Dungeon_2022-06-27-02-26-47.jpg](https://user-images.githubusercontent.com/16593263/175828866-af6d95e8-edab-40f7-98f1-b2587dc3e42b.jpg)

![Shattered Pixel Dungeon_2022-06-27-02-27-35.jpg](https://user-images.githubusercontent.com/16593263/175828906-ed6f23c3-18ab-407d-9ea0-5d07b1e51849.jpg)

I used the wand at 20th floor, before entering the king's room.

During the fight, I just used my bare hand with gladiator skills.

AND IT DOESN'T COUNT???

**Comment by 00-Evan** [comment]
Fists and combo moves both count as directly attacking DK.
